# Getting Started {#getting-started}

Before we can start looking at data, there are some key concepts to understand first

* What are R and RStudio?
* How do I use R and RStudio?
* What are R packages?

If you are already somewhat familiar with the above, then you may proceed to Chapter 




An introduction to using R, RStudio, and R Markdown is also available in a free book [here](http://ismayc.github.io/rbasics-book) [@usedtor2016].  It is recommended that you refer back to this book frequently as it has GIF screen recordings that you can follow along with as you learn.



## What you need to do to get started

* DataCamp [Intro to R](https://www.datacamp.com/courses/free-introduction-to-r) course
* Packages: Packages in R are supplemental functions and data that aren't automatically loaded at start-up. Use `LC.Rmd` Lec01 R Scripts and Lec02 R Packages
    + Installing them by download and updating them
    + loading them via `library()`


We will keep a running list of R packages you will need to have installed to complete the analysis as well here in the `needed_pkgs` character vector.  You can check if you have all of the needed packages installed by running all of the lines below in the next chunk of R code.  The last lines including the `if` will install them as needed (i.e., download their needed files from the internet to your hard drive and install them for your use).

You can run the `library` function on them to load them into your current analysis.  Prior to each analysis where a package is needed, you will see the corresponding `library` function in the text.  Make sure to check the top of the chapter to see if a package was loaded there.

```{r, warning=FALSE, message=FALSE, results='hide'}
needed_pkgs <- c("nycflights13", "tibble", "dplyr", "ggplot2", "knitr", 
  "okcupiddata", "dygraphs", "rmarkdown", "mosaic", 
  "ggplot2movies", "fivethirtyeight", "readr")

new.pkgs <- needed_pkgs[!(needed_pkgs %in% installed.packages())]

if(length(new.pkgs)) {
  install.packages(new.pkgs, repos = "http://cran.rstudio.com")
}
```





### Three driving data sources

Throughout this book, we focus on only a few data sources:  

- flights leaving New York City in 2013
- profiles of OKCupid users in San Francisco
- IMDB movie ratings

By focusing on a few large data sources, it is our hope that you'll be able to see how each of the chapters is interconnected.  You'll see how the data being "tidy" (See Chapter \@ref(tidy)) leads into data visualization and manipulation in exploratory data analysis and how those concepts tie into inference and regression.


Now let's get into learning about how to create good stories about and with data!

