<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An open-source and fully-reproducible electronic textbook for teaching statistical inference using tidyverse data science tools.">

<title>3&nbsp; Data Wrangling – Statistical Inference via Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-tidy.html" rel="next">
<link href="./02-visualization.html" rel="prev">
<link href="./images/logos/favicons/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-36bf55b16c7cb4b1420f41495cb5446a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-4e061325f75ba7fba053004d9d2e9411.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-36bf55b16c7cb4b1420f41495cb5446a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-YVFBK9P73R"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YVFBK9P73R');
</script>

<!-- Open Graph Meta Tags -->
<meta property="og:title" content="3&nbsp; Data Wrangling – Statistical Inference via Data Science">
<meta property="og:description" content="An open-source and fully-reproducible electronic textbook for teaching statistical inference using tidyverse data science tools.">
<meta property="og:image" content="https://moderndive.com/v2/images/logos/v2_cover.jpg">
<meta property="og:url" content="https://moderndive.com/v2/">
<meta name="twitter:card" content="summary_large_image">

<!-- Set up favicon -->
<link rel="icon" href="images/logos/favicons/favicon.ico" type="image/x-icon">

<!-- Redirect to ModernDive V2 -->
<script>
  if (window.location.pathname === '/v2') {
    window.location.replace(window.location.pathname + '/');
  }
</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-visualization.html">Data Science with tidyverse</a></li><li class="breadcrumb-item"><a href="./03-wrangling.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Wrangling</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Inference via Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/moderndive/ModernDive_book/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome to ModernDive (v2)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-foreword.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foreword</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with Data in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data Science with tidyverse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-wrangling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-tidy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Importing and Tidy Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Modeling with moderndive</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Inference with infer</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estimation, Confidence Intervals, and Bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-inference-for-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Inference for Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Conclusion</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-tell-your-story-with-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Tell Your Story with Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./91-appendixA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Statistical Background</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./92-appendixB.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Inference Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./93-appendixC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Tips and Tricks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./94-appendixD.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Learning Check Solutions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./95-appendixE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">The Theory Behind the Bootstrap Method</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-wrangling-packages" id="toc-sec-wrangling-packages" class="nav-link active" data-scroll-target="#sec-wrangling-packages">Needed packages</a></li>
  <li><a href="#sec-piping" id="toc-sec-piping" class="nav-link" data-scroll-target="#sec-piping"><span class="header-section-number">3.1</span> The pipe operator: <code>|&gt;</code></a></li>
  <li><a href="#sec-filter" id="toc-sec-filter" class="nav-link" data-scroll-target="#sec-filter"><span class="header-section-number">3.2</span> <code>filter</code> rows</a></li>
  <li><a href="#sec-summarize" id="toc-sec-summarize" class="nav-link" data-scroll-target="#sec-summarize"><span class="header-section-number">3.3</span> <code>summarize</code> variables</a></li>
  <li><a href="#sec-groupby" id="toc-sec-groupby" class="nav-link" data-scroll-target="#sec-groupby"><span class="header-section-number">3.4</span> <code>group_by</code> rows</a></li>
  <li><a href="#sec-mutate" id="toc-sec-mutate" class="nav-link" data-scroll-target="#sec-mutate"><span class="header-section-number">3.5</span> <code>mutate</code> existing variables</a></li>
  <li><a href="#sec-arrange" id="toc-sec-arrange" class="nav-link" data-scroll-target="#sec-arrange"><span class="header-section-number">3.6</span> <code>arrange</code> and sort rows</a></li>
  <li><a href="#sec-joins" id="toc-sec-joins" class="nav-link" data-scroll-target="#sec-joins"><span class="header-section-number">3.7</span> <code>join</code> data frames</a>
  <ul class="collapse">
  <li><a href="#matching-key-variable-names" id="toc-matching-key-variable-names" class="nav-link" data-scroll-target="#matching-key-variable-names"><span class="header-section-number">3.7.1</span> Matching key variable names</a></li>
  <li><a href="#sec-diff-key" id="toc-sec-diff-key" class="nav-link" data-scroll-target="#sec-diff-key"><span class="header-section-number">3.7.2</span> Different key variable names</a></li>
  <li><a href="#multiple-key-variables" id="toc-multiple-key-variables" class="nav-link" data-scroll-target="#multiple-key-variables"><span class="header-section-number">3.7.3</span> Multiple key variables</a></li>
  <li><a href="#sec-normal-forms" id="toc-sec-normal-forms" class="nav-link" data-scroll-target="#sec-normal-forms"><span class="header-section-number">3.7.4</span> Normal forms</a></li>
  </ul></li>
  <li><a href="#sec-other-verbs" id="toc-sec-other-verbs" class="nav-link" data-scroll-target="#sec-other-verbs"><span class="header-section-number">3.8</span> Other verbs</a>
  <ul class="collapse">
  <li><a href="#sec-select" id="toc-sec-select" class="nav-link" data-scroll-target="#sec-select"><span class="header-section-number">3.8.1</span> <code>select</code> variables</a></li>
  <li><a href="#sec-relocate" id="toc-sec-relocate" class="nav-link" data-scroll-target="#sec-relocate"><span class="header-section-number">3.8.2</span> <code>relocate</code> variables</a></li>
  <li><a href="#sec-rename" id="toc-sec-rename" class="nav-link" data-scroll-target="#sec-rename"><span class="header-section-number">3.8.3</span> <code>rename</code> variables</a></li>
  <li><a href="#top_n-values-of-a-variable" id="toc-top_n-values-of-a-variable" class="nav-link" data-scroll-target="#top_n-values-of-a-variable"><span class="header-section-number">3.8.4</span> <code>top_n</code> values of a variable</a></li>
  </ul></li>
  <li><a href="#sec-wrangling-conclusion" id="toc-sec-wrangling-conclusion" class="nav-link" data-scroll-target="#sec-wrangling-conclusion"><span class="header-section-number">3.9</span> Conclusion</a>
  <ul class="collapse">
  <li><a href="#summary-table" id="toc-summary-table" class="nav-link" data-scroll-target="#summary-table"><span class="header-section-number">3.9.1</span> Summary table</a></li>
  <li><a href="#additional-resources" id="toc-additional-resources" class="nav-link" data-scroll-target="#additional-resources"><span class="header-section-number">3.9.2</span> Additional resources</a></li>
  <li><a href="#whats-to-come" id="toc-whats-to-come" class="nav-link" data-scroll-target="#whats-to-come"><span class="header-section-number">3.9.3</span> What’s to come?</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/moderndive/ModernDive_book/edit/v2/03-wrangling.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/moderndive/ModernDive_book/blob/v2/03-wrangling.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/moderndive/ModernDive_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<img src="https://moderndive.com/wide_format.png" alt="ModernDive" style="max-width: 100%; width: 100%; height: auto; display: block; margin: 0 auto; padding-top: 10px;">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-visualization.html">Data Science with tidyverse</a></li><li class="breadcrumb-item"><a href="./03-wrangling.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Wrangling</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-wrangling" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>So far in our journey, we’ve seen how to look at data saved in data frames using the <code>glimpse()</code> and <code>View()</code> functions in <a href="01-getting-started.html" class="quarto-xref"><span>Chapter 1</span></a>, and how to create data visualizations using the <code>ggplot2</code> package in <a href="02-visualization.html" class="quarto-xref"><span>Chapter 2</span></a>. In particular, we studied what we term the “five named graphs” (5NG):</p>
<ol type="1">
<li>scatterplots via <code>geom_point()</code></li>
<li>linegraphs via <code>geom_line()</code></li>
<li>boxplots via <code>geom_boxplot()</code></li>
<li>histograms via <code>geom_histogram()</code></li>
<li>barplots via <code>geom_bar()</code> or <code>geom_col()</code></li>
</ol>
<p>We created these visualizations using the grammar of graphics, which maps variables in a data frame to the aesthetic attributes of one of the 5 <code>geom</code>etric objects. We can also control other aesthetic attributes of the geometric objects such as the size and color as seen in the Gapminder data example in <a href="02-visualization.html#fig-gapminder" class="quarto-xref">Figure&nbsp;<span>2.1</span></a>.</p>
<p>In this chapter, we’ll introduce a series of functions from the <code>dplyr</code> package for data wrangling that will allow you to take a data frame and “wrangle” it (transform it) to suit your needs. Such functions include:</p>
<ol type="1">
<li><code>filter()</code> a data frame’s existing rows to only pick out a subset of them. For example, the <code>alaska_flights</code> data frame.</li>
<li><code>summarize()</code> one or more of its columns/variables with a <em>summary statistic</em>. Examples of summary statistics include the median and interquartile range of temperatures as we saw in <a href="02-visualization.html#sec-boxplots" class="quarto-xref"><span>Section 2.7</span></a> on boxplots.</li>
<li><code>group_by()</code> its rows. In other words, assign different rows to be part of the same <em>group</em>. We can then combine <code>group_by()</code> with <code>summarize()</code> to report summary statistics for each group <em>separately</em>. For example, say you don’t want a single overall average departure delay <code>dep_delay</code> for all three <code>origin</code> airports combined, but rather three separate average departure delays, one computed for each of the three <code>origin</code> airports.</li>
<li><code>mutate()</code> its existing columns/variables to create new ones. For example, convert hourly temperature readings from Fahrenheit to Celsius.</li>
<li><code>arrange()</code> its rows. For example, sort the rows of <code>weather</code> in ascending or descending order of <code>temp</code>.</li>
<li><code>join()</code> it with another data frame by matching along a “key” variable. In other words, merge these two data frames together.</li>
</ol>
<p>Notice how we used <code>computer_code</code> font to describe the actions we want to take on our data frames. This is because the <code>dplyr</code> package for data wrangling has intuitively verb-named functions that are easy to remember.</p>
<p>There is a further benefit to learning to use the <code>dplyr</code> package for data wrangling: its similarity to the database querying language <a href="https://en.wikipedia.org/wiki/SQL">SQL</a> (pronounced “sequel” or spelled out as “S-Q-L”). SQL (which stands for “Structured Query Language”) is used to manage large databases quickly and efficiently and is widely used by many institutions with a lot of data. While SQL is a topic left for a book or a course on database management, keep in mind that once you learn <code>dplyr</code>, you can learn SQL easily. We’ll talk more about their similarities in <a href="#sec-normal-forms" class="quarto-xref"><span>Section 3.7.4</span></a>.</p>
<section id="sec-wrangling-packages" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="sec-wrangling-packages">Needed packages</h3>
<p>Let’s load all the packages needed for this chapter (this assumes you’ve already installed them). If needed, read <a href="01-getting-started.html#sec-packages" class="quarto-xref"><span>Section 1.3</span></a> for information on how to install and load R packages.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nycflights23)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="sec-piping" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-piping"><span class="header-section-number">3.1</span> The pipe operator: <code>|&gt;</code></h2>
<p>Before we start data wrangling, let’s first introduce a nifty tool that has been a part of R since May 2021: the native pipe operator <code>|&gt;</code>. The pipe operator allows us to combine multiple operations in R into a single sequential <em>chain</em> of actions. In modern R, the native pipe operator <code>|&gt;</code> is now the default for chaining functions, replacing the previously common tidyverse pipe (<code>%&gt;%</code>) that was loaded with the <code>dplyr</code> package. Introduced in R 4.1.0 in May 2021, <code>|&gt;</code> offers a more intuitive and readable syntax for data wrangling and other tasks, eliminating the need for additional package dependencies.</p>
<p>You’ll still often see R code using <code>%&gt;%</code> in older scripts or searches online, but we’ll use <code>|&gt;</code> in this book. The tidyverse pipe still works, so don’t worry if you see it in other code.</p>
<p>Let’s start with a hypothetical example. Say you would like to perform a hypothetical sequence of operations on a hypothetical data frame <code>x</code> using hypothetical functions <code>f()</code>, <code>g()</code>, and <code>h()</code>:</p>
<ol type="1">
<li>Take <code>x</code> <em>then</em></li>
<li>Use <code>x</code> as an input to a function <code>f()</code> <em>then</em></li>
<li>Use the output of <code>f(x)</code> as an input to a function <code>g()</code> <em>then</em></li>
<li>Use the output of <code>g(f(x))</code> as an input to a function <code>h()</code></li>
</ol>
<p>One way to achieve this sequence of operations is by using nesting parentheses as follows:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">h</span>(<span class="fu">g</span>(<span class="fu">f</span>(x)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This code isn’t so hard to read since we are applying only three functions: <code>f()</code>, then <code>g()</code>, then <code>h()</code> and each of the functions is short in its name. Further, each of these functions also only has one argument. However, you can imagine that this will get progressively harder to read as the number of functions applied in your sequence increases and the arguments in each function increase as well. This is where the pipe operator <code>|&gt;</code> comes in handy. <code>|&gt;</code> takes the output of one function and then “pipes” it to be the input of the next function. Furthermore, a helpful trick is to read <code>|&gt;</code> as “then” or “and then.” For example, you can obtain the same output as the hypothetical sequence of functions as follows:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">f</span>() <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">g</span>() <span class="sc">|&gt;</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">h</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You would read this sequence as:</p>
<ol type="1">
<li>Take <code>x</code> <em>then</em></li>
<li>Use this output as the input to the next function <code>f()</code> <em>then</em></li>
<li>Use this output as the input to the next function <code>g()</code> <em>then</em></li>
<li>Use this output as the input to the next function <code>h()</code></li>
</ol>
<p>So while both approaches achieve the same goal, the latter is much more human-readable because you can clearly read the sequence of operations line-by-line. But what are the hypothetical <code>x</code>, <code>f()</code>, <code>g()</code>, and <code>h()</code>? Throughout this chapter on data wrangling:</p>
<ol type="1">
<li>The starting value <code>x</code> will be a data frame. For example, the <code>flights</code> data frame we explored in <a href="01-getting-started.html#sec-nycflights" class="quarto-xref"><span>Section 1.4</span></a>.</li>
<li>The sequence of functions, here <code>f()</code>, <code>g()</code>, and <code>h()</code>, will mostly be a sequence of any number of the six data-wrangling verb-named functions we listed in the introduction to this chapter. For example, the <code>filter(carrier == "MQ")</code> function and argument specified we previewed earlier.</li>
<li>The result will be the transformed/modified data frame that you want. In our example, we’ll save the result in a new data frame by using the <code>&lt;-</code> assignment operator with the name <code>alaska_flights</code> via <code>alaska_flights &lt;-</code>.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>envoy_flights <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(carrier <span class="sc">==</span> <span class="st">"AS"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Much like when adding layers to a <code>ggplot()</code> using the <code>+</code> sign, you form a single <em>chain</em> of data wrangling operations by combining verb-named functions into a single sequence using the pipe operator <code>|&gt;</code>. Furthermore, much like how the <code>+</code> sign has to come at the end of lines when constructing plots, the pipe operator <code>|&gt;</code> has to come at the end of lines as well.</p>
<p>Keep in mind, there are many more advanced data-wrangling functions than just the six listed in the introduction to this chapter; you’ll see some examples of these in <a href="#sec-other-verbs" class="quarto-xref"><span>Section 3.8</span></a>. However, just with these six verb-named functions you’ll be able to perform a broad array of data-wrangling tasks for the rest of this book.</p>
</section>
<section id="sec-filter" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-filter"><span class="header-section-number">3.2</span> <code>filter</code> rows</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-filter" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/cheatsheets/filter.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="FIGURE&nbsp;3.1: Diagram of filter() rows operation."><img src="images/cheatsheets/filter.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;3.1: Diagram of filter() rows operation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The <code>filter()</code> function here works much like the “Filter” option in Microsoft Excel; it allows you to specify criteria about the values of a variable in your dataset and then filters out only the rows that match that criteria.</p>
<p>We begin by focusing only on flights from New York City to Phoenix, Arizona. The <code>dest</code> destination code (or airport code) for Phoenix, Arizona is <code>"PHX"</code>. Run the following and look at the results in RStudio’s spreadsheet viewer to ensure that only flights heading to Phoenix are chosen here:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>phoenix_flights <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dest <span class="sc">==</span> <span class="st">"PHX"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(phoenix_flights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note the order of the code. First, take the <code>flights</code> data frame <code>flights</code> <em>then</em> <code>filter()</code> the data frame so that only those where the <code>dest</code> equals <code>"PHX"</code> are included. We test for equality using the double equal sign <code>==</code> and not a single equal sign <code>=</code>. In other words, <code>filter(dest = "PHX")</code> will yield an error. This is a convention across many programming languages. If you are new to coding, you’ll probably forget to use the double equal sign <code>==</code> a few times before you get the hang of it.</p>
<p>You can use other operators beyond just the <code>==</code> operator that tests for equality:</p>
<ul>
<li><code>&gt;</code> corresponds to “greater than”</li>
<li><code>&lt;</code> corresponds to “less than”</li>
<li><code>&gt;=</code> corresponds to “greater than or equal to”</li>
<li><code>&lt;=</code> corresponds to “less than or equal to”</li>
<li><code>!=</code> corresponds to “not equal to.” The <code>!</code> is used in many programming languages to indicate “not.”</li>
</ul>
<p>Furthermore, you can combine multiple criteria using operators that make comparisons:</p>
<ul>
<li><code>|</code> corresponds to “or”</li>
<li><code>&amp;</code> corresponds to “and”</li>
</ul>
<p>To see many of these in action, let’s filter <code>flights</code> for all rows that departed from JFK <em>and</em> were heading to Burlington, Vermont (<code>"BTV"</code>) or Seattle, Washington (<code>"SEA"</code>) <em>and</em> departed in the months of October, November, or December. Run the following:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>btv_sea_flights_fall <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(origin <span class="sc">==</span> <span class="st">"JFK"</span> <span class="sc">&amp;</span> (dest <span class="sc">==</span> <span class="st">"BTV"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"SEA"</span>) <span class="sc">&amp;</span> month <span class="sc">&gt;=</span> <span class="dv">10</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(btv_sea_flights_fall)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that even though colloquially speaking one might say “all flights leaving Burlington, Vermont <em>and</em> Seattle, Washington,” in terms of computer operations, we really mean “all flights leaving Burlington, Vermont <em>or</em> leaving Seattle, Washington.” For a given row in the data, <code>dest</code> can be <code>"BTV"</code>, or <code>"SEA"</code>, or something else, but not both <code>"BTV"</code> and <code>"SEA"</code> at the same time. Furthermore, note the careful use of parentheses around <code>dest == "BTV" | dest == "SEA"</code>.</p>
<p>We can often skip the use of <code>&amp;</code> and just separate our conditions with a comma. The previous code will return the identical output <code>btv_sea_flights_fall</code> as the following code:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>btv_sea_flights_fall <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(origin <span class="sc">==</span> <span class="st">"JFK"</span>, (dest <span class="sc">==</span> <span class="st">"BTV"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"SEA"</span>), month <span class="sc">&gt;=</span> <span class="dv">10</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(btv_sea_flights_fall)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s present another example that uses the <code>!</code> “not” operator to pick rows that <em>don’t</em> match a criteria. As mentioned earlier, the <code>!</code> can be read as “not.” Here we are filtering rows corresponding to flights that didn’t go to Burlington, VT or Seattle, WA.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>not_BTV_SEA <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(dest <span class="sc">==</span> <span class="st">"BTV"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"SEA"</span>))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(not_BTV_SEA)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Again, note the careful use of parentheses around the <code>(dest == "BTV" | dest == "SEA")</code>. If we didn’t use parentheses as follows:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span>dest <span class="sc">==</span> <span class="st">"BTV"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"SEA"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We would be returning all flights not headed to <code>"BTV"</code> <em>or</em> those headed to <code>"SEA"</code>, which is an entirely different resulting data frame.</p>
<p>Now say we have a larger number of airports we want to filter for, say <code>"SEA"</code>, <code>"SFO"</code>, <code>"PHX"</code>, <code>"BTV"</code>, and <code>"BDL"</code>. We could continue to use the <code>|</code> (<em>or</em>) operator.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>many_airports <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dest <span class="sc">==</span> <span class="st">"SEA"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"SFO"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"PHX"</span> <span class="sc">|</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>         dest <span class="sc">==</span> <span class="st">"BTV"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"BDL"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>As we progressively include more airports, this will get unwieldy to write. A slightly shorter approach uses the <code>%in%</code> operator along with the <code>c()</code> function. Recall from <a href="01-getting-started.html#sec-programming-concepts" class="quarto-xref"><span>Section 1.2.1</span></a> that the <code>c()</code> function “combines” or “concatenates” values into a single <em>vector</em> of values. </p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>many_airports <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dest <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"SEA"</span>, <span class="st">"SFO"</span>, <span class="st">"PHX"</span>, <span class="st">"BTV"</span>, <span class="st">"BDL"</span>))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(many_airports)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>What this code is doing is filtering <code>flights</code> for all flights where <code>dest</code> is in the vector of airports <code>c("BTV", "SEA", "PHX", "SFO", "BDL")</code>. Both outputs of <code>many_airports</code> are the same, but as you can see the latter takes much less energy to code. The <code>%in%</code> operator is useful for looking for matches commonly in one vector/variable compared to another.</p>
<p>As a final note, we recommend that <code>filter()</code> should often be among the first verbs you consider applying to your data. This cleans your dataset to only those rows you care about, or put differently, it narrows down the scope of your data frame to just the observations you care about.</p>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC3.1)</strong> What’s another way of using the “not” operator <code>!</code> to filter only the rows that are not going to Burlington, VT nor Seattle, WA in the <code>flights</code> data frame? Test this out using the previous code.</p>
</div>
</section>
<section id="sec-summarize" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="sec-summarize"><span class="header-section-number">3.3</span> <code>summarize</code> variables</h2>
<p>The next common task when working with data frames is to compute <em>summary statistics</em>. Summary statistics are single numerical values that summarize a large number of values. Commonly known examples of summary statistics include the mean (also called the average) and the median (the middle value). Other examples of summary statistics that might not immediately come to mind include the <em>sum</em>, the smallest value also called the <em>minimum</em>, the largest value also called the <em>maximum</em>, and the <em>standard deviation</em>.</p>
<div class="cell" data-layout-align="center">
<p>See <a href="https://moderndive.com/v2/appendixa">Appendix A online</a> for a glossary of such summary statistics.</p>
</div>
<p>Let’s calculate two summary statistics of the <code>wind_speed</code> temperature variable in the <code>weather</code> data frame: the mean and standard deviation (recall from <a href="01-getting-started.html#sec-nycflights" class="quarto-xref"><span>Section 1.4</span></a> that the <code>weather</code> data frame is included in the <code>nycflights23</code> package). To compute these summary statistics, we need the <code>mean()</code> and <code>sd()</code> <em>summary functions</em> in R. Summary functions in R take in many values and return a single value, as shown in <a href="#fig-summary-function" class="quarto-xref">Figure&nbsp;<span>3.2</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-summary-function" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-summary-function-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/cheatsheets/summary.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="FIGURE&nbsp;3.2: Diagram illustrating summary() function in R."><img src="images/cheatsheets/summary.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-summary-function-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;3.2: Diagram illustrating summary() function in R.
</figcaption>
</figure>
</div>
</div>
</div>
<p>More precisely, we’ll use the <code>mean()</code> and <code>sd()</code> summary functions within the <code>summarize()</code> function from the <code>dplyr</code> package. Note you can also use the British English spelling of <code>summarise()</code>. As shown in <a href="#fig-sum1" class="quarto-xref">Figure&nbsp;<span>3.3</span></a>, the <code>summarize()</code> function takes in a data frame and returns a data frame with only one row corresponding to the summary statistics.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sum1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sum1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/cheatsheets/summarize1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="FIGURE&nbsp;3.3: Diagram of summarize() rows."><img src="images/cheatsheets/summarize1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sum1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;3.3: Diagram of summarize() rows.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We’ll save the results in a new data frame called <code>summary_windspeed</code> that will have two columns/variables: the <code>mean</code> and the <code>std_dev</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>summary_windspeed <span class="ot">&lt;-</span> weather <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(wind_speed), <span class="at">std_dev =</span> <span class="fu">sd</span>(wind_speed))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>summary_windspeed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   mean std_dev
  &lt;dbl&gt;   &lt;dbl&gt;
1    NA      NA</code></pre>
</div>
</div>
<p>Why are the values returned <code>NA</code>? <code>NA</code> is how R encodes <em>missing values</em> where <code>NA</code> indicates “not available” or “not applicable.” If a value for a particular row and a particular column does not exist, <code>NA</code> is stored instead. Values can be missing for many reasons. Perhaps the data was collected but someone forgot to enter it. Perhaps the data was not collected at all because it was too difficult to do so. Perhaps there was an erroneous value that someone entered that has been corrected to read as missing. You’ll often encounter issues with missing values when working with real data.</p>
<p>Going back to our <code>summary_windspeed</code> output, by default any time you try to calculate a summary statistic of a variable that has one or more <code>NA</code> missing values in R, <code>NA</code> is returned. To work around this fact, you can set the <code>na.rm</code> argument to <code>TRUE</code>, where <code>rm</code> is short for “remove”; this will ignore any <code>NA</code> missing values and only return the summary value for all non-missing values.</p>
<p>The code that follows computes the mean and standard deviation of all non-missing values of <code>temp</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>summary_windspeed <span class="ot">&lt;-</span> weather <span class="sc">|&gt;</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(wind_speed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">std_dev =</span> <span class="fu">sd</span>(wind_speed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>summary_windspeed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   mean std_dev
  &lt;dbl&gt;   &lt;dbl&gt;
1  9.43    5.27</code></pre>
</div>
</div>
<p>Notice how the <code>na.rm = TRUE</code> are used as arguments to the <code>mean()</code> and <code>sd()</code> summary functions individually, and not to the <code>summarize()</code> function.</p>
<p>However, one needs to be cautious whenever ignoring missing values as we’ve just done. In the upcoming <em>Learning checks</em> questions, we’ll consider the possible ramifications of blindly sweeping rows with missing values “under the rug.” This is in fact why the <code>na.rm</code> argument to any summary statistic function in R is set to <code>FALSE</code> by default. In other words, R does not ignore rows with missing values by default. R is alerting you to the presence of missing data and you should be mindful of this missingness and any potential causes of this missingness throughout your analysis.</p>
<p>What are other summary functions we can use inside the <code>summarize()</code> verb to compute summary statistics? As seen in the diagram in <a href="#fig-summary-function" class="quarto-xref">Figure&nbsp;<span>3.2</span></a>, you can use any function in R that takes many values and returns just one. Here are just a few:</p>
<ul>
<li><code>mean()</code>: the average</li>
<li><code>sd()</code>: the standard deviation, which is a measure of spread</li>
<li><code>min()</code> and <code>max()</code>: the minimum and maximum values, respectively</li>
<li><code>IQR()</code>: interquartile range</li>
<li><code>sum()</code>: the total amount when adding multiple numbers</li>
<li><code>n()</code>: a count of the number of rows in each group. This particular summary function will make more sense when <code>group_by()</code> is covered in <a href="#sec-groupby" class="quarto-xref"><span>Section 3.4</span></a>.</li>
</ul>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC3.2)</strong> Say a doctor is studying the effect of smoking on lung cancer for a large number of patients who have records measured at five-year intervals. She notices that a large number of patients have missing data points because the patient has died, so she chooses to ignore these patients in her analysis. What is wrong with this doctor’s approach?</p>
<p><strong>(LC3.3)</strong> Modify the earlier <code>summarize()</code> function code that creates the <code>summary_windspeed</code> data frame to also use the <code>n()</code> summary function: <code>summarize(... , count = n())</code>. What does the returned value correspond to?</p>
<p><strong>(LC3.4)</strong> Why doesn’t the following code work? Run the code line-by-line instead of all at once, and then look at the data. In other words, select and then run <code>summary_windspeed &lt;- weather |&gt; summarize(mean = mean(wind_speed, na.rm = TRUE))</code> first.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>summary_windspeed <span class="ot">&lt;-</span> weather <span class="sc">|&gt;</span>   </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(wind_speed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">std_dev =</span> <span class="fu">sd</span>(wind_speed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section id="sec-groupby" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-groupby"><span class="header-section-number">3.4</span> <code>group_by</code> rows</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-groupsummarize" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-groupsummarize-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/cheatsheets/group_summary.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="FIGURE&nbsp;3.4: Diagram of group_by() and summarize()."><img src="images/cheatsheets/group_summary.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-groupsummarize-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;3.4: Diagram of group_by() and summarize().
</figcaption>
</figure>
</div>
</div>
</div>
<p>We can modify our code above to look at the average wind speed and its spread instead of wind speed too, keeping the <code>na.rm = TRUE</code> set just in case any missing values are stored in the <code>temp</code> column:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>summary_temp <span class="ot">&lt;-</span> weather <span class="sc">|&gt;</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(wind_speed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">std_dev =</span> <span class="fu">sd</span>(wind_speed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>summary_temp</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   mean std_dev
  &lt;dbl&gt;   &lt;dbl&gt;
1  9.43    5.27</code></pre>
</div>
</div>
<p>Say instead of a single mean wind speed for the whole year, we would like 12 mean temperatures, one for each of the 12 months separately. In other words, we would like to compute the mean wind speed split by month as shown via generic diagram in <a href="#fig-groupsummarize" class="quarto-xref">Figure&nbsp;<span>3.4</span></a>. We can do this by “grouping” temperature observations by the values of another variable, in this case by the 12 values of the variable <code>month</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>summary_monthly_windspeed <span class="ot">&lt;-</span> weather <span class="sc">|&gt;</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month) <span class="sc">|&gt;</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(wind_speed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">std_dev =</span> <span class="fu">sd</span>(wind_speed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>summary_monthly_windspeed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
   month  mean std_dev
   &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;
 1     1 10.3     6.01
 2     2 10.9     6.60
 3     3 12.4     6.36
 4     4 10.0     5.02
 5     5  8.88    4.45
 6     6  8.52    4.42
 7     7  7.96    4.36
 8     8  8.83    4.34
 9     9  8.92    4.66
10    10  8.21    4.71
11    11  9.48    4.81
12    12  8.77    5.03</code></pre>
</div>
</div>
<p>This code is identical to the previous code that created <code>summary_windspeed</code>, but with an extra <code>group_by(month)</code> added before the <code>summarize()</code>. Grouping the <code>weather</code> dataset by <code>month</code> and then applying the <code>summarize()</code> functions yields a data frame that displays the mean and standard deviation wind speed split by the 12 months of the year.</p>
<p>It is important to note that the <code>group_by()</code> function doesn’t change data frames by itself. Rather it changes the <em>meta-data</em>, or data about the data, specifically the grouping structure. Only after applying the <code>summarize()</code> function does the data frame change.</p>
<p>As another example, consider the <code>diamonds</code> data frame included in the <code>ggplot2</code> package:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>diamonds</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,940 × 10
   carat cut       color clarity depth table price     x     y     z
   &lt;dbl&gt; &lt;ord&gt;     &lt;ord&gt; &lt;ord&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1  0.23 Ideal     E     SI2      61.5    55   326  3.95  3.98  2.43
 2  0.21 Premium   E     SI1      59.8    61   326  3.89  3.84  2.31
 3  0.23 Good      E     VS1      56.9    65   327  4.05  4.07  2.31
 4  0.29 Premium   I     VS2      62.4    58   334  4.2   4.23  2.63
 5  0.31 Good      J     SI2      63.3    58   335  4.34  4.35  2.75
 6  0.24 Very Good J     VVS2     62.8    57   336  3.94  3.96  2.48
 7  0.24 Very Good I     VVS1     62.3    57   336  3.95  3.98  2.47
 8  0.26 Very Good H     SI1      61.9    55   337  4.07  4.11  2.53
 9  0.22 Fair      E     VS2      65.1    61   337  3.87  3.78  2.49
10  0.23 Very Good H     VS1      59.4    61   338  4     4.05  2.39
# ℹ 53,930 more rows</code></pre>
</div>
</div>
<p>Observe that the first line of the output reads <code># A tibble: 53,940 x 10</code>. This is an example of meta-data, in this case the number of observations/rows and variables/columns in <code>diamonds</code>. The actual data itself are the subsequent table of values. Now let’s pipe the <code>diamonds</code> data frame into <code>group_by(cut)</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>diamonds <span class="sc">|&gt;</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cut)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,940 × 10
# Groups:   cut [5]
   carat cut       color clarity depth table price     x     y     z
   &lt;dbl&gt; &lt;ord&gt;     &lt;ord&gt; &lt;ord&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1  0.23 Ideal     E     SI2      61.5    55   326  3.95  3.98  2.43
 2  0.21 Premium   E     SI1      59.8    61   326  3.89  3.84  2.31
 3  0.23 Good      E     VS1      56.9    65   327  4.05  4.07  2.31
 4  0.29 Premium   I     VS2      62.4    58   334  4.2   4.23  2.63
 5  0.31 Good      J     SI2      63.3    58   335  4.34  4.35  2.75
 6  0.24 Very Good J     VVS2     62.8    57   336  3.94  3.96  2.48
 7  0.24 Very Good I     VVS1     62.3    57   336  3.95  3.98  2.47
 8  0.26 Very Good H     SI1      61.9    55   337  4.07  4.11  2.53
 9  0.22 Fair      E     VS2      65.1    61   337  3.87  3.78  2.49
10  0.23 Very Good H     VS1      59.4    61   338  4     4.05  2.39
# ℹ 53,930 more rows</code></pre>
</div>
</div>
<p>Observe that now there is additional meta-data: <code># Groups: cut [5]</code> indicating that the grouping structure meta-data has been set based on the 5 possible levels of the categorical variable <code>cut</code>: <code>"Fair"</code>, <code>"Good"</code>, <code>"Very Good"</code>, <code>"Premium"</code>, and <code>"Ideal"</code>. On the other hand, observe that the data has not changed: it is still a table of 53,940 <span class="math inline">\(\times\)</span> 10 values. Only by combining a <code>group_by()</code> with another data-wrangling operation, in this case <code>summarize()</code>, will the data actually be transformed.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>diamonds <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cut) <span class="sc">|&gt;</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_price =</span> <span class="fu">mean</span>(price))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  cut       avg_price
  &lt;ord&gt;         &lt;dbl&gt;
1 Fair          4359.
2 Good          3929.
3 Very Good     3982.
4 Premium       4584.
5 Ideal         3458.</code></pre>
</div>
</div>
<p>If you would like to remove this grouping structure meta-data, we can pipe the resulting data frame into the <code>ungroup()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>diamonds <span class="sc">|&gt;</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cut) <span class="sc">|&gt;</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,940 × 10
   carat cut       color clarity depth table price     x     y     z
   &lt;dbl&gt; &lt;ord&gt;     &lt;ord&gt; &lt;ord&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1  0.23 Ideal     E     SI2      61.5    55   326  3.95  3.98  2.43
 2  0.21 Premium   E     SI1      59.8    61   326  3.89  3.84  2.31
 3  0.23 Good      E     VS1      56.9    65   327  4.05  4.07  2.31
 4  0.29 Premium   I     VS2      62.4    58   334  4.2   4.23  2.63
 5  0.31 Good      J     SI2      63.3    58   335  4.34  4.35  2.75
 6  0.24 Very Good J     VVS2     62.8    57   336  3.94  3.96  2.48
 7  0.24 Very Good I     VVS1     62.3    57   336  3.95  3.98  2.47
 8  0.26 Very Good H     SI1      61.9    55   337  4.07  4.11  2.53
 9  0.22 Fair      E     VS2      65.1    61   337  3.87  3.78  2.49
10  0.23 Very Good H     VS1      59.4    61   338  4     4.05  2.39
# ℹ 53,930 more rows</code></pre>
</div>
</div>
<p>Observe how the <code># Groups: cut [5]</code> meta-data is no longer present.</p>
<p>Let’s now revisit the <code>n()</code> counting summary function we briefly introduced previously. Recall that the <code>n()</code> function counts rows. This is opposed to the <code>sum()</code> summary function that returns the sum of a numerical variable. For example, suppose we’d like to count how many flights departed each of the three airports in New York City:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>by_origin <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(origin) <span class="sc">|&gt;</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>by_origin</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  origin  count
  &lt;chr&gt;   &lt;int&gt;
1 EWR    138578
2 JFK    133048
3 LGA    163726</code></pre>
</div>
</div>
<p>We see that LaGuardia (<code>"LGA"</code>) had the most flights departing in 2023 followed by Newark (<code>"EWR"</code>) and lastly by <code>"JFK"</code>. Note there is a subtle but important difference between <code>sum()</code> and <code>n()</code>; while <code>sum()</code> returns the sum of a numerical variable, <code>n()</code> returns a count of the number of rows/observations.</p>
<section id="grouping-by-more-than-one-variable" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="grouping-by-more-than-one-variable">Grouping by more than one variable</h4>
<p>You are not limited to grouping by one variable. Say you want to know the number of flights leaving each of the three New York City airports <em>for each month</em>. We can also group by a second variable <code>month</code> using <code>group_by(origin, month)</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>by_origin_monthly <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(origin, month) <span class="sc">|&gt;</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'origin'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
<p>Note that an additional message appears here specifying the grouping done. The <code>.groups</code> argument to <code>summarize()</code> has four options: <code>drop_last</code>, <code>drop</code>, <code>keep</code>, and <code>rowwise</code>:</p>
<ul>
<li><code>drop_last</code> drops the last grouping variable,</li>
<li><code>drop</code> drops all grouping variables,</li>
<li><code>keep</code> keeps all grouping variables, and</li>
<li><code>rowwise</code> turns each row into a group.</li>
</ul>
<p>In most circumstances, the default is <code>drop_last</code> which drops the last grouping variable. The message is informing us that the default behavior is to drop the last grouping variable, which in this case is <code>month</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>by_origin_monthly</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 36 × 3
# Groups:   origin [3]
   origin month count
   &lt;chr&gt;  &lt;int&gt; &lt;int&gt;
 1 EWR        1 11623
 2 EWR        2 10991
 3 EWR        3 12593
 4 EWR        4 12022
 5 EWR        5 12371
 6 EWR        6 11339
 7 EWR        7 11646
 8 EWR        8 11561
 9 EWR        9 11373
10 EWR       10 11805
# ℹ 26 more rows</code></pre>
</div>
</div>
<p>Observe that there are 36 rows to <code>by_origin_monthly</code> because there are 12 months for 3 airports (<code>EWR</code>, <code>JFK</code>, and <code>LGA</code>). Why do we <code>group_by(origin, month)</code> and not <code>group_by(origin)</code> and then <code>group_by(month)</code>? Let’s investigate:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>by_origin_monthly_incorrect <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(origin) <span class="sc">|&gt;</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month) <span class="sc">|&gt;</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>by_origin_monthly_incorrect</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   month count
   &lt;int&gt; &lt;int&gt;
 1     1 36020
 2     2 34761
 3     3 39514
 4     4 37476
 5     5 38710
 6     6 35921
 7     7 36211
 8     8 36765
 9     9 35505
10    10 36586
11    11 34521
12    12 33362</code></pre>
</div>
</div>
<p>What happened here is that the second <code>group_by(month)</code> overwrote the grouping structure meta-data of the earlier <code>group_by(origin)</code>, so that in the end we are only grouping by <code>month</code>. The lesson here is if you want to <code>group_by()</code> two or more variables, you should include all the variables at the same time in the same <code>group_by()</code> adding a comma between the variable names.</p>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC3.5)</strong> Recall from <a href="02-visualization.html" class="quarto-xref"><span>Chapter 2</span></a> when we looked at wind speeds by months in NYC. What does the standard deviation column in the <code>summary_monthly_temp</code> data frame tell us about temperatures in NYC throughout the year?</p>
<p><strong>(LC3.6)</strong> What code would be required to get the mean and standard deviation wind speed for each day in 2023 for NYC?</p>
<p><strong>(LC3.7)</strong> Recreate <code>by_monthly_origin</code>, but instead of grouping via <code>group_by(origin, month)</code>, group variables in a different order <code>group_by(month, origin)</code>. What differs in the resulting dataset?</p>
<p><strong>(LC3.8)</strong> How could we identify how many flights left each of the three airports for each <code>carrier</code>?</p>
<p><strong>(LC3.9)</strong> How does the <code>filter()</code> operation differ from a <code>group_by()</code> followed by a <code>summarize()</code>?</p>
</div>
</section>
</section>
<section id="sec-mutate" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sec-mutate"><span class="header-section-number">3.5</span> <code>mutate</code> existing variables</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mutatevars" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mutatevars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/cheatsheets/mutate.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="FIGURE&nbsp;3.5: Diagram of mutate() columns."><img src="images/cheatsheets/mutate.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mutatevars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;3.5: Diagram of mutate() columns.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Another common transformation of data is to create/compute new variables based on existing ones as shown in <a href="#fig-mutatevars" class="quarto-xref">Figure&nbsp;<span>3.5</span></a>. For example, say you are more comfortable thinking of temperature in degrees Celsius (°C) instead of degrees Fahrenheit (°F). The formula to convert temperatures from °F to °C is</p>
<p><span class="math display">\[
\text{temp in C} = \frac{\text{temp in F} - 32}{1.8}
\]</span></p>
<p>We can apply this formula to the <code>temp</code> variable using the <code>mutate()</code> function from the <code>dplyr</code> package, which takes existing variables and mutates them to create new ones.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>weather <span class="ot">&lt;-</span> weather <span class="sc">|&gt;</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">temp_in_C =</span> (temp <span class="sc">-</span> <span class="dv">32</span>) <span class="sc">/</span> <span class="fl">1.8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In this code, we <code>mutate()</code> the <code>weather</code> data frame by creating a new variable</p>
<p><code>temp_in_C = (temp - 32) / 1.8</code>,</p>
<p>and then we <em>overwrite</em> the original <code>weather</code> data frame. Why did we overwrite the data frame <code>weather</code>, instead of assigning the result to a new data frame like <code>weather_new</code>?</p>
<p>As a rough rule of thumb, as long as you are not losing original information that you might need later, it’s acceptable practice to overwrite existing data frames with updated ones, as we did here. On the other hand, why did we not overwrite the variable <code>temp</code>, but instead created a new variable called <code>temp_in_C</code>? Because if we did this, we would have erased the original information contained in <code>temp</code> of temperatures in Fahrenheit that may still be valuable to us.</p>
<p>Let’s now compute monthly average temperatures in both °F and °C using the <code>group_by()</code> and <code>summarize()</code> code we saw in <a href="#sec-groupby" class="quarto-xref"><span>Section 3.4</span></a>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>summary_monthly_temp <span class="ot">&lt;-</span> weather <span class="sc">|&gt;</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month) <span class="sc">|&gt;</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_temp_in_F =</span> <span class="fu">mean</span>(temp, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_temp_in_C =</span> <span class="fu">mean</span>(temp_in_C, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>summary_monthly_temp</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
   month mean_temp_in_F mean_temp_in_C
   &lt;int&gt;          &lt;dbl&gt;          &lt;dbl&gt;
 1     1           42.8           6.02
 2     2           40.3           4.62
 3     3           43.9           6.61
 4     4           56.0          13.3 
 5     5           62.4          16.9 
 6     6           69.6          20.9 
 7     7           79.2          26.2 
 8     8           75.3          24.1 
 9     9           70.1          21.2 
10    10           61.0          16.1 
11    11           47.0           8.31
12    12           43.9           6.62</code></pre>
</div>
</div>
<p>Let’s consider another example. Passengers are often frustrated when their flight departs late, but aren’t as annoyed if, in the end, pilots can make up some time during the flight. This is known in the airline industry as <em>gain</em>, and we will create this variable using the <code>mutate()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>flights <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gain =</span> dep_delay <span class="sc">-</span> arr_delay)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s take a look at only the <code>dep_delay</code>, <code>arr_delay</code>, and the resulting <code>gain</code> variables for the first 5 rows in our updated <code>flights</code> data frame in <a href="#tbl-first-five-flights" class="quarto-xref">Table&nbsp;<span>3.1</span></a>.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-first-five-flights" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-first-five-flights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;3.1: First five rows of departure/arrival delay and gain variables
</figcaption>
<div aria-describedby="tbl-first-five-flights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">dep_delay</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">arr_delay</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">gain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">203</td>
<td style="text-align: right;">205</td>
<td style="text-align: right;">-2</td>
</tr>
<tr class="even">
<td style="text-align: right;">78</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="odd">
<td style="text-align: right;">47</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="even">
<td style="text-align: right;">173</td>
<td style="text-align: right;">166</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">228</td>
<td style="text-align: right;">211</td>
<td style="text-align: right;">17</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The flight in the first row departed 203 minutes late but arrived 205 minutes late, so its “gained time in the air” is a gain of -2 minutes, hence its <code>gain</code> is <span class="math inline">\(203 - 205 = -2\)</span>, which is a <code>loss</code> of 2 minutes. On the other hand, the flight in the third row departed late (<code>dep_delay</code> of 47) but arrived 34 minutes late (<code>arr_delay</code> of 34), so its “gained time in the air” is <span class="math inline">\(47 - 34 = 13\)</span> minutes, hence its <code>gain</code> is 13.</p>
<p>Let’s look at some summary statistics of the <code>gain</code> variable by considering multiple summary functions at once in the same <code>summarize()</code> code:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>gain_summary <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(gain, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">q1 =</span> <span class="fu">quantile</span>(gain, <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">quantile</span>(gain, <span class="fl">0.5</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">q3 =</span> <span class="fu">quantile</span>(gain, <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(gain, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(gain, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(gain, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(gain))</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>gain_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
    min    q1 median    q3   max  mean    sd missing
  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;int&gt;
1  -321     1     11    20   101  9.35  18.4   12534</code></pre>
</div>
</div>
<p>We see for example that the median gain is 11 minutes, while the largest is +101 minutes and the largest negative gain (or loss) at -321 minutes! However, this code would take some time to type out in practice. We’ll see later on in <a href="05-regression.html#sec-model1EDA" class="quarto-xref"><span>Section 5.1.1</span></a> that there is a much more succinct way to compute a variety of common summary statistics: using the <code>tidy_summary()</code> function from the <code>moderndive</code> package.</p>
<p>Recall from <a href="02-visualization.html#sec-histograms" class="quarto-xref"><span>Section 2.5</span></a> that since <code>gain</code> is a numerical variable, we can visualize its distribution using a histogram.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> gain)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"white"</span>, <span class="at">bins =</span> <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-gain-hist" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gain-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="03-wrangling_files/figure-html/fig-gain-hist-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="FIGURE&nbsp;3.6: Histogram of gain variable."><img src="03-wrangling_files/figure-html/fig-gain-hist-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gain-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;3.6: Histogram of gain variable.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The resulting histogram in <a href="#fig-gain-hist" class="quarto-xref">Figure&nbsp;<span>3.6</span></a> provides additional perspective on the <code>gain</code> variable than the summary statistics we computed earlier. For example, note that most values of <code>gain</code> are right around 0.</p>
<p>To close out our discussion on the <code>mutate()</code> function to create new variables, note that we can create multiple new variables at once in the same <code>mutate()</code> code. Furthermore, within the same <code>mutate()</code> code we can refer to new variables we just created. As an example, consider the <code>mutate()</code> code Hadley Wickham and Garrett Grolemund show in Chapter 5 of <em>R for Data Science</em> <span class="citation" data-cites="rds2016">(<a href="99-references.html#ref-rds2016" role="doc-biblioref">Grolemund and Wickham 2017</a>)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>flights <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">gain =</span> dep_delay <span class="sc">-</span> arr_delay,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">hours =</span> air_time <span class="sc">/</span> <span class="dv">60</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">gain_per_hour =</span> gain <span class="sc">/</span> hours</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC3.10)</strong> What do positive values of the <code>gain</code> variable in <code>flights</code> correspond to? What about negative values? And what about a zero value?</p>
<p><strong>(LC3.11)</strong> Could we create the <code>dep_delay</code> and <code>arr_delay</code> columns by simply subtracting <code>dep_time</code> from <code>sched_dep_time</code> and similarly for arrivals? Try the code out and explain any differences between the result and what actually appears in <code>flights</code>.</p>
<p><strong>(LC3.12)</strong> What can we say about the distribution of <code>gain</code>? Describe it in a few sentences using the plot and the <code>gain_summary</code> data frame values.</p>
</div>
</section>
<section id="sec-arrange" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="sec-arrange"><span class="header-section-number">3.6</span> <code>arrange</code> and sort rows</h2>
<p>One of the most commonly performed data-wrangling tasks is to sort a data frame’s rows in the alphanumeric order of one of the variables. The <code>dplyr</code> package’s <code>arrange()</code> function allows us to sort/reorder a data frame’s rows according to the values of the specified variable.</p>
<p>Suppose we are interested in determining the most frequent destination airports for all domestic flights departing from New York City in 2023:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>freq_dest <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(dest) <span class="sc">|&gt;</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">num_flights =</span> <span class="fu">n</span>())</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>freq_dest</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 118 × 2
   dest  num_flights
   &lt;chr&gt;       &lt;int&gt;
 1 ABQ           228
 2 ACK           916
 3 AGS            20
 4 ALB          1581
 5 ANC            95
 6 ATL         17570
 7 AUS          4848
 8 AVL          1617
 9 AVP           145
10 BDL           701
# ℹ 108 more rows</code></pre>
</div>
</div>
<p>Observe that by default the rows of the resulting <code>freq_dest</code> data frame are sorted in alphabetical order of <code>dest</code>ination. Say instead we would like to see the same data, but sorted from the most to the least number of flights (<code>num_flights</code>) instead:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>freq_dest <span class="sc">|&gt;</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(num_flights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 118 × 2
   dest  num_flights
   &lt;chr&gt;       &lt;int&gt;
 1 LEX             1
 2 AGS            20
 3 OGG            20
 4 SBN            24
 5 HDN            28
 6 PNS            71
 7 MTJ            77
 8 ANC            95
 9 VPS           109
10 AVP           145
# ℹ 108 more rows</code></pre>
</div>
</div>
<p>This is, however, the opposite of what we want. The rows are sorted with the least frequent destination airports displayed first. This is because <code>arrange()</code> always returns rows sorted in ascending order by default. To switch the ordering to be in “descending” order instead, we use the <code>desc()</code> function as so:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>freq_dest <span class="sc">|&gt;</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(num_flights))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 118 × 2
   dest  num_flights
   &lt;chr&gt;       &lt;int&gt;
 1 BOS         19036
 2 ORD         18200
 3 MCO         17756
 4 ATL         17570
 5 MIA         16076
 6 LAX         15968
 7 FLL         14239
 8 CLT         12866
 9 DFW         11675
10 SFO         11651
# ℹ 108 more rows</code></pre>
</div>
</div>
</section>
<section id="sec-joins" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="sec-joins"><span class="header-section-number">3.7</span> <code>join</code> data frames</h2>
<p>Another common data transformation task is “joining” or “merging” two different datasets. For example, in the <code>flights</code> data frame, the variable <code>carrier</code> lists the carrier code for the different flights. While the corresponding airline names for <code>"UA"</code> and <code>"AA"</code> might be somewhat easy to guess (United and American Airlines), what airlines have codes <code>"VX"</code>, <code>"HA"</code>, and <code>"B6"</code>? This information is provided in a separate data frame <code>airlines</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(airlines)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We see that in <code>airlines</code>, <code>carrier</code> is the carrier code, while <code>name</code> is the full name of the airline company. Using this table, we can see that <code>"G4"</code>, <code>"HA"</code>, and <code>"B6"</code> correspond to Allegiant Air, Hawaiian Airlines, and JetBlue, respectively. However, wouldn’t it be nice to have all this information in a single data frame instead of two separate data frames? We can do this by “joining” the <code>flights</code> and <code>airlines</code> data frames.</p>
<p>The values in the variable <code>carrier</code> in the <code>flights</code> data frame match the values in the variable <code>carrier</code> in the <code>airlines</code> data frame. In this case, we can use the variable <code>carrier</code> as a <em>key variable</em> to match the rows of the two data frames. Key variables are almost always <em>identification variables</em> that uniquely identify the observational units as we saw in <a href="01-getting-started.html#sec-identification-vs-measurement-variables" class="quarto-xref"><span>Section 1.4.4</span></a>. This ensures that rows in both data frames are appropriately matched during the join. Hadley and Garrett <span class="citation" data-cites="rds2016">(<a href="99-references.html#ref-rds2016" role="doc-biblioref">Grolemund and Wickham 2017</a>)</span> created the diagram in <a href="#fig-reldiagram" class="quarto-xref">Figure&nbsp;<span>3.7</span></a> to show how the different data frames in the <code>nycflights23</code> package are linked by various key variables:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-reldiagram" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-reldiagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/r4ds/relational-nycflights.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="FIGURE&nbsp;3.7: Data relationships in nycflights from R for Data Science."><img src="images/r4ds/relational-nycflights.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reldiagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;3.7: Data relationships in nycflights from <em>R for Data Science</em>.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="matching-key-variable-names" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="matching-key-variable-names"><span class="header-section-number">3.7.1</span> Matching key variable names</h3>
<p>In both the <code>flights</code> and <code>airlines</code> data frames, the key variable we want to join/merge/match the rows by has the same name: <code>carrier</code>. Let’s use the <code>inner_join()</code> function to join the two data frames, where the rows will be matched by the variable <code>carrier</code>, and then compare the resulting data frames:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>flights_joined <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(airlines, <span class="at">by =</span> <span class="st">"carrier"</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(flights)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(flights_joined)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Observe that the <code>flights</code> and <code>flights_joined</code> data frames are identical except that <code>flights_joined</code> has an additional variable <code>name</code>. The values of <code>name</code> correspond to the airline companies’ names as indicated in the <code>airlines</code> data frame.</p>
<p>A visual representation of the <code>inner_join()</code> is shown in <a href="#fig-ijdiagram" class="quarto-xref">Figure&nbsp;<span>3.8</span></a>. There are other types of joins available (such as <code>left_join()</code>, <code>right_join()</code>, <code>outer_join()</code>, and <code>anti_join()</code>), but the <code>inner_join()</code> will solve nearly all of the problems you’ll encounter in this book.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ijdiagram" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ijdiagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/r4ds/join-inner.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="FIGURE&nbsp;3.8: Diagram of inner join from R for Data Science."><img src="images/r4ds/join-inner.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ijdiagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;3.8: Diagram of inner join from <em>R for Data Science</em>.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-diff-key" class="level3" data-number="3.7.2">
<h3 data-number="3.7.2" class="anchored" data-anchor-id="sec-diff-key"><span class="header-section-number">3.7.2</span> Different key variable names</h3>
<p>Say instead you are interested in the destinations of all domestic flights departing NYC in 2023, and you ask yourself questions like: “What cities are these airports in?”, or “Is <code>"ORD"</code> Orlando?”, or “Where is <code>"FLL"</code>?”.</p>
<p>The <code>airports</code> data frame contains the airport codes for each airport:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(airports)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>However, if you look at both the <code>airports</code> and <code>flights</code> data frames, you’ll find that the airport codes are in variables that have different names. In <code>airports</code>, the airport code is in <code>faa</code>, whereas in <code>flights</code> the airport codes are in <code>origin</code> and <code>dest</code>. This fact is further highlighted in the visual representation of the relationships between these data frames in <a href="#fig-reldiagram" class="quarto-xref">Figure&nbsp;<span>3.7</span></a>.</p>
<p>In order to join these two data frames by airport code, our <code>inner_join()</code> operation will use the <code>by = c("dest" = "faa")</code> argument with modified code syntax allowing us to join two data frames where the key variable has a different name:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>flights_with_airport_names <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(airports, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"dest"</span> <span class="ot">=</span> <span class="st">"faa"</span>))</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(flights_with_airport_names)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s construct the chain of pipe operators <code>|&gt;</code> that computes the number of flights from NYC to each destination, but also includes information about each destination airport:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>named_dests <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(dest) <span class="sc">|&gt;</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">num_flights =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(num_flights)) <span class="sc">|&gt;</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(airports, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"dest"</span> <span class="ot">=</span> <span class="st">"faa"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">airport_name =</span> name)</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>named_dests</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 118 × 9
   dest  num_flights airport_name             lat    lon   alt    tz dst   tzone
   &lt;chr&gt;       &lt;int&gt; &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;
 1 BOS         19036 General Edward Lawren…  42.4  -71.0    20    -5 A     Amer…
 2 ORD         18200 Chicago O'Hare Intern…  42.0  -87.9   672    -6 A     Amer…
 3 MCO         17756 Orlando International…  28.4  -81.3    96    -5 A     Amer…
 4 ATL         17570 Hartsfield Jackson At…  33.6  -84.4  1026    -5 A     Amer…
 5 MIA         16076 Miami International A…  25.8  -80.3     8    -5 A     Amer…
 6 LAX         15968 Los Angeles Internati…  33.9 -118.    125    -8 A     Amer…
 7 FLL         14239 Fort Lauderdale Holly…  26.1  -80.2     9    -5 A     Amer…
 8 CLT         12866 Charlotte Douglas Int…  35.2  -80.9   748    -5 A     Amer…
 9 DFW         11675 Dallas Fort Worth Int…  32.9  -97.0   607    -6 A     Amer…
10 SFO         11651 San Francisco Interna…  37.6 -122.     13    -8 A     Amer…
# ℹ 108 more rows</code></pre>
</div>
</div>
<p>In case you didn’t know, <code>"ORD"</code> is the airport code of Chicago O’Hare airport and <code>"FLL"</code> is the main airport in Fort Lauderdale, Florida, which can be seen in the <code>airport_name</code> variable.</p>
</section>
<section id="multiple-key-variables" class="level3" data-number="3.7.3">
<h3 data-number="3.7.3" class="anchored" data-anchor-id="multiple-key-variables"><span class="header-section-number">3.7.3</span> Multiple key variables</h3>
<p>Say instead we want to join two data frames by <em>multiple key variables</em>. For example, in <a href="#fig-reldiagram" class="quarto-xref">Figure&nbsp;<span>3.7</span></a>, we see that in order to join the <code>flights</code> and <code>weather</code> data frames, we need more than one key variable: <code>year</code>, <code>month</code>, <code>day</code>, <code>hour</code>, and <code>origin</code>. This is because the combination of these 5 variables act to uniquely identify each observational unit in the <code>weather</code> data frame: hourly weather recordings at each of the 3 NYC airports.</p>
<p>We achieve this by specifying a <em>vector</em> of key variables to join by using the <code>c()</code> function. Recall from <a href="01-getting-started.html#sec-programming-concepts" class="quarto-xref"><span>Section 1.2.1</span></a> that <code>c()</code> is short for “combine” or “concatenate.” </p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>flights_weather_joined <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(weather, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"month"</span>, <span class="st">"day"</span>, <span class="st">"hour"</span>, <span class="st">"origin"</span>))</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(flights_weather_joined)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC3.13)</strong> Looking at <a href="#fig-reldiagram" class="quarto-xref">Figure&nbsp;<span>3.7</span></a>, when joining <code>flights</code> and <code>weather</code> (or, in other words, matching the hourly weather values with each flight), why do we need to join by all of <code>year</code>, <code>month</code>, <code>day</code>, <code>hour</code>, and <code>origin</code>, and not just <code>hour</code>?</p>
<p><strong>(LC3.14)</strong> What surprises you about the top 10 destinations from NYC in 2023?</p>
</div>
</section>
<section id="sec-normal-forms" class="level3" data-number="3.7.4">
<h3 data-number="3.7.4" class="anchored" data-anchor-id="sec-normal-forms"><span class="header-section-number">3.7.4</span> Normal forms</h3>
<p>The data frames included in the <code>nycflights23</code> package are in a form that minimizes redundancy of data. For example, the <code>flights</code> data frame only saves the <code>carrier</code> code of the airline company; it does not include the actual name of the airline. For example, you’ll see that the first row of <code>flights</code> has <code>carrier</code> equal to <code>UA</code>, but it does not include the airline name “United Air Lines Inc.”</p>
<p>The names of the airline companies are included in the <code>name</code> variable of the <code>airlines</code> data frame. In order to have the airline company name included in <code>flights</code>, we could join these two data frames as follows:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>joined_flights <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(airlines, <span class="at">by =</span> <span class="st">"carrier"</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(joined_flights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We are capable of performing this join because each of the data frames has <em>keys</em> in common to relate one to another: the <code>carrier</code> variable in both the <code>flights</code> and <code>airlines</code> data frames. The <em>key</em> variable(s) that we base our joins on are often <em>identification variables</em> as we mentioned previously.</p>
<p>This is an important property of what’s known as <em>normal forms</em> of data. The process of decomposing data frames into less redundant tables without losing information is called <em>normalization</em>. More information is available on <a href="https://en.wikipedia.org/wiki/Database_normalization">Wikipedia</a>.</p>
<p>Both <code>dplyr</code> and <a href="https://en.wikipedia.org/wiki/SQL">SQL</a> we mentioned in the introduction of this chapter use such <em>normal forms</em>. Given that they share such commonalities, once you learn either of these two tools, you can learn the other very easily.</p>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC3.15)</strong> What are some advantages of data in normal forms? What are some disadvantages?</p>
</div>
</section>
</section>
<section id="sec-other-verbs" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="sec-other-verbs"><span class="header-section-number">3.8</span> Other verbs</h2>
<p>Here are some other useful data-wrangling verbs:</p>
<ul>
<li><code>select()</code> only a subset of variables/columns.</li>
<li><code>relocate()</code> variables/columns to a new position.</li>
<li><code>rename()</code> variables/columns to have new names.</li>
<li>Return only the <code>top_n()</code> values of a variable.</li>
</ul>
<section id="sec-select" class="level3" data-number="3.8.1">
<h3 data-number="3.8.1" class="anchored" data-anchor-id="sec-select"><span class="header-section-number">3.8.1</span> <code>select</code> variables</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-selectfig" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-selectfig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/cheatsheets/select.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="FIGURE&nbsp;3.9: Diagram of select() columns."><img src="images/cheatsheets/select.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-selectfig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;3.9: Diagram of select() columns.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We’ve seen that the <code>flights</code> data frame in the <code>nycflights23</code> package contains 19 different variables. You can identify the names of these 19 variables by running the <code>glimpse()</code> function from the <code>dplyr</code> package:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(flights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>However, say you only need two of these 19 variables, say <code>carrier</code> and <code>flight</code>. You can <code>select()</code> these two variables:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">|&gt;</span> </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(carrier, flight)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This function makes it easier to explore large datasets since it allows us to limit the scope to only those variables we care most about. For example, if we <code>select()</code> only a smaller number of variables as is shown in <a href="#fig-selectfig" class="quarto-xref">Figure&nbsp;<span>3.9</span></a>, it will make viewing the dataset in RStudio’s spreadsheet viewer more digestible.</p>
<p>Let’s say instead you want to drop, or de-select, certain variables. For example, consider the variable <code>year</code> in the <code>flights</code> data frame. This variable isn’t quite a “variable” because it is always <code>2023</code> and hence doesn’t change. Say you want to remove this variable from the data frame. We can deselect <code>year</code> by using the <code>-</code> sign:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>flights_no_year <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="sc">-</span>year)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Another way of selecting columns/variables is by specifying a range of columns:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>flight_arr_times <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> <span class="fu">select</span>(month<span class="sc">:</span>day, arr_time<span class="sc">:</span>sched_arr_time)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>flight_arr_times</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This will <code>select()</code> all columns between <code>month</code> and <code>day</code>, as well as between <code>arr_time</code> and <code>sched_arr_time</code>, and drop the rest.</p>
<p>The helper functions <code>starts_with()</code>, <code>ends_with()</code>, and <code>contains()</code> can be used to select variables/columns that match those conditions. As examples,</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">"a"</span>))</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">ends_with</span>(<span class="st">"delay"</span>))</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"time"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Lastly, the <code>select()</code> function can also be used to reorder columns when used with the <code>everything()</code> helper function. For example, suppose we want the <code>hour</code>, <code>minute</code>, and <code>time_hour</code> variables to appear immediately after the <code>year</code>, <code>month</code>, and <code>day</code> variables, while not discarding the rest of the variables. In the following code, <code>everything()</code> will pick up all remaining variables:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>flights_reorder <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, month, day, hour, minute, time_hour, <span class="fu">everything</span>())</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(flights_reorder)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="sec-relocate" class="level3" data-number="3.8.2">
<h3 data-number="3.8.2" class="anchored" data-anchor-id="sec-relocate"><span class="header-section-number">3.8.2</span> <code>relocate</code> variables</h3>
<p>Another (usually shorter) way to reorder variables is by using the <code>relocate()</code> function. This function allows you to move variables to a new position in the data frame. For example, if we want to move the <code>hour</code>, <code>minute</code>, and <code>time_hour</code> variables to appear immediately after the <code>year</code>, <code>month</code>, and <code>day</code> variables, we can use the following code:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>flights_relocate <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(hour, minute, time_hour, <span class="at">.after =</span> day)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(flights_relocate)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="sec-rename" class="level3" data-number="3.8.3">
<h3 data-number="3.8.3" class="anchored" data-anchor-id="sec-rename"><span class="header-section-number">3.8.3</span> <code>rename</code> variables</h3>
<p>One more useful function is <code>rename()</code>, which as you may have guessed changes the name of variables. Suppose we want to only focus on <code>dep_time</code> and <code>arr_time</code> and change <code>dep_time</code> and <code>arr_time</code> to be <code>departure_time</code> and <code>arrival_time</code> instead in the <code>flights_time_new</code> data frame:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>flights_time_new <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(dep_time, arr_time) <span class="sc">|&gt;</span> </span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">departure_time =</span> dep_time, <span class="at">arrival_time =</span> arr_time)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(flights_time_new)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that in this case we used a single <code>=</code> sign within the <code>rename()</code>. For example, <code>departure_time = dep_time</code> renames the <code>dep_time</code> variable to have the new name <code>departure_time</code>. This is because we are not testing for equality like we would using <code>==</code>. Instead we want to assign a new variable <code>departure_time</code> to have the same values as <code>dep_time</code> and then delete the variable <code>dep_time</code>. Note that new <code>dplyr</code> users often forget that the new variable name comes before the equal sign.</p>
</section>
<section id="top_n-values-of-a-variable" class="level3" data-number="3.8.4">
<h3 data-number="3.8.4" class="anchored" data-anchor-id="top_n-values-of-a-variable"><span class="header-section-number">3.8.4</span> <code>top_n</code> values of a variable</h3>
<p>We can also return the top <code>n</code> values of a variable using the <code>top_n()</code> function. For example, we can return a data frame of the top 10 destination airports using the example from <a href="#sec-diff-key" class="quarto-xref"><span>Section 3.7.2</span></a>. Observe that we set the number of values to return to <code>n = 10</code> and <code>wt = num_flights</code> to indicate that we want the rows corresponding to the top 10 values of <code>num_flights</code>. See the help file for <code>top_n()</code> by running <code>?top_n</code> for more information.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>named_dests <span class="sc">|&gt;</span> <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">wt =</span> num_flights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s further <code>arrange()</code> these results in descending order of <code>num_flights</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>named_dests <span class="sc">|&gt;</span> </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">wt =</span> num_flights) <span class="sc">|&gt;</span> </span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(num_flights))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC3.16)</strong> What are some ways to select all three of the <code>dest</code>, <code>air_time</code>, and <code>distance</code> variables from <code>flights</code>? Give the code showing how to do this in at least three different ways.</p>
<p><strong>(LC3.17)</strong> How could one use <code>starts_with()</code>, <code>ends_with()</code>, and <code>contains()</code> to select columns from the <code>flights</code> data frame? Provide three different examples in total: one for <code>starts_with()</code>, one for <code>ends_with()</code>, and one for <code>contains()</code>.</p>
<p><strong>(LC3.18)</strong> Why might we want to use the <code>select()</code> function on a data frame?</p>
<p><strong>(LC3.19)</strong> Create a new data frame that shows the top 5 airports with the largest arrival delays from NYC in 2023.</p>
</div>
</section>
</section>
<section id="sec-wrangling-conclusion" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="sec-wrangling-conclusion"><span class="header-section-number">3.9</span> Conclusion</h2>
<section id="summary-table" class="level3" data-number="3.9.1">
<h3 data-number="3.9.1" class="anchored" data-anchor-id="summary-table"><span class="header-section-number">3.9.1</span> Summary table</h3>
<p>Let’s recap our data-wrangling verbs in <a href="#tbl-wrangle-summary-table" class="quarto-xref">Table&nbsp;<span>3.2</span></a>. Using these verbs and the pipe <code>|&gt;</code> operator from <a href="#sec-piping" class="quarto-xref"><span>Section 3.1</span></a>, you’ll be able to write easily legible code to perform almost all the data wrangling and data transformation necessary for the rest of this book.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-wrangle-summary-table" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-wrangle-summary-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;3.2: Summary of data-wrangling verbs
</figcaption>
<div aria-describedby="tbl-wrangle-summary-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Verb</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Data wrangling operation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">`filter()`</td>
<td style="text-align: left;">Pick out a subset of rows</td>
</tr>
<tr class="even">
<td style="text-align: left;">`summarize()`</td>
<td style="text-align: left;">Summarize many values to one using a summary statistic function like `mean()`, `median()`, etc.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">`group_by()`</td>
<td style="text-align: left;">Add grouping structure to rows in data frame. Note this does not change values in data frame, rather only the meta-data</td>
</tr>
<tr class="even">
<td style="text-align: left;">`mutate()`</td>
<td style="text-align: left;">Create new variables by mutating existing ones</td>
</tr>
<tr class="odd">
<td style="text-align: left;">`arrange()`</td>
<td style="text-align: left;">Arrange rows of a data variable in ascending (default) or `desc`ending order</td>
</tr>
<tr class="even">
<td style="text-align: left;">`inner_join()`</td>
<td style="text-align: left;">Join/merge two data frames, matching rows by a key variable</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC3.20)</strong> Let’s now put your newly acquired data-wrangling skills to the test!</p>
<p>An airline industry measure of a passenger airline’s capacity is the <a href="https://en.wikipedia.org/wiki/Available_seat_miles">available seat miles</a>, which is equal to the number of seats available multiplied by the number of miles or kilometers flown summed over all flights.</p>
<p>For example, let’s consider the scenario in <a href="#fig-available-seat-miles" class="quarto-xref">Figure&nbsp;<span>3.10</span></a>. Since the airplane has 4 seats and it travels 200 miles, the available seat miles are <span class="math inline">\(4 \times 200 = 800\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-available-seat-miles" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-available-seat-miles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/flowcharts/flowchart/flowchart.012.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="FIGURE&nbsp;3.10: Example of available seat miles for one flight."><img src="images/flowcharts/flowchart/flowchart.012.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-available-seat-miles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;3.10: Example of available seat miles for one flight.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Extending this idea, let’s say an airline had 2 flights using a plane with 10 seats that flew 500 miles and 3 flights using a plane with 20 seats that flew 1000 miles, the available seat miles would be <span class="math inline">\(2 \times 10 \times 500 + 3 \times 20 \times 1000 = 70,000\)</span> seat miles.</p>
<p>Using the datasets included in the <code>nycflights23</code> package, compute the available seat miles for each airline sorted in descending order. After completing all the necessary data-wrangling steps, the resulting data frame should have 14 rows (one for each airline) and 2 columns (airline name and available seat miles). Here are some hints:</p>
<ol type="1">
<li><strong>Crucial</strong>: Unless you are very confident in what you are doing, it is worthwhile not starting to code right away. Rather, first sketch out on paper all the necessary data wrangling steps not using exact code, but rather high-level <em>pseudocode</em> that is informal yet detailed enough to articulate what you are doing. This way you won’t confuse <em>what</em> you are trying to do (the algorithm) with <em>how</em> you are going to do it (writing <code>dplyr</code> code).</li>
<li>Take a close look at all the datasets using the <code>View()</code> function: <code>flights</code>, <code>weather</code>, <code>planes</code>, <code>airports</code>, and <code>airlines</code> to identify which variables are necessary to compute available seat miles.</li>
<li><a href="#fig-reldiagram" class="quarto-xref">Figure&nbsp;<span>3.7</span></a> showing how the various datasets can be joined will also be useful.</li>
<li>Consider the data-wrangling verbs in <a href="#tbl-wrangle-summary-table" class="quarto-xref">Table&nbsp;<span>3.2</span></a> as your toolbox!</li>
</ol>
</div>
</section>
<section id="additional-resources" class="level3" data-number="3.9.2">
<h3 data-number="3.9.2" class="anchored" data-anchor-id="additional-resources"><span class="header-section-number">3.9.2</span> Additional resources</h3>
<div class="cell" data-layout-align="center">
<p>An R script file of all R code used in this chapter is available <a href="scripts/03-wrangling.R">here</a>.</p>
</div>
<div class="cell" data-layout-align="center">
<p>In the online <a href="https://moderndive.com/v2/appendixc.html">Appendix C</a>, we provide a page of data wrangling ‘tips and tricks’ consisting of the most common data wrangling questions we’ve encountered in student projects (shout out to <a href="https://www.scsparkscience.org/fellow/jennifer-smetzer/">Dr.&nbsp;Jenny Smetzer</a> for her work setting this up!):</p>
<ul>
<li>Dealing with missing values</li>
<li>Reordering bars in a barplot</li>
<li>Showing money on an axis</li>
<li>Changing values inside cells</li>
<li>Converting a numerical variable to a categorical one</li>
<li>Computing proportions</li>
<li>Dealing with %, commas, and dollar signs</li>
</ul>
<p>However, to provide a tips and tricks page covering all possible data wrangling questions would be too long to be useful!</p>
</div>
<p>If you want to further unlock the power of the <code>dplyr</code> package for data wrangling, we suggest that you check out RStudio’s “Data Transformation with dplyr” cheatsheet. This cheatsheet summarizes much more than what we’ve discussed in this chapter, in particular more intermediate level and advanced data-wrangling functions, while providing quick and easy-to-read visual descriptions. In fact, many of the diagrams illustrating data wrangling operations in this chapter, such as <a href="#fig-filter" class="quarto-xref">Figure&nbsp;<span>3.1</span></a> on <code>filter()</code>, originate from this cheatsheet.</p>
<p>In the current version of RStudio in 2025, you can access this cheatsheet by going to the RStudio Menu Bar -&gt; Help -&gt; Cheatsheets -&gt; “Data Transformation with dplyr.” You can see a preview in the figure below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-dplyr-cheatsheet" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dplyr-cheatsheet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/cheatsheets/dplyr_cheatsheet-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="FIGURE&nbsp;3.11: Data Transformation with dplyr cheatsheet (first page)."><img src="images/cheatsheets/dplyr_cheatsheet-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dplyr-cheatsheet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;3.11: Data Transformation with dplyr cheatsheet (first page).
</figcaption>
</figure>
</div>
</div>
</div>
<p>On top of the data-wrangling verbs and examples we presented in this section, if you’d like to see more examples of using the <code>dplyr</code> package for data wrangling, check out <a href="http://r4ds.had.co.nz/transform.html">Chapter 5</a> of <em>R for Data Science</em> <span class="citation" data-cites="rds2016">(<a href="99-references.html#ref-rds2016" role="doc-biblioref">Grolemund and Wickham 2017</a>)</span>.</p>
</section>
<section id="whats-to-come" class="level3" data-number="3.9.3">
<h3 data-number="3.9.3" class="anchored" data-anchor-id="whats-to-come"><span class="header-section-number">3.9.3</span> What’s to come?</h3>
<p>So far in this book, we’ve explored, visualized, and wrangled data saved in data frames. These data frames were saved in a spreadsheet-like format: in a rectangular shape with a certain number of rows corresponding to observations and a certain number of columns corresponding to variables describing these observations.</p>
<p>We’ll see in the upcoming <a href="04-tidy.html" class="quarto-xref"><span>Chapter 4</span></a> that there are actually two ways to represent data in spreadsheet-type rectangular format: (1) “wide” format and (2) “tall/narrow” format. The tall/narrow format is also known as <em>“tidy”</em> format in R user circles. While the distinction between “tidy” and non-“tidy” formatted data is subtle, it has immense implications for our data science work. This is because almost all the packages used in this book, including the <code>ggplot2</code> package for data visualization and the <code>dplyr</code> package for data wrangling, all assume that all data frames are in “tidy” format.</p>
<p>Furthermore, up until now we’ve only explored, visualized, and wrangled data saved within R packages. But what if you want to analyze data that you have saved in a Microsoft Excel, a Google Sheets, or a “Comma-Separated Values” (CSV) file? In <a href="04-tidy.html#sec-csv" class="quarto-xref"><span>Section 4.1</span></a>, we’ll show you how to import this data into R using the <code>readr</code> package.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-rds2016" class="csl-entry" role="listitem">
Grolemund, Garrett, and Hadley Wickham. 2017. <em>R for Data Science</em>. First. O’Reilly Media. <a href="https://r4ds.had.co.nz/">https://r4ds.had.co.nz/</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02-visualization.html" class="pagination-link" aria-label="Data Visualization">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Visualization</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-tidy.html" class="pagination-link" aria-label="Data Importing and Tidy Data">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Importing and Tidy Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/moderndive/ModernDive_book/edit/v2/03-wrangling.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/moderndive/ModernDive_book/blob/v2/03-wrangling.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/moderndive/ModernDive_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>