<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An open-source and fully-reproducible electronic textbook for teaching statistical inference using tidyverse data science tools.">

<title>6&nbsp; Multiple Regression – Statistical Inference via Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-sampling.html" rel="next">
<link href="./05-regression.html" rel="prev">
<link href="./images/logos/favicons/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-36bf55b16c7cb4b1420f41495cb5446a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-4e061325f75ba7fba053004d9d2e9411.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-36bf55b16c7cb4b1420f41495cb5446a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-YVFBK9P73R"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YVFBK9P73R');
</script>

<!-- Open Graph Meta Tags -->
<meta property="og:title" content="6&nbsp; Multiple Regression – Statistical Inference via Data Science">
<meta property="og:description" content="An open-source and fully-reproducible electronic textbook for teaching statistical inference using tidyverse data science tools.">
<meta property="og:image" content="https://moderndive.com/v2/images/logos/v2_cover.jpg">
<meta property="og:url" content="https://moderndive.com/v2/">
<meta name="twitter:card" content="summary_large_image">

<!-- Set up favicon -->
<link rel="icon" href="images/logos/favicons/favicon.ico" type="image/x-icon">

<!-- Redirect to ModernDive V2 -->
<script>
  if (window.location.pathname === '/v2') {
    window.location.replace(window.location.pathname + '/');
  }
</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-regression.html">Statistical Modeling with moderndive</a></li><li class="breadcrumb-item"><a href="./06-multiple-regression.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Inference via Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/moderndive/ModernDive_book/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome to ModernDive (v2)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-foreword.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foreword</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with Data in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data Science with tidyverse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-tidy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Importing and Tidy Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Modeling with moderndive</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-multiple-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Inference with infer</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estimation, Confidence Intervals, and Bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-inference-for-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Inference for Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Conclusion</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-tell-your-story-with-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Tell Your Story with Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./91-appendixA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Statistical Background</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./92-appendixB.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Inference Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./93-appendixC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Tips and Tricks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./94-appendixD.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Learning Check Solutions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./95-appendixE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">The Theory Behind the Bootstrap Method</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./96-glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-mult-reg-packages" id="toc-sec-mult-reg-packages" class="nav-link active" data-scroll-target="#sec-mult-reg-packages">Needed packages</a></li>
  <li><a href="#sec-model4" id="toc-sec-model4" class="nav-link" data-scroll-target="#sec-model4"><span class="header-section-number">6.1</span> One numerical and one categorical explanatory variable</a>
  <ul class="collapse">
  <li><a href="#sec-model4EDA" id="toc-sec-model4EDA" class="nav-link" data-scroll-target="#sec-model4EDA"><span class="header-section-number">6.1.1</span> Exploratory data analysis</a></li>
  <li><a href="#sec-model4interactiontable" id="toc-sec-model4interactiontable" class="nav-link" data-scroll-target="#sec-model4interactiontable"><span class="header-section-number">6.1.2</span> Model with interactions</a></li>
  <li><a href="#sec-model4table" id="toc-sec-model4table" class="nav-link" data-scroll-target="#sec-model4table"><span class="header-section-number">6.1.3</span> Model without interactions</a></li>
  <li><a href="#sec-model4points" id="toc-sec-model4points" class="nav-link" data-scroll-target="#sec-model4points"><span class="header-section-number">6.1.4</span> Observed responses, fitted values, and residuals</a></li>
  </ul></li>
  <li><a href="#sec-model3" id="toc-sec-model3" class="nav-link" data-scroll-target="#sec-model3"><span class="header-section-number">6.2</span> Two numerical explanatory variables</a>
  <ul class="collapse">
  <li><a href="#sec-model3EDA" id="toc-sec-model3EDA" class="nav-link" data-scroll-target="#sec-model3EDA"><span class="header-section-number">6.2.1</span> Exploratory data analysis</a></li>
  <li><a href="#sec-model3table" id="toc-sec-model3table" class="nav-link" data-scroll-target="#sec-model3table"><span class="header-section-number">6.2.2</span> Multiple regression with two numerical regressors</a></li>
  <li><a href="#sec-model3points" id="toc-sec-model3points" class="nav-link" data-scroll-target="#sec-model3points"><span class="header-section-number">6.2.3</span> Observed/fitted values and residuals</a></li>
  </ul></li>
  <li><a href="#sec-mult-reg-conclusion" id="toc-sec-mult-reg-conclusion" class="nav-link" data-scroll-target="#sec-mult-reg-conclusion"><span class="header-section-number">6.3</span> Conclusion</a>
  <ul class="collapse">
  <li><a href="#additional-resources" id="toc-additional-resources" class="nav-link" data-scroll-target="#additional-resources"><span class="header-section-number">6.3.1</span> Additional resources</a></li>
  <li><a href="#whats-to-come" id="toc-whats-to-come" class="nav-link" data-scroll-target="#whats-to-come"><span class="header-section-number">6.3.2</span> What’s to come?</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/moderndive/ModernDive_book/edit/v2/06-multiple-regression.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/moderndive/ModernDive_book/blob/v2/06-multiple-regression.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/moderndive/ModernDive_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<img src="https://moderndive.com/wide_format.png" alt="ModernDive" style="max-width: 100%; width: 100%; height: auto; display: block; margin: 0 auto; padding-top: 10px;">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-regression.html">Statistical Modeling with moderndive</a></li><li class="breadcrumb-item"><a href="./06-multiple-regression.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-multiple-regression" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled" title="In this chapter, you'll learn how to:">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>In this chapter, you’ll learn how to:
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Fit a multiple regression model with one numerical and one categorical predictor</li>
<li>Distinguish between <em>parallel-slopes</em> and <em>interaction</em> models</li>
<li>Interpret regression coefficients when more than one predictor is present</li>
<li>Recognize when interaction effects matter for the story your data tells</li>
</ul>
</div>
</div>
<p>In <a href="05-regression.html" class="quarto-xref"><span>Chapter 5</span></a>, we studied simple linear regression as a model that represents the relationship between two variables: an outcome variable or response <span class="math inline">\(y\)</span> and an explanatory variable or regressor <span class="math inline">\(x\)</span>. Furthermore, to keep things simple, we only considered models with one explanatory <span class="math inline">\(x\)</span> variable that was either numerical in <a href="05-regression.html#sec-model1" class="quarto-xref"><span>Section 5.1</span></a> or categorical in <a href="05-regression.html#sec-model2" class="quarto-xref"><span>Section 5.2</span></a>.</p>
<p>In this chapter, we introduce multiple linear regression, the direct extension to simple linear regression when more than one explanatory variable is taken into account to explain changes in the outcome variable. As we show in the next few sections, much of the material developed for simple linear regression translates directly into multiple linear regression, but the interpretation of the associated effect of any one explanatory variable must be made taking into account the other explanatory variables included in the model.</p>
<section id="sec-mult-reg-packages" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sec-mult-reg-packages">Needed packages</h2>
<p>If needed, read <a href="01-getting-started.html#sec-packages" class="quarto-xref"><span>Section 1.3</span></a> for information on how to install and load R packages.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moderndive)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="sec-model4" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-model4"><span class="header-section-number">6.1</span> One numerical and one categorical explanatory variable</h2>
<p>We continue using the UN member states dataset introduced in <a href="05-regression.html#sec-model1" class="quarto-xref"><span>Section 5.1</span></a>. Recall that we studied the relationship between the outcome variable fertility rate, <span class="math inline">\(y\)</span>, and the regressor life expectancy, <span class="math inline">\(x\)</span>.</p>
<p>In this section, we introduce one additional regressor to this model: the categorical variable <code>income group</code> with four categories: <code>Low income</code>, <code>Lower middle income</code>, <code>Upper middle income</code>, and <code>High income</code>. We now want to study how fertility rate changes due to changes in life expectancy and different income levels. To do this, we use <em>multiple regression</em>. Observe that we now have:</p>
<ol type="1">
<li>A numerical outcome variable <span class="math inline">\(y\)</span>, the fertility rate in a given country or state, and</li>
<li>Two explanatory variables:
<ol type="a">
<li>A numerical explanatory variable <span class="math inline">\(x_1\)</span>, the life expectancy.</li>
<li>A categorical explanatory variable <span class="math inline">\(x_2\)</span>, the income group.</li>
</ol></li>
</ol>
<section id="sec-model4EDA" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="sec-model4EDA"><span class="header-section-number">6.1.1</span> Exploratory data analysis</h3>
<p>The UN member states data frame is included in the <code>moderndive</code> package. To keep things simple, we <code>select()</code> only the subset of the variables needed here, and save this data in a new data frame called <code>UN_data_ch6</code>. Note that the variables used are different than the ones chosen in <a href="05-regression.html" class="quarto-xref"><span>Chapter 5</span></a>. We also set the <code>income</code> variable to be a <code>factor</code> so that its levels show up in the expected order.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>UN_data_ch6 <span class="ot">&lt;-</span> un_member_states_2024 <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country, </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>         life_expectancy_2022, </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>         fertility_rate_2022, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>         income_group_2024)<span class="sc">|&gt;</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()<span class="sc">|&gt;</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">life_exp =</span> life_expectancy_2022, </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">fert_rate =</span> fertility_rate_2022, </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">income =</span> income_group_2024)<span class="sc">|&gt;</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">income =</span> <span class="fu">factor</span>(income, </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>                         <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Low income"</span>, <span class="st">"Lower middle income"</span>, </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Upper middle income"</span>, <span class="st">"High income"</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Recall the three common steps in an exploratory data analysis we saw in <a href="05-regression.html#sec-model1EDA" class="quarto-xref"><span>Section 5.1.1</span></a>:</p>
<ol type="1">
<li>Inspecting a sample of raw values.</li>
<li>Computing summary statistics.</li>
<li>Creating data visualizations.</li>
</ol>
<p>We first look at the raw data values by either looking at <code>UN_data_ch6</code> using RStudio’s spreadsheet viewer or by using the <code>glimpse()</code> function from the <code>dplyr</code> package:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(UN_data_ch6)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 182
Columns: 4
$ country   &lt;chr&gt; "Afghanistan", "Albania", "Algeria", "Angola", "Antigua and …
$ life_exp  &lt;dbl&gt; 53.6, 79.5, 78.0, 62.1, 77.8, 78.3, 76.1, 83.1, 82.3, 74.2, …
$ fert_rate &lt;dbl&gt; 4.3, 1.4, 2.7, 5.0, 1.6, 1.9, 1.6, 1.6, 1.5, 1.6, 1.4, 1.8, …
$ income    &lt;fct&gt; Low income, Upper middle income, Lower middle income, Lower …</code></pre>
</div>
</div>
<p>The variable <code>country</code> contains all the UN member states. R reads this variable as character, <code>&lt;chr&gt;</code>, and beyond the country identification it will not be needed for the analysis. The variables life expectancy, <code>life_exp</code>, and fertility rate, <code>fert_rate</code>, are numerical, and the variable income, <code>income</code>, is categorical. In R, categorical variables are called factors and the categories are factor levels.</p>
<p>We also display a random sample of 10 rows of the 182 rows corresponding to different countries in <a href="#tbl-model4-data-preview" class="quarto-xref">Table&nbsp;<span>6.1</span></a>. Remember due to the random nature of the sampling, you will likely end up with a different subset of 10 rows.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>UN_data_ch6 <span class="sc">|&gt;</span> <span class="fu">sample_n</span>(<span class="at">size =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-model4-data-preview" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model4-data-preview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;6.1: A random sample of 10 out of 182 UN member states
</figcaption>
<div aria-describedby="tbl-model4-data-preview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">country</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">life_exp</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">fert_rate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Trinidad and Tobago</td>
<td style="text-align: right;">75.9</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: left;">High income</td>
</tr>
<tr class="even">
<td style="text-align: left;">Micronesia, Federated States of</td>
<td style="text-align: right;">74.4</td>
<td style="text-align: right;">2.6</td>
<td style="text-align: left;">Lower middle income</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North Macedonia</td>
<td style="text-align: right;">76.8</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: left;">Upper middle income</td>
</tr>
<tr class="even">
<td style="text-align: left;">Portugal</td>
<td style="text-align: right;">81.5</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: left;">High income</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Madagascar</td>
<td style="text-align: right;">68.2</td>
<td style="text-align: right;">3.7</td>
<td style="text-align: left;">Low income</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cambodia</td>
<td style="text-align: right;">70.7</td>
<td style="text-align: right;">2.3</td>
<td style="text-align: left;">Lower middle income</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dominica</td>
<td style="text-align: right;">78.2</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: left;">Upper middle income</td>
</tr>
<tr class="even">
<td style="text-align: left;">Peru</td>
<td style="text-align: right;">68.9</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: left;">Upper middle income</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cyprus</td>
<td style="text-align: right;">79.7</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: left;">High income</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guinea-Bissau</td>
<td style="text-align: right;">63.7</td>
<td style="text-align: right;">3.8</td>
<td style="text-align: left;">Low income</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Life expectancy, <code>life_exp</code>, is an estimate of how many years, on average, a person in a given country is expected to live. Fertility rate, <code>fert_rate</code>, is the average number of live births per woman of childbearing age in a country. As we did in our exploratory data analyses in <a href="05-regression.html#sec-model1EDA" class="quarto-xref"><span>Section 5.1.1</span></a> and <a href="05-regression.html#sec-model2EDA" class="quarto-xref"><span>Section 5.2.1</span></a> from <a href="05-regression.html" class="quarto-xref"><span>Chapter 5</span></a>, we find summary statistics:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>UN_data_ch6 <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(life_exp, fert_rate, income) <span class="sc">|&gt;</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy_summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">column</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">life_exp</td>
<td style="text-align: right;">182</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">numeric</td>
<td style="text-align: right;">53.6</td>
<td style="text-align: right;">69.4</td>
<td style="text-align: right;">73.67</td>
<td style="text-align: right;">75.2</td>
<td style="text-align: right;">78.4</td>
<td style="text-align: right;">86.4</td>
<td style="text-align: right;">6.86</td>
</tr>
<tr class="even">
<td style="text-align: left;">fert_rate</td>
<td style="text-align: right;">182</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">numeric</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">2.49</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">3.2</td>
<td style="text-align: right;">6.6</td>
<td style="text-align: right;">1.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Low income</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">income</td>
<td style="text-align: right;">52</td>
<td style="text-align: left;">Lower middle income</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">income</td>
<td style="text-align: right;">49</td>
<td style="text-align: left;">Upper middle income</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">income</td>
<td style="text-align: right;">56</td>
<td style="text-align: left;">High income</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Recall that each row in <code>UN_data_ch6</code> represents a particular country or UN member state. The <code>tidy_summary()</code> function shows a summary for the numerical variables life expectancy (<code>life_exp</code>), fertility rate (<code>fert_rate</code>), and the categorical variable income group (<code>income</code>). When the variable is numerical, the <code>tidy_summary()</code> function provides the total number of observations in the data frame, the five-number summary, the mean, and the standard deviation.</p>
<p>For example, the first row of our summary refers to life expectancy as <code>life_exp</code>. There are 182 observations for this variable, it is a numerical variable, and the first quartile, <code>Q1</code>, is 69.4; this means that the life expectancy of 25% of the UN member states is less than 69.4 years. When a variable in the dataset is categorical, also called a <code>factor</code>, the summary shows all the categories or factor levels and the number of observations for each level. For example, income group (<code>income</code>) is a factor with four levels: <code>Low Income</code>, <code>Lower middle income</code>, <code>Upper middle income</code>, and <code>High income</code>. The summary also provides the number of states for each factor level; observe, for example, that the dataset has 56 UN member states that are considered <code>High Income</code> states.</p>
<p>Furthermore, we can compute the correlation coefficient between our two numerical variables: <code>life_exp</code> and <code>fert_rate</code>. Recall from <a href="05-regression.html#sec-model1EDA" class="quarto-xref"><span>Section 5.1.1</span></a> that correlation coefficients only exist between numerical variables. We observe that they are “strongly negatively” correlated.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>UN_data_ch6 <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_correlation</span>(<span class="at">formula =</span> fert_rate <span class="sc">~</span> life_exp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
     cor
   &lt;dbl&gt;
1 -0.815</code></pre>
</div>
</div>
<p>We are ready to create data visualizations, the last of our exploratory data analysis. Given that the outcome variable <code>fert_rate</code> and explanatory variable <code>life_exp</code> are both numerical, we can create a scatterplot to display their relationship, as we did in <a href="05-regression.html#fig-numxplot1" class="quarto-xref">Figure&nbsp;<span>5.2</span></a>. But this time, we incorporate the categorical variable <code>income</code> by <code>mapping</code> this variable to the <code>color</code> aesthetic, thereby creating a <em>colored</em> scatterplot.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(UN_data_ch6, <span class="fu">aes</span>(<span class="at">x =</span> life_exp, <span class="at">y =</span> fert_rate, <span class="at">color =</span> income)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Life Expectancy"</span>, <span class="at">y =</span> <span class="st">"Fertility Rate"</span>, <span class="at">color =</span> <span class="st">"Income group"</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-numxcatxplot1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-numxcatxplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-multiple-regression_files/figure-html/fig-numxcatxplot1-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="FIGURE&nbsp;6.1: Colored scatterplot of life expectancy and fertility rate."><img src="06-multiple-regression_files/figure-html/fig-numxcatxplot1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-numxcatxplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;6.1: Colored scatterplot of life expectancy and fertility rate.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In the resulting <a href="#fig-numxcatxplot1" class="quarto-xref">Figure&nbsp;<span>6.1</span></a>, observe that <code>ggplot()</code> assigns a default color scheme to the points and to the lines associated with the four levels of <code>income</code>: <code>Low income</code>, <code>Lower middle income</code>, <code>Upper middle income</code>, and <code>High income</code>. Furthermore, the <code>geom_smooth(method = "lm", se = FALSE)</code> layer automatically fits a different regression line for each group.</p>
<p>We can see some interesting trends. First, observe that we get a different line for each income group. Second, the slopes for all the income groups are negative. Third, the slope for the <code>High income</code> group is clearly less steep than the slopes for all other three groups. So, the changes in fertility rate due to changes in life expectancy are dependent on the level of income of a given country. Fourth, observe that high-income countries have, in general, high life expectancy and low fertility rates.</p>
</section>
<section id="sec-model4interactiontable" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="sec-model4interactiontable"><span class="header-section-number">6.1.2</span> Model with interactions</h3>
<p>We can represent the four regression lines in <a href="#fig-numxcatxplot1" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> as a multiple regression model with <em>interactions</em>. </p>
<p>Before we do this, however, we review a linear regression with only one categorical explanatory variable. Recall in <a href="05-regression.html#sec-model2table" class="quarto-xref"><span>Section 5.2.2</span></a> we fit a regression model for each country life expectancy as a function of the corresponding continent. We produce the corresponding analysis here, now using the fertility rate as the response variable and the income group as the categorical explanatory variable. We’ll use slightly different notation to what was done previously to make the model more general.</p>
<p>A linear model with a categorical explanatory variable is called a one-factor model where factor refers to the categorical explanatory variable and the categories are also called factor levels. We represent the categories using indicator functions or dummy variables. In our UN data example, The variable <code>income</code> has four categories or levels: <code>Low income</code>, <code>Lower middle income</code>, <code>Upper middle income</code>, and <code>High income</code>. The corresponding dummy variables needed are:</p>
<p><span class="math display">\[
D_1 = \left\{
\begin{array}{ll}
1 &amp; \text{if the UN member state has low income} \phantom{asfdasfd} \\
0 &amp; \text{otherwise}\end{array}
\right.
\]</span> <span class="math display">\[
D_2 = \left\{
\begin{array}{ll}
1 &amp; \text{if the UN member state has lower middle income} \\
0 &amp; \text{otherwise}\end{array}
\right.
\]</span> <span class="math display">\[
D_3 = \left\{
\begin{array}{ll}
1 &amp; \text{if the UN member state has high middle income}\phantom{a} \\
0 &amp; \text{otherwise}\end{array}
\right.
\]</span> <span class="math display">\[
D_4 = \left\{
\begin{array}{ll}
1 &amp; \text{if the UN member state has high income} \phantom{asfdafd}\\
0 &amp; \text{otherwise}\end{array}
\right.\\
\]</span></p>
<p>So, for example, if a given UN member state has <code>Low income</code>, its dummy variables are <span class="math inline">\(D_1 = 1\)</span> and <span class="math inline">\(D_2 = D_3 = D_4 = 0\)</span>. Similarly, if another UN member state has <code>High  middle income</code>, then its dummy variables would be <span class="math inline">\(D_1 = D_2 = D_4 = 0\)</span> and <span class="math inline">\(D_3 = 1\)</span>. Using dummy variables, the mathematical formulation of the linear regression for our example is:</p>
<p><span class="math display">\[\hat y = \widehat{\text{fert rate}} = b_0 + b_2 D_2 + b_3 D_3 + b_4 D_4\]</span></p>
<p>or if we want to express it in terms of the <span class="math inline">\(i\)</span>th observation in our dataset, we can include the <span class="math inline">\(i\)</span>th subscript:</p>
<p><span class="math display">\[\hat y_i = \widehat{\text{fert rate}} = b_0 + b_2 D_{2i} + b_3 D_{3i} + b_4 D_{4i}\]</span></p>
<p>Recall that the coefficient <span class="math inline">\(b_0\)</span> represents the intercept and the coefficients <span class="math inline">\(b_2\)</span>, <span class="math inline">\(b_3\)</span>, and <span class="math inline">\(b_4\)</span> are the offsets based on the appropriate category. The dummy variables, <span class="math inline">\(D_2\)</span>, <span class="math inline">\(D_3\)</span>, and <span class="math inline">\(D_4\)</span>, take the values of zero or one depending on the corresponding category of any given country. Observe also that <span class="math inline">\(D_1\)</span> does not appear in the model. The reason for this is entirely mathematical: if the model would contain an intercept and all the dummy variables, the model would be over-specified, that is, it would contain one redundant explanatory variable. The solution is to drop one of the variables. We keep the intercept because it provides flexibility when interpreting more complicated models, and we drop one of the dummy variables which, by default in R, is the first dummy variable, <span class="math inline">\(D_1\)</span>. This does not mean that we are losing information of the first level <span class="math inline">\(D_1\)</span>. If a country is part of the <code>Low income</code> level, <span class="math inline">\(D_1 = 1\)</span>, <span class="math inline">\(D_2 = D_3 = D_4 = 0\)</span>, so most of the terms in the regression are zero and the linear regression becomes:</p>
<p><span class="math display">\[\hat y = \widehat{\text{fert rate}} = b_0\]</span> So the intercept represents the average fertility rate when the country is a <code>Low income</code> country. Similarly, if another country is part of the <code>High middle income</code> level, then <span class="math inline">\(D_1 = D_2 = D_4 = 0\)</span> and <span class="math inline">\(D_3 = 1\)</span> so the linear regression becomes:</p>
<p><span class="math display">\[\hat y = \widehat{\text{fert rate}} = b_0 + b_3\]</span> The average fertility rate for a <code>High middle income</code> country is <span class="math inline">\(b_0 + b_3\)</span>. Observe that <span class="math inline">\(b_3\)</span> is an <em>offset</em> for life expectancy between the baseline level and the <code>High middle income</code> level. The same logic applies to the model for each possible income category.</p>
<p>We calculate the regression coefficients using the <code>lm()</code> function and the command <code>coef()</code> to retrieve the coefficients of the linear regression:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>one_factor_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(fert_rate <span class="sc">~</span> income, <span class="at">data =</span> UN_data_ch6)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(one_factor_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We present these results on a table with the mathematical notation used above:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Coefficients</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">b0</td>
<td style="text-align: right;">4.28</td>
</tr>
<tr class="even">
<td style="text-align: left;">incomeLower middle income</td>
<td style="text-align: left;">b2</td>
<td style="text-align: right;">-1.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">incomeUpper middle income</td>
<td style="text-align: left;">b3</td>
<td style="text-align: right;">-2.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">incomeHigh income</td>
<td style="text-align: left;">b4</td>
<td style="text-align: right;">-2.65</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The first level, <code>Low income</code>, is the “baseline” group. The average fertility rate for <code>Low income</code> UN member states is 4.28. Similarly, the average fertility rate for <code>Upper middle income</code> member states is 4.28 + -2.25 = 2.03.</p>
<p>We are now ready to study the multiple linear regression model with interactions shown in <a href="#fig-numxcatxplot1" class="quarto-xref">Figure&nbsp;<span>6.1</span></a>. In this figure we can identify three different effects. First, for any fixed level of life expectancy, observe that there are four different fertility rates. They represent the effect of the categorical explanatory variable, <code>income</code>. Second, for any given regression line, the slope represents the change in average fertility rate due to changes on life expectancy. This is the effect of the numerical explanatory variable <code>life_exp</code>. Third, observe that the slope of the line depends on the income level; as an illustration, observe that for <code>High income</code> member states the slope is less steep than for <code>Low income</code> member states. When the slope changes due to changes in the explanatory variable, we call this an <strong>interaction</strong> effect.</p>
<p>The mathematical formulation of the linear regression model with two explanatory variables, one numerical and one categorical, and interactions is:</p>
<p><span class="math display">\[\begin{aligned}\widehat{y} = \widehat{\text{fert rate}} = b_0
&amp;+ b_{02}D_2 + b_{03}D_3 + b_{04}D_4 \\
&amp;+ b_1x \\
&amp;+ b_{12}xD_2 + b_{13}xD_3 + b_{14}xD_4\end{aligned}\]</span></p>
<p>The linear regression shows how the average life expectancy is affected by the categorical variable, the numerical variable, and the interaction effects. There are eight coefficients in our model and we have separated their coefficients into three lines to highlight their different roles. The first line shows the intercept and the effects of the categorical explanatory variables. Recall that <span class="math inline">\(D_2\)</span>, <span class="math inline">\(D_3\)</span>, and <span class="math inline">\(D_4\)</span> are the dummy variables in the model and each is equal to one or zero depending on the category of the country at hand; correspondingly, the coefficients <span class="math inline">\(b_{02}\)</span>, <span class="math inline">\(b_{03}\)</span>, and <span class="math inline">\(b_{04}\)</span> are the offsets with respect to the baseline level of the intercept, <span class="math inline">\(b_0\)</span>. Recall that the first dummy variable has been dropped and the intercept captures this effect. The second line in the equation represents the effect of the numerical variable, <span class="math inline">\(x\)</span>. In our example <span class="math inline">\(x\)</span> is the value of life expectancy. The coefficient <span class="math inline">\(b_1\)</span> is the slope of the line and represents the change in fertility rate due to one unit change in life expectancy. The third line in the equation represents the interaction effects on the slopes. Observe that they are a combination of life expectancy, <span class="math inline">\(x\)</span>, and income level, <span class="math inline">\(D_2\)</span>, <span class="math inline">\(D_3\)</span>, and <span class="math inline">\(D_4\)</span>. What these interaction effects do is to modify the slope for different levels of income. For a <code>Low income</code> member state, the dummy variables are <span class="math inline">\(D_1 = 1\)</span>, <span class="math inline">\(D_2 = D_3 = D_4 = 0\)</span> and our linear regression is:</p>
<p><span class="math display">\[\begin{aligned}\widehat{y} = \widehat{\text{fert rate}} &amp;= b_0 + b_{02}\cdot 0 + b_{03}\cdot 0 + b_{04}\cdot 0 + b_1x + b_{12}x\cdot 0 + b_{13}x\cdot 0 + b_{14}x\cdot 0\\
&amp; = b_0 + b_1x \end{aligned}\]</span></p>
<p>Similarly, for a <code>High income</code> member state, the dummy variables are <span class="math inline">\(D_1 = D_2 =D_3 = 0\)</span>, and <span class="math inline">\(D_4 = 1\)</span>. We take into account the offsets for the intercept, <span class="math inline">\(b_{04}\)</span>, and the slope, <span class="math inline">\(b_{14}\)</span>, and the linear regression becomes:</p>
<p><span class="math display">\[\begin{aligned}\widehat{y} = \widehat{\text{fert rate}} &amp;= b_0 + b_{02}\cdot 0 + b_{03}\cdot 0 + b_{04}\cdot 1 + b_1 x  + b_{12}x\cdot 0 + b_{13}x\cdot 0 + b_{14}x\cdot 1\\
&amp; = b_0 + b_{04} +  b_1x + b_{14}x\\
&amp; = (b_0 + b_{04}) + (b_1 + b_{14})\cdot x\end{aligned}\]</span></p>
<p>Observe how the intercept and the slope are different for a <code>High income</code> member state when compared to the baseline <code>Low income</code> member state. As an illustration, we construct this multiple linear regression for the UN member state dataset in R. We first “fit” the model using the <code>lm()</code> “linear model” function and then find the coefficients using the function <code>coef()</code>. In R, the formula used is <code>y ~ x1 + x2 + x1:x2</code> where <code>x1</code> and <code>x2</code> are the variable names in the dataset and represent the main effects while <code>x1:x2</code> is the interaction term. For simplicity, we can also write <code>y ~ x1 * x2</code> as the <code>*</code> sign accounts for both, main effects and interaction effects. R would let both <code>x1</code> and <code>x2</code> be either explanatory or numerical, and we need to make sure the dataset format is appropriate for the regression we want to run. Here is the code for our example:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model and get the coefficients of the model</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>model_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(fert_rate <span class="sc">~</span> life_exp <span class="sc">*</span> income, <span class="at">data =</span> UN_data_ch6)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(model_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-regtable-interaction" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regtable-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;6.2: Regression table for interaction model
</figcaption>
<div aria-describedby="tbl-regtable-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Coefficients</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">b0</td>
<td style="text-align: right;">11.918</td>
</tr>
<tr class="even">
<td style="text-align: left;">incomeLower middle income</td>
<td style="text-align: left;">b02</td>
<td style="text-align: right;">-1.504</td>
</tr>
<tr class="odd">
<td style="text-align: left;">incomeUpper middle income</td>
<td style="text-align: left;">b03</td>
<td style="text-align: right;">-1.893</td>
</tr>
<tr class="even">
<td style="text-align: left;">incomeHigh income</td>
<td style="text-align: left;">b04</td>
<td style="text-align: right;">-6.580</td>
</tr>
<tr class="odd">
<td style="text-align: left;">life_exp</td>
<td style="text-align: left;">b1</td>
<td style="text-align: right;">-0.118</td>
</tr>
<tr class="even">
<td style="text-align: left;">incomeLower middle income:life_exp</td>
<td style="text-align: left;">b12</td>
<td style="text-align: right;">0.013</td>
</tr>
<tr class="odd">
<td style="text-align: left;">incomeUpper middle income:life_exp</td>
<td style="text-align: left;">b13</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="even">
<td style="text-align: left;">incomeHigh income:life_exp</td>
<td style="text-align: left;">b14</td>
<td style="text-align: right;">0.072</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>We can match the coefficients with the values computed in <a href="#tbl-regtable-interaction" class="quarto-xref">Table&nbsp;<span>6.2</span></a>: the fitted fertility rate <span class="math inline">\(\widehat{y} = \widehat{\text{fert rate}}\)</span> for <code>Low income</code> countries is</p>
<p><span class="math display">\[\widehat{\text{fert rate}} = b_0 + b_1\cdot x = 11.92 + (-0.12)\cdot x,\]</span></p>
<p>which is the equation of the regression line in <a href="#fig-numxcatxplot1" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> for low income countries. The regression has an intercept of 11.92 and a slope of -0.12. Since life expectancy is greater than zero for all countries, the intercept has no practical interpretation and we only need it to produce the most appropriate line. The interpretation of the slope is: for <code>Low income</code> countries, every additional year of life expectancy reduces the average fertility rate by 0.12 units.</p>
<p>As discussed earlier, the intercept and slope for all the other income groups are determined by taking into account the appropriate offsets. For example, for <code>High income</code> countries <span class="math inline">\(D_4 = 1\)</span> and all other dummy variables are equal to zero. The regression line becomes</p>
<p><span class="math display">\[\widehat{y} = \widehat{\text{fert rate}} = b_0 + b_1x + b_{04} + b_{14}x = (b_0 + b_{04} ) + (b_1+b_{14})x \]</span></p>
<p>where <span class="math inline">\(x\)</span> is life expectancy, <code>life_exp</code>. The intercept is <code>(Intercept) + incomeHigh income</code>:</p>
<p><span class="math display">\[b_0 + b_{04} = 11.92 +(-6.58) = 5.34,\]</span></p>
<p>and the slope for these <code>High income</code> countries is <code>life_exp + life_exp:incomeHigh income</code> corresponding to</p>
<p><span class="math display">\[b_1 + b_{14}=  -0.12 + 0.07 = -0.05.\]</span></p>
<p>For <code>High income</code> countries, every additional year of life expectancy reduces the average fertility rate by 0.05 units. The intercepts and slopes for other income levels are calculated similarly.</p>
<p>Since the life expectancy for <code>Low income</code> countries has a steeper slope than <code>High income</code> countries, one additional year of life expectancy will decrease fertility rates more for the low-income group than for the high-income group. This is consistent with our observation from <a href="#fig-numxcatxplot1" class="quarto-xref">Figure&nbsp;<span>6.1</span></a>. When the associated effect of one variable <em>depends on the value of another variable</em> we say that there is an interaction effect. This is the reason why the regression slopes are different for different income groups.</p>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC6.1)</strong> What is the goal of including an interaction term in a multiple regression model?</p>
<ul>
<li>A. To create more variables for analysis.</li>
<li>B. To account for the effect of one explanatory variable on the response while considering the influence of another explanatory variable.</li>
<li>C. To make the model more complex without any real benefit.</li>
<li>D. To automatically improve the fit of the regression line.</li>
</ul>
<p><strong>(LC6.2)</strong> How does the inclusion of both main effects and interaction terms in a regression model affect the interpretation of individual coefficients?</p>
<ul>
<li>A. They represent simple marginal effects.</li>
<li>B. They become meaningless.</li>
<li>C. They are conditional effects, depending on the level of the interacting variables.</li>
<li>D. They are interpreted in the same way as in models without interactions.</li>
</ul>
<p><strong>(LC6.3)</strong> Which statement about the use of dummy variables in regression models is correct?</p>
<ul>
<li>A. Dummy variables are used to represent numerical variables.</li>
<li>B. Dummy variables are used to represent categorical variables at least two levels.</li>
<li>C. Dummy variables always decrease the R-squared value.</li>
<li>D. Dummy variables are unnecessary in regression models.</li>
</ul>
</div>
</section>
<section id="sec-model4table" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="sec-model4table"><span class="header-section-number">6.1.3</span> Model without interactions</h3>
<p>We can simplify the previous model by removing the interaction effects. The model still represents different income groups with different regression lines by allowing different intercepts but all the lines have the same slope: they are parallel as shown in <a href="#fig-numxcatx-parallel" class="quarto-xref">Figure&nbsp;<span>6.2</span></a>.</p>
<p>To plot parallel slopes we use the function <a href="https://moderndive.github.io/moderndive/reference/geom_parallel_slopes.html"><code>geom_parallel_slopes()</code></a> that is included in the <code>moderndive</code> package. To use this function you need to load both the <code>ggplot2</code> and <code>moderndive</code> packages. Observe how the code is identical to the one used for the model with interactions in <a href="#fig-numxcatxplot1" class="quarto-xref">Figure&nbsp;<span>6.1</span></a>, but now the <code>geom_smooth(method = "lm", se = FALSE)</code> layer is replaced with <code>geom_parallel_slopes(se = FALSE)</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(UN_data_ch6, <span class="fu">aes</span>(<span class="at">x =</span> life_exp, <span class="at">y =</span> fert_rate, <span class="at">color =</span> income)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Life expectancy"</span>, <span class="at">y =</span> <span class="st">"Fertility rate"</span>, <span class="at">color =</span> <span class="st">"Income group"</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_parallel_slopes</span>(<span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-numxcatx-parallel" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-numxcatx-parallel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-multiple-regression_files/figure-html/fig-numxcatx-parallel-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="FIGURE&nbsp;6.2: Parallel slopes model of fertility rate with life expectancy and income."><img src="06-multiple-regression_files/figure-html/fig-numxcatx-parallel-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-numxcatx-parallel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;6.2: Parallel slopes model of fertility rate with life expectancy and income.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The regression lines for each income group are shown in <a href="#fig-numxcatx-parallel" class="quarto-xref">Figure&nbsp;<span>6.2</span></a>. Observe that the lines are now parallel: they all have the same negative slope. The interpretation of this result is that the change in fertility rate due to changes in life expectancy in a given country are the same regardless the income group of this country.</p>
<p>On the other hand, any two regression lines in <a href="#fig-numxcatx-parallel" class="quarto-xref">Figure&nbsp;<span>6.2</span></a> have different intercepts representing the income group; in particular, observe that for any fixed level of life expectancy the fertility rate is greater for <code>Low income</code> and <code>Lower middle income</code> countries than for <code>Upper middle income</code> and <code>High income</code> countries.</p>
<p>The mathematical formulation of the linear regression model with two explanatory variables, one numerical and one categorical, and without interactions is:</p>
<p><span class="math display">\[\widehat{y} = b_0 + b_{02}D_2 + b_{03}D_3 + b_{04}D_4+ b_1x.\]</span> Observe that the dummy variables only affect the intercept now, and the slope is fully described by <span class="math inline">\(b_1\)</span> for any income group. In the UN data example, a <code>High income</code> country, with <span class="math inline">\(D_4 = 1\)</span> and the other dummy variables equal to zero, will be represented by</p>
<p><span class="math display">\[\widehat{y} = (b_0 + b_{04})+ b_1x.\]</span></p>
<p>To find the coefficients for this regression in R, the formula used is <code>y ~ x1 + x2</code> where <code>x1</code> and <code>x2</code> are the variable names in the dataset and represent the main effects. Observe that the term <code>x1:x2</code> representing the interaction is no longer included. R would let both <code>x1</code> and <code>x2</code> to be either explanatory or numerical; therefore, we should always check that the variable format is appropriate for the regression we want to run. Here is the code for the UN data example:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model:</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>model_no_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(fert_rate <span class="sc">~</span> life_exp <span class="sc">+</span> income, <span class="at">data =</span> UN_data_ch6)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the coefficients of the model</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(model_no_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-regtable-parallel1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regtable-parallel1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;6.3: Regression table for a model without interactions
</figcaption>
<div aria-describedby="tbl-regtable-parallel1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Coefficients</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">b0</td>
<td style="text-align: right;">10.768</td>
</tr>
<tr class="even">
<td style="text-align: left;">incomeLower middle income</td>
<td style="text-align: left;">b02</td>
<td style="text-align: right;">-0.719</td>
</tr>
<tr class="odd">
<td style="text-align: left;">incomeUpper middle income</td>
<td style="text-align: left;">b03</td>
<td style="text-align: right;">-1.239</td>
</tr>
<tr class="even">
<td style="text-align: left;">incomeHigh income</td>
<td style="text-align: left;">b04</td>
<td style="text-align: right;">-1.067</td>
</tr>
<tr class="odd">
<td style="text-align: left;">life_exp</td>
<td style="text-align: left;">b1</td>
<td style="text-align: right;">-0.101</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In this model without interactions presented in <a href="#tbl-regtable-parallel1" class="quarto-xref">Table&nbsp;<span>6.3</span></a>, the slope is the same for all the regression lines, <span class="math inline">\(b_1 = -0.101\)</span>. Assuming that this model is correct, for any UN member state, every additional year of life expectancy reduces the average fertility rate by 0.101 units, regardless of the income level of the member state. The intercept of the regression line for <code>Low income</code> member states is 10.768 while for <code>High income</code> member states is <span class="math inline">\(10.768 + (-1.067) = 9.701\)</span>. The intercepts for other income levels can be determined similarly. We compare the visualizations for both models side-by-side in <a href="#fig-numxcatx-comparison" class="quarto-xref">Figure&nbsp;<span>6.3</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-numxcatx-comparison" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-numxcatx-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-multiple-regression_files/figure-html/fig-numxcatx-comparison-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="FIGURE&nbsp;6.3: Comparison of interaction and parallel slopes models."><img src="06-multiple-regression_files/figure-html/fig-numxcatx-comparison-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-numxcatx-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;6.3: Comparison of interaction and parallel slopes models.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Which one is the preferred model? Looking at the scatterplot and the clusters of points in <a href="#fig-numxcatx-comparison" class="quarto-xref">Figure&nbsp;<span>6.3</span></a>, it does appear that lines with different slopes capture better the behavior of different groups of points. The lines do not appear to be parallel and the interaction model seems more appropriate.</p>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC6.4)</strong> How should a model with one categorical regressor and one numerical regressor, but no interactions, be interpreted?</p>
<ul>
<li>A. The slope of the model for each category is different.</li>
<li>B. The slope of the model for each category is the same.</li>
<li>C. There is no relationship between the categorical regressor and the response.</li>
<li>D. There is no relationship between the numerical regressor and the response.</li>
</ul>
</div>
</section>
<section id="sec-model4points" class="level3" data-number="6.1.4">
<h3 data-number="6.1.4" class="anchored" data-anchor-id="sec-model4points"><span class="header-section-number">6.1.4</span> Observed responses, fitted values, and residuals</h3>
<p>In this subsection, we work with the regression model with interactions. The coefficients for this model were found earlier, saved in <code>model_int</code>, and are displayed in <a href="#tbl-regtable-interaction1" class="quarto-xref">Table&nbsp;<span>6.4</span></a>:</p>
<div class="cell" data-layout-align="center">
<div id="tbl-regtable-interaction1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regtable-interaction1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;6.4: Regression table for interaction model
</figcaption>
<div aria-describedby="tbl-regtable-interaction1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Coefficients</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">b0</td>
<td style="text-align: right;">11.918</td>
</tr>
<tr class="even">
<td style="text-align: left;">incomeLower middle income</td>
<td style="text-align: left;">b02</td>
<td style="text-align: right;">-1.504</td>
</tr>
<tr class="odd">
<td style="text-align: left;">incomeUpper middle income</td>
<td style="text-align: left;">b03</td>
<td style="text-align: right;">-1.893</td>
</tr>
<tr class="even">
<td style="text-align: left;">incomeHigh income</td>
<td style="text-align: left;">b04</td>
<td style="text-align: right;">-6.580</td>
</tr>
<tr class="odd">
<td style="text-align: left;">life_exp</td>
<td style="text-align: left;">b1</td>
<td style="text-align: right;">-0.118</td>
</tr>
<tr class="even">
<td style="text-align: left;">incomeLower middle income:life_exp</td>
<td style="text-align: left;">b12</td>
<td style="text-align: right;">0.013</td>
</tr>
<tr class="odd">
<td style="text-align: left;">incomeUpper middle income:life_exp</td>
<td style="text-align: left;">b13</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="even">
<td style="text-align: left;">incomeHigh income:life_exp</td>
<td style="text-align: left;">b14</td>
<td style="text-align: right;">0.072</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>We can use these coefficients to find the fitted values and residuals for any given observation. As an illustration, we chose two observations from the UN member states dataset, provided the values for the explanatory variables and response, as well as the fitted values and residuals:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">ID</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">fert_rate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">income</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">life_exp</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">fert_rate_hat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: left;">High income</td>
<td style="text-align: right;">79.7</td>
<td style="text-align: right;">1.65</td>
<td style="text-align: right;">-0.35</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">5.7</td>
<td style="text-align: left;">Low income</td>
<td style="text-align: right;">62.4</td>
<td style="text-align: right;">4.52</td>
<td style="text-align: right;">1.18</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The first observation is a <code>High income</code> country with a life expectancy of 79.74 years and an observed fertility rate equal to 1.3. The second observation is a <code>Low income</code> country with a life expectancy of 62.41 years and an observed fertility rate equal to 5.7 The fitted value, <span class="math inline">\(\hat y\)</span>, called <code>fert_rate_hat</code> in the table, is the estimated value of the response determined by the regression line. This value is computed by using the values of the explanatory variables and the coefficients of the linear regression. In addition, recall the difference between the observed response value and the fitted value, <span class="math inline">\(y - \hat y\)</span>, is called the residual.</p>
<p>We illustrate this in <a href="#fig-fitted-values" class="quarto-xref">Figure&nbsp;<span>6.4</span></a>. The vertical line on the left represents the life expectancy value for the <code>Low income</code> country. The y-value for the large dot on the regression line that intersects the vertical line is the fitted value for fertility rate, <span class="math inline">\(\widehat y\)</span>, and the y-value for the large dot above the line is the observed fertility rate, <span class="math inline">\(y\)</span>. The difference between these values, <span class="math inline">\(y - \widehat y\)</span>, is called the residual and in this case is positive. Similarly, the vertical line on the right represents the life expectancy value for the <code>High income</code> country, the y-value for the large dot on the regression line is the fitted fertility rate. The observed y-value for fertility rate is below the regression line making the residual negative.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-fitted-values" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fitted-values-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-multiple-regression_files/figure-html/fig-fitted-values-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="FIGURE&nbsp;6.4: Fitted values for two new countries."><img src="06-multiple-regression_files/figure-html/fig-fitted-values-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fitted-values-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;6.4: Fitted values for two new countries.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We can generalize the study of fitted values and residuals for all the countries in the <code>UN_data_ch6</code> dataset, as shown in <a href="#tbl-model4-points-table" class="quarto-xref">Table&nbsp;<span>6.5</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>regression_points <span class="ot">&lt;-</span> <span class="fu">get_regression_points</span>(model_int)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>regression_points</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-model4-points-table" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model4-points-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;6.5: Regression points (First 10 out of 182 countries)
</figcaption>
<div aria-describedby="tbl-model4-points-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">ID</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">fert_rate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">income</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">life_exp</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">fert_rate_hat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.3</td>
<td style="text-align: left;">Low income</td>
<td style="text-align: right;">53.6</td>
<td style="text-align: right;">5.56</td>
<td style="text-align: right;">-1.262</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: left;">Upper middle income</td>
<td style="text-align: right;">79.5</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">-0.098</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: left;">Lower middle income</td>
<td style="text-align: right;">78.0</td>
<td style="text-align: right;">2.16</td>
<td style="text-align: right;">0.544</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: left;">Lower middle income</td>
<td style="text-align: right;">62.1</td>
<td style="text-align: right;">3.84</td>
<td style="text-align: right;">1.159</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: left;">High income</td>
<td style="text-align: right;">77.8</td>
<td style="text-align: right;">1.74</td>
<td style="text-align: right;">-0.139</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: left;">Upper middle income</td>
<td style="text-align: right;">78.3</td>
<td style="text-align: right;">1.62</td>
<td style="text-align: right;">0.278</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: left;">Upper middle income</td>
<td style="text-align: right;">76.1</td>
<td style="text-align: right;">1.86</td>
<td style="text-align: right;">-0.256</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: left;">High income</td>
<td style="text-align: right;">83.1</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">0.105</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: left;">High income</td>
<td style="text-align: right;">82.3</td>
<td style="text-align: right;">1.53</td>
<td style="text-align: right;">-0.033</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: left;">Upper middle income</td>
<td style="text-align: right;">74.2</td>
<td style="text-align: right;">2.07</td>
<td style="text-align: right;">-0.469</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC6.5)</strong> Compute the observed response values, fitted values, and residuals for the model without interactions.</p>
<p><strong>(LC6.6)</strong> What is the main benefit of visualizing the fitted values and residuals of a multiple regression model?</p>
<ul>
<li>A. To find errors in the dataset.</li>
<li>B. To check the assumptions of the regression model, such as linearity and homoscedasticity.</li>
<li>C. To always improve the model’s accuracy.</li>
<li>D. To increase the complexity of the model.</li>
</ul>
</div>
</section>
</section>
<section id="sec-model3" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-model3"><span class="header-section-number">6.2</span> Two numerical explanatory variables</h2>
<p>We now consider regression models with two numerical explanatory variables. To illustrate this situation we explore the <code>ISLR2</code> R package for the first time in this book using its <code>Credit</code> dataset. This dataset contains simulated information for 400 customers. For the regression model we use the credit card balance (<code>Balance</code>) as the response variable; and the credit limit (<code>Limit</code>), and the income (<code>Income</code>) as the numerical explanatory variables.</p>
<section id="sec-model3EDA" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="sec-model3EDA"><span class="header-section-number">6.2.1</span> Exploratory data analysis</h3>
<p>We load the <code>Credit</code> data frame and to ensure the type of behavior we have become accustomed to in using the <code>tidyverse</code>, we also convert this data frame to be a <code>tibble</code> using <code>as_tibble()</code>. We construct a new data frame <code>credit_ch6</code> with only the variables needed. We do this by using the <code>select()</code> verb as we did in <a href="03-wrangling.html#sec-select" class="quarto-xref"><span>Section 3.8.1</span></a> and, in addition, we save the selecting variables with different names: <code>Balance</code> becomes <code>debt</code>, <code>Limit</code> becomes <code>credit_limit</code>, and <code>Income</code> becomes <code>income</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>credit_ch6 <span class="ot">&lt;-</span> Credit <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">debt =</span> Balance, <span class="at">credit_limit =</span> Limit, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">income =</span> Income, <span class="at">credit_rating =</span> Rating, <span class="at">age =</span> Age)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You can observe the effect of our use of <code>select()</code> by looking at the raw values either in RStudio’s spreadsheet viewer or by using <code>glimpse()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(credit_ch6)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 400
Columns: 5
$ debt          &lt;dbl&gt; 333, 903, 580, 964, 331, 1151, 203, 872, 279, 1350, 1407…
$ credit_limit  &lt;dbl&gt; 3606, 6645, 7075, 9504, 4897, 8047, 3388, 7114, 3300, 68…
$ income        &lt;dbl&gt; 14.9, 106.0, 104.6, 148.9, 55.9, 80.2, 21.0, 71.4, 15.1,…
$ credit_rating &lt;dbl&gt; 283, 483, 514, 681, 357, 569, 259, 512, 266, 491, 589, 1…
$ age           &lt;dbl&gt; 34, 82, 71, 36, 68, 77, 37, 87, 66, 41, 30, 64, 57, 49, …</code></pre>
</div>
</div>
<p>Furthermore, we present a random sample of five out of the 400 credit card holders in <a href="#tbl-model3-data-preview" class="quarto-xref">Table&nbsp;<span>6.6</span></a>. As observed before, each time you run this code, a different subset of five rows is given.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>credit_ch6 <span class="sc">|&gt;</span> <span class="fu">sample_n</span>(<span class="at">size =</span> <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-model3-data-preview" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model3-data-preview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;6.6: Random sample of 5 credit card holders
</figcaption>
<div aria-describedby="tbl-model3-data-preview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">debt</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">credit_limit</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">income</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">credit_rating</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">1402</td>
<td style="text-align: right;">27.2</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">67</td>
</tr>
<tr class="even">
<td style="text-align: right;">1081</td>
<td style="text-align: right;">6922</td>
<td style="text-align: right;">43.7</td>
<td style="text-align: right;">511</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1237</td>
<td style="text-align: right;">7499</td>
<td style="text-align: right;">58.0</td>
<td style="text-align: right;">560</td>
<td style="text-align: right;">67</td>
</tr>
<tr class="even">
<td style="text-align: right;">379</td>
<td style="text-align: right;">4742</td>
<td style="text-align: right;">57.1</td>
<td style="text-align: right;">372</td>
<td style="text-align: right;">79</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1151</td>
<td style="text-align: right;">8047</td>
<td style="text-align: right;">80.2</td>
<td style="text-align: right;">569</td>
<td style="text-align: right;">77</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Note that income is in thousands of dollars while debt and credit limit are in dollars. We can also compute summary statistics using the <code>tidy_summary()</code> function. We only <code>select()</code> the columns of interest for our model as shown in <a href="#tbl-credittable" class="quarto-xref">Table&nbsp;<span>6.7</span></a>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>credit_ch6 <span class="sc">|&gt;</span> <span class="fu">select</span>(debt, credit_limit, income) <span class="sc">|&gt;</span> <span class="fu">tidy_summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-credittable" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-credittable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;6.7: Summary of credit data
</figcaption>
<div aria-describedby="tbl-credittable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">column</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">debt</td>
<td style="text-align: right;">400</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">numeric</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">68.8</td>
<td style="text-align: right;">520.0</td>
<td style="text-align: right;">459.5</td>
<td style="text-align: right;">863.0</td>
<td style="text-align: right;">1999</td>
<td style="text-align: right;">459.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">credit_limit</td>
<td style="text-align: right;">400</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">numeric</td>
<td style="text-align: right;">855.0</td>
<td style="text-align: right;">3088.0</td>
<td style="text-align: right;">4735.6</td>
<td style="text-align: right;">4622.5</td>
<td style="text-align: right;">5872.8</td>
<td style="text-align: right;">13913</td>
<td style="text-align: right;">2308.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income</td>
<td style="text-align: right;">400</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">numeric</td>
<td style="text-align: right;">10.4</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">45.2</td>
<td style="text-align: right;">33.1</td>
<td style="text-align: right;">57.5</td>
<td style="text-align: right;">187</td>
<td style="text-align: right;">35.2</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The mean and median credit card <code>debt</code> are $520.0 and $459.5, respectively. The first quartile for <code>debt</code> is 68.8; this means that 25% of card holders had debts of $68.80 or less. Correspondingly, the mean and median credit card limit, <code>credit_limit</code>, are around $4,736 and $4,622, respectively. Note also that the third quartile of <code>income</code> is 57.5; so 75% of card holders had incomes below $57,500.</p>
<p>We visualize the relationship of the response variable with each of the two explanatory variables using this R code. These plots are shown in <a href="#fig-2numxplot1" class="quarto-xref">Figure&nbsp;<span>6.5</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(credit_ch6, <span class="fu">aes</span>(<span class="at">x =</span> credit_limit, <span class="at">y =</span> debt)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Credit limit (in $)"</span>, <span class="at">y =</span> <span class="st">"Credit card debt (in $)"</span>, </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Debt and credit limit"</span>) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(credit_ch6, <span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">y =</span> debt)) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Income (in $1000)"</span>, <span class="at">y =</span> <span class="st">"Credit card debt (in $)"</span>, </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Debt and income"</span>) <span class="sc">+</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-2numxplot1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2numxplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-multiple-regression_files/figure-html/fig-2numxplot1-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="FIGURE&nbsp;6.5: Relationship between credit card debt and credit limit/income."><img src="06-multiple-regression_files/figure-html/fig-2numxplot1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2numxplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;6.5: Relationship between credit card debt and credit limit/income.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The left plot in <a href="#fig-2numxplot1" class="quarto-xref">Figure&nbsp;<span>6.5</span></a> shows a positive and linear association between credit limit and credit card debt: as credit limit increases so does credit card debt. Observe also that many customers have no credit card debt and there is a cluster of points at the credit card debt value of zero. The right plot in <a href="#fig-2numxplot1" class="quarto-xref">Figure&nbsp;<span>6.5</span></a> shows also positive and somewhat linear association between income and credit card debt, but this association seems weaker and actually appears positive only for incomes larger than $50,000. For lower income values it is not clear there is any association at all.</p>
<p>Since variables <code>debt</code>, <code>credit_limit</code>, and <code>income</code> are numerical, and more importantly, the associations between the response and explanatory variables appear to be linear or close to linear, we can also calculate the correlation coefficient between any two of these variables. Recall that the correlation coefficient is appropriate if the association between the variables is linear. One way to do this is using the <code>get_correlation()</code> command as seen in <a href="05-regression.html#sec-model1EDA" class="quarto-xref"><span>Section 5.1.1</span></a>, once for each explanatory variable with the response <code>debt</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>credit_ch6 <span class="sc">|&gt;</span> <span class="fu">get_correlation</span>(debt <span class="sc">~</span> credit_limit)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>credit_ch6 <span class="sc">|&gt;</span> <span class="fu">get_correlation</span>(debt <span class="sc">~</span> income)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Alternatively, using the <code>select()</code> verb and command <code>cor()</code> we can find all correlations simultaneously by returning a <em>correlation matrix</em> as shown in <a href="#tbl-model3-correlation" class="quarto-xref">Table&nbsp;<span>6.8</span></a>. This matrix shows the correlation coefficient for any pair of variables in the appropriate row/column combination.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>credit_ch6 <span class="sc">|&gt;</span> <span class="fu">select</span>(debt, credit_limit, income) <span class="sc">|&gt;</span> <span class="fu">cor</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-model3-correlation" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model3-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;6.8: Correlation coefficients between credit card debt, credit limit, and income
</figcaption>
<div aria-describedby="tbl-model3-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">debt</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">credit_limit</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">debt</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.862</td>
<td style="text-align: right;">0.464</td>
</tr>
<tr class="even">
<td style="text-align: left;">credit_limit</td>
<td style="text-align: right;">0.862</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.792</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income</td>
<td style="text-align: right;">0.464</td>
<td style="text-align: right;">0.792</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Let’s look at some findings presented in the correlation matrix:</p>
<ol type="1">
<li>The diagonal values are all 1 because, based on the definition of the correlation coefficient, the correlation of a variable with itself is always 1.</li>
<li>The correlation between <code>debt</code> and <code>credit_limit</code> is 0.862. This indicates a strong and positive linear relationship: the greater the credit limit is, the larger is the credit card debt, on average.</li>
<li>The correlation between <code>debt</code> and <code>income</code> is 0.464. The linear relationship is positive albeit somewhat weak. In other words, higher income is only weakly associated with higher debt.</li>
<li>Observe also that the correlation coefficient between the two explanatory variables, <code>credit_limit</code> and <code>income</code>, is 0.792.</li>
</ol>
<p>A useful property of the correlation coefficient is that it is <em>invariant to linear transformations</em>; this means that the correlation between two variables, <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, will be the same as the correlation between <span class="math inline">\((a\cdot x + b)\)</span> and <span class="math inline">\(y\)</span> for any constants <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. To illustrate this, observe that the correlation coefficient between <code>income</code> in <em>thousands of dollars</em> and credit card <code>debt</code> was 0.464. If we now find the correlation income in <em>dollars</em>, by multiplying <code>income</code> by 1000, and credit card <code>debt</code> we get:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>credit_ch6 <span class="sc">|&gt;</span> <span class="fu">get_correlation</span>(debt <span class="sc">~</span> <span class="dv">1000</span> <span class="sc">*</span> income)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    cor
  &lt;dbl&gt;
1 0.464</code></pre>
</div>
</div>
<p>The correlation is exactly the same.</p>
<p>We return to our exploratory data analysis of the multiple regression. The plots in <a href="#fig-2numxplot1" class="quarto-xref">Figure&nbsp;<span>6.5</span></a> correspond to the response and each of the explanatory variables <em>separately</em>. In <a href="#fig-3D-scatterplot" class="quarto-xref">Figure&nbsp;<span>6.6</span></a> we show a 3-dimensional (3D) scatterplot representing the <em>joint</em> relationship of all three variables simultaneously. Each of the 400 observations in the <code>credit_ch6</code> data frame are marked with a blue point where</p>
<ol type="1">
<li>The response variable <span class="math inline">\(y\)</span>, <code>debt</code>, is on the vertical axis.</li>
<li>The regressors <span class="math inline">\(x_1\)</span>, <code>income</code>, and <span class="math inline">\(x_2\)</span>, <code>credit_limit</code>, are on the two axes that form the bottom plane.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-3D-scatterplot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-3D-scatterplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/ISLR2-credit_card_balance_regression_plane.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="FIGURE&nbsp;6.6: 3D scatterplot and regression plane."><img src="images/ISLR2-credit_card_balance_regression_plane.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3D-scatterplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;6.6: 3D scatterplot and regression plane.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In addition, <a href="#fig-3D-scatterplot" class="quarto-xref">Figure&nbsp;<span>6.6</span></a> includes a <em>regression plane</em>. Recall from <a href="05-regression.html#sec-leastsquares" class="quarto-xref"><span>Section 5.3.2</span></a> that the linear regression with one numerical explanatory variable selects the “best-fitting” line: the line that minimizes the <em>sum of squared residuals</em>. When linear regression is performed with two numerical explanatory variables, the solution is a “best-fitting” plane: the plane that minimizes the sum of squared residuals. Visit <a href="https://moderndive.com/v2/regression-plane-ISLR2.html">this website</a> to open an interactive version of this plot in your browser.</p>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC6.7)</strong> Conduct a new exploratory data analysis with the same outcome variable <span class="math inline">\(y\)</span> <code>debt</code> but with <code>credit_rating</code> and <code>age</code> as the new explanatory variables <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>. What can you say about the relationship between a credit card holder’s debt and their credit rating and age?</p>
</div>
</section>
<section id="sec-model3table" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="sec-model3table"><span class="header-section-number">6.2.2</span> Multiple regression with two numerical regressors</h3>
<p>As shown in <a href="#fig-3D-scatterplot" class="quarto-xref">Figure&nbsp;<span>6.6</span></a>, the linear regression with two numerical regressors produces the “best-fitting” plane. We start with a model with no interactions for the two numerical explanatory variables <code>income</code> and <code>credit_limit</code>. In R we consider a model fit with a formula of the form <code>y ~ x1 + x2</code>. We retrieve the regression coefficients using the <code>lm()</code> function and the command <code>coef()</code> to get the coefficients of the linear regression. The regression coefficients are shown in what follows.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>debt_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(debt <span class="sc">~</span> credit_limit <span class="sc">+</span> income, <span class="at">data =</span> credit_ch6)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(debt_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We present these results in a table with the mathematical notation used above:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Coefficients</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">b0</td>
<td style="text-align: right;">-385.179</td>
</tr>
<tr class="even">
<td style="text-align: left;">credit_limit</td>
<td style="text-align: left;">b1</td>
<td style="text-align: right;">0.264</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income</td>
<td style="text-align: left;">b2</td>
<td style="text-align: right;">-7.663</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="1">
<li>We determine the linear regression coefficients using <code>lm(y ~ x1 + x2, data)</code> where <code>x1</code> and <code>x2</code> are the two numerical explanatory variables used.</li>
<li>We extract the coefficients from the output using the <code>coef()</code> command.</li>
</ol>
<p>Let’s interpret the coefficients. The <code>intercept</code> value is -$385.179. If the range of values that the regressors could take include a <code>credit_limit</code> of $0 and an <code>income</code> of $0, the intercept would represent the average credit card debt for an individual with those levels of <code>credit_limit</code> and <code>income</code>. This is not the case in our data and the intercept has no practical interpretation; it is mainly used to determine where the plane should cut the <span class="math inline">\(y\)</span>-intercept to produce the smallest sum of squared residuals.</p>
<p>Each slope in a multiple linear regression is considered a partial slope and represents the marginal or additional contribution of a regressor when it is added to a model that already contains other regressors. This partial slope is typically different than the slope we may find in a simple linear regression for the same regressor. The reason is that, typically, regressors are correlated, so when one regressor is part of a model, indirectly it’s also explaining part of the other regressor. When the second regressor is added to the model, it helps explain only changes in the response that were not already accounted for by the first regressor. For example, the slope for <code>credit_limit</code> is $0.264. Keeping <code>income</code> fixed to some value, for an additional increase of credit limit by one dollar the credit debt increases, on average, by $0.264. Similarly, the slope of <code>income</code> is -$7.663. Keeping <code>credit_limit</code> fixed to some level, for a one unit increase of <code>income</code> ($1000 in actual income), there is an associated decrease of $7.66 in credit card debt, on average.</p>
<p>Putting these results together, the equation of the regression plane that gives us fitted values <span class="math inline">\(\widehat{y}\)</span> = <span class="math inline">\(\widehat{\text{debt}}\)</span> is:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} = \widehat{\text{debt}}  &amp;= b_0 + b_1 \cdot x_1 +  b_2 \cdot x_2\\
&amp;= -385.179 + 0.263 \cdot x_1 - 7.663 \cdot x_2
\end{aligned}
\]</span> where <span class="math inline">\(x_1\)</span> represents credit limit and <span class="math inline">\(x_2\)</span> income.</p>
<p>To illustrate the role of partial slopes further, observe that the right plot in <a href="#fig-2numxplot1" class="quarto-xref">Figure&nbsp;<span>6.5</span></a> shows the relationship between <code>debt</code> and <code>income</code> in isolation, a <em>positive</em> relationship, so the slope of income is positive. We can determine the value of this slope by constructing a simple linear regression using <code>income</code> as the only regressor:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model and get the coefficients of the model</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>simple_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(debt <span class="sc">~</span> income, <span class="at">data =</span> credit_ch6)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(simple_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Coefficients</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">b0'</td>
<td style="text-align: right;">246.51</td>
</tr>
<tr class="even">
<td style="text-align: left;">income</td>
<td style="text-align: left;">b2'</td>
<td style="text-align: right;">6.05</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The regression line is given by the following with the coefficients denoted using the prime (<span class="math inline">\('\)</span>) designation since they are different values than what we saw previously</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} = \widehat{\text{debt}}  &amp;= b_0' + b_2' \cdot x_2 = 246.515 + 6.048 \cdot x_2
\end{aligned}
\]</span> where <span class="math inline">\(x_2\)</span> is <code>income</code>. By contrast, when <code>credit_limit</code> and <code>income</code> are considered <em>jointly</em> to explain changes in <code>debt</code>, the equation for the multiple linear regression was:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} = \widehat{\text{debt}}  &amp;= b_0 + b_1 \cdot x_1 +  b_2 \cdot x_2\\
&amp;= -385.179 + 0.263 \cdot x_1 - 7.663 \cdot x_2
\end{aligned}
\]</span></p>
<p>So the slope for income in a simple linear regression is 6.048, and the slope for income in a multiple linear regression is <span class="math inline">\(-7.663\)</span>. As surprising as these results may appear at first, they are perfectly valid and consistent as the slope of a simple linear regression has a different role than the partial slope of a multiple linear regression. The latter is the additional effect of <code>income</code> on <code>debt</code> when <code>credit_limit</code> has already been taken into account.</p>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC6.8)</strong> Fit a new simple linear regression using <code>lm(debt ~ credit_rating + age, data = credit_ch6)</code> where <code>credit_rating</code> and <code>age</code> are the new numerical explanatory variables <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>. Get information about the “best-fitting” regression plane from the regression table by finding the coefficient of the model. How do the regression results match up with the results from your previous exploratory data analysis?</p>
<p><strong>(LC6.9)</strong> Which of the following statements best describes the interpretation of a regression coefficient in a multiple regression model?</p>
<ul>
<li>A. It is the additional effect of a regressor on the response when other regressors have already been taken into account.</li>
<li>B. It is the average response variable value when all explanatory variables are zero.</li>
<li>C. It is always positive if the correlation is strong.</li>
<li>D. It cannot be interpreted if there are more than two explanatory variables.</li>
</ul>
<p><strong>(LC6.10)</strong> What is a characteristic of the “best-fitting” plane in a multiple regression model with two numerical explanatory variables?</p>
<ul>
<li>A. It represents the line of best fit for each explanatory variable separately.</li>
<li>B. It minimizes the product of residuals.</li>
<li>C. It minimizes the sum of squared residuals for all combinations of regressors.</li>
<li>D. It shows the exact predictions for every data point.</li>
</ul>
<p><strong>(LC6.11)</strong> What does the intercept represent in a multiple regression model with two explanatory variables?</p>
<ul>
<li>A. The effect of one explanatory variable, keeping the other constant.</li>
<li>B. The change in the response variable per unit change in the explanatory variable.</li>
<li>C. The correlation between the two explanatory variables.</li>
<li>D. The expected value of the response variable when all regressors are zero.</li>
</ul>
<p><strong>(LC6.12)</strong> What does the term “partial slope” refer to in a multiple regression model?</p>
<ul>
<li>A. The additional effect of a regressor on the response variable, when all the other regressors have been taken into account.</li>
<li>B. The total slope of all variables combined.</li>
<li>C. The slope when all variables are zero.</li>
<li>D. The average of all slopes in the model.</li>
</ul>
</div>
</section>
<section id="sec-model3points" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="sec-model3points"><span class="header-section-number">6.2.3</span> Observed/fitted values and residuals</h3>
<p>As shown in <a href="#sec-model4points" class="quarto-xref"><span>Section 6.1.4</span></a> for the UN member states example, we find the fitted values and residuals for our credit card debt regression model. The fitted values for the credit card debt (<span class="math inline">\(\widehat{\text{debt}}\)</span>) are computed using the equation for the regression plane:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} = \widehat{\text{debt}} &amp;= -385.179 + 0.263 \cdot x_1 - 7.663 \cdot x_2
\end{aligned}
\]</span> where <span class="math inline">\(x_1\)</span> is <code>credit_limit</code> and <span class="math inline">\(x_2\)</span> is <code>income</code>. The residuals are the difference between the observed credit card debt and the fitted credit card debt, <span class="math inline">\(y - \widehat y\)</span>, for each observation in the data set. In R, we find the fitted values, <code>debt_hat</code>, and residuals, <code>residual</code>, using the <code>get_regression_points()</code> function. In <a href="#tbl-model3-points-table" class="quarto-xref">Table&nbsp;<span>6.9</span></a> we present the first 10 rows of output. Remember that the coordinates of each of the points in our 3D scatterplot in <a href="#fig-3D-scatterplot" class="quarto-xref">Figure&nbsp;<span>6.6</span></a> can be found in the <code>income</code>, <code>credit_limit</code>, and <code>debt</code> columns.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_points</span>(debt_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-model3-points-table" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model3-points-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;6.9: Regression points (First 10 credit card holders out of 400)
</figcaption>
<div aria-describedby="tbl-model3-points-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">ID</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">debt</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">credit_limit</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">income</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">debt_hat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">333</td>
<td style="text-align: right;">3606</td>
<td style="text-align: right;">14.9</td>
<td style="text-align: right;">454</td>
<td style="text-align: right;">-120.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">903</td>
<td style="text-align: right;">6645</td>
<td style="text-align: right;">106.0</td>
<td style="text-align: right;">559</td>
<td style="text-align: right;">344.3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">580</td>
<td style="text-align: right;">7075</td>
<td style="text-align: right;">104.6</td>
<td style="text-align: right;">683</td>
<td style="text-align: right;">-103.4</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">964</td>
<td style="text-align: right;">9504</td>
<td style="text-align: right;">148.9</td>
<td style="text-align: right;">986</td>
<td style="text-align: right;">-21.7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">331</td>
<td style="text-align: right;">4897</td>
<td style="text-align: right;">55.9</td>
<td style="text-align: right;">481</td>
<td style="text-align: right;">-150.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">1151</td>
<td style="text-align: right;">8047</td>
<td style="text-align: right;">80.2</td>
<td style="text-align: right;">1127</td>
<td style="text-align: right;">23.6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">203</td>
<td style="text-align: right;">3388</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">349</td>
<td style="text-align: right;">-146.4</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">872</td>
<td style="text-align: right;">7114</td>
<td style="text-align: right;">71.4</td>
<td style="text-align: right;">948</td>
<td style="text-align: right;">-76.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">279</td>
<td style="text-align: right;">3300</td>
<td style="text-align: right;">15.1</td>
<td style="text-align: right;">371</td>
<td style="text-align: right;">-92.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">1350</td>
<td style="text-align: right;">6819</td>
<td style="text-align: right;">71.1</td>
<td style="text-align: right;">873</td>
<td style="text-align: right;">477.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<!--
I've added the correlation property of invariance under linear transformations in the main text. The Simpson's Paradox example presenting by separating the data in 4 groups based on credit limit should be moved to an appendix. AV 8/13/24
-->
</section>
</section>
<section id="sec-mult-reg-conclusion" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-mult-reg-conclusion"><span class="header-section-number">6.3</span> Conclusion</h2>
<section id="additional-resources" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="additional-resources"><span class="header-section-number">6.3.1</span> Additional resources</h3>
<div class="cell" data-layout-align="center">
<p>An R script file of all R code used in this chapter is available <a href="scripts/06-multiple-regression.R">here</a>.</p>
</div>
</section>
<section id="whats-to-come" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="whats-to-come"><span class="header-section-number">6.3.2</span> What’s to come?</h3>
<p>This chapter concludes the “Statistical/Data Modeling with <code>moderndive</code>” portion of this book. We are ready to proceed to Part III: “Statistical Inference with <code>infer</code>.” Statistical inference is the science of inferring about some unknown quantity using sampling. So far, we have only studied the regression coefficients and their interpretation. In later chapters we learn how we can use information from a sample to make inferences about the entire population.</p>
<p>Once we have covered <a href="07-sampling.html" class="quarto-xref"><span>Chapter 7</span></a> on sampling, <a href="08-confidence-intervals.html" class="quarto-xref"><span>Chapter 8</span></a> on confidence intervals, and <a href="09-hypothesis-testing.html" class="quarto-xref"><span>Chapter 9</span></a> on hypothesis testing, we revisit the regression models in <a href="10-inference-for-regression.html" class="quarto-xref"><span>Chapter 10</span></a> on inference for regression. This will complete the topics in this book, as shown in <a href="#fig-part3" class="quarto-xref">Figure&nbsp;<span>6.7</span></a>!</p>
<p>Also in <a href="10-inference-for-regression.html" class="quarto-xref"><span>Chapter 10</span></a>, we revisit the concept of residuals <span class="math inline">\(y - \widehat{y}\)</span> and discuss their importance when interpreting the results of a regression model. We perform what is known as a <em>residual analysis</em> of the <code>residual</code> variable of all <code>get_regression_points()</code> outputs. Residual analyses enable us to verify what are known as the <em>conditions for inference for regression</em>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-part3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-part3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/flowcharts/flowchart/flowchart.006.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="FIGURE&nbsp;6.7: ModernDive flowchart – on to Part III!"><img src="images/flowcharts/flowchart/flowchart.006.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-part3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;6.7: <em>ModernDive</em> flowchart – on to Part III!
</figcaption>
</figure>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-regression.html" class="pagination-link" aria-label="Simple Linear Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-sampling.html" class="pagination-link" aria-label="Sampling">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/moderndive/ModernDive_book/edit/v2/06-multiple-regression.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/moderndive/ModernDive_book/blob/v2/06-multiple-regression.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/moderndive/ModernDive_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>