<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="An open-source and fully-reproducible electronic textbook for teaching statistical inference using tidyverse data science tools.">
<title>11&nbsp; Tell Your Story with Data – Statistical Inference via Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./91-appendixA.html" rel="next">
<link href="./10-inference-for-regression.html" rel="prev">
<link href="./images/logos/favicons/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-36bf55b16c7cb4b1420f41495cb5446a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-4e061325f75ba7fba053004d9d2e9411.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-36bf55b16c7cb4b1420f41495cb5446a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-YVFBK9P73R"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YVFBK9P73R');
</script><!-- Open Graph Meta Tags --><meta property="og:title" content="11&nbsp; Tell Your Story with Data – Statistical Inference via Data Science">
<meta property="og:description" content="An open-source and fully-reproducible electronic textbook for teaching statistical inference using tidyverse data science tools.">
<meta property="og:image" content="https://moderndive.com/v2/images/logos/v2_cover.jpg">
<meta property="og:url" content="https://moderndive.com/v2/">
<meta name="twitter:card" content="summary_large_image">
<!-- Set up favicon --><link rel="icon" href="images/logos/favicons/favicon.ico" type="image/x-icon">
<!-- Redirect to ModernDive V2 --><script>
  if (window.location.pathname === '/v2') {
    window.location.replace(window.location.pathname + '/');
  }
</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="style.css">
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./11-tell-your-story-with-data.html">Conclusion</a></li><li class="breadcrumb-item"><a href="./11-tell-your-story-with-data.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Tell Your Story with Data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Inference via Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/moderndive/ModernDive_book/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome to ModernDive (v2)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-foreword.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foreword</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with Data in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data Science with tidyverse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-tidy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Importing and Tidy Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Modeling with moderndive</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Inference with infer</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estimation, Confidence Intervals, and Bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-inference-for-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Inference for Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Conclusion</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-tell-your-story-with-data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Tell Your Story with Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./91-appendixA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Statistical Background</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./92-appendixB.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Inference Examples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./93-appendixC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Tips and Tricks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./94-appendixD.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Learning Check Solutions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./95-appendixE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">The Theory Behind the Bootstrap Method</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./96-glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#review" id="toc-review" class="nav-link active" data-scroll-target="#review"><span class="header-section-number">11.1</span> Review</a>
  <ul class="collapse">
<li><a href="#sec-story-packages" id="toc-sec-story-packages" class="nav-link" data-scroll-target="#sec-story-packages">Needed packages</a></li>
  </ul>
</li>
  <li>
<a href="#sec-seattle-house-prices" id="toc-sec-seattle-house-prices" class="nav-link" data-scroll-target="#sec-seattle-house-prices"><span class="header-section-number">11.2</span> Case study: Seattle house prices</a>
  <ul class="collapse">
<li><a href="#sec-house-prices-EDA-I" id="toc-sec-house-prices-EDA-I" class="nav-link" data-scroll-target="#sec-house-prices-EDA-I"><span class="header-section-number">11.2.1</span> Exploratory data analysis: part I</a></li>
  <li><a href="#sec-house-prices-EDA-II" id="toc-sec-house-prices-EDA-II" class="nav-link" data-scroll-target="#sec-house-prices-EDA-II"><span class="header-section-number">11.2.2</span> Exploratory data analysis: part II</a></li>
  <li><a href="#sec-house-prices-regression" id="toc-sec-house-prices-regression" class="nav-link" data-scroll-target="#sec-house-prices-regression"><span class="header-section-number">11.2.3</span> Regression modeling</a></li>
  <li><a href="#sec-house-prices-making-predictions" id="toc-sec-house-prices-making-predictions" class="nav-link" data-scroll-target="#sec-house-prices-making-predictions"><span class="header-section-number">11.2.4</span> Making predictions</a></li>
  <li><a href="#sec-house-prices-inference-for-regression" id="toc-sec-house-prices-inference-for-regression" class="nav-link" data-scroll-target="#sec-house-prices-inference-for-regression"><span class="header-section-number">11.2.5</span> Inference for multiple linear regression</a></li>
  </ul>
</li>
  <li>
<a href="#sec-data-journalism" id="toc-sec-data-journalism" class="nav-link" data-scroll-target="#sec-data-journalism"><span class="header-section-number">11.3</span> Case study: effective data storytelling</a>
  <ul class="collapse">
<li><a href="#bechdel-test-for-hollywood-gender-representation" id="toc-bechdel-test-for-hollywood-gender-representation" class="nav-link" data-scroll-target="#bechdel-test-for-hollywood-gender-representation"><span class="header-section-number">11.3.1</span> Bechdel test for Hollywood gender representation</a></li>
  <li><a href="#us-births-in-1999" id="toc-us-births-in-1999" class="nav-link" data-scroll-target="#us-births-in-1999"><span class="header-section-number">11.3.2</span> US Births in 1999</a></li>
  <li><a href="#scripts-of-r-code" id="toc-scripts-of-r-code" class="nav-link" data-scroll-target="#scripts-of-r-code"><span class="header-section-number">11.3.3</span> Scripts of R code</a></li>
  </ul>
</li>
  <li><a href="#quick-checks" id="toc-quick-checks" class="nav-link" data-scroll-target="#quick-checks">Quick checks</a></li>
  <li><a href="#concluding-remarks" id="toc-concluding-remarks" class="nav-link" data-scroll-target="#concluding-remarks">Concluding remarks</a></li>
  <li><a href="#appendix-appendix" id="toc-appendix-appendix" class="nav-link" data-scroll-target="#appendix-appendix">(APPENDIX) Appendix</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/moderndive/ModernDive_book/edit/v2/11-tell-your-story-with-data.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/moderndive/ModernDive_book/blob/v2/11-tell-your-story-with-data.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/moderndive/ModernDive_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><img src="https://moderndive.com/wide_format.png" alt="ModernDive" style="max-width: 100%; width: 100%; height: auto; display: block; margin: 0 auto; padding-top: 10px;"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./11-tell-your-story-with-data.html">Conclusion</a></li><li class="breadcrumb-item"><a href="./11-tell-your-story-with-data.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Tell Your Story with Data</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-thinking-with-data" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Tell Your Story with Data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-default callout-note callout-titled" title="In this chapter, you'll learn how to:">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>In this chapter, you’ll learn how to:
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Apply the full data-science pipeline (import → wrangle → visualize → model) to a multi-step case study</li>
<li>Diagnose and address common data quality issues (skewness, missing values, outliers)</li>
<li>Build a regression model that captures interaction between variables</li>
<li>Communicate statistical findings clearly to a non-technical audience</li>
</ul>
</div>
</div>
<p>Recall in the Preface and at the end of chapters throughout this book, we displayed the “<em>ModernDive</em> flowchart” mapping your journey through this book.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-moderndive-figure-conclusion" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-moderndive-figure-conclusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/flowcharts/flowchart/flowchart.002.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="FIGURE&nbsp;11.1: ModernDive flowchart."><img src="images/flowcharts/flowchart/flowchart.002.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-moderndive-figure-conclusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;11.1: <em>ModernDive</em> flowchart.
</figcaption></figure>
</div>
</div>
</div>
<section id="review" class="level2" data-number="11.1"><h2 data-number="11.1" class="anchored" data-anchor-id="review">
<span class="header-section-number">11.1</span> Review</h2>
<p>Let’s go over a refresher of what you’ve covered so far. You first got started with data in <a href="01-getting-started.html#sec-getting-started">Chapter 1 (Getting Started with Data in R)</a> where you learned about the difference between R and RStudio, started coding in R, installed and loaded your first R packages, and explored your first dataset: all domestic departure <code>flights</code> from a major New York City airport in 2023. Then you covered the following three parts of this book (Parts 2 and 4 are combined into a single portion):</p>
<ol type="1">
<li>Data science with <code>tidyverse</code>. You assembled your data science toolbox using <code>tidyverse</code> packages. In particular, you</li>
</ol>
<ul>
<li>
<a href="02-visualization.html#sec-viz">Chapter 2 (Data Visualization)</a>: Visualized data using the <code>ggplot2</code> package.</li>
<li>
<a href="03-wrangling.html#sec-wrangling">Chapter 3 (Data Wrangling)</a>: Wrangled data using the <code>dplyr</code> package.</li>
<li>
<a href="04-tidy.html#sec-tidy">Chapter 4 (Data Importing and Tidy Data)</a>: Learned about the concept of “tidy” data as a standardized data frame input and output format for all packages in the <code>tidyverse</code>. Furthermore, you learned how to import spreadsheet files into R using the <code>readr</code> package.</li>
</ul>
<ol start="2" type="1">
<li>Statistical/Data modeling with <code>moderndive</code>. Using these data science tools and helper functions from the <code>moderndive</code> package, you fit your first data models. In particular, you</li>
</ol>
<ul>
<li>
<a href="05-regression.html#sec-regression">Chapter 5 (Simple Linear Regression)</a>: Discovered basic regression models with only one explanatory variable.</li>
<li>
<a href="06-multiple-regression.html#sec-multiple-regression">Chapter 6 (Multiple Regression)</a>: Examined multiple regression models with more than one explanatory variable.</li>
</ul>
<ol start="3" type="1">
<li>Statistical inference with <code>infer</code>. Once again using your newly acquired data science tools, you unpacked statistical inference using the <code>infer</code> package. In particular, you</li>
</ol>
<ul>
<li>
<a href="07-sampling.html#sec-sampling">Chapter 7 (Sampling)</a>: Learned about the role that sampling variability plays in statistical inference and the role that sample size plays in this sampling variability.</li>
<li>
<a href="08-confidence-intervals.html#sec-confidence-intervals">Chapter 8 (Estimation, Confidence Intervals, and Bootstrapping)</a>: Constructed confidence intervals using bootstrapping and learned some about a theory-based approach to confidence intervals.</li>
<li>
<a href="09-hypothesis-testing.html#sec-hypothesis-testing">Chapter 9 (Hypothesis Testing)</a>: Conducted hypothesis tests using permutation.</li>
</ul>
<ol start="4" type="1">
<li>Statistical/Data modeling with <code>moderndive</code> (revisited): Armed with your understanding of statistical inference, you revisited and reviewed the models you constructed in <a href="05-regression.html#sec-regression">Chapter 5 (Simple Linear Regression)</a> and <a href="06-multiple-regression.html#sec-multiple-regression">Chapter 6 (Multiple Regression)</a>. In particular, you</li>
</ol>
<ul>
<li>
<a href="10-inference-for-regression.html#sec-inference-for-regression">Chapter 10 (Inference for Regression)</a>: Interpreted confidence intervals and hypothesis tests in a regression setting using both theory-based and simulation-based approaches.</li>
</ul>
<p>We’ve guided you through your first experiences of <a href="https://arxiv.org/pdf/1410.3127.pdf">“thinking with data,”</a> an expression originally coined by Dr.&nbsp;Diane Lambert. The philosophy underlying this expression guided your path in the flowchart in <a href="#fig-moderndive-figure-conclusion" class="quarto-xref">Figure&nbsp;<span>11.1</span></a>.</p>
<p>This philosophy is also well-summarized in <a href="https://peerj.com/collections/50-practicaldatascistats/">“Practical Data Science for Stats”</a>: a collection of pre-prints focusing on the practical side of data science workflows and statistical analysis curated by <a href="https://twitter.com/jennybryan">Dr.&nbsp;Jennifer Bryan</a> and <a href="https://twitter.com/hadleywickham">Dr.&nbsp;Hadley Wickham</a>. They quote:</p>
<blockquote class="blockquote">
<p>There are many aspects of day-to-day analytical work that are almost absent from the conventional statistics literature and curriculum. And yet these activities account for a considerable share of the time and effort of data analysts and applied statisticians. The goal of this collection is to increase the visibility and adoption of modern data analytical workflows. We aim to facilitate the transfer of tools and frameworks between industry and academia, between software engineering and statistics and computer science, and across different domains.</p>
</blockquote>
<p>In other words, to be equipped to “think with data” in the 21st century and beyond, analysts need practice going through the <a href="http://r4ds.had.co.nz/explore-intro.html">“data/science pipeline”</a> we saw in the Preface (re-displayed in <a href="#fig-pipeline-figure-conclusion" class="quarto-xref">Figure&nbsp;<span>11.2</span></a>). It is our opinion that, for too long, statistics education has only focused on parts of this pipeline, instead of going through it in its <em>entirety</em>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pipeline-figure-conclusion" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-pipeline-figure-conclusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/r4ds/data_science_pipeline.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="FIGURE&nbsp;11.2: Data/science pipeline."><img src="images/r4ds/data_science_pipeline.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pipeline-figure-conclusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;11.2: Data/science pipeline.
</figcaption></figure>
</div>
</div>
</div>
<p>To conclude this book, we’ll present you with some additional case studies of working with data. In <a href="#sec-seattle-house-prices" class="quarto-xref"><span>Section 11.2</span></a> we’ll take you through a full-pass of the “Data/Science Pipeline” in order to analyze the sale price of houses in Seattle, Washington, USA. In <a href="#sec-data-journalism" class="quarto-xref"><span>Section 11.3</span></a>, we’ll present you with some examples of effective data storytelling drawn from the data journalism website, <a href="https://fivethirtyeight.com/">FiveThirtyEight.com</a>. We present these case studies to you because we believe that you should not only be able to “think with data,” but also be able to “tell your story with data.” Let’s explore how to do this!</p>
<section id="sec-story-packages" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="sec-story-packages">Needed packages</h3>
<p>Let’s load all the packages needed for this chapter (this assumes you’ve already installed them). Read <a href="01-getting-started.html#sec-packages" class="quarto-xref"><span>Section 1.3</span></a> for information on how to install and load R packages.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://moderndive.github.io/moderndive/">moderndive</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/rudeboybert/fivethirtyeight">fivethirtyeight</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/tidymodels/infer">infer</a></span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section></section><section id="sec-seattle-house-prices" class="level2" data-number="11.2"><h2 data-number="11.2" class="anchored" data-anchor-id="sec-seattle-house-prices">
<span class="header-section-number">11.2</span> Case study: Seattle house prices</h2>
<p><a href="https://www.kaggle.com/">Kaggle.com</a> is a machine learning and predictive modeling competition website that hosts datasets uploaded by companies, governmental organizations, and other individuals. One of their datasets is the <a href="https://www.kaggle.com/harlfoxem/housesalesprediction">“House Sales in King County, USA”</a>. It consists of sale prices of homes sold between May 2014 and May 2015 in King County, Washington, USA, which includes the greater Seattle metropolitan area. This dataset is in the <code>house_prices</code> data frame included in the <code>moderndive</code> package.</p>
<p>The dataset consists of 21,613 houses and 21 variables describing these houses (for a full list and description of these variables, see the help file by running <a href="https://moderndive.github.io/moderndive/reference/house_prices.html"><code>?house_prices</code></a> in the console). In this case study, we’ll create a multiple regression model where:</p>
<ul>
<li>The outcome variable <span class="math inline">\(y\)</span> is the sale <code>price</code> of houses.</li>
<li>Two explanatory variables:</li>
</ul>
<ol type="1">
<li>A numerical explanatory variable <span class="math inline">\(x_1\)</span>: house size <code>sqft_living</code> as measured in square feet of living space. Note that 1 square foot is about 0.09 square meters.</li>
<li>A categorical explanatory variable <span class="math inline">\(x_2\)</span>: house <code>condition</code>, a categorical variable with five levels where <code>1</code> indicates “poor” and <code>5</code> indicates “excellent.”</li>
</ol>
<section id="sec-house-prices-EDA-I" class="level3" data-number="11.2.1"><h3 data-number="11.2.1" class="anchored" data-anchor-id="sec-house-prices-EDA-I">
<span class="header-section-number">11.2.1</span> Exploratory data analysis: part I</h3>
<p>As we’ve said numerous times throughout this book, a crucial first step when presented with data is to perform an exploratory data analysis (EDA). Exploratory data analysis can give you a sense of your data, help identify issues with your data, bring to light any outliers, and help inform model construction. Recall the three common steps in an exploratory data analysis we introduced in <a href="05-regression.html#sec-model1EDA" class="quarto-xref"><span>Section 5.1.1</span></a>:</p>
<ol type="1">
<li>Looking at the raw data values.</li>
<li>Computing summary statistics.</li>
<li>Creating data visualizations.</li>
</ol>
<p>First, let’s look at the raw data using <code><a href="https://rdrr.io/r/utils/View.html">View()</a></code> to bring up RStudio’s spreadsheet viewer and the <code><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse()</a></code> function from the <code>dplyr</code> package:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/View.html">View</a></span><span class="op">(</span><span class="va">house_prices</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">house_prices</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 21,613
Columns: 21
$ id            &lt;chr&gt; "7129300520", "6414100192", "5631500400", "2487200875", …
$ date          &lt;date&gt; 2014-10-13, 2014-12-09, 2015-02-25, 2014-12-09, 2015-02…
$ price         &lt;dbl&gt; 221900, 538000, 180000, 604000, 510000, 1225000, 257500,…
$ bedrooms      &lt;int&gt; 3, 3, 2, 4, 3, 4, 3, 3, 3, 3, 3, 2, 3, 3, 5, 4, 3, 4, 2,…
$ bathrooms     &lt;dbl&gt; 1.00, 2.25, 1.00, 3.00, 2.00, 4.50, 2.25, 1.50, 1.00, 2.…
$ sqft_living   &lt;int&gt; 1180, 2570, 770, 1960, 1680, 5420, 1715, 1060, 1780, 189…
$ sqft_lot      &lt;int&gt; 5650, 7242, 10000, 5000, 8080, 101930, 6819, 9711, 7470,…
$ floors        &lt;dbl&gt; 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1…
$ waterfront    &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …
$ view          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0,…
$ condition     &lt;fct&gt; 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3, 3, 4, 4,…
$ grade         &lt;fct&gt; 7, 7, 6, 7, 8, 11, 7, 7, 7, 7, 8, 7, 7, 7, 7, 9, 7, 7, 7…
$ sqft_above    &lt;int&gt; 1180, 2170, 770, 1050, 1680, 3890, 1715, 1060, 1050, 189…
$ sqft_basement &lt;int&gt; 0, 400, 0, 910, 0, 1530, 0, 0, 730, 0, 1700, 300, 0, 0, …
$ yr_built      &lt;int&gt; 1955, 1951, 1933, 1965, 1987, 2001, 1995, 1963, 1960, 20…
$ yr_renovated  &lt;int&gt; 0, 1991, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ zipcode       &lt;fct&gt; 98178, 98125, 98028, 98136, 98074, 98053, 98003, 98198, …
$ lat           &lt;dbl&gt; 47.5, 47.7, 47.7, 47.5, 47.6, 47.7, 47.3, 47.4, 47.5, 47…
$ long          &lt;dbl&gt; -122, -122, -122, -122, -122, -122, -122, -122, -122, -1…
$ sqft_living15 &lt;int&gt; 1340, 1690, 2720, 1360, 1800, 4760, 2238, 1650, 1780, 23…
$ sqft_lot15    &lt;int&gt; 5650, 7639, 8062, 5000, 7503, 101930, 6819, 9711, 8113, …</code></pre>
</div>
</div>
<p>Here are some questions you can ask yourself at this stage of an EDA: Which variables are numerical? Which are categorical? For the categorical variables, what are their levels? Besides the variables we’ll be using in our regression model, what other variables do you think would be useful to use in a model for predicting house price?</p>
<p>Observe, for example, with the raw data that while the <code>condition</code> variable has values <code>1</code> through <code>5</code>, these are saved in R as <code>fct</code> standing for “factors.” Recall this is one of R’s ways of saving categorical variables. So you should think of these as the “labels” <code>1</code> through <code>5</code> and not the numerical values <code>1</code> through <code>5</code>.</p>
<p>Let’s now perform the second step in an EDA: computing summary statistics. Recall from <a href="03-wrangling.html#sec-summarize" class="quarto-xref"><span>Section 3.3</span></a> that <em>summary statistics</em> are single numerical values that summarize a large number of values. Examples of summary statistics include the mean, the median, the standard deviation, and various percentiles.</p>
<!--
We could do this using the `summarize()` function in the `dplyr` package along with R's built-in *summary functions*, like `mean()` and `median()`. However, recall in @sec-mutate, we saw the following code that computes a variety of summary statistics of the variable `gain`, which is the amount of time that a flight makes up mid-air:


::: {.cell layout-align="center"}

```{.r .cell-code}
gain_summary <- flights |> 
  summarize(min = min(gain, na.rm = TRUE), 
            q1 = quantile(gain, 0.25, na.rm = TRUE),
            median = quantile(gain, 0.5, na.rm = TRUE),
            q3 = quantile(gain, 0.75, na.rm = TRUE),
            max = max(gain, na.rm = TRUE), 
            mean = mean(gain, na.rm = TRUE),
            sd = sd(gain, na.rm = TRUE), 
            missing = sum(is.na(gain)))
```
:::


To repeat this for all three `price`, `sqft_living`, and `condition` variables would be tedious to code up. So instead, 

-->
<p>Let’s use the convenient <code><a href="moderndive.github.io/moderndive/reference/tidy_summary.html">tidy_summary()</a></code> function from the <code>moderndive</code> package we first used in <a href="06-multiple-regression.html#sec-model4EDA" class="quarto-xref"><span>Section 6.1.1</span></a>, being sure to only <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> the variables of interest for our model:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">house_prices</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">price</span>, <span class="va">sqft_living</span>, <span class="va">condition</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="moderndive.github.io/moderndive/reference/tidy_summary.html">tidy_summary</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>(ref:some-house-price-vars)</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">column</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">price</td>
<td style="text-align: right;">21613</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">numeric</td>
<td style="text-align: right;">75000</td>
<td style="text-align: right;">321950</td>
<td style="text-align: right;">540088</td>
<td style="text-align: right;">450000</td>
<td style="text-align: right;">645000</td>
<td style="text-align: right;">7700000</td>
<td style="text-align: right;">367127</td>
</tr>
<tr class="even">
<td style="text-align: left;">sqft_living</td>
<td style="text-align: right;">21613</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">numeric</td>
<td style="text-align: right;">290</td>
<td style="text-align: right;">1427</td>
<td style="text-align: right;">2080</td>
<td style="text-align: right;">1910</td>
<td style="text-align: right;">2550</td>
<td style="text-align: right;">13540</td>
<td style="text-align: right;">918</td>
</tr>
<tr class="odd">
<td style="text-align: left;">condition</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">condition</td>
<td style="text-align: right;">172</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">condition</td>
<td style="text-align: right;">14031</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">condition</td>
<td style="text-align: right;">5679</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">condition</td>
<td style="text-align: right;">1701</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Observe that the mean <code>price</code> of $540,088 is larger than the median of $450,000. This is because a small number of very expensive houses are inflating the average. In other words, there are “outlier” house prices in our dataset. (This fact will become even more apparent when we create our visualizations next.)</p>
<p>However, the median is not as sensitive to such outlier house prices. This is why news about the real estate market generally report median house prices and not mean/average house prices. We say here that the median is more <em>robust to outliers</em> than the mean. Similarly, while both the standard deviation and interquartile-range (IQR) are both measures of spread and variability, the IQR being based on quantiles as <code>Q3 - Q1</code> is more <em>robust to outliers</em>.</p>
<p>Let’s now perform the last of the three common steps in an exploratory data analysis: creating data visualizations. Let’s first create <em>univariate</em> visualizations. These are plots focusing on a single variable at a time. Since <code>price</code> and <code>sqft_living</code> are numerical variables, we can visualize their distributions using a <code><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram()</a></code> as seen in <a href="02-visualization.html#sec-histograms" class="quarto-xref"><span>Section 2.5</span></a> on histograms. On the other hand, since <code>condition</code> is categorical, we can visualize its distribution using a <code><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar()</a></code>. Recall from <a href="02-visualization.html#sec-geombar" class="quarto-xref"><span>Section 2.8</span></a> on barplots that since <code>condition</code> is not “pre-counted,” we use a <code><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar()</a></code> and not a <code><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_col()</a></code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Histogram of house price:</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">house_prices</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">price</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"price (USD)"</span>, title <span class="op">=</span> <span class="st">"House price"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Histogram of sqft_living:</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">house_prices</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sqft_living</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"living space (square feet)"</span>, title <span class="op">=</span> <span class="st">"House size"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Barplot of condition:</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">house_prices</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">condition</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"condition"</span>, title <span class="op">=</span> <span class="st">"House condition"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In <a href="#fig-house-prices-viz" class="quarto-xref">Figure&nbsp;<span>11.3</span></a>, we display all three of these visualizations at once.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-house-prices-viz" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-house-prices-viz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11-tell-your-story-with-data_files/figure-html/fig-house-prices-viz-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="FIGURE&nbsp;11.3: Exploratory visualizations of Seattle house prices data."><img src="11-tell-your-story-with-data_files/figure-html/fig-house-prices-viz-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-house-prices-viz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;11.3: Exploratory visualizations of Seattle house prices data.
</figcaption></figure>
</div>
</div>
</div>
<p>First, observe in the bottom plot that most houses are of condition <code>3</code>, with a few more of conditions <code>4</code> and <code>5</code>, and almost none that are <code>1</code> or <code>2</code>.</p>
<p>Next, see in the histogram for <code>price</code> (the top-left plot) that a majority of houses are less than two million dollars. Observe also that the x-axis stretches out to 8 million dollars, even though there does not appear to be any houses close to that price. This is because there are a <em>very small number</em> of houses with prices closer to 8 million as noted in the <code><a href="moderndive.github.io/moderndive/reference/tidy_summary.html">tidy_summary()</a></code>. These are the outlier house prices we mentioned earlier. We say that the variable <code>price</code> is <em>right-skewed</em> as exhibited by the long right tail.</p>
<p>Further, the histogram of <code>sqft_living</code> in the middle plot shows that most houses appear to have less than 5000 square feet of living space. For comparison, an American football field in the US is about 57,600 square feet, whereas a standard soccer/association football field is about 64,000 square feet. Observe also that this variable is also right-skewed, although not as drastically as the <code>price</code> variable.</p>
<p>For both the <code>price</code> and <code>sqft_living</code> variables, the right-skew makes distinguishing houses at the lower end of the x-axis hard. This is because the scale of the x-axis is compressed by the small number of quite expensive and immensely-sized houses.</p>
<p>So what can we do about this skew? Let’s apply a <em>log10 transformation</em> to these variables.</p>
<div class="cell" data-layout-align="center">
<p>If you are unfamiliar with such transformations, we highly recommend you read <a href="https://moderndive.com/v2/appendixa">Appendix A online</a> on logarithmic (log) transformations.</p>
</div>
<p>In summary, log transformations allow us to alter the scale of a variable to focus on <em>multiplicative</em> changes instead of <em>additive</em> changes. In other words, they shift the view to be on <em>relative</em> changes instead of <em>absolute</em> changes. Such multiplicative/relative changes are also called changes in <em>orders of magnitude</em>.</p>
<p>Let’s create new log10 transformed versions of the right-skewed variable <code>price</code> and <code>sqft_living</code> using the <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> function from <a href="03-wrangling.html#sec-mutate" class="quarto-xref"><span>Section 3.5</span></a>, but we’ll give the latter the name <code>log10_size</code>, which is shorter and easier to understand than the name <code>log10_sqft_living</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">house_prices</span> <span class="op">&lt;-</span> <span class="va">house_prices</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    log10_price <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log10</a></span><span class="op">(</span><span class="va">price</span><span class="op">)</span>,</span>
<span>    log10_size <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log10</a></span><span class="op">(</span><span class="va">sqft_living</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s display the before and after effects of this transformation on these variables for only the first 10 rows of <code>house_prices</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">house_prices</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">price</span>, <span class="va">log10_price</span>, <span class="va">sqft_living</span>, <span class="va">log10_size</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21,613 × 4
     price log10_price sqft_living log10_size
     &lt;dbl&gt;       &lt;dbl&gt;       &lt;int&gt;      &lt;dbl&gt;
 1  221900        5.35        1180       3.07
 2  538000        5.73        2570       3.41
 3  180000        5.26         770       2.89
 4  604000        5.78        1960       3.29
 5  510000        5.71        1680       3.23
 6 1225000        6.09        5420       3.73
 7  257500        5.41        1715       3.23
 8  291850        5.47        1060       3.03
 9  229500        5.36        1780       3.25
10  323000        5.51        1890       3.28
# ℹ 21,603 more rows</code></pre>
</div>
</div>
<p>Observe in particular the houses in the sixth and third rows. The house in the sixth row has <code>price</code> $1,225,000, which is just above one million dollars. Since <span class="math inline">\(10^6\)</span> is one million, its <code>log10_price</code> is around 6.09. Contrast this with all other houses with <code>log10_price</code> less than six, since they all have <code>price</code> less than $1,000,000. The house in the third row is the only house with <code>sqft_living</code> less than 1000. Since <span class="math inline">\(1000 = 10^3\)</span>, it’s the lone house with <code>log10_size</code> less than 3.</p>
<p>Let’s now visualize the before and after effects of this transformation for <code>price</code> in <a href="#fig-log10-price-viz" class="quarto-xref">Figure&nbsp;<span>11.4</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Before log10 transformation:</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">house_prices</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">price</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"price (USD)"</span>, title <span class="op">=</span> <span class="st">"House price: Before"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># After log10 transformation:</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">house_prices</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">log10_price</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"log10 price (USD)"</span>, title <span class="op">=</span> <span class="st">"House price: After"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-log10-price-viz" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-log10-price-viz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11-tell-your-story-with-data_files/figure-html/fig-log10-price-viz-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="FIGURE&nbsp;11.4: House price before and after log10 transformation."><img src="11-tell-your-story-with-data_files/figure-html/fig-log10-price-viz-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-log10-price-viz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;11.4: House price before and after log10 transformation.
</figcaption></figure>
</div>
</div>
</div>
<p>Observe that after the transformation, the distribution is much less skewed, and in this case, more symmetric and more bell-shaped. Now you can more easily distinguish the lower priced houses.</p>
<p>Let’s do the same for house size, where the variable <code>sqft_living</code> was log10 transformed to <code>log10_size</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Before log10 transformation:</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">house_prices</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sqft_living</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"living space (square feet)"</span>, title <span class="op">=</span> <span class="st">"House size: Before"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># After log10 transformation:</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">house_prices</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">log10_size</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"log10 living space (square feet)"</span>, title <span class="op">=</span> <span class="st">"House size: After"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-log10-size-viz" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-log10-size-viz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11-tell-your-story-with-data_files/figure-html/fig-log10-size-viz-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="FIGURE&nbsp;11.5: House size before and after log10 transformation."><img src="11-tell-your-story-with-data_files/figure-html/fig-log10-size-viz-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-log10-size-viz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;11.5: House size before and after log10 transformation.
</figcaption></figure>
</div>
</div>
</div>
<p>Observe in <a href="#fig-log10-size-viz" class="quarto-xref">Figure&nbsp;<span>11.5</span></a> that the log10 transformation has a similar effect of un-skewing the variable. We emphasize that while in these two cases the resulting distributions are more symmetric and bell-shaped, this is not always necessarily the case.</p>
<p>Given the now symmetric nature of <code>log10_price</code> and <code>log10_size</code>, we are going to revise our multiple regression model to use our new variables:</p>
<ol type="1">
<li>The outcome variable <span class="math inline">\(y\)</span> is the sale <code>log10_price</code> of houses.</li>
<li>Two explanatory variables:</li>
<li>A numerical explanatory variable <span class="math inline">\(x_1\)</span>: house size <code>log10_size</code> as measured in log base 10 square feet of living space.</li>
<li>A categorical explanatory variable <span class="math inline">\(x_2\)</span>: house <code>condition</code>, a categorical variable with five levels where <code>1</code> indicates “poor” and <code>5</code> indicates “excellent.”</li>
</ol></section><section id="sec-house-prices-EDA-II" class="level3" data-number="11.2.2"><h3 data-number="11.2.2" class="anchored" data-anchor-id="sec-house-prices-EDA-II">
<span class="header-section-number">11.2.2</span> Exploratory data analysis: part II</h3>
<p>Let’s now continue our EDA by creating <em>multivariate</em> visualizations. Unlike the <em>univariate</em> histograms and barplot in the earlier <a href="#fig-house-prices-viz" class="quarto-xref">Figure&nbsp;<span>11.3</span></a>, <a href="#fig-log10-price-viz" class="quarto-xref">Figure&nbsp;<span>11.4</span></a>, and <a href="#fig-log10-size-viz" class="quarto-xref">Figure&nbsp;<span>11.5</span></a>, <em>multivariate</em> visualizations show relationships between more than one variable. This is an important step of an EDA to perform since the goal of modeling is to explore relationships between variables.</p>
<p>Since our model involves a numerical outcome variable, a numerical explanatory variable, and a categorical explanatory variable, we are in a similar regression modeling situation as in <a href="06-multiple-regression.html#sec-model4" class="quarto-xref"><span>Section 6.1</span></a> where we studied the UN member states dataset. Recall in that case the numerical outcome variable was fertility rate, the numerical explanatory variable was life expectancy, and the categorical explanatory variable was income group.</p>
<p>We thus have two choices of models we can fit: either (1) an <em>interaction model</em> where the regression line for each <code>condition</code> level will have both a different slope and a different intercept or (2) a <em>parallel slopes model</em> where the regression line for each <code>condition</code> level will have the same slope but different intercepts.</p>
<p>Recall from <a href="06-multiple-regression.html#sec-model4table" class="quarto-xref"><span>Section 6.1.3</span></a> that the <code><a href="moderndive.github.io/moderndive/reference/geom_parallel_slopes.html">geom_parallel_slopes()</a></code> function is a special purpose function that Evgeni Chasnovski created and included in the <code>moderndive</code> package, since the <code><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth()</a></code> method in the <code>ggplot2</code> package does not have a convenient way to plot parallel slopes models. We plot both resulting models in <a href="#fig-house-price-parallel-slopes" class="quarto-xref">Figure&nbsp;<span>11.6</span></a>, with the interaction model on the left.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Plot interaction model</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">house_prices</span>, </span>
<span>       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">log10_size</span>, y <span class="op">=</span> <span class="va">log10_price</span>, col <span class="op">=</span> <span class="va">condition</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"log10 price"</span>, </span>
<span>       x <span class="op">=</span> <span class="st">"log10 size"</span>, </span>
<span>       title <span class="op">=</span> <span class="st">"House prices in Seattle"</span><span class="op">)</span></span>
<span><span class="co"># Plot parallel slopes model</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">house_prices</span>, </span>
<span>       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">log10_size</span>, y <span class="op">=</span> <span class="va">log10_price</span>, col <span class="op">=</span> <span class="va">condition</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="moderndive.github.io/moderndive/reference/geom_parallel_slopes.html">geom_parallel_slopes</a></span><span class="op">(</span>se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"log10 price"</span>, </span>
<span>       x <span class="op">=</span> <span class="st">"log10 size"</span>, </span>
<span>       title <span class="op">=</span> <span class="st">"House prices in Seattle"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-house-price-parallel-slopes" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-house-price-parallel-slopes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11-tell-your-story-with-data_files/figure-html/fig-house-price-parallel-slopes-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="FIGURE&nbsp;11.6: Interaction and parallel slopes models."><img src="11-tell-your-story-with-data_files/figure-html/fig-house-price-parallel-slopes-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-house-price-parallel-slopes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;11.6: Interaction and parallel slopes models.
</figcaption></figure>
</div>
</div>
</div>
<p>In both cases, we see there is a positive relationship between house price and size, meaning as houses are larger in size, they tend to be more expensive. Furthermore, in both plots it seems that houses of condition 5 tend to be the most expensive for most house sizes as evidenced by the fact that the line for condition 5 is highest, followed by conditions 4 and 3. As for conditions 1 and 2, this pattern isn’t as clear. Recall from the univariate barplot of <code>condition</code> in <a href="#fig-house-prices-viz" class="quarto-xref">Figure&nbsp;<span>11.3</span></a>, there are only a few houses of condition 1 or 2.</p>
<p>Let’s also show a faceted version of just the interaction model in <a href="#fig-house-price-interaction-2" class="quarto-xref">Figure&nbsp;<span>11.7</span></a>. It is now much more apparent just how few houses are of condition 1 or 2.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">house_prices</span>, </span>
<span>       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">log10_size</span>, y <span class="op">=</span> <span class="va">log10_price</span>, col <span class="op">=</span> <span class="va">condition</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.4</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"log10 price"</span>, </span>
<span>       x <span class="op">=</span> <span class="st">"log10 size"</span>, </span>
<span>       title <span class="op">=</span> <span class="st">"House prices in Seattle"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">condition</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This can be further checked using <code>dplyr</code> and its <code><a href="https://dplyr.tidyverse.org/reference/count.html">count()</a></code> function:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">house_prices</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">condition</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  condition     n
  &lt;fct&gt;     &lt;int&gt;
1 1            30
2 2           172
3 3         14031
4 4          5679
5 5          1701</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-house-price-interaction-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-house-price-interaction-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11-tell-your-story-with-data_files/figure-html/fig-house-price-interaction-2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="FIGURE&nbsp;11.7: Faceted plot of interaction model."><img src="11-tell-your-story-with-data_files/figure-html/fig-house-price-interaction-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-house-price-interaction-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;11.7: Faceted plot of interaction model.
</figcaption></figure>
</div>
</div>
</div>
<p>Which exploratory visualization of the interaction model is better, the one in the left-hand plot of <a href="#fig-house-price-parallel-slopes" class="quarto-xref">Figure&nbsp;<span>11.6</span></a> or the faceted version in <a href="#fig-house-price-interaction-2" class="quarto-xref">Figure&nbsp;<span>11.7</span></a>? There is no universal right answer. You need to make a choice depending on what you want to convey, and own that choice, with including and discussing both also as an option as needed.</p>
</section><section id="sec-house-prices-regression" class="level3" data-number="11.2.3"><h3 data-number="11.2.3" class="anchored" data-anchor-id="sec-house-prices-regression">
<span class="header-section-number">11.2.3</span> Regression modeling</h3>
<p>Which of the two models in <a href="#fig-house-price-parallel-slopes" class="quarto-xref">Figure&nbsp;<span>11.6</span></a> is “better”? The interaction model in the left-hand plot or the parallel slopes model in the right-hand plot?</p>
<p>With <em>model selection</em>, we should only favor more complex models if the additional complexity is <em>warranted</em>. In this case, the more complex model is the interaction model since it considers five intercepts and five slopes total. This is in contrast to the parallel slopes model which considers five intercepts but only one common slope.</p>
<p>Is the additional complexity of the interaction model warranted? Looking at the left-hand plot in <a href="#fig-house-price-parallel-slopes" class="quarto-xref">Figure&nbsp;<span>11.6</span></a>, we’re of the opinion that it is, as evidenced by the slight x-like (crossing) pattern to some of the lines. Therefore, we’ll focus the rest of this analysis only on the interaction model. (This visual approach is somewhat subjective, however, so feel free to disagree!) What are the five different slopes and five different intercepts for the interaction model? We can get these values from the regression table. Recall our two-step process for getting the regression table:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">price_interaction</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">log10_price</span> <span class="op">~</span> <span class="va">log10_size</span> <span class="op">*</span> <span class="va">condition</span>, data <span class="op">=</span> <span class="va">house_prices</span><span class="op">)</span></span>
<span><span class="fu"><a href="moderndive.github.io/moderndive/reference/get_regression_table.html">get_regression_table</a></span><span class="op">(</span><span class="va">price_interaction</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-seattle-interaction" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-seattle-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;11.1: Regression table for interaction model
</figcaption><div aria-describedby="tbl-seattle-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std_error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p_value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lower_ci</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upper_ci</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">3.330</td>
<td style="text-align: right;">0.451</td>
<td style="text-align: right;">7.380</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">2.446</td>
<td style="text-align: right;">4.215</td>
</tr>
<tr class="even">
<td style="text-align: left;">log10_size</td>
<td style="text-align: right;">0.690</td>
<td style="text-align: right;">0.148</td>
<td style="text-align: right;">4.652</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.399</td>
<td style="text-align: right;">0.980</td>
</tr>
<tr class="odd">
<td style="text-align: left;">condition: 2</td>
<td style="text-align: right;">0.047</td>
<td style="text-align: right;">0.498</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">0.925</td>
<td style="text-align: right;">-0.930</td>
<td style="text-align: right;">1.024</td>
</tr>
<tr class="even">
<td style="text-align: left;">condition: 3</td>
<td style="text-align: right;">-0.367</td>
<td style="text-align: right;">0.452</td>
<td style="text-align: right;">-0.812</td>
<td style="text-align: right;">0.417</td>
<td style="text-align: right;">-1.253</td>
<td style="text-align: right;">0.519</td>
</tr>
<tr class="odd">
<td style="text-align: left;">condition: 4</td>
<td style="text-align: right;">-0.398</td>
<td style="text-align: right;">0.453</td>
<td style="text-align: right;">-0.879</td>
<td style="text-align: right;">0.380</td>
<td style="text-align: right;">-1.286</td>
<td style="text-align: right;">0.490</td>
</tr>
<tr class="even">
<td style="text-align: left;">condition: 5</td>
<td style="text-align: right;">-0.883</td>
<td style="text-align: right;">0.457</td>
<td style="text-align: right;">-1.931</td>
<td style="text-align: right;">0.053</td>
<td style="text-align: right;">-1.779</td>
<td style="text-align: right;">0.013</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log10_size:condition2</td>
<td style="text-align: right;">-0.024</td>
<td style="text-align: right;">0.163</td>
<td style="text-align: right;">-0.148</td>
<td style="text-align: right;">0.882</td>
<td style="text-align: right;">-0.344</td>
<td style="text-align: right;">0.295</td>
</tr>
<tr class="even">
<td style="text-align: left;">log10_size:condition3</td>
<td style="text-align: right;">0.133</td>
<td style="text-align: right;">0.148</td>
<td style="text-align: right;">0.893</td>
<td style="text-align: right;">0.372</td>
<td style="text-align: right;">-0.158</td>
<td style="text-align: right;">0.424</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log10_size:condition4</td>
<td style="text-align: right;">0.146</td>
<td style="text-align: right;">0.149</td>
<td style="text-align: right;">0.979</td>
<td style="text-align: right;">0.328</td>
<td style="text-align: right;">-0.146</td>
<td style="text-align: right;">0.437</td>
</tr>
<tr class="even">
<td style="text-align: left;">log10_size:condition5</td>
<td style="text-align: right;">0.310</td>
<td style="text-align: right;">0.150</td>
<td style="text-align: right;">2.067</td>
<td style="text-align: right;">0.039</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">0.604</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Recall we saw in <a href="06-multiple-regression.html#sec-model4interactiontable" class="quarto-xref"><span>Section 6.1.2</span></a> how to interpret a regression table when there are both numerical and categorical explanatory variables. Let’s now do the same for all 10 values in the <code>estimate</code> column of <a href="#tbl-seattle-interaction" class="quarto-xref">Table&nbsp;<span>11.1</span></a>.</p>
<p>In this case, the “baseline for comparison” group for the categorical variable <code>condition</code> are the condition 1 houses, since “1” comes first alphanumerically. Thus, the <code>intercept</code> and <code>log10_size</code> values are the intercept and slope for <code>log10_size</code> for this baseline group. Next, the <code>condition2</code> through <code>condition5</code> terms are the <em>offsets</em> in intercepts relative to the condition 1 intercept. Finally, the <code>log10_size:condition2</code> through <code>log10_size:condition5</code> are the <em>offsets</em> in slopes for <code>log10_size</code> relative to the condition 1 slope for <code>log10_size</code>.</p>
<p>Let’s simplify this by writing out the equation of each of the five regression lines using these 10 <code>estimate</code> values. We’ll write out each line in the following format:</p>
<p><span class="math display">\[
\widehat{\log10(\text{price})} = \hat{\beta}_0 + \hat{\beta}_{\text{size}} \cdot \log10(\text{size})
\]</span></p>
<ol type="1">
<li>Condition 1:</li>
</ol>
<p><span class="math display">\[\widehat{\log10(\text{price})} = 3.33 + 0.69 \cdot \log10(\text{size})\]</span></p>
<ol start="2" type="1">
<li>Condition 2:</li>
</ol>
<p><span class="math display">\[
\begin{aligned}
\widehat{\log10(\text{price})} &amp;= (3.33 + 0.047) + (0.69 - 0.024) \cdot \log10(\text{size}) \\
&amp;= 3.377 + 0.666 \cdot \log10(\text{size})
\end{aligned}
\]</span></p>
<ol start="3" type="1">
<li>Condition 3:</li>
</ol>
<p><span class="math display">\[
\begin{aligned}
\widehat{\log10(\text{price})} &amp;= (3.33 - 0.367) + (0.69 + 0.133) \cdot \log10(\text{size}) \\
&amp;= 2.963 + 0.823 \cdot \log10(\text{size})
\end{aligned}
\]</span></p>
<ol start="4" type="1">
<li>Condition 4:</li>
</ol>
<p><span class="math display">\[
\begin{aligned}
\widehat{\log10(\text{price})} &amp;= (3.33 - 0.398) + (0.69 + 0.146) \cdot \log10(\text{size}) \\
&amp;= 2.932 + 0.836 \cdot \log10(\text{size})
\end{aligned}
\]</span></p>
<ol start="5" type="1">
<li>Condition 5:</li>
</ol>
<p><span class="math display">\[
\begin{aligned}
\widehat{\log10(\text{price})} &amp;= (3.33 - 0.883) + (0.69 + 0.31) \cdot \log10(\text{size}) \\
&amp;= 2.447 + 1 \cdot \log10(\text{size})
\end{aligned}
\]</span></p>
<p>These correspond to the regression lines in the left-hand plot of <a href="#fig-house-price-parallel-slopes" class="quarto-xref">Figure&nbsp;<span>11.6</span></a> and the faceted plot in <a href="#fig-house-price-interaction-2" class="quarto-xref">Figure&nbsp;<span>11.7</span></a>. For homes of all five condition types, as the size of the house increases, the price increases. This is what most would expect. However, the rate of increase of price with size is fastest for the homes with conditions 3, 4, and 5 of 0.823, 0.836, and 1, respectively. These are the three largest slopes out of the five.</p>
</section><section id="sec-house-prices-making-predictions" class="level3" data-number="11.2.4"><h3 data-number="11.2.4" class="anchored" data-anchor-id="sec-house-prices-making-predictions">
<span class="header-section-number">11.2.4</span> Making predictions</h3>
<p>Say you’re a realtor and someone calls you asking you how much their home will sell for. They tell you that it’s in condition = 5 and is sized 1900 square feet. What do you tell them? Let’s use the interaction model we fit to make predictions!</p>
<p>We first make this prediction visually in <a href="#fig-house-price-interaction-3" class="quarto-xref">Figure&nbsp;<span>11.8</span></a>. The predicted <code>log10_price</code> of this house is marked with a black dot. This is where the following two lines intersect:</p>
<ul>
<li>The regression line for the condition = 5 homes and</li>
<li>The vertical dashed black line at <code>log10_size</code> equals 3.28, since our predictor variable is the log10 transformed square feet of living space of <span class="math inline">\(\log10(1900) = 3.28\)</span>.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-house-price-interaction-3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-house-price-interaction-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11-tell-your-story-with-data_files/figure-html/fig-house-price-interaction-3-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="FIGURE&nbsp;11.8: Interaction model with prediction."><img src="11-tell-your-story-with-data_files/figure-html/fig-house-price-interaction-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-house-price-interaction-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;11.8: Interaction model with prediction.
</figcaption></figure>
</div>
</div>
</div>
<p>Eyeballing it, it seems the predicted <code>log10_price</code> seems to be around 5.75. Let’s now find the exact numerical value for the prediction using the equation of the regression line for the condition = 5 houses, being sure to <code><a href="https://rdrr.io/r/base/Log.html">log10()</a></code> the square footage first.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fl">2.45</span> <span class="op">+</span> <span class="fl">1</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log10</a></span><span class="op">(</span><span class="fl">1900</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.73</code></pre>
</div>
</div>
<p>This value is very close to our earlier visually made prediction of 5.75. But wait! Is our prediction for the price of this house $5.75? No, because we are using <code>log10_price</code> as our outcome variable! If we want a prediction in dollar units of <code>price</code>, we need to un-log this by taking a power of 10.</p>
<div class="cell" data-layout-align="center">
<p>This described in <a href="https://moderndive.com/v2/appendixa">Appendix A online</a>.</p>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fl">10</span><span class="op">^</span><span class="op">(</span><span class="fl">2.45</span> <span class="op">+</span> <span class="fl">1</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log10</a></span><span class="op">(</span><span class="fl">1900</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 535493</code></pre>
</div>
</div>
<p>Our predicted price for this home of condition 5 and of size 1900 square feet is $535,493.</p>
</section><section id="sec-house-prices-inference-for-regression" class="level3" data-number="11.2.5"><h3 data-number="11.2.5" class="anchored" data-anchor-id="sec-house-prices-inference-for-regression">
<span class="header-section-number">11.2.5</span> Inference for multiple linear regression</h3>
<p>Let’s next check the results of our multiple linear regression on house prices using both theory-based and simulation-based methods with hypothesis testing.</p>
<section id="theory-based-hypothesis-testing-for-partial-slopes" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="theory-based-hypothesis-testing-for-partial-slopes">Theory-based hypothesis testing for partial slopes</h4>
<p>Recall the results of our theory-based inference that were shown when we interpreted the <code>estimate</code> column of <code>get_regression_table(price_interaction)</code> in <a href="#tbl-seattle-interaction" class="quarto-xref">Table&nbsp;<span>11.1</span></a> and are shown again in <a href="#tbl-price-inter-table-again" class="quarto-xref">Table&nbsp;<span>11.2</span></a>. We can now use these values to perform hypothesis tests on the partial slopes.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">price_interaction</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">log10_price</span> <span class="op">~</span> <span class="va">log10_size</span> <span class="op">*</span> <span class="va">condition</span>, data <span class="op">=</span> <span class="va">house_prices</span><span class="op">)</span></span>
<span><span class="fu"><a href="moderndive.github.io/moderndive/reference/get_regression_table.html">get_regression_table</a></span><span class="op">(</span><span class="va">price_interaction</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-price-inter-table-again" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-price-inter-table-again-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TABLE&nbsp;11.2: Regression table for interaction model (shown again)
</figcaption><div aria-describedby="tbl-price-inter-table-again-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std_error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p_value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lower_ci</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upper_ci</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">3.330</td>
<td style="text-align: right;">0.451</td>
<td style="text-align: right;">7.380</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">2.446</td>
<td style="text-align: right;">4.215</td>
</tr>
<tr class="even">
<td style="text-align: left;">log10_size</td>
<td style="text-align: right;">0.690</td>
<td style="text-align: right;">0.148</td>
<td style="text-align: right;">4.652</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.399</td>
<td style="text-align: right;">0.980</td>
</tr>
<tr class="odd">
<td style="text-align: left;">condition: 2</td>
<td style="text-align: right;">0.047</td>
<td style="text-align: right;">0.498</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">0.925</td>
<td style="text-align: right;">-0.930</td>
<td style="text-align: right;">1.024</td>
</tr>
<tr class="even">
<td style="text-align: left;">condition: 3</td>
<td style="text-align: right;">-0.367</td>
<td style="text-align: right;">0.452</td>
<td style="text-align: right;">-0.812</td>
<td style="text-align: right;">0.417</td>
<td style="text-align: right;">-1.253</td>
<td style="text-align: right;">0.519</td>
</tr>
<tr class="odd">
<td style="text-align: left;">condition: 4</td>
<td style="text-align: right;">-0.398</td>
<td style="text-align: right;">0.453</td>
<td style="text-align: right;">-0.879</td>
<td style="text-align: right;">0.380</td>
<td style="text-align: right;">-1.286</td>
<td style="text-align: right;">0.490</td>
</tr>
<tr class="even">
<td style="text-align: left;">condition: 5</td>
<td style="text-align: right;">-0.883</td>
<td style="text-align: right;">0.457</td>
<td style="text-align: right;">-1.931</td>
<td style="text-align: right;">0.053</td>
<td style="text-align: right;">-1.779</td>
<td style="text-align: right;">0.013</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log10_size:condition2</td>
<td style="text-align: right;">-0.024</td>
<td style="text-align: right;">0.163</td>
<td style="text-align: right;">-0.148</td>
<td style="text-align: right;">0.882</td>
<td style="text-align: right;">-0.344</td>
<td style="text-align: right;">0.295</td>
</tr>
<tr class="even">
<td style="text-align: left;">log10_size:condition3</td>
<td style="text-align: right;">0.133</td>
<td style="text-align: right;">0.148</td>
<td style="text-align: right;">0.893</td>
<td style="text-align: right;">0.372</td>
<td style="text-align: right;">-0.158</td>
<td style="text-align: right;">0.424</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log10_size:condition4</td>
<td style="text-align: right;">0.146</td>
<td style="text-align: right;">0.149</td>
<td style="text-align: right;">0.979</td>
<td style="text-align: right;">0.328</td>
<td style="text-align: right;">-0.146</td>
<td style="text-align: right;">0.437</td>
</tr>
<tr class="even">
<td style="text-align: left;">log10_size:condition5</td>
<td style="text-align: right;">0.310</td>
<td style="text-align: right;">0.150</td>
<td style="text-align: right;">2.067</td>
<td style="text-align: right;">0.039</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">0.604</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>For this model, we can perform hypothesis tests on the partial slopes with an <span class="math inline">\(\alpha\)</span> significance level set to 0.05. For example, we can test the null hypothesis that the partial slope for <code>log10_size</code> is zero. Looking at the <span class="math inline">\(p\)</span>-value in the row corresponding to <code>log10_size</code> we see a value of 0 and a large <code>statistic</code> of 4.652. With <span class="math inline">\(\alpha = 0.05\)</span>, <code>log10_size</code> is the only regressor with a statistically significant relationship with <code>log10_price</code> in this theory-based model.</p>
</section><section id="simulation-based-hypothesis-testing-for-partial-slopes" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="simulation-based-hypothesis-testing-for-partial-slopes">Simulation-based hypothesis testing for partial slopes</h4>
<p>We can also perform hypothesis tests on the partial slopes using simulation-based methods. We can use the <code><a href="https://generics.r-lib.org/reference/fit.html">fit()</a></code> function and some of the other <code>infer</code> verbs to do so to check the results of our theory-based inference.</p>
<p>Let’s begin by retrieving the observed fit values from our <code>price_interaction</code> model:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">observed_fit_coefficients</span> <span class="op">&lt;-</span> <span class="va">house_prices</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/specify.html">specify</a></span><span class="op">(</span></span>
<span>    <span class="va">log10_price</span> <span class="op">~</span> <span class="va">log10_size</span> <span class="op">*</span> <span class="va">condition</span></span>
<span>    <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/fit.html">fit</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">observed_fit_coefficients</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   term                  estimate
   &lt;chr&gt;                    &lt;dbl&gt;
 1 intercept               3.33  
 2 log10_size              0.690 
 3 condition2              0.0470
 4 condition3             -0.367 
 5 condition4             -0.398 
 6 condition5             -0.883 
 7 log10_size:condition2  -0.0242
 8 log10_size:condition3   0.133 
 9 log10_size:condition4   0.146 
10 log10_size:condition5   0.310 </code></pre>
</div>
</div>
<p>Next, we build a null distribution of the partial slopes using the <code><a href="https://infer.tidymodels.org/reference/generate.html">generate()</a></code> function and the <code><a href="https://generics.r-lib.org/reference/fit.html">fit()</a></code> function, setting <code><a href="https://infer.tidymodels.org/reference/hypothesize.html">hypothesize()</a></code> to <code>null = "independence"</code> which will shuffle the values of the response variable <code>log10_price</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">null_distribution_housing</span> <span class="op">&lt;-</span> <span class="va">house_prices</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/specify.html">specify</a></span><span class="op">(</span></span>
<span>    <span class="va">log10_price</span> <span class="op">~</span> <span class="va">log10_size</span> <span class="op">*</span> <span class="va">condition</span></span>
<span>    <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/hypothesize.html">hypothesize</a></span><span class="op">(</span>null <span class="op">=</span> <span class="st">"independence"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/generate.html">generate</a></span><span class="op">(</span>reps <span class="op">=</span> <span class="fl">1000</span>, type <span class="op">=</span> <span class="st">"permute"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/fit.html">fit</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We then visualize this null distribution and shade the observed fit values to see if they are statistically significant.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://infer.tidymodels.org/reference/visualize.html">visualize</a></span><span class="op">(</span><span class="va">null_distribution_housing</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/shade_p_value.html">shade_p_value</a></span><span class="op">(</span>obs_stat <span class="op">=</span> <span class="va">observed_fit_coefficients</span>, </span>
<span>                direction <span class="op">=</span> <span class="st">"two-sided"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="11-tell-your-story-with-data_files/figure-html/tell-your-story-with-data-conditional-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="11-tell-your-story-with-data_files/figure-html/tell-your-story-with-data-conditional-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>Of the regressors, it appears that only <code>log10_size</code> has a statistically significant relationship with <code>log10_price</code>. This is evidenced by the fact that the observed fit value for <code>log10_size</code> is far outside the range of the null distribution.</p>
<p>Lastly, we can calculate the <span class="math inline">\(p\)</span>-value for the partial slopes using the <code><a href="https://infer.tidymodels.org/reference/get_p_value.html">get_p_value()</a></code> function.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">null_distribution_housing</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/get_p_value.html">get_p_value</a></span><span class="op">(</span>obs_stat <span class="op">=</span> <span class="va">observed_fit_coefficients</span>, direction <span class="op">=</span> <span class="st">"two-sided"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   term                  p_value
   &lt;chr&gt;                   &lt;dbl&gt;
 1 condition2              0.948
 2 condition3              0.538
 3 condition4              0.508
 4 condition5              0.178
 5 intercept               0    
 6 log10_size              0.002
 7 log10_size:condition2   0.916
 8 log10_size:condition3   0.486
 9 log10_size:condition4   0.454
10 log10_size:condition5   0.148</code></pre>
</div>
</div>
<p>The <span class="math inline">\(p\)</span>-value matches up with this conclusion. Only <code>log10_size</code> appears to be a significant regressor for predicting <code>log10_price</code> in this model. This matches with the findings we had from our theory-based analysis for this same model. Remember that this won’t always be the case depending on the distributions of the variables and whether assumptions hold.</p>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC11.1)</strong> Check that the LINE conditions are met for inference to be made in this Seattle house prices example with <code>price_interaction &lt;- lm(log10_price ~ log10_size * condition, data = house_prices)</code>.</p>
<p><strong>(LC11.2)</strong> Repeat the regression modeling in <a href="#sec-house-prices-regression" class="quarto-xref"><span>Section 11.2.3</span></a> and the prediction making you just did on the house of condition 5 and size 1900 square feet in <a href="#sec-house-prices-making-predictions" class="quarto-xref"><span>Section 11.2.4</span></a>, but using the parallel slopes model you visualized in <a href="#fig-house-price-parallel-slopes" class="quarto-xref">Figure&nbsp;<span>11.6</span></a>.</p>
<p><strong>(LC11.3)</strong> Interpret the results of the other rows in terms of inference in the <code>get_regression_table(price_interaction)</code> output in <a href="#tbl-seattle-interaction" class="quarto-xref">Table&nbsp;<span>11.1</span></a> that we did not interpret in <a href="#sec-house-prices-inference-for-regression" class="quarto-xref"><span>Section 11.2.5</span></a>.</p>
<p><strong>(LC11.4)</strong> Create, visualize, and interpret confidence intervals using both theory-based and simulation-based approaches to mirror the hypothesis testing done in <a href="#sec-house-prices-inference-for-regression" class="quarto-xref"><span>Section 11.2.5</span></a>.</p>
</div>
</section></section></section><section id="sec-data-journalism" class="level2" data-number="11.3"><h2 data-number="11.3" class="anchored" data-anchor-id="sec-data-journalism">
<span class="header-section-number">11.3</span> Case study: effective data storytelling</h2>
<p>As we’ve progressed throughout this book, you’ve seen how to work with data in a variety of ways. You’ve learned effective strategies for plotting data by understanding which types of plots work best for which combinations of variable types. You’ve summarized data in spreadsheet form and calculated summary statistics for a variety of different variables. Furthermore, you’ve seen the value of statistical inference as a process to come to conclusions about a population by using sampling. Lastly, you’ve explored how to fit linear regression models and the importance of checking the conditions required so that all confidence intervals and hypothesis tests have valid interpretation. All throughout, you’ve learned many computational techniques and focused on writing R code that’s reproducible.</p>
<p>We now present another set of case studies, but this time on the “effective data storytelling” done by data journalists around the world. Great data stories don’t mislead the reader, but rather engulf them in understanding the importance that data plays in our lives through storytelling.</p>
<section id="bechdel-test-for-hollywood-gender-representation" class="level3" data-number="11.3.1"><h3 data-number="11.3.1" class="anchored" data-anchor-id="bechdel-test-for-hollywood-gender-representation">
<span class="header-section-number">11.3.1</span> Bechdel test for Hollywood gender representation</h3>
<p>We recommend you read and analyze Walt Hickey’s FiveThirtyEight.com article, <a href="http://fivethirtyeight.com/features/the-dollar-and-cents-case-against-hollywoods-exclusion-of-women/">“The Dollar-And-Cents Case Against Hollywood’s Exclusion of Women.”</a> In it, Walt completed a multi-decade study of how many movies pass the <a href="https://bechdeltest.com/">Bechdel test</a>, an informal test of gender representation in a movie that was created by Alison Bechdel.</p>
<p>As you read over the article, think carefully about how Walt Hickey is using data, graphics, and analyses to tell the reader a story. In the spirit of reproducibility, FiveThirtyEight have also shared the <a href="https://github.com/fivethirtyeight/data/tree/master/bechdel">data and R code</a> that they used for this article. You can also find the data used in many more of their articles on their <a href="https://github.com/fivethirtyeight/data">GitHub</a> page.</p>
<p><em>ModernDive</em> co-authors Chester Ismay and Albert Y. Kim along with Jennifer Chunn went one step further by creating the <code>fivethirtyeight</code> package which provides access to these datasets more easily in R. For a complete list of all 129 datasets included in the <code>fivethirtyeight</code> package, check out the package webpage at <a href="https://fivethirtyeight-r.netlify.app/articles/fivethirtyeight.html" class="uri">https://fivethirtyeight-r.netlify.app/articles/fivethirtyeight.html</a>.</p>
<p>Furthermore, example “vignettes” of fully reproducible start-to-finish analyses of some of these data using <code>dplyr</code>, <code>ggplot2</code>, and other packages in the <code>tidyverse</code> are available <a href="https://fivethirtyeight-r.netlify.app/articles/">here</a>. For example, a vignette showing how to reproduce one of the plots at the end of the article on the Bechdel test is available <a href="https://fivethirtyeightdata.github.io/fivethirtyeightdata/articles/bechdel.html">here</a>.</p>
</section><section id="us-births-in-1999" class="level3" data-number="11.3.2"><h3 data-number="11.3.2" class="anchored" data-anchor-id="us-births-in-1999">
<span class="header-section-number">11.3.2</span> US Births in 1999</h3>
<p>The <code>US_births_1994_2003</code> data frame included in the <code>fivethirtyeight</code> package provides information about the number of daily births in the United States between 1994 and 2003. For more information on this data frame including a link to the original article on FiveThirtyEight.com, check out the help file by running <code><a href="https://rdrr.io/pkg/fivethirtyeight/man/US_births_1994_2003.html">?US_births_1994_2003</a></code> in the console.</p>
<p>It’s always a good idea to preview your data, either by using RStudio’s spreadsheet <code><a href="https://rdrr.io/r/utils/View.html">View()</a></code> function or using <code><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse()</a></code> from the <code>dplyr</code> package:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">US_births_1994_2003</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,652
Columns: 6
$ year          &lt;int&gt; 1994, 1994, 1994, 1994, 1994, 1994, 1994, 1994, 1994, 19…
$ month         &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ date_of_month &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…
$ date          &lt;date&gt; 1994-01-01, 1994-01-02, 1994-01-03, 1994-01-04, 1994-01…
$ day_of_week   &lt;ord&gt; Sat, Sun, Mon, Tues, Wed, Thurs, Fri, Sat, Sun, Mon, Tue…
$ births        &lt;int&gt; 8096, 7772, 10142, 11248, 11053, 11406, 11251, 8653, 791…</code></pre>
</div>
</div>
<p>We’ll focus on the number of <code>births</code> for each <code>date</code>, but only for births that occurred in 1999. Recall from <a href="03-wrangling.html#sec-filter" class="quarto-xref"><span>Section 3.2</span></a> we can do this using the <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> function from the <code>dplyr</code> package:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">US_births_1999</span> <span class="op">&lt;-</span> <span class="va">US_births_1994_2003</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">year</span> <span class="op">==</span> <span class="fl">1999</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>As discussed in <a href="02-visualization.html#sec-linegraphs" class="quarto-xref"><span>Section 2.4</span></a>, since <code>date</code> is a notion of time and thus has sequential ordering to it, a linegraph would be a more appropriate visualization to use than a scatterplot. In other words, we should use a <code><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line()</a></code> instead of <code><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point()</a></code>. Recall that such plots are called <em>time series</em> plots.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">US_births_1999</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">date</span>, y <span class="op">=</span> <span class="va">births</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Date"</span>, </span>
<span>       y <span class="op">=</span> <span class="st">"Number of births"</span>, </span>
<span>       title <span class="op">=</span> <span class="st">"US Births in 1999"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-us-births" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-us-births-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11-tell-your-story-with-data_files/figure-html/fig-us-births-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="FIGURE&nbsp;11.9: Number of births in the US in 1999."><img src="11-tell-your-story-with-data_files/figure-html/fig-us-births-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-us-births-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIGURE&nbsp;11.9: Number of births in the US in 1999.
</figcaption></figure>
</div>
</div>
</div>
<p>In <a href="#fig-us-births" class="quarto-xref">Figure&nbsp;<span>11.9</span></a>, we see a big dip occurring just before January 1st, 2000, most likely due to the holiday season. However, what about the large spike of over 14,000 births occurring just before October 1st, 1999? What could be the reason for this anomalously high spike?</p>
<p>Let’s sort the rows of <code>US_births_1999</code> in descending order of the number of births. Recall from <a href="03-wrangling.html#sec-arrange" class="quarto-xref"><span>Section 3.6</span></a> that we can use the <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> function from the <code>dplyr</code> function to do this, making sure to sort <code>births</code> in <code>desc</code>ending order:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">US_births_1999</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">births</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 365 × 6
    year month date_of_month date       day_of_week births
   &lt;int&gt; &lt;int&gt;         &lt;int&gt; &lt;date&gt;     &lt;ord&gt;        &lt;int&gt;
 1  1999     9             9 1999-09-09 Thurs        14540
 2  1999    12            21 1999-12-21 Tues         13508
 3  1999     9             8 1999-09-08 Wed          13437
 4  1999     9            21 1999-09-21 Tues         13384
 5  1999     9            28 1999-09-28 Tues         13358
 6  1999     7             7 1999-07-07 Wed          13343
 7  1999     7             8 1999-07-08 Thurs        13245
 8  1999     8            17 1999-08-17 Tues         13201
 9  1999     9            10 1999-09-10 Fri          13181
10  1999    12            28 1999-12-28 Tues         13158
# ℹ 355 more rows</code></pre>
</div>
</div>
<p>The date with the highest number of births (14,540) is in fact 1999-09-09. If we write down this date in month/day/year format (a standard format in the US), the date with the highest number of births is 9/9/99! All nines! Could it be that parents deliberately induced labor at a higher rate on this date? Maybe? Whatever the cause may be, this fact makes a fun story!</p>
<div class="learncheck">
<p><strong>Learning Check</strong></p>
<p><strong>(LC11.5)</strong> What date between 1994 and 2003 has the fewest number of births in the US? What story could you tell about why this is the case?</p>
</div>
<p>Time to think with data and further tell your story with data! How could statistical modeling help you here? What types of statistical inference would be helpful? What else can you find and where can you take this analysis? What assumptions did you make in this analysis? We leave these questions to you as the reader to explore and examine. Remember to get in touch with us via our contact info in the Preface. We’d love to see what you come up with!</p>
<p>Please check out additional problem sets and labs at <a href="https://moderndive.com/labs" class="uri">https://moderndive.com/labs</a>.</p>
</section><section id="scripts-of-r-code" class="level3" data-number="11.3.3"><h3 data-number="11.3.3" class="anchored" data-anchor-id="scripts-of-r-code">
<span class="header-section-number">11.3.3</span> Scripts of R code</h3>
<div class="cell" data-layout-align="center">
<p>An R script file of all R code used in this chapter is available <a href="scripts/11-tell-your-story-with-data.R">here</a>.</p>
</div>
<p>R code files saved as *.R files for all relevant chapters throughout the entire book are given:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 89%">
</colgroup>
<thead><tr class="header">
<th style="text-align: right;">chapter</th>
<th style="text-align: left;">link</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">https://moderndive.com/v2/scripts/01-getting-started.R</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">https://moderndive.com/v2/scripts/02-visualization.R</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">https://moderndive.com/v2/scripts/03-wrangling.R</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">https://moderndive.com/v2/scripts/04-tidy.R</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">https://moderndive.com/v2/scripts/05-regression.R</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">https://moderndive.com/v2/scripts/06-multiple-regression.R</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">https://moderndive.com/v2/scripts/07-sampling.R</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: left;">https://moderndive.com/v2/scripts/08-confidence-intervals.R</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">https://moderndive.com/v2/scripts/09-hypothesis-testing.R</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: left;">https://moderndive.com/v2/scripts/10-inference-for-regression.R</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: left;">https://moderndive.com/v2/scripts/11-tell-your-story-with-data.R</td>
</tr>
</tbody>
</table>
</div>
</div>
</section></section><section id="quick-checks" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="quick-checks">Quick checks</h2>
<p>Test your understanding of the material in this chapter.</p>
<p><strong>Q1.</strong> When a numerical variable is <em>right-skewed</em> (a long right tail), a useful transformation often is:</p>
<ol type="a">
<li>Subtracting the mean</li>
<li>Squaring the values</li>
<li>Taking the logarithm (<code><a href="https://rdrr.io/r/base/Log.html">log10()</a></code>)</li>
<li>Multiplying by 10</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Show answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(c)</strong> Log transformation compresses large values relative to small ones, often producing a more symmetric distribution that’s easier to model.</p>
</div>
</div>
</div>
<p><strong>Q2.</strong> What’s the most important reason to communicate uncertainty (e.g., confidence intervals) along with point estimates in a data story?</p>
<ol type="a">
<li>To make the report longer</li>
<li>To accurately represent how much the estimate could vary across samples</li>
<li>To impress the reader with statistical jargon</li>
<li>To meet a regulatory requirement</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Show answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(b)</strong> Reporting only point estimates implies more precision than the data supports. CIs (or other uncertainty measures) honestly communicate sampling variability.</p>
</div>
</div>
</div>
<p><strong>Q3.</strong> Before fitting a regression model on real data, it’s good practice to:</p>
<ol type="a">
<li>Read the data dictionary and explore the variables visually</li>
<li>Always remove all rows with any missing values</li>
<li>Take the log of every variable</li>
<li>Skip exploratory analysis to save time</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Show answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a)</strong> EDA reveals data quality issues, distributions, outliers, and relationships that inform modeling decisions. The other answers are too aggressive defaults that often discard signal.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Chapter cheatsheet">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Chapter cheatsheet
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th>Pattern</th>
<th>What it does</th>
<th>Quick example</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>mutate(log10_var = log10(var))</code></td>
<td>Log-transform a right-skewed numerical variable</td>
<td><code>house_prices \|&gt; mutate(log10_price = log10(price))</code></td>
</tr>
<tr class="even">
<td><code>lm(y ~ x1 * x2, data)</code></td>
<td>Interaction model — slopes vary by group</td>
<td><code>lm(log10_price ~ log10_size * condition, data = house_prices)</code></td>
</tr>
<tr class="odd">
<td>
<code>glimpse(df)</code> / <code>summary(df)</code>
</td>
<td>Quick look at structure / range of every column</td>
<td><code>glimpse(house_prices)</code></td>
</tr>
<tr class="even">
<td><code>ggplot(df, aes(x, fill = group)) + geom_histogram()</code></td>
<td>Faceted/colored histograms for EDA</td>
<td><code>ggplot(df, aes(x = log10_price, fill = condition)) + geom_histogram()</code></td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="concluding-remarks" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="concluding-remarks">Concluding remarks</h2>
<p>Now that you’ve made it to this point in the book, we suspect that you know a thing or two about how to work with data in R! You’ve also gained a lot of knowledge about how to use simulation-based techniques for statistical inference and how these techniques help build intuition about traditional theory-based inferential methods.</p>
<p>The hope is that you’ve come to appreciate the power of data in all respects, such as data wrangling, tidying datasets, data visualization, statistical/data modeling, and statistical inference. In our opinion, while each of these is important, data visualization may be the most important tool for a citizen or professional data scientist to have in their toolbox. If you can create truly beautiful graphics that display information in ways that the reader can clearly understand, you have great power to tell your tale with data. Let’s hope that these skills help you tell great stories with data into the future. Thanks for coming along this journey as we dove into modern data analysis using R and the <code>tidyverse</code>!</p>
</section><section id="appendix-appendix" class="level1 unnumbered cell" data-layout-align="center"><h1 class="unnumbered">(APPENDIX) Appendix</h1>
</section>


</main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
        for (let i=0; i<annoteTargets.length; i++) {
          const annoteTarget = annoteTargets[i];
          const targetCell = annoteTarget.getAttribute("data-target-cell");
          const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
          const contentFn = () => {
            const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            if (content) {
              const tipContent = content.cloneNode(true);
              tipContent.classList.add("code-annotation-tip-content");
              return tipContent.outerHTML;
            }
          }
          const config = {
            allowHTML: true,
            content: contentFn,
            onShow: (instance) => {
              selectCodeLines(instance.reference);
              instance.reference.classList.add('code-annotation-active');
              window.tippy.hideAll();
            },
            onHide: (instance) => {
              unselectCodeLines();
              instance.reference.classList.remove('code-annotation-active');
            },
            maxWidth: 300,
            delay: [50, 0],
            duration: [200, 0],
            offset: [5, 10],
            arrow: true,
            appendTo: function(el) {
              return el.parentElement.parentElement.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'quarto',
            placement: 'right',
            popperOptions: {
              modifiers: [
              {
                name: 'flip',
                options: {
                  flipVariations: false, // true by default
                  allowedAutoPlacements: ['right'],
                  fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                },
              },
              {
                name: 'preventOverflow',
                options: {
                  mainAxis: false,
                  altAxis: false
                }
              }
              ]        
            }      
          };
          window.tippy(annoteTarget, config); 
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./10-inference-for-regression.html" class="pagination-link" aria-label="Inference for Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Inference for Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./91-appendixA.html" class="pagination-link" aria-label="Statistical Background">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Statistical Background</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/moderndive/ModernDive_book/edit/v2/11-tell-your-story-with-data.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/moderndive/ModernDive_book/blob/v2/11-tell-your-story-with-data.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/moderndive/ModernDive_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>