project:
  type: book
  output-dir: docs
  post-render: R/post-render-cleanup.sh
  resources:
    - regression-plane.html
    - regression-plane-ISLR2.html
    - labs.html

book:
  title: "Statistical Inference via Data Science"
  subtitle: "A ModernDive into R and the Tidyverse (Second Edition)"
  author: "Chester Ismay, Albert Y. Kim, and Arturo Valdivia"
  date: today
  description: "An open-source and fully-reproducible electronic textbook for teaching statistical inference using tidyverse data science tools."
  repo-url: https://github.com/moderndive/ModernDive_book/
  repo-branch: v2
  repo-actions: [edit, source, issue]
  favicon: images/logos/favicons/favicon.ico
  chapters:
    - index.qmd
    - 00-foreword.qmd
    - 00-preface.qmd
    - 01-getting-started.qmd
    - part: "Data Science with tidyverse"
      chapters:
        - 02-visualization.qmd
        - 03-wrangling.qmd
        - 04-tidy.qmd
    - part: "Statistical Modeling with moderndive"
      chapters:
        - 05-regression.qmd
        - 06-multiple-regression.qmd
    - part: "Statistical Inference with infer"
      chapters:
        - 07-sampling.qmd
        - 08-confidence-intervals.qmd
        - 09-hypothesis-testing.qmd
        - 10-inference-for-regression.qmd
    - part: "Conclusion"
      chapters:
        - 11-tell-your-story-with-data.qmd
  appendices:
    - 91-appendixA.qmd
    - 92-appendixB.qmd
    - 93-appendixC.qmd
    - 94-appendixD.qmd
    - 95-appendixE.qmd
    - 99-references.qmd

bibliography: [bib/books.bib, bib/packages.bib, bib/articles.bib]

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: style.css
    include-in-header: _includes/analytics.html
    include-before-body: _includes/logo.html
    lightbox: true

crossref:
  fig-title: FIGURE
  tbl-title: TABLE
  chapters: true
