# For printing the PDF from the .tex file
if(!dir.exists("docs"))
  dir.create("docs")
file.copy("krantz.cls", "docs/krantz.cls", overwrite = TRUE)

# Keep all the intermediary files so they can be copied below
bookdown::render_book("index.Rmd", "bookdown::pdf_book",
                      clean = FALSE,
                      clean_envir = FALSE,
                      encoding = 'UTF-8')

# Rename the PDF generated by bookdown in the lines above
# so it isn't overwritten
file.rename(from = "docs/moderndive.pdf",
            to = paste0("docs/moderndive_", Sys.Date(), ".pdf"))

# figure-latex is removed from clean builds so need to copy it over
# to get images
if(!dir.exists("docs/moderndive_files/figure-latex"))
  dir.create("docs/moderndive_files/figure-latex", recursive = TRUE)
file.copy(from = "_bookdown_files/moderndive_files/figure-latex",
          to = "docs/moderndive_files",
          recursive = TRUE)

# Copy references over
if(!dir.exists("docs/bib"))
  dir.create("docs/bib")
file.copy(from = "bib", to = "docs", recursive = TRUE)

# Go to RStudio -> Preferences -> Sweave -> Typeset LaTeX into PDF
#  - Change to XeLaTeX
# Now open up moderndive.tex and press Compile PDF
