---
title: "ch7 toc 2nd Ed"
output:
  html_document:
    toc: true
    toc_depth: 5
    number_sections: true
---

# Sampling {#sampling}

### Needed packages {-#sampling-packages}

## First bowl activity {#sampling-activity}

### The proportion of red balls in the bowl {#population-proportion}

### Manual sampling {#sampling-manual}


#### One sample {#one-sample}
#### Thirty-three samples {#student-shovels}


### Virtual sampling {#sampling-simulation}
#### One virtual sample
#### Thirty-three virtual samples {#shovel-33-times}
#### One thousand virtual samples {#shovel-1000-times}
#### Different sample sizes {#different-shovels}

## Sampling framework {#sampling-framework}

### Population, sample, and the sampling distribution {#terminology-and-notation}

## The Central Limit Theorem {#central-limit-theorem}

### Random Variables

### The Sampling distribution using random variables

### The Center of the distribution: the expected value

### Sampling variation: standard deviation and standard error

#### The standard deviation

#### The standard error

#### The sampling distribution of the sample proportion

### Summary


## Second bowl activity {#sampling-activity}


### The population mean weight of almonds in the bowl {#population-mean}

### Manual sampling and sample means {#resampling-tactile-bowl}


### Virtual sampling {#virtual-samples-mean-bowl}

### The sampling distribution of the sample mean 

### Random variables

### The Central Limit Theorem revisited {#CLT-mean}

## The Sampling Distribution in Other Scenarios{#sampling-other-scenarios}

### Sampling distribution for two samples

#### Difference of sample means

#### Difference of sample proportions

### Regression slope

### Summary of scenarios

## Summary and Final Remarks
