---
title: "ch8 toc MD 2nd Ed"
output:
  html_document:
    toc: true
    toc_depth: 5
    number_sections: true
---


# Estimation, Confidence Intervals, and Bootstrapping {#confidence-intervals}

- Introducing the idea of estimation as the real goal. 
- Highlight sampling as a tool to understand estimation.
    - Introduce the idea of precision and accuracy
- Remark that in real-life examples one sample is all we get.



### Needed packages {-#CI-packages}


## Estimation: Revisiting the bowl activities {#estimation-bowl-activities}

### Estimating the proportion of red balls in the bowl {#estimation-proportion}

- Show any given sample proportion and compare it with the population proportion
- Pick the 33 sample proportions obtained earlier and show how close they are for the population proportion
- Discuss preShow how about 95% of the 20000 sample proportions are within 2 SE from the true population proportion
- Construct an interval based on any one sample and show how this interval contains the true population proportion

### Estimate the average weight of chocolate-covered almonds

- Show how about 95% of the 20000 sample means obtained earlier are within 2 SE from the sample mean
- Construct an interval based on any one sample and show how this interval contains the true population proportion

## Bootstrap sampling: Computer simulation of resampling {#resampling-simulation}

- Obtain one sample and introduce resampling with replacements from this sample. Introduce bootstrap sampling.
- Obtain 20000 bootstrap samples and obtain their sample means. Show how the histogram compares to the histogram of 20000 samples.
- Use the bootstrap samples to obtain the 95% interval

## Confidence Intervals framework

### Precision and accuracy (perhaps unbiasedness and consistency)
### Confidence Interval: the theory-based approach
### Confidence interval: the simulation-based approach

- Introduce some theory about bootstrap sampling

### Comparing theory- and simulation-based approaches

- Show benefits of using bootstrap over traditional methods
    - Add a simulation that shows this
- Add a note that in the remainder of the text, we’ll mainly focus on the simulation-based approach, but we'll use the traditional method for comparison



## Constructing confidence intervals using the simulation-based approach {#bootstrap-process}

### Original workflow

### `infer` package workflow {#infer-workflow}
#### 1. `specify` variables {-}
#### 2. `generate` replicates {-}
#### 3. `calculate` summary statistics {-}
#### 4. `visualize` the results {-}


### Percentile method with `infer` {#percentile-method-infer}
### Standard error method with `infer` {#infer-se}

## Interpreting confidence intervals {#one-prop-ci}

### Did the net capture the fish? {#ilyas-yohan}
#### 1. `specify` variables {-}
#### 2. `generate` replicates {-}
#### 3. `calculate` summary statistics {-}
#### 4. `visualize` the results {-}

### Precise and shorthand interpretation {#shorthand}
### Width of confidence intervals {#ci-width}
#### Impact of confidence level {-}
#### Impact of sample size {-}


## Theoretical Framework
### Why the simulation-based approach

Here comes the theory supporting the use of bootstrapping for inference
Some results based on simulations showing this (as hinted by Robert) would be useful here too

### Some details to take into account when using simulation-based confidence intervals

Best practices when using these methods
Introduce some theory/simulations/reference that show the bootstrap sample is an adequate method and could have some advantages over the theory-based approach






## Case study: Is yawning contagious? {#case-study-two-prop-ci}
### *Mythbusters* study data
### Sampling scenario
### Constructing the confidence interval {#ci-build}

#### 1. `specify` variables {-}
#### 2. `generate` replicates {-}
#### 3. `calculate` summary statistics {-}
#### 4. `visualize` the results {-}

### Interpreting the confidence interval

## Summary and Final Remarks

