{
  "hash": "b1461b997944527500c7f0b88f0fc2af",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Statistical Background {#sec-appendixA}\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n## Basic statistical terms {#sec-appendix-stat-terms}\n\nNote that all the following statistical terms apply only to *numerical* variables, except the *distribution* which can exist for both numerical and categorical variables. \n\n\n### Mean\n\nThe *mean* is the most commonly reported measure of center.  It is commonly called the *average* though this term can be a little ambiguous.  The mean is the sum of all of the data elements divided by how many elements there are. If we have $n$ data points, the mean is given by: \n\n$$Mean = \\frac{x_1 + x_2 + \\cdots + x_n}{n}$$\n\n\n### Median\n\nThe median is calculated by first sorting a variable's data from smallest to largest.  After sorting the data, the middle element in the list is the *median*.  If the middle falls between two values, then the median is the mean of those two middle values.\n\n\n### Standard deviation and variance {#sec-appendix-sd-variance}\n\nWe will next discuss the *standard deviation* ($sd$) of a variable.  The formula can be a little intimidating at first but it is important to remember that it is essentially a measure of how far we expect a given data value will be from its mean:\n\n$$sd = \\sqrt{\\frac{(x_1 - Mean)^2 + (x_2 - Mean)^2 + \\cdots + (x_n - Mean)^2}{n - 1}}$$\n\nThe *variance* of a variable is merely the standard deviation squared.\n\n$$variance = sd^2 = \\frac{(x_1 - Mean)^2 + (x_2 - Mean)^2 + \\cdots + (x_n - Mean)^2}{n - 1}$$\n\n\n### Five-number summary\n\nThe *five-number summary* consists of five summary statistics: the minimum, the first quantile AKA 25th percentile, the second quantile AKA median or 50th percentile, the third quantile AKA 75th, and the maximum. The five-number summary of a variable is used when constructing boxplots, as seen in @sec-boxplots.\n\nThe quantiles are calculated as\n\n- first quantile ($Q_1$): the median of the first half of the sorted data\n- third quantile ($Q_3$): the median of the second half of the sorted data\n\nThe *interquartile range (IQR)*\\index{interquartile range (IQR)} is defined as $Q_3 - Q_1$ and is a measure of how spread out the middle 50% of values are. The IQR corresponds to the length of the box in a boxplot.\n\nThe median and the IQR are not influenced by the presence of outliers in the ways that the mean and standard deviation are. They are, thus, recommended for skewed datasets. We say in this case that the median and IQR are more *robust to outliers*.\n\n\n### Distribution\n\nThe *distribution* of a variable shows how frequently different values of a variable occur. Looking at the visualization of a distribution can show where the values are centered, show how the values vary, and give some information about where a typical value might fall.  It can also alert you to the presence of outliers. \n\nRecall from @sec-viz that we can visualize the distribution of a numerical variable using binning in a histogram and that we can visualize the distribution of a categorical variable using a barplot.\n\n\n### Outliers\n\n*Outliers* correspond to values in the dataset that fall far outside the range of \"ordinary\" values.  In the context of a boxplot, by default they correspond to values below $Q_1 - (1.5 \\cdot IQR)$ or above $Q_3 + (1.5 \\cdot IQR)$.\n\n\n\n\n\n## Normal distribution {#sec-appendix-normal-curve}\n\nLet's next discuss one particular kind of distribution: \\index{distribution!normal} *normal distributions*. Such bell-shaped distributions are defined by two values: (1) the *mean* $\\mu$ (\"mu\") which locates the center of the distribution and (2) the *standard deviation* $\\sigma$ (\"sigma\") which determines the variation of the distribution. In @fig-normal-curves2, we plot three normal distributions where:\n\n1. The solid normal curve has mean $\\mu = 5$ \\& standard deviation $\\sigma = 2$.\n1. The dotted normal curve has mean $\\mu = 5$ \\& standard deviation $\\sigma = 5$.\n1. The dashed normal curve has mean $\\mu = 15$ \\& standard deviation $\\sigma = 2$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Three normal distributions.](91-appendixA_files/figure-html/fig-normal-curves2-1.png){#fig-normal-curves2 fig-alt='Three normal density curves overlaid: a tall narrow one centered at 5 (small SD), a wider one also at 5 (larger SD), and a tall narrow one shifted to 15 (different mean, small SD).' width=90%}\n:::\n:::\n\n\nNotice how the solid and dotted line normal curves have the same center due to their common mean $\\mu$ = 5. However, the dotted line normal curve is wider due to its larger standard deviation of $\\sigma$ = 5. On the other hand, the solid and dashed line normal curves have the same variation due to their common standard deviation $\\sigma$ = 2. However, they are centered at different locations. \n\nWhen the mean $\\mu$ = 0 and the standard deviation $\\sigma$ = 1, the normal distribution has a special name. It's called the *standard normal distribution* or the *$z$-curve*\\index{distribution!standard normal}.\n\nFurthermore, if a variable follows a normal curve, there are *three rules of thumb* we can use:\n\n1. 68% of values will lie within $\\pm$ 1 standard deviation of the mean.\n1. 95% of values will lie within $\\pm$ 1.96 $\\approx$ 2 standard deviations of the mean.\n1. 99.7% of values will lie within $\\pm$ 3 standard deviations of the mean.\n\nLet's illustrate this on a standard normal curve in @fig-normal-rule-of-thumb. The dashed lines are at -3, -1.96, -1, 0, 1, 1.96, and 3. These 7 lines cut up the x-axis into 8 segments. The areas under the normal curve for each of the 8 segments are marked and add up to 100%. For example:\n\n1. The middle two segments represent the interval -1 to 1. The shaded area above this interval represents 34% + 34% = 68% of the area under the curve. In other words, 68% of values. \n1. The middle four segments represent the interval -1.96 to 1.96. The shaded area above this interval represents 13.5% + 34% + 34% + 13.5% = 95% of the area under the curve. In other words, 95% of values. \n1. The middle six segments represent the interval -3 to 3. The shaded area above this interval represents 2.35% + 13.5% + 34% + 34% + 13.5% + 2.35% = 99.7% of the area under the curve. In other words, 99.7% of values. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Rules of thumb about areas under normal curves.](91-appendixA_files/figure-html/fig-normal-rule-of-thumb-1.png){#fig-normal-rule-of-thumb fig-alt='Standard normal curve with vertical lines at -3, -2, -1, 0, 1, 2, 3 standard deviations, each segment shaded and labeled with the corresponding area — the empirical 68-95-99.7 rule.' width=80%}\n:::\n:::\n\n\n\\vspace{0.1in}\n\n:::{.learncheck}\n**Learning Check**\n\n<!--\nv2 TODO: Consider LC using this later on: <https://gallery.shinyapps.io/dist_calc/>\n-->\n\nSay you have a normal distribution with mean $\\mu = 6$ and standard deviation $\\sigma = 3$. \n\n**(LCA.1)** What proportion of the area under the normal curve is less than 3? Greater than 12? Between 0 and 12?\n\n**(LCA.2)** What is the 2.5th percentile of the area under the normal curve? The 97.5th percentile? The 100th percentile?\n\n:::\n\n\\vspace{0.1in}\n\n### Additional normal calculations\n\nFor a normal density curve, the probabilities or areas for any given interval can be obtained using the R function `pnorm()`. Think of the `p` in the name as __p__robability or __p__ercentage as this function finds the area under the curve to the left of any given value which is the probability of observing any number less than or equal to that value. It is possible to indicate the appropriate expected value and standard deviation as arguments in the function, but the default uses the standard normal values, $\\mu = 0$ and $\\sigma = 1$. For example, the probability of observing a value that is less than or equal to 1 in the standard normal curve is given by:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.841\n```\n\n\n:::\n:::\n\n\nor 84%. This is the probability of observing a value that is less than or equal to one standard deviation above the mean. \n\nSimilarly, the probability of observing a standard value between -1 and 1 is given by subtracting the area to the left of -1 from the area to the left of 1. In R, we obtain this probability as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(1) - pnorm(-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.683\n```\n\n\n:::\n:::\n\nThe probability of getting a standard value between -1 and 1, or equivalently, the probability of observing a value within one standard deviation from the mean is about 68%. Similarly, the probability of getting a value within 2 standard deviations from the mean is given by\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(2) - pnorm(-2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.954\n```\n\n\n:::\n:::\n\nor about 95%. \n\nMoreover, we do not need to restrict our study to areas within one or two standard deviations from the mean. We can find the number of standard deviations needed for any desired percentage around the mean using the R function `qnorm()`. The `q` in the name stands for $quantile$ and this function can be thought of as the inverse or complement of `pnorm()`. It finds the value of the random variable for a given area under the curve to the left of this value. When using the standard normal, the quantile also represents the number of standard deviations. For example, we learned that the area under the standard normal curve to the left of a standard value of 1 was approximately 84%. If instead, we want to find the standard value that corresponds to exactly an area of 84% under the curve to the left of this value, we can use the following syntax:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.84)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.994\n```\n\n\n:::\n:::\n\nIn other words, there is exactly an 84% chance that the observed standard value is less than or equal to 0.994. Similarly, to have exactly a 95% chance of obtaining a value within `q` number of standard deviations from the mean, we need to select the appropriate value for `qnorm()`. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(NULL, aes(c(-4,4))) +\n  geom_area(stat = \"function\", fun = dnorm, fill = \"grey100\", xlim = c(-4, -2)) +\n  geom_area(stat = \"function\", fun = dnorm, fill = \"grey80\", xlim = c(-2, 2)) +\n  geom_area(stat = \"function\", fun = dnorm, fill = \"grey100\", xlim = c(2, 4)) +\n  labs(x = \"z\", y = \"\") +\n  scale_y_continuous(breaks = NULL) +\n  scale_x_continuous(breaks = NULL) + \n  annotate(geom=\"text\", x=2, y=-0.01, label=\"q\",\n           color=\"blue\")\n```\n\n::: {.cell-output-display}\n![](91-appendixA_files/figure-html/normal-curve-shaded-3-1.png){width=\\textwidth}\n:::\n:::\n\n\nWe want to find the standard value `q` such that the area in the middle is exactly 0.95 (or 95%). Before using `qnorm()` we need to provide the total area under the curve to the left of `q`. Since the total area under the normal density curve is 1, the curve is symmetric, and the area in the middle is 0.95, the total area on the tails is 1 - 0.95 = 0.05 (or 5%), and the area on each tail is 0.05/2 = 0.025 (or 2.5%). The total area under the curve to the left of `q` will be the area in the middle and the area on the left tail or 0.95 + 0.025 = 0.975. We can now obtain the standard value `q` by using `qnorm()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq <- qnorm(0.975)\nq\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.96\n```\n\n\n:::\n:::\n\nThe probability of observing a value within 1.96 standard deviations from the mean is exactly 95%.\n\nWe can follow this method to obtain the number of standard deviations needed for any area, or probability, around the mean. For example, if we want an area of 98% around the mean, the area on the tails is 1 - 0.98 = 0.02, or 0.02/2 = 0.01 on each tail, the area under the curve to the left of the desired `q` value would be 0.98 + 0.01 = 0.99 so\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.33\n```\n\n\n:::\n:::\n\nThe area within 2.33 standard deviations from the mean is 98%, or there is a 98% chance of choosing a value within 2.33 standard deviations from the mean. This information will be very useful to us.\n\n## The t distribution calculations\n\nThe syntax in R for the $t$ distribution is analogous to the standard normal distribution. We use the function `pt()` instead of `pnorm()` and `qt()` instead of `qnorm()`.\nIn addition, the $t$ distribution requires one additional parameter, the degrees of freedom. For the sample mean problems, the degrees of freedom needed are exactly $n-1$, the size of the samples minus one.\n\nWe construct again a 95% confidence interval for the population mean, but this time using the sample standard deviation to estimate the standard error and the $t$ distribution to determine how wide the confidence interval should be.\n\nWe start by obtaining the sample statistics:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalmonds_sample_100 |> \nsummarize(mean_weight = mean(weight),\nsd_weight = sd(weight),\nsample_size = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  replicate mean_weight sd_weight sample_size\n      <int>       <dbl>     <dbl>       <int>\n1         1        3.68     0.362         100\n```\n\n\n:::\n:::\n\nTo obtain the number of standard deviations on the $t$ distribution to account for 95% of the values, we proceed as we did in the normal case: the area in the middle is 0.95, so the area on the tails is 1-0.95 = 0.05. Since the $t$ distribution is also symmetric, the area on each tail is 0.05/2 - 0.025. The number of standard deviation around the center is given by the value $q$ such as the area under the $t$ curve to the left of $q$ is exactly $0.95 + 0.025 = 0.975$. Using R we get:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(0.975, df = 100 - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.98\n```\n\n\n:::\n:::\n\nSo, in order to account for 95% of the observations around the mean, we need to take into account all the values within 1.98 standard deviation from the mean. Compare this number with the 1.96 obtained for the standard normal; the difference is due to the fact that the $t$ curve has thicker tails than the standard normal.\nWe can now construct the 95% confidence interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 3.682 \nse_xbar <- 0.362/sqrt(100)\nlower_bound <- xbar - 1.98 *  se_xbar\nupper_bound <- xbar + 1.98 *  se_xbar\nc(lower_bound, upper_bound)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.61 3.75\n```\n\n\n:::\n:::\n\nWe are 95% confident that the population mean weight of almonds is a number between 3.61 and 3.75 grams.\n\n\n## log10 transformations {#sec-appendix-log10-transformations}\n\nAt its simplest, log10 transformations return base 10 *logarithms*. For example, since $1000 = 10^3$, running `log10(1000)` returns `3` in R. To undo a log10 transformation, we raise 10 to this value. For example, to undo the previous log10 transformation and return the original value of 1000, we raise 10 to the power of 3 by running `10^(3) = 1000` in R. \\index{log transformations}\n\nLog transformations allow us to focus on changes in *orders of magnitude*. In other words, they allow us to focus on *multiplicative changes* instead of *additive ones*. Let's illustrate this idea in @tbl-logten with examples of prices of consumer goods in 2019 US dollars. \n\n<!--\nv2 TODO: Add text like:\nWe can also frame such changes as being relative percentage increases/decreases\ninstead of absolute increases/decreases.\n-->\n\n\n::: {#tbl-logten .cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"font-size: 16px; margin-left: auto; margin-right: auto;\">\n<caption style=\"font-size: initial !important;\">log10 transformed prices, orders of magnitude, and examples</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Price </th>\n   <th style=\"text-align:right;\"> log10(Price) </th>\n   <th style=\"text-align:left;\"> Order of magnitude </th>\n   <th style=\"text-align:left;\"> Examples </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> $1 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:left;\"> Singles </td>\n   <td style=\"text-align:left;\"> Cups of coffee </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> $10 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:left;\"> Tens </td>\n   <td style=\"text-align:left;\"> Books </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> $100 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:left;\"> Hundreds </td>\n   <td style=\"text-align:left;\"> Mobile phones </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> $1,000 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:left;\"> Thousands </td>\n   <td style=\"text-align:left;\"> High definition TVs </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> $10,000 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:left;\"> Tens of thousands </td>\n   <td style=\"text-align:left;\"> Cars </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> $100,000 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:left;\"> Hundreds of thousands </td>\n   <td style=\"text-align:left;\"> Luxury cars and houses </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> $1,000,000 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:left;\"> Millions </td>\n   <td style=\"text-align:left;\"> Luxury houses </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nLet's make some remarks about log10 transformations based on @tbl-logten:\n\n1. When purchasing a cup of coffee, we tend to think of prices ranging in single dollars, such as \\$2 or \\$3. However, when purchasing a mobile phone, we don't tend to think of their prices in units of single dollars such as \\$313 or \\$727. Instead, we tend to think of their prices in units of hundreds of dollars like \\$300 or \\$700. Thus, cups of coffee and mobile phones are of different *orders of magnitude* in price.\n1. Let's say we want to know the log10 transformed value of \\$76. This would be hard to compute exactly without a calculator. However, since \\$76 is between \\$10 and \\$100 and since log10(10) = 1 and log10(100) = 2, we know log10(76) will be between 1 and 2. In fact, log10(76) is 1.880814.\n1. log10 transformations are *monotonic*, meaning they preserve orders. So if Price A is lower than Price B, then log10(Price A) will also be lower than log10(Price B).\n1. Most importantly, increments of one in log10-scale correspond to *relative multiplicative changes* in the original scale and not *absolute additive changes*. For example, increasing a log10(Price) from 3 to 4 corresponds to a multiplicative increase by a factor of 10: \\$100 to \\$1000.\n",
    "supporting": [
      "91-appendixA_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}