<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ex</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="02_ex_files/libs/clipboard/clipboard.min.js"></script>
<script src="02_ex_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="02_ex_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="02_ex_files/libs/quarto-html/popper.min.js"></script>
<script src="02_ex_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="02_ex_files/libs/quarto-html/anchor.min.js"></script>
<link href="02_ex_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="02_ex_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="02_ex_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="02_ex_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="02_ex_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<p>Solutions for the end-of-chapter exercises in <em>Chapter 2 — Data Visualization</em>. The dataset is <code>olympic_athletes</code> (≈315k athlete-event rows, 1896–2026), accompanied by <code>medal_table</code> (medal counts per Games × NOC for 2018–2026) and <code>editions</code> (metadata for the five most recent Games), all from the <a href="https://github.com/moderndive/olympicAthletes"><code>olympicAthletes</code></a> package.</p>
<div class="callout callout-style-simple callout-tip callout-titled" title="Section coverage at a glance">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Section coverage at a glance
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><strong>Exercises per section</strong> — count of prompts that touch each book section.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Book section</th>
<th style="text-align: right;"># of exercises</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Setup / data exploration (chapter overview)</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td>2.1 The grammar of graphics</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td>2.2 Five named graphs (5NG)</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>2.3 Scatterplots</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td>2.4 Linegraphs</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td>2.5 Histograms</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td>2.6 Facets</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td>2.7 Boxplots</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td>2.8 Barplots</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td>Critical thinking / open exploration</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td>Extensions</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>
<p><strong>Exercises by subsection</strong> — which prompts target each finer-grained subsection.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Subsection</th>
<th>Exercises</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Setup and data exploration</td>
<td>EX2.1, EX2.2, EX2.3, EX2.4</td>
</tr>
<tr class="even">
<td>2.1 The grammar of graphics</td>
<td>EX2.5</td>
</tr>
<tr class="odd">
<td>2.3 Scatterplots (<code>geom_point</code>)</td>
<td>EX2.6, EX2.9, EX2.10, EX2.11</td>
</tr>
<tr class="even">
<td>2.3.1 Overplotting (<code>alpha</code>, color)</td>
<td>EX2.7, EX2.8</td>
</tr>
<tr class="odd">
<td>2.4 Linegraphs (<code>geom_line</code>)</td>
<td>EX2.12, EX2.13, EX2.14</td>
</tr>
<tr class="even">
<td>2.5 Histograms (<code>geom_histogram</code>)</td>
<td>EX2.15, EX2.17, EX2.18</td>
</tr>
<tr class="odd">
<td>2.5.1 Adjusting bins</td>
<td>EX2.16</td>
</tr>
<tr class="even">
<td>2.6 Facets (<code>facet_wrap</code>)</td>
<td>EX2.19, EX2.20, EX2.21</td>
</tr>
<tr class="odd">
<td>2.7 Boxplots (<code>geom_boxplot</code>, IQR rule)</td>
<td>EX2.22, EX2.23, EX2.24, EX2.25, EX2.26</td>
</tr>
<tr class="even">
<td>2.8.1 Barplots (<code>geom_bar</code> vs <code>geom_col</code>)</td>
<td>EX2.27, EX2.29, EX2.30</td>
</tr>
<tr class="odd">
<td>2.8.2 Must avoid pie charts</td>
<td>EX2.31</td>
</tr>
<tr class="even">
<td>2.8.3 Two categorical variables (stacked / dodged / fill)</td>
<td>EX2.28, EX2.32, EX2.33</td>
</tr>
<tr class="odd">
<td>Critical thinking / open exploration</td>
<td>EX2.34, EX2.35, EX2.36, EX2.37, EX2.38, EX2.39</td>
</tr>
<tr class="even">
<td>Extensions</td>
<td>EX2.40, EX2.41, EX2.42, EX2.43, EX2.44, EX2.45, EX2.46, EX2.47, EX2.48, EX2.49</td>
</tr>
</tbody>
</table>
<p><strong>A note on coverage.</strong> Section 2.2 (“Five named graphs”) is a 15-line transition — it lists the geoms covered next and has nothing to assess on its own; the <em>named graphs themselves</em> (Sections 2.3–2.8) carry all the practice.</p>
<p>Difficulty stars on each exercise: ★ warm-up, ★★ standard application, ★★★ critical thinking. Click <em>show question</em> on any callout to reveal the prompt; the solution is always visible underneath.</p>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(olympicAthletes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="setup-and-exploration" class="level3">
<h3 class="anchored" data-anchor-id="setup-and-exploration">Setup and exploration</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.1 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.1 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.1 (★)</strong> Load <code>olympicAthletes</code>, then run <code>glimpse()</code> on each of the three datasets. How many rows and how many columns does each have?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Chapter 2, “Data Visualization”, overview)</em>.</p>
<p><code>olympic_athletes</code> ≈ <strong>314,749 × 15</strong>; <code>medal_table</code> ≈ <strong>273 × 9</strong>; <code>editions</code> ≈ <strong>5 × 14</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(medal_table)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,929
Columns: 11
$ edition_id &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,…
$ games      &lt;chr&gt; "1896 Summer", "1896 Summer", "1896 Summer", "1896 Summer",…
$ year       &lt;int&gt; 1896, 1896, 1896, 1896, 1896, 1896, 1896, 1896, 1896, 1896,…
$ season     &lt;chr&gt; "Summer", "Summer", "Summer", "Summer", "Summer", "Summer",…
$ noc        &lt;chr&gt; "USA", "GRE", "GER", "FRA", "GBR", "HUN", "AUT", "AUS", "DE…
$ country    &lt;chr&gt; "United States", "Greece", "Germany", "France", "Great Brit…
$ gold       &lt;int&gt; 11, 10, 6, 5, 2, 2, 2, 2, 1, 1, 1, 31, 20, 20, 6, 6, 4, 3, …
$ silver     &lt;int&gt; 7, 18, 5, 4, 3, 1, 1, 0, 2, 2, 0, 41, 13, 8, 6, 3, 3, 2, 3,…
$ bronze     &lt;int&gt; 2, 19, 2, 2, 2, 3, 2, 0, 3, 0, 1, 40, 15, 9, 6, 1, 2, 0, 2,…
$ total      &lt;int&gt; 20, 47, 13, 11, 7, 6, 5, 2, 6, 3, 2, 112, 48, 37, 18, 10, 9…
$ notes      &lt;chr&gt; "", "", "", "", "", "", "", "", "", "", "Mixed-NOC team (at…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(editions)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 62
Columns: 15
$ edition_id       &lt;int&gt; 1, 2, 3, 4, 5, 6, 50, 7, 8, 29, 9, 30, 10, 31, 11, 32…
$ games            &lt;chr&gt; "1896 Summer", "1900 Summer", "1904 Summer", "1906 Su…
$ year             &lt;int&gt; 1896, 1900, 1904, 1906, 1908, 1912, 1916, 1920, 1924,…
$ season           &lt;chr&gt; "Summer", "Summer", "Summer", "Summer", "Summer", "Su…
$ city_local_latin &lt;chr&gt; "Athína", "Paris", "St. Louis", "Athína", "London", "…
$ city_english     &lt;chr&gt; "Athens", "Paris", "St. Louis", "Athens", "London", "…
$ country          &lt;chr&gt; "Greece", "France", "United States", "Greece", "Great…
$ opening_ceremony &lt;date&gt; 1896-04-06, NA, 1904-05-14, 1906-04-22, 1908-07-13, …
$ closing_ceremony &lt;date&gt; 1896-04-15, NA, NA, 1906-05-02, 1908-07-25, 1912-07-…
$ participants     &lt;int&gt; 176, 1241, 650, 841, 2024, 2409, NA, 2680, 3255, 312,…
$ nocs             &lt;int&gt; 13, 26, 10, 21, 23, 28, NA, 29, 45, 19, 46, 25, 47, 1…
$ medal_events     &lt;int&gt; 43, 95, 95, 74, 110, 107, NA, 162, 131, 17, 125, 14, …
$ disciplines      &lt;int&gt; 10, 22, 18, 14, 24, 23, NA, 33, 27, 10, 24, 8, 26, 7,…
$ notes            &lt;chr&gt; "", "", "", "Intercalated Games; not officially recog…
$ source           &lt;chr&gt; "https://www.olympedia.org/editions/1", "https://www.…</code></pre>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.2 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.2 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.2 (★)</strong> For each column in <code>olympic_athletes</code>, classify it as <strong>numerical</strong> or <strong>categorical</strong>. There are some that look numerical but behave categorically — name at least one and justify.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Chapter 1, “Identification and measurement variables”)</em>.</p>
<p>Numerical: <code>age</code>, <code>height</code>, <code>weight</code>, <code>year</code>. Categorical: <code>sex</code>, <code>team</code>, <code>noc</code>, <code>games</code>, <code>season</code>, <code>city_english</code>, <code>sport</code>, <code>event</code>, <code>medal</code>. Identifier: <code>id</code>, <code>name</code>. <strong>Year</strong> is interesting — stored as integer, but for grouping/coloring purposes it acts like a small set of categorical levels (every 4 years).</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.3 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.3 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.3 (★)</strong> <code>year</code> stores values like <code>1896</code>, <code>2024</code>. Why is treating <code>year</code> as numerical (continuous x-axis on a linegraph) often more useful than treating it as categorical? When would the categorical interpretation be useful?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Sections 2.4 “Linegraphs” and 2.8 “Barplots”)</em>.</p>
<p>Treating <code>year</code> as numerical preserves the <strong>ordering and spacing</strong> of time, which is what a linegraph needs. Treating it as categorical (factor) can be useful for <em>boxplots</em> or <em>grouped barplots</em> where each Games is its own category to compare side-by-side.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.4 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.4 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.4 (★)</strong> Build the simplest scatterplot you can: <code>weight</code> (y) vs <code>height</code> (x) on <code>olympic_athletes</code>. When the plot renders, R will print a <em>warning</em> like <code>Removed N rows containing missing values (geom_point)</code>. Read the warning and report <code>N</code>. What does that tell you about which athlete-rows have complete bio data — and why might older Games be over-represented in the missing rows?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Chapter 2 overview, exploring the data)</em>.</p>
<p>The plot renders, but you’ll see a warning along the lines of <code>Removed ~70,000 rows containing missing values (geom_point())</code>. That’s the rows where <em>either</em> <code>height</code> or <code>weight</code> is <code>NA</code> — roughly a third of the data set. Bio data wasn’t systematically reported in early-20th-century Games; coverage improved over time but is still incomplete for the most recent Games (athlete privacy and late data ingest). The takeaway: any pattern you see in this scatterplot describes only the <strong>subset of athletes with complete bio data</strong>, which is <em>not</em> a random sample of all Olympians.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.05</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 92382 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="grammar-of-graphics" class="level3">
<h3 class="anchored" data-anchor-id="grammar-of-graphics">Grammar of graphics</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.5 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.5 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.5 (★)</strong> Run the snippet below. Identify the three pieces of the <em>grammar of graphics</em> at play: the <strong>data</strong>, the <strong>aesthetic mappings</strong> (which variable is assigned to which of <code>x</code>, <code>y</code>, and <code>color</code>?), and the <strong>geom</strong>. Bonus: if you wanted to layer individual points on top of the boxes, which kind of <em>layer</em> would you add?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.1 “The grammar of graphics”)</em>.</p>
<ul>
<li><strong>Data</strong>: <code>olympic_athletes</code> (filtered to <code>sport == "Athletics"</code>).</li>
<li><strong>Aesthetic mappings</strong> (the <code>aes()</code> call): <code>x = sex</code>, <code>y = height</code>, <code>color = sex</code> — <code>sex</code> is mapped to <em>two</em> channels (the x-axis position and the box color).</li>
<li><strong>Geom</strong>: <code>geom_boxplot()</code> — one box per level of the x variable.</li>
</ul>
<p><strong>Bonus — layering points on top:</strong> add a <code>geom_jitter()</code> (or <code>geom_point()</code> with horizontal jitter) layer:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sport <span class="sc">==</span> <span class="st">"Athletics"</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> height, <span class="at">color =</span> sex)) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.05</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The grammar’s power is exactly this — the boxplot and jittered points share the <em>same</em> data and aesthetics, so they line up automatically.</p>
<hr>
</section>
<section id="scatterplots" class="level3">
<h3 class="anchored" data-anchor-id="scatterplots">Scatterplots</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.6 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.6 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.6 (★★)</strong> Build a scatterplot of <code>weight</code> (y) vs <code>height</code> (x) for <strong>all athletes</strong>. What overall pattern do you see? Do you see overplotting?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.3 “Scatterplots”)</em>.</p>
<p>A clear positive linear association — taller athletes tend to be heavier. With ~315k points, the cloud is heavily over-plotted near the median.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.7 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.7 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.7 (★★)</strong> Modify your scatterplot to color points by <code>sex</code>. What pattern does coloring reveal that the single-color version hid?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.3.1 “Overplotting”)</em>.</p>
<p>Two overlapping clouds — the female cloud sits below-left of the male cloud (lower height, lower weight on average) but with substantial overlap.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight, <span class="at">color =</span> sex)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.05</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.8 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.8 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.8 (★★)</strong> Set <code>alpha = 0.05</code> on <code>geom_point()</code>. Compare to the un-faded version. Where is the densest cluster?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.3.1 “Overplotting”)</em>.</p>
<p>With <code>alpha = 0.05</code> the densest core (around ~175 cm and ~70 kg) becomes visible. The opaque version hides this peak under a black blob.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.05</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.9 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.9 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.9 (★★)</strong> Filter the data to <code>sport == "Gymnastics"</code> and rebuild the Height vs Weight scatterplot. How does the cloud differ from the all-sport view?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.3 “Scatterplots”)</em>.</p>
<p>The cloud is shifted <em>left and down</em> compared to all-athletes — gymnasts are typically shorter and lighter.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sport <span class="sc">==</span> <span class="st">"Gymnastics"</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight, <span class="at">color =</span> sex)) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.10 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.10 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.10 (★★)</strong> Filter to <code>sport == "Basketball"</code> and rebuild. Compared with gymnastics, where on the (Height, Weight) plane do basketball athletes sit?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.3 “Scatterplots”)</em>.</p>
<p>Basketball players cluster at the <strong>upper-right</strong> — much taller (often 190+ cm) and heavier than gymnasts.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sport <span class="sc">==</span> <span class="st">"Basketball"</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight, <span class="at">color =</span> sex)) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.11 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.11 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.11 (★★)</strong> Add <code>labs()</code> to your favorite of the above plots — title, axis labels in human language, and a caption naming the data source. Why are good labels especially important when sharing plots?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.3 “Scatterplots”, grammar of graphics layers)</em>.</p>
<p>Good labels turn a chart from “data” into a <em>communication artifact</em>. A reader who sees only the image — not your code — needs to know what’s plotted, in what units, and where the data came from.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sport <span class="sc">==</span> <span class="st">"Basketball"</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight, <span class="at">color =</span> sex)) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title    =</span> <span class="st">"Olympic basketball athletes are tall, regardless of sex"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"1896–2026 Summer games"</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"height (cm)"</span>, <span class="at">y =</span> <span class="st">"weight (kg)"</span>, <span class="at">color =</span> <span class="st">"sex"</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: olympicAthletes R package"</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="linegraphs" class="level3">
<h3 class="anchored" data-anchor-id="linegraphs">Linegraphs</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.12 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.12 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.12 (★★)</strong> Using <code>medal_table</code> (which already records <code>gold</code> per Games × NOC), plot <code>gold</code> medals (y) vs <code>year</code> (x) for <strong><code>"USA"</code></strong> as a linegraph. Add points on top of the line with <code>geom_point()</code> to mark each Games.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.4 “Linegraphs”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>medal_table <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(noc <span class="sc">==</span> <span class="st">"USA"</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> gold)) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"games (year)"</span>, <span class="at">y =</span> <span class="st">"Gold medals (USA)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.13 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.13 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.13 (★★)</strong> Using the <code>editions</code> data frame from <code>olympicAthletes</code> (one row per Games, <code>participants</code> already counted), plot <code>participants</code> (y) vs <code>year</code> (x) as a linegraph. Filter to a single <code>season</code> first — combining Summer and Winter would zigzag two different cycles. Has the number of athletes per Games grown over time?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.4 “Linegraphs”)</em>.</p>
<p><code>editions</code> has one row per Games, with <code>participants</code> already counted — perfect for a linegraph. We filter to a single season so the x-axis is a single ordered sequence (Summer and Winter alternate every two years and would zig-zag if mixed).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>editions <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(season <span class="sc">==</span> <span class="st">"Summer"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> participants)) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Participants"</span>, <span class="at">title =</span> <span class="st">"Summer Olympics: athletes per Games over time"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 3 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Participation grows roughly monotonically over the century, with notable dips at the World War years.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.14 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.14 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.14 (★★)</strong> Using <code>editions</code>, plot <code>medal_events</code> (y) vs <code>year</code> (x) as a linegraph, with <code>color = season</code> so Summer and Winter appear as two separate lines on the same axes. Has the number of medal events grown more in one season than the other?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.4 “Linegraphs”, color aesthetic)</em>.</p>
<p>Both Summer and Winter trend upward, but Summer’s growth is much steeper — most of the <em>new</em> medal events over the past 50 years (skateboarding, surfing, climbing, BMX freestyle) have been Summer.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(editions, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> medal_events, <span class="at">color =</span> season)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"medal events"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="histograms" class="level3">
<h3 class="anchored" data-anchor-id="histograms">Histograms</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.15 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.15 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.15 (★★)</strong> Build a histogram of <code>age</code> for all athletes. What’s the rough median? Are there suspicious values (very young / very old)?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.5 “Histograms”)</em>.</p>
<p>Median age sits around <strong>25</strong>. Tails reach into the teens and 50s+ — a few are real (equestrian, shooting) and a few may be data anomalies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"age (years)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.16 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.16 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.16 (★★)</strong> Try <code>bins = 10</code>, then <code>bins = 80</code>. Which gives a more honest view of the age distribution? Why?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.5.1 “Adjusting the bins”)</em>.</p>
<p>With <code>bins = 10</code>, fine structure is washed out. With <code>bins = 80</code>, noise dominates — every integer age gets a spike. Around <code>bins = 30</code> is the sweet spot for this distribution.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.17 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.17 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.17 (★★)</strong> Filter to <code>season == "Winter"</code> and plot a histogram of <code>height</code>. Repeat for <code>season == "Summer"</code>. Which season has taller athletes on average?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.5 “Histograms”)</em>.</p>
<p>Both distributions peak around 175 cm but <strong>Summer</strong> athletes have a slightly heavier upper tail (basketball/volleyball/rowing pull it up).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(season <span class="sc">==</span> <span class="st">"Summer"</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> height)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Summer games — height (cm)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.18 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.18 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.18 (★★)</strong> A peer claims “Olympic athletes are mostly in their 20s.” Use a histogram to support or refute this claim with a one-sentence answer.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.5 “Histograms”)</em>.</p>
<p>The histogram supports the claim — the bulk of the distribution sits between 20 and 30, with the central tendency in the mid-20s.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="facets" class="level3">
<h3 class="anchored" data-anchor-id="facets">Facets</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.19 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.19 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.19 (★★)</strong> Take your Height vs Weight scatterplot from EX2.6 and add <code>facet_wrap(~ sex)</code>. What does faceting reveal that coloring did <em>not</em> (or vice versa)?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.6 “Facets”)</em>.</p>
<p>Faceting separates the two clouds into their own panels — easier for <em>spotting outliers within each group</em>. Coloring keeps both on one set of axes — easier for <em>comparing the two distributions side-by-side</em>. Different jobs.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.05</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> sex)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.20 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.20 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.20 (★★)</strong> Build a faceted histogram of <code>age</code>, one panel per <code>season</code>. How do the two distributions differ?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.6 “Facets”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> season, <span class="at">scales =</span> <span class="st">"free_y"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.21 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.21 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.21 (★★)</strong> Filter <code>olympic_athletes</code> to <code>sport %in% c("Athletics", "Swimming", "Gymnastics", "Basketball", "Wrestling")</code>. Use <code>facet_wrap(~ sport)</code> to show a <code>height</code> vs <code>weight</code> scatterplot for each of those five sports. Which sport’s cluster sits in the <em>upper-right</em> corner (taller and heavier)?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.6 “Facets”)</em>.</p>
<p>Basketball sits up and to the right (tall + heavy), Gymnastics down and to the left (short + light), and the three middle sports cluster around average physiques. Faceting makes the sport-to-sport contrast much sharper than a single overlapping cloud could.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sport <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Athletics"</span>, <span class="st">"Swimming"</span>, <span class="st">"Gymnastics"</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Basketball"</span>, <span class="st">"Wrestling"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> sport)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="boxplots" class="level3">
<h3 class="anchored" data-anchor-id="boxplots">Boxplots</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.22 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.22 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.22 (★★)</strong> Build side-by-side boxplots of <code>age</code> by <code>season</code>. Which season’s athletes skew older?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.7 “Boxplots”)</em>.</p>
<p>Winter Games athletes skew slightly older — sports like curling, biathlon, and bobsleigh keep peak ages later than gymnastics or sprinting.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> season, <span class="at">y =</span> age)) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.23 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.23 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.23 (★★)</strong> Filter <code>olympic_athletes</code> to <code>sport %in% c("Weightlifting", "Cycling Road", "Marathon", "Equestrianism", "Sailing")</code> and build boxplots of <code>weight</code> (not height — height is covered in EX 2.26) for those five sports. Which sport has the <em>largest IQR</em>, and what does that range tell you about athletes in that sport?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.7 “Boxplots”)</em>.</p>
<p><strong>Weightlifting</strong> typically shows the largest IQR — weight classes span featherweight to super-heavyweight, so a single boxplot bundles all of them and looks very spread out. The other four sports each have a narrower physique profile.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sport <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Weightlifting"</span>, <span class="st">"Cycling Road"</span>, <span class="st">"Marathon"</span>,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Equestrianism"</span>, <span class="st">"Sailing"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sport, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">coord_flip</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.24 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.24 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.24 (★★)</strong> A single boxplot for <em>all</em> sports would have hundreds of boxes. Why is filtering to a few sports a <em>better</em> visualization choice than showing them all?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.7 “Boxplots”, chart legibility)</em>.</p>
<p>Visual clutter masks the signal. With 50+ boxes, individual medians are unreadable, axis labels overlap, and the chart conveys “lots of sports” instead of any specific comparison. Selecting a small set lets the reader actually <em>compare</em>.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.25 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.25 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.25 (★★★)</strong> A boxplot of <code>weight</code> for one sport shows many “outlier” dots above the upper whisker. Are these necessarily data errors? Justify in 1–2 sentences.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.7 “Boxplots”, IQR rule)</em>.</p>
<p><strong>No.</strong> Boxplot “outliers” use the <span class="math inline">\(Q_3 + 1.5 \times \text{IQR}\)</span> rule and flag any unusually large value relative to the bulk — but heavyweight sports legitimately produce athletes well above average. They’re statistical outliers, not necessarily errors.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.26 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.26 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.26 (★★)</strong> Build side-by-side boxplots of <code>height</code> for <code>sport %in% c("Athletics", "Gymnastics", "Basketball", "Swimming", "Wrestling")</code>. From the resulting plot, read off (eyeballing is fine): (a) the rough median height for each sport, (b) which sport has the <em>tightest</em> IQR, and (c) which sport’s whiskers extend the furthest above its median.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.7 “Boxplots”)</em>.</p>
<p><em>Approximate readings</em> (your eyeballs may differ):</p>
<ul>
<li><strong>Medians</strong>: Basketball ≈ 195 cm, Swimming ≈ 180 cm, Athletics ≈ 178 cm, Wrestling ≈ 172 cm, Gymnastics ≈ 162 cm.</li>
<li><strong>Tightest IQR</strong>: <strong>Gymnastics</strong> — the box is short; gymnasts are a narrow height range relative to other sports.</li>
<li><strong>Whiskers furthest above the median</strong>: <strong>Basketball</strong> — the upper whisker stretches to ~215 cm because of centers and forwards in the tail.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sport <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Athletics"</span>, <span class="st">"Gymnastics"</span>, <span class="st">"Basketball"</span>,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Swimming"</span>, <span class="st">"Wrestling"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sport, <span class="at">y =</span> height)) <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"height (cm)"</span>, <span class="at">x =</span> <span class="cn">NULL</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="barplots" class="level3">
<h3 class="anchored" data-anchor-id="barplots">Barplots</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.27 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.27 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.27 (★★)</strong> Filter <code>medal_table</code> to <code>games == "2024 Summer"</code>, then build a horizontal bar chart of <code>total</code> per <code>noc</code>. Use <code>geom_col(aes(y = reorder(noc, total)))</code> to sort the bars by descending medal count. Which NOC tops the chart?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.8 “Barplots”, <code>geom_col</code> + <code>reorder</code>)</em>.</p>
<p>The U.S. is typically the top medal-winner at the 2024 Summer Games.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>medal_table <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(games <span class="sc">==</span> <span class="st">"2024 Summer"</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> total, <span class="at">y =</span> <span class="fu">reorder</span>(noc, total))) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Total medals"</span>, <span class="at">y =</span> <span class="cn">NULL</span>, <span class="at">title =</span> <span class="st">"2024 Summer — every NOC's medal total"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Because each row of <code>medal_table</code> already records a single Games × NOC pair, <code>geom_col()</code> (which expects pre-computed bar heights) is the right geom — no counting needed. <code>reorder(noc, total)</code> sorts the bars by descending medal count.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.28 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.28 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.28 (★★)</strong> Use <code>geom_bar()</code> on <code>olympic_athletes</code> to plot athlete-row counts by <code>season</code>, with <code>fill = sex</code>. By default the two <code>sex</code> levels stack within each <code>season</code> bar. Roughly, what’s the male-to-female ratio in each season?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.8 “Barplots”, stacked bars (default position))</em>.</p>
<p>Both seasons skew <strong>male-heavy</strong> historically — Summer is closer to parity (roughly 60/40 male/female across all Games) while Winter is more lopsided. <code>geom_bar()</code> counts rows internally, so adding <code>fill = sex</code> is all it takes to split each season’s bar into two stacked pieces.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> season, <span class="at">fill =</span> sex)) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.29 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-30-contents" aria-controls="callout-30" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.29 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-30" class="callout-30-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.29 (★★)</strong> Filter <code>olympic_athletes</code> to <code>year == 2024 &amp; season == "Summer"</code>. Build a <code>geom_bar()</code> of athlete-rows by <code>medal</code>. The <code>NA</code> bar dominates — why? (Hint — think about what fraction of athletes at any Games win <em>no</em> medal in <em>any</em> event.)</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.8 “Barplots”, <code>geom_bar</code> counts internally)</em>.</p>
<p>The <code>NA</code> bar dwarfs the medal bars because at any single Games, the vast majority of athletes who <em>compete</em> don’t end up on a podium — only the top three per event get a medal, but every roster member of every team gets a row in <code>olympic_athletes</code>. The medal bars themselves should be roughly equal in size (each event awards one gold, one silver, one bronze).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2024</span>, season <span class="sc">==</span> <span class="st">"Summer"</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> medal)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.30 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.30 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.30 (★★)</strong> Use <code>geom_bar()</code> (not <code>geom_col()</code>) on <code>olympic_athletes</code> to show the count of athlete-rows per <code>season</code>. Why is <code>geom_bar()</code> the right choice here, not <code>geom_col()</code>?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.8 “Barplots”, <code>geom_bar()</code> vs `geom_col())</em>.</p>
<p><code>geom_bar()</code> <em>counts rows</em> — exactly what we want here (no pre-tallying needed). <code>geom_col()</code> requires a pre-computed <code>y</code> value.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> season)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.31 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.31 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.31 (★★★)</strong> A pie chart of the top-10-NOC medal totals from EX2.27 would be visually appealing. Give two reasons the chapter argues a barplot is <em>better</em>.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.8 “Must avoid pie charts!”)</em>.</p>
<ol type="1">
<li><strong>Humans judge length more accurately than angle</strong>: differences between similar-sized slices are nearly impossible to perceive. (2) <strong>Sorted bars convey ranking</strong> at a glance, while pie slices need a legend or numeric labels for the same effect.</li>
</ol>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.32 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-33-contents" aria-controls="callout-33" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.32 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-33" class="callout-33-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.32 (★★)</strong> On <code>olympic_athletes</code>, rebuild your EX 2.28 plot but switch from the default <em>stacked</em> bars to side-by-side bars with <code>position = "dodge"</code>. What’s easier to see in the dodged version that was harder in the stacked one?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.8 “Barplots”, dodged bars)</em>.</p>
<p>In the <strong>stacked</strong> version (EX 2.28), male and female totals sit on top of each other within a single bar, so it’s hard to read the absolute count of each separately. <strong>Dodging</strong> puts the male and female bars <em>side by side</em> inside each season, making the per-sex absolute counts directly comparable across the four bars.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> season, <span class="at">fill =</span> sex)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.33 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.33 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.33 (★★)</strong> Take your EX 2.28 stacked barplot of athlete-rows by <code>season</code> filled by <code>sex</code>, and switch the <code>geom_bar()</code> argument to <code>position = "fill"</code>. Now each season’s bar reaches 100 %. Compare the two charts: what new question does the proportional version answer (that the stacked-counts version <em>cannot</em>), and conversely what does the stacked version show that gets hidden when you switch to proportions?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.8 “Barplots”, <code>position = "fill"</code>)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> season, <span class="at">fill =</span> sex)) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>What the proportional version answers</strong> (that the stacked-counts version cannot): <em>what share</em> of each season’s athletes are male vs.&nbsp;female? Both bars now reach 100 %, so the <em>relative balance</em> is directly readable on the y-axis.</p>
<p><strong>What the stacked version showed</strong> (and the proportional version hides): the absolute count of athletes per season — i.e., that Summer has many more athletes than Winter to begin with. After <code>position = "fill"</code>, the two seasons look like equally tall bars, regardless of how many athletes each Games actually had.</p>
<p>Counts answer “how many?”; proportions answer “what share?”. Different questions, different geom configurations.</p>
<hr>
</section>
<section id="critical-thinking-and-open-exploration" class="level3">
<h3 class="anchored" data-anchor-id="critical-thinking-and-open-exploration">Critical thinking and open exploration</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.34 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.34 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.34 (★★★)</strong> Imagine a news outlet posts a chart of “USA’s medal dominance” using a y-axis that starts at 50 (cropping the bar baseline). Explain in 2–3 sentences how the chart misleads viewers, and what a more honest chart would look like.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.8 “Barplots”, chart honesty)</em>.</p>
<p>Cropping the y-axis exaggerates differences — a USA total of 120 vs a peer’s 90 looks like <em>4× as many</em> (70 vs 40 above the cropped origin) instead of the true 1.33×. An honest version starts the y-axis at zero, or uses a non-bar geom (e.g., points + connecting line) where a non-zero baseline is conventionally acceptable.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.35 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-36-contents" aria-controls="callout-36" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.35 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-36" class="callout-36-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.35 (★★★)</strong> Pick any chart you’ve built in this chapter and write a short <em>chart caption</em> (2–3 sentences) suitable for publishing in a news article. The caption should (a) state the <em>finding</em>, (b) identify the <em>data source</em>, and (c) flag one <em>caveat</em> about the data (e.g., missingness, selection, sample size). Compare your caption to the chart’s <code>labs(title = ..., caption = ...)</code> and revise either as needed.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Chapter 2 synthesis — chart-quality thinking)</em>.</p>
<p><em>Answers will vary.</em> Example caption for the EX 2.27 horizontal barplot of 2024 Summer medal totals:</p>
<blockquote class="blockquote">
<p>“<strong>United States led the 2024 Summer medal table</strong> with 126 total medals, followed by China (91) and Great Britain (65). <em>Source:</em> <code>medal_table</code> from the <code>olympicAthletes</code> R package. <em>Caveat:</em> the chart shows <strong>total medals</strong> counted with one row per athlete on every medal-winning team, so team sports (basketball, water polo, relays) contribute multiple rows per podium — the ranking is sensitive to how team medals are tallied.”</p>
</blockquote>
<p>Then revise the chart’s own <code>labs()</code> to include the same <code>title</code>, a <code>caption</code> naming the data source, and an <code>x</code> label like “Total medals (2024 Summer)”. A good chart and a good caption say the same thing in two slightly different ways.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.36 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-37-contents" aria-controls="callout-37" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.36 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-37" class="callout-37-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.36 (★★★)</strong> This chapter introduced the <strong>5 named graphs</strong> (5NG): scatterplot, linegraph, histogram, boxplot, barplot. For each of the five, write <em>one sentence</em> describing a question about Olympic athletes that the geom would be the right tool to answer. (No code required — this is a matching-question-to-geom exercise.) When you’re done, pick <em>one</em> of your five questions and identify which Ch 2 exercise from this chapter most closely resembles it.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Chapter 2 synthesis — the 5 named graphs (5NG))</em>.</p>
<p><em>Answers will vary.</em> Example matchups:</p>
<ul>
<li><strong>Scatterplot</strong> — <em>“Is taller and heavier correlated across Olympic athletes?”</em> (two numerical variables → <code>geom_point</code>; closest to EX 2.6).</li>
<li><strong>Linegraph</strong> — <em>“How has the number of participants per Games changed over time?”</em> (one numerical variable over an ordered axis → <code>geom_line</code>; closest to EX 2.13).</li>
<li><strong>Histogram</strong> — <em>“What’s the typical age of an Olympic competitor, and is there a long tail of older athletes?”</em> (one numerical variable → <code>geom_histogram</code>; closest to EX 2.15).</li>
<li><strong>Boxplot</strong> — <em>“Which sport’s athletes are most consistent in body weight?”</em> (one numerical variable split by a categorical → <code>geom_boxplot</code>; closest to EX 2.23).</li>
<li><strong>Barplot</strong> — <em>“At the 2024 Summer Games, how did medal totals stack up by NOC?”</em> (counts of a categorical variable → <code>geom_bar</code>/<code>geom_col</code>; closest to EX 2.27).</li>
</ul>
<p>The 5NG framework is a quick triage tool: figure out how many numerical/categorical variables your question involves, and the geom usually picks itself.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.37 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-38-contents" aria-controls="callout-38" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.37 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-38" class="callout-38-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.37 (★★★)</strong> Re-run your EX 2.4 scatterplot of <code>weight</code> vs <code>height</code> and read the <code>Removed N rows…</code> warning carefully. Approximately what <em>proportion</em> of athlete-rows have either a missing height or a missing weight? Given that, what conclusion about <em>Olympic athletes</em> should you <strong>not</strong> draw from this scatterplot until you understand <em>why</em> those rows are missing?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Chapter 2 synthesis — reading ggplot warnings)</em>.</p>
<p>The warning text is the data-quality signal: roughly <strong>30–35 %</strong> of athlete-rows have a missing <code>height</code> and/or <code>weight</code>. The right inference is <strong>“the cloud you’re looking at describes athletes whose bio data was recorded”</strong> — <em>not</em> “Olympic athletes in general.” Athletes from early-20th-century Games (where bio data wasn’t systematically reported) and from very recent Games (where privacy policies suppress some entries) are <em>under-represented</em> in the visible scatter. Any claim about “Olympic athletes are X tall and Y heavy” needs that caveat.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.05</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 92382 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.38 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-39-contents" aria-controls="callout-39" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.38 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-39" class="callout-39-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.38 (★★★)</strong> Using <code>editions</code>, build a scatterplot of <code>medal_events</code> (y) vs <code>participants</code> (x), colored by <code>season</code>. Are bigger Games (more athletes) also more medal-rich? Does the pattern look the same for Summer and Winter?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 2.3 “Scatterplots”, color aesthetic)</em>.</p>
<p>More participants generally accompanies more medal events, but <strong>Summer and Winter sit on completely different scales</strong> — Summer Games have ~10× the athletes and ~3× the medal events of Winter Games. Coloring by <code>season</code> shows that the apparent positive correlation in the overall cloud is partly driven by the season split itself: each season’s own cluster has a much weaker internal trend.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(editions, <span class="fu">aes</span>(<span class="at">x =</span> participants, <span class="at">y =</span> medal_events, <span class="at">color =</span> season)) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"participants"</span>, <span class="at">y =</span> <span class="st">"medal events"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.39 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-40-contents" aria-controls="callout-40" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.39 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-40" class="callout-40-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.39 (★★★)</strong> Open exploration: using any of the three datasets, find one pattern that surprises you. Build the <strong>single chart</strong> that communicates it best, and write a one-sentence headline above it.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Chapter 2 — synthesis)</em>.</p>
<p><em>Answers will vary.</em> One example: <strong>medal share is heavily right-skewed</strong> — a small number of NOCs win the bulk of medals each Games.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>medal_table <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(games <span class="sc">==</span> <span class="st">"2024 Summer"</span>) <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total)) <span class="sc">|&gt;</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rank =</span> <span class="fu">row_number</span>()) <span class="sc">|&gt;</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> rank, <span class="at">y =</span> total)) <span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"noc rank"</span>, <span class="at">y =</span> <span class="st">"Total medals"</span>,</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"2024 Summer — long tail of medal distribution"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="extensions" class="level3">
<h3 class="anchored" data-anchor-id="extensions">Extensions</h3>
<div class="callout callout-style-simple callout-note callout-titled" title="About these Extensions">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>About these Extensions
</div>
</div>
<div class="callout-body-container callout-body">
<p>The exercises below <strong>deliberately introduce functions and concepts beyond what this chapter teaches</strong> — log transformations, <code>predict()</code>, new packages, foreshadowing later chapters. They are <em>optional</em>, aimed at readers who want to push further. The main Exercises and Quick checks above stick strictly to what this chapter covers.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.40 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-42-contents" aria-controls="callout-42" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.40 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-42" class="callout-42-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.40 (◆◆)</strong> <strong>Themes.</strong> ggplot’s default look isn’t the only option. Try <code>theme_minimal()</code>, <code>theme_bw()</code>, and <code>theme_classic()</code> on the basketball scatterplot from EX 2.6. Which would you reach for in a <em>printed report</em> vs.&nbsp;a <em>slide deck</em>? Why?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Extension: ggplot themes)</em>.</p>
<p><code>theme_minimal()</code> strips the gray panel background and most gridlines — clean for <strong>printed reports</strong> where heavy ink wastes paper. <code>theme_classic()</code> adds axis lines only (no gridlines, no background) — great for <strong>slide decks</strong> where you want maximum data-ink ratio at low resolution. <code>theme_bw()</code> keeps faint gridlines but drops the gray panel — a good general-purpose default. The default theme (<code>theme_gray</code>) is fine for exploratory work but looks dated in polished output.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.41 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-43-contents" aria-controls="callout-43" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.41 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-43" class="callout-43-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.41 (◆◆)</strong> <strong>Color-blind-safe palettes.</strong> Default ggplot colors look bright but aren’t always distinguishable for readers with color-vision deficiencies. The <code>viridis</code> palette family (<code>scale_color_viridis_d()</code> for discrete, <code>scale_color_viridis_c()</code> for continuous) is designed to be both attractive and perceptually robust. Apply it to a Height-vs-Weight scatter colored by <code>season</code>. How does the visual distinction compare to the default?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Extension: viridis palettes)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight, <span class="at">color =</span> season)) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 92382 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Viridis is <em>perceptually uniform</em> — equal steps in the data correspond to equal perceived steps in color, even for readers with red-green color blindness. The default ggplot palette uses hues chosen to look distinct to readers with typical color vision but can collapse to near-identical grays for some color-vision deficiencies. As a rule of thumb, default to <code>viridis</code> for any chart that will be published or shared widely.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.42 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-44-contents" aria-controls="callout-44" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.42 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-44" class="callout-44-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.42 (◆◆)</strong> <strong>Saving plots to file.</strong> <code>ggsave()</code> saves the <em>last plot</em> (or a named plot object) to disk in your preferred format and dimensions. Save a histogram of <code>age</code> as a 6-inch × 4-inch PNG at 300 DPI. Then save the same plot as a PDF. Which format is better for inclusion in a printed report? In a website? Why?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Extension: ggsave)</em>.</p>
<p><code>ggsave("age_hist.png", p, width = 6, height = 4, dpi = 300)</code> writes a 6 × 4-inch PNG at print resolution.</p>
<ul>
<li><strong>PNG</strong> is a <em>raster</em> format (a grid of pixels). Good for the web (small files, broad browser support) but quality degrades when scaled up beyond its DPI.</li>
<li><strong>PDF / SVG</strong> are <em>vector</em> formats (a list of shapes). They scale arbitrarily without quality loss — essential for printed reports, journal submissions, and posters.</li>
</ul>
<p>Rule of thumb: PDF for print, PNG (or SVG) for web. The same <code>ggsave()</code> call works for both — just change the extension.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.43 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-45-contents" aria-controls="callout-45" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.43 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-45" class="callout-45-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.43 (◆◆)</strong> <strong>Annotating plots with <code>annotate()</code>.</strong> Use <code>annotate("text", ...)</code> and <code>annotate("rect", ...)</code> to draw the reader’s eye to a specific cluster in the Height-vs-Weight scatter — for example, the basketball-center region (≥ 200 cm tall, ≥ 100 kg). Briefly: what’s the difference between <code>annotate()</code> and <code>geom_text()</code> for labeling individual points?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Extension: annotate())</em>.</p>
<p><code>annotate(...)</code> places a <em>single</em> label/shape at fixed coordinates — useful for guiding the reader’s eye to one specific region (a cluster, an outlier, a threshold line). <code>geom_text(aes(label = name))</code>, by contrast, draws <em>one label per data row</em> — useful when every point deserves its own label (small datasets only — anything bigger than ~30 points gets unreadable). For the basketball-centers callout, <code>annotate()</code> is the right tool: one label for the region, not one label per athlete.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.44 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-46-contents" aria-controls="callout-46" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.44 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-46" class="callout-46-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.44 (◆◆)</strong> <strong>Density plots.</strong> A density plot is a smoothed alternative to a histogram — <code>geom_density()</code> instead of <code>geom_histogram()</code>. Build one for <code>age</code>, and compare it to the histogram you built in EX 2.15. When is the density’s smoothing helpful, and when is the histogram’s <em>integer-bin honesty</em> (each spike = real count) more useful?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Extension: density plots)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> age)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 21349 rows containing non-finite outside the scale range
(`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Density’s smoothing is helpful when the data are continuous and bin-edge choices feel arbitrary — it averages over the bin question. The histogram’s per-bin honesty is more useful when ages have <em>integer spikes</em> (e.g., a notable bump at exactly 18 from minimum-age rules) that the smoother would wash away.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.45 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-47-contents" aria-controls="callout-47" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.45 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-47" class="callout-47-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.45 (◆◆)</strong> <strong>Violin plots.</strong> <code>geom_violin()</code> combines a boxplot’s summary with a density’s shape — wide where data is dense, narrow where sparse. Overlay a <code>geom_violin()</code> and a narrow <code>geom_boxplot()</code> for <code>height</code> across three sports. What does the violin show that a boxplot alone hides? (Hint — modality.)</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Extension: violin plots)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sport <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Athletics"</span>, <span class="st">"Swimming"</span>, <span class="st">"Basketball"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sport, <span class="at">y =</span> height)) <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">fill =</span> <span class="st">"lightgray"</span>) <span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 15738 rows containing non-finite outside the scale range
(`stat_ydensity()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 15738 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A boxplot tells you the median and IQR but is <em>blind to modality</em> — a unimodal distribution and a bimodal one with the same median and IQR look identical. The violin’s outline reveals <em>shape</em>: if there are two clusters at different heights (e.g., separate sub-populations of athletes), the violin will be wide at both heights with a narrow waist between them.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.46 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-48-contents" aria-controls="callout-48" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.46 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-48" class="callout-48-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.46 (◆◆◆)</strong> <strong>Nonlinear smoothing with <code>loess</code>.</strong> <code>geom_smooth(method = "loess")</code> draws a locally-fitted curve through the data, no equation required — handy for spotting <em>shape</em> before committing to a model. Add it to your Height-vs-Weight scatter. Where does the curve depart from a straight line? (This previews Chapter 5, which formally introduces <em>linear</em> regression with <code>method = "lm"</code>.)</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Extension: loess smoothing)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.05</span>) <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 92382 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Failed to fit group -1.
Caused by error in `predLoess()`:
! workspace required (74400674057) is too large probably because of setting 'se = TRUE'.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 92382 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The loess curve typically bends <em>upward</em> at high heights — taller athletes are heavier-than-linear (longer levers + thicker bones). A straight line would understate weight at the extremes. Chapter 5’s <code>method = "lm"</code> will fit the best <em>straight</em> line through this cloud, with R² measuring how much of the structure that line captures.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.47 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-49-contents" aria-controls="callout-49" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.47 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-49" class="callout-49-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.47 (◆◆◆)</strong> <strong>Interactive ggplots with <code>plotly::ggplotly()</code>.</strong> A single function call turns any ggplot into an interactive widget — readers can hover for tooltips, zoom, and pan. Try it on a height-vs-weight scatter colored by <code>sport</code>. When is the interactive version genuinely more useful than a static one? When does it just add load time without adding insight?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Extension: plotly::ggplotly)</em>.</p>
<p>Interactive ggplots are most valuable when (a) the reader needs to identify <em>specific</em> points (hover for the athlete name), (b) the chart has too many overlapping points to read statically (zoom to disambiguate), or (c) the chart will live in an HTML report where readers can explore. The cost: every interactive plot bloats the HTML payload with embedded JavaScript and data — fine for one or two key charts, painful for dozens in a single document.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.48 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-50-contents" aria-controls="callout-50" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.48 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-50" class="callout-50-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.48 (◆◆◆)</strong> <strong>Composing multiple plots with <code>patchwork</code>.</strong> The <code>patchwork</code> package lets you arrange ggplots in arbitrary grids using <code>+</code> (side-by-side), <code>/</code> (stacked), and parentheses. Build a 2-on-top, 1-on-bottom layout showing histograms of <code>age</code>, <code>height</code>, and <code>weight</code>. Briefly — why is patchwork a better choice here than building a faceted plot with <code>facet_wrap()</code>?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Extension: patchwork composition)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> age))    <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> height)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(olympic_athletes, <span class="fu">aes</span>(<span class="at">x =</span> weight)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>(p1 <span class="sc">+</span> p2) <span class="sc">/</span> p3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 21349 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 86542 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 90938 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_ex_files/figure-html/02-ex-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>facet_wrap()</code> requires the data to be in <em>long</em> format with a single shared scale — fine when you’re slicing one variable by a group, but here we want to show <em>three different variables</em> on <em>different scales</em>. patchwork lets each plot be entirely independent (different axes, themes, even data sources) while still arranging them in one figure.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX2.49 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-51-contents" aria-controls="callout-51" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX2.49 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-51" class="callout-51-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX2.49 (◆◆◆)</strong> <strong><code>ylim()</code> vs <code>coord_cartesian()</code>.</strong> Both restrict the y-axis range — but <code>ylim()</code> <em>removes</em> points outside the range <em>before</em> statistics like <code>geom_smooth()</code> run, while <code>coord_cartesian(ylim = ...)</code> <em>zooms</em> the view <em>after</em> statistics run. Run the comparison above. Why does the smoother differ between the two panels?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Extension: ylim vs coord_cartesian)</em>.</p>
<p><code>ylim(50, 120)</code> <em>removes</em> the rows with weight outside <code>[50, 120]</code> before any stats run, so <code>geom_smooth()</code> fits to a <em>subset</em> of the data. <code>coord_cartesian(ylim = c(50, 120))</code> keeps all rows in the fit and just <em>zooms the visible window</em> afterward. The smoother in the trimmed version is fit on fewer (and skewed) data; the smoother in the zoomed version reflects the full dataset’s structure. Almost always you want <code>coord_cartesian()</code> — trimming silently changes what your statistics describe.</p>
<hr>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>