<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ex</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="10_ex_files/libs/clipboard/clipboard.min.js"></script>
<script src="10_ex_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="10_ex_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="10_ex_files/libs/quarto-html/popper.min.js"></script>
<script src="10_ex_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="10_ex_files/libs/quarto-html/anchor.min.js"></script>
<link href="10_ex_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="10_ex_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="10_ex_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="10_ex_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="10_ex_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<p>Solutions for the end-of-chapter exercises in <em>Chapter 10 — Inference for Regression</em>. Datasets: <code>olympic_athletes</code> (<code>olympicAthletes</code>) and <code>planets</code> (<code>exoplanets</code>).</p>
<div class="callout callout-style-simple callout-tip callout-titled" title="Section coverage at a glance">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Section coverage at a glance
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><strong>Exercises per section</strong> — count of prompts that touch each book section.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Book section</th>
<th style="text-align: right;"># of exercises</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10.2 Theory-based inference for simple linear regression</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td>10.3 Simulation-based inference for simple linear regression</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td>10.5 Theory-based inference for multiple linear regression</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td>10.6 Simulation-based inference for multiple linear regression</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td>Practical / interpretation (cross-section)</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td>Critical thinking / synthesis</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>
<p><strong>Exercises by subsection</strong> — which prompts target each finer-grained subsection.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Subsection</th>
<th>Exercises</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10.2.3 Confidence intervals for LS estimators</td>
<td>EX10.2</td>
</tr>
<tr class="even">
<td>10.2.4 Hypothesis test for population slope</td>
<td>EX10.3, EX10.4, EX10.30</td>
</tr>
<tr class="odd">
<td>10.2.5 The regression table in R</td>
<td>EX10.1</td>
</tr>
<tr class="even">
<td>10.2.6 Model fit and assumptions (LINE)</td>
<td>EX10.5, EX10.6, EX10.7, EX10.37, EX10.38, EX10.39</td>
</tr>
<tr class="odd">
<td>10.3 Simulation-based — bootstrap CI / permutation test</td>
<td>EX10.8, EX10.9, EX10.10, EX10.11, EX10.12</td>
</tr>
<tr class="even">
<td>10.3.1 Confidence intervals using <code>infer</code></td>
<td>EX10.19</td>
</tr>
<tr class="odd">
<td>10.3.1 Theory- vs simulation-based CIs</td>
<td>EX10.20</td>
</tr>
<tr class="even">
<td>10.5 + LINE diagnostics (cross-cut)</td>
<td>EX10.40, EX10.41, EX10.42</td>
</tr>
<tr class="odd">
<td>10.5 Theory-based for multiple regression</td>
<td>EX10.13, EX10.14, EX10.15, EX10.16</td>
</tr>
<tr class="even">
<td>10.5.3 Confidence intervals for the partial slopes</td>
<td>EX10.21</td>
</tr>
<tr class="odd">
<td>10.6 Simulation-based for multiple regression</td>
<td>EX10.17, EX10.18</td>
</tr>
<tr class="even">
<td>Practical / interpretation (cross-section)</td>
<td>EX10.22, EX10.23, EX10.24, EX10.25</td>
</tr>
<tr class="odd">
<td>Critical thinking / synthesis</td>
<td>EX10.26, EX10.27, EX10.28, EX10.29, EX10.31, EX10.32, EX10.33, EX10.34, EX10.35, EX10.36</td>
</tr>
</tbody>
</table>
<p><strong>A note on coverage.</strong> <em>Sections 10.1 (the simple-LR model) and 10.4 (the multiple-LR model) appear with 0 exercise rows above</em>: they are <strong>conceptual setups</strong> for the inference machinery that follows, and EX10.25 (“What’s <em>the population</em> in regression here?”) plus the practical/interpretation block effectively quizzes those setup ideas.</p>
<p>Difficulty: ★ warm-up · ★★ standard · ★★★ critical thinking.</p>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(infer)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moderndive)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(olympicAthletes)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(exoplanets)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>bball <span class="ot">&lt;-</span> olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sport <span class="sc">==</span> <span class="st">"Basketball"</span>, <span class="sc">!</span><span class="fu">is.na</span>(height), <span class="sc">!</span><span class="fu">is.na</span>(weight))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>m_b <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> height, <span class="at">data =</span> bball)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>planets_lite <span class="ot">&lt;-</span> planets <span class="sc">|&gt;</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(radius_earth), <span class="sc">!</span><span class="fu">is.na</span>(mass_earth), <span class="sc">!</span><span class="fu">is.na</span>(discovery_method)) <span class="sc">|&gt;</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_mass =</span> <span class="fu">log10</span>(mass_earth), <span class="at">log_radius =</span> <span class="fu">log10</span>(radius_earth))</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>top2 <span class="ot">&lt;-</span> planets_lite <span class="sc">|&gt;</span> <span class="fu">count</span>(discovery_method, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(discovery_method)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>pl2 <span class="ot">&lt;-</span> planets_lite <span class="sc">|&gt;</span> <span class="fu">filter</span>(discovery_method <span class="sc">%in%</span> top2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="theory-based-inference-for-simple-regression" class="level3">
<h3 class="anchored" data-anchor-id="theory-based-inference-for-simple-regression">Theory-based inference for simple regression</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.1 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.1 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.1 (★★)</strong> Filter to basketball, fit <code>lm(weight ~ height)</code>, print the regression table. Identify SE, t-statistic, and p-value of the slope.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.5 “The regression table in R”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(m_b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term      estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept  -130.        1.97     -66.0       0  -134.    -126.  
2 height        1.13      0.01     110.        0     1.11     1.15</code></pre>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.2 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.2 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.2 (★★)</strong> Interpret the slope’s <strong>95% CI</strong> in plain English.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.3 “Confidence intervals for the least-squares estimators”)</em>.</p>
<p>We are 95% confident that, for each additional centimeter of height, the <em>population</em> mean Weight of Olympic basketball athletes increases by between [lower] and [upper] kilograms.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.3 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.3 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.3 (★★★)</strong> What’s the <em>null hypothesis</em> the slope’s p-value tests? What’s your conclusion?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.4 “Hypothesis test for population slope”)</em>.</p>
<p><strong><span class="math inline">\(H_0\)</span>: population slope = 0</strong> — i.e., Height has no linear relationship with Weight in the population. Tiny p-value ⇒ reject; basketball Height <em>does</em> predict Weight.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.4 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.4 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.4 (★★★)</strong> Verify: t-statistic = (estimate − 0) / SE.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.4 “Hypothesis test for population slope”, t-statistic)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">get_regression_table</span>(m_b)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>tab</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term      estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept  -130.        1.97     -66.0       0  -134.    -126.  
2 height        1.13      0.01     110.        0     1.11     1.15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>tab<span class="sc">$</span>estimate[<span class="dv">2</span>] <span class="sc">/</span> tab<span class="sc">$</span>std_error[<span class="dv">2</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 112.7</code></pre>
</div>
</div>
<p>The computed ratio matches <code>statistic</code> in the table.</p>
<hr>
</section>
<section id="model-fit-and-assumptions-line" class="level3">
<h3 class="anchored" data-anchor-id="model-fit-and-assumptions-line">Model fit and assumptions (LINE)</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.5 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.5 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.5 (★★)</strong> What four assumptions does <code>lm()</code> inference require? (acronym L.I.N.E.)</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.6 “Model fit and model assumptions”)</em>.</p>
<p><strong>L</strong>inearity of the relationship, <strong>I</strong>ndependence of residuals, <strong>N</strong>ormality of residuals, <strong>E</strong>qual variance (homoscedasticity).</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.6 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.6 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.6 (★★★)</strong> Build a couple of <code>ggplot</code>-based diagnostic plots for <code>m_b</code> — a residual-vs-fitted plot and a histogram of the residuals. For each LINE assumption (Linearity, Independence, Normality, Equal variance), say which plot is most informative for that assumption and what you’d look for.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.6 “Model fit and model assumptions”, residual diagnostics)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>pts <span class="ot">&lt;-</span> <span class="fu">get_regression_points</span>(m_b)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>p_resid_fit <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(pts, <span class="fu">aes</span>(<span class="at">x =</span> weight_hat, <span class="at">y =</span> residual)) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Fitted"</span>, <span class="at">y =</span> <span class="st">"Residual"</span>, <span class="at">title =</span> <span class="st">"Residual vs. fitted"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>p_hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(pts, <span class="fu">aes</span>(<span class="at">x =</span> residual)) <span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residual distribution"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>p_resid_fit <span class="sc">+</span> p_hist</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10_ex_files/figure-html/10-ex-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Which plot probes which assumption:</p>
<ul>
<li><strong>L</strong> (Linearity): residual-vs-fitted — look for a systematic <em>curve</em> in the cloud (trend → fit is missing structure).</li>
<li><strong>I</strong> (Independence): neither plot can detect this directly; it’s a <em>design</em> property of the data. We mention it but don’t diagnose it here.</li>
<li><strong>N</strong> (Normality): residual histogram — look for a roughly bell-shaped, symmetric distribution centered at 0.</li>
<li><strong>E</strong> (Equal variance): residual-vs-fitted — look for a <em>trumpet</em> shape (spread growing or shrinking with the fitted value).</li>
</ul>
<p>For Olympic basketball the diagnostics are mostly clean.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.7 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.7 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.7 (★★★)</strong> “I trust the t-test more than the bootstrap because it has a closed form.” Push back.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.3 “Simulation-based inference for simple linear regression”)</em>.</p>
<p>The t-test relies on assumptions (L.I.N.E.) that may not hold. The bootstrap is <strong>assumption-light</strong> — it just resamples the data — making it more reliable when residuals are skewed, when <span class="math inline">\(n\)</span> is small, or when nonlinear structure violates the t-test’s premises.</p>
<hr>
</section>
<section id="simulation-based-inference-for-simple-regression" class="level3">
<h3 class="anchored" data-anchor-id="simulation-based-inference-for-simple-regression">Simulation-based inference for simple regression</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.8 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.8 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.8 (★★★)</strong> Bootstrap distribution of the slope.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.3.1 “Confidence intervals for the population slope using infer”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">76</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>slope_boot <span class="ot">&lt;-</span> bball <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(weight <span class="sc">~</span> height) <span class="sc">|&gt;</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">500</span>, <span class="at">type =</span> <span class="st">"bootstrap"</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(slope_boot)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10_ex_files/figure-html/10-ex-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.9 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.9 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.9 (★★★)</strong> Bootstrap percentile 95% CI; compare to theory-based.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.3.1 “Confidence intervals for the population slope using infer”, method comparison)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>slope_boot <span class="sc">|&gt;</span> <span class="fu">get_confidence_interval</span>(<span class="at">level =</span> <span class="fl">0.95</span>, <span class="at">type =</span> <span class="st">"percentile"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower_ci upper_ci
     &lt;dbl&gt;    &lt;dbl&gt;
1     1.10     1.15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(m_b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term      estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept  -130.        1.97     -66.0       0  -134.    -126.  
2 height        1.13      0.01     110.        0     1.11     1.15</code></pre>
</div>
</div>
<p>The bootstrap CI matches the theory-based CI very closely (large <span class="math inline">\(n\)</span>, well-behaved residuals).</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.10 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.10 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.10 (★★★)</strong> Permutation test of <span class="math inline">\(H_0\)</span>: slope = 0.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.3.2 “Hypothesis test for population slope using infer”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">76</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>null_slope <span class="ot">&lt;-</span> bball <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(weight <span class="sc">~</span> height) <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">"independence"</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">500</span>, <span class="at">type =</span> <span class="st">"permute"</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>obs_slope <span class="ot">&lt;-</span> bball <span class="sc">|&gt;</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(weight <span class="sc">~</span> height) <span class="sc">|&gt;</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="fu">get_p_value</span>(null_slope, <span class="at">obs_stat =</span> obs_slope, <span class="at">direction =</span> <span class="st">"two-sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Please be cautious in reporting a p-value of 0. This result is an approximation
based on the number of `reps` chosen in the `generate()` step.
ℹ See `get_p_value()` (`?infer::get_p_value()`) for more information.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1       0</code></pre>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.11 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.11 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.11 (★★★)</strong> Visualize the null + p-value shading.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.3.2 “Hypothesis test for population slope using infer”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(null_slope) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_p_value</span>(<span class="at">obs_stat =</span> obs_slope, <span class="at">direction =</span> <span class="st">"two-sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10_ex_files/figure-html/10-ex-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.12 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.12 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.12 (★★★)</strong> Why do simulation-based and theory-based p-values agree here?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.3 “Simulation-based inference for simple linear regression”)</em>.</p>
<p>With <span class="math inline">\(n\)</span> in the thousands and reasonably normal residuals, both procedures converge on the same answer — the CLT applies to the sampling distribution of the slope estimator.</p>
<hr>
</section>
<section id="theory-based-inference-for-multiple-regression" class="level3">
<h3 class="anchored" data-anchor-id="theory-based-inference-for-multiple-regression">Theory-based inference for multiple regression</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.13 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.13 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.13 (★★★)</strong> Build <code>pl2</code>, fit parallel-slopes, print table.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.5 “Theory-based inference for multiple linear regression”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>m_par <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_earth <span class="sc">~</span> radius_earth <span class="sc">+</span> discovery_method, <span class="at">data =</span> pl2)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(m_par)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term                    estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;                      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept                  389.      32.4       12.0       0    326.     453. 
2 radius_earth                62.1      2.30      27.0       0     57.6     66.6
3 discovery_method-Trans…   -535.      29.0      -18.4       0   -592.    -478. </code></pre>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.14 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.14 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.14 (★★★)</strong> Interpret the 95% CI for <code>radius_earth</code>.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.5.3 “Confidence intervals”, multiple-regression CIs)</em>.</p>
<p>Holding discovery method fixed, a one-Earth-radius increase in <code>radius_earth</code> is associated with a slope-sized increase in <code>mass_earth</code>, with the 95 % CI giving the plausible range for that slope. The CI is narrow when <span class="math inline">\(n\)</span> is large; if it excludes zero, the <em>direction</em> of the association is well-supported by the data.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.15 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.15 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.15 (★★★)</strong> What does the p-value for the discovery-method coefficient test?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.5.4 “Hypothesis test for a single coefficient”)</em>.</p>
<p><span class="math inline">\(H_0\)</span>: the difference between the non-baseline method and the baseline method, <em>holding radius fixed</em>, is 0. Equivalently: parallel slopes share a common intercept.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.16 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.16 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.16 (★★★)</strong> Fit the interaction model; what does the interaction’s p-value tell you?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.5.4 “Hypothesis test for a single coefficient”, interactions)</em>.</p>
<p>Tests whether the slope on <code>radius_earth</code> <em>differs</em> between the two methods. A small p-value means slopes really do differ — the interaction is needed.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>m_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_earth <span class="sc">~</span> radius_earth <span class="sc">*</span> discovery_method, <span class="at">data =</span> pl2)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(m_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  term                    estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;                      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept                 -188.      52.4      -3.59   0      -291.      -85.4
2 radius_earth               121.       4.83     25.1    0       112.      131. 
3 discovery_method-Trans…    114.      54.8       2.08   0.038     6.54    221. 
4 radius_earth:discovery…    -75.8      5.46    -13.9    0       -86.5     -65.1</code></pre>
</div>
</div>
<hr>
</section>
<section id="simulation-based-inference-for-multiple-regression" class="level3">
<h3 class="anchored" data-anchor-id="simulation-based-inference-for-multiple-regression">Simulation-based inference for multiple regression</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.17 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.17 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.17 (★★★)</strong> Bootstrap CI for <code>radius_earth</code> coefficient; compare to theory.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.6.1 “Confidence intervals for the partial slopes using infer”)</em>.</p>
<p>With multi-predictor models, easiest path is to extract coefficients per bootstrap replicate via <code>tidy()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">76</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>boot_radius <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">500</span>, {</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> pl2 <span class="sc">|&gt;</span> <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="fu">nrow</span>(pl2), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(<span class="fu">lm</span>(mass_earth <span class="sc">~</span> radius_earth <span class="sc">+</span> discovery_method, <span class="at">data =</span> s))[<span class="st">"radius_earth"</span>]</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(boot_radius, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    2.5%    97.5% 
57.57012 67.05254 </code></pre>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.18 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.18 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.18 (★★★)</strong> <em>Simulation-based inference for a partial slope.</em> Take the parallel-slopes model <code>m_par</code> from EX10.13. Bootstrap the <strong>partial slope on <code>radius_earth</code></strong> by resampling <code>pl2</code> with replacement (≥ 500 reps), refitting on each resample, and pulling out the <code>radius_earth</code> coefficient. (a) Plot the bootstrap distribution. (b) Read off the <strong>95% percentile CI</strong> and compare it to the theory-based CI from EX10.14. (c) Under what condition would you <em>expect</em> the simulation-based CI to disagree noticeably with the theory-based one?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.6 “Simulation-based Inference for multiple linear regression”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">76</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Bootstrap the partial slope on radius_earth</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>n_reps <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>boot_slopes <span class="ot">&lt;-</span> <span class="fu">replicate</span>(n_reps, {</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(pl2)), <span class="fu">nrow</span>(pl2), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  m_b <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_earth <span class="sc">~</span> radius_earth <span class="sc">+</span> discovery_method, <span class="at">data =</span> pl2[idx, ])</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(m_b)[<span class="st">"radius_earth"</span>]</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">slope =</span> boot_slopes), <span class="fu">aes</span>(<span class="at">x =</span> slope)) <span class="sc">+</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Bootstrap partial slope (radius_earth)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10_ex_files/figure-html/10-ex-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) 95% percentile CI</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>boot_ci <span class="ot">&lt;-</span> <span class="fu">quantile</span>(boot_slopes, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>boot_ci</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    2.5%    97.5% 
57.57012 67.05254 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare with theory-based CI from EX10.14</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>m_par <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_earth <span class="sc">~</span> radius_earth <span class="sc">+</span> discovery_method, <span class="at">data =</span> pl2)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(m_par)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term                    estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;                      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept                  389.      32.4       12.0       0    326.     453. 
2 radius_earth                62.1      2.30      27.0       0     57.6     66.6
3 discovery_method-Trans…   -535.      29.0      -18.4       0   -592.    -478. </code></pre>
</div>
</div>
<p><strong>(b) Comparison.</strong> The bootstrap percentile CI and the theory-based CI on <code>radius_earth</code> should overlap heavily — both centered on the OLS partial slope, both about the same width.</p>
<p><strong>(c) When would they disagree?</strong> The theory-based CI assumes the four LINE conditions hold (Linearity, Independence, Normality of residuals, Equal variance). The bootstrap CI relaxes the <strong>Normality</strong> and <strong>Equal-variance</strong> assumptions — it directly resamples the joint <span class="math inline">\((x, y)\)</span> distribution. So you’d expect them to disagree when:</p>
<ol type="1">
<li><strong>Residuals are heavy-tailed</strong> (e.g., a few extreme outliers) — the theory CI under-states uncertainty; the bootstrap captures it.</li>
<li><strong>Heteroscedasticity is strong</strong> — variance grows with the predictor; theory’s “homoscedastic σ̂” assumption gets the SE wrong.</li>
<li><strong>Sample is small</strong> — the t-distribution approximation degrades; the bootstrap, being non-parametric, fares better.</li>
</ol>
<p>For <em>well-behaved</em> multi-thousand-row datasets (which this is), the two answers are usually within a few percent of each other — the bootstrap is <em>insurance</em> for the cases where theory’s assumptions wobble.</p>
<hr>
</section>
<section id="visualizing-slope-uncertainty-bootstrap-distribution" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-slope-uncertainty-bootstrap-distribution">Visualizing slope uncertainty (bootstrap distribution)</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.19 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.19 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.19 (★★★)</strong> Take the bootstrap slope distribution <code>slope_boot</code> from EX 10.8 and compute its 95 % percentile CI with <code>get_confidence_interval(level = 0.95, type = "percentile")</code>. Then re-plot <code>visualize(slope_boot)</code> and use <code>shade_confidence_interval(endpoints = ...)</code> (passing the lower/upper bounds you just computed) to mark the CI on the histogram.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.3.1 “Confidence intervals using infer” — visualizing the CI)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">76</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>slope_boot <span class="ot">&lt;-</span> bball <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(weight <span class="sc">~</span> height) <span class="sc">|&gt;</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">500</span>, <span class="at">type =</span> <span class="st">"bootstrap"</span>) <span class="sc">|&gt;</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> slope_boot <span class="sc">|&gt;</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_confidence_interval</span>(<span class="at">level =</span> <span class="fl">0.95</span>, <span class="at">type =</span> <span class="st">"percentile"</span>)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>ci</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower_ci upper_ci
     &lt;dbl&gt;    &lt;dbl&gt;
1     1.10     1.15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(slope_boot) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_confidence_interval</span>(<span class="at">endpoints =</span> ci)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10_ex_files/figure-html/10-ex-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The shaded band marks the middle 95 % of bootstrap slopes — the range of slope values consistent with the observed data.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.20 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.20 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.20 (★★★)</strong> Compare two ways of estimating a 95 % CI for the slope of <code>lm(weight ~ height, data = bball)</code>: (a) bootstrap percentile via <code>infer::get_confidence_interval()</code>, and (b) theory-based via <code>get_regression_table(m_b)</code> (the <code>lower_ci</code> / <code>upper_ci</code> columns). Do they agree closely? Briefly, <em>when</em> would you expect the two to disagree?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.3.1 “Theory- vs simulation-based CIs”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">76</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>slope_boot <span class="ot">&lt;-</span> bball <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(weight <span class="sc">~</span> height) <span class="sc">|&gt;</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">500</span>, <span class="at">type =</span> <span class="st">"bootstrap"</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>bootstrap_ci <span class="ot">&lt;-</span> slope_boot <span class="sc">|&gt;</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_confidence_interval</span>(<span class="at">level =</span> <span class="fl">0.95</span>, <span class="at">type =</span> <span class="st">"percentile"</span>)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>theory_ci <span class="ot">&lt;-</span> <span class="fu">get_regression_table</span>(m_b) <span class="sc">|&gt;</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"height"</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lower_ci, upper_ci)</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(<span class="at">bootstrap =</span> bootstrap_ci, <span class="at">theory =</span> theory_ci)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$bootstrap
# A tibble: 1 × 2
  lower_ci upper_ci
     &lt;dbl&gt;    &lt;dbl&gt;
1     1.10     1.15

$theory
# A tibble: 1 × 2
  lower_ci upper_ci
     &lt;dbl&gt;    &lt;dbl&gt;
1     1.11     1.15</code></pre>
</div>
</div>
<p>With <span class="math inline">\(n\)</span> in the thousands and roughly LINE-respecting residuals, the two CIs agree closely. They can drift apart when residuals are heavily skewed, when <span class="math inline">\(n\)</span> is small, or when equal-variance is badly violated — in those cases the bootstrap’s assumption-light approach is the more honest choice.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.21 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.21 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.21 (★★★)</strong> For the parallel-slopes model <code>m_par</code> from EX 10.13, pull <code>get_regression_table(m_par)</code> and report the <strong>theory-based 95 % CI</strong> for the <code>radius_earth</code> slope (the <code>lower_ci</code> / <code>upper_ci</code> columns of the relevant row). Does the CI exclude zero? In one sentence, what does that tell you about whether <code>radius_earth</code> is a useful predictor of <code>mass_earth</code> <em>after holding <code>discovery_method</code> constant</em>?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.5.3 “Confidence intervals for the partial slopes”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(m_par) <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"radius_earth"</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate, lower_ci, upper_ci)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  term         estimate lower_ci upper_ci
  &lt;chr&gt;           &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 radius_earth     62.1     57.6     66.6</code></pre>
</div>
</div>
<p>If the 95 % CI for the <code>radius_earth</code> partial slope <strong>excludes zero</strong>, the data clearly support the conclusion that — <em>holding <code>discovery_method</code> constant</em> — mass increases with radius. If it <em>includes</em> zero, the data are consistent with no partial effect of radius on mass once detection method is accounted for.</p>
<hr>
</section>
<section id="practical-questions" class="level3">
<h3 class="anchored" data-anchor-id="practical-questions">Practical questions</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.22 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.22 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.22 (★★★)</strong> Test <span class="math inline">\(H_0\)</span>: slope = 0 in <code>lm(height ~ year, data = bball)</code>.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.4 “Hypothesis test for population slope”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(<span class="fu">lm</span>(height <span class="sc">~</span> year, <span class="at">data =</span> bball))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term      estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept  101.        19.6       5.16       0   62.7    140.   
2 year         0.045      0.01      4.59       0    0.026    0.065</code></pre>
</div>
</div>
<p>A small p-value confirms heights have grown over time in basketball.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.23 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.23 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.23 (★★★)</strong> Reader concludes “Olympic basketball trains taller players.” Refute.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 5.3.1 “Correlation is not necessarily causation”)</em>.</p>
<p>Same as Ch 5: the slope reflects <strong>selection</strong> (the Olympics has progressively recruited taller athletes due to NBA pipeline, rule changes), not biology. Inference doesn’t establish causation; only experiments and randomization do.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.24 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.24 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.24 (★★★)</strong> Repeat EX10.22 for gymnastics. Compare.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.4 “Hypothesis test for population slope”)</em>.</p>
<p>Gymnastics likely has a <em>negative</em> slope (modern gymnasts are shorter than mid-century ones, especially female).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>gym <span class="ot">&lt;-</span> olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sport <span class="sc">==</span> <span class="st">"Gymnastics"</span>, <span class="sc">!</span><span class="fu">is.na</span>(height))</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(<span class="fu">lm</span>(height <span class="sc">~</span> year, <span class="at">data =</span> gym))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term      estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept  280.        5.38       52.0       0  269.     291.   
2 year        -0.059     0.003     -21.7       0   -0.064   -0.054</code></pre>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.25 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.25 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.25 (★★★)</strong> What’s “the population” in regression here?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.1 “The simple linear regression model”, scope of inference)</em>.</p>
<p>The “population” is implicitly <strong>all Olympic basketball athletes</strong>, past and future, who <em>could</em> be in this dataset under the same selection process. Inference applies to that population — <em>not</em> to the general human population. This is why CIs from Olympic data tell you about Olympic athletes, not basketball players in general.</p>
<hr>
</section>
<section id="critical-thinking-and-synthesis" class="level3">
<h3 class="anchored" data-anchor-id="critical-thinking-and-synthesis">Critical thinking and synthesis</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.26 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.26 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.26 (★★★)</strong> With <span class="math inline">\(n \approx 1000\)</span> tiny p-values are easy. Does that mean every effect is meaningful?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.5.4 “Hypothesis test for a single coefficient”, practical vs statistical)</em>.</p>
<p><strong>No.</strong> With <span class="math inline">\(n \approx 1000\)</span>, even effects measured in fractions of a kilogram or millimeters become statistically significant. Always check the <strong>estimate’s magnitude</strong> in domain units before celebrating.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.27 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.27 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.27 (★★★)</strong> Why does removing <code>sport</code> change the <code>sex</code> coefficient on Height?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.5.2 “Model dependency of estimators”, omitted-variable bias)</em>.</p>
<p><strong>Sport</strong> is correlated with both Sex (uneven gender ratios across sports) and Height (sport-specific selection on height). Omitting it makes the Sex coefficient absorb that confounding — coefficients are <em>not invariant</em> to which controls are included.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.28 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.28 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.28 (★★★)</strong> Demonstrate this for two specific sports.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.5.2 “Model dependency of estimators”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>two_sports <span class="ot">&lt;-</span> olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sport <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Athletics"</span>, <span class="st">"Swimming"</span>),</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(height))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(<span class="fu">lm</span>(height <span class="sc">~</span> sex, <span class="at">data =</span> two_sports))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term      estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept    170.      0.055     3091.       0    170.     170. 
2 sex-M         11.0     0.07       157.       0     10.9     11.2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(<span class="fu">lm</span>(height <span class="sc">~</span> sex <span class="sc">+</span> sport, <span class="at">data =</span> two_sports))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term           estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept        169.       0.062    2737.        0   169.     169.  
2 sex-M             11.4      0.069     166.        0    11.3     11.6 
3 sport-Swimming     3.69     0.069      53.3       0     3.55     3.83</code></pre>
</div>
</div>
<p>The <code>SexM</code> coefficient typically <em>changes</em> once <code>sport</code> is added — the per-sport male-female gap differs from the pooled gap.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.29 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-30-contents" aria-controls="callout-30" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.29 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-30" class="callout-30-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.29 (★★★)</strong> CI widths at <span class="math inline">\(n \in \{30, 100, \text{full}\}\)</span>.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.3 “Confidence intervals for the least-squares estimators”)</em>.</p>
<p>Width shrinks as <span class="math inline">\(\sqrt{n}\)</span> grows.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">76</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>ci_at_n <span class="ot">&lt;-</span> <span class="cf">function</span>(nn) {</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> <span class="cf">if</span> (nn <span class="sc">==</span> <span class="st">"full"</span>) bball <span class="cf">else</span> <span class="fu">slice_sample</span>(bball, <span class="at">n =</span> <span class="fu">as.integer</span>(nn))</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  tab <span class="ot">&lt;-</span> <span class="fu">get_regression_table</span>(<span class="fu">lm</span>(weight <span class="sc">~</span> height, <span class="at">data =</span> s))</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  tab <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"height"</span>) <span class="sc">|&gt;</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">transmute</span>(lower_ci, upper_ci, <span class="at">n =</span> nn)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">ci_at_n</span>(<span class="st">"30"</span>), <span class="fu">ci_at_n</span>(<span class="st">"100"</span>), <span class="fu">ci_at_n</span>(<span class="st">"full"</span>))</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>out</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  lower_ci upper_ci n    
     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;
1    0.909     1.30 30   
2    1.06      1.32 100  
3    1.11      1.15 full </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(out, <span class="fu">aes</span>(<span class="at">y =</span> n, <span class="at">xmin =</span> lower_ci, <span class="at">xmax =</span> upper_ci)) <span class="sc">+</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="at">height =</span> <span class="fl">0.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `geom_errorbarh()` was deprecated in ggplot2 4.0.0.
ℹ Please use the `orientation` argument of `geom_errorbar()` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`height` was translated to `width`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10_ex_files/figure-html/10-ex-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.30 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.30 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.30 (★★★)</strong> For <code>m_b</code> (the basketball weight-vs-height model), extract the slope’s <strong>t-statistic</strong> and <strong>p-value</strong> from <code>get_regression_table(m_b)</code> (the <code>statistic</code> and <code>p_value</code> columns). In one sentence each, what is the t-statistic measuring, and what null hypothesis is the p-value testing?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.4 “Hypothesis test for population slope”)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(m_b) <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"height"</span>) <span class="sc">|&gt;</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate, std_error, statistic, p_value)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  term   estimate std_error statistic p_value
  &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 height     1.13      0.01      110.       0</code></pre>
</div>
</div>
<p>The <strong>t-statistic</strong> is <code>estimate / std_error</code> — how many standard errors away from zero the observed slope sits. The <strong>p-value</strong> is the probability of seeing a slope this far from zero (in either direction) <em>if the true population slope were zero</em> — i.e., it tests <span class="math inline">\(H_0: \beta_1 = 0\)</span>. A tiny p-value means the observed slope is implausibly far from zero under <span class="math inline">\(H_0\)</span>, so we reject the null.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.31 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.31 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.31 (★★★)</strong> Section 10.5.4 lets you read a separate p-value for <em>each</em> coefficient in a multi-predictor model. For <code>m_par</code> (EX 10.13), suppose its <code>radius_earth</code> coefficient has a tiny p-value, while the <code>discovery_method</code> offset has a large p-value. In plain English, what does the <em>combination</em> of those two p-values tell you about each predictor’s evidence-supported role in the model?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.5.4 “Hypothesis test for a single coefficient”)</em>.</p>
<p>A tiny p-value on <code>radius_earth</code> means the <em>partial</em> relationship between radius and mass (holding detection method fixed) is well-supported by the data — radius adds information <em>beyond</em> what method alone tells you. A large p-value on the <code>discovery_method</code> offset means the data don’t clearly support a vertical-shift difference between methods <em>once radius is already accounted for</em>. So the combined message is: radius does most of the predictive work; detection method, conditional on radius, doesn’t move mass much.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.32 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-33-contents" aria-controls="callout-33" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.32 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-33" class="callout-33-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.32 (★★★)</strong> On <code>pl2</code>, fit two simple-LR models: (a) <code>lm(mass_earth ~ radius_earth)</code> (no <code>discovery_method</code>), and (b) <code>lm(mass_earth ~ radius_earth + discovery_method)</code> (the parallel-slopes spec). Read the <code>radius_earth</code> slope from each. Did the slope move much when you added <code>discovery_method</code> as a control? If so, what does that tell you about how <code>discovery_method</code> and <code>radius_earth</code> are related as predictors?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Chapter 10 — synthesis, confounding via omitted variables)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>m_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_earth <span class="sc">~</span> radius_earth, <span class="at">data =</span> pl2)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>m_with   <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_earth <span class="sc">~</span> radius_earth <span class="sc">+</span> discovery_method, <span class="at">data =</span> pl2)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(<span class="at">simple  =</span> <span class="fu">get_regression_table</span>(m_simple) <span class="sc">|&gt;</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>               <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"radius_earth"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(estimate),</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">with_dm =</span> <span class="fu">get_regression_table</span>(m_with)   <span class="sc">|&gt;</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>               <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"radius_earth"</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(estimate))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$simple
[1] 80.429

$with_dm
[1] 62.084</code></pre>
</div>
</div>
<p>If the radius slope moves <em>a lot</em> when <code>discovery_method</code> is added, that’s a signal that detection method is correlated with radius (e.g., one method preferentially finds large planets while the other finds small ones). The simple-LR slope mixed in that confounded variation; the multi-predictor slope isolates the <em>partial</em> effect of radius after method is held fixed. That’s the same omitted-variable lesson EX 10.27 made on <code>bball</code>.</p>
<p>The slopes can differ; if they have opposite signs and the pooled has the wrong direction, that <em>would</em> be Simpson’s paradox.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.33 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.33 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.33 (★★★)</strong> R² = 0.95 but diagnostics show curvature — trust the inference?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.6 “Model fit and model assumptions”)</em>.</p>
<p><strong>No.</strong> The high R² doesn’t validate the <em>model form</em>. Curvature in residuals violates linearity, biasing inference (CIs/SEs misstate uncertainty) and producing predictions that systematically err in different parts of the X range.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.34 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.34 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.34 (★★★)</strong> CI for slope is <code>(0.001, 0.005)</code>. Above 0 but tiny — takeaway?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.3 “Confidence intervals for the least-squares estimators”, practical significance)</em>.</p>
<p>The slope is <em>statistically</em> different from 0 (CI excludes 0), but <strong>practically</strong> tiny — for any X-range you care about, the predicted Y barely moves. Don’t write a press release.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.35 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-36-contents" aria-controls="callout-36" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.35 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-36" class="callout-36-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.35 (★★★)</strong> Open exploration: pick a numerical pair, fit and run inference.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Chapter 10 — synthesis)</em>.</p>
<p><em>Answers vary.</em> Example: <code>weight ~ height</code> for swimming — strong positive slope, narrow 95% CI, p ≈ 0.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>swim <span class="ot">&lt;-</span> olympic_athletes <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sport <span class="sc">==</span> <span class="st">"Swimming"</span>, <span class="sc">!</span><span class="fu">is.na</span>(height), <span class="sc">!</span><span class="fu">is.na</span>(weight))</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(<span class="fu">lm</span>(weight <span class="sc">~</span> height, <span class="at">data =</span> swim))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term      estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept -106.        0.733     -144.       0 -107.    -104.   
2 height       0.987     0.004      241.       0    0.979    0.995</code></pre>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.36 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-37-contents" aria-controls="callout-37" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.36 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-37" class="callout-37-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.36 (★★★)</strong> Build a multiple regression on <code>planets</code> predicting <code>eq_temp_k</code> from ≥2 predictors and write a 2–3 sentence summary of <em>robustly supported</em> findings.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Chapter 10 — synthesis)</em>.</p>
<p><em>Answers vary.</em> Robustly supported: (i) insolation is a strong, statistically significant predictor of equilibrium temperature; (ii) host star temperature has a smaller but significant additional effect; (iii) selection-bias caveats apply — these conclusions describe the <em>catalog</em>, not all exoplanets.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>planets_temp <span class="ot">&lt;-</span> planets <span class="sc">|&gt;</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(eq_temp_k), <span class="sc">!</span><span class="fu">is.na</span>(star_temp_k), <span class="sc">!</span><span class="fu">is.na</span>(insolation_earth)) <span class="sc">|&gt;</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">insolation_earth =</span> insolation_earth)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(<span class="fu">lm</span>(eq_temp_k <span class="sc">~</span> insolation_earth <span class="sc">+</span> star_temp_k, <span class="at">data =</span> planets_temp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term             estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept         -91.2      34.8       -2.62   0.009 -159.     -23.0  
2 insolation_earth    0.175     0.004     42.4    0        0.167    0.183
3 star_temp_k         0.173     0.006     26.7    0        0.16     0.185</code></pre>
</div>
</div>
<hr>
</section>
<section id="residual-diagnostics-in-practice-deferred-from-chs-56" class="level3">
<h3 class="anchored" data-anchor-id="residual-diagnostics-in-practice-deferred-from-chs-56">Residual diagnostics in practice (deferred from Chs 5–6)</h3>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.37 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-38-contents" aria-controls="callout-38" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.37 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-38" class="callout-38-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.37 (★★★)</strong> <em>Carried over from Chapter 5 — the model itself is simple-LR material, but the residual-vs-fitted </em>diagnostic* requires the LINE assumptions from § 10.2.6.*</p>
<p>Plot residuals against fitted values for <code>m_b</code> (the simple-LR <code>lm(weight ~ height, data = bball)</code> fit at the top of this chapter). Do you see any obvious pattern (curvature → linearity violation, fan-shape → equal-variance violation) that would suggest mis-specification?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.6 “Model fit and assumptions (LINE)”, residual-vs-fitted plot)</em>.</p>
<p>Look for trumpet shapes (Equal-variance violation) or systematic curvature (Linearity violation). The basketball data is mostly clean; modest fan-out is normal at the high-weight tail.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_points</span>(m_b) <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> weight_hat, <span class="at">y =</span> residual)) <span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Fitted"</span>, <span class="at">y =</span> <span class="st">"Residual"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10_ex_files/figure-html/10-ex-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.38 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-39-contents" aria-controls="callout-39" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.38 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-39" class="callout-39-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.38 (★★★)</strong> <em>Carried over from Chapter 5 — the residuals come from a Ch 5 simple-LR model, but interpreting their </em>distribution* belongs with LINE in § 10.2.6.*</p>
<p>Build a histogram of residuals from <code>m_b</code>. Are they roughly symmetric and centered at zero? Which LINE assumption does this most directly probe?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.6 “Model fit and assumptions (LINE)”, normality of residuals)</em>.</p>
<p>Roughly bell-shaped and centered at 0 — the Normality assumption of LINE is reasonable here.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_points</span>(m_b) <span class="sc">|&gt;</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> residual)) <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10_ex_files/figure-html/10-ex-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.39 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-40-contents" aria-controls="callout-40" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.39 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-40" class="callout-40-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.39 (★★★)</strong> <em>Carried over from Chapter 5 — same Ch 5 model, but checking the Equal-variance assumption belongs with the LINE diagnostics from § 10.2.6.</em></p>
<p>Plot residuals from <code>m_b</code> vs <code>height</code> (the predictor). Does the residual spread <em>grow</em> with <code>height</code> (a violation of the <strong>E</strong>qual-variance condition in LINE)? What does that imply about trusting the theory-based slope CI?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.6 “Model fit and assumptions (LINE)”, equal-variance check)</em>.</p>
<p>Some fan-out at higher heights is visible — not extreme, but enough to note. That’s a mild Equal-variance violation: the <strong>theory-based</strong> slope CI assumes constant residual variance, so a noticeable fan should make you reach for the simulation-based (bootstrap) CI from § 10.3 instead, which doesn’t depend on equal variance.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_points</span>(m_b) <span class="sc">|&gt;</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> residual)) <span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10_ex_files/figure-html/10-ex-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.40 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-41-contents" aria-controls="callout-41" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.40 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-41" class="callout-41-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.40 (★★★)</strong> <em>Carried over from Chapter 6 — fitting an interaction model is Ch 6 material, but interpreting per-group residual patterns belongs with the LINE diagnostics in § 10.2.6.</em></p>
<p>From <code>m_int</code>, pull residuals with <code>get_regression_points()</code>. (a) Plot residuals vs fitted values <em>colored by</em> <code>discovery_method</code> — does the residual cloud look the same for both methods? (b) For each <code>discovery_method</code>, compute the mean residual; both should be ≈ 0 by construction. Verify, and explain in one sentence <em>why</em> the means are mathematically forced to be ≈ 0.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.6 “Model fit and assumptions (LINE)” applied to the interaction model from Ch 6)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>pts_int <span class="ot">&lt;-</span> <span class="fu">get_regression_points</span>(m_int)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (a) residuals vs fitted, colored by method</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>pts_int <span class="sc">|&gt;</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mass_earth_hat, <span class="at">y =</span> residual,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> discovery_method)) <span class="sc">+</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Fitted mass_earth"</span>, <span class="at">y =</span> <span class="st">"Residual"</span>, <span class="at">color =</span> <span class="st">"Method"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10_ex_files/figure-html/10-ex-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) per-method mean residual — should be ≈ 0</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>pts_int <span class="sc">|&gt;</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(discovery_method) <span class="sc">|&gt;</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_resid =</span> <span class="fu">mean</span>(residual), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  discovery_method mean_resid
  &lt;fct&gt;                 &lt;dbl&gt;
1 Radial Velocity  0.00000612
2 Transit          0.00000607</code></pre>
</div>
</div>
<p>Both per-method means are essentially zero. <strong>Why:</strong> the interaction model gives each <code>discovery_method</code> its own intercept <em>and</em> its own slope. The OLS fit chooses those parameters to minimize squared residuals within each group, which is mathematically equivalent to forcing the group-specific residual mean to zero (just as a model with only an intercept produces residuals that sum to zero).</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.41 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-42-contents" aria-controls="callout-42" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.41 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-42" class="callout-42-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.41 (★★★)</strong> <em>Carried over from Chapter 6 — <code>m_two</code> was fit in Ch 6, but a residual-vs-fitted plot to probe LINE for a multi-predictor model belongs here.</em></p>
<p>Plot residuals vs fitted values for <code>m_two</code>. Comment on any structure you see (curvature, fan-shape, outlier clusters). Which LINE assumption is each pattern probing?</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.2.6 “Model fit and assumptions (LINE)” extended to multiple regression)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>planets_temp <span class="ot">&lt;-</span> planets <span class="sc">|&gt;</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(eq_temp_k), <span class="sc">!</span><span class="fu">is.na</span>(star_temp_k), <span class="sc">!</span><span class="fu">is.na</span>(insolation_earth))</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>m_two <span class="ot">&lt;-</span> <span class="fu">lm</span>(eq_temp_k <span class="sc">~</span> insolation_earth <span class="sc">+</span> star_temp_k,</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> planets_temp)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_points</span>(m_two) <span class="sc">|&gt;</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> eq_temp_k_hat, <span class="at">y =</span> residual)) <span class="sc">+</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Fitted eq_temp_k"</span>, <span class="at">y =</span> <span class="st">"Residual"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10_ex_files/figure-html/10-ex-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Some unequal-variance behavior at the high-temperature end is expected — hot exoplanets near their stars are over-represented and under-modeled by a two-predictor linear fit. That’s an <strong>Equal-variance</strong> (LINE “E”) flag. A trumpet shape (or systematic curvature) here is a signal to either add more predictors or fall back on the bootstrap (§ 10.3) for the slopes, which doesn’t require equal variance.</p>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="EX10.42 — show question">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-43-contents" aria-controls="callout-43" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>EX10.42 — show question
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-43" class="callout-43-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>EX10.42 (★★★)</strong> <em>Carried over from Chapter 6 — inspecting the </em>typical magnitude* of residuals is a natural follow-on to the LINE diagnostics in § 10.2.6.*</p>
<p>For <code>m_two</code> (reuse the setup from EX 10.41), use <code>get_regression_points(m_two)</code> to compute the <strong>standard deviation of the <code>residual</code> column</strong> with <code>sd()</code>. Translate this number into Kelvin and explain in one sentence what it tells a non-statistician about how far off a typical per-planet prediction is.</p>
</div>
</div>
</div>
<p><strong>Solution</strong> <em>(reference: Section 10.5 + LINE diagnostics — typical residual magnitude)</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>planets_temp <span class="ot">&lt;-</span> planets <span class="sc">|&gt;</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(eq_temp_k), <span class="sc">!</span><span class="fu">is.na</span>(star_temp_k), <span class="sc">!</span><span class="fu">is.na</span>(insolation_earth))</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>m_two <span class="ot">&lt;-</span> <span class="fu">lm</span>(eq_temp_k <span class="sc">~</span> insolation_earth <span class="sc">+</span> star_temp_k,</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> planets_temp)</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_points</span>(m_two) <span class="sc">|&gt;</span></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">typical_residual =</span> <span class="fu">sd</span>(residual))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  typical_residual
             &lt;dbl&gt;
1             337.</code></pre>
</div>
</div>
<p>A typical per-planet prediction is off by roughly ±<code>typical_residual</code> Kelvin (the standard deviation of the residuals). In plain English: the model is good at describing <em>trends</em> across the catalog, but you shouldn’t expect any <em>individual</em> planet’s predicted temperature to be within a few tens of Kelvin of the truth.</p>
<hr>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>