{
  "hash": "caeb36da149117cfe1adbbb9b4257f1e",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Estimation, Confidence Intervals, and Bootstrapping {#sec-confidence-intervals}\n\n::: {.callout-note title=\"In this chapter, you'll learn how to:\"}\n- Construct a *bootstrap distribution* using the `infer` workflow (`specify` → `generate` → `calculate`)\n- Build *percentile-based* and *standard-error-based* confidence intervals\n- Interpret a confidence interval in plain language (avoiding common misinterpretations)\n- Connect the bootstrap distribution to the theoretical sampling distribution\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\nWe studied sampling in @sec-sampling. Recall, for example, getting many random samples of red and white balls from a bowl, finding the sample proportions of red balls from each of those samples, and studying the distribution of the sample proportions. We can summarize our findings as follows:\n\n- the sampling distribution of the sample proportion follows, approximately, the normal distribution, \n- the expected value of the sample proportion, located at the center of the distribution, is exactly equal to the population proportion, and\n- the sampling variation, measured by the standard error of the sample proportion, is equal to the standard deviation of the population divided by the square root of the sample size used to collect the samples.\n\nSimilarly, when sampling chocolate-covered almonds and getting the sample mean weight from each sample, the characteristics described above are also encountered in the sampling distribution of the sample mean; namely,\n\n- the sampling distribution of the sample mean follows, approximately, the normal distribution; \n- the expected value of the sample mean is the population mean, and\n- the standard error of the sample mean is the standard deviation of the population divided by the square root of the sample size.\n\nMoreover, these characteristics also apply to sampling distributions for the difference in sample means, the difference in sample proportions, and others. Recall that the sampling distribution is not restricted by the distribution of the population. As long as the samples taken are fairly large and we use the appropriate standard error, we can generalize these results appropriately.\n\nThe study of the sampling distribution is motivated by another question we have not yet answered: how can we determine the average weight of all the almonds if we do not have access to the entire bowl? We have seen by using simulations in @sec-sampling that the average of the sample means, derived from many random samples, will be fairly close to the expected value of the sample mean, which is precisely the population mean weight.\n\nHowever, in real-life situations, we do not have access to many random samples, only to a single random sample. This chapter introduces methods and techniques that can help us approximate the information of the entire population, such as the population mean weight, by using a single random sample from this population. This undertaking is called __estimation__, and it is central to Statistics and Data Science.\n\nWe introduce some statistical jargon about estimation. If we are using a sample statistic to __estimate__ a population parameter, e.g., using the sample mean from a random sample to estimate the population mean, we call this statistic a __point estimate__ to make emphasis that it is a single value that is used to estimate the parameter of interest. \nNow, you may recall that, due to sampling variation, the sample mean typically does not match the population mean exactly, even if the sample is large. \nTo account for this variation, we use an interval to estimate the parameter instead of a single value, and appropriately call it an __interval estimate__ or, if given some level of accuracy, a __confidence interval__ of the population parameter. In this chapter, we explain how to find confidence intervals, the advantages of using them, and the different methods that can be used to determine them.\n\nIn @sec-theory-based-CI we introduce a method to build a confidence interval for the population mean that uses the random sample taken and theoretical characteristics of the sampling distribution discussed in @sec-sampling. \nWe call this the theory-based approach for constructing intervals. \nIn @sec-simulation-based-CI we introduce another method, called the bootstrap, that produces confidence intervals by resampling a large number of times from the original sample. Since resampling is done via simulations, we call this the simulation-based approach for constructing confidence intervals. <!-- In @sec-theory-ci we provide some theoretical foundations to explain the logic behind the bootstrap, introduce some alternatives within this approach, compare it with the theory-based approach, and show the advantages and disadvantages of different approaches. -->\nFinally, in @sec-summary-CI we summarize and present extensions of these methods.\n\n\n\n## Needed packages {.unnumbered #sec-CI-packages}\n\nIf needed, read @sec-packages for information on how to install and load R packages. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(moderndive)\nlibrary(infer)\n```\n:::\n\n\nRecall that loading the `tidyverse` package loads many packages that we have encountered earlier. For details refer to @sec-tidyverse-package. The packages `moderndive` and `infer` contain functions and data frames that will be used in this chapter.\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n## Tying the sampling distribution to estimation {#sec-theory-based-CI}\n\n\nIn this section we revisit the chocolate-covered almonds example introduced in @sec-sampling and the results from the sampling distribution of the sample mean weight of almonds, but this time we use this information in the context of estimation.\n\nWe start by introducing or reviewing some terminology using the almonds example. The bowl of chocolate-covered almonds is the population of interest. The parameter of interest is the *population mean* weight of almonds in the bowl, $\\mu$. This is the quantity we want to estimate.\n\nWe want to use the sample mean to estimate this parameter. So we call the sample mean an **estimator** or an **estimate** of $\\mu$, the population mean weight. \nThe difference between estimator and estimate is worth discussing.\n\nAs an illustration, we decide to take a random sample of 100 almonds from the bowl and use its sample mean weight to estimate the population mean weight. In other words, we intend to sum 100 almonds' weights, divide this sum by 100, and use this value to estimate the population mean weight. When we refer to the *sample mean* to describe this process via an equation, the sample mean weight is called an **estimator** of the population mean weight. \nSince different samples produce different sample means, the sample mean as an estimator is the random variable $\\overline  X$ described in @sec-random-variable-sample-mean. As we have learned studying the sampling distribution in @sec-sampling, we know that this **estimator** follows, approximately, a normal distribution; its expected value is equal to the population mean weight. Its standard deviation, also called standard error, is \n\n$$SE(\\bar x) = \\frac{\\sigma}{\\sqrt{n}}$$ \n\nwhere $n = 100$ in this example and $\\sigma$ is the population standard deviation of almonds' weights.\n\nWe took a random sample of 100 almonds' weights such as the one shown here and stored it in the `moderndive` package with the same name:\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 100 × 3\n# Groups:   replicate [1]\n   replicate    ID weight\n       <int> <int>  <dbl>\n 1         1   166    4.2\n 2         1  1215    4.2\n 3         1  1899    3.9\n 4         1  1912    3.8\n 5         1  4637    3.3\n 6         1   511    3.5\n 7         1   127    4  \n 8         1  4419    3.5\n 9         1  4729    4.2\n10         1  2574    4.1\n# ℹ 90 more rows\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nWe can use it to calculate the sample mean weight:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |>\n  summarize(sample_mean = mean(weight))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  replicate sample_mean\n      <int>       <dbl>\n1         1       3.682\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nThen $\\overline{x} = 3.682$ grams is an **estimate** of the population mean weight. \nIn summary, the **estimator** is the procedure, equation, or method that will be used on a sample to estimate a parameter before the sample has been retrieved and has many useful properties discussed in @sec-sampling. The moment a sample is taken and the equation of a sample mean is applied to this sample, the resulting number is an **estimate**.\n\nThe sample mean, as an estimator or estimate of the population mean, will be a central component of the material developed in this chapter. \nBut, note that it is not the only quantity of interest. \nFor example, the *population standard deviation* of the almonds' weight, denoted by the Greek letter $\\sigma$, is a parameter and the *sample standard deviation* can be an **estimator** or **estimate** of this parameter.\n\nFurthermore, we have shown in @sec-sampling that the expected value of the sample mean is equal to the population mean. When this happens, we call the sample mean an **unbiased** estimator of the population mean. This does not mean that any sample mean will be equal to the population mean; some sample means will be greater while others will be smaller but, on average, they will be equal to the population mean. In general, when the expected value of an estimator is equal to the parameter it is trying to estimate, we call the estimator **unbiased**. If it is not, the estimator is **biased**. \n\nWe now revisit the almond activity and study how the sampling distribution of the sample mean can help us build interval estimates for the population mean. \n\n:::{.learncheck}\n**Learning Check**\n\n**(LC8.1)**  What is the expected value of the sample mean weight of almonds in a large sample according to the sampling distribution theory?\n\n- A. It is always larger than the population mean.\n- B. It is always smaller than the population mean.\n- C. It is exactly equal to the population mean.\n- D. It is equal to the population mean on average but may vary in any single sample.\n\n**(LC8.2)**  What is a **point estimate** and how does it differ from an **interval estimate** in the context of statistical estimation?\n\n- A. A point estimate uses multiple values to estimate a parameter; an interval estimate uses a single value.\n- B. A point estimate is a single value used to estimate a parameter; an interval estimate provides a range of values within which the parameter likely falls.\n- C. A point estimate is the mean of multiple samples; an interval estimate is the median.\n- D. A point estimate and an interval estimate are the same and can be used interchangeably.\n\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n### Revisiting the almond activity for estimation {#sec-revisit-almond}\n\nIn @sec-sampling, one of the activities was to take many random samples of size 100 from a bowl of 5,000 chocolate-covered almonds. Since we have access to the contents of the entire bowl, we can compute the population parameters:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_bowl |> \n  summarize(population_mean = mean(weight), \n            population_sd = pop_sd(weight))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  population_mean population_sd\n            <dbl>         <dbl>\n1         3.64496      0.392070\n```\n\n\n:::\n:::\n\n\nThe total number of almonds in the bowl is 5,000. The population mean is \n\n$$\\mu = \\sum_{i=1}^{5000}\\frac{x_i}{5000}=3.64496,$$ \n\nand the population standard deviation, [`pop_sd()`](https://moderndive.github.io/moderndive/reference/pop_sd.html), from `moderndive`, is defined as\n\n$$\\sigma = \\sum_{i=1}^{5000} \\frac{(x_i - \\mu)^2}{5000}=0.3920696.$$\n\nWe keep those numbers for future reference to determine how well our methods of estimation are doing, but recall that in real-life situations we do not have access to the population values and the population mean $\\mu$ is unknown. All we have is the information from one random sample. In our example, we assume that all we know is the `almonds_sample_100` object stored in `moderndive`. \nIts `ID` variable shows the almond chosen from the bowl and its corresponding `weight`. Using this sample we calculate some sample statistics:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |> \n  summarize(mean_weight = mean(weight), \n            sd_weight = sd(weight), \n            sample_size = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  replicate mean_weight sd_weight sample_size\n      <int>       <dbl>     <dbl>       <int>\n1         1       3.682  0.362199         100\n```\n\n\n:::\n:::\n\n\nIn one of the activities performed in @sec-sampling we took many random samples, calculated their sample means, constructed a histogram using these sample means, and showed how the histogram is a good approximation of the sampling distribution of the sample mean. \nWe redraw @fig-sample-mean-100-with-normal here as @fig-sample-mean-100-with-normal-redraw.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The distribution of the sample mean.](08-confidence-intervals_files/figure-html/fig-sample-mean-100-with-normal-redraw-1.png){#fig-sample-mean-100-with-normal-redraw fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nThe histogram in @fig-sample-mean-100-with-normal-redraw is drawn using many sample mean weights from random samples of size $n=100$. \nThe added red smooth curve is the density curve for the normal distribution with the appropriate expected value and standard error calculated from the sample distribution. \nThe red dot represents the population mean $\\mu$, the unknown parameter we are trying to estimate. The blue right is the sample mean $\\overline{x} = 3.682$ from the random sample stored in `almonds_sample_100`.\n\nIn real-life applications, a sample mean is taken from a sample, but the distribution of the population and the population mean are unknown, so the location of the blue dot with respect to the red dot is also unknown. However, if we construct an interval centered on the blue dot, as long as it is wide enough the interval will contain the red dot.\nTo understand this better, we need to learn a few additional properties of the normal distribution.\n\n### The normal distribution\n\nA random variable can take on different values. When those values can be represented by one or more intervals, the likelihood of those values can be expressed graphically by a density curve on a Cartesian coordinate system in two dimensions. The horizontal axis (X-axis) represents the values that the random variable can take and the height of density curve (Y-axis) provides a graphical representation of the likelihood of those values; the higher the curve the more likely those values are. In addition, the total area under a density curve is always equal to 1. The set of values a random variable can take alongside their likelihood is what we call the distribution of a random variable.\n\nThe normal distribution \\index{distribution!normal} is the distribution of a special type of random variable. Its density curve has a distinctive bell shape, and it is fully defined by two values: (1) the mean or expected value of the random variable, $\\mu$, which is located on the X-axis at the center of the density curve (its highest point), and (2) the standard deviation, $\\sigma$, which reflects the dispersion of the random variable; the greater the standard deviation is the wider the curve appears.\nIn @fig-normal-curves, we plot the density curves of three random variables, all following normal distributions:\n\n1. The solid line represents a normal distribution with $\\mu = 5$ \\& $\\sigma = 2$.\n1. The dotted line represents a normal distribution with $\\mu = 5$ \\& $\\sigma = 5$.\n1. The dashed line represents a normal distribution with $\\mu = 15$ \\& $\\sigma = 2$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Three normal distributions.](08-confidence-intervals_files/figure-html/fig-normal-curves-1.png){#fig-normal-curves fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nA random variable that follows a normal distribution can take any values in the real line, but those values (on the X-axis) that correspond to the peak of the density curve are more likely than those corresponding to the tails.\nThe density curve drawn with a solid line has the same mean as the one drawn with a dotted line, $\\mu = 5$, but the former exhibits less dispersion, measured by the standard deviation $\\sigma =2$, than the latter, $\\sigma = 5$. Since the total area under any density curve is equal to 1, the wider curve has to be shorter in height to preserve this property. On the other hand, the density curve drawn with a solid line has the same standard deviation as the one drawn with a dashed line, $\\sigma = 2$, but the latter has a greater mean, $\\mu = 15$, than the former, $\\mu = 5$, so they do look the same but the latter is centered farther to the right on the X-axis than the former. \n\n\n#### The standard normal distribution {.unnumbered}\n\nA special normal distribution has mean $\\mu$ = 0 and standard deviation $\\sigma$ = 1. It is called the *standard normal distribution*, and it is represented by a density curve called the *$z$-curve*\\index{distribution!standard normal}. If a random variable $Z$ follows the standard normal distribution, a realization of this random variable is called a standard value or $z$-value. The $z$-value also represents the number of standard deviations above the mean, if positive, or below the mean, if negative. For example, if $z=5$, the value observed represents a realization of the random variable $Z$ that is five standard deviations above the mean, $\\mu = 0$.\n\n\n#### Linear transformations of random variables that follow the normal distribution {.unnumbered}\n\nA linear transformation of a random variable transforms the original variable into a new random variable by adding, subtracting, multiplying, or dividing constants to the original values. The resulting random variable could have a different mean and standard deviation. The most interesting transformation is turning a random variable into another with $\\mu = 0$ and $\\sigma = 1$. When this happens we say that the random variable has been standardized.\n\nA property of the normal distribution is that any linear transformation of a random variable that follows the normal distribution results in a new random variable that also follows a normal distribution, potentially with different mean and standard deviation. In particular, we can turn any random variable that follows the normal distribution into a random variable that follows the standard normal distribution. For example, if a value $x = 11$ comes from a normal distribution with mean $\\mu =5$ and standard deviation $\\sigma = 2$, the $z$-value \n\n$$z = \\frac{x - \\mu}{\\sigma} = \\frac{11 - 5}{2} = 3$$ \nis the corresponding value in a standard normal curve. Moreover, we have determined that $x = 11$ for this example is precisely $3$ standard deviations above the mean.\n\n#### Finding probabilities under a density curve {.unnumbered}\n\nWhen a random variable can be represented by a density curve, the probability that the random variable takes a value in any given interval (on the X-axis) is equal to the area under the density curve for that interval. If we know the equation that represents the density curve, we could use the mathematical technique from calculus known as integration to determine this area. In the case of the normal curve, the integral for any interval does not have a close-form solution, and the solution is calculated using numerical approximations.\n\n\n::: {.cell layout-align=\"center\"}\nPlease review [Appendix A online](https://moderndive.com/v2/appendixa) where we provide R code to work with different areas, probabilities, and values under a normal density curve. Here, we place focus on the insights of specific values and areas without dedicating time to those calculations.\n:::\n\n\nWe assume that a random variable $Z$ follows a standard normal distribution. We would like to know how likely it is for this random variable to take a value that is within one standard deviation from the mean. Equivalently, what is the probability that the observed value $z$ (in the X-axis) is between -1 and 1 as shown in @fig-normal-curve-shaded-1a?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Normal area within one standard deviation.](08-confidence-intervals_files/figure-html/fig-normal-curve-shaded-1a-1.png){#fig-normal-curve-shaded-1a fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nCalculations show that this area is 0.6827 (68.27%) of the total area under the curve. This is equivalent to saying that the probability of getting a value between $-1$ and 1 on a standard normal is 68.27%. This also means that if a random variable representing an experiment follows a normal distribution, the probability that the outcome of this experiment is within one standard deviation from the mean is 68.27%. Similarly, the area under the standard normal density curve between -2 and 2 is shown in @fig-normal-curve-shaded-2a.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Normal area within two standard deviations.](08-confidence-intervals_files/figure-html/fig-normal-curve-shaded-2a-1.png){#fig-normal-curve-shaded-2a fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nCalculations show that this area is equal to 0.9545 or 95.45%. If a random variable representing an experiment follows a normal distribution, the probability that the outcome of this experiment is within two standard deviations from the mean is 95.45%. It is also common practice to use the exact number of standard deviations that correspond to an area around the mean exactly equal to 95% (instead of 95.45%).\n\n::: {.cell layout-align=\"center\"}\nPlease see [Appendix A online](https://moderndive.com/v2/appendixa) to produce these or other calculations in R. \n:::\n\nThe result is that the area under the density curve around the mean that is exactly equal to 0.95, or 95%, is the area within 1.96 standard deviation from the mean. Remember this number as it will be used a few times in later sections.\n\nIn summary, if the possible outcomes of an experiment can be expressed as a random variable that follows the normal distribution, the probability of getting a result that is within one standard deviation from the mean is about 68.27%, within 2 standard deviations form the mean is 95.45%, within 1.96 standard deviations from the mean is 95%, and within 3 standard deviations from the mean is about 99.73%, to name a few.\nSpend a few moments grasping this idea; observe, for example, that it is almost impossible to observe an outcome represented by a number that is five standard deviations above the mean as the chances of that happening are near zero. We are now ready to return to our main goal: how to find an interval estimate of the population mean based on a single sample.\n\n:::{.learncheck}\n**Learning Check**\n\n**(LC8.3)** What does the population mean ($\\mu$) represent in the context of the almond activity?\n\n- A. The average weight of 100 randomly sampled almonds.\n- B. The weight of the heaviest almond in the bowl.\n- C. The average weight of all 5,000 almonds in the bowl.\n- D. The total weight of all almonds in the bowl.\n\n**(LC8.4)** Which of the following statements best describes the population standard deviation ($\\sigma$) in the almond activity?\n\n- A. It measures the average difference between each almond's weight and the sample mean weight.\n- B. It measures the average difference between each almond's weight and the population mean weight.\n- C. It is equal to the square root of the sample variance.\n- D. It is always smaller than the population mean.\n\n**(LC8.5)** Why do we use the sample mean to estimate the population mean in the almond activity?\n\n- A. Because the sample mean is always larger than the population mean.\n- B. Because the sample mean is a good estimator of the population mean due to its unbiasedness.\n- C. Because the sample mean requires less computational effort than the population mean.\n- D. Because the sample mean eliminates all sampling variation.\n\n:::\n\n### The confidence interval{#sec-CI-general}\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\nWe continue using the example where we try to estimate the population mean weight of almonds with a random sample of 100 almonds. We showed in @sec-sampling that the sampling distribution of the sample mean weight of almonds approximates a normal distribution with expected value equal to the population mean weight of almonds and a standard error equal to \n\n$$SE(\\bar x) = \\frac{\\sigma}{\\sqrt {100}}.$$ \nIn @sec-revisit-almond we showed that for the population of almonds, $\\mu =3.64496$ grams and $\\sigma = 0.3920696$, so the standard error for the sampling distribution is \n\n$$SE(\\bar x) = \\frac{\\sigma}{\\sqrt{100}} = \\frac{0.3920696}{\\sqrt{100}} = 0.039207$$ \ngrams. In @fig-normal-curve-1 we plot the density curve for this distribution using these values.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Normal density curve for the sample mean weight of almonds.](08-confidence-intervals_files/figure-html/fig-normal-curve-1-1.png){#fig-normal-curve-1 fig-align='center' width=90%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nThe horizontal axis (X-axis) represents the sample means that we can determine from all the possible random samples of 100 almonds. The red dot represents the expected value of the sampling distribution, $\\mu = 3.64$, located on the X-axis at the center of the distribution. The density curve's height can be thought of as how likely those sample means are to be observed. For example, it is more likely to get a random sample with a sample mean around $3.64496$ grams (which corresponds to the highest point of the curve) than it is to get a sample with a sample mean of around $3.5$ grams, since the curve's height is almost zero at that value. The blue dot is the sample mean from our sample of 100 almonds, $\\overline{x} = 3.682$ grams. It is located 0.03704 grams above the population mean weight. How far is 0.03704 grams? It is helpful to express this distance in standardized values: \n\n$$\\frac{3.682 - 3.64496}{0.039207} = 0.9447301$$\n\nso 0.03704 more grams is about 0.9447301 standard errors above the population mean.\n\nIn real-life situations, the population mean, $\\mu$, is unknown so the distance from the sample mean to $\\mu$ is also unknown. \nOn the other hand, the sampling distribution of the sample mean follows a normal distribution. Based on our earlier discussion about areas under the normal curve, there is a 95% chance that the value observed is within 1.96 standard deviations from the mean. In the context of our problem, there is a 95% chance that the sample mean weight is within 1.96 standard errors from the population mean weight. As shown earlier, the sample mean calculated in our example was 0.9447301 standard errors above the population mean, well within the reasonable range. \n\nThink about this result. If we were to take a different random sample of 100 almonds, the sample mean will likely be different, but you still have a 95% chance that the new sample mean will be within 1.96 standard errors from the population mean.\n\nWe can finally construct an interval estimate that takes advantage of this configuration. We center our interval at the sample mean observed and then extend to each side the magnitude equivalent to 1.96 standard errors. The lower and upper bounds of this interval are:\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n$$\\begin{aligned}\\left(\\overline{x} - 1.96 \\frac{\\sigma}{\\sqrt{n}},\\quad \\overline{x} + 1.96 \\frac{\\sigma}{\\sqrt{n}}\\right) &= \\left(3.682 - 1.96 \\cdot \\frac{0.3920696}{\\sqrt{100}},\\quad 3.682 + 1.96 \\cdot \\frac{0.3920696}{\\sqrt{100}}\\right)\\\\\n&= (3.605, 3.759)\\end{aligned}$$ \n\nHere is R code that can be used to calculate these lower and upper bounds:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |>\n  summarize(\n    sample_mean = mean(weight),\n    lower_bound = mean(weight) - 1.96 * sigma / sqrt(length(weight)),\n    upper_bound = mean(weight) + 1.96 * sigma / sqrt(length(weight))\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  replicate sample_mean lower_bound upper_bound\n      <int>       <dbl>       <dbl>       <dbl>\n1         1       3.682     3.60515     3.75885\n```\n\n\n:::\n:::\n\n\nThe functions `mean()` and `length()` find the sample mean weight and sample size, respectively, from the sample of almonds' weights in `almonds_sample_100`. The number 1.96 corresponds to the number of standard errors needed to get a 95% area under the normal distribution and the population standard deviation `sigma` of 0.3920696 was found in @sec-revisit-almond. @fig-normal-curve-2 shows this interval as a horizontal blue line. Observe how the population mean $\\mu$ is part of this interval.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Is the population mean in the interval?](08-confidence-intervals_files/figure-html/fig-normal-curve-2-1.png){#fig-normal-curve-2 fig-align='center' width=90%}\n:::\n:::\n\n\nSince 1.96 standard errors were used on the construction of this interval, we call this a 95% confidence interval. A confidence interval can be viewed as an interval estimator of the population mean. Compare an interval estimator with the sample mean that is a point estimator. The latter estimates the parameter with a single number, the former provides an entire interval to account for the location of the parameter. An apt analogy involves fishing. Imagine that there is a single fish swimming in murky water. The fish is not visible but its movement produces ripples on the surface that can provide some limited information about the fish's location. To capture the fish, one could use a spear or a net. Because the information is limited, throwing the spear at the ripples may capture the fish but likely will miss it.\n\n::: {.callout-warning title=\"Common mistake\"}\n**A 95% confidence interval is *not* \"a 95% probability that the parameter is in this range.\"** The population parameter is a fixed (though unknown) number — it's either inside this particular interval or it isn't. The \"95%\" refers to the *procedure*: if you repeated the sampling-and-CI process many times, about 95% of the resulting intervals would contain the true parameter. The honest interpretation: *\"We are 95% confident that the population mean is between X and Y\"*, where \"confident\" refers to the long-run reliability of the method, not the probability of any single interval.\n:::\n\nThrowing a net around the ripples, on the other hand, may give a much higher likelihood of capturing the fish. Using the sample mean only to estimate the population mean is like throwing a spear at the ripples in the hopes of capturing the fish. Constructing a confidence interval that may include the population mean is like throwing a net to surround the ripples. Keep this analogy in mind, as we will revisit it in later sections.\n\n:::{.learncheck}\n**Learning Check**\n\n**(LC8.6)**  How is the standard error of the sample mean weight of almonds calculated in the context of this example?\n\n- A. By dividing the sample mean by the population standard deviation.\n- B. By dividing the population standard deviation by the square root of the sample size.\n- C. By multiplying the sample mean by the square root of the sample size.\n- D. By dividing the population mean by the sample size.\n\n**(LC8.7)** What does a 95% confidence interval represent in the context of the almond weight estimation?\n\n- A. There is a 95% chance that the sample mean is within 1.96 standard deviations from the population mean.\n- B. The interval will contain 95% of the almond weights from the sample.\n- C. There is a 95% chance that the population mean falls within 1.96 standard errors from the sample mean.\n- D. The sample mean is exactly equal to the population mean 95% of the time.\n\n:::\n\n### The t distribution {#sec-t-distribution-CI}\n\n\nRecall that due to the Central Limit Theorem, the sampling distribution of the sample mean was approximately normal with mean equal to the population mean $\\mu$ and standard deviation given by the standard error $SE(\\overline X) = \\sigma/\\sqrt{n}$. We can standardize this for any sample mean $\\overline{x}$ such that \n\n$$z = \\frac{\\overline{x} - \\mu}{\\sigma/\\sqrt{n}}$$ \n\nis the corresponding value of the standard normal distribution.\n\nIn the construction of the interval in @fig-normal-curve-2 we have assumed the population standard deviation, $\\sigma$, was known, and therefore we have used it to find the confidence interval. Nevertheless, in real-life applications, the population standard deviation is also unknown. \nInstead, we use the sample standard deviation, $s$, from the sample we have, as an estimator of the population standard deviation $\\sigma$. Our estimated standard error is given by \n\n$$\\widehat{SE}(\\overline X) = \\frac{s}{\\sqrt n}.$$\n\n\nWhen using the sample standard deviation to estimate the standard error, we are introducing additional uncertainty in our model. For example, if we try to standardize this value, we get \n\n$$t = \\frac{\\overline{x} - \\mu}{s/\\sqrt{n}}.$$\n\nBecause we are using the sample standard deviation in this equation and since the sample standard deviation changes from sample to sample, the additional uncertainty makes the values $t$ no longer normal. Instead they follow a new distribution called the $t$ distribution.\n\nThe $t$ distribution is similar to the standard normal; its density curve is also bell-shaped, and it is symmetric around zero, but the tails of the $t$ distribution are a little thicker than those of the standard normal.\nIn addition, the $t$ distribution requires one additional parameter, the degrees of freedom. For sample mean problems, the degrees of freedom needed are exactly $n-1$, the size of the sample minus one. @fig-t-curve-1 shows the density curves of \n\n- the standard normal density curve, in black, \n- a $t$ density curve for a t distribution with 2 degrees of freedom, in dotted blue, and\n- a $t$ density curve for a t distribution with 10 degrees of freedom, in dashed red.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The standard normal and two t-distributions.](08-confidence-intervals_files/figure-html/fig-t-curve-1-1.png){#fig-t-curve-1 fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nObserve how the $t$ density curve in dashed red ($t$ with 10 degrees of freedom) gets closer to the standard normal density curve, or $z$-curve, in solid black, than the $t$ curve in dotted blue ($t$ with 2 degrees of freedom). The greater the number of degrees of freedom, the closer the $t$ density curve is from the $z$ curve. This change makes our calculations slightly different.\n\n\n::: {.cell layout-align=\"center\"}\nPlease see [Appendix A online](https://moderndive.com/v2/appendixa) for calculations of probabilities for $t$ density curves with different degrees of freedom.\n:::\n\nUsing that knowledge, the calculation for our specific example shows that 95% of the sample means are within 1.98 standard errors from the population mean weight. The number of standard errors needed is not that different from before, 1.98 versus 1.96, because the degrees of freedom are fairly large.\n\nUsing this information, we can construct the 95% confidence interval based entirely on our sample information and using the sample mean and sample standard deviation. We calculate those values again for `almonds_sample_100`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |>\n  summarize(sample_mean = mean(weight), sample_sd = sd(weight))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  replicate sample_mean sample_sd\n      <int>       <dbl>     <dbl>\n1         1       3.682  0.362199\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\nObserve that the sample standard deviation is $s = 0.3621987$ which is not that different from the population standard deviation of $\\sigma = 0.3920696$. We again center the confidence interval at the observed sample mean but now extend the interval by 1.98 standard errors to each side. The lower and upper bounds of this confidence interval are:\n\n$$\n\\begin{aligned}\n\\left(\\overline{x} - 1.98 \\frac{s}{\\sqrt{n}},\\quad \\overline{x} + 1.98 \\frac{s}{\\sqrt{n}}\\right) &= \\left(3.682 - 1.98 \\cdot \\frac{0.3621987}{\\sqrt{100}}, 3.682 + 1.98 \\cdot \\frac{0.3621987}{\\sqrt{100}}\\right) \\\\\n&= (3.498, 3.846))\n\\end{aligned}\n$$ \n\nWe can also compute these lower and upper bounds:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |>\n  summarize(sample_mean = mean(weight), sample_sd = sd(weight),\n            lower_bound = mean(weight) - 1.98*sd(weight)/sqrt(length(weight)),\n            upper_bound = mean(weight) + 1.98*sd(weight)/sqrt(length(weight)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  replicate sample_mean sample_sd lower_bound upper_bound\n      <int>       <dbl>     <dbl>       <dbl>       <dbl>\n1         1       3.682  0.362199     3.61028     3.75372\n```\n\n\n:::\n:::\n\n\nThe confidence interval computed here, using the sample standard deviation and a $t$ distribution, is almost the same as the one attained using the population standard deviation and the standard normal distribution, the difference is about 0.005 units for the upper and lower bound. This happens because with a sample size of 100, the $t$-curve and $z$-curve are almost identical and also because the sample standard deviation was very similar to the population standard deviation. This does not have to be always the case and occasionally we can observe greater differences; but, in general, the results are fairly similar.\n\nMore importantly, the confidence interval constructed here contains the population mean of $\\mu = 3.64496$, which is the result we needed. Recall that a confidence interval is an interval estimate of the parameter of interest, the population mean weight of almonds. \nWe can summarize the results so far:\n\n- If the size used for your random sample is large enough, the sampling distribution of the sample mean follows, approximately, the normal distribution.\n- Using the sample mean observed and the standard error of the sampling distribution, we can construct 95% confidence intervals for the population mean. The formula for these intervals (where $n$ is the sample size used) is given by \n\n$$\\left(\\overline{x} - 1.96 \\frac{\\sigma}{\\sqrt{n}},\\quad \\overline{x} + 1.96 \\frac{\\sigma}{\\sqrt{n}}\\right).$$\n\n- When the population standard deviation is unknown (which is almost always the case), the sample standard deviation is used to estimate the standard error. This produces additional variability and the standardized values follow a $t$ distribution with $n-1$ degrees of freedom. The formula for 95% confidence intervals when the sample size is $n=100$ is given by \n\n$$\\left(\\overline{x} - 1.98 \\frac{s}{\\sqrt{100}},\\quad \\overline{x} + 1.98 \\frac{s}{\\sqrt{100}}\\right).$$  \n\n- The method to construct 95% confidence intervals guarantees that in the long-run for 95% of the possible samples, the intervals determined will include the population mean. It also guarantees that 5% of the possible samples will lead to intervals that do not include the population mean.\n- As we have constructed intervals with a 95% level of confidence, we can construct intervals with any level of confidence. The only change in the equations will be the number of standard errors needed.\n\n\n### Interpreting confidence intervals\n\nWe have used the sample `almonds_sample_100`, constructed a 95% confidence interval for the population mean weight of almonds, and showed that the interval contained this population. This result is not surprising as we expect intervals such as this to include the population mean for 95% of the possible random samples. We repeat this interval construction for many random samples. @fig-almond-mean-cis presents the results for one hundred 95% confidence intervals.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![One hundred 95% confidence intervals and whether the population mean is captured in each.](08-confidence-intervals_files/figure-html/fig-almond-mean-cis-1.png){#fig-almond-mean-cis fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nNote that each interval was built using a different random sample. The red vertical line is drawn at the location of the population mean weight, $\\mu = 3.64496$. The horizontal lines represent the one hundred 95% confidence intervals found. The gray confidence intervals cross the red vertical line so they contain the population mean. The black confidence intervals do not.\n\nThis result motivates the meaning of a 95% confidence interval: If you could construct intervals using the procedure described earlier for every possible random sample, then 95% of these intervals will include the population mean and 5% of them will not. \n\nOf course, in most situations, it would be impractical or impossible to take every possible random sample. Still, for a large number of random samples, this result is approximately correct. In @fig-almond-mean-cis, for example, 5 out of 100 confidence intervals do not include the population mean, and 95% do. It won't always match up perfectly like this, but the proportions should match pretty close to the confidence level chosen.\n\nThe term \"95% confidence\" invites us to think we are talking about probabilities or chances. Indeed we are, but in a subtle way. Before a random sample has been procured, there is a 95% chance that when a confidence interval is constructed using the prospective random sample, this interval will contain the population mean. The moment a random sample has been attained, the interval constructed either contains the population mean or it does not; with certainty, there is no longer a chance involved. This is true even if we do not know what the population mean is.\nSo the 95% confidence refers to the method or process to be used on a prospective sample. We are confident that if we follow the process to construct the interval, 95% of the time the random sample attained will lead us to produce an interval that contains the population mean.\n\nOn the other hand, it would be improper to say that... \"there is a 95% chance that the confidence interval contains the population mean.\"  Looking at @fig-almond-mean-cis, each of the confidence intervals either does or does not contain $\\mu$. Once the confidence interval is determined, either the population mean is included or not. \n\nIn the literature, this explanation has been encapsulated in a short-hand version: we are 95% confident that the interval contains the population parameter. For example, in @sec-t-distribution-CI the 95% confidence interval for the population mean weight of almonds was (3.498, 3.846), and we would say: \"We are 95% confident that the population mean weight of almonds is between 3.498 and 3.846 grams.\" \n\nIt is perfectly acceptable to use the short-hand statement, but always remember that the 95% confidence refers to the process, or method, and can be thought of as a chance or probability only before the random sample has been acquired. To further ensure that the probability-type of language is not misused, quotation marks are sometimes put around \"95% confident\" to emphasize that it is a short-hand version of the more accurate explanation.\n\n:::{.learncheck}\n**Learning Check**\n\n**(LC8.8)** Why does the $t$ distribution have thicker tails compared to the standard normal distribution?\n\n- A. Because the sample mean is considered more likely to match the population mean closely.\n- B. Because the $t$ distribution is designed to work when the data does not follow a normal distribution.\n- C. Because it assumes that the sample size is always smaller when applying the $t$ distribution.\n- D. Because it accounts for the extra uncertainty that comes from using the sample standard deviation instead of the population standard deviation.\n\n\\newpage\n\n**(LC8.9)** What is the effect of increasing the degrees of freedom on the $t$ distribution?\n\n- A. The tails of the distribution become thicker.\n- B. The tails of the distribution become thinner.\n- C. The distribution does not change with degrees of freedom.\n- D. The distribution becomes skewed to the right.\n\n:::\n\n#### Understanding the width of a confidence interval {#sec-ci-width .unnumbered}\n\nA confidence interval is an estimator of a population parameter. In the case of the almonds' bowl we constructed a confidence interval for the population mean. The equation to construct a 95% confidence interval was \n\n$$\\left(\\overline{x} - 1.96 \\frac{\\sigma}{\\sqrt{n}}, \\overline{x} + 1.96 \\frac{\\sigma}{\\sqrt{n}}\\right)$$ \nObserve that the confidence interval is centered at the sample mean and it extends to each side 1.96 standard errors $1.96\\cdot \\sigma / \\sqrt{n}$. This quantity is exactly half the width of your confidence interval, and it is called the **margin of error**. The value of the population standard deviation, $\\sigma$, is beyond our control, as it is determined by the distribution of the experiment or phenomenon studied. The sample mean, $\\overline{x}$, is a result that depends on your random sample exclusively. On the other hand, the number 1.96 and the sample size, $n$, are values that can be changed by the researcher or practitioner. They play an important role on the width of the confidence interval. We study each of them separately.\n\n##### The confidence level {.unnumbered}\n\nWe mentioned earlier that the number 1.96 relates to a 95% confidence process but we did not show how to determine this value. The level of confidence is a decision of the practitioner. If you want to be more confident, say 98% or 99% confident, you just need to adjust the appropriate number of standard errors needed. We show how to determine this number, and use @fig-normal-curve-shaded-3a to illustrate this process.\n\n- If the confidence level is 0.95 (or 95%), the area in the middle of the standard normal distribution is 0.95. This area is shaded in @fig-normal-curve-shaded-3a.\n- We construct $\\alpha = 1 - \\text{confidence level} = 1 - 0.95 = 0.05$. Think of $\\alpha$ as the total area on both tails.\n- Since the normal distribution is symmetric, the area on each tail is $\\alpha/2 = 0.05/2 = 0.025$.\n- We need the exact number of standard deviations that produces the shaded area. Since the center of a standard normal density curve is zero, as shown in @fig-normal-curve-shaded-3a, and the normal curve is symmetric, the number of standard deviations can be represented by $-q$ and $q$, the same magnitude but one positive and the other negative.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Normal curve with the shaded middle area being 0.95](08-confidence-intervals_files/figure-html/fig-normal-curve-shaded-3a-1.png){#fig-normal-curve-shaded-3a fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nIn R, the function `qnorm()` finds the value of $q$ when the area under this curve to the left of this value $q$ is given. In our example the area to the left of $-q$ is $\\alpha/2 = 0.05/2 = 0.025$, so\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqnorm(0.025)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.959964\n```\n\n\n:::\n:::\n\n\nor 1.96 standard deviation below the mean. Similarly, the total area under the curve to the left of $q$ is the total shaded area, 0.95, plus the small white area on the left tail, $0.025$, and $0.95 + 0.025 = 0.975$, so\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqnorm(0.975)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.959964\n```\n\n\n:::\n:::\n\n\nThat is the reason we use 1.96 standard deviation when calculating 95% confidence intervals. What if we want to retrieve a 90% confidence interval? We follow the same procedure:\n\n- The confidence level is 0.90.\n- $\\alpha = 1 - \\text{confidence level} = 1 - 0.90 = 0.10$.\n- The area on each tail is $\\alpha/2 = 0.10/2 = 0.05$.\n- The area needed to find $q$ is $0.90+0.05 = 0.95$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqnorm(0.95)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.645\n```\n\n\n:::\n:::\n\n\nIf we want to determine a 90% confidence interval, we need to use 1.6448536 standard errors in our calculations. We can update the R code to calculate the lower and upper bounds of a 90% confidence interval:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |>\n  summarize(sample_mean = mean(weight),\n            lower_bound = mean(weight) - qnorm(0.95)*sigma/sqrt(length(weight)),\n            upper_bound = mean(weight) + qnorm(0.95)*sigma/sqrt(length(weight)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  replicate sample_mean lower_bound upper_bound\n      <int>       <dbl>       <dbl>       <dbl>\n1         1       3.682     3.61751     3.74649\n```\n\n\n:::\n:::\n\n\nLet's do one more. If we want an 80% confidence interval, $1 - 0.8 = 0.2$, $0.2/2 = 0.1$, and $0.8+0.1 = 0.9$, so\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqnorm(0.9)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.282\n```\n\n\n:::\n:::\n\n\nWhen you want to calculate an 80%, 90%, or 95% confidence interval, you need to construct your interval using 1.2815516, 1.6448536, or 1.959964 standard errors, respectively. The more confident you want to be, the larger the number of standard errors you need to use, and the wider your confidence interval becomes. But a confidence interval is an estimator of the population mean, the narrower it is, the more useful it is for practical reasons. So there is a trade-off between the width of a confidence interval and the confidence you want to have.\n\n\n##### The sample size {.unnumbered}\n\nAs we studied changes to the confidence level, we can determine how big is the random sample used. The margin of error for a 95% confidence interval is \n\n$$1.96\\cdot \\frac{\\sigma}{\\sqrt{n}}.$$\n\nIf the sample size increases, the margin of error decreases proportional to the square root of the sample size. For example, if we secure a random sample of size 25, $1/\\sqrt{25} = 0.2$, and if we draw a sample of size 100, $1/\\sqrt{100} = 0.1$. By choosing a larger sample size, four times larger, we produce a confidence interval that is half the width. This result is worth considering.\n\nA confidence interval is an estimator of the parameter of interest, such as the population mean weight of almonds. Ideally, we would like to build a confidence interval with a high level of confidence, for example, 95% confidence. But we also want an interval that is narrow enough to provide useful information. For example, assume we get the following 95% confidence intervals for the population mean weight of almonds:\n\n- between 2 and 4 grams, or \n- between 3.51 and 3.64 grams, or \n- between 3.539 and 3.545 grams.\n\nThe first interval does not seem useful at all, the second works better, and the third is tremendously accurate, as we are 95% confident that the population mean is within 0.006 grams. Obviously, we always prefer narrower intervals, but there are trade-offs we need to consider. We always prefer high levels of confidence, but the more confident we want to be the wider the interval will be. In addition, the larger the random sample used, the narrower the confidence interval will be. Using a large sample is always a preferred choice, but the trade-offs are often external; collecting large samples could be expensive and time-consuming. The construction of confidence intervals needs to take into account all these considerations.\n\nWe have concluded the theory-based approach to construct confidence intervals. In the next section we explore a completely different approach to construct confidence intervals and in later sections we will make comparisons of these methods.\n\n## Estimation with the bootstrap {#sec-simulation-based-CI}\n\nIn 1979, Brad Efron published an article introducing a method called the bootstrap \\index{bootstrap!statistical reference}[@Efron1979] that is next summarized. A random sample of size $n$ is taken from the population. \nThis sample is used to find another sample, with replacement, also of size $n$. This is called *resampling with replacement*\\index{resampling} and the resulting sample is called a *bootstrap sample*\\index{bootstrap}. For example, if the original sample is $\\{4,2,5,4,1,3,7,4,6,1\\}$, one particular bootstrap sample could be $\\{6, 4, 7, 4, 2, 7, 2, 5, 4, 1\\}.$\nObserve that the number 7 appears once in the original sample, but twice in the bootstrap sample; \nsimilarly, the number 3 in the original sample does not appear in the bootstrap sample. This is not uncommon for a bootstrap sample, some of the numbers in the original sample are repeated and others are not included. \n\nThe basic idea of the bootstrap is to gain a large number of bootstrap samples, all drawn from the same original sample. Then, we use all these bootstrap samples to find estimates of population parameters, standard errors, or even the density curve of the population. Using them we can construct confidence intervals, perform hypothesis testing, and other inferential methods.\n\nThis method takes advantage of the large number of bootstrap samples that can be determined. In several respects, this exercise is not different from the sampling distribution explained in @sec-sampling. The only difference, albeit an important one, is that we are not sampling from the population, we are sampling from the original sample. \nHow many different bootstrap samples could we get from a single sample? A very large number, actually. If the original sample has 10 numbers, as the one shown above, each possible bootstrap sample of size 10 is determined by sampling 10 times with replacement, so the total number of bootstrap samples is $10^{10}$ or 10 billion different bootstrap samples. If the original sample has 20 numbers, the number of bootstrap samples is $20^{20}$, a number greater than the total number of stars in the universe.\nEven with modern powerful computers, it would be an onerous task to calculate every possible bootstrap sample. Instead, a thousand or so bootstrap samples are retrieved, similar to the simulations performed in @sec-sampling, and this number is often large enough to provide useful results.\n\nSince Efron [@Efron1979] proposed the bootstrap, the statistical community embraced this method. During the 1980s and 1990s, many theoretical and empirical results were presented showing the strength of bootstrap methods. As an illustration, Efron [@Efron1979], Hall [@Hall1986], Efron and Tibshirani[@EfronTibshi1986], and Hall [@Hall1988] showed that bootstrapping was at least as good if not better than existent methods, when the goal was to estimate the standard error of an estimator or find the confidence intervals of a parameter. Modifications were proposed to improve the algorithm in situations where the basic method was not producing accurate results. With the continuous improvement of computing power and speed, and the advantages of having ready-to-use statistical software for its implementation, the use of the bootstrap has become more and more popular in many fields.\n\nAs an illustration, if we are interested in the mean of the population, $\\mu$, and we have collected one random sample, we can gain a large number of bootstrap samples from this original sample, use them to calculate sample means, order the sample means from smallest to largest, and choose the interval that contains the middle 95% of these sample means. This will be the simplest way to find a confidence interval based on the bootstrap. In the next few subsections, we explore how to incorporate this and similar methods to construct confidence intervals.\n\n### Bootstrap samples: revisiting the almond activity {#sec-revisit-almond-bootstrap}\n\nTo study and understand the behavior of bootstrap samples, we return to our example of the chocolate-covered almonds in a bowl. Recall that the bowl is considered the population of almonds, and we are interested in estimating the population mean weight of almonds.\n\nAs we did before, we only have access to a single random sample. In this section, we use the data frame `almonds_sample_100`, a random sample of 100 almonds taken earlier. We call this the original sample, and it is used in this section to create the bootstrap samples.\nThe first 10 rows are shown:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 100 × 3\n# Groups:   replicate [1]\n   replicate    ID weight\n       <int> <int>  <dbl>\n 1         1   166    4.2\n 2         1  1215    4.2\n 3         1  1899    3.9\n 4         1  1912    3.8\n 5         1  4637    3.3\n 6         1   511    3.5\n 7         1   127    4  \n 8         1  4419    3.5\n 9         1  4729    4.2\n10         1  2574    4.1\n# ℹ 90 more rows\n```\n\n\n:::\n:::\n\n\n\n#### Constructing a bootstrap sample: resampling once {.unnumbered}\n\nWe start by constructing one bootstrap sample of 100 almonds from the original sample of 100 almonds. These are the steps needed to perform this task manually:\n\n**Step 1**: Place the original sample of 100 almonds into a bag or hat.\n\n**Step 2**: Mix the bag contents, draw one almond, weigh it, and record the weight as seen in @fig-confidence-intervals-tactile-resampling-alt.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Step 2: Weighing one almond at random.](images/sampling/almonds/one-almond.png){#fig-confidence-intervals-tactile-resampling-alt fig-align='center' width=30%}\n:::\n:::\n\n\n**Step 3**: Put the almond back into the bag! In other words, replace it as seen in @fig-confidence-intervals-tactile-resampling-v4. \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Step 3: Replacing almond.](images/sampling/pennies/tactile_simulation/4_put_it_back.png){#fig-confidence-intervals-tactile-resampling-v4 fig-align='center' width=50%}\n:::\n:::\n\n\n**Step 4**: Repeat Steps 2 and 3 a total of 99 more times, resulting in 100 weights.\n\nThese steps describe *resampling with replacement*\\index{resampling}, and the resulting sample is called a *bootstrap sample*. This procedure results in some almonds being chosen more than once and other almonds not being chosen at all. Resampling with replacement induces *sampling variation*, so every bootstrap sample can be different than any other.\n\nThis activity can be performed manually following the steps described above. We can also take advantage of the R code we have introduced in @sec-sampling and do this virtually.\nThe data frame `almonds_sample_100` contains the random sample of almonds taken from the population. We show selected rows from this sample. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 <- almonds_sample_100 |> \n  ungroup() |> \n  select(-replicate)\nalmonds_sample_100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 100 × 2\n      ID weight\n   <int>  <dbl>\n 1   166    4.2\n 2  1215    4.2\n 3  1899    3.9\n 4  1912    3.8\n 5  4637    3.3\n 6   511    3.5\n 7   127    4  \n 8  4419    3.5\n 9  4729    4.2\n10  2574    4.1\n# ℹ 90 more rows\n```\n\n\n:::\n:::\n\n\nWe use `ungroup()` and `select` to eliminate the variable `replicate` from the `almonds_sample_100` as this variable may create clutter when resampling. We can now create a bootstrap sample also of size 100 by resampling with replacement once.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nboot_sample <- almonds_sample_100 |> \n  rep_sample_n(size = 100, replace = TRUE, reps = 1)\n```\n:::\n\n\nWe have used this type of R syntax many times in @sec-sampling.\nWe first select the data frame `almonds_sample_100` that contains the almonds' weights in the original sample. \nWe then perform resampling with replacement once: we resample by using `rep_sample_n()`, a sample of size 100 by setting `size = 100`, with replacement by adding the argument `replace = TRUE`, and one time by setting `reps = 1`.\nThe object `boot_sample` is a bootstrap sample of 100 almonds' weights gained from the original sample of 100 almonds' weights. We show the first ten rows of `boot_sample`:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nboot_sample\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 100 × 3\n# Groups:   replicate [1]\n   replicate    ID weight\n       <int> <int>  <dbl>\n 1         1  2105    3.1\n 2         1  4529    3.8\n 3         1  1146    4.2\n 4         1  2993    3.2\n 5         1  1535    3.2\n 6         1  2294    3.7\n 7         1   438    3.8\n 8         1  4419    3.5\n 9         1  1674    3.5\n10         1  1146    4.2\n# ℹ 90 more rows\n```\n\n\n:::\n:::\n\n\nWe can also study some of the characteristics of this bootstrap sample, such as its sample mean:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nboot_sample |> \n  summarize(mean_weight = mean(weight))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  replicate mean_weight\n      <int>       <dbl>\n1         1       3.702\n```\n\n\n:::\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nBy using `summarize()` and `mean()` on the bootstrap sample `boot_sample`, we determine that the mean weight is 3.702 grams. Recall that the sample mean of the original sample was found in the previous subsection as 3.682. So, the sample mean of the bootstrap sample is different than the sample mean of the original sample. This variation is induced by resampling with replacement, the method for finding the bootstrap sample. We can also compare the histogram of `weight`s for the bootstrap sample with the histogram of `weight`s for the original sample.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(boot_sample, aes(x = weight)) +\n  geom_histogram(binwidth = 0.1, color = \"white\") +\n  labs(title = \"Resample of 100 weights\")\n```\n\n```{.r .cell-code}\nggplot(almonds_sample_100, aes(x = weight)) +\n  geom_histogram(binwidth = 0.1, color = \"white\") +\n  labs(title = \"Original sample of 100 weights\")\n```\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Comparing `weight` in the resampled `boot_sample` with the original sample `almonds_sample_100`.](08-confidence-intervals_files/figure-html/fig-origandresample-1.png){#fig-origandresample fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nObserve in @fig-origandresample that while the general shapes of both distributions of `weight`s are roughly similar, they are not identical. \nThis is the typical behavior of bootstrap samples. They are samples that have been determined from the original sample, but because replacement is used before each new observation is attained, some values often appear more than once while others often do not appear at all.\n\n#### Many bootstrap samples: resampling multiple times {#sec-replicates .unnumbered}\n\nIn this subsection, we take full advantage of resampling with replacement by taking many bootstrap samples and study relevant information, such as the variability of their sample means. We can start by using the R syntax we used before, this time for 35 replications.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbootstrap_samples_35 <- almonds_sample_100 |> \n  rep_sample_n(size = 100, replace = TRUE, reps = 35)\nbootstrap_samples_35\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,500 × 3\n# Groups:   replicate [35]\n   replicate    ID weight\n       <int> <int>  <dbl>\n 1         1  1459    3.6\n 2         1  2972    3.4\n 3         1  1215    4.2\n 4         1  1381    3.4\n 5         1  1264    3.5\n 6         1   199    3.4\n 7         1   476    3.8\n 8         1  4806    3.7\n 9         1  3169    4.1\n10         1  2265    3.4\n# ℹ 3,490 more rows\n```\n\n\n:::\n:::\n\n\nThe syntax is the same as before, but this time we set `reps =` 35 to get 35 bootstrap samples.\nThe resulting data frame, `bootstrap_samples`, has 35 $\\cdot$ 100 = 3500 rows corresponding to 35 resamples of 100 almonds' weights. Let's now compute the resulting 35 sample means using the same `dplyr` code as we did in the previous section:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nboot_means <- bootstrap_samples_35 |> \n  summarize(mean_weight = mean(weight))\nboot_means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 35 × 2\n   replicate mean_weight\n       <int>       <dbl>\n 1         1       3.68 \n 2         2       3.688\n 3         3       3.632\n 4         4       3.68 \n 5         5       3.679\n 6         6       3.675\n 7         7       3.678\n 8         8       3.706\n 9         9       3.643\n10        10       3.68 \n# ℹ 25 more rows\n```\n\n\n:::\n:::\n\n\nObserve that `boot_means` has 35 rows, corresponding to the 35 bootstrap sample means. Furthermore, observe that the values of `mean_weight` vary as shown in @fig-resampling-35.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(boot_means, aes(x = mean_weight)) +\n  geom_histogram(binwidth = 0.01, color = \"white\") +\n  labs(x = \"sample mean weight in grams\")\n```\n\n::: {.cell-output-display}\n![Distribution of 35 sample means from 35 bootstrap samples.](08-confidence-intervals_files/figure-html/fig-resampling-35-1.png){#fig-resampling-35 fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nThis histogram highlights the variation of the sample mean weights. Since we have only used 35 bootstrap samples, the histogram looks a little coarse.\nTo improve our perception of this variation, we find 1000 bootstrap samples and their sample means:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Retrieve 1000 bootstrap samples\nbootstrap_samples <- almonds_sample_100 |> \n  rep_sample_n(size = 100, replace = TRUE, reps = 1000)\n\n# Compute sample means from the bootstrap samples\nboot_means <- bootstrap_samples |> \n  summarize(mean_weight = mean(weight))\n```\n:::\n\n\nWe can combine these two operations into a single chain of pipe (`|>`) operators:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nboot_means <- almonds_sample_100 |> \n  rep_sample_n(size = 100, replace = TRUE, reps = 1000) |> \n  summarize(mean_weight = mean(weight))\nboot_means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000 × 2\n   replicate mean_weight\n       <int>       <dbl>\n 1         1       3.68 \n 2         2       3.688\n 3         3       3.632\n 4         4       3.68 \n 5         5       3.679\n 6         6       3.675\n 7         7       3.678\n 8         8       3.706\n 9         9       3.643\n10        10       3.68 \n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\nThe data frame `boot_means` contains 1000 sample mean weights. Each is calculated from a different bootstrap sample and visualized in @fig-one-thousand-sample-means.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(boot_means, aes(x = mean_weight)) +\n  geom_histogram(binwidth = 0.01, color = \"white\") +\n  labs(x = \"sample mean weight in grams\")\n```\n\n::: {.cell-output-display}\n![Histogram of 1000 bootstrap sample mean weights of almonds.](08-confidence-intervals_files/figure-html/fig-one-thousand-sample-means-1.png){#fig-one-thousand-sample-means fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nThe histogram is a graphical approximation of the *bootstrap distribution of the sample mean*. This distribution is constructed by getting all the sample means from every bootstrap sample constructed based on the original sample. Since the total number of possible bootstraps is really large, we have not used all of them here, but 1000 of them already provides a good visual approximation.\n\nObserve also that the bootstrap distribution itself can approximate the *sampling distribution* of the sample mean, a concept we studied in @sec-sampling where we took multiple samples from the population. The key difference here is that we resample from a single sample, the original sample, not from the entire population.\n\nBy inspecting the histogram in @fig-one-thousand-sample-means, the bell-shape is apparent. We can also approximate the center and the spread of this distribution by computing the mean and the standard deviation of these 1000 bootstrap sample means:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nboot_means |> \n  summarize(mean_of_means = mean(mean_weight),\n            sd_of_means = sd(mean_weight))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  mean_of_means sd_of_means\n          <dbl>       <dbl>\n1       3.67998   0.0356615\n```\n\n\n:::\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nEverything we learned in @sec-sampling when studying the sampling distribution of the sample mean applies here. For example, observe that the mean of these bootstrap sample means is near 3.68 grams, very close to the mean of the original sample: 3.682 grams. Our intention is not to study the distribution of the bootstrap samples, but rather to use them to estimate population values, such as the population mean. In the next section, we discuss how can we use these bootstrap samples to construct *confidence intervals*.\n\n:::{.learncheck}\n**Learning Check**\n\n**(LC8.10)** What is the chief difference between a bootstrap distribution and a sampling distribution?\n\n**(LC8.11)** Looking at the bootstrap distribution for the sample mean in @fig-one-thousand-sample-means, between what two values would you say *most* values lie?\n\n**(LC8.12)** Which of the following is true about the confidence level when constructing a confidence interval?\n\n- A. The confidence level determines the width of the interval and affects how likely it is to contain the population parameter.\n- B. The confidence level is always fixed at 95% for all statistical analyses involving confidence intervals.\n- C. A higher confidence level always results in a narrower confidence interval, making it more useful for practical purposes.\n- D. The confidence level is only relevant when the population standard deviation is known.\n\n**(LC8.13)** How does increasing the sample size affect the width of a confidence interval for a given confidence level?\n\n- A. It increases the width of the confidence interval, making it less precise.\n- B. It has no effect on the width of the confidence interval since the confidence level is fixed.\n- C. It decreases the width of the confidence interval, making it more precise by reducing the margin of error.\n- D. It changes the confidence level directly, regardless of other factors.\n\n:::\n\n### Confidence intervals and the bootstrap: original workflow {#sec-bootstrap-process}\n\n\nThe process of determining bootstrap samples and using them for *estimation* is called *bootstrapping*. \\index{bootstrapping!statistical reference}\nWe can estimate population parameters such as the mean, median, or standard deviation. We can also construct confidence intervals.\n\nIn this subsection, we focus on the latter and construct confidence intervals based on bootstrap samples. For this, we review the R syntax and workflow we have already used in previous sections and also introduce a new package: the `infer` package for tidy and transparent statistical inference. \n\n#### Original workflow {.unnumbered}\n\nRecall that we took bootstrap samples, then calculated the sample means from these samples. Let's revisit the original workflow using `dplyr` verbs and the `|>` operator.\n\nFirst, we use `rep_sample_n()` to resample from the original sample `almonds_sample_100` of 5000 almonds. We set  ``size = 100 `` to generate bootstrap samples of the same size as the original sample, and we resample with replacement by setting `replace = TRUE`. We create 1000 bootstrap samples by setting ``reps = 1000 ``:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |> \n  rep_sample_n(size = 100, replace = TRUE, reps = 1000)\n```\n:::\n\n\nSecond, we add another pipe followed by `summarize()` to compute the sample `mean()` weight for each `replicate`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |> \n  rep_sample_n(size = 100, replace = TRUE, reps = 1000) |> \n  summarize(mean_weight = mean(weight))\n```\n:::\n\n\nFor this simple case, all we needed was to use the `rep_sample_n()` function and a `dplyr` verb. However, using only `dplyr` verbs provides us with a limited set of tools that is not ideal when working with more complicated situations. This is the reason we introduce the `infer` package.\n\n\n### The `infer` package workflow: {#sec-infer-workflow}\n\nThe `infer` package is an R package for statistical inference. It makes efficient use of the `|>` pipe operator we introduced in @sec-piping to spell out the sequence of steps necessary to perform statistical inference in a \"tidy\" and transparent fashion.\\index{operators!pipe} Just as the `dplyr` package provides functions with verb-like names to perform data wrangling, the `infer` package provides functions with intuitive verb-like names to perform statistical inference, such as constructing confidence intervals or performing hypothesis testing. We have discussed the theory-based implementation of the former in @sec-CI-general and we introduce the latter in @sec-hypothesis-testing.\n\nUsing the example of almonds' weights, we introduce `infer` first by comparing its implementation with `dplyr`. Recall that to calculate a sample statistic or point estimate from a sample, such as the sample mean, when using `dplyr` we use `summarize()` and `mean()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |> \n  summarize(stat = mean(weight))\n```\n:::\n\n\nIf we want to use `infer` instead, we use the functions `specify()` and `calculate()`\\index{R packages!infer!observed statistic shortcut} as shown:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |> \n  specify(response = weight) |> \n  calculate(stat = \"mean\")\n```\n:::\n\n\nThe new structure using `infer` seems slightly more complicated than the one using `dplyr` for this simple calculation. These functions will provide three chief benefits moving forward.\n\n- First, the `infer` verb names better align with the overall simulation-based framework you need to understand to construct confidence intervals and to conduct hypothesis tests (in @sec-hypothesis-testing). We will see flowchart diagrams of this framework in the upcoming @fig-infer-workflow-ci and in @sec-hypothesis-testing with @fig-htdowney.\n\n- Second, you can transition seamlessly between confidence intervals and hypothesis testing with minimal changes to your code. This becomes apparent in @sec-comparing-infer-workflows when we compare the `infer` code for both of these inferential methods.\n\n- Third, the `infer` workflow is much simpler for conducting inference when you have *more than one variable*. We introduce *two-sample* inference\\index{two-sample inference} where the sample data is collected from two groups, such as in @sec-case-study-two-prop-ci where we study the contagiousness of yawning and in @sec-ht-activity where we compare the popularity of music genres. Then in @sec-infer-regression, we see situations of *inference for regression* using the regression models you fit in @sec-regression. \n\nWe now illustrate the sequence of verbs necessary to construct a confidence interval for $\\mu$, the population mean weight of almonds.\n\n#### 1. `specify` variables {.unnumbered}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Diagram of the specify() verb.](images/flowcharts/infer/specify.png){#fig-infer-specify fig-align='center' width=40%}\n:::\n:::\n\n\nAs shown in @fig-infer-specify, the `specify()` \\index{R packages!infer!specify()} function is used to choose which variables in a data frame are the focus of our statistical inference. We do this by `specify`ing the `response` argument. For example, in our `almonds_sample_100` data frame of the 100 almonds sampled from the bowl, the variable of interest is `weight`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |> \n  specify(response = weight)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: weight (numeric)\n# A tibble: 100 × 1\n   weight\n    <dbl>\n 1    4.2\n 2    4.2\n 3    3.9\n 4    3.8\n 5    3.3\n 6    3.5\n 7    4  \n 8    3.5\n 9    4.2\n10    4.1\n# ℹ 90 more rows\n```\n\n\n:::\n:::\n\n\nNotice how the data itself does not change, but the `Response: weight (numeric)` *meta-data* does\\index{meta-data}. This is similar to how the `group_by()` verb from `dplyr` doesn't change the data, but only adds \"grouping\" meta-data, as we saw in @sec-groupby.\n\nWe can also specify which variables are the focus of the study by introducing a `formula = y ~ x` in `specify()`. This is the same formula notation you saw in @sec-regression and @sec-multiple-regression on regression models: the response variable `y` is separated from the explanatory variable `x` by a `~` (\"tilde\"). The following use of `specify()` with the `formula` argument yields the same result seen previously:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |> \n  specify(formula = weight ~ NULL)\n```\n:::\n\n\nIn the case of almonds we only have a response variable and no explanatory variable of interest. Thus, we set the `x` on the right-hand side of the `~` to be `NULL`. \n\nIn cases where inference is focused on a single sample, as it is the almonds' weights example, either specification works. In the examples we present in later sections, the `formula` specification is simpler and more flexible. In particular, this comes up in the upcoming @sec-case-study-two-prop-ci on comparing two proportions and @sec-infer-regression on inference for regression.\n\n#### 2. `generate` replicates {.unnumbered}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Diagram of generate() replicates.](images/flowcharts/infer/generate.png){#fig-infer-generate fig-align='center' width=40%}\n:::\n:::\n\n\nAfter we `specify()` the variables of interest, we pipe the results into the `generate()` function to generate replicates. This is the function that produces the bootstrap samples or performs the similar resampling process a large number of times, based on the variable(s) specified previously, as shown in @fig-infer-generate. Recall we did this 1000 times.\n\nThe `generate()` \\index{R packages!infer!generate()} function's first argument is `reps`, which sets the number of replicates we would like to generate. Since we want to resample the 100 almonds in `almonds_sample_100` with replacement 1000 times, we set ``reps = 1000 ``. \n\nThe second argument `type` determines the type of computer simulation used. Setting this to `type = \"bootstrap\"` produces bootstrap samples using resampling with replacement. We present different options for `type` in @sec-hypothesis-testing. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |> \n  specify(response = weight) |> \n  generate(reps = 1000, type = \"bootstrap\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: weight (numeric)\n# A tibble: 100,000 × 2\n# Groups:   replicate [1,000]\n   replicate weight\n       <int>  <dbl>\n 1         1    3.6\n 2         1    3.4\n 3         1    4.2\n 4         1    3.4\n 5         1    3.5\n 6         1    3.4\n 7         1    3.8\n 8         1    3.7\n 9         1    4.1\n10         1    3.4\n# ℹ 99,990 more rows\n```\n\n\n:::\n:::\n\n\nObserve that the resulting data frame has 100,000 rows. This is because we have found 1000 bootstrap samples, each with 100 rows.\n\nThe variable `replicate` indicates the bootstrap sample each row belongs to, from `1` to 1000, each replicate repeated 100 times. The default value of the `type` argument is `\"bootstrap\"` in this scenario, so the inclusion was only made for completeness. If the last line was written simply as ``generate(reps = 1000)``, the result would be the same. \n\n**Comparing with original workflow**: Note that the steps of the `infer` workflow so far produce the same results as the original workflow using the `rep_sample_n()` function we saw earlier. In other words, the following two code chunks produce similar results:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# infer workflow:                   # Original workflow:\nalmonds_sample_100 |>               almonds_sample_100 |> \n  specify(response = weight) |>        rep_sample_n(size = 100, replace = TRUE, \n  generate(reps = 1000)                             reps = 1000)              \n```\n:::\n\n\n#### 3. `calculate` summary statistics {.unnumbered}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Diagram of calculate() summary statistics.](images/flowcharts/infer/calculate.png){#fig-infer-calculate fig-align='center' width=50%}\n:::\n:::\n\n\nAfter we `generate()` 1000 bootstrap samples, we want to summarize each of them, for example, by calculating the sample mean of each one of them. As @fig-infer-calculate shows, the `calculate()` \\index{R packages!infer!calculate()} function does this.\n\nIn our example, we calculate the mean `weight` for each bootstrap sample by setting the `stat` argument equal to `\"mean\"` inside the `calculate()` function. The `stat` argument can be used for other common summary statistics such as `\"median\"`, `\"sum\"`, `\"sd\"` (standard deviation), and `\"prop\"` (proportion). To see a list of other possible summary statistics you can use, type `?calculate` and read the help file.\n\nLet's save the result in a data frame called `bootstrap_means` and explore its contents:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbootstrap_means <- almonds_sample_100 |> \n  specify(response = weight) |> \n  generate(reps = 1000) |> \n  calculate(stat = \"mean\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting `type = \"bootstrap\"` in `generate()`.\n```\n\n\n:::\n\n```{.r .cell-code}\nbootstrap_means\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: weight (numeric)\n# A tibble: 1,000 × 2\n   replicate  stat\n       <int> <dbl>\n 1         1 3.68 \n 2         2 3.688\n 3         3 3.632\n 4         4 3.68 \n 5         5 3.679\n 6         6 3.675\n 7         7 3.678\n 8         8 3.706\n 9         9 3.643\n10        10 3.68 \n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\nObserve that the resulting data frame has 1000 rows and 2 columns corresponding to the 1000 `replicate` values. It also has the mean weight for each bootstrap sample saved in the variable `stat`. \n\n**Comparing with original workflow**: You may have recognized at this point that the `calculate()` step in the `infer` workflow produces the same output as the `summarize()` step in the original workflow.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# infer workflow:                   # Original workflow:\nalmonds_sample_100 |>                  almonds_sample_100 |> \n  specify(response = weight) |>        rep_sample_n(size = 100, replace = TRUE, \n  generate(reps = 1000) |>                          reps = 1000) |>              \n  calculate(stat = \"mean\")             summarize(stat = mean(weight))\n```\n:::\n\n\n#### 4. `visualize` the results {.unnumbered}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Diagram of visualize() results.](images/flowcharts/infer/visualize.png){#fig-infer-visualize fig-align='center' width=60%}\n:::\n:::\n\n\nThe `visualize()` \\index{R packages!infer!visualize()} verb provides a quick way to visualize the bootstrap distribution as a histogram of the numerical `stat` variable's values as shown in @fig-bootstrap-distribution-infer. The pipeline of the main `infer` verbs used for exploring bootstrap distribution results is shown in @fig-infer-visualize.  \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvisualize(bootstrap_means)\n```\n\n::: {.cell-output-display}\n![Bootstrap distribution.](08-confidence-intervals_files/figure-html/fig-bootstrap-distribution-infer-1.png){#fig-bootstrap-distribution-infer fig-align='center' width=\\textwidth}\n:::\n:::\n\n\n**Comparing with original workflow**: In fact, `visualize()` is a *wrapper function* for the `ggplot()` function that uses a `geom_histogram()` layer. Recall that we illustrated the concept of a wrapper function in @fig-moderndive-figure-wrapper in @sec-model1table.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# infer workflow:                    # Original workflow:\nvisualize(bootstrap_means)           ggplot(bootstrap_means, aes(x = stat)) +\n                                        geom_histogram()\n```\n:::\n\n\nThe `visualize()` function can take many other arguments to customize the plot further. In later sections, we take advantage of this flexibility. In addition, it works with helper functions to add shading of the histogram values corresponding to the confidence interval values.\nWe have introduced the different elements of the `infer` workflow for constructing a bootstrap distribution and visualizing it. A summary of these steps is presented in @fig-infer-workflow-ci.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![infer package workflow for confidence intervals.](images/flowcharts/infer/ci_diagram.png){#fig-infer-workflow-ci fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n### Confidence intervals using bootstrap samples with `infer` {#sec-conf-int-infer}\n\nWe are ready to introduce confidence intervals using the bootstrap via `infer`. We present two different methods for constructing 95% confidence intervals as interval estimates of an unknown population parameter: the *percentile method*\\index{Bootstrap!percentile method} and the *standard error method*{Bootstrap!standard error method}. Let's now check out the `infer` package code that explicitly constructs these. There are also some additional neat functions to visualize the resulting confidence intervals built-in to the `infer` package.\n\n\n#### Percentile method {#sec-percentile-method-infer .unnumbered}\n\nRecall that in @sec-infer-workflow we have generated 1000 bootstrap samples and stored them in data frame `bootstrap_means`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbootstrap_means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: weight (numeric)\n# A tibble: 1,000 × 2\n   replicate  stat\n       <int> <dbl>\n 1         1 3.68 \n 2         2 3.688\n 3         3 3.632\n 4         4 3.68 \n 5         5 3.679\n 6         6 3.675\n 7         7 3.678\n 8         8 3.706\n 9         9 3.643\n10        10 3.68 \n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\nThe sample means stored in `bootstrap_means` represent a good approximation to the bootstrap distribution of all possible bootstrap samples. The percentile method for constructing 95% confidence intervals sets the lower endpoint of the confidence interval at the 2.5th percentile of `bootstrap_means` and similarly sets the upper endpoint at the 97.5th percentile. The resulting interval captures the middle 95% of the values of the sample mean weights of almonds in `bootstrap_means`. This is the interval estimate of the population mean weight of almonds in the entire bowl.\n\nWe can compute the 95% confidence interval by piping `bootstrap_means` into the `get_confidence_interval()` \\index{R packages!infer!get\\_confidence\\_interval()} function from the `infer` package, with the confidence `level` set to 0.95 and the confidence interval `type` to be `\"percentile\"`. We save the results in `percentile_ci`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npercentile_ci <- bootstrap_means |> \n  get_confidence_interval(level = 0.95, type = \"percentile\")\npercentile_ci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1  3.61198    3.756\n```\n\n\n:::\n:::\n\n\nAlternatively, we can visualize the interval (3.61, 3.76) by piping the `bootstrap_means` data frame into the `visualize()` function and adding a `shade_confidence_interval()` \\index{R packages!infer!shade\\_confidence\\_interval()} layer. We set the `endpoints` argument to be `percentile_ci`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvisualize(bootstrap_means) + \n  shade_confidence_interval(endpoints = percentile_ci)\n```\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Percentile method 95% confidence interval shaded corresponding to potential values.](08-confidence-intervals_files/figure-html/fig-percentile-ci-viz-1.png){#fig-percentile-ci-viz fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nObserve in @fig-percentile-ci-viz that 95% of the sample means stored in the `stat` variable in `bootstrap_means` fall between the two endpoints marked with the darker lines, with 2.5% of the sample means to the left of the shaded area and 2.5% of the sample means to the right. You also have the option to change the colors of the shading using the `color` and `fill` arguments. \n\nThe `infer` package has incorporated a shorter named function `shade_ci()` that produces the same results. Try out the following code:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvisualize(bootstrap_means) + \n  shade_ci(endpoints = percentile_ci, color = \"hotpink\", fill = \"khaki\")\n```\n:::\n\n\n\n\n\n\n#### Standard error method {#sec-se-infer .unnumbered}\n\n\nIn @sec-CI-general we introduced theory-based confidence intervals. We show that a 95% confidence interval can be constructed as\n\n$$\\left(\\overline{x} - 1.96 \\cdot SE(\\bar x), \\quad \\overline{x} + 1.96 \\cdot SE(\\bar x)\\right)$$\n\nwhere $\\overline{x}$ is the sample mean of the original sample, 1.96 is the number of standard errors around the mean needed to account for 95% of the area under the density curve (when the distribution is normal), and $SE(\\bar x)$ is the standard error of the sample mean that can be computed as $\\sigma /\\sqrt{n}$ if the population standard deviation is known, or estimated as $s/\\sqrt{n}$ if we have to use the sample standard deviation, $s$, and the sample size, $n$.\n\nWe use the same structure to construct confidence intervals but using the bootstrap sample means to estimate the standard error of $\\overline{x}$.\nThus, the 95% confidence interval for the population mean, $\\mu$, using the standard error estimated via bootstrapping, $SE_\\text{boot}$, is:\n\n$$\\left(\\overline{x} - 1.96 \\cdot SE_{\\text{boot}}, \\quad \\overline{x} + 1.96 \\cdot SE_{\\text{boot}}\\right)$$\n\nWe can compute this confidence interval using `dplyr`. First, we calculate the estimated standard error:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSE_boot <- bootstrap_means |>\n  summarize(SE = sd(stat)) |>\n  pull(SE)\nSE_boot\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03566146\n```\n\n\n:::\n:::\n\n\nand then use the original sample mean to calculate the 95% confidence interval:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalmonds_sample_100 |>\n  summarize(lower_bound = mean(weight) - 1.96 * SE_boot,\n            upper_bound = mean(weight) + 1.96 * SE_boot)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_bound upper_bound\n        <dbl>       <dbl>\n1     3.61210     3.75190\n```\n\n\n:::\n:::\n\n\nAlternatively, computation of the 95% confidence interval can once again be done via `infer`. We find the sample mean of the original sample and store it in variable `x_bar`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx_bar <- almonds_sample_100 |> \n  specify(response = weight) |> \n  calculate(stat = \"mean\")\nx_bar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: weight (numeric)\n# A tibble: 1 × 1\n   stat\n  <dbl>\n1 3.682\n```\n\n\n:::\n:::\n\n\nNow, we pipe the `bootstrap_means` data frame we created into the `get_confidence_interval()` function. We set the `type` argument to be `\"se\"` and specify the `point_estimate` argument to be `x_bar` in order to set the center of the confidence interval to the sample mean of the original sample.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstandard_error_ci <- bootstrap_means |> \n  get_confidence_interval(type = \"se\", point_estimate = x_bar, level = 0.95)\nstandard_error_ci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1  3.61210  3.75190\n```\n\n\n:::\n:::\n\n\nThe results are the same whether `dplyr` or `infer` is used, but as explained earlier, the latter provides more flexibility for other tests.\n\nIf we would like to visualize the interval (3.61, 3.75), we can once again pipe the `bootstrap_means` data frame into the `visualize()` function and add a `shade_confidence_interval()` layer to our plot. We set the `endpoints` argument to be `standard_error_ci`. The resulting standard-error method based on a 95% confidence interval for $\\mu$ can be seen in @fig-se-ci-viz.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvisualize(bootstrap_means) + \n  shade_confidence_interval(endpoints = standard_error_ci)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Standard-error method 95% confidence interval.](08-confidence-intervals_files/figure-html/fig-se-ci-viz-1.png){#fig-se-ci-viz fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nBecause we are using bootstrap samples to construct these intervals, we call the percentile and standard error methods simulation-based methods. We can compare the 95% confidence intervals from using both simulation-based methods as well as the one attained using the theory-based method described in @sec-CI-general:\n\n* Percentile method: (3.61, 3.76)\n* Standard error method: (3.61, 3.75)\n* Theory-based method: (3.61, 3.76)\n\n\n<!--\n#### Percentile-$t$ method {#sec-infer-percentile-t .unnumbered}\n\nIt requires adding a type to generate or calculate, to allow for finding the t at each step without hypothesis\nAdvantage: Simplest and easiest to compute\nDisadvantage: Only works for estimators where the sample standard deviation can be computed directly.\n-->\n\n\n<!--\n#### Bias-corrected and accelerated, BCa, method {#sec-bca .unnumbered}\n-->\n\n\n\n:::{.learncheck}\n**Learning Check**\n\n**(LC8.14)** Construct a 95% confidence interval for the *median* weight of *all* almonds with the percentile method. Is it appropriate to also use the standard-error method?\n\n**(LC8.15)** What are the advantages of using `infer` for building confidence intervals?\n\n**(LC8.16)** What is the main purpose of bootstrapping in statistical inference?\n\n- A. To visualize data distributions and identify outliers.\n- B. To generate multiple samples from the original data for estimating parameters.\n- C. To replace missing data points with the mean of the dataset.\n- D. To validate the assumptions of a regression model.\n\n**(LC8.17)** \"Which function denotes the variables of interest for inference?\"\n\n- A. `rep_sample_n()`\n- B. `calculate()`\n- C. `specify()`\n- D. `visualize()`\n\n**(LC8.18)** What is a key difference between the percentile method and the standard error method for constructing confidence intervals using bootstrap samples?\n\n- A. The percentile method requires the population standard deviation.\n- B. The percentile method uses the middle 95% of bootstrap statistics, while the standard error method relies on the estimated standard error.\n- C. The standard error method always results in a narrower confidence interval.\n- D. The percentile method requires more bootstrap samples.\n\n:::\n\n## Additional remarks about the bootstrap {#sec-boot-remarks}\n\nThis section expands explanations on the bootstrap methods, provides some \nhistorical context, gives a comparison between the theory-based approach and the simulation-based approach when working with confidence intervals, and provides\nreasons for using the bootstrap. The presentation is more \ntheoretical than other sections in this chapter, and you are welcome to skip to \n@sec-case-study-two-prop-ci if you want to go over directly another\napplication of the bootstrap methods in R. Additional theoretical explanations\nare available in the [Appendices of the online version of the book](https://moderndive.com/v2/appendixa).\n\n### The bootstrap and other resampling methods\n\nThe bootstrap is one of many resampling methods. Chernick and LaBudde noted that\nthe bootstrap's roots trace back to the development of similar techniques like permutations \nand the jackknife [@Chernick2011].\nThe bootstrap was initially conceived as an approximation to another \nresampling method called *the jackknife*\\index{jackknife} but quickly gained \nrecognition for its broader applicability and efficiency.\nSince then, it has been shown in multiple contexts that the bootstrap performs \nat least as well as traditional methods in estimating standard errors, \nconstructing confidence intervals, performing hypothesis testing, and many other \nstatistical techniques.\n\nFurthermore, since the 1980s (but even more in the last two decades), the use of \nsimulations to compare advanced \nbootstrap methods against other techniques, such as cross-validation, further \nestablished its superiority in specific contexts, particularly when dealing with \nsmall sample sizes. \nThe use of the bootstrap and bootstrap-related methods has become a cornerstone \nin modern statistical and data science practices.\n\nIn this section, we introduce additional details about the bootstrap, and \nexplain the advantages and limitations of using the bootstrap.\n\n### Confidence intervals and rate of convergence {#sec-rate-convergence}\n\nWe want to compare how the bootstrap performs when building confidence intervals \nwith respect to the theory-based approach discussed in @sec-theory-based-CI. \nThe formal comparison requires mathematical concepts beyond the scope of this \nbook, and it is not pursued here. Instead, we provide just enough elements to \nhelp you with the intuition of how this \ncomparison is made and why bootstrap-related methods can be as strong as or even \nstronger than theory-based or alternative methods.\n\nLet's start with an illustration using the theory-based confidence interval. \nA 95% confidence interval for $\\mu$, when a sample of size $n = 100$ is used, \nis given by\n\n$$\\overline{x} \\pm 1.96 \\frac{\\sigma}{\\sqrt{n}}$$\n  \n  when $\\sigma$ is unknown or\n\n$$\\overline{x} \\pm 1.98 \\frac{s}{\\sqrt{n}}$$\n  \nwhen $\\sigma$ is unknown. We use 95% and $n = 100$ for this illustration, but \nthe exposition is also true with any other confidence level or other \nsample sizes.\nWe understand that 95% of all the possible samples would lead to an interval that \ncontains $\\mu$. \nThis statement is exactly true if the distribution of $\\overline X$ is precisely normal, \nand we say that 95% is the *true coverage probability*\\index{Confidence interval!true coverage probability}. \nIn reality, we do not know what is the distribution of the population, \nbut because of the Central Limit Theorem we know that for a large sample size \n$n$ the distribution of $\\overline X$ is *approximately* normal. \nIn this case, the 95% is an *approximate coverage probability*\\index{Confidence interval!approximate coverage probability}.\nThis means that if we were to take every possible sample of size $n$ and \nconstruct a confidence interval using the formulas above, not exactly 95% of the \nintervals will include $\\mu$.\nAgain, this happens because $\\overline X$ is not exactly, but approximately,\nnormal. \nStill, the Central Limit Theorem states that when $n$ tends to infinity, \nthe distribution of $\\overline X$ tends to normal, so the \nlarger the sample size $n$ the closer the distribution of $\\overline X$ is to \nthe normal distribution, and the smaller the difference between the true and the \napproximate coverage probability.\n\nGiven that we can never make $n$ infinity in real-life applications, we would \nlike to produce 95% confidence intervals that make the difference \nbetween the *approximate coverage probability* and the \n*true coverage probability* as small as possible when we increase the sample \nsize of our sample.\nImagine a sequence of sample sizes $n_1, n_2, n_3,\\dots$ that gets bigger \nand bigger and bigger. The rate at which the corresponding consecutive differences \nin confidence intervals' coverage probability decreases is called the \n*rate of convergence*\\index{Confidence interval!rate of convergence} of the difference between \napproximate and true coverage probabilities. \n\nIn the case of a 95% confidence interval for $\\mu$ using the theory-based \napproach, the rate of convergence for the difference is about $1/\\sqrt{n}$.\nThis means that if we increase $n$ from 100 to 400, the difference between the\napproximate and true coverage goes down from a factor of  $1/\\sqrt{100} = 0.1$ \n  to a factor of $1/\\sqrt{400} = 0.05$. Thus, increasing $n$ four times leads to a \ndecrease of the difference of about two times. In the statistical literature, a method that has this rate \nof convergence is called a *first-order correct*\\index{Confidence interval!first-order-correct} [@Hall1992] \nor *first-order accurate*\\index{Confidence Interval!first-order-accurate} [@Chernick2011].\n\nThe bootstrap percentile method discussed in @sec-conf-int-infer, in the case \nof a 95% confidence interval for $\\mu$, is also first-order accurate. \nThus, confidence intervals calculated using the theory-based and the bootstrap percentile method are comparable. \nThis is consistent with the results we obtained earlier in this chapter.\n\nIn general, if you have two different methods that produce similar 95% confidence intervals and \nwe need to choose one of them, we would choose the one that has a faster rate of \nconvergence. As we discuss in the next subsection, other bootstrap methods have, \nin certain contexts, faster rates of convergence.\n\n\n\n### Why bootstrap methods\n\nWhy is it suitable to learn and use bootstrap \nmethods for confidence intervals? The most important reason is that bootstrap \nmethods, in particular advanced bootstrap methods, can deal with many \nlimitations of the theory-based approach. Let's discuss three of these limitations.\n\nFirst, a 95% confidence interval for $\\mu$ is appropriate if the population \ndistribution is not too extreme and the sample size is large enough for the \ndistribution of $\\overline X$ to be approximately normal. \nBut there are situations where these conditions are not satisfied, for example, \nif the population distribution is heavily skewed to the right, as in the case of \nincome or wealth; or the distribution is constructed from only two values \n(1 or 0) but the chances of getting zero are \nmuch greater than the ones of getting one (for example, chance of getting zero \nis 0.999 and chance of getting 1 is 0.001) as it is the case in lottery outcomes \nor the presence of some disease in a population. \nWhen these situations are present, the confidence intervals would be inaccurate \nbecause the sample mean $\\overline X$ is biased when $n$ is not too large. \nThis means that if you were to take a large number of random samples and \nconstruct the sample mean of these samples, their average will\nbe clearly different than $\\mu$, breaking down the theory we developed in \n@sec-theory-based-CI. This problem may be fixed if the\nsample size is large, but, depending on how extreme the population distribution \nis, the sample size may need to be extremely large; perhaps in \nthe order of thousands, or tens of thousands, or even more. Getting samples of \nthose sizes may not be doable in real-life situations.\n\nSecond, in this chapter, we have study confidence intervals for the population \nmean $\\mu$, because it is a fundamental quantity and it is the foundation for \nother cases. However, building confidence intervals for other parameters using \nthe theory-based approach (for example, for the median, the first quartile, \nthe standard deviation, etc.) becomes more complicated or even unfeasible.\n\nThird, when working with estimators more complicated than \n$\\overline X$, it is often not possible to derive the standard\nerror estimator with a formula as clean as $\\sigma/\\sqrt{n}$. Sometimes, there\nis no formula for the standard error and alternative methods have to be used to \nestimate it. This can create an additional source of bias. When bias is present, \nthe confidence intervals created using the theory-based approach in @sec-CI-general could be suspect, even completely useless.\n\nThe bootstrap percentile method is not affected directly by the second and third \nlimitations. It can be implemented for any other parameter beyond the population \nmean, as long as all the information needed can be extracted from each bootstrap \nsample. On the other hand, the first limitation listed above can also affect the\naccuracy of this method. \n\nFortunately, since the inception of the bootstrap, many \nimprovements have been made to the percentile method. Bootstrap methods have \nbeen proposed that address the presence of bias either by the limitations discussed above \nor the bias created when obtaining estimators or incorporating these methods. \nIn addition, in certain contexts, these methods also improve the rate of convergence \nof the difference between the approximate and true coverage probability.\nSome of these methods are the percentile-$t$ and the Bias Correction and \nAcceleration bootstrap method (BCa). In terms of rates of convergence, these methods are\n*second-order accurate*\\index{Confidence interval!second-order accurate}; that is, they have a rate \nof convergence of about $1/n$. Another method called the double bootstrap (or more generally, \nthe iterated bootstrap) can even be a *third-order accurate*.\n\nWe have not included these methods directly here because the theory that \njustifies them goes beyond the scope of this book and, when dealing with \nconfidence intervals for $\\mu$ from populations with distributions that are not\nextreme, there are not real gains in using them over the theory-based approach \nor the percentile method. (We encourage you to check out one implementation of\nbias-corrected confidence intervals in the `infer` package by setting\n`type = \"bias-corrected\"` in the `get_confidence_interval()` \n\\index{R packages!infer!get\\_confidence\\_interval()!bias-corrected type} function.)\n\nTo summarize, when working with skewed \ndistributions, small sample sizes, estimators of parameters other than $\\mu$ \n(such as the median), or the estimation of the standard error when there are no\nformulas to obtain them, many advanced bootstrap methods would be preferred over \nthe theory-based approach. In the Appendices of the online version of the book, \nwe plan to explore some of these advanced methods and present simulations \nthat show when these methods are preferred over the percentile method or the \ntheory-based approach.\n\n\n## Case study: is yawning contagious? {#sec-case-study-two-prop-ci}\n\nLet's apply our knowledge of confidence intervals to answer the question: \"Is yawning contagious?\". If you see someone else yawn, are you more likely to yawn? In an episode of the US show *Mythbusters* that aired on Discovery, the hosts conducted an experiment to answer this question. More information about the episode is available on [IMDb](https://www.imdb.com/title/tt0768479/).\n\n### *Mythbusters* study data\n\nFifty adult participants who thought they were being considered for an appearance on the show were interviewed by a show recruiter. In the interview, the recruiter either yawned or did not. Participants then sat by themselves in a large van and were asked to wait. While in the van, the *Mythbusters* team watched the participants using a hidden camera to see if they yawned. The data frame containing the results of their experiment is available as `mythbusters_yawn` included in the `moderndive` package: \\index{R packages!moderndive!mythbusters\\_yawn}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmythbusters_yawn\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 50 × 3\n    subj group   yawn \n   <int> <chr>   <chr>\n 1     1 seed    yes  \n 2     2 control yes  \n 3     3 seed    no   \n 4     4 seed    yes  \n 5     5 seed    no   \n 6     6 control no   \n 7     7 seed    yes  \n 8     8 control no   \n 9     9 control no   \n10    10 seed    no   \n# ℹ 40 more rows\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nThe variables are:\n\n- `subj`: The participant ID with values 1 through 50.\n- `group`: A binary *treatment* variable indicating whether the participant was exposed to yawning. `\"seed\"` indicates the participant was exposed to yawning while `\"control\"` indicates the participant was not. \n- `yawn`: A binary *response* variable indicating whether the participant ultimately yawned.\n\nRecall that you learned about treatment and response variables in @sec-correlation-is-not-causation in our discussion on confounding variables. \\index{variables!treatment}\\index{variables!response}\n\nLet's use some data wrangling to calculate counts of the four possible outcomes:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmythbusters_yawn |> \n  group_by(group, yawn) |> \n  summarize(count = n(), .groups = \"keep\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n# Groups:   group, yawn [4]\n  group   yawn  count\n  <chr>   <chr> <int>\n1 control no       12\n2 control yes       4\n3 seed    no       24\n4 seed    yes      10\n```\n\n\n:::\n:::\n\n\nLet's first focus on the `\"control\"` group participants who were not exposed to yawning. 12 such participants did not yawn, while 4 such participants did. So out of the 16 people who were not exposed to yawning, 4/16 = 0.25 = 25% did yawn. \n\nLet's now focus on the `\"seed\"` group participants who were exposed to yawning where 24 such participants did not yawn, while 10 such participants did yawn. So out of the 34 people who were exposed to yawning, 10/34 = 0.294 = 29.4% did yawn. Comparing these two percentages, the participants who were exposed to yawning yawned 29.4% - 25% = 4.4% more often than those who were not.\n\n\n### Sampling scenario\n\nLet's review the terminology and notation related to sampling we studied in @sec-terminology-and-notation. In @sec-sampling, our *study population* was the bowl of $N$ = 2400 balls. Our *population parameter* of interest was the *population proportion* of these balls that were red, denoted mathematically by $p$. In order to estimate $p$, we extracted a sample of 50 balls using the shovel and computed the relevant *point estimate*: the *sample proportion* that were red, denoted mathematically by $\\widehat{p}$.\n\nWho is the study population here? All humans? All the people who watch the show *Mythbusters*? It's hard to say! This question can only be answered if we know how the show's hosts recruited participants! In other words, what was the *sampling methodology*\\index{sampling methodology} used by the *Mythbusters* to recruit participants? We alas are not provided with this information. Only for the purposes of this case study, however, we'll *assume* that the 50 participants are a representative sample of all Americans given the popularity of this show. Thus, we'll be assuming that any results of this experiment will generalize to all $N$ = 346 million Americans (2024 population estimate). \n\nJust like with our sampling bowl, the population parameter here will involve proportions. However, in this case, it will be the *difference in population proportions* $p_{seed} - p_{control}$, where $p_{seed}$ is the proportion of *all* Americans who if exposed to yawning will yawn themselves, and $p_{control}$ is the proportion of *all* Americans who if not exposed to yawning still yawn themselves. Correspondingly, the point estimate/sample statistic based on the *Mythbusters*' sample of participants will be the *difference in sample proportions* $\\widehat{p}_{seed} - \\widehat{p}_{control}$. Let's extend @tbl-table-ch8-c of scenarios of sampling for inference to include our latest scenario. \n\n\n::: {#tbl-table-ch8-c .cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"font-size: 16px; margin-left: auto; margin-right: auto;\">\n<caption style=\"font-size: initial !important;\">Scenarios of sampling for inference</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> Scenario </th>\n   <th style=\"text-align:left;\"> Population parameter </th>\n   <th style=\"text-align:left;\"> Notation </th>\n   <th style=\"text-align:left;\"> Point estimate </th>\n   <th style=\"text-align:left;\"> Symbol(s) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;width: 0.5in; \"> 1 </td>\n   <td style=\"text-align:left;width: 1.5in; \"> Population proportion </td>\n   <td style=\"text-align:left;width: 0.65in; \"> $p$ </td>\n   <td style=\"text-align:left;width: 1.6in; \"> Sample proportion </td>\n   <td style=\"text-align:left;width: 0.65in; \"> $\\widehat{p}$ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;width: 0.5in; \"> 2 </td>\n   <td style=\"text-align:left;width: 1.5in; \"> Population mean </td>\n   <td style=\"text-align:left;width: 0.65in; \"> $\\mu$ </td>\n   <td style=\"text-align:left;width: 1.6in; \"> Sample mean </td>\n   <td style=\"text-align:left;width: 0.65in; \"> $\\overline{x}$ or $\\widehat{\\mu}$ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;width: 0.5in; \"> 3 </td>\n   <td style=\"text-align:left;width: 1.5in; \"> Difference in population proportions </td>\n   <td style=\"text-align:left;width: 0.65in; \"> $p_1 - p_2$ </td>\n   <td style=\"text-align:left;width: 1.6in; \"> Difference in sample proportions </td>\n   <td style=\"text-align:left;width: 0.65in; \"> $\\widehat{p}_1 - \\widehat{p}_2$ </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nThis is known as a *two-sample* inference\\index{two-sample inference} situation since we have two separate samples. Based on their two-samples of size $n_{seed}$ = 34 and $n_{control}$ = 16, the point estimate is\n\n$$\n\\widehat{p}_{seed} - \\widehat{p}_{control} = \\frac{24}{34} - \\frac{12}{16} = 0.04411765 \\approx 4.4\\%\n$$\n\nHowever, say the *Mythbusters* repeated this experiment. In other words, say they recruited 50 new participants and exposed 34 of them to yawning and 16 not. Would they find the exact same estimated difference of 4.4%? Probably not, again, because of *sampling variation*. \n\nHow does this sampling variation affect their estimate of 4.4%? In other words, what would be a plausible range of values for this difference that accounts for this sampling variation? We can answer this question with confidence intervals! Furthermore, since the *Mythbusters* only have a single two-sample of 50 participants, they would have to construct a 95% confidence interval for $p_{seed} - p_{control}$ using *bootstrap resampling with replacement*.\n\nWe make a couple of important notes. First, for the comparison between the `\"seed\"` and `\"control\"` groups to make sense, however, both groups need to be *independent* from each other. Otherwise, they could influence each other's results. This means that a participant being selected for the `\"seed\"` or `\"control\"` group has no influence on another participant being assigned to one of the two groups. As an example, if there were a mother and her child as participants in the study, they wouldn't necessarily be in the same group. They would each be assigned randomly to one of the two groups of the explanatory variable.\n\nSecond, the order of the subtraction in the difference doesn't matter so long as you are consistent and tailor your interpretations accordingly. In other words, using a point estimate of $\\widehat{p}_{seed} - \\widehat{p}_{control}$ or $\\widehat{p}_{control} - \\widehat{p}_{seed}$ does not make a material difference, you just need to stay consistent and interpret your results accordingly. \n\n\n### Constructing the confidence interval {#sec-ci-build}\n\nAs we did in @sec-infer-workflow, let's first construct the bootstrap distribution for $\\widehat{p}_{seed} - \\widehat{p}_{control}$ and then use this to construct 95% confidence intervals for $p_{seed} - p_{control}$. We'll do this using the `infer` workflow again. However, since the difference in proportions is a new scenario for inference, we'll need to use some new arguments in the `infer` functions along the way.\n\n#### 1. `specify` variables {.unnumbered}\n\nLet's take our `mythbusters_yawn` data frame and `specify()` which variables are of interest using the `y ~ x` formula interface where:\n\n* Our response variable is `yawn`: whether or not a participant yawned. It has levels `\"yes\"` and `\"no\"`.\n* The explanatory variable is `group`. It has levels `\"seed\"` (exposed to yawning) and `\"control\"` (not exposed to yawning).\n\n```r\nmythbusters_yawn |> \n  specify(formula = yawn ~ group)\n```\n\n```\nError: A level of the response variable `yawn` needs to be specified for the \n`success` argument in `specify()`.\n```\n\nAlas, we got an error message that `infer` is telling us that one of the levels of the categorical variable `yawn` needs to be defined as the `success`. Recall that we define `success` to be the event of interest we are trying to count and compute proportions of. Are we interested in those participants who `\"yes\"` yawned or those who `\"no\"` didn't yawn? This isn't clear to R or someone just picking up the code and results for the first time, so we need to set the `success` argument to `\"yes\"` as follows to improve the transparency of the code:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmythbusters_yawn |> \n  specify(formula = yawn ~ group, success = \"yes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: yawn (factor)\nExplanatory: group (factor)\n# A tibble: 50 × 2\n   yawn  group  \n   <fct> <fct>  \n 1 yes   seed   \n 2 yes   control\n 3 no    seed   \n 4 yes   seed   \n 5 no    seed   \n 6 no    control\n 7 yes   seed   \n 8 no    control\n 9 no    control\n10 no    seed   \n# ℹ 40 more rows\n```\n\n\n:::\n:::\n\n\n#### 2. `generate` replicates {.unnumbered}\n\nOur next step is to perform *bootstrap resampling with replacement* like we did with the almonds in the activity in @sec-revisit-almond-bootstrap. We saw how it works with both a single variable in computing bootstrap means in @sec-bootstrap-process, but we haven't yet worked with bootstrapping involving multiple variables. \n\nIn the `infer` package, bootstrapping with multiple variables means that each *row* is potentially resampled. Let's investigate this by focusing only on the first six rows of `mythbusters_yawn`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfirst_six_rows <- head(mythbusters_yawn)\nfirst_six_rows\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n   subj group   yawn \n  <int> <chr>   <chr>\n1     1 seed    yes  \n2     2 control yes  \n3     3 seed    no   \n4     4 seed    yes  \n5     5 seed    no   \n6     6 control no   \n```\n\n\n:::\n:::\n\n\nWhen we bootstrap this data, we are potentially pulling the subject's readings multiple times. Thus, we could see the entries of `\"seed\"` for `group` and `\"no\"` for `yawn` together in a new row in a bootstrap sample. This is further seen by exploring the `sample_n()` function in `dplyr` on this smaller 6-row data frame comprised of `head(mythbusters_yawn)`. The `sample_n()` function can perform this bootstrapping procedure and is similar to the `rep_sample_n()` function in `infer`, except that it is not repeated, but rather only performs one sample with or without replacement.\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfirst_six_rows |> \n  sample_n(size = 6, replace = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n   subj group   yawn \n  <int> <chr>   <chr>\n1     6 control no   \n2     1 seed    yes  \n3     2 control yes  \n4     6 control no   \n5     4 seed    yes  \n6     4 seed    yes  \n```\n\n\n:::\n:::\n\n\nWe can see that in this bootstrap sample generated from the first six rows of `mythbusters_yawn`, we have some rows repeated. The same is true when we perform the `generate()` step in `infer` as done in what follows. Using this fact, we `generate` 1000 replicates, or, in other words, we bootstrap resample the 50 participants with replacement 1000 times. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmythbusters_yawn |> \n  specify(formula = yawn ~ group, success = \"yes\") |> \n  generate(reps = 1000, type = \"bootstrap\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: yawn (factor)\nExplanatory: group (factor)\n# A tibble: 50,000 × 3\n# Groups:   replicate [1,000]\n   replicate yawn  group  \n       <int> <fct> <fct>  \n 1         1 yes   seed   \n 2         1 yes   control\n 3         1 no    control\n 4         1 no    control\n 5         1 yes   seed   \n 6         1 yes   seed   \n 7         1 yes   seed   \n 8         1 yes   seed   \n 9         1 no    seed   \n10         1 yes   seed   \n# ℹ 49,990 more rows\n```\n\n\n:::\n:::\n\n\nObserve that the resulting data frame has 50,000 rows. This is because we performed resampling of 50 participants with replacement 1000 times and 50,000 = 1000 $\\cdot$ 50. The variable `replicate` indicates which resample each row belongs to. So it has the value `1` 50 times, the value `2` 50 times, all the way through to the value `` 1000 `` 50 times. \n\n#### 3. `calculate` summary statistics {.unnumbered}\n\nAfter we `generate()` many replicates of bootstrap resampling with replacement, we next want to summarize the bootstrap resamples of size 50 with a single summary statistic, the difference in proportions. We do this by setting the `stat` argument to `\"diff in props\"`:\n\n<!-- \nChester: A challenging Learning check for those {dplyr} diehards is to get these values \nwithout using {infer}. It takes a double group_by() and some trickery, but could \nbe a good exercise for those that don't quite see the power of {infer}.\n\nAlbert: Great idea!\n-->\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmythbusters_yawn |> \n  specify(formula = yawn ~ group, success = \"yes\") |> \n  generate(reps = 1000, type = \"bootstrap\") |> \n  calculate(stat = \"diff in props\")\n```\n:::\n\n```\nWarning message:\nThe statistic is based on a difference or ratio; by default, for \ndifference-based statistics, the explanatory variable is subtracted in the \norder \"control\" - \"seed\", or divided in the order \"control\" / \"seed\" for \nratio-based statistics. To specify this order yourself, supply \n`order = c(\"control\", \"seed\")` to the calculate() function. \n```\n\nWe see another warning here. We need to specify the order of the subtraction. Is it $\\widehat{p}_{seed} - \\widehat{p}_{control}$ or $\\widehat{p}_{control} - \\widehat{p}_{seed}$. We specify it to be $\\widehat{p}_{seed} - \\widehat{p}_{control}$ by setting `order = c(\"seed\", \"control\")`.  Note that you could've also set `order = c(\"control\", \"seed\")`. As we stated earlier, the order of the subtraction does not matter, so long as you stay consistent throughout your analysis and tailor your interpretations accordingly. \n\nLet's save the output in a data frame `bootstrap_distribution_yawning`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbootstrap_distribution_yawning <- mythbusters_yawn |> \n  specify(formula = yawn ~ group, success = \"yes\") |> \n  generate(reps = 1000, type = \"bootstrap\") |> \n  calculate(stat = \"diff in props\", order = c(\"seed\", \"control\"))\nbootstrap_distribution_yawning\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000 × 2\n   replicate        stat\n       <int>       <dbl>\n 1         1  0.0357143 \n 2         2  0.229167  \n 3         3  0.00952381\n 4         4  0.0106952 \n 5         5  0.00483092\n 6         6  0.00793651\n 7         7 -0.0845588 \n 8         8 -0.00466200\n 9         9  0.164686  \n10        10  0.124777  \n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\nObserve that the resulting data frame has 1000 rows and 2 columns corresponding to the 1000 `replicate` ID's and the 1000 differences in proportions for each bootstrap resample in `stat`.\n\n#### 4. `visualize` the results {.unnumbered}\n\nIn @fig-bootstrap-distribution-mythbusters we `visualize()` the resulting bootstrap resampling distribution. Let's also add a vertical line at 0 by adding a `geom_vline()` layer. \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Bootstrap distribution.](08-confidence-intervals_files/figure-html/fig-bootstrap-distribution-mythbusters-1.png){#fig-bootstrap-distribution-mythbusters fig-align='center' width=\\textwidth}\n:::\n:::\n\n\nFirst, let's compute the 95% confidence interval for $p_{seed} - p_{control}$ using the percentile method, in other words, by identifying the 2.5th and 97.5th percentiles which include the middle 95% of values. Recall that this method does not require the bootstrap distribution to be normally shaped. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbootstrap_distribution_yawning |> \n  get_confidence_interval(type = \"percentile\", level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n   lower_ci upper_ci\n      <dbl>    <dbl>\n1 -0.238276 0.302464\n```\n\n\n:::\n:::\n\n\n\nSecond, since the bootstrap distribution is roughly bell-shaped, we can construct a confidence interval using the standard error method as well. Recall that to construct a confidence interval using the standard error method, we need to specify the center of the interval using the `point_estimate` argument. In our case, we need to set it to be the difference in sample proportions of 4.4% that the *Mythbusters* observed.\n\nWe can also use the `infer` workflow to compute this value by excluding the `generate()` 1000 bootstrap replicates step. In other words, do not generate replicates, but rather use only the original sample data. We can achieve this by commenting out the `generate()` line, telling R to ignore it:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nobs_diff_in_props <- mythbusters_yawn |> \n  specify(formula = yawn ~ group, success = \"yes\") |> \n  # generate(reps = 1000, type = \"bootstrap\") |> \n  calculate(stat = \"diff in props\", order = c(\"seed\", \"control\"))\nobs_diff_in_props\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: yawn (factor)\nExplanatory: group (factor)\n# A tibble: 1 × 1\n       stat\n      <dbl>\n1 0.0441176\n```\n\n\n:::\n:::\n\n\nWe thus plug this value in as the `point_estimate` argument. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmyth_ci_se <- bootstrap_distribution_yawning |> \n  get_confidence_interval(type = \"se\", point_estimate = obs_diff_in_props,\n                          level = 0.95)\nmyth_ci_se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n   lower_ci upper_ci\n      <dbl>    <dbl>\n1 -0.227291 0.315526\n```\n\n\n:::\n:::\n\n\nLet's visualize both confidence intervals in @fig-bootstrap-distribution-mythbusters-CI, with the percentile method interval marked with black lines and the standard-error method marked with grey lines. Observe that they are both similar to each other. \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Two 95\\% confidence intervals: percentile method (black) and standard error method (grey).](08-confidence-intervals_files/figure-html/fig-bootstrap-distribution-mythbusters-CI-1.png){#fig-bootstrap-distribution-mythbusters-CI fig-align='center' width=\\textwidth}\n:::\n:::\n\n\n\n### Interpreting the confidence interval\n\nGiven that both confidence intervals are quite similar, let's focus our interpretation to only the percentile method confidence interval of (-0.2383, 0.3025). The precise statistical interpretation of a 95% confidence interval is: if this construction procedure is repeated 100 times, then we expect about 95 of the confidence intervals to capture the true value of $p_{seed} - p_{control}$. In other words, if we gathered 100 samples of $n$ = 50 participants from a similar pool of people and constructed 100 confidence intervals each based on each of the 100 samples, about 95 of them will contain the true value of $p_{seed} - p_{control}$ while about five won't. Given that this is a little long winded, we use the shorthand interpretation: we're 95% \"confident\" that the true difference in proportions $p_{seed} - p_{control}$ is between (-0.2383, 0.3025).\n\nThere is one value of particular interest that this 95% confidence interval contains: zero. If $p_{seed} - p_{control}$ were equal to 0, then there would be no difference in proportion yawning between the two groups. This would suggest that there is no associated effect of being exposed to a yawning recruiter on whether you yawn yourself. \n\nIn our case, since the 95% confidence interval includes 0, we cannot conclusively say if either proportion is larger. Of our 1000 bootstrap resamples with replacement, sometimes $\\widehat{p}_{seed}$ was higher and thus those exposed to yawning yawned themselves more often. At other times, the reverse happened. \n\nSay, on the other hand, the 95% confidence interval was entirely above zero. This would suggest that $p_{seed} - p_{control} > 0$, or, in other words $p_{seed} > p_{control}$, and thus we'd have evidence suggesting those exposed to yawning do yawn more often. \n\n## Quick checks {.unnumbered}\n\nTest your understanding of the material in this chapter.\n\n**Q1.** What does it mean to construct a 95% confidence interval?\n\na. There is a 95% probability that the population parameter lies in the interval\nb. 95% of the data values fall in the interval\nc. If we repeated the procedure many times, about 95% of the resulting intervals would contain the true parameter\nd. The sample mean has a 95% chance of being correct\n\n::: {.callout-tip collapse=\"true\" title=\"Show answer\"}\n**(c)** The 95% refers to the long-run reliability of the *procedure*, not the probability for any single computed interval. The parameter is fixed; the interval is random.\n:::\n\n**Q2.** In bootstrapping, you generate replicate samples by:\n\na. Drawing without replacement from the population\nb. Drawing with replacement from the original sample\nc. Drawing without replacement from a different population\nd. Generating random numbers from a normal distribution\n\n::: {.callout-tip collapse=\"true\" title=\"Show answer\"}\n**(b)** Bootstrap = resample *with replacement* from your one observed sample. This simulates \"what would another sample have looked like?\" without needing the actual population.\n:::\n\n**Q3.** A wider confidence interval generally means:\n\na. More precision\nb. Less precision (more uncertainty)\nc. A larger sample\nd. A higher confidence level always\n\n::: {.callout-tip collapse=\"true\" title=\"Show answer\"}\n**(b)** Wider = more uncertain about where the parameter is. To narrow a CI, lower the confidence level (e.g., 90% instead of 99%) or collect more data.\n:::\n\n## Summary and final remarks {#sec-summary-CI}\n\n### Additional resources\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nIf you want more examples of the `infer` workflow to construct confidence intervals, we suggest you check out the `infer` package homepage, in particular, a series of example analyses available at <https://infer.netlify.app/articles/>.\n\n\n### What's to come?\n\nNow that we've equipped ourselves with confidence intervals, in @sec-hypothesis-testing we'll cover the other common tool for statistical inference: hypothesis testing. Just like confidence intervals, hypothesis tests are used to infer about a population using a sample. However, we'll see that the framework for making such inferences is slightly different. \n",
    "supporting": [
      "08-confidence-intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}