#!/usr/bin/env Rscript
# Unused images audit.
#
# Scans `images/` recursively for image files (.png, .jpg, .jpeg, .svg, .gif,
# .webp, .ico, .tif, .tiff). For each, checks whether ANY qmd / md / lua / R
# file in the project references the image's filename. Flags images that
# nobody references — those are stale and safe to delete.
#
# Conversely, also flags references to images that don't exist on disk
# (broken `include_graphics()` calls, broken markdown image links).
#
# Output: two lists.
# Exit non-zero ONLY for broken references; unused-image lists are
# informational (some images are deliberately kept around for instructor
# use or historical reasons).

suppressPackageStartupMessages({
  library(stringr)
})

book <- "/Users/chesterismay/Desktop/repos/ModernDive_book"
setwd(book)

img_exts <- c("png", "jpg", "jpeg", "svg", "gif", "webp", "ico", "tif", "tiff")
img_pattern <- paste0("\\.(", paste(img_exts, collapse = "|"), ")$")

# All image files under images/ (recursively)
all_imgs <- list.files("images", recursive = TRUE, full.names = TRUE,
                       pattern = img_pattern, ignore.case = TRUE)
all_imgs <- all_imgs[file.info(all_imgs)$isdir == FALSE | is.na(file.info(all_imgs)$isdir)]
# Trim to paths relative to repo root (already are, since we set wd)

# All source files that might reference images
src_files <- c(
  list.files(".", pattern = "\\.qmd$", recursive = FALSE),
  list.files(".", pattern = "\\.md$", recursive = FALSE),
  list.files("scripts", pattern = "\\.(R|lua)$", full.names = TRUE),
  list.files("_extensions", pattern = "\\.(lua|yml)$", recursive = TRUE, full.names = TRUE),
  list.files("_includes", pattern = "\\.html$", full.names = TRUE),
  list.files("exercises", pattern = "\\.yml$", full.names = TRUE),
  list.files("instructor-solutions", pattern = "\\.(qmd|yml)$", recursive = TRUE, full.names = TRUE),
  list.files("lc-answers", pattern = "\\.qmd$", full.names = TRUE),
  "_quarto.yml",
  "404.html"
)
src_files <- src_files[file.exists(src_files)]

# Read all source content into one big string for quick substring matching.
all_text <- paste(unlist(lapply(src_files, function(f) readLines(f, warn = FALSE))),
                  collapse = "\n")

# Audit 1: images on disk that are never referenced
unused <- character()
for (img in all_imgs) {
  # Match by basename (preferred) OR full path (fallback for ambiguous names)
  base <- basename(img)
  if (!grepl(base, all_text, fixed = TRUE) &&
      !grepl(img, all_text, fixed = TRUE)) {
    unused <- c(unused, img)
  }
}

# Audit 2: image references in source that don't resolve to a file on disk
# Match markdown `![...](path)`, R `include_graphics("path")`, and inline HTML <img src="path">.
references_seen <- character()
img_pattern_in_src <- "(?:!\\[[^\\]]*\\]\\(|include_graphics\\([\"']|<img[^>]*src=[\"'])([^\"')\\s]+\\.(?:png|jpg|jpeg|svg|gif|webp|ico|tif|tiff))"
for (f in src_files) {
  content <- paste(readLines(f, warn = FALSE), collapse = "\n")
  matches <- str_match_all(content, img_pattern_in_src)[[1]]
  if (nrow(matches) > 0) {
    for (k in seq_len(nrow(matches))) {
      path <- matches[k, 2]
      # Skip remote URLs (http(s):// or //)
      if (grepl("^(https?:)?//", path)) next
      # Skip in-place rendered figure paths (those generated by knitr)
      if (grepl("^[A-Za-z0-9_-]+_files/", path)) next
      if (grepl("^\\.quarto/_freeze/", path)) next
      # Skip CI-built diagram outputs referenced by instructor-solutions/diagrams.qmd.
      # The PNG/SVG files are generated by scripts/build_diagrams.R in the
      # companion CI and land in instructor-solutions/_site/diagrams/ at
      # render time — they don't exist as static files in this repo.
      if (basename(f) == "diagrams.qmd" && grepl("^diagrams/", path)) next
      references_seen <- c(references_seen, paste0(f, ": ", path))
      if (!file.exists(path)) {
        # broken reference
        cat(sprintf("BROKEN REF: [%s] -> %s\n", f, path))
      }
    }
  }
}

cat(sprintf("\nScanned %d images, %d source files.\n",
            length(all_imgs), length(src_files)))
cat(sprintf("Image references in source: %d\n", length(references_seen)))
cat(sprintf("Unused images on disk: %d\n\n", length(unused)))

if (length(unused)) {
  cat("=== Unused images on disk (informational) ===\n")
  for (img in unused) {
    sz <- file.info(img)$size
    cat(sprintf("  %s  (%s)\n", img,
                if (sz > 1e6) sprintf("%.1f MB", sz / 1e6)
                else if (sz > 1e3) sprintf("%.0f KB", sz / 1e3)
                else sprintf("%d B", sz)))
  }
  cat("\n")
}

# Exit non-zero if broken references found (the cat output above)
broken_count <- length(grep("^BROKEN REF:", capture.output(
  for (f in src_files) {
    content <- paste(readLines(f, warn = FALSE), collapse = "\n")
    matches <- str_match_all(content, img_pattern_in_src)[[1]]
    if (nrow(matches) > 0) {
      for (k in seq_len(nrow(matches))) {
        path <- matches[k, 2]
        if (grepl("^(https?:)?//", path)) next
        if (grepl("^[A-Za-z0-9_-]+_files/", path)) next
        if (grepl("^\\.quarto/_freeze/", path)) next
        if (basename(f) == "diagrams.qmd" && grepl("^diagrams/", path)) next
        if (!file.exists(path)) cat("BROKEN REF: ", f, " -> ", path, "\n", sep = "")
      }
    }
  }
)))

if (broken_count > 0) {
  cat(sprintf("\n%d broken image reference(s) — fail.\n", broken_count))
  quit(status = 1)
}
cat("No broken image references.\n")
