<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>ModernDive</title>
  <meta name="description" content="Combining statistical and computational thinking to make sense of data. An evolution of the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown">
  <meta name="generator" content="bookdown 0.4 and GitBook 2.6.7">

  <meta property="og:title" content="ModernDive" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Combining statistical and computational thinking to make sense of data. An evolution of the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown" />
  <meta name="github-repo" content="ismayc/moderndiver-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="ModernDive" />
  
  <meta name="twitter:description" content="Combining statistical and computational thinking to make sense of data. An evolution of the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown" />
  

<meta name="author" content="Chester Ismay and Albert Y. Kim">


<meta name="date" content="2017-02-09">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="8-ci.html">
<link rel="next" href="10-effective-data-storytelling.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-0.9/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.4/dygraphs.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89938436-1', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preamble</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#principles-of-this-book---for-instructors"><i class="fa fa-check"></i><b>1.1</b> Principles of this Book - For Instructors</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#contribute"><i class="fa fa-check"></i><b>1.2</b> Contribute</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#getting-started---for-students"><i class="fa fa-check"></i><b>1.3</b> Getting Started - For Students</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#colophon"><i class="fa fa-check"></i>Colophon</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-intro.html"><a href="2-intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="2-intro.html"><a href="2-intro.html#preamble-1"><i class="fa fa-check"></i><b>2.1</b> Preamble</a></li>
<li class="chapter" data-level="2.2" data-path="2-intro.html"><a href="2-intro.html#three-driving-data-sources"><i class="fa fa-check"></i><b>2.2</b> Three driving data sources</a></li>
<li class="chapter" data-level="2.3" data-path="2-intro.html"><a href="2-intro.html#datascience-pipeline"><i class="fa fa-check"></i><b>2.3</b> Data/science pipeline</a></li>
<li class="chapter" data-level="2.4" data-path="2-intro.html"><a href="2-intro.html#reproducibility"><i class="fa fa-check"></i><b>2.4</b> Reproducibility</a></li>
<li class="chapter" data-level="2.5" data-path="2-intro.html"><a href="2-intro.html#who-is-this-book-for"><i class="fa fa-check"></i><b>2.5</b> Who is this book for?</a></li>
</ul></li>
<li class="part"><span><b>I Data Exploration</b></span></li>
<li class="chapter" data-level="3" data-path="3-tidy.html"><a href="3-tidy.html"><i class="fa fa-check"></i><b>3</b> Tidy Data</a><ul>
<li class="chapter" data-level="" data-path="3-tidy.html"><a href="3-tidy.html#needed-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="3.1" data-path="3-tidy.html"><a href="3-tidy.html#what-is-tidy-data"><i class="fa fa-check"></i><b>3.1</b> What is tidy data?</a></li>
<li class="chapter" data-level="3.2" data-path="3-tidy.html"><a href="3-tidy.html#datasets-in-the-nycflights13-package"><i class="fa fa-check"></i><b>3.2</b> Datasets in the <code>nycflights13</code> package</a></li>
<li class="chapter" data-level="3.3" data-path="3-tidy.html"><a href="3-tidy.html#how-is-flights-tidy"><i class="fa fa-check"></i><b>3.3</b> How is <code>flights</code> tidy?</a><ul>
<li class="chapter" data-level="3.3.1" data-path="3-tidy.html"><a href="3-tidy.html#identification-variables"><i class="fa fa-check"></i><b>3.3.1</b> Identification variables</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="3-tidy.html"><a href="3-tidy.html#normal-forms-of-data"><i class="fa fa-check"></i><b>3.4</b> Normal forms of data</a></li>
<li class="chapter" data-level="3.5" data-path="3-tidy.html"><a href="3-tidy.html#whats-to-come"><i class="fa fa-check"></i><b>3.5</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-viz.html"><a href="4-viz.html"><i class="fa fa-check"></i><b>4</b> Data Visualization via ggplot2</a><ul>
<li class="chapter" data-level="" data-path="4-viz.html"><a href="4-viz.html#needed-packages-1"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="4.1" data-path="4-viz.html"><a href="4-viz.html#grammarofgraphics"><i class="fa fa-check"></i><b>4.1</b> The Grammar of Graphics</a><ul>
<li class="chapter" data-level="4.1.1" data-path="4-viz.html"><a href="4-viz.html#components-of-grammar"><i class="fa fa-check"></i><b>4.1.1</b> Components of Grammar</a></li>
<li class="chapter" data-level="4.1.2" data-path="4-viz.html"><a href="4-viz.html#napoleans-march-on-moscow"><i class="fa fa-check"></i><b>4.1.2</b> Napolean’s March on Moscow</a></li>
<li class="chapter" data-level="4.1.3" data-path="4-viz.html"><a href="4-viz.html#other-components-of-the-grammar"><i class="fa fa-check"></i><b>4.1.3</b> Other Components of the Grammar</a></li>
<li class="chapter" data-level="4.1.4" data-path="4-viz.html"><a href="4-viz.html#the-ggplot2-package"><i class="fa fa-check"></i><b>4.1.4</b> The ggplot2 Package</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="4-viz.html"><a href="4-viz.html#five-named-graphs---the-5ng"><i class="fa fa-check"></i><b>4.2</b> Five Named Graphs - The 5NG</a></li>
<li class="chapter" data-level="4.3" data-path="4-viz.html"><a href="4-viz.html#scatterplots"><i class="fa fa-check"></i><b>4.3</b> 5NG#1: Scatter-plots</a><ul>
<li class="chapter" data-level="4.3.1" data-path="4-viz.html"><a href="4-viz.html#geompoint"><i class="fa fa-check"></i><b>4.3.1</b> Scatter-plots via geom_point</a></li>
<li class="chapter" data-level="4.3.2" data-path="4-viz.html"><a href="4-viz.html#over-plotting"><i class="fa fa-check"></i><b>4.3.2</b> Over-Plotting</a></li>
<li class="chapter" data-level="4.3.3" data-path="4-viz.html"><a href="4-viz.html#summary"><i class="fa fa-check"></i><b>4.3.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="4-viz.html"><a href="4-viz.html#linegraphs"><i class="fa fa-check"></i><b>4.4</b> 5NG#2: Line-graphs</a><ul>
<li class="chapter" data-level="4.4.1" data-path="4-viz.html"><a href="4-viz.html#geomline"><i class="fa fa-check"></i><b>4.4.1</b> Line-graphs via geom_line</a></li>
<li class="chapter" data-level="4.4.2" data-path="4-viz.html"><a href="4-viz.html#summary-1"><i class="fa fa-check"></i><b>4.4.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="4-viz.html"><a href="4-viz.html#histograms"><i class="fa fa-check"></i><b>4.5</b> 5NG#3: Histograms</a><ul>
<li class="chapter" data-level="4.5.1" data-path="4-viz.html"><a href="4-viz.html#geomhistogram"><i class="fa fa-check"></i><b>4.5.1</b> Histograms via geom_histogram</a></li>
<li class="chapter" data-level="4.5.2" data-path="4-viz.html"><a href="4-viz.html#adjustbins"><i class="fa fa-check"></i><b>4.5.2</b> Adjusting the Bins</a></li>
<li class="chapter" data-level="4.5.3" data-path="4-viz.html"><a href="4-viz.html#summary-2"><i class="fa fa-check"></i><b>4.5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="4-viz.html"><a href="4-viz.html#facets"><i class="fa fa-check"></i><b>4.6</b> Facets</a></li>
<li class="chapter" data-level="4.7" data-path="4-viz.html"><a href="4-viz.html#ng4-boxplots"><i class="fa fa-check"></i><b>4.7</b> 5NG#4: Boxplots</a><ul>
<li class="chapter" data-level="4.7.1" data-path="4-viz.html"><a href="4-viz.html#geomboxplot"><i class="fa fa-check"></i><b>4.7.1</b> Boxplots via geom_boxplot</a></li>
<li class="chapter" data-level="4.7.2" data-path="4-viz.html"><a href="4-viz.html#summary-3"><i class="fa fa-check"></i><b>4.7.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="4-viz.html"><a href="4-viz.html#geombar"><i class="fa fa-check"></i><b>4.8</b> 5NG#5: Barplots</a><ul>
<li class="chapter" data-level="4.8.1" data-path="4-viz.html"><a href="4-viz.html#barplots-via-geom_bar"><i class="fa fa-check"></i><b>4.8.1</b> Barplots via geom_bar</a></li>
<li class="chapter" data-level="4.8.2" data-path="4-viz.html"><a href="4-viz.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>4.8.2</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="4.8.3" data-path="4-viz.html"><a href="4-viz.html#using-barplots-to-compare-two-variables"><i class="fa fa-check"></i><b>4.8.3</b> Using barplots to compare two variables</a></li>
<li class="chapter" data-level="4.8.4" data-path="4-viz.html"><a href="4-viz.html#summary-4"><i class="fa fa-check"></i><b>4.8.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="4-viz.html"><a href="4-viz.html#conclusion"><i class="fa fa-check"></i><b>4.9</b> Conclusion</a><ul>
<li class="chapter" data-level="4.9.1" data-path="4-viz.html"><a href="4-viz.html#resources"><i class="fa fa-check"></i><b>4.9.1</b> Resources</a></li>
<li class="chapter" data-level="4.9.2" data-path="4-viz.html"><a href="4-viz.html#script-of-r-code"><i class="fa fa-check"></i><b>4.9.2</b> Script of R code</a></li>
<li class="chapter" data-level="4.9.3" data-path="4-viz.html"><a href="4-viz.html#whats-to-come-1"><i class="fa fa-check"></i><b>4.9.3</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-manip.html"><a href="5-manip.html"><i class="fa fa-check"></i><b>5</b> Data Manipulation via dplyr</a><ul>
<li class="chapter" data-level="" data-path="5-manip.html"><a href="5-manip.html#needed-packages-2"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="5.1" data-path="5-manip.html"><a href="5-manip.html#the-pipe"><i class="fa fa-check"></i><b>5.1</b> The pipe <code>%&gt;%</code></a></li>
<li class="chapter" data-level="5.2" data-path="5-manip.html"><a href="5-manip.html#five-main-verbs---the-5mv"><i class="fa fa-check"></i><b>5.2</b> Five Main Verbs - The 5MV</a><ul>
<li class="chapter" data-level="5.2.1" data-path="5-manip.html"><a href="5-manip.html#filter"><i class="fa fa-check"></i><b>5.2.1</b> 5MV#1: Filter observations using filter</a></li>
<li class="chapter" data-level="5.2.2" data-path="5-manip.html"><a href="5-manip.html#mv2-summarize-variables-using-summarize"><i class="fa fa-check"></i><b>5.2.2</b> 5MV#2: Summarize variables using summarize</a></li>
<li class="chapter" data-level="5.2.3" data-path="5-manip.html"><a href="5-manip.html#mv3-group-rows-using-group_by"><i class="fa fa-check"></i><b>5.2.3</b> 5MV#3: Group rows using group_by</a></li>
<li class="chapter" data-level="5.2.4" data-path="5-manip.html"><a href="5-manip.html#mv4-create-new-variableschange-old-variables-using-mutate"><i class="fa fa-check"></i><b>5.2.4</b> 5MV#4: Create new variables/change old variables using mutate</a></li>
<li class="chapter" data-level="5.2.5" data-path="5-manip.html"><a href="5-manip.html#arrange"><i class="fa fa-check"></i><b>5.2.5</b> 5MV#5: Reorder the data frame using arrange</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="5-manip.html"><a href="5-manip.html#joining-data-frames"><i class="fa fa-check"></i><b>5.3</b> Joining data frames</a><ul>
<li class="chapter" data-level="5.3.1" data-path="5-manip.html"><a href="5-manip.html#joining-by-key-variables"><i class="fa fa-check"></i><b>5.3.1</b> Joining by Key Variables</a></li>
<li class="chapter" data-level="5.3.2" data-path="5-manip.html"><a href="5-manip.html#joining-by-key-variables-with-different-names"><i class="fa fa-check"></i><b>5.3.2</b> Joining by Key Variables with Different Names</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="5-manip.html"><a href="5-manip.html#optional-other-verbs"><i class="fa fa-check"></i><b>5.4</b> Optional: Other verbs</a><ul>
<li class="chapter" data-level="5.4.1" data-path="5-manip.html"><a href="5-manip.html#select"><i class="fa fa-check"></i><b>5.4.1</b> Select variables using select</a></li>
<li class="chapter" data-level="5.4.2" data-path="5-manip.html"><a href="5-manip.html#rename"><i class="fa fa-check"></i><b>5.4.2</b> Rename variables using rename</a></li>
<li class="chapter" data-level="5.4.3" data-path="5-manip.html"><a href="5-manip.html#find-the-top-number-of-values-using-top_n"><i class="fa fa-check"></i><b>5.4.3</b> Find the top number of values using top_n</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="5-manip.html"><a href="5-manip.html#conclusion-1"><i class="fa fa-check"></i><b>5.5</b> Conclusion</a><ul>
<li class="chapter" data-level="5.5.1" data-path="5-manip.html"><a href="5-manip.html#resources-1"><i class="fa fa-check"></i><b>5.5.1</b> Resources</a></li>
<li class="chapter" data-level="5.5.2" data-path="5-manip.html"><a href="5-manip.html#script-of-r-code-1"><i class="fa fa-check"></i><b>5.5.2</b> Script of R code</a></li>
<li class="chapter" data-level="5.5.3" data-path="5-manip.html"><a href="5-manip.html#whats-to-come-2"><i class="fa fa-check"></i><b>5.5.3</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Inference</b></span></li>
<li class="chapter" data-level="6" data-path="6-sim.html"><a href="6-sim.html"><i class="fa fa-check"></i><b>6</b> Simulating Randomness via mosaic</a><ul>
<li class="chapter" data-level="" data-path="6-sim.html"><a href="6-sim.html#needed-packages-3"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="6.1" data-path="6-sim.html"><a href="6-sim.html#random-sampling"><i class="fa fa-check"></i><b>6.1</b> Random sampling</a><ul>
<li class="chapter" data-level="6.1.1" data-path="6-sim.html"><a href="6-sim.html#tasting-soup"><i class="fa fa-check"></i><b>6.1.1</b> Tasting soup</a></li>
<li class="chapter" data-level="6.1.2" data-path="6-sim.html"><a href="6-sim.html#common-terms"><i class="fa fa-check"></i><b>6.1.2</b> Common terms</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="6-sim.html"><a href="6-sim.html#visualizing-sampling"><i class="fa fa-check"></i><b>6.2</b> Visualizing sampling</a><ul>
<li class="chapter" data-level="6.2.1" data-path="6-sim.html"><a href="6-sim.html#sampling-distribution"><i class="fa fa-check"></i><b>6.2.1</b> Sampling distribution</a></li>
<li class="chapter" data-level="6.2.2" data-path="6-sim.html"><a href="6-sim.html#repeated-sampling-via-do"><i class="fa fa-check"></i><b>6.2.2</b> Repeated sampling via <code>do</code></a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="6-sim.html"><a href="6-sim.html#simulation"><i class="fa fa-check"></i><b>6.3</b> Simulation</a></li>
<li class="chapter" data-level="6.4" data-path="6-sim.html"><a href="6-sim.html#review-of-mosaic-simulation-functions"><i class="fa fa-check"></i><b>6.4</b> Review of <code>mosaic</code> simulation functions</a></li>
<li class="chapter" data-level="6.5" data-path="6-sim.html"><a href="6-sim.html#conclusion-2"><i class="fa fa-check"></i><b>6.5</b> Conclusion</a><ul>
<li class="chapter" data-level="6.5.1" data-path="6-sim.html"><a href="6-sim.html#script-of-r-code-2"><i class="fa fa-check"></i><b>6.5.1</b> Script of R code</a></li>
<li class="chapter" data-level="6.5.2" data-path="6-sim.html"><a href="6-sim.html#whats-to-come-3"><i class="fa fa-check"></i><b>6.5.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-hypo.html"><a href="7-hypo.html"><i class="fa fa-check"></i><b>7</b> Hypothesis Testing</a><ul>
<li class="chapter" data-level="" data-path="7-hypo.html"><a href="7-hypo.html#needed-packages-4"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="7.1" data-path="7-hypo.html"><a href="7-hypo.html#when-inference-is-not-needed"><i class="fa fa-check"></i><b>7.1</b> When Inference Is Not Needed</a></li>
<li class="chapter" data-level="7.2" data-path="7-hypo.html"><a href="7-hypo.html#basics-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.2</b> Basics of Hypothesis Testing</a></li>
<li class="chapter" data-level="7.3" data-path="7-hypo.html"><a href="7-hypo.html#trial"><i class="fa fa-check"></i><b>7.3</b> Criminal trial analogy</a><ul>
<li class="chapter" data-level="7.3.1" data-path="7-hypo.html"><a href="7-hypo.html#two-possible-conclusions"><i class="fa fa-check"></i><b>7.3.1</b> Two possible conclusions</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="7-hypo.html"><a href="7-hypo.html#types-of-errors-in-hypothesis-testing"><i class="fa fa-check"></i><b>7.4</b> Types of Errors in Hypothesis Testing</a><ul>
<li class="chapter" data-level="7.4.1" data-path="7-hypo.html"><a href="7-hypo.html#logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.4.1</b> Logic of Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="7-hypo.html"><a href="7-hypo.html#statistical-significance"><i class="fa fa-check"></i><b>7.5</b> Statistical Significance</a></li>
<li class="chapter" data-level="7.6" data-path="7-hypo.html"><a href="7-hypo.html#example-revisiting-the-lady-tasting-tea"><i class="fa fa-check"></i><b>7.6</b> EXAMPLE: Revisiting the Lady Tasting Tea</a><ul>
<li class="chapter" data-level="7.6.1" data-path="7-hypo.html"><a href="7-hypo.html#data"><i class="fa fa-check"></i><b>7.6.1</b> Data</a></li>
<li class="chapter" data-level="7.6.2" data-path="7-hypo.html"><a href="7-hypo.html#test-statistic-delta"><i class="fa fa-check"></i><b>7.6.2</b> Test Statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="7.6.3" data-path="7-hypo.html"><a href="7-hypo.html#observed-effect-delta"><i class="fa fa-check"></i><b>7.6.3</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="7.6.4" data-path="7-hypo.html"><a href="7-hypo.html#model-of-h_0"><i class="fa fa-check"></i><b>7.6.4</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.6.5" data-path="7-hypo.html"><a href="7-hypo.html#simulated-data"><i class="fa fa-check"></i><b>7.6.5</b> Simulated Data</a></li>
<li class="chapter" data-level="7.6.6" data-path="7-hypo.html"><a href="7-hypo.html#distribution-of-delta-under-h_0"><i class="fa fa-check"></i><b>7.6.6</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.6.7" data-path="7-hypo.html"><a href="7-hypo.html#the-p-value"><i class="fa fa-check"></i><b>7.6.7</b> The p-value</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="7-hypo.html"><a href="7-hypo.html#example-comparing-two-means"><i class="fa fa-check"></i><b>7.7</b> EXAMPLE: Comparing two means</a><ul>
<li class="chapter" data-level="7.7.1" data-path="7-hypo.html"><a href="7-hypo.html#randomizationpermutation"><i class="fa fa-check"></i><b>7.7.1</b> Randomization/Permutation</a></li>
<li class="chapter" data-level="7.7.2" data-path="7-hypo.html"><a href="7-hypo.html#comparing-action-and-romance-movies"><i class="fa fa-check"></i><b>7.7.2</b> Comparing Action and Romance Movies</a></li>
<li class="chapter" data-level="7.7.3" data-path="7-hypo.html"><a href="7-hypo.html#sampling-rightarrow-randomization"><i class="fa fa-check"></i><b>7.7.3</b> Sampling <span class="math inline">\(\rightarrow\)</span> Randomization</a></li>
<li class="chapter" data-level="7.7.4" data-path="7-hypo.html"><a href="7-hypo.html#data-1"><i class="fa fa-check"></i><b>7.7.4</b> Data</a></li>
<li class="chapter" data-level="7.7.5" data-path="7-hypo.html"><a href="7-hypo.html#model-of-h_0-1"><i class="fa fa-check"></i><b>7.7.5</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.7.6" data-path="7-hypo.html"><a href="7-hypo.html#test-statistic-delta-1"><i class="fa fa-check"></i><b>7.7.6</b> Test Statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="7.7.7" data-path="7-hypo.html"><a href="7-hypo.html#observed-effect-delta-1"><i class="fa fa-check"></i><b>7.7.7</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="7.7.8" data-path="7-hypo.html"><a href="7-hypo.html#simulated-data-1"><i class="fa fa-check"></i><b>7.7.8</b> Simulated Data</a></li>
<li class="chapter" data-level="7.7.9" data-path="7-hypo.html"><a href="7-hypo.html#distribution-of-delta-under-h_0-1"><i class="fa fa-check"></i><b>7.7.9</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.7.10" data-path="7-hypo.html"><a href="7-hypo.html#the-p-value-1"><i class="fa fa-check"></i><b>7.7.10</b> The p-value</a></li>
<li class="chapter" data-level="7.7.11" data-path="7-hypo.html"><a href="7-hypo.html#summary-5"><i class="fa fa-check"></i><b>7.7.11</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="7-hypo.html"><a href="7-hypo.html#theory-hypo"><i class="fa fa-check"></i><b>7.8</b> Building theory-based methods using computation</a><ul>
<li class="chapter" data-level="7.8.1" data-path="7-hypo.html"><a href="7-hypo.html#example-t-test-for-two-independent-samples"><i class="fa fa-check"></i><b>7.8.1</b> EXAMPLE: <span class="math inline">\(t\)</span>-test for two independent samples</a></li>
<li class="chapter" data-level="7.8.2" data-path="7-hypo.html"><a href="7-hypo.html#conditions-for-t-test"><i class="fa fa-check"></i><b>7.8.2</b> Conditions for t-test</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="7-hypo.html"><a href="7-hypo.html#conclusion-3"><i class="fa fa-check"></i><b>7.9</b> Conclusion</a><ul>
<li class="chapter" data-level="7.9.1" data-path="7-hypo.html"><a href="7-hypo.html#script-of-r-code-3"><i class="fa fa-check"></i><b>7.9.1</b> Script of R code</a></li>
<li class="chapter" data-level="7.9.2" data-path="7-hypo.html"><a href="7-hypo.html#whats-to-come-4"><i class="fa fa-check"></i><b>7.9.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-ci.html"><a href="8-ci.html"><i class="fa fa-check"></i><b>8</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="" data-path="8-ci.html"><a href="8-ci.html#needed-packages-5"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="8.1" data-path="8-ci.html"><a href="8-ci.html#bootstrapping"><i class="fa fa-check"></i><b>8.1</b> Bootstrapping</a><ul>
<li class="chapter" data-level="8.1.1" data-path="8-ci.html"><a href="8-ci.html#review-of-bootstrapping"><i class="fa fa-check"></i><b>8.1.1</b> Review of Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="8-ci.html"><a href="8-ci.html#relation-to-hypothesis-testing"><i class="fa fa-check"></i><b>8.2</b> Relation to hypothesis testing</a></li>
<li class="chapter" data-level="8.3" data-path="8-ci.html"><a href="8-ci.html#effect-size"><i class="fa fa-check"></i><b>8.3</b> Effect size</a></li>
<li class="chapter" data-level="8.4" data-path="8-ci.html"><a href="8-ci.html#conclusion-4"><i class="fa fa-check"></i><b>8.4</b> Conclusion</a><ul>
<li class="chapter" data-level="8.4.1" data-path="8-ci.html"><a href="8-ci.html#script-of-r-code-4"><i class="fa fa-check"></i><b>8.4.1</b> Script of R code</a></li>
<li class="chapter" data-level="8.4.2" data-path="8-ci.html"><a href="8-ci.html#whats-to-come-5"><i class="fa fa-check"></i><b>8.4.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="9-regress.html"><a href="9-regress.html"><i class="fa fa-check"></i><b>9</b> Regression via broom</a><ul>
<li class="chapter" data-level="" data-path="9-regress.html"><a href="9-regress.html#needed-packages-6"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="9.1" data-path="9-regress.html"><a href="9-regress.html#example-alaskan-airlines-delays"><i class="fa fa-check"></i><b>9.1</b> EXAMPLE: Alaskan Airlines delays</a></li>
<li class="chapter" data-level="9.2" data-path="9-regress.html"><a href="9-regress.html#correlation"><i class="fa fa-check"></i><b>9.2</b> Correlation</a><ul>
<li class="chapter" data-level="9.2.1" data-path="9-regress.html"><a href="9-regress.html#correlation-does-not-imply-causation"><i class="fa fa-check"></i><b>9.2.1</b> Correlation does not imply causation</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="9-regress.html"><a href="9-regress.html#linear-regression"><i class="fa fa-check"></i><b>9.3</b> Linear regression</a><ul>
<li class="chapter" data-level="9.3.1" data-path="9-regress.html"><a href="9-regress.html#understanding-linear-regression-basics"><i class="fa fa-check"></i><b>9.3.1</b> Understanding linear regression basics</a></li>
<li class="chapter" data-level="9.3.2" data-path="9-regress.html"><a href="9-regress.html#the-equation-of-the-line"><i class="fa fa-check"></i><b>9.3.2</b> The equation of the line</a></li>
<li class="chapter" data-level="9.3.3" data-path="9-regress.html"><a href="9-regress.html#interpreting-the-slope"><i class="fa fa-check"></i><b>9.3.3</b> Interpreting the slope</a></li>
<li class="chapter" data-level="9.3.4" data-path="9-regress.html"><a href="9-regress.html#predicting-values"><i class="fa fa-check"></i><b>9.3.4</b> Predicting values</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="9-regress.html"><a href="9-regress.html#inference-for-regression"><i class="fa fa-check"></i><b>9.4</b> Inference for regression</a><ul>
<li class="chapter" data-level="9.4.1" data-path="9-regress.html"><a href="9-regress.html#data-2"><i class="fa fa-check"></i><b>9.4.1</b> Data</a></li>
<li class="chapter" data-level="9.4.2" data-path="9-regress.html"><a href="9-regress.html#test-statistic-delta-2"><i class="fa fa-check"></i><b>9.4.2</b> Test Statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="9.4.3" data-path="9-regress.html"><a href="9-regress.html#observed-effect-delta-2"><i class="fa fa-check"></i><b>9.4.3</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="9.4.4" data-path="9-regress.html"><a href="9-regress.html#model-of-h_0-2"><i class="fa fa-check"></i><b>9.4.4</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="9.4.5" data-path="9-regress.html"><a href="9-regress.html#simulated-data-2"><i class="fa fa-check"></i><b>9.4.5</b> Simulated Data</a></li>
<li class="chapter" data-level="9.4.6" data-path="9-regress.html"><a href="9-regress.html#distribution-of-delta-under-h_0-2"><i class="fa fa-check"></i><b>9.4.6</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="9.4.7" data-path="9-regress.html"><a href="9-regress.html#the-p-value-2"><i class="fa fa-check"></i><b>9.4.7</b> The p-value</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="9-regress.html"><a href="9-regress.html#resid"><i class="fa fa-check"></i><b>9.5</b> Residual analysis</a></li>
<li class="chapter" data-level="9.6" data-path="9-regress.html"><a href="9-regress.html#conditions-for-regression"><i class="fa fa-check"></i><b>9.6</b> Conditions for regression</a></li>
<li class="chapter" data-level="9.7" data-path="9-regress.html"><a href="9-regress.html#conclusion-5"><i class="fa fa-check"></i><b>9.7</b> Conclusion</a><ul>
<li class="chapter" data-level="9.7.1" data-path="9-regress.html"><a href="9-regress.html#script-of-r-code-5"><i class="fa fa-check"></i><b>9.7.1</b> Script of R code</a></li>
<li class="chapter" data-level="9.7.2" data-path="9-regress.html"><a href="9-regress.html#whats-to-come-6"><i class="fa fa-check"></i><b>9.7.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Conclusion</b></span></li>
<li class="chapter" data-level="10" data-path="10-effective-data-storytelling.html"><a href="10-effective-data-storytelling.html"><i class="fa fa-check"></i><b>10</b> Effective Data Storytelling</a><ul>
<li class="chapter" data-level="" data-path="10-effective-data-storytelling.html"><a href="10-effective-data-storytelling.html#concluding-remarks"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="A-appendixA.html"><a href="A-appendixA.html"><i class="fa fa-check"></i><b>A</b> Statistical Background</a><ul>
<li class="chapter" data-level="A.1" data-path="A-appendixA.html"><a href="A-appendixA.html#basic-statistical-terms"><i class="fa fa-check"></i><b>A.1</b> Basic statistical terms</a><ul>
<li class="chapter" data-level="A.1.1" data-path="A-appendixA.html"><a href="A-appendixA.html#mean"><i class="fa fa-check"></i><b>A.1.1</b> Mean</a></li>
<li class="chapter" data-level="A.1.2" data-path="A-appendixA.html"><a href="A-appendixA.html#median"><i class="fa fa-check"></i><b>A.1.2</b> Median</a></li>
<li class="chapter" data-level="A.1.3" data-path="A-appendixA.html"><a href="A-appendixA.html#standard-deviation"><i class="fa fa-check"></i><b>A.1.3</b> Standard deviation</a></li>
<li class="chapter" data-level="A.1.4" data-path="A-appendixA.html"><a href="A-appendixA.html#five-number-summary"><i class="fa fa-check"></i><b>A.1.4</b> Five-number summary</a></li>
<li class="chapter" data-level="A.1.5" data-path="A-appendixA.html"><a href="A-appendixA.html#distribution"><i class="fa fa-check"></i><b>A.1.5</b> Distribution</a></li>
<li class="chapter" data-level="A.1.6" data-path="A-appendixA.html"><a href="A-appendixA.html#outliers"><i class="fa fa-check"></i><b>A.1.6</b> Outliers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="B-appendixB.html"><a href="B-appendixB.html"><i class="fa fa-check"></i><b>B</b> Inference Examples</a><ul>
<li class="chapter" data-level="" data-path="B-appendixB.html"><a href="B-appendixB.html#needed-packages-7"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="B.1" data-path="B-appendixB.html"><a href="B-appendixB.html#inference-mind-map"><i class="fa fa-check"></i><b>B.1</b> Inference Mind Map</a></li>
<li class="chapter" data-level="B.2" data-path="B-appendixB.html"><a href="B-appendixB.html#one-mean"><i class="fa fa-check"></i><b>B.2</b> One Mean</a><ul>
<li class="chapter" data-level="B.2.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement"><i class="fa fa-check"></i><b>B.2.1</b> Problem Statement</a></li>
<li class="chapter" data-level="B.2.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses"><i class="fa fa-check"></i><b>B.2.2</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.2.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data"><i class="fa fa-check"></i><b>B.2.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.2.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods"><i class="fa fa-check"></i><b>B.2.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.2.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods"><i class="fa fa-check"></i><b>B.2.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.2.6" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results"><i class="fa fa-check"></i><b>B.2.6</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.3" data-path="B-appendixB.html"><a href="B-appendixB.html#one-proportion"><i class="fa fa-check"></i><b>B.3</b> One Proportion</a><ul>
<li class="chapter" data-level="B.3.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement-1"><i class="fa fa-check"></i><b>B.3.1</b> Problem Statement</a></li>
<li class="chapter" data-level="B.3.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-1"><i class="fa fa-check"></i><b>B.3.2</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.3.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-1"><i class="fa fa-check"></i><b>B.3.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.3.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-1"><i class="fa fa-check"></i><b>B.3.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.3.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-1"><i class="fa fa-check"></i><b>B.3.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.3.6" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-1"><i class="fa fa-check"></i><b>B.3.6</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.4" data-path="B-appendixB.html"><a href="B-appendixB.html#two-proportions"><i class="fa fa-check"></i><b>B.4</b> Two Proportions</a><ul>
<li class="chapter" data-level="B.4.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement-2"><i class="fa fa-check"></i><b>B.4.1</b> Problem Statement</a></li>
<li class="chapter" data-level="B.4.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-2"><i class="fa fa-check"></i><b>B.4.2</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.4.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-2"><i class="fa fa-check"></i><b>B.4.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.4.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-2"><i class="fa fa-check"></i><b>B.4.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.4.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-2"><i class="fa fa-check"></i><b>B.4.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.4.6" data-path="B-appendixB.html"><a href="B-appendixB.html#check-conditions-2"><i class="fa fa-check"></i><b>B.4.6</b> Check conditions</a></li>
<li class="chapter" data-level="B.4.7" data-path="B-appendixB.html"><a href="B-appendixB.html#test-statistic-2"><i class="fa fa-check"></i><b>B.4.7</b> Test statistic</a></li>
<li class="chapter" data-level="B.4.8" data-path="B-appendixB.html"><a href="B-appendixB.html#state-conclusion-2"><i class="fa fa-check"></i><b>B.4.8</b> State conclusion</a></li>
<li class="chapter" data-level="B.4.9" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-2"><i class="fa fa-check"></i><b>B.4.9</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.5" data-path="B-appendixB.html"><a href="B-appendixB.html#two-means-independent-samples"><i class="fa fa-check"></i><b>B.5</b> Two Means (Independent Samples)</a><ul>
<li class="chapter" data-level="B.5.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement-3"><i class="fa fa-check"></i><b>B.5.1</b> Problem Statement</a></li>
<li class="chapter" data-level="B.5.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-3"><i class="fa fa-check"></i><b>B.5.2</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.5.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-3"><i class="fa fa-check"></i><b>B.5.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.5.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-3"><i class="fa fa-check"></i><b>B.5.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.5.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-3"><i class="fa fa-check"></i><b>B.5.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.5.6" data-path="B-appendixB.html"><a href="B-appendixB.html#test-statistic-3"><i class="fa fa-check"></i><b>B.5.6</b> Test statistic</a></li>
<li class="chapter" data-level="B.5.7" data-path="B-appendixB.html"><a href="B-appendixB.html#compute-p-value-2"><i class="fa fa-check"></i><b>B.5.7</b> Compute <span class="math inline">\(p\)</span>-value</a></li>
<li class="chapter" data-level="B.5.8" data-path="B-appendixB.html"><a href="B-appendixB.html#state-conclusion-3"><i class="fa fa-check"></i><b>B.5.8</b> State conclusion</a></li>
<li class="chapter" data-level="B.5.9" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-3"><i class="fa fa-check"></i><b>B.5.9</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.6" data-path="B-appendixB.html"><a href="B-appendixB.html#two-means-paired-samples"><i class="fa fa-check"></i><b>B.6</b> Two Means (Paired Samples)</a><ul>
<li class="chapter" data-level="B.6.1" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-4"><i class="fa fa-check"></i><b>B.6.1</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.6.2" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-4"><i class="fa fa-check"></i><b>B.6.2</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.6.3" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-4"><i class="fa fa-check"></i><b>B.6.3</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.6.4" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-4"><i class="fa fa-check"></i><b>B.6.4</b> Traditional methods</a></li>
<li class="chapter" data-level="B.6.5" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-4"><i class="fa fa-check"></i><b>B.6.5</b> Comparing results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="C" data-path="C-appendixC.html"><a href="C-appendixC.html"><i class="fa fa-check"></i><b>C</b> Reach for the Stars</a><ul>
<li class="chapter" data-level="" data-path="C-appendixC.html"><a href="C-appendixC.html#needed-packages-8"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="C.1" data-path="C-appendixC.html"><a href="C-appendixC.html#sorted-barplots"><i class="fa fa-check"></i><b>C.1</b> Sorted barplots</a></li>
<li class="chapter" data-level="C.2" data-path="C-appendixC.html"><a href="C-appendixC.html#interactive-graphics"><i class="fa fa-check"></i><b>C.2</b> Interactive graphics</a><ul>
<li class="chapter" data-level="C.2.1" data-path="C-appendixC.html"><a href="C-appendixC.html#interactive-line-graphs"><i class="fa fa-check"></i><b>C.2.1</b> Interactive line-graphs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ModernDive</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regress" class="section level1">
<h1><span class="header-section-number">9</span> Regression via broom</h1>
<p>One of the most commonly used statistical procedures is <em>regression</em>. Regression, in its simplest form, focuses on trying to predict values of one numerical variable based on the values of another numerical variable using a straight line fit to data. We saw in Chapters <a href="7-hypo.html#hypo">7</a> and <a href="8-ci.html#ci">8</a> an example of analyses using a categorical predictor (movie genre–action or romance) and a numerical response (movie rating). In this chapter, we will focus on going back to the <code>flights</code> data frame in the <code>nycflights13</code> package to look at the relationship between departure delay and arrival delay. We will also discuss the concept of <em>correlation</em> and how it is frequently incorrectly implied to also lead to <em>causation</em>. This chapter also introduces the <code>broom</code> package, which is a useful tool in summarizing the results of model fits in tidy format. You will see examples of the <code>tidy</code>, <code>glance</code>, and <code>augment</code> functions with linear regression.</p>
<!--
- Bootstrap points (Hesterberg)
- Interpreting table of results
    -  P-value: H0: beta1 = 0 vs !=0
    - CI: Range of plausible
R-squared
-->
<div id="needed-packages-6" class="section level3 unnumbered">
<h3>Needed packages</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(mosaic)
<span class="kw">library</span>(dplyr)
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(knitr)
<span class="kw">library</span>(broom)
<span class="kw">library</span>(nycflights13)</code></pre></div>
</div>
<div id="example-alaskan-airlines-delays" class="section level2">
<h2><span class="header-section-number">9.1</span> EXAMPLE: Alaskan Airlines delays</h2>
<p>We’ll next explore the relationship/association of departure delays and arrival delays for a sample of 100 flights departing from New York City in 2013 with Alaskan Airlines.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(nycflights13)
<span class="kw">data</span>(flights)
<span class="kw">set.seed</span>(<span class="dv">2017</span>)

<span class="co"># Load Alaska data, deleting rows that have missing departure delay</span>
<span class="co"># or arrival delay data</span>
alaska_flights &lt;-<span class="st"> </span>flights %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(carrier ==<span class="st"> &quot;AS&quot;</span>) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(!<span class="kw">is.na</span>(dep_delay) &amp;<span class="st"> </span>!<span class="kw">is.na</span>(arr_delay)) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">resample</span>(<span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)

<span class="kw">ggplot</span>(<span class="dt">data =</span> alaska_flights, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> dep_delay, <span class="dt">y =</span> arr_delay)) +<span class="st"> </span>
<span class="st">   </span><span class="kw">geom_point</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:regplot1"></span>
<img src="ismaykim_files/figure-html/regplot1-1.png" alt="Departure and Arrival Flight Delays for a sample of 50 Alaskan flights from NYC" width="\textwidth" />
<p class="caption">
Figure 9.1: Departure and Arrival Flight Delays for a sample of 50 Alaskan flights from NYC
</p>
</div>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.1)</strong> Does there appear to be a linear relationship with arrival delay and departure delay? In other words, could you fit a line to the data and have it explain well how <code>arr_delay</code> increases as <code>dep_delay</code> increases?</p>
<p><strong>(LC9.2)</strong> Is there only one possible line that fits the data “well”? How could you decide on which one is best if there are multiple options?</p>
<hr />
</div>
<div id="correlation" class="section level2">
<h2><span class="header-section-number">9.2</span> Correlation</h2>
<p>One way to measure the linearity between two numerical variables is by using correlation. In fact, the <strong>correlation coefficient</strong> is defined as just that.</p>
<hr />
<p><strong>Definition: Correlation Coefficient</strong></p>
<p>The <em>correlation coefficient</em> measures the strength of linear association between two variables.</p>
<hr />
<p><strong>Properties of the correlation coefficient</strong>:</p>
<p>It is always between -1 and 1, inclusive, where</p>
<ul>
<li>-1 indicates perfect negative relationship</li>
<li>0 indicates no relationship</li>
<li>+1 indicates perfect positive relationship</li>
</ul>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.3)</strong> Make a guess as to the value of the correlation cofficient between <code>arr_delay</code> and <code>dep_delay</code> in the <code>alaska_flights</code> data frame.</p>
<p><strong>(LC9.4)</strong> Do you think that the correlation coefficient between <code>arr_delay</code> and <code>dep_delay</code> is the same as the correlation coefficient between <code>dep_delay</code> and <code>arr_delay</code>? Explain.</p>
<hr />
<p>We can look at a variety of different data sets and their corresponding correlation coefficients in the following plot.</p>
<div class="figure" style="text-align: center"><span id="fig:corr-coefs"></span>
<img src="ismaykim_files/figure-html/corr-coefs-1.png" alt="Different Correlation Coefficients" width="\textwidth" />
<p class="caption">
Figure 9.2: Different Correlation Coefficients
</p>
</div>
<p>We can calculate the correlation coefficient for our example of flight delays via</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">alaska_flights %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">correl =</span> <span class="kw">cor</span>(dep_delay, arr_delay))</code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   correl
##    &lt;dbl&gt;
## 1 0.7908</code></pre>
<p>The sample correlation coefficient is denoted by <span class="math inline">\(r\)</span>. In this case, <span class="math inline">\(r = 0.7908\)</span>.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.5)</strong> Would you quantify the value of <code>correl</code> calculated above as being</p>
<ul>
<li>strongly positively linear,</li>
<li>weakly positively linear,</li>
<li>not linear,</li>
<li>weakly negatively linear, or</li>
<li>strongly positively linear?</li>
</ul>
<p>Discuss your choice.</p>
<hr />
<p>If you’d like a little more practice in determining the linear relationship between two variables by quantifying a correlation coefficient, you should check out the <a href="http://guessthecorrelation.com/">Guess the Correlation</a> game online.</p>
<div id="correlation-does-not-imply-causation" class="section level3">
<h3><span class="header-section-number">9.2.1</span> Correlation does not imply causation</h3>
<p>Just because arrival delays are related to departure delays in a somewhat linear fashion, we can’t say with certaintly that arrival delays are caused <strong>entirely</strong> by departure delays. Certainly it appears that as one increases, the other tends to increase, but that might not always be the case.</p>
<p>Causation is a tricky problem and frequently takes carefully designed experiments. These experiments remove confounding variables and only focus on the behavior of one variable in the presence of the levels of the other variable(s).</p>
<p>Be careful as you read studies to make sure that the writers aren’t falling into this fallacy of correlation implying causation. If you spot one, you may want to send them a link to <a href="http://www.tylervigen.com/spurious-correlations">Spurious Correlations</a>.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.6)</strong> What are some other confounding variables besides departure delay that could attribute to an increase in arrival delays? Remember that a variable is something that has to <strong>vary</strong>!</p>
<hr />
</div>
</div>
<div id="linear-regression" class="section level2">
<h2><span class="header-section-number">9.3</span> Linear regression</h2>
<p>So we see above that there is a strong positive association between these delay variables. Let’s say that we are waiting for our flight to leave New York City on Alaskan and we are told that our flight is going to be delayed 25 minutes. What could we predict for our arrival delay based on the plot in Figure <a href="9-regress.html#fig:regplot1">9.1</a>?</p>
<p>It may be hard to pick a particular value here, especially after just going over confidence intervals in Chapter <a href="8-ci.html#ci">8</a>. One way to do this would be to fit a line that fits the data best and then use the predicted <code>arr_delay</code> value from that line for <code>dep_delay = 25</code> as our prediction. But what is meant by “fits the data best”?</p>
<p>The least squares/best fitting/linear regression line has been fit to the data below.</p>
<div class="figure" style="text-align: center"><span id="fig:with-reg"></span>
<img src="ismaykim_files/figure-html/with-reg-1.png" alt="Regression line fit on delays" width="\textwidth" />
<p class="caption">
Figure 9.3: Regression line fit on delays
</p>
</div>
<p>Here <code>lm</code> corresponds to “linear model” and we’ll see its use again in a bit when we find the values that define this line.</p>
<div id="understanding-linear-regression-basics" class="section level3">
<h3><span class="header-section-number">9.3.1</span> Understanding linear regression basics</h3>
<p>Let’s choose an arbitrary point on the graph and label it the color blue.</p>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-132-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>Now consider this point’s <em>deviation</em> from the regression line.</p>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-133-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>Do this for another point.</p>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-134-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>And for another point.</p>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-135-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>We could repeat this process for each of the points in our sample. The pattern that emerges here is that the regression line minimizes the sum of the squared arrow lengths (i.e., the least squares) for all of the points.</p>
<p>As you look at these points you might think that a different line could fit the data better based on this criteria. That isn’t the case though and it can be shown via calculus (omitted here) that this line minimizes the sum of the squared residuals for these 50 points.</p>
</div>
<div id="the-equation-of-the-line" class="section level3">
<h3><span class="header-section-number">9.3.2</span> The equation of the line</h3>
<p>We can use R and the <code>lm</code> function to retrieve the equation of the line of best fit here in red. A simple linear regression such as this will produce two coeffients: one for the <em><span class="math inline">\(y\)</span>-intercept</em> and one for the <em>slope</em>. We can use the <code>tidy</code> function in the <code>broom</code> package to extract these coefficients from the model fit.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">delay_fit &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> arr_delay ~<span class="st"> </span>dep_delay, <span class="dt">data =</span> alaska_flights)
<span class="kw">tidy</span>(delay_fit) %&gt;%<span class="st"> </span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-14.155</td>
<td align="right">2.809</td>
<td align="right">-5.038</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">dep_delay</td>
<td align="right">1.218</td>
<td align="right">0.136</td>
<td align="right">8.951</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>In general, the equation of the line of best fit for a sample is <span class="math display">\[\hat{y} = b_0 + b_1 x.\]</span> Thus, our equation is <span class="math inline">\(\hat{y} = -14.155 + 1.2177 \, x.\)</span> It is usually preferred to actually write the names of the variables instead of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>: <span class="math display">\[\widehat{arr\_delay} = -14.155 + 1.2177 \, dep\_delay.\]</span></p>
<p>We can also extract the coefficients by using the <code>coef</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(delay_fit)</code></pre></div>
<pre><code>## (Intercept)   dep_delay 
##     -14.155       1.218</code></pre>
</div>
<div id="interpreting-the-slope" class="section level3">
<h3><span class="header-section-number">9.3.3</span> Interpreting the slope</h3>
<p>After you have determined your line of best fit, it is good practice to interpret the results to see if they make sense. Slope is defined as rise over run or the change in <span class="math inline">\(y\)</span> for every one unit increase in <span class="math inline">\(x\)</span>. For our specific example, we can say that for every one <strong>minute</strong> increase in the departure delay of Alaskan Airlines flights from NYC, we can expect the corresponding arrival delay to be 1.22 minutes more.</p>
<p>This estimate does make some practical sense. It would be strange if arrival delays went down as departure delays increased. We also expect that the longer a flight is delayed on departure, the more likely the longer a flight is delayed on arrival. Remember that we are also using data here to make a guess as to how the population of all Alaskan flights might behave with regards to departure delays and arrival delays, so just as with other sampling procedures there is also variability in the sample estimates for the regression line.</p>
</div>
<div id="predicting-values" class="section level3">
<h3><span class="header-section-number">9.3.4</span> Predicting values</h3>
<p>Getting back to our hypothetical flight that has been delayed 25 minutes, we can use the <code>augment</code> function in the <code>broom</code> package to get the fitted arrival delay value:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">delay_fit %&gt;%<span class="st"> </span><span class="kw">augment</span>(<span class="dt">newdata =</span> <span class="kw">data_frame</span>(<span class="dt">dep_delay =</span> <span class="dv">25</span>))</code></pre></div>
<pre><code>##   dep_delay .fitted .se.fit
## 1        25   16.29   3.967</code></pre>
<p>Note the use of the <code>data_frame</code> function here, which must be used since <code>newdata</code> is expecting a data frame as its argument. We must also specify that we are plugging in 25 for the value of <code>dep_delay</code> here. We can see that the line predicted an arrival delay of 16.29 minutes based on our 25 minute departure delay. This also does make some sense since flights that aren’t delayed greatly from the beginning to tend to make up time in the air to compensate.</p>
<p><strong>Important note</strong>: The correlation coefficient and the slope of the regression line are not the same thing. They will always share the same sign (positive correlation coefficients correspond to positive slope coefficients and the same holds true for negative values), but you can’t make any more conclusions about them than that.</p>
<p>For example, say we have 3 groups of points:</p>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-138-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>Their regression lines have different slopes, but <span class="math inline">\(r = 1\)</span> for all 3. In other words, all three groups of points have a perfect (positive) linear relationship.</p>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-139-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="inference-for-regression" class="section level2">
<h2><span class="header-section-number">9.4</span> Inference for regression</h2>
<p>The population least squares line is defined by the formula <span class="math inline">\(y = \beta_0 + \beta_1 x + \epsilon\)</span>. Here <span class="math inline">\(\epsilon\)</span> represents the error term. It corresponds to the part of the response variable <span class="math inline">\(y\)</span> that remains unexplained after considering the predictor variable <span class="math inline">\(x\)</span>. Often it is standard practice to assume that this error term follows a normal distribution. We will focus on checking whether that assumption is valid in Section <a href="9-regress.html#resid">9.5</a>.</p>
<p>In the population least squares line <span class="math inline">\(y = \beta_0 + \beta_1 x + \epsilon\)</span>, we can see that if <span class="math inline">\(\beta_1 = 0\)</span> there is no relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. If <span class="math inline">\(\beta_1 = 0\)</span>, <span class="math inline">\(y = \beta_0 + \epsilon\)</span>. Therefore, <span class="math inline">\(y\)</span> does not depend on <span class="math inline">\(x\)</span> at all in the equation. A hypothesis test is frequently conducted to check whether a relationship exists between two numerical variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p>
<p>We can also use the concept of shuffling to determine the standard error of our null distribution and conduct a hypothesis test for a population slope. Let’s go back to our example on Alaskan flights that represent a sample of all Alaskan flights departing NYC in 2013. Let’s test to see if we have evidence that a <em>positive</em> relationship exists between the departure delay and arrival delay for Alaskan flights. We will set up this hypothesis testing process as we have each before via the “There is Only One Test” diagram in Figure <a href="7-hypo.html#fig:htdowney">7.1</a>.</p>
<div id="data-2" class="section level3">
<h3><span class="header-section-number">9.4.1</span> Data</h3>
<p>Our data is stored in <code>alaska_flights</code> and we are focused on the 50 measurements of <code>dep_delay</code> and <code>arr_delay</code> there.</p>
</div>
<div id="test-statistic-delta-2" class="section level3">
<h3><span class="header-section-number">9.4.2</span> Test Statistic <span class="math inline">\(\delta\)</span></h3>
<p>Our test statistic here is the sample slope coefficient that we denote with <span class="math inline">\(b_1\)</span>.</p>
</div>
<div id="observed-effect-delta-2" class="section level3">
<h3><span class="header-section-number">9.4.3</span> Observed effect <span class="math inline">\(\delta^*\)</span></h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(b1_obs &lt;-<span class="st"> </span><span class="kw">tidy</span>(delay_fit)$estimate[<span class="dv">2</span>])</code></pre></div>
<pre><code>## [1] 1.218</code></pre>
<p>The calculated slope value from our observed sample is <span class="math inline">\(b_1 = 1.2177\)</span>.</p>
</div>
<div id="model-of-h_0-2" class="section level3">
<h3><span class="header-section-number">9.4.4</span> Model of <span class="math inline">\(H_0\)</span></h3>
<p>We are looking to see if a positive relationship exists so <span class="math inline">\(H_a: \beta_1 &gt; 0\)</span>. Our null hypothesis is always in terms of equality so we have <span class="math inline">\(H_0: \beta_1 = 0\)</span>.</p>
</div>
<div id="simulated-data-2" class="section level3">
<h3><span class="header-section-number">9.4.5</span> Simulated Data</h3>
<p>Now to simulate the null hypothesis being true and recreating how our sample was created, we need to think about what it means for <span class="math inline">\(\beta_1\)</span> to be zero. If <span class="math inline">\(\beta_1 = 0\)</span>, we said above that there is no relationship between the departure delay and arrival delay. If there is no relationship, then any one of the arrival delay values could have just as likely occurred with any of the other departure delay values instead of the one that it actually did fall with. We, therefore, have another example of shuffling in our simulating of data.</p>
<p><strong>Tactile simulation</strong></p>
<p>We could use a deck of 100 note cards to create a tactile simulation of this shuffling process. We would write the 50 different values of departure delays on each of the 50 cards, one per card. We would then do the same thing for the 50 arrival delays putting them on one per card.</p>
<p>Next, we would lay out each of the 50 departure delay cards and we would shuffle the arrival delay deck. Then, after shuffling the deck well, we would disperse the cards one per each one of the departure delay cards. We would then enter these new values in for arrival delay and compute a sample slope based on this shuffling. We could repeat this process many times, keeping track of our sample slope after each shuffle.</p>
</div>
<div id="distribution-of-delta-under-h_0-2" class="section level3">
<h3><span class="header-section-number">9.4.6</span> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></h3>
<p>We can build our randomization distribution in much the same way we did before using the <code>do</code> and <code>shuffle</code> functions. Here we will take advantage of the <code>coef</code> function we saw earlier to extract the slope and intercept coefficients. (Our focus will be on the slope here though.)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rand_distn &lt;-<span class="st"> </span>mosaic::<span class="kw">do</span>(<span class="dv">10000</span>) *
<span class="st">  </span>(<span class="kw">lm</span>(<span class="dt">formula =</span> <span class="kw">shuffle</span>(arr_delay) ~<span class="st"> </span>dep_delay, <span class="dt">data =</span> alaska_flights) %&gt;%
<span class="st">     </span><span class="kw">coef</span>())
<span class="kw">names</span>(rand_distn)</code></pre></div>
<pre><code>## [1] &quot;Intercept&quot; &quot;dep_delay&quot;</code></pre>
<p>We see that the names of our columns are <code>Intercept</code> and <code>dep_delay</code>. We want to look at <code>dep_delay</code> since that corresponds to the slope coefficients.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> rand_distn, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> dep_delay)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-141-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
</div>
<div id="the-p-value-2" class="section level3">
<h3><span class="header-section-number">9.4.7</span> The p-value</h3>
<p>Recall that we want to see where our observed sample slope <span class="math inline">\(\delta^* = 1.2177\)</span> falls on this distribution and then count all of the values to the right of it corresponding to <span class="math inline">\(H_a: \beta_0 &gt; 0\)</span>. To get a sense for where our values falls, we can shade all values at least as big as <span class="math inline">\(\delta^*\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> rand_distn, <span class="kw">aes</span>(<span class="dt">x =</span> dep_delay, <span class="dt">fill =</span> (dep_delay &gt;=<span class="st"> </span>b1_obs))) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-142"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-142-1.png" alt="Shaded histogram to show p-value" width="\textwidth" />
<p class="caption">
Figure 9.4: Shaded histogram to show p-value
</p>
</div>
<p>Since 1.2177 falls far to the right of this plot, we can say that we have a <span class="math inline">\(p\)</span>-value of 0. We, thus, have evidence to reject the null hypothesis in support of there being a positive association between the departure delay and arrival delay of all Alaskan flights from NYC in 2013.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.7)</strong> Repeat the inference above but this time for the correlation coefficient instead of the slope.</p>
<p><strong>(LC9.8)</strong> Use bootstrapping (of points) to determine a range of possible values for the population slope comparing departure delays to arrival delays for Alaskan flights in 2013 from NYC.</p>
<hr />
</div>
</div>
<div id="resid" class="section level2">
<h2><span class="header-section-number">9.5</span> Residual analysis</h2>
<p>The following diagram will help you to keep track of what is meant by a residual.</p>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-143-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>Here, <span class="math inline">\(y_i\)</span> is an observed value of the <code>arr_delay</code> variable. <span class="math inline">\(i\)</span> ranges from 1 to 50. For this example, it is the vertical component of the blue dot. <span class="math inline">\(\hat{y}_i\)</span> is the fitted value–the <code>arr_delay</code> value that is being pointed to on the red line. The residual is <span class="math display">\[\hat{\epsilon}_i = y_i - \hat{y}_i.\]</span> <strong>Note the order here!</strong> You start at the non-pointy end of the arrow (<span class="math inline">\(y_i\)</span>) and then subtract away what comes at the point (<span class="math inline">\(\hat{y_i}\)</span>).</p>
</div>
<div id="conditions-for-regression" class="section level2">
<h2><span class="header-section-number">9.6</span> Conditions for regression</h2>
<p>In order for regression to be valid, we have three conditions to check:</p>
<ol style="list-style-type: decimal">
<li>Equal variances across explanatory variable (Check residual plot for fan-shaped patterns.)</li>
<li>Independent observations, errors, and predictor variables (Check residual plot for no time series-like patterns.)</li>
<li>Nearly normal residuals (Check quantile-quantile plot of standardized residuals.)</li>
</ol>
<p>As you can see from the things to check after the conditions <em>residuals</em> will play a large role in determining whether the conditions are met. <em>Residuals</em> are estimates for the error term <span class="math inline">\(\epsilon\)</span> we discussed earlier, and this is a big reason why they play an important role in validating regression assumptions.</p>
<p><strong>Residual plot</strong></p>
<p>To construct a residual plot we will analyze data from the <code>augment</code> function in <code>broom</code>. Specifically, we are interested in the <code>.fitted</code> and <code>.resid</code> variables there:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fits &lt;-<span class="st"> </span><span class="kw">augment</span>(delay_fit)
<span class="kw">ggplot</span>(<span class="dt">data =</span> fits, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> .fitted, <span class="dt">y =</span> .resid)) +
<span class="st">  </span><span class="kw">geom_point</span>() +
<span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">slope =</span> <span class="dv">0</span>, <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/resid-plot-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p><strong>Quantile-quantile plot</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> fits, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">sample =</span> .resid)) +
<span class="st">  </span><span class="kw">stat_qq</span>()</code></pre></div>
<p><img src="ismaykim_files/figure-html/qqplot1-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p><strong>Checking conditions</strong>:</p>
<ol style="list-style-type: decimal">
<li><p>We are looking to see if the points are scattered about the blue line at 0 relatively evenly as we look from left to right. We have some reason for concern here as the large lump of values on the left are much more dispersed than those on the right.</p></li>
<li><p>The second condition is invalidated if there is a trigonometric pattern of up and down throughout the residual plot. That is not the case here.</p></li>
<li><p>We look at the <em>quantile-quantile plot</em> (Q-Q plot for sure) for the third condition. We are looking to see if the residuals fall on a straight line with what we would expect if they were normally distributed. We see some curvature here as well. We should begin to wonder if regression was valid here with both condition 1 and condition 3 in question.</p></li>
</ol>
<p>We have reason to doubt whether a linear regression is valid here. Unfortunately, all too frequently regressions are run without checking these assumptions carefully. While small deviations from the assumptions can be OK, larger violations can completely invalidate the results and make any inferences improbable and questionable.</p>
</div>
<div id="conclusion-5" class="section level2">
<h2><span class="header-section-number">9.7</span> Conclusion</h2>
<div id="script-of-r-code-5" class="section level3">
<h3><span class="header-section-number">9.7.1</span> Script of R code</h3>
<p>An R script file of all R code used in this chapter is available <a href="http://ismayc.github.io/moderndiver-book/scripts/09-regress.R">here</a>.</p>
</div>
<div id="whats-to-come-6" class="section level3">
<h3><span class="header-section-number">9.7.2</span> What’s to come?</h3>
<p>In the last chapter of the textbook, we’ll summarize the purpose of this book as well as present an excellent example of what goes into making an effective story via data.</p>

</div>
</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="8-ci.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="10-effective-data-storytelling.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ismayc/moderndiver-book/edit/master/09-regress.Rmd",
"text": "Edit"
},
"download": ["ismaykim.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
