<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>ModernDive</title>
  <meta name="description" content="Combining statistical and computational thinking to make sense of data. An evolution of the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown">
  <meta name="generator" content="bookdown 0.4 and GitBook 2.6.7">

  <meta property="og:title" content="ModernDive" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Combining statistical and computational thinking to make sense of data. An evolution of the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown" />
  <meta name="github-repo" content="ismayc/moderndiver-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="ModernDive" />
  
  <meta name="twitter:description" content="Combining statistical and computational thinking to make sense of data. An evolution of the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown" />
  

<meta name="author" content="Chester Ismay and Albert Y. Kim">


<meta name="date" content="2017-02-09">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="A-appendixA.html">
<link rel="next" href="C-appendixC.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-0.9/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.4/dygraphs.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89938436-1', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preamble</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#principles-of-this-book---for-instructors"><i class="fa fa-check"></i><b>1.1</b> Principles of this Book - For Instructors</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#contribute"><i class="fa fa-check"></i><b>1.2</b> Contribute</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#getting-started---for-students"><i class="fa fa-check"></i><b>1.3</b> Getting Started - For Students</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#colophon"><i class="fa fa-check"></i>Colophon</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-intro.html"><a href="2-intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="2-intro.html"><a href="2-intro.html#preamble-1"><i class="fa fa-check"></i><b>2.1</b> Preamble</a></li>
<li class="chapter" data-level="2.2" data-path="2-intro.html"><a href="2-intro.html#three-driving-data-sources"><i class="fa fa-check"></i><b>2.2</b> Three driving data sources</a></li>
<li class="chapter" data-level="2.3" data-path="2-intro.html"><a href="2-intro.html#datascience-pipeline"><i class="fa fa-check"></i><b>2.3</b> Data/science pipeline</a></li>
<li class="chapter" data-level="2.4" data-path="2-intro.html"><a href="2-intro.html#reproducibility"><i class="fa fa-check"></i><b>2.4</b> Reproducibility</a></li>
<li class="chapter" data-level="2.5" data-path="2-intro.html"><a href="2-intro.html#who-is-this-book-for"><i class="fa fa-check"></i><b>2.5</b> Who is this book for?</a></li>
</ul></li>
<li class="part"><span><b>I Data Exploration</b></span></li>
<li class="chapter" data-level="3" data-path="3-tidy.html"><a href="3-tidy.html"><i class="fa fa-check"></i><b>3</b> Tidy Data</a><ul>
<li class="chapter" data-level="" data-path="3-tidy.html"><a href="3-tidy.html#needed-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="3.1" data-path="3-tidy.html"><a href="3-tidy.html#what-is-tidy-data"><i class="fa fa-check"></i><b>3.1</b> What is tidy data?</a></li>
<li class="chapter" data-level="3.2" data-path="3-tidy.html"><a href="3-tidy.html#datasets-in-the-nycflights13-package"><i class="fa fa-check"></i><b>3.2</b> Datasets in the <code>nycflights13</code> package</a></li>
<li class="chapter" data-level="3.3" data-path="3-tidy.html"><a href="3-tidy.html#how-is-flights-tidy"><i class="fa fa-check"></i><b>3.3</b> How is <code>flights</code> tidy?</a><ul>
<li class="chapter" data-level="3.3.1" data-path="3-tidy.html"><a href="3-tidy.html#identification-variables"><i class="fa fa-check"></i><b>3.3.1</b> Identification variables</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="3-tidy.html"><a href="3-tidy.html#normal-forms-of-data"><i class="fa fa-check"></i><b>3.4</b> Normal forms of data</a></li>
<li class="chapter" data-level="3.5" data-path="3-tidy.html"><a href="3-tidy.html#whats-to-come"><i class="fa fa-check"></i><b>3.5</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-viz.html"><a href="4-viz.html"><i class="fa fa-check"></i><b>4</b> Data Visualization via ggplot2</a><ul>
<li class="chapter" data-level="" data-path="4-viz.html"><a href="4-viz.html#needed-packages-1"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="4.1" data-path="4-viz.html"><a href="4-viz.html#grammarofgraphics"><i class="fa fa-check"></i><b>4.1</b> The Grammar of Graphics</a><ul>
<li class="chapter" data-level="4.1.1" data-path="4-viz.html"><a href="4-viz.html#components-of-grammar"><i class="fa fa-check"></i><b>4.1.1</b> Components of Grammar</a></li>
<li class="chapter" data-level="4.1.2" data-path="4-viz.html"><a href="4-viz.html#napoleans-march-on-moscow"><i class="fa fa-check"></i><b>4.1.2</b> Napolean’s March on Moscow</a></li>
<li class="chapter" data-level="4.1.3" data-path="4-viz.html"><a href="4-viz.html#other-components-of-the-grammar"><i class="fa fa-check"></i><b>4.1.3</b> Other Components of the Grammar</a></li>
<li class="chapter" data-level="4.1.4" data-path="4-viz.html"><a href="4-viz.html#the-ggplot2-package"><i class="fa fa-check"></i><b>4.1.4</b> The ggplot2 Package</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="4-viz.html"><a href="4-viz.html#five-named-graphs---the-5ng"><i class="fa fa-check"></i><b>4.2</b> Five Named Graphs - The 5NG</a></li>
<li class="chapter" data-level="4.3" data-path="4-viz.html"><a href="4-viz.html#scatterplots"><i class="fa fa-check"></i><b>4.3</b> 5NG#1: Scatter-plots</a><ul>
<li class="chapter" data-level="4.3.1" data-path="4-viz.html"><a href="4-viz.html#geompoint"><i class="fa fa-check"></i><b>4.3.1</b> Scatter-plots via geom_point</a></li>
<li class="chapter" data-level="4.3.2" data-path="4-viz.html"><a href="4-viz.html#over-plotting"><i class="fa fa-check"></i><b>4.3.2</b> Over-Plotting</a></li>
<li class="chapter" data-level="4.3.3" data-path="4-viz.html"><a href="4-viz.html#summary"><i class="fa fa-check"></i><b>4.3.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="4-viz.html"><a href="4-viz.html#linegraphs"><i class="fa fa-check"></i><b>4.4</b> 5NG#2: Line-graphs</a><ul>
<li class="chapter" data-level="4.4.1" data-path="4-viz.html"><a href="4-viz.html#geomline"><i class="fa fa-check"></i><b>4.4.1</b> Line-graphs via geom_line</a></li>
<li class="chapter" data-level="4.4.2" data-path="4-viz.html"><a href="4-viz.html#summary-1"><i class="fa fa-check"></i><b>4.4.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="4-viz.html"><a href="4-viz.html#histograms"><i class="fa fa-check"></i><b>4.5</b> 5NG#3: Histograms</a><ul>
<li class="chapter" data-level="4.5.1" data-path="4-viz.html"><a href="4-viz.html#geomhistogram"><i class="fa fa-check"></i><b>4.5.1</b> Histograms via geom_histogram</a></li>
<li class="chapter" data-level="4.5.2" data-path="4-viz.html"><a href="4-viz.html#adjustbins"><i class="fa fa-check"></i><b>4.5.2</b> Adjusting the Bins</a></li>
<li class="chapter" data-level="4.5.3" data-path="4-viz.html"><a href="4-viz.html#summary-2"><i class="fa fa-check"></i><b>4.5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="4-viz.html"><a href="4-viz.html#facets"><i class="fa fa-check"></i><b>4.6</b> Facets</a></li>
<li class="chapter" data-level="4.7" data-path="4-viz.html"><a href="4-viz.html#ng4-boxplots"><i class="fa fa-check"></i><b>4.7</b> 5NG#4: Boxplots</a><ul>
<li class="chapter" data-level="4.7.1" data-path="4-viz.html"><a href="4-viz.html#geomboxplot"><i class="fa fa-check"></i><b>4.7.1</b> Boxplots via geom_boxplot</a></li>
<li class="chapter" data-level="4.7.2" data-path="4-viz.html"><a href="4-viz.html#summary-3"><i class="fa fa-check"></i><b>4.7.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="4-viz.html"><a href="4-viz.html#geombar"><i class="fa fa-check"></i><b>4.8</b> 5NG#5: Barplots</a><ul>
<li class="chapter" data-level="4.8.1" data-path="4-viz.html"><a href="4-viz.html#barplots-via-geom_bar"><i class="fa fa-check"></i><b>4.8.1</b> Barplots via geom_bar</a></li>
<li class="chapter" data-level="4.8.2" data-path="4-viz.html"><a href="4-viz.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>4.8.2</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="4.8.3" data-path="4-viz.html"><a href="4-viz.html#using-barplots-to-compare-two-variables"><i class="fa fa-check"></i><b>4.8.3</b> Using barplots to compare two variables</a></li>
<li class="chapter" data-level="4.8.4" data-path="4-viz.html"><a href="4-viz.html#summary-4"><i class="fa fa-check"></i><b>4.8.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="4-viz.html"><a href="4-viz.html#conclusion"><i class="fa fa-check"></i><b>4.9</b> Conclusion</a><ul>
<li class="chapter" data-level="4.9.1" data-path="4-viz.html"><a href="4-viz.html#resources"><i class="fa fa-check"></i><b>4.9.1</b> Resources</a></li>
<li class="chapter" data-level="4.9.2" data-path="4-viz.html"><a href="4-viz.html#script-of-r-code"><i class="fa fa-check"></i><b>4.9.2</b> Script of R code</a></li>
<li class="chapter" data-level="4.9.3" data-path="4-viz.html"><a href="4-viz.html#whats-to-come-1"><i class="fa fa-check"></i><b>4.9.3</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-manip.html"><a href="5-manip.html"><i class="fa fa-check"></i><b>5</b> Data Manipulation via dplyr</a><ul>
<li class="chapter" data-level="" data-path="5-manip.html"><a href="5-manip.html#needed-packages-2"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="5.1" data-path="5-manip.html"><a href="5-manip.html#the-pipe"><i class="fa fa-check"></i><b>5.1</b> The pipe <code>%&gt;%</code></a></li>
<li class="chapter" data-level="5.2" data-path="5-manip.html"><a href="5-manip.html#five-main-verbs---the-5mv"><i class="fa fa-check"></i><b>5.2</b> Five Main Verbs - The 5MV</a><ul>
<li class="chapter" data-level="5.2.1" data-path="5-manip.html"><a href="5-manip.html#filter"><i class="fa fa-check"></i><b>5.2.1</b> 5MV#1: Filter observations using filter</a></li>
<li class="chapter" data-level="5.2.2" data-path="5-manip.html"><a href="5-manip.html#mv2-summarize-variables-using-summarize"><i class="fa fa-check"></i><b>5.2.2</b> 5MV#2: Summarize variables using summarize</a></li>
<li class="chapter" data-level="5.2.3" data-path="5-manip.html"><a href="5-manip.html#mv3-group-rows-using-group_by"><i class="fa fa-check"></i><b>5.2.3</b> 5MV#3: Group rows using group_by</a></li>
<li class="chapter" data-level="5.2.4" data-path="5-manip.html"><a href="5-manip.html#mv4-create-new-variableschange-old-variables-using-mutate"><i class="fa fa-check"></i><b>5.2.4</b> 5MV#4: Create new variables/change old variables using mutate</a></li>
<li class="chapter" data-level="5.2.5" data-path="5-manip.html"><a href="5-manip.html#arrange"><i class="fa fa-check"></i><b>5.2.5</b> 5MV#5: Reorder the data frame using arrange</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="5-manip.html"><a href="5-manip.html#joining-data-frames"><i class="fa fa-check"></i><b>5.3</b> Joining data frames</a><ul>
<li class="chapter" data-level="5.3.1" data-path="5-manip.html"><a href="5-manip.html#joining-by-key-variables"><i class="fa fa-check"></i><b>5.3.1</b> Joining by Key Variables</a></li>
<li class="chapter" data-level="5.3.2" data-path="5-manip.html"><a href="5-manip.html#joining-by-key-variables-with-different-names"><i class="fa fa-check"></i><b>5.3.2</b> Joining by Key Variables with Different Names</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="5-manip.html"><a href="5-manip.html#optional-other-verbs"><i class="fa fa-check"></i><b>5.4</b> Optional: Other verbs</a><ul>
<li class="chapter" data-level="5.4.1" data-path="5-manip.html"><a href="5-manip.html#select"><i class="fa fa-check"></i><b>5.4.1</b> Select variables using select</a></li>
<li class="chapter" data-level="5.4.2" data-path="5-manip.html"><a href="5-manip.html#rename"><i class="fa fa-check"></i><b>5.4.2</b> Rename variables using rename</a></li>
<li class="chapter" data-level="5.4.3" data-path="5-manip.html"><a href="5-manip.html#find-the-top-number-of-values-using-top_n"><i class="fa fa-check"></i><b>5.4.3</b> Find the top number of values using top_n</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="5-manip.html"><a href="5-manip.html#conclusion-1"><i class="fa fa-check"></i><b>5.5</b> Conclusion</a><ul>
<li class="chapter" data-level="5.5.1" data-path="5-manip.html"><a href="5-manip.html#resources-1"><i class="fa fa-check"></i><b>5.5.1</b> Resources</a></li>
<li class="chapter" data-level="5.5.2" data-path="5-manip.html"><a href="5-manip.html#script-of-r-code-1"><i class="fa fa-check"></i><b>5.5.2</b> Script of R code</a></li>
<li class="chapter" data-level="5.5.3" data-path="5-manip.html"><a href="5-manip.html#whats-to-come-2"><i class="fa fa-check"></i><b>5.5.3</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Inference</b></span></li>
<li class="chapter" data-level="6" data-path="6-sim.html"><a href="6-sim.html"><i class="fa fa-check"></i><b>6</b> Simulating Randomness via mosaic</a><ul>
<li class="chapter" data-level="" data-path="6-sim.html"><a href="6-sim.html#needed-packages-3"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="6.1" data-path="6-sim.html"><a href="6-sim.html#random-sampling"><i class="fa fa-check"></i><b>6.1</b> Random sampling</a><ul>
<li class="chapter" data-level="6.1.1" data-path="6-sim.html"><a href="6-sim.html#tasting-soup"><i class="fa fa-check"></i><b>6.1.1</b> Tasting soup</a></li>
<li class="chapter" data-level="6.1.2" data-path="6-sim.html"><a href="6-sim.html#common-terms"><i class="fa fa-check"></i><b>6.1.2</b> Common terms</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="6-sim.html"><a href="6-sim.html#visualizing-sampling"><i class="fa fa-check"></i><b>6.2</b> Visualizing sampling</a><ul>
<li class="chapter" data-level="6.2.1" data-path="6-sim.html"><a href="6-sim.html#sampling-distribution"><i class="fa fa-check"></i><b>6.2.1</b> Sampling distribution</a></li>
<li class="chapter" data-level="6.2.2" data-path="6-sim.html"><a href="6-sim.html#repeated-sampling-via-do"><i class="fa fa-check"></i><b>6.2.2</b> Repeated sampling via <code>do</code></a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="6-sim.html"><a href="6-sim.html#simulation"><i class="fa fa-check"></i><b>6.3</b> Simulation</a></li>
<li class="chapter" data-level="6.4" data-path="6-sim.html"><a href="6-sim.html#review-of-mosaic-simulation-functions"><i class="fa fa-check"></i><b>6.4</b> Review of <code>mosaic</code> simulation functions</a></li>
<li class="chapter" data-level="6.5" data-path="6-sim.html"><a href="6-sim.html#conclusion-2"><i class="fa fa-check"></i><b>6.5</b> Conclusion</a><ul>
<li class="chapter" data-level="6.5.1" data-path="6-sim.html"><a href="6-sim.html#script-of-r-code-2"><i class="fa fa-check"></i><b>6.5.1</b> Script of R code</a></li>
<li class="chapter" data-level="6.5.2" data-path="6-sim.html"><a href="6-sim.html#whats-to-come-3"><i class="fa fa-check"></i><b>6.5.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-hypo.html"><a href="7-hypo.html"><i class="fa fa-check"></i><b>7</b> Hypothesis Testing</a><ul>
<li class="chapter" data-level="" data-path="7-hypo.html"><a href="7-hypo.html#needed-packages-4"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="7.1" data-path="7-hypo.html"><a href="7-hypo.html#when-inference-is-not-needed"><i class="fa fa-check"></i><b>7.1</b> When Inference Is Not Needed</a></li>
<li class="chapter" data-level="7.2" data-path="7-hypo.html"><a href="7-hypo.html#basics-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.2</b> Basics of Hypothesis Testing</a></li>
<li class="chapter" data-level="7.3" data-path="7-hypo.html"><a href="7-hypo.html#trial"><i class="fa fa-check"></i><b>7.3</b> Criminal trial analogy</a><ul>
<li class="chapter" data-level="7.3.1" data-path="7-hypo.html"><a href="7-hypo.html#two-possible-conclusions"><i class="fa fa-check"></i><b>7.3.1</b> Two possible conclusions</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="7-hypo.html"><a href="7-hypo.html#types-of-errors-in-hypothesis-testing"><i class="fa fa-check"></i><b>7.4</b> Types of Errors in Hypothesis Testing</a><ul>
<li class="chapter" data-level="7.4.1" data-path="7-hypo.html"><a href="7-hypo.html#logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.4.1</b> Logic of Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="7-hypo.html"><a href="7-hypo.html#statistical-significance"><i class="fa fa-check"></i><b>7.5</b> Statistical Significance</a></li>
<li class="chapter" data-level="7.6" data-path="7-hypo.html"><a href="7-hypo.html#example-revisiting-the-lady-tasting-tea"><i class="fa fa-check"></i><b>7.6</b> EXAMPLE: Revisiting the Lady Tasting Tea</a><ul>
<li class="chapter" data-level="7.6.1" data-path="7-hypo.html"><a href="7-hypo.html#data"><i class="fa fa-check"></i><b>7.6.1</b> Data</a></li>
<li class="chapter" data-level="7.6.2" data-path="7-hypo.html"><a href="7-hypo.html#test-statistic-delta"><i class="fa fa-check"></i><b>7.6.2</b> Test Statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="7.6.3" data-path="7-hypo.html"><a href="7-hypo.html#observed-effect-delta"><i class="fa fa-check"></i><b>7.6.3</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="7.6.4" data-path="7-hypo.html"><a href="7-hypo.html#model-of-h_0"><i class="fa fa-check"></i><b>7.6.4</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.6.5" data-path="7-hypo.html"><a href="7-hypo.html#simulated-data"><i class="fa fa-check"></i><b>7.6.5</b> Simulated Data</a></li>
<li class="chapter" data-level="7.6.6" data-path="7-hypo.html"><a href="7-hypo.html#distribution-of-delta-under-h_0"><i class="fa fa-check"></i><b>7.6.6</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.6.7" data-path="7-hypo.html"><a href="7-hypo.html#the-p-value"><i class="fa fa-check"></i><b>7.6.7</b> The p-value</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="7-hypo.html"><a href="7-hypo.html#example-comparing-two-means"><i class="fa fa-check"></i><b>7.7</b> EXAMPLE: Comparing two means</a><ul>
<li class="chapter" data-level="7.7.1" data-path="7-hypo.html"><a href="7-hypo.html#randomizationpermutation"><i class="fa fa-check"></i><b>7.7.1</b> Randomization/Permutation</a></li>
<li class="chapter" data-level="7.7.2" data-path="7-hypo.html"><a href="7-hypo.html#comparing-action-and-romance-movies"><i class="fa fa-check"></i><b>7.7.2</b> Comparing Action and Romance Movies</a></li>
<li class="chapter" data-level="7.7.3" data-path="7-hypo.html"><a href="7-hypo.html#sampling-rightarrow-randomization"><i class="fa fa-check"></i><b>7.7.3</b> Sampling <span class="math inline">\(\rightarrow\)</span> Randomization</a></li>
<li class="chapter" data-level="7.7.4" data-path="7-hypo.html"><a href="7-hypo.html#data-1"><i class="fa fa-check"></i><b>7.7.4</b> Data</a></li>
<li class="chapter" data-level="7.7.5" data-path="7-hypo.html"><a href="7-hypo.html#model-of-h_0-1"><i class="fa fa-check"></i><b>7.7.5</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.7.6" data-path="7-hypo.html"><a href="7-hypo.html#test-statistic-delta-1"><i class="fa fa-check"></i><b>7.7.6</b> Test Statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="7.7.7" data-path="7-hypo.html"><a href="7-hypo.html#observed-effect-delta-1"><i class="fa fa-check"></i><b>7.7.7</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="7.7.8" data-path="7-hypo.html"><a href="7-hypo.html#simulated-data-1"><i class="fa fa-check"></i><b>7.7.8</b> Simulated Data</a></li>
<li class="chapter" data-level="7.7.9" data-path="7-hypo.html"><a href="7-hypo.html#distribution-of-delta-under-h_0-1"><i class="fa fa-check"></i><b>7.7.9</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.7.10" data-path="7-hypo.html"><a href="7-hypo.html#the-p-value-1"><i class="fa fa-check"></i><b>7.7.10</b> The p-value</a></li>
<li class="chapter" data-level="7.7.11" data-path="7-hypo.html"><a href="7-hypo.html#summary-5"><i class="fa fa-check"></i><b>7.7.11</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="7-hypo.html"><a href="7-hypo.html#theory-hypo"><i class="fa fa-check"></i><b>7.8</b> Building theory-based methods using computation</a><ul>
<li class="chapter" data-level="7.8.1" data-path="7-hypo.html"><a href="7-hypo.html#example-t-test-for-two-independent-samples"><i class="fa fa-check"></i><b>7.8.1</b> EXAMPLE: <span class="math inline">\(t\)</span>-test for two independent samples</a></li>
<li class="chapter" data-level="7.8.2" data-path="7-hypo.html"><a href="7-hypo.html#conditions-for-t-test"><i class="fa fa-check"></i><b>7.8.2</b> Conditions for t-test</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="7-hypo.html"><a href="7-hypo.html#conclusion-3"><i class="fa fa-check"></i><b>7.9</b> Conclusion</a><ul>
<li class="chapter" data-level="7.9.1" data-path="7-hypo.html"><a href="7-hypo.html#script-of-r-code-3"><i class="fa fa-check"></i><b>7.9.1</b> Script of R code</a></li>
<li class="chapter" data-level="7.9.2" data-path="7-hypo.html"><a href="7-hypo.html#whats-to-come-4"><i class="fa fa-check"></i><b>7.9.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-ci.html"><a href="8-ci.html"><i class="fa fa-check"></i><b>8</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="" data-path="8-ci.html"><a href="8-ci.html#needed-packages-5"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="8.1" data-path="8-ci.html"><a href="8-ci.html#bootstrapping"><i class="fa fa-check"></i><b>8.1</b> Bootstrapping</a><ul>
<li class="chapter" data-level="8.1.1" data-path="8-ci.html"><a href="8-ci.html#review-of-bootstrapping"><i class="fa fa-check"></i><b>8.1.1</b> Review of Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="8-ci.html"><a href="8-ci.html#relation-to-hypothesis-testing"><i class="fa fa-check"></i><b>8.2</b> Relation to hypothesis testing</a></li>
<li class="chapter" data-level="8.3" data-path="8-ci.html"><a href="8-ci.html#effect-size"><i class="fa fa-check"></i><b>8.3</b> Effect size</a></li>
<li class="chapter" data-level="8.4" data-path="8-ci.html"><a href="8-ci.html#conclusion-4"><i class="fa fa-check"></i><b>8.4</b> Conclusion</a><ul>
<li class="chapter" data-level="8.4.1" data-path="8-ci.html"><a href="8-ci.html#script-of-r-code-4"><i class="fa fa-check"></i><b>8.4.1</b> Script of R code</a></li>
<li class="chapter" data-level="8.4.2" data-path="8-ci.html"><a href="8-ci.html#whats-to-come-5"><i class="fa fa-check"></i><b>8.4.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="9-regress.html"><a href="9-regress.html"><i class="fa fa-check"></i><b>9</b> Regression via broom</a><ul>
<li class="chapter" data-level="" data-path="9-regress.html"><a href="9-regress.html#needed-packages-6"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="9.1" data-path="9-regress.html"><a href="9-regress.html#example-alaskan-airlines-delays"><i class="fa fa-check"></i><b>9.1</b> EXAMPLE: Alaskan Airlines delays</a></li>
<li class="chapter" data-level="9.2" data-path="9-regress.html"><a href="9-regress.html#correlation"><i class="fa fa-check"></i><b>9.2</b> Correlation</a><ul>
<li class="chapter" data-level="9.2.1" data-path="9-regress.html"><a href="9-regress.html#correlation-does-not-imply-causation"><i class="fa fa-check"></i><b>9.2.1</b> Correlation does not imply causation</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="9-regress.html"><a href="9-regress.html#linear-regression"><i class="fa fa-check"></i><b>9.3</b> Linear regression</a><ul>
<li class="chapter" data-level="9.3.1" data-path="9-regress.html"><a href="9-regress.html#understanding-linear-regression-basics"><i class="fa fa-check"></i><b>9.3.1</b> Understanding linear regression basics</a></li>
<li class="chapter" data-level="9.3.2" data-path="9-regress.html"><a href="9-regress.html#the-equation-of-the-line"><i class="fa fa-check"></i><b>9.3.2</b> The equation of the line</a></li>
<li class="chapter" data-level="9.3.3" data-path="9-regress.html"><a href="9-regress.html#interpreting-the-slope"><i class="fa fa-check"></i><b>9.3.3</b> Interpreting the slope</a></li>
<li class="chapter" data-level="9.3.4" data-path="9-regress.html"><a href="9-regress.html#predicting-values"><i class="fa fa-check"></i><b>9.3.4</b> Predicting values</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="9-regress.html"><a href="9-regress.html#inference-for-regression"><i class="fa fa-check"></i><b>9.4</b> Inference for regression</a><ul>
<li class="chapter" data-level="9.4.1" data-path="9-regress.html"><a href="9-regress.html#data-2"><i class="fa fa-check"></i><b>9.4.1</b> Data</a></li>
<li class="chapter" data-level="9.4.2" data-path="9-regress.html"><a href="9-regress.html#test-statistic-delta-2"><i class="fa fa-check"></i><b>9.4.2</b> Test Statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="9.4.3" data-path="9-regress.html"><a href="9-regress.html#observed-effect-delta-2"><i class="fa fa-check"></i><b>9.4.3</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="9.4.4" data-path="9-regress.html"><a href="9-regress.html#model-of-h_0-2"><i class="fa fa-check"></i><b>9.4.4</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="9.4.5" data-path="9-regress.html"><a href="9-regress.html#simulated-data-2"><i class="fa fa-check"></i><b>9.4.5</b> Simulated Data</a></li>
<li class="chapter" data-level="9.4.6" data-path="9-regress.html"><a href="9-regress.html#distribution-of-delta-under-h_0-2"><i class="fa fa-check"></i><b>9.4.6</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="9.4.7" data-path="9-regress.html"><a href="9-regress.html#the-p-value-2"><i class="fa fa-check"></i><b>9.4.7</b> The p-value</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="9-regress.html"><a href="9-regress.html#resid"><i class="fa fa-check"></i><b>9.5</b> Residual analysis</a></li>
<li class="chapter" data-level="9.6" data-path="9-regress.html"><a href="9-regress.html#conditions-for-regression"><i class="fa fa-check"></i><b>9.6</b> Conditions for regression</a></li>
<li class="chapter" data-level="9.7" data-path="9-regress.html"><a href="9-regress.html#conclusion-5"><i class="fa fa-check"></i><b>9.7</b> Conclusion</a><ul>
<li class="chapter" data-level="9.7.1" data-path="9-regress.html"><a href="9-regress.html#script-of-r-code-5"><i class="fa fa-check"></i><b>9.7.1</b> Script of R code</a></li>
<li class="chapter" data-level="9.7.2" data-path="9-regress.html"><a href="9-regress.html#whats-to-come-6"><i class="fa fa-check"></i><b>9.7.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Conclusion</b></span></li>
<li class="chapter" data-level="10" data-path="10-effective-data-storytelling.html"><a href="10-effective-data-storytelling.html"><i class="fa fa-check"></i><b>10</b> Effective Data Storytelling</a><ul>
<li class="chapter" data-level="" data-path="10-effective-data-storytelling.html"><a href="10-effective-data-storytelling.html#concluding-remarks"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="A-appendixA.html"><a href="A-appendixA.html"><i class="fa fa-check"></i><b>A</b> Statistical Background</a><ul>
<li class="chapter" data-level="A.1" data-path="A-appendixA.html"><a href="A-appendixA.html#basic-statistical-terms"><i class="fa fa-check"></i><b>A.1</b> Basic statistical terms</a><ul>
<li class="chapter" data-level="A.1.1" data-path="A-appendixA.html"><a href="A-appendixA.html#mean"><i class="fa fa-check"></i><b>A.1.1</b> Mean</a></li>
<li class="chapter" data-level="A.1.2" data-path="A-appendixA.html"><a href="A-appendixA.html#median"><i class="fa fa-check"></i><b>A.1.2</b> Median</a></li>
<li class="chapter" data-level="A.1.3" data-path="A-appendixA.html"><a href="A-appendixA.html#standard-deviation"><i class="fa fa-check"></i><b>A.1.3</b> Standard deviation</a></li>
<li class="chapter" data-level="A.1.4" data-path="A-appendixA.html"><a href="A-appendixA.html#five-number-summary"><i class="fa fa-check"></i><b>A.1.4</b> Five-number summary</a></li>
<li class="chapter" data-level="A.1.5" data-path="A-appendixA.html"><a href="A-appendixA.html#distribution"><i class="fa fa-check"></i><b>A.1.5</b> Distribution</a></li>
<li class="chapter" data-level="A.1.6" data-path="A-appendixA.html"><a href="A-appendixA.html#outliers"><i class="fa fa-check"></i><b>A.1.6</b> Outliers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="B-appendixB.html"><a href="B-appendixB.html"><i class="fa fa-check"></i><b>B</b> Inference Examples</a><ul>
<li class="chapter" data-level="" data-path="B-appendixB.html"><a href="B-appendixB.html#needed-packages-7"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="B.1" data-path="B-appendixB.html"><a href="B-appendixB.html#inference-mind-map"><i class="fa fa-check"></i><b>B.1</b> Inference Mind Map</a></li>
<li class="chapter" data-level="B.2" data-path="B-appendixB.html"><a href="B-appendixB.html#one-mean"><i class="fa fa-check"></i><b>B.2</b> One Mean</a><ul>
<li class="chapter" data-level="B.2.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement"><i class="fa fa-check"></i><b>B.2.1</b> Problem Statement</a></li>
<li class="chapter" data-level="B.2.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses"><i class="fa fa-check"></i><b>B.2.2</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.2.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data"><i class="fa fa-check"></i><b>B.2.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.2.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods"><i class="fa fa-check"></i><b>B.2.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.2.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods"><i class="fa fa-check"></i><b>B.2.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.2.6" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results"><i class="fa fa-check"></i><b>B.2.6</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.3" data-path="B-appendixB.html"><a href="B-appendixB.html#one-proportion"><i class="fa fa-check"></i><b>B.3</b> One Proportion</a><ul>
<li class="chapter" data-level="B.3.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement-1"><i class="fa fa-check"></i><b>B.3.1</b> Problem Statement</a></li>
<li class="chapter" data-level="B.3.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-1"><i class="fa fa-check"></i><b>B.3.2</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.3.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-1"><i class="fa fa-check"></i><b>B.3.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.3.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-1"><i class="fa fa-check"></i><b>B.3.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.3.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-1"><i class="fa fa-check"></i><b>B.3.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.3.6" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-1"><i class="fa fa-check"></i><b>B.3.6</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.4" data-path="B-appendixB.html"><a href="B-appendixB.html#two-proportions"><i class="fa fa-check"></i><b>B.4</b> Two Proportions</a><ul>
<li class="chapter" data-level="B.4.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement-2"><i class="fa fa-check"></i><b>B.4.1</b> Problem Statement</a></li>
<li class="chapter" data-level="B.4.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-2"><i class="fa fa-check"></i><b>B.4.2</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.4.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-2"><i class="fa fa-check"></i><b>B.4.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.4.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-2"><i class="fa fa-check"></i><b>B.4.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.4.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-2"><i class="fa fa-check"></i><b>B.4.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.4.6" data-path="B-appendixB.html"><a href="B-appendixB.html#check-conditions-2"><i class="fa fa-check"></i><b>B.4.6</b> Check conditions</a></li>
<li class="chapter" data-level="B.4.7" data-path="B-appendixB.html"><a href="B-appendixB.html#test-statistic-2"><i class="fa fa-check"></i><b>B.4.7</b> Test statistic</a></li>
<li class="chapter" data-level="B.4.8" data-path="B-appendixB.html"><a href="B-appendixB.html#state-conclusion-2"><i class="fa fa-check"></i><b>B.4.8</b> State conclusion</a></li>
<li class="chapter" data-level="B.4.9" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-2"><i class="fa fa-check"></i><b>B.4.9</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.5" data-path="B-appendixB.html"><a href="B-appendixB.html#two-means-independent-samples"><i class="fa fa-check"></i><b>B.5</b> Two Means (Independent Samples)</a><ul>
<li class="chapter" data-level="B.5.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement-3"><i class="fa fa-check"></i><b>B.5.1</b> Problem Statement</a></li>
<li class="chapter" data-level="B.5.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-3"><i class="fa fa-check"></i><b>B.5.2</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.5.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-3"><i class="fa fa-check"></i><b>B.5.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.5.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-3"><i class="fa fa-check"></i><b>B.5.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.5.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-3"><i class="fa fa-check"></i><b>B.5.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.5.6" data-path="B-appendixB.html"><a href="B-appendixB.html#test-statistic-3"><i class="fa fa-check"></i><b>B.5.6</b> Test statistic</a></li>
<li class="chapter" data-level="B.5.7" data-path="B-appendixB.html"><a href="B-appendixB.html#compute-p-value-2"><i class="fa fa-check"></i><b>B.5.7</b> Compute <span class="math inline">\(p\)</span>-value</a></li>
<li class="chapter" data-level="B.5.8" data-path="B-appendixB.html"><a href="B-appendixB.html#state-conclusion-3"><i class="fa fa-check"></i><b>B.5.8</b> State conclusion</a></li>
<li class="chapter" data-level="B.5.9" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-3"><i class="fa fa-check"></i><b>B.5.9</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.6" data-path="B-appendixB.html"><a href="B-appendixB.html#two-means-paired-samples"><i class="fa fa-check"></i><b>B.6</b> Two Means (Paired Samples)</a><ul>
<li class="chapter" data-level="B.6.1" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-4"><i class="fa fa-check"></i><b>B.6.1</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.6.2" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-4"><i class="fa fa-check"></i><b>B.6.2</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.6.3" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-4"><i class="fa fa-check"></i><b>B.6.3</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.6.4" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-4"><i class="fa fa-check"></i><b>B.6.4</b> Traditional methods</a></li>
<li class="chapter" data-level="B.6.5" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-4"><i class="fa fa-check"></i><b>B.6.5</b> Comparing results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="C" data-path="C-appendixC.html"><a href="C-appendixC.html"><i class="fa fa-check"></i><b>C</b> Reach for the Stars</a><ul>
<li class="chapter" data-level="" data-path="C-appendixC.html"><a href="C-appendixC.html#needed-packages-8"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="C.1" data-path="C-appendixC.html"><a href="C-appendixC.html#sorted-barplots"><i class="fa fa-check"></i><b>C.1</b> Sorted barplots</a></li>
<li class="chapter" data-level="C.2" data-path="C-appendixC.html"><a href="C-appendixC.html#interactive-graphics"><i class="fa fa-check"></i><b>C.2</b> Interactive graphics</a><ul>
<li class="chapter" data-level="C.2.1" data-path="C-appendixC.html"><a href="C-appendixC.html#interactive-line-graphs"><i class="fa fa-check"></i><b>C.2.1</b> Interactive line-graphs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ModernDive</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="appendixB" class="section level1">
<h1><span class="header-section-number">B</span> Inference Examples</h1>
<p>This appendix is designed to provide you with example of the five basic hypothesis tests and their corresponding confidence intervals. Traditional theory-based methods as well as computational-based methods are presented.</p>
<div id="needed-packages-7" class="section level2 unnumbered">
<h2>Needed packages</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(mosaic)
<span class="kw">library</span>(knitr)
<span class="kw">library</span>(readr)</code></pre></div>
<hr />
<hr />
</div>
<div id="inference-mind-map" class="section level2">
<h2><span class="header-section-number">B.1</span> Inference Mind Map</h2>
<p>To help you better navigate and choose the appropriate analysis, we’ve created a mind map on <a href="http://coggle.it" class="uri">http://coggle.it</a> available <a href="https://coggle.it/diagram/Vxlydu1akQFeqo6-">here</a> and below.</p>
<div class="figure" style="text-align: center"><span id="fig:infer-map"></span>
<img src="images/coggle.png" alt="Mind map for Inference" width="200%" />
<p class="caption">
Figure B.1: Mind map for Inference
</p>
</div>
</div>
<div id="one-mean" class="section level2">
<h2><span class="header-section-number">B.2</span> One Mean</h2>
<div id="problem-statement" class="section level3">
<h3><span class="header-section-number">B.2.1</span> Problem Statement</h3>
<p>The National Survey of Family Growth conducted by the Centers for Disease Control gathers information on family life, marriage and divorce, pregnancy, infertility, use of contraception, and men’s and women’s health. One of the variables collected on this survey is the age at first marriage. 5,534 randomly sampled US women between 2006 and 2010 completed the survey. The women sampled here had been married at least once. Do we have evidence that the mean age of first marriage for all US women from 2006 to 2010 is greater than 23 years? <span class="citation">(Tweaked a bit from Diez, Barr, and Çetinkaya-Rundel <a href="#ref-isrs2014">2014</a> [Chapter 4])</span></p>
</div>
<div id="competing-hypotheses" class="section level3">
<h3><span class="header-section-number">B.2.2</span> Competing Hypotheses</h3>
<div id="in-words" class="section level4">
<h4><span class="header-section-number">B.2.2.1</span> In words</h4>
<ul>
<li><p>Null hypothesis: The mean age of first marriage for all US women from 2006 to 2010 is equal to 23 years.</p></li>
<li><p>Alternative hypothesis: The mean age of first marriage for all US women from 2006 to 2010 is greater than 23 years.</p></li>
</ul>
</div>
<div id="in-symbols-with-annotations" class="section level4">
<h4><span class="header-section-number">B.2.2.2</span> In symbols (with annotations)</h4>
<ul>
<li><span class="math inline">\(H_0: \mu = \mu_{0}\)</span>, where <span class="math inline">\(\mu\)</span> represents the mean age of first marriage for all US women from 2006 to 2010 and <span class="math inline">\(\mu_0\)</span> is 23.</li>
<li><span class="math inline">\(H_A: \mu &gt; 23\)</span></li>
</ul>
</div>
<div id="set-alpha" class="section level4">
<h4><span class="header-section-number">B.2.2.3</span> Set <span class="math inline">\(\alpha\)</span></h4>
<p>It’s important to set the significance level before starting the testing using the data. Let’s set the significance level at 5% here.</p>
</div>
</div>
<div id="exploring-the-sample-data" class="section level3">
<h3><span class="header-section-number">B.2.3</span> Exploring the sample data</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#download.file(&quot;http://ismayc.github.io/teaching/sample_problems/ageAtMar.csv&quot;, </span>
<span class="co">#  destfile = &quot;data/ageAtMar.csv&quot;,</span>
<span class="co">#  method = &quot;curl&quot;)</span>
ageAtMar &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/ageAtMar.csv&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">age_summ &lt;-<span class="st"> </span>ageAtMar %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">sample_size =</span> <span class="kw">n</span>(),
    <span class="dt">mean =</span> <span class="kw">mean</span>(age),
    <span class="dt">sd =</span> <span class="kw">sd</span>(age),
    <span class="dt">minimum =</span> <span class="kw">min</span>(age),
    <span class="dt">lower_quartile =</span> <span class="kw">quantile</span>(age, <span class="fl">0.25</span>),
    <span class="dt">median =</span> <span class="kw">median</span>(age),
    <span class="dt">upper_quartile =</span> <span class="kw">quantile</span>(age, <span class="fl">0.75</span>),
    <span class="dt">max =</span> <span class="kw">max</span>(age))
<span class="kw">kable</span>(age_summ)</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">sample_size</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">minimum</th>
<th align="right">lower_quartile</th>
<th align="right">median</th>
<th align="right">upper_quartile</th>
<th align="right">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">5534</td>
<td align="right">23.44</td>
<td align="right">4.721</td>
<td align="right">10</td>
<td align="right">20</td>
<td align="right">23</td>
<td align="right">26</td>
<td align="right">43</td>
</tr>
</tbody>
</table>
<p>The histogram below also shows the distribution of <code>age</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ageAtMar %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> age)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">3</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/hist1b-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="guess-about-statistical-significance" class="section level4">
<h4><span class="header-section-number">B.2.3.1</span> Guess about statistical significance</h4>
<p>We are looking to see if the observed sample mean of 23.4402 is statistically greater than <span class="math inline">\(\mu_0 = 23\)</span>. They seem to be quite close, but we have a large sample size here. Let’s guess that the large sample size will lead us to reject this practically small difference.</p>
<hr />
</div>
</div>
<div id="non-traditional-methods" class="section level3">
<h3><span class="header-section-number">B.2.4</span> Non-traditional methods</h3>
<div id="bootstrapping-for-hypothesis-test" class="section level4">
<h4><span class="header-section-number">B.2.4.1</span> Bootstrapping for Hypothesis Test</h4>
<p>In order to look to see if the observed sample mean of 23.4402 is statistically greater than <span class="math inline">\(\mu_0 = 23\)</span>, we need to account for the sample size. We also need to determine a process that replicates how the original sample of size 5534 was selected.</p>
<p>We can use the idea of <em>bootstrapping</em> to simulate the population from which the sample came and then generate samples from that simulated population to account for sampling variability. Recall how bootstrapping would apply in this context:</p>
<ol style="list-style-type: decimal">
<li>Sample with replacement from our original sample of 5534 women and repeat this process 10,000 times,</li>
<li>calculate the mean for each of the 10,000 bootstrap samples created in Step 1.,</li>
<li>combine all of these bootstrap statistics calculated in Step 2 into a <code>boot_distn</code> object, and</li>
<li>shift the center of this distribution over to the null value of 23. (This is needed since it will be centered at 23.4402 via the process of bootstrapping.)</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">2016</span>)
mu0 &lt;-<span class="st"> </span><span class="dv">23</span>
shift &lt;-<span class="st"> </span>mu0 -<span class="st"> </span>age_summ$mean
null_distn &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span>
<span class="st">  </span><span class="kw">resample</span>(ageAtMar, <span class="dt">replace =</span> <span class="ot">TRUE</span>) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age =</span> age +<span class="st"> </span>shift) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_age =</span> <span class="kw">mean</span>(age))
null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean_age)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/sim1-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>We can next use this distribution to observe our <span class="math inline">\(p\)</span>-value. Recall this is a right-tailed test so we will be looking for values that are greater than or equal to 23.4402 for our <span class="math inline">\(p\)</span>-value.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">obs_mean &lt;-<span class="st"> </span>age_summ$mean
null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean_age)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">xintercept =</span> obs_mean)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-148-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="calculate-p-value" class="section level5">
<h5><span class="header-section-number">B.2.4.1.1</span> Calculate <span class="math inline">\(p\)</span>-value</h5>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pvalue &lt;-<span class="st"> </span>null_distn %&gt;%
<span class="st">  </span><span class="kw">filter</span>( mean_age &gt;=<span class="st"> </span>obs_mean ) %&gt;%
<span class="st">  </span><span class="kw">nrow</span>() /<span class="st"> </span><span class="kw">nrow</span>(null_distn)
pvalue</code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>So our <span class="math inline">\(p\)</span>-value is 0 and we reject the null hypothesis at the 5% level. You can also see this from the histogram above that we are far into the tail of the null distribution.</p>
</div>
</div>
<div id="bootstrapping-for-confidence-interval" class="section level4">
<h4><span class="header-section-number">B.2.4.2</span> Bootstrapping for Confidence Interval</h4>
<p>We can also create a confidence interval for the unknown population parameter <span class="math inline">\(\mu\)</span> using our sample data using <em>bootstrapping</em>. Note that we don’t need to shift this distribution since we want the center of our confidence interval to be our point estimate <span class="math inline">\(\bar{x}_{obs} = 23.4402\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span>
<span class="st">  </span><span class="kw">resample</span>(ageAtMar, <span class="dt">replace =</span> <span class="ot">TRUE</span>) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_age =</span> <span class="kw">mean</span>(age))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean_age)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-150-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">lower =</span> <span class="kw">quantile</span>(mean_age, <span class="dt">probs =</span> <span class="fl">0.025</span>),
    <span class="dt">upper =</span> <span class="kw">quantile</span>(mean_age, <span class="dt">probs =</span> <span class="fl">0.975</span>))</code></pre></div>
<pre><code>##   lower upper
## 1 23.32 23.56</code></pre>
<p>We see that 23 is not contained in this confidence interval as a plausible value of <span class="math inline">\(\mu\)</span> (the unknown population mean) and the entire interval is larger than 23. This matches with our hypothesis test results of rejecting the null hypothesis in favor of the alternative (<span class="math inline">\(\mu &gt; 23\)</span>).</p>
<p><strong>Interpretation</strong>: We are 95% confident the true mean age of first marriage for all US women from 2006 to 2010 is between and .</p>
<hr />
</div>
</div>
<div id="traditional-methods" class="section level3">
<h3><span class="header-section-number">B.2.5</span> Traditional methods</h3>
<div id="check-conditions" class="section level4">
<h4><span class="header-section-number">B.2.5.1</span> Check conditions</h4>
<p>Remember that in order to use the shortcut (formula-based, theoretical) approach, we need to check that some conditions are met.</p>
<ol style="list-style-type: decimal">
<li><p><em>Independent observations</em>: The observations are collected independently.</p>
<p>The cases are selected independently through random sampling so this condition is met.</p></li>
<li><p><em>Approximately normal</em>: The distribution of the response variable should be normal or the sample size should be at least 30.</p>
<p>The histogram for the sample above does show some skew.</p></li>
</ol>
<p>The Q-Q plot below also shows some skew.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> ageAtMar, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">sample =</span> age)) +
<span class="st">  </span><span class="kw">stat_qq</span>()</code></pre></div>
<p><img src="ismaykim_files/figure-html/qqplotmean-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>The sample size here is quite large though (<span class="math inline">\(n = 5534\)</span>) so both conditions are met.</p>
</div>
<div id="test-statistic" class="section level4">
<h4><span class="header-section-number">B.2.5.2</span> Test statistic</h4>
<p>The test statistic is a random variable based on the sample data. Here, we want to look at a way to estimate the population mean <span class="math inline">\(\mu\)</span>. A good guess is the sample mean <span class="math inline">\(\bar{X}\)</span>. Recall that this sample mean is actually a random variable that will vary as different samples are (theoretically, would be) collected. We are looking to see how likely is it for us to have observed a sample mean of <span class="math inline">\(\bar{x}_{obs} = 23.4402\)</span> or larger assuming that the population mean is 23 (assuming the null hypothesis is true). If the conditions are met and assuming <span class="math inline">\(H_0\)</span> is true, we can “standardize” this original test statistic of <span class="math inline">\(\bar{X}\)</span> into a <span class="math inline">\(T\)</span> statistic that follows a <span class="math inline">\(t\)</span> distribution with degrees of freedom equal to <span class="math inline">\(df = n - 1\)</span>:</p>
<p><span class="math display">\[ T =\dfrac{ \bar{X} - \mu_0}{ S / \sqrt{n} } \sim t (df = n - 1) \]</span></p>
<p>where <span class="math inline">\(S\)</span> represents the standard deviation of the sample and <span class="math inline">\(n\)</span> is the sample size.</p>
<div id="observed-test-statistic" class="section level5">
<h5><span class="header-section-number">B.2.5.2.1</span> Observed test statistic</h5>
<p>While one could compute this observed test statistic by “hand”, the focus here is on the set-up of the problem and in understanding which formula for the test statistic applies. We can use the <code>t.test</code> function to perform this analysis for us.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(<span class="dt">x =</span> ageAtMar$age, 
       <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>,
       <span class="dt">mu =</span> <span class="dv">23</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  ageAtMar$age
## t = 6.9, df = 5500, p-value = 0.000000000002
## alternative hypothesis: true mean is greater than 23
## 95 percent confidence interval:
##  23.34   Inf
## sample estimates:
## mean of x 
##     23.44</code></pre>
<p>We see here that the <span class="math inline">\(t_{obs}\)</span> value is around 6.94. Recall that for large sample sizes the <span class="math inline">\(t\)</span> distribution is essentially the standard normal distribution and this is why the statistic is reported as <code>Z</code>.</p>
</div>
</div>
<div id="compute-p-value" class="section level4">
<h4><span class="header-section-number">B.2.5.3</span> Compute <span class="math inline">\(p\)</span>-value</h4>
<p>The <span class="math inline">\(p\)</span>-value—the probability of observing an <span class="math inline">\(t_{obs}\)</span> value of 6.94 or more in our null distribution of a <span class="math inline">\(t\)</span> with 5433 degrees of freedom—is essentially 0. This can also be calculated in R directly:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pt</span>(<span class="fl">6.936</span>, <span class="dt">df =</span> <span class="kw">nrow</span>(ageAtMar) -<span class="st"> </span><span class="dv">1</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## [1] 0.000000000002247</code></pre>
<p>We can also use the <span class="math inline">\(N(0, 1)\)</span> distribution here:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pnorm</span>(<span class="fl">6.936</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## [1] 0.000000000002017</code></pre>
</div>
<div id="state-conclusion" class="section level4">
<h4><span class="header-section-number">B.2.5.4</span> State conclusion</h4>
<p>We, therefore, have sufficient evidence to reject the null hypothesis. Our initial guess that our observed sample mean was statistically greater than the hypothesized mean has supporting evidence here. Based on this sample, we have evidence that the mean age of first marriage for all US women from 2006 to 2010 is greater than 23 years.</p>
</div>
<div id="confidence-interval" class="section level4">
<h4><span class="header-section-number">B.2.5.5</span> Confidence interval</h4>
<p>The confidence interval reported above with <code>t.test</code> is known as a one-sided confidence interval and gives the lowest value one could expect <span class="math inline">\(\mu\)</span> to be with 95% confidence. We usually want a range of values so we can use <code>alternative = &quot;two.sided&quot;</code> to get the similar values compared to the bootstrapping process:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(<span class="dt">x =</span> ageAtMar$age, 
       <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,
       <span class="dt">mu =</span> <span class="dv">23</span>)$conf</code></pre></div>
<pre><code>## [1] 23.32 23.56
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<hr />
</div>
</div>
<div id="comparing-results" class="section level3">
<h3><span class="header-section-number">B.2.6</span> Comparing results</h3>
<p>Observing the bootstrap distribution that were created, it makes quite a bit of sense that the results are so similar for traditional and non-traditional methods in terms of the <span class="math inline">\(p\)</span>-value and the confidence interval since these distributions look very similar to normal distributions. The conditions also being met (the large sample size was the driver here) leads us to better guess that using any of the methods whether they are traditional (formula-based) or non-traditional (computational-based) will lead to similar results.</p>
<hr />
<hr />
</div>
</div>
<div id="one-proportion" class="section level2">
<h2><span class="header-section-number">B.3</span> One Proportion</h2>
<div id="problem-statement-1" class="section level3">
<h3><span class="header-section-number">B.3.1</span> Problem Statement</h3>
<p>The CEO of a large electric utility claims that 80 percent of his 1,000,000 customers are satisfied with the service they receive. To test this claim, the local newspaper surveyed 100 customers, using simple random sampling. 73 were satisfied and the remaining were unsatisfied. Based on these findings from the sample, can we reject the CEO’s hypothesis that 80% of the customers are satisfied? [Tweaked a bit from <a href="http://stattrek.com/hypothesis-test/proportion.aspx?Tutorial=AP" class="uri">http://stattrek.com/hypothesis-test/proportion.aspx?Tutorial=AP</a>]</p>
</div>
<div id="competing-hypotheses-1" class="section level3">
<h3><span class="header-section-number">B.3.2</span> Competing Hypotheses</h3>
<div id="in-words-1" class="section level4">
<h4><span class="header-section-number">B.3.2.1</span> In words</h4>
<ul>
<li><p>Null hypothesis: The proportion of all customers of the large electric utility satisfied with service they receive is equal 0.80.</p></li>
<li><p>Alternative hypothesis: The proportion of all customers of the large electric utility satisfied with service they receive is different from 0.80.</p></li>
</ul>
<!--
## Another way with words

- Null hypothesis:  There is no association between feed type and age in the population of interest.

- Alternative hypothesis:  There is an association between the variables in the population.
-->
</div>
<div id="in-symbols-with-annotations-1" class="section level4">
<h4><span class="header-section-number">B.3.2.2</span> In symbols (with annotations)</h4>
<ul>
<li><span class="math inline">\(H_0: \pi = p_{0}\)</span>, where <span class="math inline">\(\pi\)</span> represents the proportion of all customers of the large electric utility satisfied with service they receive and <span class="math inline">\(p_0\)</span> is 0.8.</li>
<li><span class="math inline">\(H_A: \pi \ne 0.8\)</span></li>
</ul>
</div>
<div id="set-alpha-1" class="section level4">
<h4><span class="header-section-number">B.3.2.3</span> Set <span class="math inline">\(\alpha\)</span></h4>
<p>It’s important to set the significance level before starting the testing using the data. Let’s set the significance level at 5% here.</p>
</div>
</div>
<div id="exploring-the-sample-data-1" class="section level3">
<h3><span class="header-section-number">B.3.3</span> Exploring the sample data</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">elec &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;satisfied&quot;</span>, <span class="dv">73</span>), <span class="kw">rep</span>(<span class="st">&quot;unsatisfied&quot;</span>, <span class="dv">27</span>)) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">as_data_frame</span>() %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">rename</span>(<span class="st">&quot;satisfy&quot;</span> =<span class="st"> </span>value)</code></pre></div>
<p>The bar graph below also shows the distribution of <code>satisfy</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> elec, <span class="kw">aes</span>(<span class="dt">x =</span> satisfy)) +<span class="st"> </span><span class="kw">geom_bar</span>()</code></pre></div>
<p><img src="ismaykim_files/figure-html/bar-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="guess-about-statistical-significance-1" class="section level4">
<h4><span class="header-section-number">B.3.3.1</span> Guess about statistical significance</h4>
<p>We are looking to see if the sample proportion of 0.73 is statistically different from <span class="math inline">\(p_0 = 0.8\)</span> based on this sample. They seem to be quite close, and our sample size is not huge here (<span class="math inline">\(n = 100\)</span>). Let’s guess that we do not have evidence to reject the null hypothesis.</p>
<hr />
</div>
</div>
<div id="non-traditional-methods-1" class="section level3">
<h3><span class="header-section-number">B.3.4</span> Non-traditional methods</h3>
<div id="simulation-for-hypothesis-test" class="section level4">
<h4><span class="header-section-number">B.3.4.1</span> Simulation for Hypothesis Test</h4>
<p>In order to look to see if 0.73 is statistically different from 0.8, we need to account for the sample size. We also need to determine a process that replicates how the original sample of size 100 was selected. We can use the idea of an unfair coin to <em>simulate</em> this process. We will simulate flipping an unfair coin (with probability of success 0.8 matching the null hypothesis) 100 times. Then we will keep track of how many heads come up in those 100 flips. Our simulated statistic matches with how we calculated the original statistic <span class="math inline">\(\hat{p}\)</span>: the number of heads (satisfied) out of our total sample of 100. We then repeat this process many times (say 10,000) to create the null distribution looking at the simulated proportions of successes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">2016</span>)
null_distn &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span><span class="kw">rflip</span>(<span class="dv">100</span>, <span class="dt">prob =</span> <span class="fl">0.8</span>)
null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> prop)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/sim2-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>We can next use this distribution to observe our <span class="math inline">\(p\)</span>-value. Recall this is a two-tailed test so we will be looking for values that are 0.8 - 0.73 = 0.07 away from 0.8 in BOTH directions for our <span class="math inline">\(p\)</span>-value:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p_hat &lt;-<span class="st"> </span><span class="dv">73</span>/<span class="dv">100</span>
dist &lt;-<span class="st"> </span><span class="fl">0.8</span> -<span class="st"> </span>p_hat
null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> prop)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">xintercept =</span> <span class="fl">0.8</span> +<span class="st"> </span>dist) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">xintercept =</span> p_hat)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-152-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="calculate-p-value-1" class="section level5">
<h5><span class="header-section-number">B.3.4.1.1</span> Calculate <span class="math inline">\(p\)</span>-value</h5>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pvalue &lt;-<span class="st"> </span>null_distn %&gt;%
<span class="st">  </span><span class="kw">filter</span>( (prop &gt;=<span class="st"> </span><span class="fl">0.8</span> +<span class="st"> </span>dist) |<span class="st"> </span>(prop &lt;=<span class="st"> </span>p_hat) ) %&gt;%
<span class="st">  </span><span class="kw">nrow</span>() /<span class="st"> </span><span class="kw">nrow</span>(null_distn)
pvalue</code></pre></div>
<pre><code>## [1] 0.081</code></pre>
<p>So our <span class="math inline">\(p\)</span>-value is 0.081 and we fail to reject the null hypothesis at the 5% level.</p>
</div>
</div>
<div id="bootstrapping-for-confidence-interval-1" class="section level4">
<h4><span class="header-section-number">B.3.4.2</span> Bootstrapping for Confidence Interval</h4>
<p>We can also create a confidence interval for the unknown population parameter <span class="math inline">\(\pi\)</span> using our sample data. To do so, we use <em>bootstrapping</em>, which involves</p>
<ol style="list-style-type: decimal">
<li>sampling with replacement from our original sample of 100 survey respondents and repeating this process 10,000 times,</li>
<li>calculating the proportion of successes for each of the 10,000 bootstrap samples created in Step 1.,</li>
<li>combining all of these bootstrap statistics calculated in Step 2 into a <code>boot_distn</code> object,</li>
<li>identifying the 2.5<sup>th</sup> and 97.5<sup>th</sup> percentiles of this distribution (corresponding to the 5% significance level chosen) to find a 95% confidence interval for <span class="math inline">\(\pi\)</span>, and</li>
<li>interpret this confidence interval in the context of the problem.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span>
<span class="st">  </span>elec %&gt;%<span class="st"> </span><span class="kw">resample</span>(<span class="dt">size =</span> <span class="dv">100</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">success_rate =</span> <span class="kw">mean</span>(satisfy ==<span class="st"> &quot;satisfied&quot;</span>))</code></pre></div>
<p>Just as we use the <code>mean</code> function for calculating the mean over a numerical variable, we can also use it to compute the proportion of successes for a categorical variable where we specify what we are calling a “success” after the <code>==</code>. (Think about the formula for calculating a mean and how R handles logical statements such as <code>satisfy == &quot;satisfied&quot;</code> for why this must be true.)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> success_rate)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-154-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">lower =</span> <span class="kw">quantile</span>(success_rate, <span class="dt">probs =</span> <span class="fl">0.025</span>),
    <span class="dt">upper =</span> <span class="kw">quantile</span>(success_rate, <span class="dt">probs =</span> <span class="fl">0.975</span>))</code></pre></div>
<pre><code>##   lower upper
## 1  0.64  0.81</code></pre>
<p>We see that 0.80 is contained in this confidence interval as a plausible value of <span class="math inline">\(\pi\)</span> (the unknown population proportion). This matches with our hypothesis test results of failing to reject the null hypothesis.</p>
<p><strong>Interpretation</strong>: We are 95% confident the true proportion of customers who are satisfied with the service they receive is between and .</p>
<p><strong>Note</strong>: You could also use the null distribution with a shift to have its center at <span class="math inline">\(\hat{p} = 0.73\)</span> instead of at <span class="math inline">\(p_0 = 0.8\)</span> and calculate its percentiles. The confidence interval produced via this method should be comparable to the one done using bootstrapping above.</p>
<hr />
</div>
</div>
<div id="traditional-methods-1" class="section level3">
<h3><span class="header-section-number">B.3.5</span> Traditional methods</h3>
<div id="check-conditions-1" class="section level4">
<h4><span class="header-section-number">B.3.5.1</span> Check conditions</h4>
<p>Remember that in order to use the shortcut (formula-based, theoretical) approach, we need to check that some conditions are met.</p>
<ol style="list-style-type: decimal">
<li><p><em>Independent observations</em>: The observations are collected independently.</p>
<p>The cases are selected independently through random sampling so this condition is met.</p></li>
<li><p><em>Approximately normal</em>: The number of expected successes and expected failures is at least 10.</p>
<p>This condition is met since 73 and 27 are both greater than 10.</p></li>
</ol>
</div>
<div id="test-statistic-1" class="section level4">
<h4><span class="header-section-number">B.3.5.2</span> Test statistic</h4>
<p>The test statistic is a random variable based on the sample data. Here, we want to look at a way to estimate the population proportion <span class="math inline">\(\pi\)</span>. A good guess is the sample proportion <span class="math inline">\(\hat{P}\)</span>. Recall that this sample proportion is actually a random variable that will vary as different samples are (theoretically, would be) collected. We are looking to see how likely is it for us to have observed a sample proportion of <span class="math inline">\(\hat{p}_{obs} = 0.73\)</span> or larger assuming that the population proportion is 0.80 (assuming the null hypothesis is true). If the conditions are met and assuming <span class="math inline">\(H_0\)</span> is true, we can standardize this original test statistic of <span class="math inline">\(\hat{P}\)</span> into a <span class="math inline">\(Z\)</span> statistic that follows a <span class="math inline">\(N(0, 1)\)</span> distribution.</p>
<p><span class="math display">\[ Z =\dfrac{ \hat{P} - p_0}{\sqrt{\dfrac{p_0(1 - p_0)}{n} }} \sim N(0, 1) \]</span></p>
<div id="observed-test-statistic-1" class="section level5">
<h5><span class="header-section-number">B.3.5.2.1</span> Observed test statistic</h5>
<p>While one could compute this observed test statistic by “hand” by plugging the observed values into the formula, the focus here is on the set-up of the problem and in understanding which formula for the test statistic applies. The calculation has been done in R below for completeness though:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p_hat &lt;-<span class="st"> </span><span class="fl">0.73</span>
p0 &lt;-<span class="st"> </span><span class="fl">0.8</span>
n &lt;-<span class="st"> </span><span class="dv">100</span>
(z_obs &lt;-<span class="st"> </span>(p_hat -<span class="st"> </span>p0) /<span class="st"> </span><span class="kw">sqrt</span>( (p0 *<span class="st"> </span>(<span class="dv">1</span> -<span class="st"> </span>p0)) /<span class="st"> </span>n))</code></pre></div>
<pre><code>## [1] -1.75</code></pre>
<p>We see here that the <span class="math inline">\(z_{obs}\)</span> value is around -1.75. Our observed sample proportion of 0.73 is 1.75 standard errors below the hypothesized parameter value of 0.8.</p>
</div>
</div>
<div id="compute-p-value-1" class="section level4">
<h4><span class="header-section-number">B.3.5.3</span> Compute <span class="math inline">\(p\)</span>-value</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> *<span class="st"> </span><span class="kw">pnorm</span>(z_obs)</code></pre></div>
<pre><code>## [1] 0.08012</code></pre>
<p>The <span class="math inline">\(p\)</span>-value—the probability of observing an <span class="math inline">\(z_{obs}\)</span> value of -1.75 or more extreme (in both directions) in our null distribution—is around 8%.</p>
<p>Note that we could also do this test directly using the <code>prop.test</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stats::<span class="kw">prop.test</span>(<span class="dt">x =</span> <span class="kw">table</span>(elec$satisfy),
       <span class="dt">n =</span> <span class="kw">length</span>(elec$satisfy),
       <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,
       <span class="dt">p =</span> <span class="fl">0.8</span>,
       <span class="dt">correct =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  table(elec$satisfy), null probability 0.8
## X-squared = 3.1, df = 1, p-value = 0.08
## alternative hypothesis: true p is not equal to 0.8
## 95 percent confidence interval:
##  0.6357 0.8073
## sample estimates:
##    p 
## 0.73</code></pre>
<p><code>prop.test</code> does a <span class="math inline">\(\chi^2\)</span> test here but this matches up exactly with what we would expect: <span class="math inline">\(x^2_{obs} = 3.06 = (-1.75)^2 = (z_{obs})^2\)</span> and the <span class="math inline">\(p\)</span>-values are the same because we are focusing on a two-tailed test.</p>
<p>Note that the 95 percent confidence interval given above matches well with the one calculated using bootstrapping.</p>
</div>
<div id="state-conclusion-1" class="section level4">
<h4><span class="header-section-number">B.3.5.4</span> State conclusion</h4>
<p>We, therefore, do not have sufficient evidence to reject the null hypothesis. Our initial guess that our observed sample proportion was not statistically greater than the hypothesized proportion has not been invalidated. Based on this sample, we have do not evidence that the proportion of all customers of the large electric utility satisfied with service they receive is different from 0.80, at the 5% level.</p>
<hr />
</div>
</div>
<div id="comparing-results-1" class="section level3">
<h3><span class="header-section-number">B.3.6</span> Comparing results</h3>
<p>Observing the bootstrap distribution and the null distribution that were created, it makes quite a bit of sense that the results are so similar for traditional and non-traditional methods in terms of the <span class="math inline">\(p\)</span>-value and the confidence interval since these distributions look very similar to normal distributions. The conditions also being met leads us to better guess that using any of the methods whether they are traditional (formula-based) or non-traditional (computational-based) will lead to similar results.</p>
<hr />
<hr />
</div>
</div>
<div id="two-proportions" class="section level2">
<h2><span class="header-section-number">B.4</span> Two Proportions</h2>
<div id="problem-statement-2" class="section level3">
<h3><span class="header-section-number">B.4.1</span> Problem Statement</h3>
<p>A 2010 survey asked 827 randomly sampled registered voters in California “Do you support? Or do you oppose? Drilling for oil and natural gas off the Coast of California? Or do you not know enough to say?” Conduct a hypothesis test to determine if the data provide strong evidence that the proportion of college graduates who do not have an opinion on this issue is different than that of non-college graduates. <span class="citation">(Tweaked a bit from Diez, Barr, and Çetinkaya-Rundel <a href="#ref-isrs2014">2014</a> [Chapter 6])</span></p>
</div>
<div id="competing-hypotheses-2" class="section level3">
<h3><span class="header-section-number">B.4.2</span> Competing Hypotheses</h3>
<div id="in-words-2" class="section level4">
<h4><span class="header-section-number">B.4.2.1</span> In words</h4>
<ul>
<li><p>Null hypothesis: There is no association between having an opinion on drilling and having a college degree for all registered California voters in 2010.</p></li>
<li><p>Alternative hypothesis: There is an association between having an opinion on drilling and having a college degree for all registered California voters in 2010.</p></li>
</ul>
</div>
<div id="another-way-in-words" class="section level4">
<h4><span class="header-section-number">B.4.2.2</span> Another way in words</h4>
<ul>
<li><p>Null hypothesis: The probability that a Californian voter in 2010 having no opinion on drilling and is a college graduate is the <strong>same</strong> as that of a non-college graduate.</p></li>
<li><p>Alternative hypothesis: These parameter probabilities are different.</p></li>
</ul>
</div>
<div id="in-symbols-with-annotations-2" class="section level4">
<h4><span class="header-section-number">B.4.2.3</span> In symbols (with annotations)</h4>
<ul>
<li><span class="math inline">\(H_0: \pi_{college} = \pi_{no\_college}\)</span> or <span class="math inline">\(H_0: \pi_{college} - \pi_{no\_college} = 0\)</span>, where <span class="math inline">\(\pi\)</span> represents the probability of not having an opinion on drilling.</li>
<li><span class="math inline">\(H_A: \pi_{college} - \pi_{no\_college} \ne 0\)</span></li>
</ul>
</div>
<div id="set-alpha-2" class="section level4">
<h4><span class="header-section-number">B.4.2.4</span> Set <span class="math inline">\(\alpha\)</span></h4>
<p>It’s important to set the significance level before starting the testing using the data. Let’s set the significance level at 5% here.</p>
</div>
</div>
<div id="exploring-the-sample-data-2" class="section level3">
<h3><span class="header-section-number">B.4.3</span> Exploring the sample data</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#download.file(&quot;http://ismayc.github.io/teaching/sample_problems/offshore.csv&quot;,</span>
<span class="co">#              destfile = &quot;data/offshore.csv&quot;, </span>
<span class="co">#              method = &quot;curl&quot;)</span>
offshore &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/offshore.csv&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(offshore$college_grad, offshore$response)</code></pre></div>
<pre><code>##      
##       no opinion opinion
##   no         131     258
##   yes        104     334</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(off_summ &lt;-<span class="st"> </span>offshore %&gt;%<span class="st"> </span><span class="kw">group_by</span>(college_grad) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">prop_no_opinion =</span> <span class="kw">mean</span>(response ==<span class="st"> &quot;no opinion&quot;</span>),
    <span class="dt">sample_size =</span> <span class="kw">n</span>())
)</code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   college_grad prop_no_opinion sample_size
##          &lt;chr&gt;           &lt;dbl&gt;       &lt;int&gt;
## 1           no          0.3368         389
## 2          yes          0.2374         438</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">offshore %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> college_grad, <span class="dt">fill =</span> response)) +
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="st">&quot;fill&quot;</span>) +
<span class="st">  </span><span class="kw">coord_flip</span>()</code></pre></div>
<p><img src="ismaykim_files/figure-html/stacked_bar-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="guess-about-statistical-significance-2" class="section level4">
<h4><span class="header-section-number">B.4.3.1</span> Guess about statistical significance</h4>
<p>We are looking to see if a difference exists in the heights of the bars corresponding to <code>no opinion</code> for the plot. Based solely on the plot, we have little reason to believe that a difference exists since the bars seem to be about the same height, BUT…it’s important to use statistics to see if that difference is actually statistically significant!</p>
<hr />
</div>
</div>
<div id="non-traditional-methods-2" class="section level3">
<h3><span class="header-section-number">B.4.4</span> Non-traditional methods</h3>
<div id="collecting-summary-info" class="section level4">
<h4><span class="header-section-number">B.4.4.1</span> Collecting summary info</h4>
<p>Next we will assign some key values to variable names in R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">phat_nograd &lt;-<span class="st"> </span>off_summ$prop_no_opinion[<span class="dv">1</span>]
phat_grad &lt;-<span class="st"> </span>off_summ$prop_no_opinion[<span class="dv">2</span>]
obs_diff &lt;-<span class="st"> </span>phat_grad -<span class="st"> </span>phat_nograd
n_nograd &lt;-<span class="st"> </span>off_summ$sample_size[<span class="dv">1</span>]
n_grad &lt;-<span class="st"> </span>off_summ$sample_size[<span class="dv">2</span>]</code></pre></div>
</div>
<div id="randomization-for-hypothesis-test" class="section level4">
<h4><span class="header-section-number">B.4.4.2</span> Randomization for Hypothesis Test</h4>
<p>In order to look to see if the observed sample proportion of no opinion for college graduates of 0.3368 is statistically different than that for graduates of 0.2374, we need to account for the sample sizes. Note that this is the same as looking to see if <span class="math inline">\(\hat{p}_{grad} - \hat{p}_{nograd}\)</span> is statistically different than 0. We also need to determine a process that replicates how the original group sizes of 389 and 438 were selected.</p>
<p>We can use the idea of <em>randomization testing</em> (also known as <em>permutation testing</em>) to simulate the population from which the sample came (with two groups of different sizes) and then generate samples using <em>shuffling</em> from that simulated population to account for sampling variability.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">2016</span>)
many_shuffles &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span>
<span class="st">  </span>(offshore %&gt;%
<span class="st">     </span><span class="kw">mutate</span>(<span class="dt">response =</span> <span class="kw">shuffle</span>(response)) %&gt;%<span class="st"> </span>
<span class="st">     </span><span class="kw">group_by</span>(college_grad) %&gt;%
<span class="st">     </span><span class="kw">summarize</span>(<span class="dt">prop_no_opinion =</span> <span class="kw">mean</span>(response ==<span class="st"> &quot;no opinion&quot;</span>))
   )
null_distn &lt;-<span class="st"> </span>many_shuffles %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(.index) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">diffprop =</span> <span class="kw">diff</span>(prop_no_opinion))
null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffprop)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">25</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/sim3-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>We can next use this distribution to observe our <span class="math inline">\(p\)</span>-value. Recall this is a two-tailed test so we will be looking for values that are greater than or equal to -0.0993 or less than or equal to 0.0993 for our <span class="math inline">\(p\)</span>-value.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffprop)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">20</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">xintercept =</span> obs_diff) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">xintercept =</span> -obs_diff)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-157-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="calculate-p-value-2" class="section level5">
<h5><span class="header-section-number">B.4.4.2.1</span> Calculate <span class="math inline">\(p\)</span>-value</h5>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pvalue &lt;-<span class="st"> </span>null_distn %&gt;%
<span class="st">  </span><span class="kw">filter</span>( (diffprop &lt;=<span class="st"> </span>obs_diff) |<span class="st"> </span>(diffprop &gt;=<span class="st"> </span>-obs_diff) ) %&gt;%
<span class="st">  </span><span class="kw">nrow</span>() /<span class="st"> </span><span class="kw">nrow</span>(null_distn)
pvalue</code></pre></div>
<pre><code>## [1] 0.0025</code></pre>
<p>So our <span class="math inline">\(p\)</span>-value is 0.0025 and we reject the null hypothesis at the 5% level. You can also see this from the histogram above that we are far into the tails of the null distribution.</p>
</div>
</div>
<div id="bootstrapping-for-confidence-interval-2" class="section level4">
<h4><span class="header-section-number">B.4.4.3</span> Bootstrapping for Confidence Interval</h4>
<p>We can also create a confidence interval for the unknown population parameter <span class="math inline">\(\pi_{college} - \pi_{no\_college}\)</span> using our sample data with <em>bootstrapping</em>. Here we will bootstrap each of the groups with replacement instead of shuffling. This is done using the <code>groups</code> argument in the <code>resample</code> function to fix the size of each group to be the same as the original group sizes of 389 for non-college graduates and 438 for college graduates.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_props &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *
<span class="st">  </span>offshore %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">resample</span>(<span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">groups =</span> college_grad) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(college_grad) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">prop_no_opinion =</span> <span class="kw">mean</span>(response ==<span class="st"> &quot;no opinion&quot;</span>))</code></pre></div>
<p>Next, we calculate the difference in sample proportions for each of the 10,000 replications:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn &lt;-<span class="st"> </span>boot_props %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(.index) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">diffprop =</span> <span class="kw">diff</span>(prop_no_opinion))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffprop)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-160-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(ci_boot &lt;-<span class="st"> </span>boot_distn %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">lower =</span> <span class="kw">quantile</span>(diffprop, <span class="dt">probs =</span> <span class="fl">0.025</span>),
    <span class="dt">upper =</span> <span class="kw">quantile</span>(diffprop, <span class="dt">probs =</span> <span class="fl">0.975</span>)))</code></pre></div>
<pre><code>## # A tibble: 1 x 2
##     lower    upper
##     &lt;dbl&gt;    &lt;dbl&gt;
## 1 -0.1596 -0.03792</code></pre>
<p>We see that 0 is not contained in this confidence interval as a plausible value of <span class="math inline">\(\pi_{college} - \pi_{no\_college}\)</span> (the unknown population parameter). This matches with our hypothesis test results of rejecting the null hypothesis. Since zero is not a plausible value of the population parameter, we have evidence that the proportion of college graduates in California with no opinion on drilling is different than that of non-college graduates.</p>
<p><strong>Interpretation</strong>: We are 95% confident the true proportion of non-college graduates with no opinion on offshore drilling in California is between 0.16 dollars smaller to 0.04 dollars smaller than for college graduates.</p>
<p><strong>Note</strong>: You could also use the null distribution based on randomization with a shift to have its center at <span class="math inline">\(\hat{p}_{college} - \hat{p}_{no\_college} = \$-0.1\)</span> instead of at 0 and calculate its percentiles. The confidence interval produced via this method should be comparable to the one done using bootstrapping above.</p>
<hr />
</div>
</div>
<div id="traditional-methods-2" class="section level3">
<h3><span class="header-section-number">B.4.5</span> Traditional methods</h3>
</div>
<div id="check-conditions-2" class="section level3">
<h3><span class="header-section-number">B.4.6</span> Check conditions</h3>
<p>Remember that in order to use the short-cut (formula-based, theoretical) approach, we need to check that some conditions are met.</p>
<ol style="list-style-type: decimal">
<li><p><em>Independent observations</em>: Each case that was selected must be independent of all the other cases selected.</p>
<p>This condition is met since cases were selected at random to observe.</p></li>
<li><p><em>Sample size</em>: The number of pooled successes and pooled failures must be at least 10 for each group.</p>
<p>We need to first figure out the pooled success rate: <span class="math display">\[\hat{p}_{obs} = \dfrac{131 + 104}{827} = 0.28.\]</span> We now determine expected (pooled) success and failure counts:</p>
<p><span class="math inline">\(0.28 \cdot (131 + 258) = 108.92\)</span>, <span class="math inline">\(0.72 \cdot (131 + 258) = 280.08\)</span></p>
<p><span class="math inline">\(0.28 \cdot (104 + 334) = 122.64\)</span>, <span class="math inline">\(0.72 \cdot (104 + 334) = 315.36\)</span></p></li>
<li><p><em>Independent selection of samples</em>: The cases are not paired in any meaningful way.</p>
<p>We have no reason to suspect that a college graduate selected would have any relationship to a non-college graduate selected.</p></li>
</ol>
</div>
<div id="test-statistic-2" class="section level3">
<h3><span class="header-section-number">B.4.7</span> Test statistic</h3>
<p>The test statistic is a random variable based on the sample data. Here, we are interested in seeing if our observed difference in sample proportions corresponding to no opinion on drilling (<span class="math inline">\(\hat{p}_{college, obs} - \hat{p}_{no\_college, obs}\)</span> = 0.0326) is statistically different than 0. Assuming that conditions are met and the null hypothesis is true, we can use the standard normal distribution to standardize the difference in sample proportions (<span class="math inline">\(\hat{P}_{college} - \hat{P}_{no\_college}\)</span>) using the standard error of <span class="math inline">\(\hat{P}_{college} - \hat{P}_{no\_college}\)</span> and the pooled estimate:</p>
<p><span class="math display">\[ Z =\dfrac{ (\hat{P}_1 - \hat{P}_2) - 0}{\sqrt{\dfrac{\hat{P}(1 - \hat{P})}{n_1} + \dfrac{\hat{P}(1 - \hat{P})}{n_2} }} \sim N(0, 1) \]</span> where <span class="math inline">\(\hat{P} = \dfrac{\text{total number of successes} }{ \text{total number of cases}}.\)</span></p>
<div id="observed-test-statistic-2" class="section level4">
<h4><span class="header-section-number">B.4.7.1</span> Observed test statistic</h4>
<p>While one could compute this observed test statistic by “hand”, the focus here is on the set-up of the problem and in understanding which formula for the test statistic applies. We can use the <code>prop.test</code> function to perform this analysis for us.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stats::<span class="kw">prop.test</span>(<span class="dt">x =</span> <span class="kw">table</span>(offshore$college_grad, offshore$response),
       <span class="dt">n =</span> <span class="kw">nrow</span>(offshore),
       <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,
       <span class="dt">correct =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions without continuity
##  correction
## 
## data:  table(offshore$college_grad, offshore$response)
## X-squared = 10, df = 1, p-value = 0.002
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  0.03773 0.16091
## sample estimates:
## prop 1 prop 2 
## 0.3368 0.2374</code></pre>
<p><code>prop.test</code> does a <span class="math inline">\(\chi^2\)</span> test here but this matches up exactly with what we would expect from the test statistic above since <span class="math inline">\(Z^2 = \chi^2\)</span> so <span class="math inline">\(\sqrt{9.99} = 3.16 = z_{obs}\)</span>: The <span class="math inline">\(p\)</span>-values are the same because we are focusing on a two-tailed test. The observed difference in sample proportions is 3.16 standard deviations larger than 0.</p>
<p>The <span class="math inline">\(p\)</span>-value—the probability of observing a <span class="math inline">\(Z\)</span> value of 3.16 or more extreme in our null distribution—is 0.0016. This can also be calculated in R directly:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> *<span class="st"> </span><span class="kw">pnorm</span>(<span class="fl">3.16</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## [1] 0.001578</code></pre>
<p>The 95% confidence interval is also stated above in the <code>prop.test</code> results.</p>
</div>
</div>
<div id="state-conclusion-2" class="section level3">
<h3><span class="header-section-number">B.4.8</span> State conclusion</h3>
<p>We, therefore, have sufficient evidence to reject the null hypothesis. Our initial guess that a statistically significant difference did not exist in the proportions of no opinion on offshore drilling between college educated and non-college educated Californians was not validated. We do have evidence to suggest that there is a dependency between college graduation and position on offshore drilling for Californians.</p>
<hr />
</div>
<div id="comparing-results-2" class="section level3">
<h3><span class="header-section-number">B.4.9</span> Comparing results</h3>
<p>Observing the bootstrap distribution and the null distribution that were created, it makes quite a bit of sense that the results are so similar for traditional and non-traditional methods in terms of the <span class="math inline">\(p\)</span>-value and the confidence interval since these distributions look very similar to normal distributions. The conditions were not met since the number of pairs was small, but the sample data was not highly skewed. Using any of the methods whether they are traditional (formula-based) or non-traditional (computational-based) lead to similar results.</p>
<hr />
<hr />
</div>
</div>
<div id="two-means-independent-samples" class="section level2">
<h2><span class="header-section-number">B.5</span> Two Means (Independent Samples)</h2>
<div id="problem-statement-3" class="section level3">
<h3><span class="header-section-number">B.5.1</span> Problem Statement</h3>
<p>Average income varies from one region of the country to another, and it often reflects both lifestyles and regional living expenses. Suppose a new graduate is considering a job in two locations, Cleveland, OH and Sacramento, CA, and he wants to see whether the average income in one of these cities is higher than the other. He would like to conduct a hypothesis test based on two randomly selected samples from the 2000 Census. <span class="citation">(Tweaked a bit from Diez, Barr, and Çetinkaya-Rundel <a href="#ref-isrs2014">2014</a> [Chapter 5])</span></p>
</div>
<div id="competing-hypotheses-3" class="section level3">
<h3><span class="header-section-number">B.5.2</span> Competing Hypotheses</h3>
<div id="in-words-3" class="section level4">
<h4><span class="header-section-number">B.5.2.1</span> In words</h4>
<ul>
<li><p>Null hypothesis: There is no association between income and location (Cleveland, OH and Sacramento, CA).</p></li>
<li><p>Alternative hypothesis: There is an association between income and location (Cleveland, OH and Sacramento, CA).</p></li>
</ul>
</div>
<div id="another-way-in-words-1" class="section level4">
<h4><span class="header-section-number">B.5.2.2</span> Another way in words</h4>
<ul>
<li><p>Null hypothesis: The mean income is the <strong>same</strong> for both cities.</p></li>
<li><p>Alternative hypothesis: The mean income is different for the two cities.</p></li>
</ul>
</div>
<div id="in-symbols-with-annotations-3" class="section level4">
<h4><span class="header-section-number">B.5.2.3</span> In symbols (with annotations)</h4>
<ul>
<li><span class="math inline">\(H_0: \mu_{sac} = \mu_{cle}\)</span> or <span class="math inline">\(H_0: \mu_{sac} - \mu_{cle} = 0\)</span>, where <span class="math inline">\(\mu\)</span> represents the average income.</li>
<li><span class="math inline">\(H_A: \mu_{sac} - \mu_{cle} \ne 0\)</span></li>
</ul>
</div>
<div id="set-alpha-3" class="section level4">
<h4><span class="header-section-number">B.5.2.4</span> Set <span class="math inline">\(\alpha\)</span></h4>
<p>It’s important to set the significance level before starting the testing using the data. Let’s set the significance level at 5% here.</p>
</div>
</div>
<div id="exploring-the-sample-data-3" class="section level3">
<h3><span class="header-section-number">B.5.3</span> Exploring the sample data</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">inc_summ &lt;-<span class="st"> </span>cleSac %&gt;%<span class="st"> </span><span class="kw">group_by</span>(metro_area) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">sample_size =</span> <span class="kw">n</span>(),
    <span class="dt">mean =</span> <span class="kw">mean</span>(income),
    <span class="dt">sd =</span> <span class="kw">sd</span>(income),
    <span class="dt">minimum =</span> <span class="kw">min</span>(income),
    <span class="dt">lower_quartile =</span> <span class="kw">quantile</span>(income, <span class="fl">0.25</span>),
    <span class="dt">median =</span> <span class="kw">median</span>(income),
    <span class="dt">upper_quartile =</span> <span class="kw">quantile</span>(income, <span class="fl">0.75</span>),
    <span class="dt">max =</span> <span class="kw">max</span>(income))
<span class="kw">kable</span>(inc_summ)</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">metro_area</th>
<th align="right">sample_size</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">minimum</th>
<th align="right">lower_quartile</th>
<th align="right">median</th>
<th align="right">upper_quartile</th>
<th align="right">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Cleveland_ OH</td>
<td align="right">212</td>
<td align="right">27467</td>
<td align="right">27681</td>
<td align="right">0</td>
<td align="right">8475</td>
<td align="right">21000</td>
<td align="right">35275</td>
<td align="right">152400</td>
</tr>
<tr class="even">
<td align="left">Sacramento_ CA</td>
<td align="right">175</td>
<td align="right">32428</td>
<td align="right">35774</td>
<td align="right">0</td>
<td align="right">8050</td>
<td align="right">20000</td>
<td align="right">49350</td>
<td align="right">206900</td>
</tr>
</tbody>
</table>
<p>The boxplot below also shows the mean for each group highlighted by the red dots.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cleSac %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> metro_area, <span class="dt">y =</span> income)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>() +
<span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.y =</span> <span class="st">&quot;mean&quot;</span>, <span class="dt">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/boxplot-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="guess-about-statistical-significance-3" class="section level4">
<h4><span class="header-section-number">B.5.3.1</span> Guess about statistical significance</h4>
<p>We are looking to see if a difference exists in the mean income of the two levels of the explanatory variable. Based solely on the boxplot, we have reason to believe that no difference exists. The distributions of income seem similar and the means fall in roughly the same place.</p>
<hr />
</div>
</div>
<div id="non-traditional-methods-3" class="section level3">
<h3><span class="header-section-number">B.5.4</span> Non-traditional methods</h3>
<div id="collecting-summary-info-1" class="section level4">
<h4><span class="header-section-number">B.5.4.1</span> Collecting summary info</h4>
<p>Next we will assign some key values to variable names in R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">xbar_cle &lt;-<span class="st"> </span>inc_summ$mean[<span class="dv">1</span>]
xbar_sac &lt;-<span class="st"> </span>inc_summ$mean[<span class="dv">2</span>]
obs_diff &lt;-<span class="st"> </span>xbar_sac -<span class="st"> </span>xbar_cle
n_cle &lt;-<span class="st"> </span>inc_summ$sample_size[<span class="dv">1</span>]
n_sac &lt;-<span class="st"> </span>inc_summ$sample_size[<span class="dv">2</span>]</code></pre></div>
</div>
<div id="randomization-for-hypothesis-test-1" class="section level4">
<h4><span class="header-section-number">B.5.4.2</span> Randomization for Hypothesis Test</h4>
<p>In order to look to see if the observed sample mean for Sacramento of 27467.066 is statistically different than that for Cleveland of 32427.5429, we need to account for the sample sizes. Note that this is the same as looking to see if <span class="math inline">\(\bar{x}_{sac} - \bar{x}_{cle}\)</span> is statistically different than 0. We also need to determine a process that replicates how the original group sizes of 212 and 175 were selected.</p>
<p>We can use the idea of <em>randomization testing</em> (also known as <em>permutation testing</em>) to simulate the population from which the sample came (with two groups of different sizes) and then generate samples using <em>shuffling</em> from that simulated population to account for sampling variability.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">2016</span>)
many_shuffles &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span>
<span class="st">  </span>(cleSac %&gt;%
<span class="st">     </span><span class="kw">mutate</span>(<span class="dt">income =</span> <span class="kw">shuffle</span>(income)) %&gt;%<span class="st"> </span>
<span class="st">     </span><span class="kw">group_by</span>(metro_area) %&gt;%
<span class="st">     </span><span class="kw">summarize</span>(<span class="dt">mean_inc =</span> <span class="kw">mean</span>(income))
   )
null_distn &lt;-<span class="st"> </span>many_shuffles %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(.index) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">diffmean =</span> <span class="kw">diff</span>(mean_inc))
null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffmean)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/sim4-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>We can next use this distribution to observe our <span class="math inline">\(p\)</span>-value. Recall this is a two-tailed test so we will be looking for values that are greater than or equal to 4960.4768 or less than or equal to -4960.4768 for our <span class="math inline">\(p\)</span>-value.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffmean)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">xintercept =</span> obs_diff) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">xintercept =</span> -obs_diff)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-162-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="calculate-p-value-3" class="section level5">
<h5><span class="header-section-number">B.5.4.2.1</span> Calculate <span class="math inline">\(p\)</span>-value</h5>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pvalue &lt;-<span class="st"> </span>null_distn %&gt;%
<span class="st">  </span><span class="kw">filter</span>( (diffmean &gt;=<span class="st"> </span>obs_diff) |<span class="st"> </span>(diffmean &lt;=<span class="st"> </span>-obs_diff) ) %&gt;%
<span class="st">  </span><span class="kw">nrow</span>() /<span class="st"> </span><span class="kw">nrow</span>(null_distn)
pvalue</code></pre></div>
<pre><code>## [1] 0.1225</code></pre>
<p>So our <span class="math inline">\(p\)</span>-value is 0.1225 and we fail to reject the null hypothesis at the 5% level. You can also see this from the histogram above that we are not very far into the tail of the null distribution.</p>
</div>
</div>
<div id="bootstrapping-for-confidence-interval-3" class="section level4">
<h4><span class="header-section-number">B.5.4.3</span> Bootstrapping for Confidence Interval</h4>
<p>We can also create a confidence interval for the unknown population parameter <span class="math inline">\(\mu_{sac} - \mu_{cle}\)</span> using our sample data with <em>bootstrapping</em>. Here we will bootstrap each of the groups with replacement instead of shuffling. This is done using the <code>groups</code> argument in the <code>resample</code> function to fix the size of each group to be the same as the original group sizes of 175 for Sacramento and 212 for Cleveland.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_means &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *
<span class="st">  </span>cleSac %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">resample</span>(<span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">groups =</span> metro_area) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(metro_area) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_inc =</span> <span class="kw">mean</span>(income))</code></pre></div>
<p>Next, we calculate the difference in sample means for each of the 10,000 replications:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn &lt;-<span class="st"> </span>boot_means %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(.index) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">diffmean =</span> <span class="kw">diff</span>(mean_inc))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffmean)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-165-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(ci_boot &lt;-<span class="st"> </span>boot_distn %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">lower =</span> <span class="kw">quantile</span>(diffmean, <span class="dt">probs =</span> <span class="fl">0.025</span>),
    <span class="dt">upper =</span> <span class="kw">quantile</span>(diffmean, <span class="dt">probs =</span> <span class="fl">0.975</span>)))</code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   lower upper
##   &lt;dbl&gt; &lt;dbl&gt;
## 1 -1513 11459</code></pre>
<p>We see that 0 is contained in this confidence interval as a plausible value of <span class="math inline">\(\mu_{sac} - \mu_{cle}\)</span> (the unknown population parameter). This matches with our hypothesis test results of failing to reject the null hypothesis. Since zero is a plausible value of the population parameter, we do not have evidence that Sacramento incomes are different than Cleveland incomes.</p>
<p><strong>Interpretation</strong>: We are 95% confident the true mean yearly income for those living in Sacramento is between 1512.59 dollars smaller to 11458.85 dollars higher than for Cleveland.</p>
<p><strong>Note</strong>: You could also use the null distribution based on randomization with a shift to have its center at <span class="math inline">\(\bar{x}_{sac} - \bar{x}_{cle} = \$4960.48\)</span> instead of at 0 and calculate its percentiles. The confidence interval produced via this method should be comparable to the one done using bootstrapping above.</p>
<hr />
</div>
</div>
<div id="traditional-methods-3" class="section level3">
<h3><span class="header-section-number">B.5.5</span> Traditional methods</h3>
<div id="check-conditions-3" class="section level5">
<h5><span class="header-section-number">B.5.5.0.1</span> Check conditions</h5>
<p>Remember that in order to use the short-cut (formula-based, theoretical) approach, we need to check that some conditions are met.</p>
<ol style="list-style-type: decimal">
<li><p><em>Independent observations</em>: The observations are independent in both groups.</p>
<p>This <code>metro_area</code> variable is met since the cases are randomly selected from each city.</p></li>
<li><p><em>Approximately normal</em>: The distribution of the response for each group should be normal or the sample sizes should be at least 30.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cleSac %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> income)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">binwidth =</span> <span class="dv">20000</span>) +
<span class="st">  </span><span class="kw">facet_wrap</span>(~<span class="st"> </span>metro_area)</code></pre></div>
<p><img src="ismaykim_files/figure-html/hist-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>We have some reason to doubt the normality assumption here since both the histograms show deviation from a normal model fitting the data well for each group. The sample sizes for each group are greater than 100 though so the assumptions should still apply.</p></li>
<li><p><em>Independent samples</em>: The samples should be collected without any natural pairing.</p>
<p>There is no mention of there being a relationship between those selected in Cleveland and in Sacramento.</p></li>
</ol>
</div>
</div>
<div id="test-statistic-3" class="section level3">
<h3><span class="header-section-number">B.5.6</span> Test statistic</h3>
<p>The test statistic is a random variable based on the sample data. Here, we are interested in seeing if our observed difference in sample means (<span class="math inline">\(\bar{x}_{sac, obs} - \bar{x}_{cle, obs}\)</span> = 4960.4768) is statistically different than 0. Assuming that conditions are met and the null hypothesis is true, we can use the <span class="math inline">\(t\)</span> distribution to standardize the difference in sample means (<span class="math inline">\(\bar{X}_{sac} - \bar{X}_{cle}\)</span>) using the approximate standard error of <span class="math inline">\(\bar{X}_{sac} - \bar{X}_{cle}\)</span> (invoking <span class="math inline">\(S_{sac}\)</span> and <span class="math inline">\(S_{cle}\)</span> as estimates of unknown <span class="math inline">\(\sigma_{sac}\)</span> and <span class="math inline">\(\sigma_{cle}\)</span>).</p>
<p><span class="math display">\[ T =\dfrac{ (\bar{X}_1 - \bar{X}_2) - 0}{ \sqrt{\dfrac{S_1^2}{n_1} + \dfrac{S_2^2}{n_2}}  } \sim t (df = min(n_1 - 1, n_2 - 1)) \]</span> where 1 = Sacramento and 2 = Cleveland with <span class="math inline">\(S_1^2\)</span> and <span class="math inline">\(S_2^2\)</span> the sample variance of the incomes of both cities, respectively, and <span class="math inline">\(n_1 = 175\)</span> for Sacramento and <span class="math inline">\(n_2 = 212\)</span> for Cleveland.</p>
<div id="observed-test-statistic-3" class="section level4">
<h4><span class="header-section-number">B.5.6.1</span> Observed test statistic</h4>
<p>Note that we could also do (ALMOST) this test directly using the <code>t.test</code> function. The <code>x</code> and <code>y</code> arguments are expected to both be numeric vectors here so we’ll need to appropriately filter our data sets.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cleveland &lt;-<span class="st"> </span>cleSac %&gt;%<span class="st"> </span><span class="kw">filter</span>(metro_area ==<span class="st"> &quot;Cleveland_ OH&quot;</span>)
sacramento &lt;-<span class="st"> </span>cleSac %&gt;%<span class="st"> </span><span class="kw">filter</span>(metro_area !=<span class="st"> &quot;Cleveland_ OH&quot;</span>)
<span class="kw">t.test</span>(<span class="dt">y =</span> cleveland$income, <span class="dt">x =</span> sacramento$income,
       <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  sacramento$income and cleveland$income
## t = 1.5, df = 320, p-value = 0.1
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1543 11464
## sample estimates:
## mean of x mean of y 
##     32428     27467</code></pre>
<p>Note that the degrees of freedom reported above are different than what we used above in specifying the <strong>Test Statistic</strong>. The degrees of freedom used here is also known as the Satterthwaite approximation and involves a quite complicated formula. For most problems, the must simpler smaller of sample sizes minus one will suffice.</p>
<p>While one could compute this observed test statistic by “hand”, the focus here is on the set-up of the problem and in understanding which formula for the test statistic applies.</p>
<!--
We can use the `inference` function in the `oilabs` package to perform this analysis for us.  Note that to obtain the `F value` given here, you divide the observed $MSG$ value of 17.53 by the observed $MSE$ value of 1.75.  (The use of the word `Residuals` will make more sense when we have covered regression.)
-->
<p>We see here that the observed test statistic value is around -1.5 with <span class="math inline">\(df = min(212 - 1, 175 - 1) = 174\)</span>. Recall that for large degrees of freedom, the <span class="math inline">\(t\)</span> distribution is roughly equal to the standard normal curve so our difference in <code>df</code> for the Satterthwaite and “min” variations doesn’t really matter.</p>
</div>
</div>
<div id="compute-p-value-2" class="section level3">
<h3><span class="header-section-number">B.5.7</span> Compute <span class="math inline">\(p\)</span>-value</h3>
<p>The <span class="math inline">\(p\)</span>-value—the probability of observing an <span class="math inline">\(t_{174}\)</span> value of -1.501 or more extreme (in both directions) in our null distribution—is 0.13. This can also be calculated in R directly:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> *<span class="st"> </span><span class="kw">pt</span>(-<span class="fl">1.501</span>, <span class="dt">df =</span> <span class="kw">min</span>(<span class="dv">212</span> -<span class="st"> </span><span class="dv">1</span>, <span class="dv">175</span> -<span class="st"> </span><span class="dv">1</span>), <span class="dt">lower.tail =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 0.1352</code></pre>
<p>We can also approximate by using the standard normal curve:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> *<span class="st"> </span><span class="kw">pnorm</span>(-<span class="fl">1.501</span>)</code></pre></div>
<pre><code>## [1] 0.1334</code></pre>
<p>Note that the 95 percent confidence interval given above matches well with the one calculated using bootstrapping.</p>
</div>
<div id="state-conclusion-3" class="section level3">
<h3><span class="header-section-number">B.5.8</span> State conclusion</h3>
<p>We, therefore, do not have sufficient evidence to reject the null hypothesis. Our initial guess that a statistically significant difference not existing in the means was backed by this statistical analysis. We do not have evidence to suggest that the true mean income differs between Cleveland, OH and Sacramento, CA based on this data.</p>
<hr />
</div>
<div id="comparing-results-3" class="section level3">
<h3><span class="header-section-number">B.5.9</span> Comparing results</h3>
<p>Observing the bootstrap distribution and the null distribution that were created, it makes quite a bit of sense that the results are so similar for traditional and non-traditional methods in terms of the <span class="math inline">\(p\)</span>-value and the confidence interval since these distributions look very similar to normal distributions. The conditions also being met leads us to better guess that using any of the methods whether they are traditional (formula-based) or non-traditional (computational-based) will lead to similar results.</p>
<hr />
<hr />
</div>
</div>
<div id="two-means-paired-samples" class="section level2">
<h2><span class="header-section-number">B.6</span> Two Means (Paired Samples)</h2>
<div id="problem-statement-4" class="section level4">
<h4><span class="header-section-number">B.6.0.1</span> Problem Statement</h4>
<p>Trace metals in drinking water affect the flavor and an unusually high concentration can pose a health hazard. Ten pairs of data were taken measuring zinc concentration in bottom water and surface water at 10 randomly selected locations on a stretch of river. Do the data suggest that the true average concentration in the surface water is smaller than that of bottom water? (Note that units are not given.) [Tweaked a bit from <a href="https://onlinecourses.science.psu.edu/stat500/node/51" class="uri">https://onlinecourses.science.psu.edu/stat500/node/51</a>]</p>
</div>
<div id="competing-hypotheses-4" class="section level3">
<h3><span class="header-section-number">B.6.1</span> Competing Hypotheses</h3>
<div id="in-words-4" class="section level4">
<h4><span class="header-section-number">B.6.1.1</span> In words</h4>
<ul>
<li><p>Null hypothesis: The mean concentration in the bottom water is the same as that of the surface water at different paired locations.</p></li>
<li><p>Alternative hypothesis: The mean concentration in the surface water is smaller than that of the bottom water at different paired locations.</p></li>
</ul>
</div>
<div id="in-symbols-with-annotations-4" class="section level4">
<h4><span class="header-section-number">B.6.1.2</span> In symbols (with annotations)</h4>
<ul>
<li><span class="math inline">\(H_0: \mu_{diff} = 0\)</span>, where <span class="math inline">\(\mu_{diff}\)</span> represents the mean difference in concentration for surface water minus bottom water.</li>
<li><span class="math inline">\(H_A: \mu_{diff} &lt; 0\)</span></li>
</ul>
</div>
<div id="set-alpha-4" class="section level4">
<h4><span class="header-section-number">B.6.1.3</span> Set <span class="math inline">\(\alpha\)</span></h4>
<p>It’s important to set the significance level before starting the testing using the data. Let’s set the significance level at 5% here.</p>
</div>
</div>
<div id="exploring-the-sample-data-4" class="section level3">
<h3><span class="header-section-number">B.6.2</span> Exploring the sample data</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#download.file(&quot;http://ismayc.github.io/teaching/sample_problems/zinc_tidy.csv&quot;,</span>
<span class="co">#              destfile = &quot;data/zinc_tidy.csv&quot;,</span>
<span class="co">#              method = &quot;curl&quot;)</span>
zinc_tidy &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/zinc_tidy.csv&quot;</span>)</code></pre></div>
<p>We want to look at the differences in <code>surface - bottom</code> for each location:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">zinc_diff &lt;-<span class="st"> </span>zinc_tidy %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(loc_id) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">pair_diff =</span> <span class="kw">diff</span>(concentration))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">zinc_summ &lt;-<span class="st"> </span>zinc_diff %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">sample_size =</span> <span class="kw">n</span>(),
    <span class="dt">mean =</span> <span class="kw">mean</span>(pair_diff),
    <span class="dt">sd =</span> <span class="kw">sd</span>(pair_diff),
    <span class="dt">minimum =</span> <span class="kw">min</span>(pair_diff),
    <span class="dt">lower_quartile =</span> <span class="kw">quantile</span>(pair_diff, <span class="fl">0.25</span>),
    <span class="dt">median =</span> <span class="kw">median</span>(pair_diff),
    <span class="dt">upper_quartile =</span> <span class="kw">quantile</span>(pair_diff, <span class="fl">0.75</span>),
    <span class="dt">max =</span> <span class="kw">max</span>(pair_diff))
<span class="kw">kable</span>(zinc_summ)</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">sample_size</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">minimum</th>
<th align="right">lower_quartile</th>
<th align="right">median</th>
<th align="right">upper_quartile</th>
<th align="right">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">10</td>
<td align="right">-0.0804</td>
<td align="right">0.0523</td>
<td align="right">-0.177</td>
<td align="right">-0.11</td>
<td align="right">-0.084</td>
<td align="right">-0.0355</td>
<td align="right">-0.015</td>
</tr>
</tbody>
</table>
<p>The histogram below also shows the distribution of <code>pair_diff</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">zinc_diff %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> pair_diff)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="fl">0.04</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/hist1a-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="guess-about-statistical-significance-4" class="section level4">
<h4><span class="header-section-number">B.6.2.1</span> Guess about statistical significance</h4>
<p>We are looking to see if the sample paired mean difference of -0.0804 is statistically less than 0. They seem to be quite close, but we have a small number of pairs here. Let’s guess that we will fail to reject the null hypothesis.</p>
<hr />
</div>
</div>
<div id="non-traditional-methods-4" class="section level3">
<h3><span class="header-section-number">B.6.3</span> Non-traditional methods</h3>
<div id="collecting-summary-info-2" class="section level4">
<h4><span class="header-section-number">B.6.3.1</span> Collecting summary info</h4>
<p>Next we will assign some key values to variable names in R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">obs_diff &lt;-<span class="st"> </span>zinc_summ$mean
n_pairs &lt;-<span class="st"> </span>zinc_summ$sample_size</code></pre></div>
</div>
<div id="randomization-for-hypothesis-test-2" class="section level4">
<h4><span class="header-section-number">B.6.3.2</span> Randomization for Hypothesis Test</h4>
<p>In order to look to see if the observed sample mean difference <span class="math inline">\(\bar{x}_{diff} = -0.0804\)</span> is statistically less than 0, we need to account for the number of pairs. We also need to determine a process that replicates how the paired data was selected in a way similar to how we calculated our original difference in sample means.</p>
<p>We can use the idea of <em>randomization testing</em> (also known as <em>permutation testing</em>) to simulate the population from which the sample came and then generate samples using <em>shuffling</em> from that simulated population to account for sampling variability. In this case, we will shuffle along each paired location. So values that were on the bottom of location 1 may now be switched to be on the surface or vice versa.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(mosaic)
<span class="kw">set.seed</span>(<span class="dv">2016</span>)
many_shuffles &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span>
<span class="st">  </span>(zinc_tidy %&gt;%
<span class="st">     </span><span class="kw">mutate</span>(<span class="dt">concentration =</span> <span class="kw">shuffle</span>(concentration, <span class="dt">groups =</span> loc_id)) %&gt;%<span class="st"> </span>
<span class="st">     </span><span class="kw">group_by</span>(loc_id) %&gt;%<span class="st"> </span>
<span class="st">     </span><span class="kw">summarize</span>(<span class="dt">pair_diff =</span> <span class="kw">diff</span>(concentration))
   )
null_distn &lt;-<span class="st"> </span>many_shuffles %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(.index) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_diff =</span> <span class="kw">mean</span>(pair_diff))
null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean_diff)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/sim5-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>We can next use this distribution to observe our <span class="math inline">\(p\)</span>-value. Recall this is a left-tailed test so we will be looking for values that are less than or equal to -0.0804 for our <span class="math inline">\(p\)</span>-value.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean_diff)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">xintercept =</span> obs_diff)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-168-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="calculate-p-value-4" class="section level5">
<h5><span class="header-section-number">B.6.3.2.1</span> Calculate <span class="math inline">\(p\)</span>-value</h5>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pvalue &lt;-<span class="st"> </span>null_distn %&gt;%
<span class="st">  </span><span class="kw">filter</span>(mean_diff &lt;=<span class="st"> </span>obs_diff) %&gt;%
<span class="st">  </span><span class="kw">nrow</span>() /<span class="st"> </span><span class="kw">nrow</span>(null_distn)
pvalue</code></pre></div>
<pre><code>## [1] 0.0009</code></pre>
<p>So our <span class="math inline">\(p\)</span>-value is essentially 0.0009 and we reject the null hypothesis at the 5% level. You can also see this from the histogram above that we are far into the left tail of the null distribution.</p>
</div>
</div>
<div id="bootstrapping-for-confidence-interval-4" class="section level4">
<h4><span class="header-section-number">B.6.3.3</span> Bootstrapping for Confidence Interval</h4>
<p>We can also create a confidence interval for the unknown population parameter <span class="math inline">\(\mu_{diff}\)</span> using our sample data (the calculated differences) with <em>bootstrapping</em>. This is similar to the bootstrapping done in a one sample mean case, except now our data is differences instead of raw numerical data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span>
<span class="st">  </span><span class="kw">resample</span>(zinc_diff, <span class="dt">replace =</span> <span class="ot">TRUE</span>) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_diff =</span> <span class="kw">mean</span>(pair_diff))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean_diff)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-170-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(ci_boot &lt;-<span class="st"> </span>boot_distn %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">lower =</span> <span class="kw">quantile</span>(mean_diff, <span class="dt">probs =</span> <span class="fl">0.025</span>),
    <span class="dt">upper =</span> <span class="kw">quantile</span>(mean_diff, <span class="dt">probs =</span> <span class="fl">0.975</span>)))</code></pre></div>
<pre><code>##     lower   upper
## 1 -0.1114 -0.0505</code></pre>
<p>We see that 0 is not contained in this confidence interval as a plausible value of <span class="math inline">\(\mu_{diff}\)</span> (the unknown population parameter). This matches with our hypothesis test results of rejecting the null hypothesis. Since zero is not a plausible value of the population parameter and since the entire confidence interval falls below zero, we have evidence that surface zinc concentration levels are lower, on average, than bottom level zinc concentrations.</p>
<p><strong>Interpretation</strong>: We are 95% confident the true mean zinc concentration on the surface is between 0.11 units smaller to 0.05 units smaller than on the bottom.</p>
<p><strong>Note</strong>: You could also use the null distribution based on randomization with a shift to have its center at <span class="math inline">\(\bar{x}_{diff} = -0.08\)</span> instead of at 0 and calculate its percentiles. The confidence interval produced via this method should be comparable to the one done using bootstrapping above.</p>
<hr />
</div>
</div>
<div id="traditional-methods-4" class="section level3">
<h3><span class="header-section-number">B.6.4</span> Traditional methods</h3>
<div id="check-conditions-4" class="section level4">
<h4><span class="header-section-number">B.6.4.1</span> Check conditions</h4>
<p>Remember that in order to use the shortcut (formula-based, theoretical) approach, we need to check that some conditions are met.</p>
<ol style="list-style-type: decimal">
<li><em>Independent observations</em>: The observations among pairs are independent.</li>
</ol>
<p>The locations are selected independently through random sampling so this condition is met.</p>
<ol start="2" style="list-style-type: decimal">
<li><p><em>Approximately normal</em>: The distribution of population of differences is normal or the number of pairs is at least 30.</p>
<p>The histogram above does show some skew so we have reason to doubt the population being normal based on this sample. We also only have 10 pairs which is fewer than the 30 needed. A theory-based test may not be valid here.</p></li>
</ol>
</div>
<div id="test-statistic-4" class="section level4">
<h4><span class="header-section-number">B.6.4.2</span> Test statistic</h4>
<p>The test statistic is a random variable based on the sample data. Here, we want to look at a way to estimate the population mean difference <span class="math inline">\(\mu_{diff}\)</span>. A good guess is the sample mean difference <span class="math inline">\(\bar{X}_{diff}\)</span>. Recall that this sample mean is actually a random variable that will vary as different samples are (theoretically, would be) collected. We are looking to see how likely is it for us to have observed a sample mean of <span class="math inline">\(\bar{x}_{diff, obs} = 0.0804\)</span> or larger assuming that the population mean difference is 0 (assuming the null hypothesis is true). If the conditions are met and assuming <span class="math inline">\(H_0\)</span> is true, we can “standardize” this original test statistic of <span class="math inline">\(\bar{X}_{diff}\)</span> into a <span class="math inline">\(T\)</span> statistic that follows a <span class="math inline">\(t\)</span> distribution with degrees of freedom equal to <span class="math inline">\(df = n - 1\)</span>:</p>
<p><span class="math display">\[ T =\dfrac{ \bar{X}_{diff} - 0}{ S_{diff} / \sqrt{n} } \sim t (df = n - 1) \]</span></p>
<p>where <span class="math inline">\(S\)</span> represents the standard deviation of the sample differences and <span class="math inline">\(n\)</span> is the number of pairs.</p>
<div id="observed-test-statistic-4" class="section level5">
<h5><span class="header-section-number">B.6.4.2.1</span> Observed test statistic</h5>
<p>While one could compute this observed test statistic by “hand”, the focus here is on the set-up of the problem and in understanding which formula for the test statistic applies. We can use the <code>t.test</code> function on the differences to perform this analysis for us.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stats::<span class="kw">t.test</span>(<span class="dt">x =</span> zinc_diff$pair_diff, 
       <span class="dt">alternative =</span> <span class="st">&quot;less&quot;</span>,
       <span class="dt">mu =</span> <span class="dv">0</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  zinc_diff$pair_diff
## t = -4.9, df = 9, p-value = 0.0004
## alternative hypothesis: true mean is less than 0
## 95 percent confidence interval:
##     -Inf -0.0501
## sample estimates:
## mean of x 
##   -0.0804</code></pre>
<p>We see here that the <span class="math inline">\(t_{obs}\)</span> value is around -5.</p>
</div>
</div>
<div id="compute-p-value-3" class="section level4">
<h4><span class="header-section-number">B.6.4.3</span> Compute <span class="math inline">\(p\)</span>-value</h4>
<p>The <span class="math inline">\(p\)</span>-value—the probability of observing a <span class="math inline">\(t_{obs}\)</span> value of -5 or less in our null distribution of a <span class="math inline">\(t\)</span> with 9 degrees of freedom—is 0.0004. This can also be calculated in R directly:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pt</span>(-<span class="dv">5</span>, <span class="dt">df =</span> <span class="kw">nrow</span>(zinc_diff) -<span class="st"> </span><span class="dv">1</span>, <span class="dt">lower.tail =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 0.0003695</code></pre>
</div>
<div id="state-conclusion-4" class="section level4">
<h4><span class="header-section-number">B.6.4.4</span> State conclusion</h4>
<p>We, therefore, have sufficient evidence to reject the null hypothesis. Our initial guess that our observed sample mean difference was not statistically less than the hypothesized mean of 0 has been invalidated here. Based on this sample, we have evidence that the mean concentration in the bottom water is greater than that of the surface water at different paired locations.</p>
<hr />
</div>
</div>
<div id="comparing-results-4" class="section level3">
<h3><span class="header-section-number">B.6.5</span> Comparing results</h3>
<p>Observing the bootstrap distribution and the null distribution that were created, it makes quite a bit of sense that the results are so similar for traditional and non-traditional methods in terms of the <span class="math inline">\(p\)</span>-value and the confidence interval since these distributions look very similar to normal distributions. The conditions were not met since the number of pairs was small, but the sample data was not highly skewed. Using any of the methods whether they are traditional (formula-based) or non-traditional (computational-based) lead to similar results.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-isrs2014">
<p>Diez, David M, Christopher D Barr, and Mine Çetinkaya-Rundel. 2014. <em>Introductory Statistics with Randomization and Simulation</em>. First Edition. <a href="https://www.openintro.org/stat/textbook.php?stat_book=isrs" class="uri">https://www.openintro.org/stat/textbook.php?stat_book=isrs</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="A-appendixA.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="C-appendixC.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ismayc/moderndiver-book/edit/master/92-appendixB.Rmd",
"text": "Edit"
},
"download": ["ismaykim.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
