<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>A MODERN DIVE into Data with R</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="Getting away from the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown">
  <meta name="generator" content="bookdown 0.1 and GitBook 2.6.7">

  <meta property="og:title" content="A MODERN DIVE into Data with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Getting away from the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown" />
  <meta name="github-repo" content="ismayc/moderndiver-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="A MODERN DIVE into Data with R" />
  
  <meta name="twitter:description" content="Getting away from the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown" />
  

<meta name="author" content="Chester Ismay">

<meta name="date" content="2016-09-15">

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="3-tidy.html">
<link rel="next" href="5-manip.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-0.7/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/dygraphs-binding-1.1.1.1/dygraphs.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#colophon"><i class="fa fa-check"></i>Colophon</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-intro.html"><a href="2-intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="2-intro.html"><a href="2-intro.html#preamble"><i class="fa fa-check"></i><b>2.1</b> Preamble</a></li>
<li class="chapter" data-level="2.2" data-path="2-intro.html"><a href="2-intro.html#two-driving-data-sources"><i class="fa fa-check"></i><b>2.2</b> Two driving data sources</a></li>
<li class="chapter" data-level="2.3" data-path="2-intro.html"><a href="2-intro.html#datascience-pipeline"><i class="fa fa-check"></i><b>2.3</b> Data/science pipeline</a></li>
<li class="chapter" data-level="2.4" data-path="2-intro.html"><a href="2-intro.html#reproducibility"><i class="fa fa-check"></i><b>2.4</b> Reproducibility</a></li>
<li class="chapter" data-level="2.5" data-path="2-intro.html"><a href="2-intro.html#who-is-this-book-for"><i class="fa fa-check"></i><b>2.5</b> Who is this book for?</a></li>
</ul></li>
<li class="part"><span><b>Data Exploration</b></span></li>
<li class="chapter" data-level="3" data-path="3-tidy.html"><a href="3-tidy.html"><i class="fa fa-check"></i><b>3</b> Tidy Data</a><ul>
<li class="chapter" data-level="3.1" data-path="3-tidy.html"><a href="3-tidy.html#what-is-tidy-data"><i class="fa fa-check"></i><b>3.1</b> What is tidy data?</a></li>
<li class="chapter" data-level="3.2" data-path="3-tidy.html"><a href="3-tidy.html#the-nycflights13-datasets"><i class="fa fa-check"></i><b>3.2</b> The <code>nycflights13</code> datasets</a></li>
<li class="chapter" data-level="3.3" data-path="3-tidy.html"><a href="3-tidy.html#how-is-flights-tidy"><i class="fa fa-check"></i><b>3.3</b> How is <code>flights</code> tidy?</a></li>
<li class="chapter" data-level="3.4" data-path="3-tidy.html"><a href="3-tidy.html#normal-forms-of-data"><i class="fa fa-check"></i><b>3.4</b> Normal forms of data</a></li>
<li class="chapter" data-level="3.5" data-path="3-tidy.html"><a href="3-tidy.html#whats-to-come"><i class="fa fa-check"></i><b>3.5</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-viz.html"><a href="4-viz.html"><i class="fa fa-check"></i><b>4</b> Visualizing Data</a><ul>
<li class="chapter" data-level="4.1" data-path="4-viz.html"><a href="4-viz.html#five-named-graphs---the-5ng"><i class="fa fa-check"></i><b>4.1</b> Five Named Graphs - The 5NG</a></li>
<li class="chapter" data-level="4.2" data-path="4-viz.html"><a href="4-viz.html#histograms"><i class="fa fa-check"></i><b>4.2</b> Histograms</a><ul>
<li class="chapter" data-level="4.2.1" data-path="4-viz.html"><a href="4-viz.html#contsum"><i class="fa fa-check"></i><b>4.2.1</b> Continuous data summaries</a></li>
<li class="chapter" data-level="4.2.2" data-path="4-viz.html"><a href="4-viz.html#summary"><i class="fa fa-check"></i><b>4.2.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="4-viz.html"><a href="4-viz.html#boxplots"><i class="fa fa-check"></i><b>4.3</b> Boxplots</a><ul>
<li class="chapter" data-level="4.3.1" data-path="4-viz.html"><a href="4-viz.html#faceting"><i class="fa fa-check"></i><b>4.3.1</b> Faceting</a></li>
<li class="chapter" data-level="4.3.2" data-path="4-viz.html"><a href="4-viz.html#summary-1"><i class="fa fa-check"></i><b>4.3.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="4-viz.html"><a href="4-viz.html#barplots"><i class="fa fa-check"></i><b>4.4</b> Barplots</a><ul>
<li class="chapter" data-level="4.4.1" data-path="4-viz.html"><a href="4-viz.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>4.4.1</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="4.4.2" data-path="4-viz.html"><a href="4-viz.html#using-barplots-to-compare-two-variables"><i class="fa fa-check"></i><b>4.4.2</b> Using barplots to compare two variables</a></li>
<li class="chapter" data-level="4.4.3" data-path="4-viz.html"><a href="4-viz.html#summary-2"><i class="fa fa-check"></i><b>4.4.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="4-viz.html"><a href="4-viz.html#scatter-plots"><i class="fa fa-check"></i><b>4.5</b> Scatter-plots</a><ul>
<li class="chapter" data-level="4.5.1" data-path="4-viz.html"><a href="4-viz.html#jittering"><i class="fa fa-check"></i><b>4.5.1</b> Jittering</a></li>
<li class="chapter" data-level="4.5.2" data-path="4-viz.html"><a href="4-viz.html#setting-transparency"><i class="fa fa-check"></i><b>4.5.2</b> Setting transparency</a></li>
<li class="chapter" data-level="4.5.3" data-path="4-viz.html"><a href="4-viz.html#summary-3"><i class="fa fa-check"></i><b>4.5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="4-viz.html"><a href="4-viz.html#line-graphs"><i class="fa fa-check"></i><b>4.6</b> Line-graphs</a><ul>
<li class="chapter" data-level="4.6.1" data-path="4-viz.html"><a href="4-viz.html#summary-4"><i class="fa fa-check"></i><b>4.6.1</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="4-viz.html"><a href="4-viz.html#brief-review-of-the-grammar-of-graphics"><i class="fa fa-check"></i><b>4.7</b> Brief Review of The Grammar of Graphics</a></li>
<li class="chapter" data-level="4.8" data-path="4-viz.html"><a href="4-viz.html#whats-to-come-1"><i class="fa fa-check"></i><b>4.8</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-manip.html"><a href="5-manip.html"><i class="fa fa-check"></i><b>5</b> Manipulating Data</a><ul>
<li class="chapter" data-level="5.1" data-path="5-manip.html"><a href="5-manip.html#five-main-verbs---the-fmv"><i class="fa fa-check"></i><b>5.1</b> Five Main Verbs - The FMV</a><ul>
<li class="chapter" data-level="5.1.1" data-path="5-manip.html"><a href="5-manip.html#select-variables-using-select"><i class="fa fa-check"></i><b>5.1.1</b> Select variables using <code>select</code></a></li>
<li class="chapter" data-level="5.1.2" data-path="5-manip.html"><a href="5-manip.html#filter-observations-using-filter"><i class="fa fa-check"></i><b>5.1.2</b> Filter observations using <code id="filter">filter</code></a></li>
<li class="chapter" data-level="5.1.3" data-path="5-manip.html"><a href="5-manip.html#summarize-variables-using-summarize"><i class="fa fa-check"></i><b>5.1.3</b> Summarize variables using <code>summarize</code></a></li>
<li class="chapter" data-level="5.1.4" data-path="5-manip.html"><a href="5-manip.html#create-new-variableschange-old-variables-using-mutate"><i class="fa fa-check"></i><b>5.1.4</b> Create new variables/change old variables using <code>mutate</code></a></li>
<li class="chapter" data-level="5.1.5" data-path="5-manip.html"><a href="5-manip.html#reorder-the-data-frame-using-arrange"><i class="fa fa-check"></i><b>5.1.5</b> Reorder the data frame using <code id="arrange">arrange</code></a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="5-manip.html"><a href="5-manip.html#the-pipe"><i class="fa fa-check"></i><b>5.2</b> The pipe <code>%&gt;%</code></a></li>
<li class="chapter" data-level="5.3" data-path="5-manip.html"><a href="5-manip.html#joiningmerging-data-frames"><i class="fa fa-check"></i><b>5.3</b> Joining/merging data frames</a></li>
<li class="chapter" data-level="5.4" data-path="5-manip.html"><a href="5-manip.html#whats-to-come-2"><i class="fa fa-check"></i><b>5.4</b> What’s to come?</a></li>
</ul></li>
<li class="part"><span><b>Inference</b></span></li>
<li class="chapter" data-level="6" data-path="6-infer-basics.html"><a href="6-infer-basics.html"><i class="fa fa-check"></i><b>6</b> Inference Basics</a><ul>
<li class="chapter" data-level="6.1" data-path="6-infer-basics.html"><a href="6-infer-basics.html#random-sampling"><i class="fa fa-check"></i><b>6.1</b> Random sampling</a><ul>
<li class="chapter" data-level="6.1.1" data-path="6-infer-basics.html"><a href="6-infer-basics.html#tasting-soup"><i class="fa fa-check"></i><b>6.1.1</b> Tasting soup</a></li>
<li class="chapter" data-level="6.1.2" data-path="6-infer-basics.html"><a href="6-infer-basics.html#common-terms"><i class="fa fa-check"></i><b>6.1.2</b> Common terms</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="6-infer-basics.html"><a href="6-infer-basics.html#simulation"><i class="fa fa-check"></i><b>6.2</b> Simulation</a><ul>
<li class="chapter" data-level="6.2.1" data-path="6-infer-basics.html"><a href="6-infer-basics.html#the-p-value"><i class="fa fa-check"></i><b>6.2.1</b> The p-value</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="6-infer-basics.html"><a href="6-infer-basics.html#bootstrapping"><i class="fa fa-check"></i><b>6.3</b> Bootstrapping</a><ul>
<li class="chapter" data-level="6.3.1" data-path="6-infer-basics.html"><a href="6-infer-basics.html#review-of-bootstrapping"><i class="fa fa-check"></i><b>6.3.1</b> Review of Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="6-infer-basics.html"><a href="6-infer-basics.html#whats-to-come-3"><i class="fa fa-check"></i><b>6.4</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-hypo.html"><a href="7-hypo.html"><i class="fa fa-check"></i><b>7</b> Hypothesis Testing</a><ul>
<li class="chapter" data-level="7.1" data-path="7-hypo.html"><a href="7-hypo.html#trial"><i class="fa fa-check"></i><b>7.1</b> Criminal trial analogy</a><ul>
<li class="chapter" data-level="7.1.1" data-path="7-hypo.html"><a href="7-hypo.html#two-possible-conclusions"><i class="fa fa-check"></i><b>7.1.1</b> Two possible conclusions</a></li>
<li class="chapter" data-level="7.1.2" data-path="7-hypo.html"><a href="7-hypo.html#basic-logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.1.2</b> Basic Logic of Hypothesis Testing</a></li>
<li class="chapter" data-level="7.1.3" data-path="7-hypo.html"><a href="7-hypo.html#statistical-significance"><i class="fa fa-check"></i><b>7.1.3</b> Statistical Significance</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="7-hypo.html"><a href="7-hypo.html#randomization"><i class="fa fa-check"></i><b>7.2</b> Randomization</a><ul>
<li class="chapter" data-level="7.2.1" data-path="7-hypo.html"><a href="7-hypo.html#comparing-action-and-romance-movies"><i class="fa fa-check"></i><b>7.2.1</b> Comparing Action and Romance Movies</a></li>
<li class="chapter" data-level="7.2.2" data-path="7-hypo.html"><a href="7-hypo.html#sampling---randomization"><i class="fa fa-check"></i><b>7.2.2</b> Sampling -&gt; Randomization</a></li>
<li class="chapter" data-level="7.2.3" data-path="7-hypo.html"><a href="7-hypo.html#summary-5"><i class="fa fa-check"></i><b>7.2.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="7-hypo.html"><a href="7-hypo.html#whats-to-come-4"><i class="fa fa-check"></i><b>7.3</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-ci.html"><a href="8-ci.html"><i class="fa fa-check"></i><b>8</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="8.1" data-path="8-ci.html"><a href="8-ci.html#relation-to-hypothesis-testing"><i class="fa fa-check"></i><b>8.1</b> Relation to hypothesis testing</a></li>
<li class="chapter" data-level="8.2" data-path="8-ci.html"><a href="8-ci.html#effect-size"><i class="fa fa-check"></i><b>8.2</b> Effect size</a></li>
<li class="chapter" data-level="8.3" data-path="8-ci.html"><a href="8-ci.html#whats-to-come-5"><i class="fa fa-check"></i><b>8.3</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="9-regress.html"><a href="9-regress.html"><i class="fa fa-check"></i><b>9</b> Simple and Multiple Regression</a><ul>
<li class="chapter" data-level="9.1" data-path="9-regress.html"><a href="9-regress.html#correlation-is-not-causation"><i class="fa fa-check"></i><b>9.1</b> Correlation is not causation</a></li>
<li class="chapter" data-level="9.2" data-path="9-regress.html"><a href="9-regress.html#simple-linear-regression"><i class="fa fa-check"></i><b>9.2</b> Simple linear regression</a></li>
<li class="chapter" data-level="9.3" data-path="9-regress.html"><a href="9-regress.html#mlr"><i class="fa fa-check"></i><b>9.3</b> Multiple linear regression</a></li>
<li class="chapter" data-level="9.4" data-path="9-regress.html"><a href="9-regress.html#types-of-predictors"><i class="fa fa-check"></i><b>9.4</b> Types of predictors</a></li>
<li class="chapter" data-level="9.5" data-path="9-regress.html"><a href="9-regress.html#advanced-topics"><i class="fa fa-check"></i><b>9.5</b> Advanced topics</a></li>
<li class="chapter" data-level="9.6" data-path="9-regress.html"><a href="9-regress.html#whats-to-come-6"><i class="fa fa-check"></i><b>9.6</b> What’s to come?</a></li>
</ul></li>
<li class="part"><span><b>Conclusion</b></span></li>
<li class="chapter" data-level="10" data-path="10-conclusion.html"><a href="10-conclusion.html"><i class="fa fa-check"></i><b>10</b> Concluding Remarks</a></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="A-appendix1.html"><a href="A-appendix1.html"><i class="fa fa-check"></i><b>A</b> Intermediate R</a><ul>
<li class="chapter" data-level="A.1" data-path="A-appendix1.html"><a href="A-appendix1.html#sorted-barplots"><i class="fa fa-check"></i><b>A.1</b> Sorted barplots</a></li>
<li class="chapter" data-level="A.2" data-path="A-appendix1.html"><a href="A-appendix1.html#interactive-graphics"><i class="fa fa-check"></i><b>A.2</b> Interactive graphics</a><ul>
<li class="chapter" data-level="A.2.1" data-path="A-appendix1.html"><a href="A-appendix1.html#interactive-line-graphs"><i class="fa fa-check"></i><b>A.2.1</b> Interactive line-graphs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="B-appendix2.html"><a href="B-appendix2.html"><i class="fa fa-check"></i><b>B</b> Statistical Basics</a><ul>
<li class="chapter" data-level="B.1" data-path="B-appendix2.html"><a href="B-appendix2.html#basic-statistical-terms"><i class="fa fa-check"></i><b>B.1</b> Basic statistical terms</a><ul>
<li class="chapter" data-level="B.1.1" data-path="B-appendix2.html"><a href="B-appendix2.html#mean"><i class="fa fa-check"></i><b>B.1.1</b> Mean</a></li>
<li class="chapter" data-level="B.1.2" data-path="B-appendix2.html"><a href="B-appendix2.html#median"><i class="fa fa-check"></i><b>B.1.2</b> Median</a></li>
<li class="chapter" data-level="B.1.3" data-path="B-appendix2.html"><a href="B-appendix2.html#standard-deviation"><i class="fa fa-check"></i><b>B.1.3</b> Standard deviation</a></li>
<li class="chapter" data-level="B.1.4" data-path="B-appendix2.html"><a href="B-appendix2.html#five-number-summary"><i class="fa fa-check"></i><b>B.1.4</b> Five-number summary</a></li>
<li class="chapter" data-level="B.1.5" data-path="B-appendix2.html"><a href="B-appendix2.html#distribution"><i class="fa fa-check"></i><b>B.1.5</b> Distribution</a></li>
<li class="chapter" data-level="B.1.6" data-path="B-appendix2.html"><a href="B-appendix2.html#outliers"><i class="fa fa-check"></i><b>B.1.6</b> Outliers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A MODERN DIVE into Data with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="viz" class="section level1">
<h1><span class="header-section-number">4</span> Visualizing Data</h1>
<p>In Chapter <a href="3-tidy.html#tidy">3</a>, we discussed the importance of datasets being <strong>tidy</strong>. You will see in examples here why having a tidy dataset helps us immensely with plotting our data. In plotting our data, we will be able to gain valuable insights from our data that we couldn’t initially see from just looking at the raw tidy data. We will focus on using Hadley’s <code>ggplot2</code> package in doing so, which was developed to work specifically on datasets that are <strong>tidy</strong>. It provides an easy way to customize your plots and is based on data visualization theory given in <em>The Grammar of Graphics</em> <span class="citation">(Wilkinson <a href="#ref-wilkinson2005">2005</a>)</span>.</p>
<p>At the most basic level, graphics/plots/charts provide a nice way for us to get a sense for how quantitative variables compare in terms of their center and their spread. The most important thing to know about graphics is that they should be created to make it obvious for your audience to see the findings you want to get across. This requires a balance on not including too much in your plots, but also including enough so that relationships and interesting findings can be easily seen. As we will see, plots/graphics also help us to identify patterns and outliers in our data. We will see that a common extension of these ideas is to compare the distribution of one quantitative variable (i.e., what the spread of a variable looks like) as we go across the levels of a different categorical variable.</p>
<div id="five-named-graphs---the-5ng" class="section level2">
<h2><span class="header-section-number">4.1</span> Five Named Graphs - The 5NG</h2>
<p>For our purposes here, we will be working with five different types of graphs. (Note that we will use a lot of different words here in regards to plotting - “graphs”, “plots”, and “charts” are all ways to discuss a resulting graphic. You can think of them as all being synonyms.) These five plots are:</p>
<ul>
<li>histograms</li>
<li>boxplots</li>
<li>barplots</li>
<li>scatter-plots</li>
<li>line-graphs</li>
</ul>
<p>With this toolbox of plots, you can visualize just about any type of variable thrown at you. We will discuss some other variations of these but with the 5NG in your repertoire you can do big things! Something we will also stress here is that certain plots only work for categorical/logical variables and others only for quantitative variables. You’ll want to quiz yourself often on which plot makes sense with a given problem set-up.</p>
<p>We now introduce another dataframe in the <code>nycflights13</code> package introduced in Chapter <a href="3-tidy.html#tidy">3</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">if(!<span class="kw">require</span>(<span class="st">&quot;nycflights13&quot;</span>))
  <span class="kw">install.packages</span>(<span class="st">&quot;nycflights13&quot;</span>, <span class="dt">repos =</span> <span class="st">&quot;http://cran.rstudio.org&quot;</span>)
<span class="kw">library</span>(nycflights13)
<span class="kw">data</span>(weather)</code></pre></div>
</div>
<div id="histograms" class="section level2">
<h2><span class="header-section-number">4.2</span> Histograms</h2>
<p>Our focus turns to the <code>temp</code> variable in this <code>weather</code> dataset. We would like to visualize what the 26130 temperatures look like. Looking over the <code>weather</code> dataset<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a> and running <code>?weather</code>, we can see that the <code>temp</code> variable corresponds to hourly temperature (in Fahrenheit) recordings at weather stations near airports in New York City. We could just produce points where each of the different values appear on something similar to a number line:</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-14"></span>
<img src="ismay_files/figure-html/unnamed-chunk-14-1.png" alt="Strip Plot of Hourly Temperature Recordings from NYC in 2013" width="\textwidth" />
<p class="caption">
Figure 4.1: Strip Plot of Hourly Temperature Recordings from NYC in 2013
</p>
</div>
<p>This gives us a general idea of how the values of <code>temp</code> differ. We see that temperatures vary from around 11 up to 100 degrees Fahrenheit. The area between 40 and 60 degrees appears to have more points plotted than outside that range.</p>
<p>What is commonly produced instead of this strip plot is a plot known as a <strong>histogram</strong>. The <strong>histogram</strong> shows how many elements of the variable fall in specified <strong>bins</strong>. These <strong>bins</strong> may correspond to between 0-10°F, 10-20°F, etc. To produce a histogram, we introduce Hadley’s <code>ggplot2</code> package <span class="citation">(Wickham and Chang <a href="#ref-R-ggplot2">2016</a>)</span>. We will use the <code>ggplot</code> function which expects at a bare minimal as arguments</p>
<ul>
<li>the dataframe where the variables exist (the <code>data</code> argument) and</li>
<li>the names of the variables to be plotted (the <code>mapping</code> argument).</li>
</ul>
<p>The names of the variables will be entered into the <code>aes</code> function as arguments where <code>aes</code> stands for “aesthetics”.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">if(!<span class="kw">require</span>(<span class="st">&quot;ggplot2&quot;</span>))
  <span class="kw">install.packages</span>(<span class="st">&quot;ggplot2&quot;</span>, <span class="dt">repos =</span> <span class="st">&quot;http://cran.rstudio.org&quot;</span>)
<span class="kw">library</span>(ggplot2)
<span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> temp))</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-15"></span>
<img src="ismay_files/figure-html/unnamed-chunk-15-1.png" alt="ggplot backdrop" width="\textwidth" />
<p class="caption">
Figure 4.2: ggplot backdrop
</p>
</div>
<p>The plot given above is not a histogram, but the output does show us a bit of what is going on with <code>ggplot(data = weather, mapping = aes(x = temp))</code>. It is producing a backdrop onto which we will “paint” elements. We next proceed by adding a layer—hence, the use of the <code>+</code> symbol—to the plot to produce a histogram. (Note also here that we don’t have to specify the <code>data =</code> and <code>mapping =</code> text in our function calls. This is covered in more detail in Chapter 5 of the “Getting Used to R, RStudio, and R Markdown” book <span class="citation">(Ismay <a href="#ref-usedtor2016">2016</a>)</span>).</p>
<p>You are encouraged to enter <strong>Return</strong> on your keyboard after entering the <code>+</code>. As we add more and more elements, it will be nice to keep them indented as you see below. Note that this will not work if you begin the line with the <code>+</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> temp)) +
<span class="st">  </span><span class="kw">geom_histogram</span>()</code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_bin).</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-16"></span>
<img src="ismay_files/figure-html/unnamed-chunk-16-1.png" alt="Histogram of Hourly Temperature Recordings from NYC in 2013" width="\textwidth" />
<p class="caption">
Figure 4.3: Histogram of Hourly Temperature Recordings from NYC in 2013
</p>
</div>
<p>We have the power to specify how many bins we would like to put the data into as an argument in the <code>geom_histogram</code> function. By default, this is chosen to be 30 somewhat arbitrarily and we have received a warning above our plot that this was done. We also notice here that another warning about 1 missing value is given. This value is omitted from the plot. This warning is ignored for future customizations of the plot.</p>
<p>Missing values are a common problem when working with data and there are entire fields of study on how to work with missing data. Frequently what is done is to remove instances from the data set that are missing. This is certainly the easy way to deal with them, but not necessarily the correct decision in all cases. For our purposes, we will usually ignore potential warnings about missing data since R can usually handle them by ignoring them.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> temp)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">60</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-17"></span>
<img src="ismay_files/figure-html/unnamed-chunk-17-1.png" alt="Histogram of Hourly Temperature Recordings from NYC in 2013 - 60 Bins" width="\textwidth" />
<p class="caption">
Figure 4.4: Histogram of Hourly Temperature Recordings from NYC in 2013 - 60 Bins
</p>
</div>
<p>We can tweak the plot a little more by specifying the width of the bins (instead of how many bins to divide the variable into) by using the <code>binwidth</code> argument in the <code>geom_histogram</code> function. We can also add some color to the plot by invoking the <code>fill</code> and <code>color</code> arguments. A listing of all of the built-in colors to R by name and color is available <a href="http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf">here</a>. You are encouraged to play around with tweaking this plot by changing the arguments to help you understand how you could go about making your own histograms.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> temp)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">10</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;forestgreen&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-18"></span>
<img src="ismay_files/figure-html/unnamed-chunk-18-1.png" alt="Histogram of Hourly Temperature Recordings from NYC in 2013 - Binwidth = 10" width="\textwidth" />
<p class="caption">
Figure 4.5: Histogram of Hourly Temperature Recordings from NYC in 2013 - Binwidth = 10
</p>
</div>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC4.1)</strong> What does changing the number of bins from 30 to 60 tell us about the distribution of temperatures?</p>
<p><strong>(LC4.2)</strong> Would you classify the distribution of temperatures as symmetric or skewed?</p>
<p><strong>(LC4.3)</strong> What would you guess is the “center” value in this distribution? Why did you make that choice?</p>
<p><strong>(LC4.4)</strong> Is this data spread out greatly from the center or is it close? Why?</p>
<hr />
<div id="contsum" class="section level3">
<h3><span class="header-section-number">4.2.1</span> Continuous data summaries</h3>
<p>The <code>temp</code> variable is a <strong>continuous</strong> quantitative variable (frequently just called a <strong>continuous variable</strong>). “A variable is <strong>continuous</strong> if you can arrange its values in order and an infinite number of unique values can exist between any two values of the variable” <span class="citation">(Grolemund and Wickham <a href="#ref-rds2016">2016</a>)</span>. Some common examples of continuous variables are time and height. Between any two times there are an infinitely many number of time units that fall between them.<br />
It is often easier to think about quantitative variables that are not continuous to help us better understand continuity. The best example is counts. If we are looking to count the number of flights that depart on a given day from New York City, this variable would not be continuous. It falls on a <strong>discrete</strong> scale.</p>
<p>We can examine some summary information about this <code>temp</code> variable. To do so, we introduce the <code>summary</code> function. (We will see in Chapter <a href="5-manip.html#manip">5</a> how to use the <code>summarize</code> function in the <code>dplyr</code> package to produce similar results.) The syntax here is a little different than what we have seen before. (A further discussion about R syntax is available in Chapter 5 of the “R basics” book <span class="citation">(Ismay <a href="#ref-usedtor2016">2016</a>)</span>). Here, <code>summary</code> is the function and it is expecting an object to be summarized as its argument. The object here is the <code>temp</code> variable in the <code>weather</code> dataframe. To focus on just this one variable <code>temp</code> in <code>weather</code>, we separate them by the dollar sign symbol <code>$</code>. Order matters here: the dataframe comes before the <code>$</code> and the variable/column name comes after.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(weather$temp)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   10.94   39.92   55.04   55.20   69.98  100.00       1</code></pre>
<p>This tells us what is known as the <strong>five-number summary</strong> for our variable, the <strong>mean</strong> value of the variable, and how many missing values <code>NA</code>’s appear in this column of the <code>weather</code> data frame. More information on the concepts of five-number summary and mean is given in Appendix <a href="B-appendix2.html#appendix2">B</a>.</p>
<p>This <code>summary</code> gives us some numerical summaries of our temperature variable. The minimum recorded temperature is 10.94 degrees Fahrenheit and the maximum is 100.04 degrees Fahrenheit. We have one missing value denoted as an <code>NA</code> in the observations of this variable. The median Fahrenheit temperature of 55.04 and mean of 55.2035149 are quite close. This is a property of symmetric distributions.</p>
<p>The last two entries given by <code>summary</code> correspond to the 25<sup>th</sup> percentile and the 75<sup>th</sup> percentile. If we sorted all of the temperatures in increasing order, we would see that 25% of them would fall below 39.92 and that 75% of them would fall below 69.98. This implies that the middle 50% of data values lie between 39.92 and 69.98 degrees Fahrenheit.</p>
<p>Another common measure to determine the variability of a data set is the <strong>standard deviation</strong>. You can read further about the mathematical details of standard deviation in Appendix <a href="B-appendix2.html#appendix2">B</a>, but you can think of it as being a measure of how far the data is, on average, from the mean. Let’s investigate this further by calculating the standard deviation of our temperature variable:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(weather$temp)</code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>Remember that there were some missing values in our temperature data when we plotted it earlier. By default, the <code>sd</code> function that computes standard deviation of a variable will give the value of <code>NA</code> if any of the data is missing. To further understand this, you can look at the help of the <code>sd</code> function in the R Console:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">?sd</code></pre></div>
<p>Under <strong>Usage</strong> you can see that <code>na.rm</code> is set to <code>FALSE</code> by default. We’d like for missing values to be removed from our analysis so we set that value to <code>TRUE</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(weather$temp, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 17.78212</code></pre>
<p>Standard deviation is always in the same units as our original data set. So in this case the standard deviation is in degrees Fahrenheit. Thus, for a randomly selected element in our temperature column, we can expect it to be about 17.7821236 degrees Fahrenheit from our mean value of 55.2035149. By combining this knowledge with the plots above, we can have a good idea for whether this data is very spread out from its center or if it is tightly bunched.</p>
</div>
<div id="summary" class="section level3">
<h3><span class="header-section-number">4.2.2</span> Summary</h3>
<p>Histograms provide a useful way of looking at how ONE continuous variable varies. They allow us to answer questions such as</p>
<ul>
<li>Are there values far away from the center? These are commonly called <strong>outliers</strong> and can frequently be easily identified on a histogram.</li>
<li>Are most values close to the center? If so, the spread of the variable is small. If not, the spread is large.</li>
<li>How spread out are the values? One measure of this spread is <strong>standard deviation</strong> discussed above.</li>
</ul>
<p>The histogram shows how many entries fall in different groupings of this variable. Another common property of distributions is symmetry and as we saw it is quite easily identified by looking over the histogram produced from the variable’s values.</p>
</div>
</div>
<div id="boxplots" class="section level2">
<h2><span class="header-section-number">4.3</span> Boxplots</h2>
<p>Histograms can also be produced to compare the distribution of a variable over another variable. Suppose we were interested in looking at how the temperature recordings we saw in the last section varied by month. This is what is meant by “the distribution of a variable over another variable”: <code>temp</code> is one variable and <code>month</code> is the other variable.</p>
<p>Before we introduce the concept of <strong>boxplots</strong>, we’ll begin with an exploration into <strong>faceting</strong>. We will see that this is a powerful way to look at the relationships of two variables. Specifically this is nice in comparing the distribution of a quantitative variable over different levels of a categorical variable. It is often recommended that you create a faceted histogram and a boxplot in situations such as this. By looking at both of them together, you’ll be able to identify patterns that you may miss by looking at only one of them. As you read through this next section, think about how you might use faceting to look at the relationships between other types of variables using the different types of plots we explore throughout this chapter.</p>
<div id="faceting" class="section level3">
<h3><span class="header-section-number">4.3.1</span> Faceting</h3>
<p>In order to look at histograms of <code>temp</code> for each month, we introduce a new concept called <strong>faceting</strong>. Faceting is used when we’d like to create small multiples of the same plot over a different categorical variable. By default, all of the small multiples will have the same vertical axis. An example will help here. We will discuss the concept of faceting in further detail in Section <a href="4-viz.html#barplots">4.4</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> temp)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">5</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;firebrick&quot;</span>) +
<span class="st">  </span><span class="kw">facet_wrap</span>(~<span class="st"> </span>month)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:facethistogram"></span>
<img src="ismay_files/figure-html/facethistogram-1.png" alt="Faceted histogram" width="\textwidth" />
<p class="caption">
Figure 4.6: Faceted histogram
</p>
</div>
<p>As we might expect, the temperature tends to increase as summer approaches and then decrease as winter approaches.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC4.5)</strong> What other things do you notice about the faceted plot above? How does a faceted plot help us see how relationships between two variables?</p>
<p><strong>(LC4.6)</strong> What do the numbers 1-12 correspond to in the plot above? What about 25, 50, 75, 100?</p>
<p><strong>(LC4.7)</strong> What could be done to make the faceted plot above more readable? (Focus on tweaking the histograms and not on making a different type of plot here.)</p>
<p><strong>(LC4.8)</strong> For which types of datasets would these types of faceted plots not work well in comparing relationships between variables? Give an example describing the variability of the variables and other important characteristics.</p>
<p><strong>(LC4.9)</strong> Does the <code>temp</code> variable in the <code>weather</code> data set have a lot of variability? Why do you say that?</p>
<hr />
<p>Histograms can provide a way to compare distributions across groups as we see above when we looked at temperature over months. Frequently, a plot called a <strong>boxplot</strong> (also called a <strong>side-by-side boxplot</strong>) is done instead. The <strong>boxplot</strong> uses the information provided in the <strong>five-number summary</strong> referred to in the previous section when we used the <code>summary</code> function. It gives a way to compare this summary information across the different levels of a group. Let’s create a boxplot to compare the monthly temperatures as we did above with the faceted histograms.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> month, <span class="dt">y =</span> temp)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<pre><code>## Warning: Continuous x aesthetic -- did you forget aes(group=...)?</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_boxplot).</code></pre>
<div class="figure" style="text-align: center"><span id="fig:badbox"></span>
<img src="ismay_files/figure-html/badbox-1.png" alt="Invalid boxplot specification" width="\textwidth" />
<p class="caption">
Figure 4.7: Invalid boxplot specification
</p>
</div>
<p>Note the first warning that is given here. (The second one corresponds to missing values in the dataframe and it is turned off on subsequent plots.) Observe that this plot does not look like what we were expecting. We were expecting to see the distribution of temperatures for each month (so 12 different boxplots). This gives us the overall boxplot without any other groupings. We can get around this by introducing a new function for our <code>x</code> variable.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> weather, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(month), <span class="dt">y =</span> temp)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:monthtempbox"></span>
<img src="ismay_files/figure-html/monthtempbox-1.png" alt="Month by temp boxplot" width="\textwidth" />
<p class="caption">
Figure 4.8: Month by temp boxplot
</p>
</div>
<p>We have introduced a new function called <code>factor()</code> here. One of the things this function does is to convert a discrete value like <code>month</code> (1, 2, …, 12) into a categorical variable. The “box” part of this plot represents the 25<sup>th</sup> percentile, the median (50<sup>th</sup> percentile), and the 75<sup>th</sup> percentile. The dots correspond to <strong>outliers</strong>. (The specific formulation for these outliers is discussed in Appendix <a href="B-appendix2.html#appendix2">B</a>.) The lines show how the data varies that is not in the center 50% defined by the first and third quantiles. Longer lines correspond to more variability and shorter lines correspond to less variability.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC4.10)</strong> What does the dot at the bottom of the plot for May correspond to? Explain what might have occurred in May to produce this point.</p>
<p><strong>(LC4.11)</strong> Which months have the highest variability in temperature? What reasons do you think this is?</p>
<p><strong>(LC4.12)</strong> We looked at the distribution of a continuous variable over a categorical variable here with this boxplot. Why can’t we look at the distribution of one continuous variable over the distribution of another continuous variable? Say temperature across pressure, for example?</p>
<p><strong>(LC4.13)</strong> Boxplots provide a simple way to identify outliers. Why may outliers be easier to identify when looking at a boxplot instead of a faceted histogram?</p>
<hr />
</div>
<div id="summary-1" class="section level3">
<h3><span class="header-section-number">4.3.2</span> Summary</h3>
<p>Boxplots provide a way to compare and contrast the distribution of ONE quantitative variable across multiple levels of ONE categorical variable. One can easily look to see where the median falls across the different groups by looking at the center line in the box. You can also see how spread out the variable is across the different groups by looking at the width of the box and also how far out the lines stretch from the box. If the lines stretch far from the box but the box has a small width, the variability of the values closer to the center is much smaller than the variable of the outer ends of the variable. Lastly, outliers are even more easily identified when looking at a boxplot than when looking at a histogram.</p>
</div>
</div>
<div id="barplots" class="section level2">
<h2><span class="header-section-number">4.4</span> Barplots</h2>
<p>Both histograms and boxplots represent ways to visualize the variability of continuous variables. Another common task is to present the distribution of a categorical variable. This is a simpler task since we will be interested in how many elements from our data fall into the different categories of the categorical variable. We need not bin the data or identify the different quantiles for categorical variables.</p>
<p>Frequently, the best way to visualize these different counts (also known as <strong>frequencies</strong>) is via a barplot. Consider the distribution of airlines that flew out of New York City in 2013. Here we explore the number of flights from each airline/<code>carrier</code>. This can be plotted by invoking the <code>geom_bar</code> function in <code>ggplot2</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> flights, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> carrier)) +
<span class="st">  </span><span class="kw">geom_bar</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:flightsbar"></span>
<img src="ismay_files/figure-html/flightsbar-1.png" alt="Number of flights departing NYC in 2013 by airline" width="\textwidth" />
<p class="caption">
Figure 4.9: Number of flights departing NYC in 2013 by airline
</p>
</div>
<p>Recall the <code>airlines</code> dataset discussed in Chapter <a href="3-tidy.html#tidy">3</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">if(!<span class="kw">require</span>(<span class="st">&quot;nycflights13&quot;</span>))
  <span class="kw">install.packages</span>(<span class="st">&quot;nycflights13&quot;</span>, <span class="dt">repos =</span> <span class="st">&quot;http://cran.rstudio.org&quot;</span>)
<span class="kw">library</span>(nycflights13)
<span class="kw">data</span>(airlines)
airlines</code></pre></div>
<pre><code>## # A tibble: 16 × 2
##    carrier                        name
##      &lt;chr&gt;                       &lt;chr&gt;
## 1       9E           Endeavor Air Inc.
## 2       AA      American Airlines Inc.
## 3       AS        Alaska Airlines Inc.
## 4       B6             JetBlue Airways
## 5       DL        Delta Air Lines Inc.
## 6       EV    ExpressJet Airlines Inc.
## 7       F9      Frontier Airlines Inc.
## 8       FL AirTran Airways Corporation
## 9       HA      Hawaiian Airlines Inc.
## 10      MQ                   Envoy Air
## 11      OO       SkyWest Airlines Inc.
## 12      UA       United Air Lines Inc.
## 13      US             US Airways Inc.
## 14      VX              Virgin America
## 15      WN      Southwest Airlines Co.
## 16      YV          Mesa Airlines Inc.</code></pre>
<p>We see that United Air Lines, JetBlue Airways, and ExpressJet Airlines had the most flights depart New York City in 2013. To get the actual number of flights by each airline we can use the <code>count</code> function in the <code>dplyr</code> package on the <code>carrier</code> variable in <code>flights</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">if(!<span class="kw">require</span>(<span class="st">&quot;dplyr&quot;</span>))
  <span class="kw">install.packages</span>(<span class="st">&quot;dplyr&quot;</span>, <span class="dt">repos =</span> <span class="st">&quot;http://cran.rstudio.org&quot;</span>)
<span class="kw">library</span>(dplyr)
flights_table &lt;-<span class="st"> </span><span class="kw">count</span>(<span class="dt">x =</span> flights, <span class="dt">vars =</span> carrier)
flights_table</code></pre></div>
<pre><code>## # A tibble: 16 × 2
##     vars     n
##    &lt;chr&gt; &lt;int&gt;
## 1     9E 18460
## 2     AA 32729
## 3     AS   714
## 4     B6 54635
## 5     DL 48110
## 6     EV 54173
## 7     F9   685
## 8     FL  3260
## 9     HA   342
## 10    MQ 26397
## 11    OO    32
## 12    UA 58665
## 13    US 20536
## 14    VX  5162
## 15    WN 12275
## 16    YV   601</code></pre>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC4.14)</strong> Why are histograms inappropriate for visualizing categorical variables?</p>
<p><strong>(LC4.15)</strong> What is the difference between histograms and barplots?</p>
<p><strong>(LC4.16)</strong> How many Envoy Air flights departed NYC in 2013?</p>
<p><strong>(LC4.17)</strong> What was the seventh highest airline in terms of departed flights from NYC in 2013?</p>
<hr />
<div id="must-avoid-pie-charts" class="section level3">
<h3><span class="header-section-number">4.4.1</span> Must avoid pie charts!</h3>
<p>Unfortunately, one of the most common plots seen today for categorical data is the pie chart. While they may see harmless enough, they actually present a problem in that humans are unable to judge angles well. As Naomi Robbins describes in her book “Creating More Effective Graphs” <span class="citation">(Robbins <a href="#ref-robbins2013">2013</a>)</span>, we overestimate angles greater than 90 degrees and we underestimate angles less than 90 degrees. In other words, it is difficult for us to determine relative size of one piece of the pie compared to another.</p>
<p>Let’s examine our previous barplot example on the number of flights departing NYC by airline. This time we will use a pie chart. As you review this chart, try to identify</p>
<ul>
<li>how much larger the portion of the pie is for ExpressJet Airlines (<code>EV</code>) compared to US Airways (<code>US</code>),</li>
<li>what the third largest carrier is in terms of departing flights, and</li>
<li>how many carriers have fewer flights than United Airlines (<code>UA</code>)?</li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:carrierpie"></span>
<img src="ismay_files/figure-html/carrierpie-1.png" alt="The dreaded pie chart" width="\textwidth" />
<p class="caption">
Figure 4.10: The dreaded pie chart
</p>
</div>
<p>While it is quite easy to look back at the barplot to get the answer to these questions, it’s quite difficult to get the answers correct when looking at the pie graph. Barplots can always present the information in a way that is easier for the eye to determine relative position. There may be one exception from Nathan Yau at <a href="https://flowingdata.com/2008/09/19/pie-i-have-eaten-and-pie-i-have-not-eaten/" title="Pie I Have Eaten and Pie I Have Not Eaten">FlowingData.com</a> but we will leave this for the reader to decide:</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-25"></span>
<img src="images/Pie-I-have-Eaten.jpg" alt="The only good pie chart" width="\textwidth" />
<p class="caption">
Figure 4.11: The only good pie chart
</p>
</div>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC4.18)</strong> Why should pie charts be avoided and replaced by barplots?</p>
<p><strong>(LC4.19)</strong> What is your opinion as to why pie charts continue to be used?</p>
<hr />
</div>
<div id="using-barplots-to-compare-two-variables" class="section level3">
<h3><span class="header-section-number">4.4.2</span> Using barplots to compare two variables</h3>
<p>Barplots are the go-to way to visualize the frequency of different categories of a categorical variable. They make it easy to order the counts and to compare one group’s frequency to another. Another use of barplots (unfortunately, sometimes inappropriately and confusingly) is to compare two categorical variables together. Let’s examine the distribution of outgoing flights from NYC by <code>carrier</code> and <code>airport</code>.</p>
<p>We begin by getting the names of the airports in NYC that were included in the <code>flights</code> dataset. Remember from Chapter <a href="3-tidy.html#tidy">3</a> that this can be done by using the <code>inner_join</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
flights_namedports &lt;-<span class="st"> </span><span class="kw">inner_join</span>(flights, airports, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;origin&quot;</span> =<span class="st"> &quot;faa&quot;</span>))</code></pre></div>
<p>After running <code>View(flights_namedports)</code>, we see that <code>name</code> now corresponds to the name of the airport as referenced by the <code>origin</code> variable. We will now plot <code>carrier</code> as the horizontal variable. When we specify <code>geom_bar</code>, it will specify <code>count</code> as being the vertical variable. A new addition here is <code>fill = name</code>. Look over what was produced from the plot to get an idea of what this argument gives.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> flights_namedports, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> carrier, <span class="dt">fill =</span> name)) +
<span class="st">  </span><span class="kw">geom_bar</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-27"></span>
<img src="ismay_files/figure-html/unnamed-chunk-27-1.png" alt="Stacked barplot comparing the number of flights by carrier and airport" width="\textwidth" />
<p class="caption">
Figure 4.12: Stacked barplot comparing the number of flights by carrier and airport
</p>
</div>
<p>This plot is what is known as a <strong>stacked barplot</strong>. While simple to make, it often leads to many problems.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC4.20)</strong> What kinds of questions are not easily answered by looking at the above figure?</p>
<p><strong>(LC4.21)</strong> What can you say, if anything, about the relationship between airline and airport in NYC in 2013 in regards to the number of departing flights?</p>
<hr />
<p>Another variation on the <strong>stacked barplot</strong> is the <strong>side-by-side barplot</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> flights_namedports, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> carrier, <span class="dt">fill =</span> name)) +
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-28"></span>
<img src="ismay_files/figure-html/unnamed-chunk-28-1.png" alt="Side-by-side barplot comparing the number of flights by carrier and airport" width="\textwidth" />
<p class="caption">
Figure 4.13: Side-by-side barplot comparing the number of flights by carrier and airport
</p>
</div>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC4.22)</strong> Why might the side-by-side barplot be preferable to a stacked barplot in this case?</p>
<p><strong>(LC4.23)</strong> What are the disadvantages of using a side-by-side barplot, in general?</p>
<hr />
<p>Lastly, an often preferred type of barplot is the <strong>faceted barplot</strong>. We already saw this concept of faceting and small multiples in Subsection <a href="4-viz.html#faceting">4.3.1</a>. This gives us a nicer way to compare the distributions across both <code>carrier</code> and airport/<code>name</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> flights_namedports, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> carrier, <span class="dt">fill =</span> name)) +
<span class="st">  </span><span class="kw">geom_bar</span>() +
<span class="st">  </span><span class="kw">facet_grid</span>(name ~<span class="st"> </span>.)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-29"></span>
<img src="ismay_files/figure-html/unnamed-chunk-29-1.png" alt="Faceted barplot comparing the number of flights by carrier and airport" width="\textwidth" />
<p class="caption">
Figure 4.14: Faceted barplot comparing the number of flights by carrier and airport
</p>
</div>
<p>Note how the <code>facet_grid</code> function arguments are written here. We are wanting the names of the airports vertically and the <code>carrier</code> listed horizontally. As you may have guessed, this argument and other <em>formulas</em> of this sort in R are in <code>y ~ x</code> order. We will see more examples of this in Chapter <a href="9-regress.html#regress">9</a>.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC4.24)</strong> Why is the faceted barplot preferred to the side-by-side and stacked barplots in this case?</p>
<p><strong>(LC4.25)</strong> What information about the different carriers at different airports is more easily seen in the faceted barplot?</p>
<hr />
</div>
<div id="summary-2" class="section level3">
<h3><span class="header-section-number">4.4.3</span> Summary</h3>
<p>Barplots are the preferred way of displaying categorical variables. They are easy-to-understand and to make comparisons across groups of a categorical variable. When dealing with more than one categorical variable, faceted barplots are frequently preferred over side-by-side or stacked barplots. Stacked barplots are sometimes nice to look at, but it is quite difficult to compare across the levels since the sizes of the bars are all of different sizes. Side-by-side barplots can provide an improvement on this, but the issue about comparing across groups still must be dealt with.</p>
</div>
</div>
<div id="scatter-plots" class="section level2">
<h2><span class="header-section-number">4.5</span> Scatter-plots</h2>
<p>We have seen that boxplots are most appropriate when plotting the distribution of ONE continuous variable across different levels/groups of ONE categorical variable. Barplots (preferably the faceted type) are best when looking at the distribution of ONE categorical variable across different levels of another categorical variable. But what if we are looking to investigate the relationship between TWO continuous variables? What is commonly produced is the well-known <strong>scatter-plot</strong>, which shows the points corresponding to the values of each of the variables scattered around.</p>
<p>We will now investigate arrival delays (the vertical “y” axis variable) versus departure delays (the horizontal “x” axis variable) for Alaska Airlines flights leaving NYC in 2013. Notice the new function that is invoked here: <code>filter</code>, which resides in the <code>dplyr</code> package. You will see many more examples using this function in Chapter <a href="5-manip.html#manip">5</a>. The <code>filter</code> function goes through the dataframe specified (<code>flights</code> here) and selects only those rows which meet the condition given (<code>carrier == &quot;AS&quot;</code> here).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">alaska_flights &lt;-<span class="st"> </span><span class="kw">filter</span>(flights, carrier ==<span class="st"> &quot;AS&quot;</span>)
<span class="kw">ggplot</span>(alaska_flights, <span class="kw">aes</span>(<span class="dt">x =</span> dep_delay, <span class="dt">y =</span> arr_delay)) +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:noalpha"></span>
<img src="ismay_files/figure-html/noalpha-1.png" alt="Arrival Delays vs Departure Delays for Alaska Airlines flights from NYC in 2013" width="\textwidth" />
<p class="caption">
Figure 4.15: Arrival Delays vs Departure Delays for Alaska Airlines flights from NYC in 2013
</p>
</div>
<p>We see that a positive relationship exists between <code>dep_delay</code> and <code>arr_delay</code>: as departure delays increase, arrival delays tend to also increase. We also note that the majority of points fall near the point (0, 0) here. There is a large mass of points clustered there.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC4.26)</strong> What are some practical reasons why <code>dep_delay</code> and <code>arr_delay</code> have a positive relationship?</p>
<p><strong>(LC4.27)</strong> What variables (not necessarily in the <code>flights</code> dataframe) would you expect to have a negative correlation (i.e. a negative relationship) with <code>dep_delay</code>? Why? Remember that we are focusing on continuous variables here.</p>
<p><strong>(LC4.28)</strong> Why do you believe there is a cluster of points near (0, 0)?</p>
<ul>
<li>What does (0, 0) correspond to in terms of the Alaskan flights?</li>
</ul>
<p><strong>(LC4.29)</strong> What are some other features of the plot that stand out to you?</p>
<hr />
<div id="jittering" class="section level3">
<h3><span class="header-section-number">4.5.1</span> Jittering</h3>
<p>The large mass of points near (0, 0) can cause some confusion. This is the result of a phenomenon called <strong>over-plotting</strong>. As one may guess, this corresponds to values being plotted on top of each other <em>over</em> and <em>over</em> again. It is often difficult to know just how many values are plotted in this way when looking at a basic scatter-plot as we have here.</p>
<p>One way of relieving this issue of <strong>over-plotting</strong> is to <strong>jitter</strong> the points a bit. In other words, we are going to add just a bit of random noise to the points to better see them and remove some of the over-plotting. You can think of “jittering” as shaking the points a bit on the plot. Instead of using <code>geom_point</code>, we use <code>geom_jitter</code> to perform this shaking and specify around how much jitter to add with the <code>width</code> and <code>height</code> arguments. This corresponds to how hard you’d like to shake the plot in units corresponding to those for both the horizontal and vertical variables (minutes here).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(alaska_flights, <span class="kw">aes</span>(<span class="dt">x =</span> dep_delay, <span class="dt">y =</span> arr_delay)) +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="dv">30</span>, <span class="dt">height =</span> <span class="dv">30</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-31"></span>
<img src="ismay_files/figure-html/unnamed-chunk-31-1.png" alt="Jittered delay scatterplot" width="\textwidth" />
<p class="caption">
Figure 4.16: Jittered delay scatterplot
</p>
</div>
<p>This helps us a little bit in getting a sense for the over-plotting, but with a relatively large dataset like this one (714 flights), it is often useful to change the transparency of the points as seen in the next section.</p>
</div>
<div id="setting-transparency" class="section level3">
<h3><span class="header-section-number">4.5.2</span> Setting transparency</h3>
<p>One of the arguments that can be changed with <code>geom_point</code> is <code>alpha</code>. By default, this value is set to <code>1</code>. We can change this value to a smaller fraction to change the transparency of the points in the plot:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(alaska_flights, <span class="kw">aes</span>(<span class="dt">x =</span> dep_delay, <span class="dt">y =</span> arr_delay)) +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.2</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:alpha"></span>
<img src="ismay_files/figure-html/alpha-1.png" alt="Arrival Delays vs Departure Delays for Alaska Airlines flights from NYC in 2013 - alpha=0.2 1" width="\textwidth" />
<p class="caption">
Figure 4.17: Arrival Delays vs Departure Delays for Alaska Airlines flights from NYC in 2013 - alpha=0.2 1
</p>
</div>
<p>We can also specify the <code>alpha</code> argument in <code>geom_jitter</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(alaska_flights, <span class="kw">aes</span>(<span class="dt">x =</span> dep_delay, <span class="dt">y =</span> arr_delay)) +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="dv">30</span>, <span class="dt">height =</span> <span class="dv">30</span>, <span class="dt">alpha =</span> <span class="fl">0.3</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:jitteralpha"></span>
<img src="ismay_files/figure-html/jitteralpha-1.png" alt="Arrival Delays vs Departure Delays for Alaska Airlines flights from NYC in 2013 - jitter and alpha added 1" width="\textwidth" />
<p class="caption">
Figure 4.18: Arrival Delays vs Departure Delays for Alaska Airlines flights from NYC in 2013 - jitter and alpha added 1
</p>
</div>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC4.30)</strong> Why is setting the <code>alpha</code> argument value useful with scatter-plots?</p>
<ul>
<li>What further information does it give you that a regular scatter-plot cannot?</li>
</ul>
<p><strong>(LC4.31)</strong> After viewing the <a href="4-viz.html#fig:alpha">4.17</a> above, give a range of arrival times and departure times that occur most frequently?</p>
<ul>
<li>How has that region changed compared to when you observed the same plot without the <code>alpha = 0.2</code> set in <a href="4-viz.html#fig:noalpha">4.15</a>?</li>
</ul>
<hr />
<!--
**Maybe include a shading of the points by another variable example here for multivariate thinking?**
-->
</div>
<div id="summary-3" class="section level3">
<h3><span class="header-section-number">4.5.3</span> Summary</h3>
<p>Scatter-plots may be the most used plot today and they can provide an immediate way to see the trend in one variable versus another. Remember that they only make sense when plotting a continuous variable versus a continuous variable though. If you try to create a scatter-plot where either one of the two variables is not quantitative, you will get strange results. Be careful!</p>
<p>With medium to large datasets, you may need to tweak arguments in both <code>geom_jitter</code> and the <code>alpha</code> parameter in order to get a good feel for relationships in your data. This tweaking is often a fun part of data visualization since you’ll have the chance to see different relationships come about as you make subtle changes to your plots.</p>
</div>
</div>
<div id="line-graphs" class="section level2">
<h2><span class="header-section-number">4.6</span> Line-graphs</h2>
<p>The last of the 5NG is a line-graph. They are most frequently used when the horizontal axis is time. Time represents a variable that is connected together by each day following the previous day. In other words, time has a natural ordering. Line-graphs should be avoided when there is not a clear ordering to the explanatory (“x” variable).</p>
<p>We are interested in exploring the arrival delays by day throughout the year of 2013 from outgoing flights from New York City. If we plotted all of these values, we obtain the following scatter-plot:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(flights, <span class="kw">aes</span>(<span class="dt">x =</span> time_hour, <span class="dt">y =</span> arr_delay)) +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-32"></span>
<img src="ismay_files/figure-html/unnamed-chunk-32-1.png" alt="Hard to read scatterplot" width="\textwidth" />
<p class="caption">
Figure 4.19: Hard to read scatterplot
</p>
</div>
<p>We see that this plot is difficult to understand based on the sheer number of points plotted. We see some outlier points with more than 500 minutes of arrival delay, but even some jittering and transparency is not going to help us here.</p>
<p>Instead of plotting all of the values for each hour for all flights, it might make sense to plot the average value for each day in terms of arrival delays. Of course, we also need to address which average we should use: mean or median. With there being some outliers here, we have chosen to use the median arrival delay (since the mean is heavily influence by outliers).</p>
<p>You may think that this is a difficult task but the <code>group_by</code> and <code>summarize</code> functions make this a breeze. You’ll see more examples using these two functions in Chapter <a href="5-manip.html#manip">5</a>. Here we will create a new variable, which corresponds to the month and day combined, from the <code>time_hour</code> column using the <code>mutate</code> function and create a new dataframe called <code>flights_day</code>. Notice from running <code>View(flights_day)</code> that the new variable added called <code>date</code> appears on the far right of the dataset.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights_day &lt;-<span class="st"> </span><span class="kw">mutate</span>(flights, <span class="dt">date =</span> <span class="kw">as.Date</span>(time_hour))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights_summarized &lt;-<span class="st"> </span>flights_day %&gt;%<span class="st"> </span><span class="kw">group_by</span>(date) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">median_arr_delay =</span> <span class="kw">median</span>(arr_delay, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))
flights_summarized</code></pre></div>
<pre><code>## # A tibble: 365 × 2
##          date median_arr_delay
##        &lt;date&gt;            &lt;dbl&gt;
## 1  2013-01-01                3
## 2  2013-01-02                4
## 3  2013-01-03                1
## 4  2013-01-04               -8
## 5  2013-01-05               -7
## 6  2013-01-06               -1
## 7  2013-01-07              -10
## 8  2013-01-08               -7
## 9  2013-01-09               -6
## 10 2013-01-10              -11
## # ... with 355 more rows</code></pre>
<p>You will see the “pipe” operator <code>%&gt;%</code> explained in more detail in Chapter <a href="5-manip.html#manip">5</a>, but you can read it as “and then”. Here, we take the <code>flights_day</code> dataframe that we just created and then group it together by <code>date</code>. This goes through the dataframe and puts together all rows that have <code>2013-01-01</code> together, all rows that have <code>2013-01-02</code> together, …, and all rows that have <code>2013-12-31</code> together. And then it looks at the median value of <code>arr_delay</code> over each one of the days. You can get a glimpse of the first few rows of this new dataset above since we invoked the <code>head</code> function on it.</p>
<p>Note also that there are missing values in this data set so we need to exclude them from the analysis. This is why the <code>na.rm = TRUE</code> argument is invoked. Many functions require this extra specification so it’s always a good idea to run a <code>?median</code> or <code>?mean</code> before you try to run the function. Or you can always run it afterwards as well when you get strange results.</p>
<p>Now getting back to our line-graph. We want to plot the median arrival delay over all airlines on all days in 2013 from departing flights in NYC. This syntax should look similar to what we have seen before with plots involving <code>ggplot</code>. Notice that we are using the <code>flights_summarized</code> dataset here and not the <code>flights_day</code> or <code>flights</code> dataframes.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> flights_summarized, <span class="kw">aes</span>(<span class="dt">x =</span> date, <span class="dt">y =</span> median_arr_delay)) +
<span class="st">  </span><span class="kw">geom_line</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:lineflights"></span>
<img src="ismay_files/figure-html/lineflights-1.png" alt="Line-graph of median arrival delay for flights leaving NYC in 2013 versus day of the year" width="\textwidth" />
<p class="caption">
Figure 4.20: Line-graph of median arrival delay for flights leaving NYC in 2013 versus day of the year
</p>
</div>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC4.32)</strong> Why should line-graphs be avoided when there is not a clear ordering of the horizontal axis?</p>
<p><strong>(LC4.33)</strong> Why are line-graphs frequently used when time is the explanatory variable?</p>
<p><strong>(LC4.34)</strong> Why did we use the <code>flights_summarized</code> dataframe to produce the line-graph in Figure <a href="4-viz.html#fig:lineflights">4.20</a> instead of <code>flights</code> or <code>flights_day</code>?</p>
<p><strong>(LC4.35)</strong> Are the largest median arrival delays where you expected them to occur on the line-graph above in Figure <a href="4-viz.html#fig:lineflights">4.20</a>? Why or why not?</p>
<hr />
<div id="summary-4" class="section level3">
<h3><span class="header-section-number">4.6.1</span> Summary</h3>
<p>Line-graphs provide a useful tool for viewing a continuous variable that is plotted versus time. We need to be careful to not be too entrenched in using line-graphs whenever we wish though. They only make sense when the explanatory variable (the one on the explanatory variable) has a natural ordering. We can mislead our audience if that isn’t the case.</p>
</div>
</div>
<div id="brief-review-of-the-grammar-of-graphics" class="section level2">
<h2><span class="header-section-number">4.7</span> Brief Review of The Grammar of Graphics</h2>
<p>The 5NG discussion above has introduced you to all of the major pieces behind “The Grammar of Graphics”, which serves as the basis for the <code>ggplot2</code> package. This theoretical framework given by Leland Wilkinson <span class="citation">(Wilkinson <a href="#ref-wilkinson2005">2005</a>)</span> helps us identify what the pieces are that make up a statistical graphic:</p>
<blockquote>
<p>In brief, the grammar tells us that a statistical graphic is a mapping from data to aesthetic attributes (color, shape, size) of geometric objects (points, lines, bars).</p>
</blockquote>
<p>Specially, we can break a graphic into the following components:</p>
<ul>
<li><p><code>aes</code>: mappings of data to <em>aesthetics</em> we can perceive on a graphic. These include x/y position, color, size, and shape. Each aesthetic can be mapped to a variable in our data set. If not assigned, they are set to defaults.</p></li>
<li><p><code>geom</code>: (geometric objects) This refers to our type of plot: points, lines, bars, etc.</p></li>
<li><p><code>stat</code>: (statistical transformations to summarize data) This includes smoothing, binning values into a histogram, or just itself <code>&quot;identity&quot;</code>. You’ll see this when we get to regression later in Chapter <a href="9-regress.html#regress">9</a>.</p></li>
<li><p><code>facet</code>: how to break up data into subsets and display broken down plots as small multiples</p></li>
<li><p><code>scales</code> both</p>
<ul>
<li>convert <strong>data units</strong> to <strong>physical units</strong> the computer can display</li>
<li>draw a legend and/or axes, which provide an inverse mapping to make it possible to read the original data values from the graph.</li>
</ul></li>
<li><p><code>coord</code>: coordinate system for x/y values: typically cartesian.</p></li>
<li><p><code>position</code> adjustments</p></li>
</ul>
<p>There are other extra attributes that can be tweaked as well including titles for the plot and each of the axes and also over-arching themes for the plot. In general, the Grammar of Graphics allows for customizability but also keeping with a consistent framework that allows the user to easily tweak their creations as they wish or need to in order to convey a message about their data.</p>
<p>We’ll see (and have seen) that you don’t necessarily need to include all of these in your code to produce a plot but each of the components are set by default and do exist with each plot produced using <code>ggplot2</code>.</p>
<p>An excellent resource as you begin to create plots using the <code>ggplot2</code> package is a cheatsheet that RStudio has put together entitled “Data Visualization with ggplot2” available <a href="https://www.rstudio.com/wp-content/uploads/2015/12/ggplot2-cheatsheet-2.0.pdf">here</a>. This covers more than what we’ve discussed in this chapter but provides nice visual descriptions of what each function produces.</p>
<!--
***
***

<div class="review">
<p><strong><em>Review questions</em></strong></p>
</div>

**`paste0("(RQ", chap, ".", (rq <- rq + 1), ")")`**

- Have a variety of bad plots with data for the readers and have readers create better plots with `ggplot2`

- Have sample datasets to work with from problem statements
    + Identify the appropriate plot to address the questions of interest

- Why is it important for barplots to start at zero?

***
***
-->
</div>
<div id="whats-to-come-1" class="section level2">
<h2><span class="header-section-number">4.8</span> What’s to come?</h2>
<p>In Chapter <a href="5-manip.html#manip">5</a>, we’ll further explore data by grouping our data, creating summaries based on those groupings, filtering our data to match conditions, selecting specific columns of our data, and other manipulations with our data including defining new columns/variables. These data manipulation procedures will go hand-in-hand with the data visualizations you’ve produced here.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-wilkinson2005">
<p>Wilkinson, Leland. 2005. <em>The Grammar of Graphics (Statistics and Computing)</em>. Secaucus, NJ, USA: Springer-Verlag New York, Inc.</p>
</div>
<div id="ref-R-ggplot2">
<p>Wickham, Hadley, and Winston Chang. 2016. <em>Ggplot2: An Implementation of the Grammar of Graphics</em>. <a href="https://CRAN.R-project.org/package=ggplot2" class="uri">https://CRAN.R-project.org/package=ggplot2</a>.</p>
</div>
<div id="ref-usedtor2016">
<p>Ismay, Chester. 2016. <em>Getting Used to R, RStudio, and R Markdown</em>. <a href="http://ismayc.github.io/rbasics-book" class="uri">http://ismayc.github.io/rbasics-book</a>.</p>
</div>
<div id="ref-rds2016">
<p>Grolemund, Garrett, and Hadley Wickham. 2016. <em>R for Data Science</em>. <a href="http://r4ds.had.co.nz/" class="uri">http://r4ds.had.co.nz/</a>.</p>
</div>
<div id="ref-robbins2013">
<p>Robbins, Naomi. 2013. <em>Creating More Effective Graphs</em>. Chart House.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Recall that to view a dataset in spreadsheet format in RStudio, you can run the <code>View()</code> function with the dataframe as its argument.<a href="4-viz.html#fnref1">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="3-tidy.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="5-manip.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ismayc/moderndiver-source/edit/master/04-visualizing_data.Rmd",
"text": null
},
"download": ["ismay.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
