<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>ModernDive</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="Combining statistical and computational thinking to make sense of data. Getting away from the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown">
  <meta name="generator" content="bookdown 0.3 and GitBook 2.6.7">

  <meta property="og:title" content="ModernDive" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Combining statistical and computational thinking to make sense of data. Getting away from the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown" />
  <meta name="github-repo" content="ismayc/moderndiver-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="ModernDive" />
  
  <meta name="twitter:description" content="Combining statistical and computational thinking to make sense of data. Getting away from the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown" />
  

<meta name="author" content="Chester Ismay and Albert Y. Kim">


<meta name="date" content="2017-01-06">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="7-hypo.html">
<link rel="next" href="9-regression-via-broom.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-0.8/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.4/dygraphs.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89938436-1', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#colophon"><i class="fa fa-check"></i>Colophon</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-intro.html"><a href="2-intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="2-intro.html"><a href="2-intro.html#preamble"><i class="fa fa-check"></i><b>2.1</b> Preamble</a></li>
<li class="chapter" data-level="2.2" data-path="2-intro.html"><a href="2-intro.html#two-driving-data-sources"><i class="fa fa-check"></i><b>2.2</b> Two driving data sources</a></li>
<li class="chapter" data-level="2.3" data-path="2-intro.html"><a href="2-intro.html#datascience-pipeline"><i class="fa fa-check"></i><b>2.3</b> Data/science pipeline</a></li>
<li class="chapter" data-level="2.4" data-path="2-intro.html"><a href="2-intro.html#reproducibility"><i class="fa fa-check"></i><b>2.4</b> Reproducibility</a></li>
<li class="chapter" data-level="2.5" data-path="2-intro.html"><a href="2-intro.html#who-is-this-book-for"><i class="fa fa-check"></i><b>2.5</b> Who is this book for?</a></li>
</ul></li>
<li class="part"><span><b>I Data Exploration</b></span></li>
<li class="chapter" data-level="3" data-path="3-tidy.html"><a href="3-tidy.html"><i class="fa fa-check"></i><b>3</b> Tidy Data</a><ul>
<li class="chapter" data-level="3.1" data-path="3-tidy.html"><a href="3-tidy.html#what-is-tidy-data"><i class="fa fa-check"></i><b>3.1</b> What is tidy data?</a></li>
<li class="chapter" data-level="3.2" data-path="3-tidy.html"><a href="3-tidy.html#the-nycflights13-datasets"><i class="fa fa-check"></i><b>3.2</b> The <code>nycflights13</code> datasets</a></li>
<li class="chapter" data-level="3.3" data-path="3-tidy.html"><a href="3-tidy.html#how-is-flights-tidy"><i class="fa fa-check"></i><b>3.3</b> How is <code>flights</code> tidy?</a></li>
<li class="chapter" data-level="3.4" data-path="3-tidy.html"><a href="3-tidy.html#normal-forms-of-data"><i class="fa fa-check"></i><b>3.4</b> Normal forms of data</a></li>
<li class="chapter" data-level="3.5" data-path="3-tidy.html"><a href="3-tidy.html#whats-to-come"><i class="fa fa-check"></i><b>3.5</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html"><i class="fa fa-check"></i><b>4</b> Data Visualization via <code id="viz">ggplot2</code></a><ul>
<li class="chapter" data-level="4.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#five-named-graphs---the-5ng"><i class="fa fa-check"></i><b>4.1</b> Five Named Graphs - The 5NG</a></li>
<li class="chapter" data-level="4.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#histograms"><i class="fa fa-check"></i><b>4.2</b> Histograms</a><ul>
<li class="chapter" data-level="4.2.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#contsum"><i class="fa fa-check"></i><b>4.2.1</b> Continuous data summaries</a></li>
<li class="chapter" data-level="4.2.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary"><i class="fa fa-check"></i><b>4.2.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#boxplots"><i class="fa fa-check"></i><b>4.3</b> Boxplots</a><ul>
<li class="chapter" data-level="4.3.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#faceting"><i class="fa fa-check"></i><b>4.3.1</b> Faceting</a></li>
<li class="chapter" data-level="4.3.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary-1"><i class="fa fa-check"></i><b>4.3.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#barplots"><i class="fa fa-check"></i><b>4.4</b> Barplots</a><ul>
<li class="chapter" data-level="4.4.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>4.4.1</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="4.4.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#using-barplots-to-compare-two-variables"><i class="fa fa-check"></i><b>4.4.2</b> Using barplots to compare two variables</a></li>
<li class="chapter" data-level="4.4.3" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary-2"><i class="fa fa-check"></i><b>4.4.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#scatter-plots"><i class="fa fa-check"></i><b>4.5</b> Scatter-plots</a><ul>
<li class="chapter" data-level="4.5.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#jittering"><i class="fa fa-check"></i><b>4.5.1</b> Jittering</a></li>
<li class="chapter" data-level="4.5.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#setting-transparency"><i class="fa fa-check"></i><b>4.5.2</b> Setting transparency</a></li>
<li class="chapter" data-level="4.5.3" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary-3"><i class="fa fa-check"></i><b>4.5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#line-graphs"><i class="fa fa-check"></i><b>4.6</b> Line-graphs</a><ul>
<li class="chapter" data-level="4.6.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary-4"><i class="fa fa-check"></i><b>4.6.1</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#brief-review-of-the-grammar-of-graphics"><i class="fa fa-check"></i><b>4.7</b> Brief Review of The Grammar of Graphics</a></li>
<li class="chapter" data-level="4.8" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#script-of-r-code"><i class="fa fa-check"></i><b>4.8</b> Script of R code</a></li>
<li class="chapter" data-level="4.9" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#whats-to-come-1"><i class="fa fa-check"></i><b>4.9</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html"><i class="fa fa-check"></i><b>5</b> Data Manipulation via <code id="manip">dplyr</code></a><ul>
<li class="chapter" data-level="5.1" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#five-main-verbs---the-fmv"><i class="fa fa-check"></i><b>5.1</b> Five Main Verbs - The FMV</a><ul>
<li class="chapter" data-level="5.1.1" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#select-variables-using-select"><i class="fa fa-check"></i><b>5.1.1</b> Select variables using <code id="select">select</code></a></li>
<li class="chapter" data-level="5.1.2" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#filter-observations-using-filter"><i class="fa fa-check"></i><b>5.1.2</b> Filter observations using <code id="filter">filter</code></a></li>
<li class="chapter" data-level="5.1.3" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#summarize-variables-using-summarize"><i class="fa fa-check"></i><b>5.1.3</b> Summarize variables using <code>summarize</code></a></li>
<li class="chapter" data-level="5.1.4" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#create-new-variableschange-old-variables-using-mutate"><i class="fa fa-check"></i><b>5.1.4</b> Create new variables/change old variables using <code>mutate</code></a></li>
<li class="chapter" data-level="5.1.5" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#reorder-the-data-frame-using-arrange"><i class="fa fa-check"></i><b>5.1.5</b> Reorder the data frame using <code id="arrange">arrange</code></a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#the-pipe"><i class="fa fa-check"></i><b>5.2</b> The pipe <code>%&gt;%</code></a></li>
<li class="chapter" data-level="5.3" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#joiningmerging-data-frames"><i class="fa fa-check"></i><b>5.3</b> Joining/merging data frames</a></li>
<li class="chapter" data-level="5.4" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#script-of-r-code-1"><i class="fa fa-check"></i><b>5.4</b> Script of R code</a></li>
<li class="chapter" data-level="5.5" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#whats-to-come-2"><i class="fa fa-check"></i><b>5.5</b> What’s to come?</a></li>
</ul></li>
<li class="part"><span><b>II Inference</b></span></li>
<li class="chapter" data-level="6" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html"><i class="fa fa-check"></i><b>6</b> Simulating Randomness via <code id="sim">mosaic</code></a><ul>
<li class="chapter" data-level="6.1" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#needed-packages"><i class="fa fa-check"></i><b>6.1</b> Needed packages</a></li>
<li class="chapter" data-level="6.2" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#random-sampling"><i class="fa fa-check"></i><b>6.2</b> Random sampling</a><ul>
<li class="chapter" data-level="6.2.1" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#tasting-soup"><i class="fa fa-check"></i><b>6.2.1</b> Tasting soup</a></li>
<li class="chapter" data-level="6.2.2" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#common-terms"><i class="fa fa-check"></i><b>6.2.2</b> Common terms</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#visualizing-sampling"><i class="fa fa-check"></i><b>6.3</b> Visualizing sampling</a><ul>
<li class="chapter" data-level="6.3.1" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#sampling-distribution"><i class="fa fa-check"></i><b>6.3.1</b> Sampling distribution</a></li>
<li class="chapter" data-level="6.3.2" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#repeated-sampling-via-do"><i class="fa fa-check"></i><b>6.3.2</b> Repeated sampling via <code>do</code></a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#simulation"><i class="fa fa-check"></i><b>6.4</b> Simulation</a></li>
<li class="chapter" data-level="6.5" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#review-of-mosaic-simulation-functions"><i class="fa fa-check"></i><b>6.5</b> Review of <code>mosaic</code> simulation functions</a></li>
<li class="chapter" data-level="6.6" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#script-of-r-code-2"><i class="fa fa-check"></i><b>6.6</b> Script of R code</a></li>
<li class="chapter" data-level="6.7" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#whats-to-come-3"><i class="fa fa-check"></i><b>6.7</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-hypo.html"><a href="7-hypo.html"><i class="fa fa-check"></i><b>7</b> Hypothesis Testing</a><ul>
<li class="chapter" data-level="7.1" data-path="7-hypo.html"><a href="7-hypo.html#needed-packages-1"><i class="fa fa-check"></i><b>7.1</b> Needed packages</a></li>
<li class="chapter" data-level="7.2" data-path="7-hypo.html"><a href="7-hypo.html#when-inference-is-not-needed"><i class="fa fa-check"></i><b>7.2</b> When Inference Is Not Needed</a></li>
<li class="chapter" data-level="7.3" data-path="7-hypo.html"><a href="7-hypo.html#basics-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.3</b> Basics of Hypothesis Testing</a></li>
<li class="chapter" data-level="7.4" data-path="7-hypo.html"><a href="7-hypo.html#trial"><i class="fa fa-check"></i><b>7.4</b> Criminal trial analogy</a><ul>
<li class="chapter" data-level="7.4.1" data-path="7-hypo.html"><a href="7-hypo.html#two-possible-conclusions"><i class="fa fa-check"></i><b>7.4.1</b> Two possible conclusions</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="7-hypo.html"><a href="7-hypo.html#types-of-errors-in-hypothesis-testing"><i class="fa fa-check"></i><b>7.5</b> Types of Errors in Hypothesis Testing</a><ul>
<li class="chapter" data-level="7.5.1" data-path="7-hypo.html"><a href="7-hypo.html#logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.5.1</b> Logic of Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="7-hypo.html"><a href="7-hypo.html#statistical-significance"><i class="fa fa-check"></i><b>7.6</b> Statistical Significance</a></li>
<li class="chapter" data-level="7.7" data-path="7-hypo.html"><a href="7-hypo.html#example-revisiting-the-lady-tasting-tea"><i class="fa fa-check"></i><b>7.7</b> EXAMPLE: Revisiting the Lady Tasting Tea</a><ul>
<li class="chapter" data-level="7.7.1" data-path="7-hypo.html"><a href="7-hypo.html#data"><i class="fa fa-check"></i><b>7.7.1</b> Data</a></li>
<li class="chapter" data-level="7.7.2" data-path="7-hypo.html"><a href="7-hypo.html#test-statistic-delta"><i class="fa fa-check"></i><b>7.7.2</b> Test Statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="7.7.3" data-path="7-hypo.html"><a href="7-hypo.html#observed-effect-delta"><i class="fa fa-check"></i><b>7.7.3</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="7.7.4" data-path="7-hypo.html"><a href="7-hypo.html#model-of-h_0"><i class="fa fa-check"></i><b>7.7.4</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.7.5" data-path="7-hypo.html"><a href="7-hypo.html#simulated-data"><i class="fa fa-check"></i><b>7.7.5</b> Simulated Data</a></li>
<li class="chapter" data-level="7.7.6" data-path="7-hypo.html"><a href="7-hypo.html#distribution-of-delta-under-h_0"><i class="fa fa-check"></i><b>7.7.6</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.7.7" data-path="7-hypo.html"><a href="7-hypo.html#the-p-value"><i class="fa fa-check"></i><b>7.7.7</b> The p-value</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="7-hypo.html"><a href="7-hypo.html#example-comparing-two-means"><i class="fa fa-check"></i><b>7.8</b> EXAMPLE: Comparing two means</a><ul>
<li class="chapter" data-level="7.8.1" data-path="7-hypo.html"><a href="7-hypo.html#randomizationpermutation"><i class="fa fa-check"></i><b>7.8.1</b> Randomization/Permutation</a></li>
<li class="chapter" data-level="7.8.2" data-path="7-hypo.html"><a href="7-hypo.html#comparing-action-and-romance-movies"><i class="fa fa-check"></i><b>7.8.2</b> Comparing Action and Romance Movies</a></li>
<li class="chapter" data-level="7.8.3" data-path="7-hypo.html"><a href="7-hypo.html#sampling-rightarrow-randomization"><i class="fa fa-check"></i><b>7.8.3</b> Sampling <span class="math inline">\(\rightarrow\)</span> Randomization</a></li>
<li class="chapter" data-level="7.8.4" data-path="7-hypo.html"><a href="7-hypo.html#data-1"><i class="fa fa-check"></i><b>7.8.4</b> Data</a></li>
<li class="chapter" data-level="7.8.5" data-path="7-hypo.html"><a href="7-hypo.html#model-of-h_0-1"><i class="fa fa-check"></i><b>7.8.5</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.8.6" data-path="7-hypo.html"><a href="7-hypo.html#test-statistic-delta-1"><i class="fa fa-check"></i><b>7.8.6</b> Test Statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="7.8.7" data-path="7-hypo.html"><a href="7-hypo.html#observed-effect-delta-1"><i class="fa fa-check"></i><b>7.8.7</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="7.8.8" data-path="7-hypo.html"><a href="7-hypo.html#simulated-data-1"><i class="fa fa-check"></i><b>7.8.8</b> Simulated Data</a></li>
<li class="chapter" data-level="7.8.9" data-path="7-hypo.html"><a href="7-hypo.html#distribution-of-delta-under-h_0-1"><i class="fa fa-check"></i><b>7.8.9</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.8.10" data-path="7-hypo.html"><a href="7-hypo.html#the-p-value-1"><i class="fa fa-check"></i><b>7.8.10</b> The p-value</a></li>
<li class="chapter" data-level="7.8.11" data-path="7-hypo.html"><a href="7-hypo.html#summary-5"><i class="fa fa-check"></i><b>7.8.11</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="7-hypo.html"><a href="7-hypo.html#theory-hypo"><i class="fa fa-check"></i><b>7.9</b> Building theory-based methods using computation</a><ul>
<li class="chapter" data-level="7.9.1" data-path="7-hypo.html"><a href="7-hypo.html#example-t-test-for-two-independent-samples"><i class="fa fa-check"></i><b>7.9.1</b> EXAMPLE: <span class="math inline">\(t\)</span>-test for two independent samples</a></li>
<li class="chapter" data-level="7.9.2" data-path="7-hypo.html"><a href="7-hypo.html#conditions-for-t-test"><i class="fa fa-check"></i><b>7.9.2</b> Conditions for t-test</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="7-hypo.html"><a href="7-hypo.html#whats-to-come-4"><i class="fa fa-check"></i><b>7.10</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-ci.html"><a href="8-ci.html"><i class="fa fa-check"></i><b>8</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="8.1" data-path="8-ci.html"><a href="8-ci.html#needed-packages-2"><i class="fa fa-check"></i><b>8.1</b> Needed packages</a></li>
<li class="chapter" data-level="8.2" data-path="8-ci.html"><a href="8-ci.html#bootstrapping"><i class="fa fa-check"></i><b>8.2</b> Bootstrapping</a><ul>
<li class="chapter" data-level="8.2.1" data-path="8-ci.html"><a href="8-ci.html#review-of-bootstrapping"><i class="fa fa-check"></i><b>8.2.1</b> Review of Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="8-ci.html"><a href="8-ci.html#relation-to-hypothesis-testing"><i class="fa fa-check"></i><b>8.3</b> Relation to hypothesis testing</a></li>
<li class="chapter" data-level="8.4" data-path="8-ci.html"><a href="8-ci.html#effect-size"><i class="fa fa-check"></i><b>8.4</b> Effect size</a></li>
<li class="chapter" data-level="8.5" data-path="8-ci.html"><a href="8-ci.html#script-of-r-code-3"><i class="fa fa-check"></i><b>8.5</b> Script of R code</a></li>
<li class="chapter" data-level="8.6" data-path="8-ci.html"><a href="8-ci.html#whats-to-come-5"><i class="fa fa-check"></i><b>8.6</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html"><i class="fa fa-check"></i><b>9</b> Regression via <code id="regress">broom</code></a><ul>
<li class="chapter" data-level="9.1" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#whats-to-come-6"><i class="fa fa-check"></i><b>9.1</b> What’s to come?</a></li>
</ul></li>
<li class="part"><span><b>III Conclusion</b></span></li>
<li class="chapter" data-level="10" data-path="10-effective-data-storytelling.html"><a href="10-effective-data-storytelling.html"><i class="fa fa-check"></i><b>10</b> Effective Data Storytelling</a><ul>
<li class="chapter" data-level="10.1" data-path="10-effective-data-storytelling.html"><a href="10-effective-data-storytelling.html#conclusion"><i class="fa fa-check"></i><b>10.1</b> Concluding Remarks</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="A-appendixA.html"><a href="A-appendixA.html"><i class="fa fa-check"></i><b>A</b> Statistical Background</a><ul>
<li class="chapter" data-level="A.1" data-path="A-appendixA.html"><a href="A-appendixA.html#basic-statistical-terms"><i class="fa fa-check"></i><b>A.1</b> Basic statistical terms</a><ul>
<li class="chapter" data-level="A.1.1" data-path="A-appendixA.html"><a href="A-appendixA.html#mean"><i class="fa fa-check"></i><b>A.1.1</b> Mean</a></li>
<li class="chapter" data-level="A.1.2" data-path="A-appendixA.html"><a href="A-appendixA.html#median"><i class="fa fa-check"></i><b>A.1.2</b> Median</a></li>
<li class="chapter" data-level="A.1.3" data-path="A-appendixA.html"><a href="A-appendixA.html#standard-deviation"><i class="fa fa-check"></i><b>A.1.3</b> Standard deviation</a></li>
<li class="chapter" data-level="A.1.4" data-path="A-appendixA.html"><a href="A-appendixA.html#five-number-summary"><i class="fa fa-check"></i><b>A.1.4</b> Five-number summary</a></li>
<li class="chapter" data-level="A.1.5" data-path="A-appendixA.html"><a href="A-appendixA.html#distribution"><i class="fa fa-check"></i><b>A.1.5</b> Distribution</a></li>
<li class="chapter" data-level="A.1.6" data-path="A-appendixA.html"><a href="A-appendixA.html#outliers"><i class="fa fa-check"></i><b>A.1.6</b> Outliers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="B-appendixB.html"><a href="B-appendixB.html"><i class="fa fa-check"></i><b>B</b> Inference Examples</a></li>
<li class="chapter" data-level="C" data-path="C-appendixC.html"><a href="C-appendixC.html"><i class="fa fa-check"></i><b>C</b> Reach for the Starts</a><ul>
<li class="chapter" data-level="C.1" data-path="C-appendixC.html"><a href="C-appendixC.html#sorted-barplots"><i class="fa fa-check"></i><b>C.1</b> Sorted barplots</a></li>
<li class="chapter" data-level="C.2" data-path="C-appendixC.html"><a href="C-appendixC.html#interactive-graphics"><i class="fa fa-check"></i><b>C.2</b> Interactive graphics</a><ul>
<li class="chapter" data-level="C.2.1" data-path="C-appendixC.html"><a href="C-appendixC.html#interactive-line-graphs"><i class="fa fa-check"></i><b>C.2.1</b> Interactive line-graphs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ModernDive</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ci" class="section level1">
<h1><span class="header-section-number">8</span> Confidence Intervals</h1>
<div id="needed-packages-2" class="section level2">
<h2><span class="header-section-number">8.1</span> Needed packages</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(okcupiddata)
<span class="kw">library</span>(mosaic)
<span class="kw">library</span>(knitr)
<span class="kw">library</span>(nycflights13)</code></pre></div>
<p><strong>Definition: Confidence Interval</strong></p>
<p>A <em>confidence interval</em> gives a range of plausible values for a parameter. It depends on a specified <em>confidence level</em> with higher confidence levels corresponding to wider confidence intervals and lower confidence levels corresponding to narrower confidence intervals. Common confidence levels include 90%, 95%, and 99%.</p>
<!--
Standard error

Interpretation: was constructed using the sample data by a procedure that is 95% reliable. 
Lift/steal the OI diagram of horizontal lines, with those not capturing pop parameter in red
Sample heights from profiles in okcupiddata (Section 3.c) of outline)
There is only one CI 
  - Build a diagram
Fishing with a spear/net Analogy: Confidence intervals
Confidence interval MEGA LC: s/sqrt(n) form of SE
  - Population distribution very right skewed
  - Population distribution symmetric
  - Sample size small from very left skewed population
-->
</div>
<div id="bootstrapping" class="section level2">
<h2><span class="header-section-number">8.2</span> Bootstrapping</h2>
<p>Just as we did in the previous section when making hypotheses about a population proportion with which we would like to test which one is more plausible, we can also use simulation to infer conclusions about a population quantitative statistic such as the mean. In this case, we will focus on constructing confidence intervals to produce plausible values for a population mean. (We can do a similar analysis for a population median or other summary measure as well.)</p>
<p>Traditionally, the way to construct confidence intervals for a mean is to assume a normal distribution for the population or to invoke the Central Limit Theorem and get, what often appears to be magic, results. These methods are often not intuitive, especially for those that lack a strong mathematical background. They also come with their fair share of assumptions and often turn Statistics, a field that is full of tons of useful applications to many different fields and disciplines, into a robotic procedural-based topic. It doesn’t have to be that way!</p>
<p>In this section, we will introduce the concept of <strong>bootstrapping</strong>. It will be a useful tool that will allow us to estimate the variability of our statistic from sample to sample. One neat feature of bootstrapping is that it enables us to approximate the sampling distribution and estimate the distribution’s standard deviation using ONLY the information in the one selected (original) sample.</p>
<p>It sounds just as plagued with the magical type qualities of traditional theory-based inference on initial glance but we will see that it provides an intuitive and useful way to make inferences, especially when the samples are of medium to large size.</p>
<!--We will begin by investigating an example on the selling prices of used Ford Mustang cars taken from the textbook {\it Statistics:  UnLOCKing the Power of Data} by Lock, Lock, Lock, Lock, and Lock.  (That isn't me hitting Copy+Paste too many times.  Patti and Robin Lock both work in the Mathematics Department at St. Lawrence University and they have three children that are statisticians.  They are often referred to as the Lock5.)
-->
<p>To introduce the concept of bootstrapping, we now introduce the <code>movies</code> data set in the <code>ggplot2movies</code> data frame. We will load this data frame into R in much the same way as we loaded <code>flights</code> and <code>weather</code> from the <code>nycflights13</code> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2movies)
<span class="kw">data</span>(movies, <span class="dt">package =</span> <span class="st">&quot;ggplot2movies&quot;</span>)</code></pre></div>
<p>Let’s also glance at this data frame using the <code>View</code> function and look at the help documentation for <code>movies</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">View</span>(movies)
?movies</code></pre></div>
<p>We will explore many other features of this data set in the chapters to come, but here we will be focusing on the <code>rating</code> variable corresponding to the average IMDB user rating.</p>
<p>You may notice that this data set is quite large: 58,788 movies have data collected about them here. This will correspond to our population of ALL movies. Remember from Chapter <a href="#infer-basics"><strong>??</strong></a> that our population is rarely known. We use this data set as our population here to show you the power of bootstrapping in estimating population parameters. We’ll see how <strong>confidence intervals</strong> built using the bootstrap distribution do at including our population parameter of interest. Here we can actually calculate these values since our population is known, but remember that in general this isn’t the case.</p>
<p>Let’s take a look at what the distribution of our population <code>ratings</code> looks like. We’ll see that we will use the distribution of our sample(s) as an estimate of this population histogram.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">movies %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> rating)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-121"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-121-1.png" alt="Population ratings histogram" width="\textwidth" />
<p class="caption">
Figure 8.1: Population ratings histogram
</p>
</div>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC8.1)</strong> Why was a histogram chosen as the plot to make for the <code>rating</code> variable above?</p>
<p><strong>(LC8.2)</strong> Why does the shape of the <code>rating</code> histogram tell us about how IMDB users rate movies? What stands out about the plot?</p>
<hr />
<p>It’s important to think about what our goal is here. We would like to produce a confidence interval for the population mean <code>rating</code>. We will have to pretend for a moment that we don’t have all 58,788 movies. Let’s say that we only have a random sample of 50 movies from this data set instead. In order to get a random sample, we can use the <code>sample_n</code> function from <code>dplyr</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">2016</span>)
movies_sample &lt;-<span class="st"> </span>movies %&gt;%
<span class="st">  </span><span class="kw">sample_n</span>(<span class="dv">50</span>)</code></pre></div>
<p>The <code>sample_n</code> function has filtered the data frame <code>movies</code> “at random” to choose only 50 rows from the larger <code>movies</code> data frame. We store information on these 50 movies in the <code>movies_sample</code> data frame.</p>
<p>Let’s now explore what the <code>rating</code> variable looks like for these 50 movies:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">movies_sample %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> rating)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-123"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-123-1.png" alt="Sample ratings histogram" width="\textwidth" />
<p class="caption">
Figure 8.2: Sample ratings histogram
</p>
</div>
<p>Remember that we can think of this histogram as an estimate of our population distribution histogram that we saw above. We are interested in the population mean rating and trying to find a range of plausible values for that value. A good start in guessing the population mean is to use the mean of our sample <code>rating</code> from the <code>movies_sample</code> data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(movies_sample_mean &lt;-<span class="st"> </span>movies_sample %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(rating)))</code></pre></div>
<pre><code>## # A tibble: 1 × 1
##    mean
##   &lt;dbl&gt;
## 1 6.034</code></pre>
<p>Note the use of the <code>( )</code> at the beginning and the end of this creation of the <code>movies_sample_mean</code> object. If you’d like to print out your newly created object, you can enclose it in the parentheses as we have here.</p>
<p>This value of 6.034 is just one guess at the population mean. The idea behind <em>bootstrapping</em> is to sample <strong>with replacement</strong> from the original sample to create new <strong>resamples</strong> of the same size as our original sample.</p>
<p>Returning to our example, let’s investigate what one such resample of the <code>movies_sample</code> data set accomplishes. We can create one resample/bootstrap sample by using the <code>resample</code> function in the <code>mosaic</code> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(mosaic)
<span class="kw">library</span>(tibble)
boot1 &lt;-<span class="st"> </span><span class="kw">resample</span>(movies_sample, <span class="dt">orig.ids =</span> <span class="ot">TRUE</span>) %&gt;%
<span class="st">  </span><span class="kw">select</span>(orig.id, <span class="kw">everything</span>()) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(orig.id)</code></pre></div>
<p>Take a look at this resample/bootstrap:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">View</span>(boot1)</code></pre></div>
<p>The important thing to note here is the original row numbers from the <code>movies_sample</code> data frame in the far left column called <code>orig.ids</code>. Since we are sampling with replacement, there is a strong likelihood that some of the 50 observational units are going to be selected again.</p>
<p>You may be asking yourself what does this mean and how to this lead us to creating a distribution for the sample mean. Recall that the original sample mean of our data was calculated using the <code>summarize</code> function above.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC8.3)</strong> What happens if we change the seed to our pseudo-random generation? Try it above when we used <code>sample_n</code> to describe the resulting <code>movies_sample</code>.</p>
<p><strong>(LC8.4)</strong> Why is sampling at random important from the <code>movies</code> data frame? Why don’t we just pick <code>Action</code> movies and do bootstrapping with this <code>Action</code> movies subset?</p>
<p><strong>(LC8.5)</strong> What was the purpose of assuming we didn’t have access to the full <code>movies</code> data set here?</p>
<hr />
<p>Before we had a calculated mean in our original sample of 6.034. Let’s calculate the mean of <code>ratings</code> in our bootstrapped sample:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(movies_boot1_mean &lt;-<span class="st"> </span>boot1 %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(rating)))</code></pre></div>
<pre><code>## # A tibble: 1 × 1
##    mean
##   &lt;dbl&gt;
## 1 6.144</code></pre>
<p>More than likely the calculated bootstrap sample mean is different than the original sample mean. This is what I meant earlier when I said that the sample means have some variability. What we are trying to do is replicate many different samples being taken from a larger population. Our best guess at what the population looks like is multiple copies of the sample we collected. We then can sample from that larger “created” population by generating bootstrap samples.</p>
<p>Similar to what we did in the previous section, we can repeat this process using the <code>do</code> function followed by an asterisk. Let’s look at 10 different bootstrap means for <code>ratings</code> from <code>movies_sample</code>. Note the use of the <code>resample</code> function here.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">do</span>(<span class="dv">10</span>) *<span class="st"> </span><span class="kw">summarize</span>(<span class="kw">resample</span>(movies_sample), <span class="dt">mean =</span> <span class="kw">mean</span>(rating))</code></pre></div>
<pre><code>##     mean
## 1  6.020
## 2  6.668
## 3  5.996
## 4  6.056
## 5  6.168
## 6  6.360
## 7  5.702
## 8  6.218
## 9  6.252
## 10 5.904</code></pre>
<p>You should see some variability begin to tease its way out here. Many of the simulated means will be close to our original sample mean but many will stray pretty far away. This occurs because outliers may have been selected a couple of times in the resampling or small values were selected more than larger. There are myriad reasons why this might be the case.</p>
<p>So what’s the next step now? Just as we repeated the repetitions thousands of times with the “Lady Tasting Tea” example, we can do a similar thing here.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">trials &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span><span class="kw">summarize</span>(<span class="kw">resample</span>(movies_sample), 
                                <span class="dt">mean =</span> <span class="kw">mean</span>(rating))
trials %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-129"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-129-1.png" alt="Bootstrapped means histogram" width="\textwidth" />
<p class="caption">
Figure 8.3: Bootstrapped means histogram
</p>
</div>
<p>The shape of this resulting distribution may look familiar to you. It resembles the well-known normal (bell-shaped) curve. We will see in Chapters <a href="7-hypo.html#hypo">7</a> and <a href="8-ci.html#ci">8</a> when we might expect a normal curve to come through as we have here and when we shouldn’t. There will be specific assumptions that need to be checked and we will see that the normal distribution doesn’t always approximate this bootstrapped distribution well. In those case, we should NOT rely on traditional methods.</p>
<p>At this point, we can easily calculate a confidence interval. In fact, we have a couple different options. We will first use the percentiles of the distribution we just created to isolate the middle 95% of values. This will correspond to our 95% confidence interval for the population mean <code>rating</code>, denoted by <span class="math inline">\(\mu\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(ciq_mean_rating &lt;-<span class="st"> </span><span class="kw">confint</span>(trials, <span class="dt">level =</span> <span class="fl">0.95</span>, <span class="dt">method =</span> <span class="st">&quot;quantile&quot;</span>))</code></pre></div>
<pre><code>##   name   lower upper level     method estimate
## 1 mean 5.50795  6.54  0.95 percentile    6.034</code></pre>
<p>It’s always important at this point to interpret the results of this confidence interval calculation. In this context, we can say something like the following:</p>
<blockquote>
<p>Based on the sample data and bootstrapping techniques, we can be 95% confident that the true mean rating of ALL IMDB ratings is between 5.50795 and 6.54.</p>
</blockquote>
<p>This statement may seem a little confusing to you. Remember that we are pretending like we don’t know what the mean IMDB rating for ALL movies is. Our population here is all of the movies listed in the <code>movies</code> data frame from <code>ggplot2movies</code>. So does our bootstrapped confidence interval here contain the actual mean value?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarize</span>(movies, <span class="dt">mean =</span> <span class="kw">mean</span>(rating))</code></pre></div>
<pre><code>## # A tibble: 1 × 1
##      mean
##     &lt;dbl&gt;
## 1 5.93285</code></pre>
<p>We see here that the population mean does fall in our range of plausible values generated from the bootstrapped samples.</p>
<p>We can also get an idea of how the theory-based inference techniques would have approximated this confidence interval by using the formula <span class="math display">\[\bar{x} \pm (2 * SE),\]</span> where <span class="math inline">\(\bar{x}\)</span> is our original sample mean and <span class="math inline">\(SE\)</span> stands for <strong>standard error</strong> and corresponds to the standard deviation of the bootstrap distribution. The value of 2 here corresponds to it being a 95% confidence interval. This formula assumes that the bootstrap distribution is symmetric. This is often the case with bootstrap distributions, especially those in which the original distribution of the sample is not highly skewed.</p>
<p>To compute this type of confidence interval, we only need to make a slight modification to the <code>confint</code> function seen above. (The expression after the <span class="math inline">\(\pm\)</span> sign is known as the <strong>margin of error</strong>.)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(cise_mean_rating &lt;-<span class="st"> </span><span class="kw">confint</span>(trials, <span class="dt">level =</span> <span class="fl">0.95</span>, <span class="dt">method =</span> <span class="st">&quot;stderr&quot;</span>))</code></pre></div>
<pre><code>##   name    lower    upper level method estimate margin.of.error
## 1 mean 5.516196 6.551379  0.95 stderr    6.034       0.5175914</code></pre>
<blockquote>
<p>Based on the sample data and bootstrapping techniques, we can be 95% confident that the true mean rating of ALL IMDB ratings is between 5.5161962 and 6.551379.</p>
</blockquote>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC8.6)</strong> Reproduce the bootstrapping above using a sample of size 50 instead of 25. What changes do you see?</p>
<p><strong>(LC8.7)</strong> Reproduce the bootstrapping above using a sample of size 5 instead of 25. What changes do you see?</p>
<p><strong>(LC8.8)</strong> How does the sample size affect the analysis?</p>
<p><strong>(LC8.9)</strong> Why must bootstrap samples be the same size as the original sample?</p>
<hr />
<div id="review-of-bootstrapping" class="section level3">
<h3><span class="header-section-number">8.2.1</span> Review of Bootstrapping</h3>
<p>We can summarize the process to generate a bootstrap distribution here in a series of steps that clearly identify the terminology we will use <span class="citation">(R. Lock et al. <a href="#ref-lock2012">2012</a>)</span>.</p>
<ul>
<li>Generate <code>bootstrap samples</code> by sampling with replacement from the original sample, using the same sample size.</li>
<li>Compute the statistic of interest, called a <code>bootstrap statistic</code>, for each of the bootstrap samples.</li>
<li>Collect the statistics for many bootstrap samples to create a <code>bootstrap distribution</code>.</li>
</ul>
<p>Visually, we can represent this process in the following diagram.</p>
<div class="figure" style="text-align: center"><span id="fig:bootstrapimg"></span>
<img src="images/bootstrap.png" alt="Bootstrapping diagram from Lock5 textbook" width="\textwidth" />
<p class="caption">
Figure 8.4: Bootstrapping diagram from Lock5 textbook
</p>
</div>
</div>
</div>
<div id="relation-to-hypothesis-testing" class="section level2">
<h2><span class="header-section-number">8.3</span> Relation to hypothesis testing</h2>
<p>Recall that we found a statistically significant difference in the sample mean of romance movie ratings compared to the sample mean of action movie ratings. We concluded Chapter <a href="7-hypo.html#hypo">7</a> by attempted to understand just how much greater we could expect the <em>population</em> mean romance movie rating to be as compared to the <em>population</em> mean action movie rating. In order to do so, we will calculate a confidence interval for the difference <span class="math inline">\(\mu_r - \mu_a\)</span>. We’ll then go back to our population parameter values and see if our confidence interval contains our parameter value.</p>
<p>We could use bootstrapping in a way similar to that done in the Chapter <a href="#infer-basics"><strong>??</strong></a>, except now on a difference in sample means, to create a distribution and then use the <code>confint</code> function with the option of <code>quantile</code> to determine a confidence interval for the plausible values of the difference in population means. This is an excellent programming activity and the reader is urged to try to do so.</p>
<p>Recall what the randomization/null distribution looked like for our simulated shuffled sample means:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(dplyr)
rand_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffmean)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-133"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-133-1.png" alt="Simulated shuffled sample means histogram" width="\textwidth" />
<p class="caption">
Figure 8.5: Simulated shuffled sample means histogram
</p>
</div>
<p>With this null distribution being quite symmetric, the standard error method introduced in Chapter <a href="#infer-basics"><strong>??</strong></a> likely provides a good estimate of a range of plausible values for <span class="math inline">\(\mu_r - \mu_a\)</span>. Another nice option here is that we can use the standard deviation of the null/randomization distribution we just found with our hypothesis test.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(std_err &lt;-<span class="st"> </span>rand_distn %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">se =</span> <span class="kw">sd</span>(diffmean)))</code></pre></div>
<pre><code>## # A tibble: 1 × 1
##           se
##        &lt;dbl&gt;
## 1 0.03182225</code></pre>
<p>Remembering that we can use the general formula of <span class="math inline">\(statistic \pm (2 * SE)\)</span> we get the following result for plausible values of the difference in population means at the 95% level.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(lower &lt;-<span class="st"> </span>obs_diff -<span class="st"> </span>(<span class="dv">2</span> *<span class="st"> </span>std_err))</code></pre></div>
<pre><code>##          se
## 1 0.7657673</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(upper &lt;-<span class="st"> </span>obs_diff +<span class="st"> </span>(<span class="dv">2</span> *<span class="st"> </span>std_err))</code></pre></div>
<pre><code>##          se
## 1 0.8930563</code></pre>
<p>We can, therefore, say that we are 95% confident that the population mean rating for romance movies is between 0.766 and 0.893 points higher than for that of action movies.</p>
<p>The important thing to check here is whether 0 is contained in the confidence interval. If it is, it is plausible that the difference in the two population means between the two groups is 0. This means that the null hypothesis is plausible. The results of the hypothesis test and the confidence interval should match as they do here. We rejected the null hypothesis with hypothesis testing and we have evidence here than the mean rating for romance movies is higher than for action movies.</p>
</div>
<div id="effect-size" class="section level2">
<h2><span class="header-section-number">8.4</span> Effect size</h2>
<p>The phrase <strong>effect size</strong> has been thrown around recently as an alternative to <span class="math inline">\(p\)</span>-values. In combination with the confidence interval, it can be often more valuable than just looking at the results of a hypothesis test. It depends on the scientific discipline exactly what is meant by “effect size” but, in general, it refers to <em>the magnitude of the difference between group measurements</em>. For our two sample problem involving movies, it is the observed difference in sample means <code>obs_diff</code>.</p>
<p>It’s worthy of mention here that confidence intervals are always centered at the observed statistic. In other words, if you are looking at a confidence interval and someone asks you what the “effect size” is you can simply find the midpoint of the stated confidence interval.</p>
<!--
## Theory-based CIs 
-->
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC8.10)</strong> Check to see whether the difference in population mean ratings for the two genres falls in the confidence interval we found here. Are we guaranteed that it will fall in the range of plausible values?</p>
<p><strong>(LC8.11)</strong> Why do you think many scientific fields are shifting to preferring inclusion of confidence intervals in articles over just <span class="math inline">\(p\)</span>-values and hypothesis tests?</p>
<p><strong>(LC8.12)</strong> Why is 95% related to a value of 2 in the margin of error? What would approximate values be for 90% and for 99%?</p>
<p><strong>(LC8.13)</strong> Why is a 95% confidence interval wider than a 90% confidence interval? Explain by using a concrete example from everyday life about what is meant by “confidence.”</p>
<p><strong>(LC8.14)</strong> How would confidence intervals correspond to one-sided hypothesis tests?</p>
<p><strong>(LC8.15)</strong> There is a relationship between the significance level and the confidence level. What do you think it is?</p>
<hr />
</div>
<div id="script-of-r-code-3" class="section level2">
<h2><span class="header-section-number">8.5</span> Script of R code</h2>
<p>An R script file of all R code used in this chapter is available <a href="http://ismayc.github.io/moderndiver-book/08-ci.R">here</a>.</p>
</div>
<div id="whats-to-come-5" class="section level2">
<h2><span class="header-section-number">8.6</span> What’s to come?</h2>
<p>We will see in Chapter <a href="9-regression-via-broom.html#regress"><strong>??</strong></a> many of the same ideas we have seen with hypothesis testing and confidence intervals in the last two chapters. Regression is frequently associated both correctly and incorrectly with statistics and data analysis, so you’ll need to make sure you understand when it is appropriate and when it is not.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-lock2012">
<p>Lock, Robin, Patti Frazer Lock, Kari Lock Morgan, Eric F. Lock, and Dennis F. Lock. 2012. <em>Statistics: UnLOCKing the Power of Data</em>. Wiley.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="7-hypo.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="9-regression-via-broom.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ismayc/moderndiver-source/edit/master/08-ci.Rmd",
"text": "Edit"
},
"download": ["ismaykim.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
