<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>ModernDive</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="Combining statistical and computational thinking to make sense of data. Getting away from the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown">
  <meta name="generator" content="bookdown 0.3 and GitBook 2.6.7">

  <meta property="og:title" content="ModernDive" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Combining statistical and computational thinking to make sense of data. Getting away from the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown" />
  <meta name="github-repo" content="ismayc/moderndiver-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="ModernDive" />
  
  <meta name="twitter:description" content="Combining statistical and computational thinking to make sense of data. Getting away from the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown" />
  

<meta name="author" content="Chester Ismay and Albert Y. Kim">


<meta name="date" content="2017-01-06">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="A-appendixA.html">
<link rel="next" href="C-appendixC.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-0.8/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.4/dygraphs.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#colophon"><i class="fa fa-check"></i>Colophon</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-intro.html"><a href="2-intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="2-intro.html"><a href="2-intro.html#preamble"><i class="fa fa-check"></i><b>2.1</b> Preamble</a></li>
<li class="chapter" data-level="2.2" data-path="2-intro.html"><a href="2-intro.html#two-driving-data-sources"><i class="fa fa-check"></i><b>2.2</b> Two driving data sources</a></li>
<li class="chapter" data-level="2.3" data-path="2-intro.html"><a href="2-intro.html#datascience-pipeline"><i class="fa fa-check"></i><b>2.3</b> Data/science pipeline</a></li>
<li class="chapter" data-level="2.4" data-path="2-intro.html"><a href="2-intro.html#reproducibility"><i class="fa fa-check"></i><b>2.4</b> Reproducibility</a></li>
<li class="chapter" data-level="2.5" data-path="2-intro.html"><a href="2-intro.html#who-is-this-book-for"><i class="fa fa-check"></i><b>2.5</b> Who is this book for?</a></li>
</ul></li>
<li class="part"><span><b>I Data Exploration</b></span></li>
<li class="chapter" data-level="3" data-path="3-tidy.html"><a href="3-tidy.html"><i class="fa fa-check"></i><b>3</b> Tidy Data</a><ul>
<li class="chapter" data-level="3.1" data-path="3-tidy.html"><a href="3-tidy.html#what-is-tidy-data"><i class="fa fa-check"></i><b>3.1</b> What is tidy data?</a></li>
<li class="chapter" data-level="3.2" data-path="3-tidy.html"><a href="3-tidy.html#the-nycflights13-datasets"><i class="fa fa-check"></i><b>3.2</b> The <code>nycflights13</code> datasets</a></li>
<li class="chapter" data-level="3.3" data-path="3-tidy.html"><a href="3-tidy.html#how-is-flights-tidy"><i class="fa fa-check"></i><b>3.3</b> How is <code>flights</code> tidy?</a></li>
<li class="chapter" data-level="3.4" data-path="3-tidy.html"><a href="3-tidy.html#normal-forms-of-data"><i class="fa fa-check"></i><b>3.4</b> Normal forms of data</a></li>
<li class="chapter" data-level="3.5" data-path="3-tidy.html"><a href="3-tidy.html#whats-to-come"><i class="fa fa-check"></i><b>3.5</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html"><i class="fa fa-check"></i><b>4</b> Data Visualization via <code id="viz">ggplot2</code></a><ul>
<li class="chapter" data-level="4.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#five-named-graphs---the-5ng"><i class="fa fa-check"></i><b>4.1</b> Five Named Graphs - The 5NG</a></li>
<li class="chapter" data-level="4.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#histograms"><i class="fa fa-check"></i><b>4.2</b> Histograms</a><ul>
<li class="chapter" data-level="4.2.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#contsum"><i class="fa fa-check"></i><b>4.2.1</b> Continuous data summaries</a></li>
<li class="chapter" data-level="4.2.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary"><i class="fa fa-check"></i><b>4.2.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#boxplots"><i class="fa fa-check"></i><b>4.3</b> Boxplots</a><ul>
<li class="chapter" data-level="4.3.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#faceting"><i class="fa fa-check"></i><b>4.3.1</b> Faceting</a></li>
<li class="chapter" data-level="4.3.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary-1"><i class="fa fa-check"></i><b>4.3.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#barplots"><i class="fa fa-check"></i><b>4.4</b> Barplots</a><ul>
<li class="chapter" data-level="4.4.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>4.4.1</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="4.4.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#using-barplots-to-compare-two-variables"><i class="fa fa-check"></i><b>4.4.2</b> Using barplots to compare two variables</a></li>
<li class="chapter" data-level="4.4.3" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary-2"><i class="fa fa-check"></i><b>4.4.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#scatter-plots"><i class="fa fa-check"></i><b>4.5</b> Scatter-plots</a><ul>
<li class="chapter" data-level="4.5.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#jittering"><i class="fa fa-check"></i><b>4.5.1</b> Jittering</a></li>
<li class="chapter" data-level="4.5.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#setting-transparency"><i class="fa fa-check"></i><b>4.5.2</b> Setting transparency</a></li>
<li class="chapter" data-level="4.5.3" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary-3"><i class="fa fa-check"></i><b>4.5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#line-graphs"><i class="fa fa-check"></i><b>4.6</b> Line-graphs</a><ul>
<li class="chapter" data-level="4.6.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary-4"><i class="fa fa-check"></i><b>4.6.1</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#brief-review-of-the-grammar-of-graphics"><i class="fa fa-check"></i><b>4.7</b> Brief Review of The Grammar of Graphics</a></li>
<li class="chapter" data-level="4.8" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#script-of-r-code"><i class="fa fa-check"></i><b>4.8</b> Script of R code</a></li>
<li class="chapter" data-level="4.9" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#whats-to-come-1"><i class="fa fa-check"></i><b>4.9</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html"><i class="fa fa-check"></i><b>5</b> Data Manipulation via <code id="manip">dplyr</code></a><ul>
<li class="chapter" data-level="5.1" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#five-main-verbs---the-fmv"><i class="fa fa-check"></i><b>5.1</b> Five Main Verbs - The FMV</a><ul>
<li class="chapter" data-level="5.1.1" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#select-variables-using-select"><i class="fa fa-check"></i><b>5.1.1</b> Select variables using <code id="select">select</code></a></li>
<li class="chapter" data-level="5.1.2" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#filter-observations-using-filter"><i class="fa fa-check"></i><b>5.1.2</b> Filter observations using <code id="filter">filter</code></a></li>
<li class="chapter" data-level="5.1.3" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#summarize-variables-using-summarize"><i class="fa fa-check"></i><b>5.1.3</b> Summarize variables using <code>summarize</code></a></li>
<li class="chapter" data-level="5.1.4" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#create-new-variableschange-old-variables-using-mutate"><i class="fa fa-check"></i><b>5.1.4</b> Create new variables/change old variables using <code>mutate</code></a></li>
<li class="chapter" data-level="5.1.5" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#reorder-the-data-frame-using-arrange"><i class="fa fa-check"></i><b>5.1.5</b> Reorder the data frame using <code id="arrange">arrange</code></a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#the-pipe"><i class="fa fa-check"></i><b>5.2</b> The pipe <code>%&gt;%</code></a></li>
<li class="chapter" data-level="5.3" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#joiningmerging-data-frames"><i class="fa fa-check"></i><b>5.3</b> Joining/merging data frames</a></li>
<li class="chapter" data-level="5.4" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#script-of-r-code-1"><i class="fa fa-check"></i><b>5.4</b> Script of R code</a></li>
<li class="chapter" data-level="5.5" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#whats-to-come-2"><i class="fa fa-check"></i><b>5.5</b> What’s to come?</a></li>
</ul></li>
<li class="part"><span><b>II Inference</b></span></li>
<li class="chapter" data-level="6" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html"><i class="fa fa-check"></i><b>6</b> Simulating Randomness via <code id="infer-basics">mosaic</code></a><ul>
<li class="chapter" data-level="6.1" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#needed-packages"><i class="fa fa-check"></i><b>6.1</b> Needed packages</a></li>
<li class="chapter" data-level="6.2" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#random-sampling"><i class="fa fa-check"></i><b>6.2</b> Random sampling</a><ul>
<li class="chapter" data-level="6.2.1" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#tasting-soup"><i class="fa fa-check"></i><b>6.2.1</b> Tasting soup</a></li>
<li class="chapter" data-level="6.2.2" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#common-terms"><i class="fa fa-check"></i><b>6.2.2</b> Common terms</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#visualizing-sampling"><i class="fa fa-check"></i><b>6.3</b> Visualizing Sampling</a><ul>
<li class="chapter" data-level="6.3.1" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#sampling-distribution"><i class="fa fa-check"></i><b>6.3.1</b> Sampling distribution</a></li>
<li class="chapter" data-level="6.3.2" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#repeated-sampling-via-do"><i class="fa fa-check"></i><b>6.3.2</b> Repeated sampling via <code>do</code></a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#simulation"><i class="fa fa-check"></i><b>6.4</b> Simulation</a></li>
<li class="chapter" data-level="6.5" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#review-of-mosaic-simulation-functions"><i class="fa fa-check"></i><b>6.5</b> Review of <code>mosaic</code> simulation functions</a></li>
<li class="chapter" data-level="6.6" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#script-of-r-code-2"><i class="fa fa-check"></i><b>6.6</b> Script of R code</a></li>
<li class="chapter" data-level="6.7" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#whats-to-come-3"><i class="fa fa-check"></i><b>6.7</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-hypo.html"><a href="7-hypo.html"><i class="fa fa-check"></i><b>7</b> Hypothesis Testing</a><ul>
<li class="chapter" data-level="7.1" data-path="7-hypo.html"><a href="7-hypo.html#needed-packages-1"><i class="fa fa-check"></i><b>7.1</b> Needed packages</a></li>
<li class="chapter" data-level="7.2" data-path="7-hypo.html"><a href="7-hypo.html#basics-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.2</b> Basics of Hypothesis Testing</a></li>
<li class="chapter" data-level="7.3" data-path="7-hypo.html"><a href="7-hypo.html#trial"><i class="fa fa-check"></i><b>7.3</b> Criminal trial analogy</a><ul>
<li class="chapter" data-level="7.3.1" data-path="7-hypo.html"><a href="7-hypo.html#two-possible-conclusions"><i class="fa fa-check"></i><b>7.3.1</b> Two possible conclusions</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="7-hypo.html"><a href="7-hypo.html#types-of-errors-in-hypothesis-testing"><i class="fa fa-check"></i><b>7.4</b> Types of Errors in Hypothesis Testing</a><ul>
<li class="chapter" data-level="7.4.1" data-path="7-hypo.html"><a href="7-hypo.html#logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.4.1</b> Logic of Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="7-hypo.html"><a href="7-hypo.html#statistical-significance"><i class="fa fa-check"></i><b>7.5</b> Statistical Significance</a></li>
<li class="chapter" data-level="7.6" data-path="7-hypo.html"><a href="7-hypo.html#revisiting-the-lady-tasting-tea-example"><i class="fa fa-check"></i><b>7.6</b> Revisiting the Lady Tasting Tea example</a><ul>
<li class="chapter" data-level="7.6.1" data-path="7-hypo.html"><a href="7-hypo.html#data"><i class="fa fa-check"></i><b>7.6.1</b> Data</a></li>
<li class="chapter" data-level="7.6.2" data-path="7-hypo.html"><a href="7-hypo.html#test-statistic-delta"><i class="fa fa-check"></i><b>7.6.2</b> Test Statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="7.6.3" data-path="7-hypo.html"><a href="7-hypo.html#observed-effect-delta"><i class="fa fa-check"></i><b>7.6.3</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="7.6.4" data-path="7-hypo.html"><a href="7-hypo.html#model-of-h_0"><i class="fa fa-check"></i><b>7.6.4</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.6.5" data-path="7-hypo.html"><a href="7-hypo.html#simulated-data"><i class="fa fa-check"></i><b>7.6.5</b> Simulated Data</a></li>
<li class="chapter" data-level="7.6.6" data-path="7-hypo.html"><a href="7-hypo.html#distribution-of-delta-under-h_0"><i class="fa fa-check"></i><b>7.6.6</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.6.7" data-path="7-hypo.html"><a href="7-hypo.html#the-p-value"><i class="fa fa-check"></i><b>7.6.7</b> The p-value</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="7-hypo.html"><a href="7-hypo.html#when-inference-is-not-needed"><i class="fa fa-check"></i><b>7.7</b> When Inference Is Not Needed</a></li>
<li class="chapter" data-level="7.8" data-path="7-hypo.html"><a href="7-hypo.html#script-of-r-code-3"><i class="fa fa-check"></i><b>7.8</b> Script of R code</a></li>
<li class="chapter" data-level="7.9" data-path="7-hypo.html"><a href="7-hypo.html#whats-to-come-4"><i class="fa fa-check"></i><b>7.9</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-ci.html"><a href="8-ci.html"><i class="fa fa-check"></i><b>8</b> Confidence Intervals</a></li>
<li class="chapter" data-level="9" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html"><i class="fa fa-check"></i><b>9</b> Regression via <code id="regress">broom</code></a><ul>
<li class="chapter" data-level="9.1" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#whats-to-come-5"><i class="fa fa-check"></i><b>9.1</b> What’s to come?</a></li>
</ul></li>
<li class="part"><span><b>III Conclusion</b></span></li>
<li class="chapter" data-level="10" data-path="10-effective-data-storytelling.html"><a href="10-effective-data-storytelling.html"><i class="fa fa-check"></i><b>10</b> Effective Data Storytelling</a><ul>
<li class="chapter" data-level="10.1" data-path="10-effective-data-storytelling.html"><a href="10-effective-data-storytelling.html#conclusion"><i class="fa fa-check"></i><b>10.1</b> Concluding Remarks</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="A-appendixA.html"><a href="A-appendixA.html"><i class="fa fa-check"></i><b>A</b> Statistical Background</a><ul>
<li class="chapter" data-level="A.1" data-path="A-appendixA.html"><a href="A-appendixA.html#basic-statistical-terms"><i class="fa fa-check"></i><b>A.1</b> Basic statistical terms</a><ul>
<li class="chapter" data-level="A.1.1" data-path="A-appendixA.html"><a href="A-appendixA.html#mean"><i class="fa fa-check"></i><b>A.1.1</b> Mean</a></li>
<li class="chapter" data-level="A.1.2" data-path="A-appendixA.html"><a href="A-appendixA.html#median"><i class="fa fa-check"></i><b>A.1.2</b> Median</a></li>
<li class="chapter" data-level="A.1.3" data-path="A-appendixA.html"><a href="A-appendixA.html#standard-deviation"><i class="fa fa-check"></i><b>A.1.3</b> Standard deviation</a></li>
<li class="chapter" data-level="A.1.4" data-path="A-appendixA.html"><a href="A-appendixA.html#five-number-summary"><i class="fa fa-check"></i><b>A.1.4</b> Five-number summary</a></li>
<li class="chapter" data-level="A.1.5" data-path="A-appendixA.html"><a href="A-appendixA.html#distribution"><i class="fa fa-check"></i><b>A.1.5</b> Distribution</a></li>
<li class="chapter" data-level="A.1.6" data-path="A-appendixA.html"><a href="A-appendixA.html#outliers"><i class="fa fa-check"></i><b>A.1.6</b> Outliers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="B-appendixB.html"><a href="B-appendixB.html"><i class="fa fa-check"></i><b>B</b> Inference Examples</a><ul>
<li class="chapter" data-level="B.1" data-path="B-appendixB.html"><a href="B-appendixB.html#randomization"><i class="fa fa-check"></i><b>B.1</b> Randomization</a><ul>
<li class="chapter" data-level="B.1.1" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-action-and-romance-movies"><i class="fa fa-check"></i><b>B.1.1</b> Comparing Action and Romance Movies</a></li>
<li class="chapter" data-level="B.1.2" data-path="B-appendixB.html"><a href="B-appendixB.html#sampling-rightarrow-randomization"><i class="fa fa-check"></i><b>B.1.2</b> Sampling <span class="math inline">\(\rightarrow\)</span> Randomization</a></li>
<li class="chapter" data-level="B.1.3" data-path="B-appendixB.html"><a href="B-appendixB.html#summary-5"><i class="fa fa-check"></i><b>B.1.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="B.2" data-path="B-appendixB.html"><a href="B-appendixB.html#bootstrapping"><i class="fa fa-check"></i><b>B.2</b> Bootstrapping</a><ul>
<li class="chapter" data-level="B.2.1" data-path="B-appendixB.html"><a href="B-appendixB.html#review-of-bootstrapping"><i class="fa fa-check"></i><b>B.2.1</b> Review of Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="B.3" data-path="B-appendixB.html"><a href="B-appendixB.html#relation-to-hypothesis-testing"><i class="fa fa-check"></i><b>B.3</b> Relation to hypothesis testing</a></li>
<li class="chapter" data-level="B.4" data-path="B-appendixB.html"><a href="B-appendixB.html#effect-size"><i class="fa fa-check"></i><b>B.4</b> Effect size</a></li>
<li class="chapter" data-level="B.5" data-path="B-appendixB.html"><a href="B-appendixB.html#script-of-r-code-4"><i class="fa fa-check"></i><b>B.5</b> Script of R code</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="C-appendixC.html"><a href="C-appendixC.html"><i class="fa fa-check"></i><b>C</b> Reach for the Starts</a><ul>
<li class="chapter" data-level="C.1" data-path="C-appendixC.html"><a href="C-appendixC.html#sorted-barplots"><i class="fa fa-check"></i><b>C.1</b> Sorted barplots</a></li>
<li class="chapter" data-level="C.2" data-path="C-appendixC.html"><a href="C-appendixC.html#interactive-graphics"><i class="fa fa-check"></i><b>C.2</b> Interactive graphics</a><ul>
<li class="chapter" data-level="C.2.1" data-path="C-appendixC.html"><a href="C-appendixC.html#interactive-line-graphs"><i class="fa fa-check"></i><b>C.2.1</b> Interactive line-graphs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ModernDive</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="appendixB" class="section level1">
<h1><span class="header-section-number">B</span> Inference Examples</h1>
<div id="randomization" class="section level2">
<h2><span class="header-section-number">B.1</span> Randomization</h2>
<p>We will now focus on building hypotheses looking at the difference between two population means in an example. We will denote population means using the Greek symbol <span class="math inline">\(\mu\)</span> (pronounced “mu”). Thus, we will be looking to see if one group “out-performs” another group. This is quite possibly the most common type of statistical inference and serves as a basis for many other types of analyses when comparing two groups.</p>
<p>Our null hypothesis will be of the form <span class="math inline">\(H_0: \mu_1 = \mu_2\)</span>, which can also be written as <span class="math inline">\(H_0: \mu_1 - \mu_2 = 0\)</span>. Our alternative hypothesis will be of the form <span class="math inline">\(H_0: \mu_1 \star \mu_2\)</span> (or <span class="math inline">\(H_a: \mu_1 - \mu_2 \, \star \, 0\)</span>) where <span class="math inline">\(\star\)</span> = <span class="math inline">\(&lt;\)</span>, <span class="math inline">\(\ne\)</span>, or <span class="math inline">\(&gt;\)</span> depending on the context of the problem. You needn’t focus on these new symbols too much at this point. It will just be a shortcut way for us to describe our hypotheses.</p>
<p>As we saw in Chapter <a href="6-simulating-randomness-via-mosaic.html#infer-basics"><strong>??</strong></a>, simulation and bootstrapping are valuable tools when conducting inferences based on one population variable. We will see that the process of <strong>randomization</strong>, which is a resampling procedure similar to bootstrapping in some ways, will be valuable in conducting tests comparing quantitative values from two groups.</p>
<div id="comparing-action-and-romance-movies" class="section level3">
<h3><span class="header-section-number">B.1.1</span> Comparing Action and Romance Movies</h3>
<p>The <code>movies</code> data set in the <code>ggplot2movies</code> package contains information on a large number of movies that have been rated by users of IMDB.com. We are interested in the question here of whether <code>Action</code> movies are rated higher on IMDB than <code>Romance</code> movies. We will first need to do a little bit of data manipulation using the ideas from Chapter <a href="5-data-manipulation-via-dplyr.html#manip"><strong>??</strong></a> to get the data in the form that we would like:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
<span class="kw">library</span>(ggplot2movies)
(movies_trimmed &lt;-<span class="st"> </span>movies %&gt;%<span class="st"> </span><span class="kw">select</span>(title, year, rating, Action, Romance))</code></pre></div>
<pre><code>## # A tibble: 58,788 × 5
##                       title  year rating Action Romance
##                       &lt;chr&gt; &lt;int&gt;  &lt;dbl&gt;  &lt;int&gt;   &lt;int&gt;
## 1                         $  1971    6.4      0       0
## 2         $1000 a Touchdown  1939    6.0      0       0
## 3    $21 a Day Once a Month  1941    8.2      0       0
## 4                   $40,000  1996    8.2      0       0
## 5  $50,000 Climax Show, The  1975    3.4      0       0
## 6                     $pent  2000    4.3      0       0
## 7                   $windle  2002    5.3      1       0
## 8                      &#39;15&#39;  2002    6.7      0       0
## 9                       &#39;38  1987    6.6      0       0
## 10                  &#39;49-&#39;17  1917    6.0      0       0
## # ... with 58,778 more rows</code></pre>
<p>Note that <code>Action</code> and <code>Romance</code> are binary variables here. To remove any overlap of movies (and potential confusion) that are both <code>Action</code> and <code>Romance</code>, we will remove them from our <em>population</em>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">movies_trimmed &lt;-<span class="st"> </span>movies_trimmed %&gt;%
<span class="st">  </span><span class="kw">filter</span>(!(Action ==<span class="st"> </span><span class="dv">1</span> &amp;<span class="st"> </span>Romance ==<span class="st"> </span><span class="dv">1</span>))</code></pre></div>
<p>We will now create a new variable called <code>genre</code> that specifies whether a movie in our <code>movies_trimmed</code> data frame is an <code>&quot;Action&quot;</code> movie, a <code>&quot;Romance&quot;</code> movie, or <code>&quot;Neither&quot;</code>. We aren’t really interested in the <code>&quot;Neither&quot;</code> category here so we will exclude those rows as well. Lastly, the <code>Action</code> and <code>Romance</code> columns are not needed anymore since they are encoded in the <code>genre</code> column.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">movies_trimmed &lt;-<span class="st"> </span>movies_trimmed %&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">genre =</span> <span class="kw">ifelse</span>(Action ==<span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;Action&quot;</span>,
                        <span class="kw">ifelse</span>(Romance ==<span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;Romance&quot;</span>,
                               <span class="st">&quot;Neither&quot;</span>))) %&gt;%
<span class="st">  </span><span class="kw">filter</span>(genre !=<span class="st"> &quot;Neither&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">select</span>(-Action, -Romance)</code></pre></div>
<p>We are left with 8878 movies in our <em>population</em> data set that focuses on only <code>&quot;Action&quot;</code> and <code>&quot;Romance&quot;</code> movies.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.2)</strong> Why are the different genre variables stored as binary variables (1s and 0s) instead of just listing the <code>genre</code> as a column of values like “Action”, “Comedy”, etc.?</p>
<p><strong>(LC9.3)</strong> What complications could come above with us excluding action romance movies? Should we question the results of our hypothesis test? Explain.</p>
<hr />
<p>Let’s now visualize the distributions of <code>rating</code> across both levels of <code>genre</code>. Think about what type(s) of plot is/are appropriate here before you proceed:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
movies_trimmed %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> genre, <span class="dt">y =</span> rating)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-96"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-96-1.png" alt="Rating vs genre in the population" width="\textwidth" />
<p class="caption">
Figure B.1: Rating vs genre in the population
</p>
</div>
<p>We can see that the middle 50% of ratings for <code>&quot;Action&quot;</code> movies is more spread out than that of <code>&quot;Romance&quot;</code> movies in the population. <code>&quot;Romance&quot;</code> has outliers at both the top and bottoms of the scale though. We are initially interested in comparing the mean <code>rating</code> across these two groups so a faceted histogram may also be useful:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">movies_trimmed %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> rating)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">1</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;dodgerblue&quot;</span>) +
<span class="st">  </span><span class="kw">facet_grid</span>(genre ~<span class="st"> </span>.)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-97"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-97-1.png" alt="Faceted histogram of genre vs rating" width="\textwidth" />
<p class="caption">
Figure B.2: Faceted histogram of genre vs rating
</p>
</div>
<p><strong>Important note:</strong> Remember that we hardly ever have access to the population values as we do here. This example and the <code>nycflights13</code> data set were used to create a common flow from chapter to chapter. In nearly all circumstances, we’ll be needing to use only a sample of the population to try to infer conclusions about the unknown population parameter values. These examples do show a nice relationship between statistics (where data is usually small and more focused on experimental settings) and data science (where data is frequently large and collected without experimental conditions).</p>
<!--
We'll learn more about observational studies and experiments in Chapter \@ref(regress).
-->
</div>
<div id="sampling-rightarrow-randomization" class="section level3">
<h3><span class="header-section-number">B.1.2</span> Sampling <span class="math inline">\(\rightarrow\)</span> Randomization</h3>
<p>We can use hypothesis testing to investigate ways to determine, for example, whether a <strong>treatment</strong> has an effect over a <strong>control</strong> and other ways to statistically analyze if one group performs better than, worse than, or different than another. We will also use confidence intervals to determine the size of the effect if it exists. You’ll see more on this in Chapter <a href="8-ci.html#ci">8</a>.</p>
<p>We are interested here in seeing how we can use a random sample of action movies and a random sample of romance movies from <code>movies</code> to determine if a statistical difference exists in the mean ratings of each group.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.4)</strong> Define the relevant parameters here in terms of the populations of movies.</p>
<hr />
<p>Let’s select a random sample of 34 action movies and a random sample of 34 romance movies. (The number 34 was chosen somewhat arbitrarily here.)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
<span class="kw">library</span>(mosaic)
<span class="kw">set.seed</span>(<span class="dv">2016</span>)
movies_genre_sample &lt;-<span class="st"> </span>movies_trimmed %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(genre) %&gt;%
<span class="st">  </span><span class="kw">sample_n</span>(<span class="dv">34</span>)</code></pre></div>
<p>We can now observe the distributions of our two sample ratings for both groups. Remember that these plots should be rough approximations of our population distributions of movie ratings for <code>&quot;Action&quot;</code> and <code>&quot;Romance&quot;</code> in our population of all movies in the <code>movies</code> data frame.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">movies_genre_sample %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> genre, <span class="dt">y =</span> rating)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-99"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-99-1.png" alt="Genre vs rating for our sample" width="\textwidth" />
<p class="caption">
Figure B.3: Genre vs rating for our sample
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">movies_genre_sample %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> rating)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">1</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;dodgerblue&quot;</span>) +
<span class="st">  </span><span class="kw">facet_grid</span>(genre ~<span class="st"> </span>.)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-100"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-100-1.png" alt="Genre vs rating for our sample as faceted histogram" width="\textwidth" />
<p class="caption">
Figure B.4: Genre vs rating for our sample as faceted histogram
</p>
</div>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.5)</strong> What single value could we change to improve the approximation using the sample distribution on the population distribution?</p>
<hr />
<p>Do we have reason to believe, based on the sample distributions of <code>rating</code> over the two groups of <code>genre</code>, that there is a significant difference between the mean <code>rating</code> for action movies compared to romance movies? It’s hard to say just based on the plots. The boxplot does show that the median sample rating is higher for romance movies, but the histogram isn’t as clear. The two groups have somewhat differently shaped distributions but they are both over similar values of <code>rating</code>. It’s often useful to calculate the mean and standard deviation as well, conditioned on the two levels.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">summary_ratings &lt;-<span class="st"> </span>movies_genre_sample %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(genre) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(rating),
            <span class="dt">std_dev =</span> <span class="kw">sd</span>(rating))
summary_ratings</code></pre></div>
<pre><code>## # A tibble: 2 × 3
##     genre     mean  std_dev
##     &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1  Action 5.197059 1.464837
## 2 Romance 6.026471 1.202096</code></pre>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.6)</strong> Why did we not specify <code>na.rm = TRUE</code> here as we did in Chapter <a href="5-data-manipulation-via-dplyr.html#manip"><strong>??</strong></a>?</p>
<hr />
<p>We see that the sample mean rating for romance movies, <span class="math inline">\(\bar{x}_{r}\)</span>, is greater than the similar measure for action movies, <span class="math inline">\(\bar{x}_a\)</span>. But is it statistically significantly greater (thus, leading us to conclude that the means are statistically different)? The standard deviation can provide some insight here but with these standard deviations being so similar it’s still hard to say for sure.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.7)</strong> Why might the standard deviation provide some insight about the means being statistically different or not?</p>
<hr />
<p>The hypotheses we specified can also be written in another form to better give us an idea of what we will be simulating to create our null distribution.</p>
<ul>
<li><span class="math inline">\(H_0: \mu_r - \mu_a = 0\)</span></li>
<li><span class="math inline">\(H_a: \mu_r - \mu_a \ne 0\)</span></li>
</ul>
<p>We are, therefore, interested in seeing whether the difference in the sample means, <span class="math inline">\(\bar{x}_r - \bar{x}_a\)</span>, is statistically different than 0. R has a built-in command that can calculate the difference in these two sample means.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mean_ratings &lt;-<span class="st"> </span>movies_genre_sample %&gt;%<span class="st"> </span><span class="kw">group_by</span>(genre) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(rating))
obs_diff &lt;-<span class="st"> </span><span class="kw">diff</span>(mean_ratings$mean)</code></pre></div>
<p>We see here that the <code>diff</code> function calculates <span class="math inline">\(\bar{x}_r - \bar{x}_a = 6.0264706 - 5.1970588 = 0.8294118\)</span>. We will now proceed similarly to how we conducted hypothesis tests in Chapter <a href="6-simulating-randomness-via-mosaic.html#infer-basics"><strong>??</strong></a> using simulation. Our goal is figure out a random process with which to simulate the null hypothesis being true. In Chapter <a href="6-simulating-randomness-via-mosaic.html#infer-basics"><strong>??</strong></a>, we used flipping of a fair coin as the random process we were simulating with the null hypothesis being true (<span class="math inline">\(H_0: \pi = 0.5\)</span>).</p>
<p>Here, with us assuming the two population means are equal (<span class="math inline">\(H_0: \mu_r - \mu_a = 0\)</span>), we can look at this from a tactile point of view by using index cards. There are <span class="math inline">\(n_r = 34\)</span> data elements corresponding to romance movies and <span class="math inline">\(n_a = 34\)</span> for action movies. We can write the 34 ratings from our sample for romance movies on one set of 34 index cards and the 34 ratings for action movies on another set of 34 index cards. (Note that the sample sizes need not be the same.)</p>
<p>The next step is to put the two stacks of index cards together, creating a new set of 68 cards. If we assume that the two population means are equal, we are saying that there is no association between ratings and genre (romance vs action). We can use the index cards to create two <strong>new</strong> stacks for romance and action movies. First, we must shuffle all the cards thoroughly. After doing so, in this case with equal values of sample sizes, we split the deck in half. (You should be thinking about how this process is similar to what was done with <strong>bootstrapping</strong> in Chapter <a href="6-simulating-randomness-via-mosaic.html#infer-basics"><strong>??</strong></a>.)</p>
<p>We then calculate the new sample mean rating of the romance deck, and also the new sample mean rating of the action deck. This creates one simulation of the samples that were collected originally. We next want to calculate a statistic from these two samples. Instead of actually doing the calculation using index cards, we can use R as we have before to simulate this process.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.8)</strong> How would the tactile shuffling of index cards change if we had different samples of say 20 action movies and 60 romance movies? Describe each step that would change.</p>
<p><strong>(LC9.9)</strong> Why are we taking the difference in the means of the cards in the new shuffled decks?</p>
<hr />
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(mosaic)
shuffled_ratings &lt;-<span class="st"> </span>movies_trimmed %&gt;%
<span class="st">     </span><span class="kw">mutate</span>(<span class="dt">rating =</span> <span class="kw">shuffle</span>(rating)) %&gt;%<span class="st"> </span>
<span class="st">     </span><span class="kw">group_by</span>(genre) %&gt;%
<span class="st">     </span><span class="kw">summarize</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(rating))
<span class="kw">diff</span>(shuffled_ratings$mean)</code></pre></div>
<pre><code>## [1] -0.02287811</code></pre>
<p>The only new command here is <code>shuffle</code> from the <code>mosaic</code> package, which does what we would expect it to do. It simulates a shuffling of the ratings between the two levels of <code>genre</code> just as we could have done with index cards. We can now proceed in a similar way to what we have done previously in Chapter <a href="6-simulating-randomness-via-mosaic.html#infer-basics"><strong>??</strong></a> by repeating this process many times to create a <em>null distribution</em> of simulated differences in sample means.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">2016</span>)
many_shuffles &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span>
<span class="st">  </span>(movies_trimmed %&gt;%
<span class="st">     </span><span class="kw">mutate</span>(<span class="dt">rating =</span> <span class="kw">shuffle</span>(rating)) %&gt;%<span class="st"> </span>
<span class="st">     </span><span class="kw">group_by</span>(genre) %&gt;%
<span class="st">     </span><span class="kw">summarize</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(rating))
   )</code></pre></div>
<p>It is a good idea here to <code>View</code> the <code>many_shuffles</code> data frame via <code>View(many_shuffles)</code>. We need to figure out a way to subtract the first value of <code>mean</code> from the second value of <code>mean</code> for each of the 10,000 simulations. This is a little tricky but the <code>group_by</code> function comes to our rescue here:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rand_distn &lt;-<span class="st"> </span>many_shuffles %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(.index) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">diffmean =</span> <span class="kw">diff</span>(mean))</code></pre></div>
<p>We can now plot the distribution of these simulated differences in means:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rand_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffmean)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-106"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-106-1.png" alt="Simulated differences in means histogram" width="\textwidth" />
<p class="caption">
Figure B.5: Simulated differences in means histogram
</p>
</div>
<p>Remember that we are interested in seeing where our observed sample mean difference of 0.8294118 falls on this null/randomization distribution. We are interested in simply a difference here so “more extreme” corresponds to values in both tails on the distribution. Let’s shade our null distribution to show a visual representation of our <span class="math inline">\(p\)</span>-value:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rand_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffmean, <span class="dt">fill =</span> (<span class="kw">abs</span>(diffmean) &gt;=<span class="st"> </span>obs_diff))) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-107"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-107-1.png" alt="Shaded histogram to show p-value" width="\textwidth" />
<p class="caption">
Figure B.6: Shaded histogram to show p-value
</p>
</div>
<p>You may initially think there is an error here, but remember that the observed difference in means was 0.8294118. It falls far outside the range of simulated differences. We can add a vertical line to represent both it and its negative (since this is a two-tailed test) instead:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rand_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffmean)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">bins =</span> <span class="dv">100</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> obs_diff, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> -obs_diff, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-108"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-108-1.png" alt="Histogram with vertical lines corresponding to observed statistic" width="\textwidth" />
<p class="caption">
Figure B.7: Histogram with vertical lines corresponding to observed statistic
</p>
</div>
<p>Based on this plot, we have evidence supporting the conclusion that the mean rating for romance movies is different from that of action movies. (It doesn’t really matter what significance level was chosen in this case. Think about why.) The next important idea is to better understand just how much higher of a mean rating can we expect the romance movies to have compared to that of action movies. This can be addressed by creating a 95% confidence interval as we will explore in Chapter <a href="8-ci.html#ci">8</a>.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.10)</strong> Conduct the same analysis comparing action movies versus romantic movies using the median rating instead of the mean rating? Make sure to use the <code>%&gt;%</code> as much as possible. What was different and what was the same?</p>
<p><strong>(LC9.11)</strong> What conclusions can you make from viewing the faceted histogram looking at <code>rating</code> versus <code>genre</code> that you couldn’t see when looking at the boxplot?</p>
<p><strong>(LC9.12)</strong> Describe in a paragraph how we used Allen Downey’s diagram to conclude if a statistical difference existed between mean movie ratings for action and romance movies.</p>
<p><strong>(LC9.13)</strong> Why are we relatively confident that the distributions of the sample ratings will be good approximations of the population distributions of ratings for the two genres?</p>
<p><strong>(LC9.14)</strong> Using the definition of “<span class="math inline">\(p\)</span>-value” in Chapter <a href="6-simulating-randomness-via-mosaic.html#infer-basics"><strong>??</strong></a>, write in words what the <span class="math inline">\(p\)</span>-value represents for the hypothesis test above comparing the mean rating of romance to action movies.</p>
<p><strong>(LC9.15)</strong> What is the value of the <span class="math inline">\(p\)</span>-value for the hypothesis test comparing the mean rating of romance to action movies?</p>
<p><strong>(LC9.16)</strong> Do the results of the hypothesis test match up with the original plots we made looking at the population of movies? Why or why not?</p>
<hr />
</div>
<div id="summary-5" class="section level3">
<h3><span class="header-section-number">B.1.3</span> Summary</h3>
<p>To review, these are the steps one would take whenever you’d like to do a hypothesis test comparing values from the distributions of two groups:</p>
<ul>
<li><p>Simulate many samples using a random process that matches the way the original data were collected and that <em>assumes the null hypothesis is true</em>.</p></li>
<li><p>Collect the values of a sample statistic for each sample created using this random process to build a <em>randomization distribution</em>.</p></li>
<li><p>Assess the significance of the <em>original</em> sample by determining where its sample statistic lies in the randomization distribution.</p></li>
<li><p>If the proportion of values as extreme or more extreme than the observed statistic in the randomization distribution is smaller than the pre-determined significance level <span class="math inline">\(\alpha\)</span>, we reject <span class="math inline">\(H_0\)</span>. Otherwise, we fail to reject <span class="math inline">\(H_0\)</span>. (If no significance level is given, one can assume <span class="math inline">\(\alpha = 0.05\)</span>.)</p></li>
</ul>
<!--
## Theory-based methods {#theory-hypo} (Put into lab instead)

## Non-rejection of null hypothesis (Put into lab instead)
-->
</div>
</div>
<div id="bootstrapping" class="section level2">
<h2><span class="header-section-number">B.2</span> Bootstrapping</h2>
<p>Just as we did in the previous section when making hypotheses about a population proportion with which we would like to test which one is more plausible, we can also use simulation to infer conclusions about a population quantitative statistic such as the mean. In this case, we will focus on constructing confidence intervals to produce plausible values for a population mean. (We can do a similar analysis for a population median or other summary measure as well.)</p>
<p>Traditionally, the way to construct confidence intervals for a mean is to assume a normal distribution for the population or to invoke the Central Limit Theorem and get, what often appears to be magic, results. These methods are often not intuitive, especially for those that lack a strong mathematical background. They also come with their fair share of assumptions and often turn Statistics, a field that is full of tons of useful applications to many different fields and disciplines, into a robotic procedural-based topic. It doesn’t have to be that way!</p>
<p>In this section, we will introduce the concept of <strong>bootstrapping</strong>. It will be a useful tool that will allow us to estimate the variability of our statistic from sample to sample. One neat feature of bootstrapping is that it enables us to approximate the sampling distribution and estimate the distribution’s standard deviation using ONLY the information in the one selected (original) sample.</p>
<p>It sounds just as plagued with the magical type qualities of traditional theory-based inference on initial glance but we will see that it provides an intuitive and useful way to make inferences, especially when the samples are of medium to large size.</p>
<!--We will begin by investigating an example on the selling prices of used Ford Mustang cars taken from the textbook {\it Statistics:  UnLOCKing the Power of Data} by Lock, Lock, Lock, Lock, and Lock.  (That isn't me hitting Copy+Paste too many times.  Patti and Robin Lock both work in the Mathematics Department at St. Lawrence University and they have three children that are statisticians.  They are often referred to as the Lock5.)
-->
<p>To introduce the concept of bootstrapping, we now introduce the <code>movies</code> data set in the <code>ggplot2movies</code> data frame. We will load this data frame into R in much the same way as we loaded <code>flights</code> and <code>weather</code> from the <code>nycflights13</code> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2movies)
<span class="kw">data</span>(movies, <span class="dt">package =</span> <span class="st">&quot;ggplot2movies&quot;</span>)</code></pre></div>
<p>Let’s also glance at this data frame using the <code>View</code> function and look at the help documentation for <code>movies</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">View</span>(movies)
?movies</code></pre></div>
<p>We will explore many other features of this data set in the chapters to come, but here we will be focusing on the <code>rating</code> variable corresponding to the average IMDB user rating.</p>
<p>You may notice that this data set is quite large: 58,788 movies have data collected about them here. This will correspond to our population of ALL movies. Remember from Chapter <a href="6-simulating-randomness-via-mosaic.html#infer-basics"><strong>??</strong></a> that our population is rarely known. We use this data set as our population here to show you the power of bootstrapping in estimating population parameters. We’ll see how <strong>confidence intervals</strong> built using the bootstrap distribution do at including our population parameter of interest. Here we can actually calculate these values since our population is known, but remember that in general this isn’t the case.</p>
<p>Let’s take a look at what the distribution of our population <code>ratings</code> looks like. We’ll see that we will use the distribution of our sample(s) as an estimate of this population histogram.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">movies %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> rating)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-111"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-111-1.png" alt="Population ratings histogram" width="\textwidth" />
<p class="caption">
Figure B.8: Population ratings histogram
</p>
</div>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.17)</strong> Why was a histogram chosen as the plot to make for the <code>rating</code> variable above?</p>
<p><strong>(LC9.18)</strong> Why does the shape of the <code>rating</code> histogram tell us about how IMDB users rate movies? What stands out about the plot?</p>
<hr />
<p>It’s important to think about what our goal is here. We would like to produce a confidence interval for the population mean <code>rating</code>. We will have to pretend for a moment that we don’t have all 58,788 movies. Let’s say that we only have a random sample of 50 movies from this data set instead. In order to get a random sample, we can use the <code>sample_n</code> function from <code>dplyr</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">2016</span>)
movies_sample &lt;-<span class="st"> </span>movies %&gt;%
<span class="st">  </span><span class="kw">sample_n</span>(<span class="dv">50</span>)</code></pre></div>
<p>The <code>sample_n</code> function has filtered the data frame <code>movies</code> “at random” to choose only 50 rows from the larger <code>movies</code> data frame. We store information on these 50 movies in the <code>movies_sample</code> data frame.</p>
<p>Let’s now explore what the <code>rating</code> variable looks like for these 50 movies:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">movies_sample %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> rating)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-113"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-113-1.png" alt="Sample ratings histogram" width="\textwidth" />
<p class="caption">
Figure B.9: Sample ratings histogram
</p>
</div>
<p>Remember that we can think of this histogram as an estimate of our population distribution histogram that we saw above. We are interested in the population mean rating and trying to find a range of plausible values for that value. A good start in guessing the population mean is to use the mean of our sample <code>rating</code> from the <code>movies_sample</code> data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(movies_sample_mean &lt;-<span class="st"> </span>movies_sample %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(rating)))</code></pre></div>
<pre><code>## # A tibble: 1 × 1
##    mean
##   &lt;dbl&gt;
## 1 6.034</code></pre>
<p>Note the use of the <code>( )</code> at the beginning and the end of this creation of the <code>movies_sample_mean</code> object. If you’d like to print out your newly created object, you can enclose it in the parentheses as we have here.</p>
<p>This value of 6.034 is just one guess at the population mean. The idea behind <em>bootstrapping</em> is to sample <strong>with replacement</strong> from the original sample to create new <strong>resamples</strong> of the same size as our original sample.</p>
<p>Returning to our example, let’s investigate what one such resample of the <code>movies_sample</code> data set accomplishes. We can create one resample/bootstrap sample by using the <code>resample</code> function in the <code>mosaic</code> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(mosaic)
<span class="kw">library</span>(tibble)
boot1 &lt;-<span class="st"> </span><span class="kw">resample</span>(movies_sample, <span class="dt">orig.ids =</span> <span class="ot">TRUE</span>) %&gt;%
<span class="st">  </span><span class="kw">select</span>(orig.id, <span class="kw">everything</span>()) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(orig.id)</code></pre></div>
<p>Take a look at this resample/bootstrap:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">View</span>(boot1)</code></pre></div>
<p>The important thing to note here is the original row numbers from the <code>movies_sample</code> data frame in the far left column called <code>orig.ids</code>. Since we are sampling with replacement, there is a strong likelihood that some of the 50 observational units are going to be selected again.</p>
<p>You may be asking yourself what does this mean and how to this lead us to creating a distribution for the sample mean. Recall that the original sample mean of our data was calculated using the <code>summarize</code> function above.</p>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.19)</strong> What happens if we change the seed to our pseudo-random generation? Try it above when we used <code>sample_n</code> to describe the resulting <code>movies_sample</code>.</p>
<p><strong>(LC9.20)</strong> Why is sampling at random important from the <code>movies</code> data frame? Why don’t we just pick <code>Action</code> movies and do bootstrapping with this <code>Action</code> movies subset?</p>
<p><strong>(LC9.21)</strong> What was the purpose of assuming we didn’t have access to the full <code>movies</code> data set here?</p>
<hr />
<p>Before we had a calculated mean in our original sample of 6.034. Let’s calculate the mean of <code>ratings</code> in our bootstrapped sample:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(movies_boot1_mean &lt;-<span class="st"> </span>boot1 %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(rating)))</code></pre></div>
<pre><code>## # A tibble: 1 × 1
##    mean
##   &lt;dbl&gt;
## 1 6.144</code></pre>
<p>More than likely the calculated bootstrap sample mean is different than the original sample mean. This is what I meant earlier when I said that the sample means have some variability. What we are trying to do is replicate many different samples being taken from a larger population. Our best guess at what the population looks like is multiple copies of the sample we collected. We then can sample from that larger “created” population by generating bootstrap samples.</p>
<p>Similar to what we did in the previous section, we can repeat this process using the <code>do</code> function followed by an asterisk. Let’s look at 10 different bootstrap means for <code>ratings</code> from <code>movies_sample</code>. Note the use of the <code>resample</code> function here.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">do</span>(<span class="dv">10</span>) *<span class="st"> </span><span class="kw">summarize</span>(<span class="kw">resample</span>(movies_sample), <span class="dt">mean =</span> <span class="kw">mean</span>(rating))</code></pre></div>
<pre><code>##     mean
## 1  6.020
## 2  6.668
## 3  5.996
## 4  6.056
## 5  6.168
## 6  6.360
## 7  5.702
## 8  6.218
## 9  6.252
## 10 5.904</code></pre>
<p>You should see some variability begin to tease its way out here. Many of the simulated means will be close to our original sample mean but many will stray pretty far away. This occurs because outliers may have been selected a couple of times in the resampling or small values were selected more than larger. There are myriad reasons why this might be the case.</p>
<p>So what’s the next step now? Just as we repeated the repetitions thousands of times with the “Lady Tasting Tea” example, we can do a similar thing here.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">trials &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span><span class="kw">summarize</span>(<span class="kw">resample</span>(movies_sample), 
                                <span class="dt">mean =</span> <span class="kw">mean</span>(rating))
trials %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-119"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-119-1.png" alt="Bootstrapped means histogram" width="\textwidth" />
<p class="caption">
Figure B.10: Bootstrapped means histogram
</p>
</div>
<p>The shape of this resulting distribution may look familiar to you. It resembles the well-known normal (bell-shaped) curve. We will see in Chapters <a href="7-hypo.html#hypo">7</a> and <a href="8-ci.html#ci">8</a> when we might expect a normal curve to come through as we have here and when we shouldn’t. There will be specific assumptions that need to be checked and we will see that the normal distribution doesn’t always approximate this bootstrapped distribution well. In those case, we should NOT rely on traditional methods.</p>
<p>At this point, we can easily calculate a confidence interval. In fact, we have a couple different options. We will first use the percentiles of the distribution we just created to isolate the middle 95% of values. This will correspond to our 95% confidence interval for the population mean <code>rating</code>, denoted by <span class="math inline">\(\mu\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(ciq_mean_rating &lt;-<span class="st"> </span><span class="kw">confint</span>(trials, <span class="dt">level =</span> <span class="fl">0.95</span>, <span class="dt">method =</span> <span class="st">&quot;quantile&quot;</span>))</code></pre></div>
<pre><code>##   name   lower upper level     method estimate
## 1 mean 5.50795  6.54  0.95 percentile    6.034</code></pre>
<p>It’s always important at this point to interpret the results of this confidence interval calculation. In this context, we can say something like the following:</p>
<blockquote>
<p>Based on the sample data and bootstrapping techniques, we can be 95% confident that the true mean rating of ALL IMDB ratings is between 5.50795 and 6.54.</p>
</blockquote>
<p>This statement may seem a little confusing to you. Remember that we are pretending like we don’t know what the mean IMDB rating for ALL movies is. Our population here is all of the movies listed in the <code>movies</code> data frame from <code>ggplot2movies</code>. So does our bootstrapped confidence interval here contain the actual mean value?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarize</span>(movies, <span class="dt">mean =</span> <span class="kw">mean</span>(rating))</code></pre></div>
<pre><code>## # A tibble: 1 × 1
##      mean
##     &lt;dbl&gt;
## 1 5.93285</code></pre>
<p>We see here that the population mean does fall in our range of plausible values generated from the bootstrapped samples.</p>
<p>We can also get an idea of how the theory-based inference techniques would have approximated this confidence interval by using the formula <span class="math display">\[\bar{x} \pm (2 * SE),\]</span> where <span class="math inline">\(\bar{x}\)</span> is our original sample mean and <span class="math inline">\(SE\)</span> stands for <strong>standard error</strong> and corresponds to the standard deviation of the bootstrap distribution. The value of 2 here corresponds to it being a 95% confidence interval. This formula assumes that the bootstrap distribution is symmetric. This is often the case with bootstrap distributions, especially those in which the original distribution of the sample is not highly skewed.</p>
<p>To compute this type of confidence interval, we only need to make a slight modification to the <code>confint</code> function seen above. (The expression after the <span class="math inline">\(\pm\)</span> sign is known as the <strong>margin of error</strong>.)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(cise_mean_rating &lt;-<span class="st"> </span><span class="kw">confint</span>(trials, <span class="dt">level =</span> <span class="fl">0.95</span>, <span class="dt">method =</span> <span class="st">&quot;stderr&quot;</span>))</code></pre></div>
<pre><code>##   name    lower    upper level method estimate margin.of.error
## 1 mean 5.516196 6.551379  0.95 stderr    6.034       0.5175914</code></pre>
<blockquote>
<p>Based on the sample data and bootstrapping techniques, we can be 95% confident that the true mean rating of ALL IMDB ratings is between 5.5161962 and 6.551379.</p>
</blockquote>
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.22)</strong> Reproduce the bootstrapping above using a sample of size 50 instead of 25. What changes do you see?</p>
<p><strong>(LC9.23)</strong> Reproduce the bootstrapping above using a sample of size 5 instead of 25. What changes do you see?</p>
<p><strong>(LC9.24)</strong> How does the sample size affect the analysis?</p>
<p><strong>(LC9.25)</strong> Why must bootstrap samples be the same size as the original sample?</p>
<hr />
<div id="review-of-bootstrapping" class="section level3">
<h3><span class="header-section-number">B.2.1</span> Review of Bootstrapping</h3>
<p>We can summarize the process to generate a bootstrap distribution here in a series of steps that clearly identify the terminology we will use <span class="citation">(R. Lock et al. <a href="#ref-lock2012">2012</a>)</span>.</p>
<ul>
<li>Generate <code>bootstrap samples</code> by sampling with replacement from the original sample, using the same sample size.</li>
<li>Compute the statistic of interest, called a <code>bootstrap statistic</code>, for each of the bootstrap samples.</li>
<li>Collect the statistics for many bootstrap samples to create a <code>bootstrap distribution</code>.</li>
</ul>
<p>Visually, we can represent this process in the following diagram.</p>
<div class="figure" style="text-align: center"><span id="fig:bootstrapimg"></span>
<img src="images/bootstrap.png" alt="Bootstrapping diagram from Lock5 textbook" width="\textwidth" />
<p class="caption">
Figure B.11: Bootstrapping diagram from Lock5 textbook
</p>
</div>
</div>
</div>
<div id="relation-to-hypothesis-testing" class="section level2">
<h2><span class="header-section-number">B.3</span> Relation to hypothesis testing</h2>
<p>Recall that we found a statistically significant difference in the sample mean of romance movie ratings compared to the sample mean of action movie ratings. We concluded Chapter <a href="7-hypo.html#hypo">7</a> by attempted to understand just how much greater we could expect the <em>population</em> mean romance movie rating to be as compared to the <em>population</em> mean action movie rating. In order to do so, we will calculate a confidence interval for the difference <span class="math inline">\(\mu_r - \mu_a\)</span>. We’ll then go back to our population parameter values and see if our confidence interval contains our parameter value.</p>
<p>We could use bootstrapping in a way similar to that done in the Chapter <a href="6-simulating-randomness-via-mosaic.html#infer-basics"><strong>??</strong></a>, except now on a difference in sample means, to create a distribution and then use the <code>confint</code> function with the option of <code>quantile</code> to determine a confidence interval for the plausible values of the difference in population means. This is an excellent programming activity and the reader is urged to try to do so.</p>
<p>Recall what the randomization/null distribution looked like for our simulated shuffled sample means:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(dplyr)
rand_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffmean)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-123"></span>
<img src="ismaykim_files/figure-html/unnamed-chunk-123-1.png" alt="Simulated shuffled sample means histogram" width="\textwidth" />
<p class="caption">
Figure B.12: Simulated shuffled sample means histogram
</p>
</div>
<p>With this null distribution being quite symmetric, the standard error method introduced in Chapter <a href="6-simulating-randomness-via-mosaic.html#infer-basics"><strong>??</strong></a> likely provides a good estimate of a range of plausible values for <span class="math inline">\(\mu_r - \mu_a\)</span>. Another nice option here is that we can use the standard deviation of the null/randomization distribution we just found with our hypothesis test.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(std_err &lt;-<span class="st"> </span>rand_distn %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">se =</span> <span class="kw">sd</span>(diffmean)))</code></pre></div>
<pre><code>## # A tibble: 1 × 1
##           se
##        &lt;dbl&gt;
## 1 0.03182225</code></pre>
<p>Remembering that we can use the general formula of <span class="math inline">\(statistic \pm (2 * SE)\)</span> we get the following result for plausible values of the difference in population means at the 95% level.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(lower &lt;-<span class="st"> </span>obs_diff -<span class="st"> </span>(<span class="dv">2</span> *<span class="st"> </span>std_err))</code></pre></div>
<pre><code>##          se
## 1 0.7657673</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(upper &lt;-<span class="st"> </span>obs_diff +<span class="st"> </span>(<span class="dv">2</span> *<span class="st"> </span>std_err))</code></pre></div>
<pre><code>##          se
## 1 0.8930563</code></pre>
<p>We can, therefore, say that we are 95% confident that the population mean rating for romance movies is between 0.766 and 0.893 points higher than for that of action movies.</p>
<p>The important thing to check here is whether 0 is contained in the confidence interval. If it is, it is plausible that the difference in the two population means between the two groups is 0. This means that the null hypothesis is plausible. The results of the hypothesis test and the confidence interval should match as they do here. We rejected the null hypothesis with hypothesis testing and we have evidence here than the mean rating for romance movies is higher than for action movies.</p>
</div>
<div id="effect-size" class="section level2">
<h2><span class="header-section-number">B.4</span> Effect size</h2>
<p>The phrase <strong>effect size</strong> has been thrown around recently as an alternative to <span class="math inline">\(p\)</span>-values. In combination with the confidence interval, it can be often more valuable than just looking at the results of a hypothesis test. It depends on the scientific discipline exactly what is meant by “effect size” but, in general, it refers to <em>the magnitude of the difference between group measurements</em>. For our two sample problem involving movies, it is the observed difference in sample means <code>obs_diff</code>.</p>
<p>It’s worthy of mention here that confidence intervals are always centered at the observed statistic. In other words, if you are looking at a confidence interval and someone asks you what the “effect size” is you can simply find the midpoint of the stated confidence interval.</p>
<!--
## Theory-based CIs (Put into lab instead)
-->
<hr />
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC9.26)</strong> Check to see whether the difference in population mean ratings for the two genres falls in the confidence interval we found here. Are we guaranteed that it will fall in the range of plausible values?</p>
<p><strong>(LC9.27)</strong> Why do you think many scientific fields are shifting to preferring inclusion of confidence intervals in articles over just <span class="math inline">\(p\)</span>-values and hypothesis tests?</p>
<p><strong>(LC9.28)</strong> Why is 95% related to a value of 2 in the margin of error? What would approximate values be for 90% and for 99%?</p>
<p><strong>(LC9.29)</strong> Why is a 95% confidence interval wider than a 90% confidence interval? Explain by using a concrete example from everyday life about what is meant by “confidence.”</p>
<p><strong>(LC9.30)</strong> How would confidence intervals correspond to one-sided hypothesis tests?</p>
<p><strong>(LC9.31)</strong> There is a relationship between the significance level and the confidence level. What do you think it is?</p>
<hr />
</div>
<div id="script-of-r-code-4" class="section level2">
<h2><span class="header-section-number">B.5</span> Script of R code</h2>
<p>An R script file of all R code used in this chapter is available <a href="http://ismayc.github.io/moderndiver-book/08-conf_intervals.R">here</a>.</p>
<!--    
## What's to come? 

We will see in Chapter \@ref(regress) many of the same ideas we have seen with hypothesis testing and confidence intervals in the last two chapters.  Regression is frequently associated both correctly and incorrectly with statistics and data analysis, so you'll need to make sure you understand when it is appropriate and when it is not.
-->

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-lock2012">
<p>Lock, Robin, Patti Frazer Lock, Kari Lock Morgan, Eric F. Lock, and Dennis F. Lock. 2012. <em>Statistics: UnLOCKing the Power of Data</em>. Wiley.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="A-appendixA.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="C-appendixC.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ismayc/moderndiver-source/edit/master/92-appendixB.Rmd",
"text": "Edit"
},
"download": ["ismaykim.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
