<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>ModernDive</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="Combining statistical and computational thinking to make sense of data. Getting away from the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown">
  <meta name="generator" content="bookdown 0.3 and GitBook 2.6.7">

  <meta property="og:title" content="ModernDive" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Combining statistical and computational thinking to make sense of data. Getting away from the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown" />
  <meta name="github-repo" content="ismayc/moderndiver-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="ModernDive" />
  
  <meta name="twitter:description" content="Combining statistical and computational thinking to make sense of data. Getting away from the traditional introductory statistics curriculum, more focused on reproducible research, data visualization, and modern data analysis techniques and tools including resampling and bootstrapping using R, RStudio, and R Markdown" />
  

<meta name="author" content="Chester Ismay and Albert Y. Kim">


<meta name="date" content="2017-01-06">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="B-appendixB.html">
<link rel="next" href="D-appendixC.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-0.8/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.4/dygraphs.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89938436-1', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#colophon"><i class="fa fa-check"></i>Colophon</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-intro.html"><a href="2-intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="2-intro.html"><a href="2-intro.html#preamble"><i class="fa fa-check"></i><b>2.1</b> Preamble</a></li>
<li class="chapter" data-level="2.2" data-path="2-intro.html"><a href="2-intro.html#three-driving-data-sources"><i class="fa fa-check"></i><b>2.2</b> Three driving data sources</a></li>
<li class="chapter" data-level="2.3" data-path="2-intro.html"><a href="2-intro.html#datascience-pipeline"><i class="fa fa-check"></i><b>2.3</b> Data/science pipeline</a></li>
<li class="chapter" data-level="2.4" data-path="2-intro.html"><a href="2-intro.html#reproducibility"><i class="fa fa-check"></i><b>2.4</b> Reproducibility</a></li>
<li class="chapter" data-level="2.5" data-path="2-intro.html"><a href="2-intro.html#who-is-this-book-for"><i class="fa fa-check"></i><b>2.5</b> Who is this book for?</a></li>
</ul></li>
<li class="part"><span><b>I Data Exploration</b></span></li>
<li class="chapter" data-level="3" data-path="3-tidy.html"><a href="3-tidy.html"><i class="fa fa-check"></i><b>3</b> Tidy Data</a><ul>
<li class="chapter" data-level="3.1" data-path="3-tidy.html"><a href="3-tidy.html#what-is-tidy-data"><i class="fa fa-check"></i><b>3.1</b> What is tidy data?</a></li>
<li class="chapter" data-level="3.2" data-path="3-tidy.html"><a href="3-tidy.html#the-nycflights13-datasets"><i class="fa fa-check"></i><b>3.2</b> The <code>nycflights13</code> datasets</a></li>
<li class="chapter" data-level="3.3" data-path="3-tidy.html"><a href="3-tidy.html#how-is-flights-tidy"><i class="fa fa-check"></i><b>3.3</b> How is <code>flights</code> tidy?</a></li>
<li class="chapter" data-level="3.4" data-path="3-tidy.html"><a href="3-tidy.html#normal-forms-of-data"><i class="fa fa-check"></i><b>3.4</b> Normal forms of data</a></li>
<li class="chapter" data-level="3.5" data-path="3-tidy.html"><a href="3-tidy.html#whats-to-come"><i class="fa fa-check"></i><b>3.5</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html"><i class="fa fa-check"></i><b>4</b> Data Visualization via <code id="viz">ggplot2</code></a><ul>
<li class="chapter" data-level="4.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#five-named-graphs---the-5ng"><i class="fa fa-check"></i><b>4.1</b> Five Named Graphs - The 5NG</a></li>
<li class="chapter" data-level="4.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#histograms"><i class="fa fa-check"></i><b>4.2</b> Histograms</a><ul>
<li class="chapter" data-level="4.2.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#contsum"><i class="fa fa-check"></i><b>4.2.1</b> Continuous data summaries</a></li>
<li class="chapter" data-level="4.2.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary"><i class="fa fa-check"></i><b>4.2.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#boxplots"><i class="fa fa-check"></i><b>4.3</b> Boxplots</a><ul>
<li class="chapter" data-level="4.3.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#faceting"><i class="fa fa-check"></i><b>4.3.1</b> Faceting</a></li>
<li class="chapter" data-level="4.3.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary-1"><i class="fa fa-check"></i><b>4.3.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#barplots"><i class="fa fa-check"></i><b>4.4</b> Barplots</a><ul>
<li class="chapter" data-level="4.4.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>4.4.1</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="4.4.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#using-barplots-to-compare-two-variables"><i class="fa fa-check"></i><b>4.4.2</b> Using barplots to compare two variables</a></li>
<li class="chapter" data-level="4.4.3" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary-2"><i class="fa fa-check"></i><b>4.4.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#scatter-plots"><i class="fa fa-check"></i><b>4.5</b> Scatter-plots</a><ul>
<li class="chapter" data-level="4.5.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#jittering"><i class="fa fa-check"></i><b>4.5.1</b> Jittering</a></li>
<li class="chapter" data-level="4.5.2" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#setting-transparency"><i class="fa fa-check"></i><b>4.5.2</b> Setting transparency</a></li>
<li class="chapter" data-level="4.5.3" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary-3"><i class="fa fa-check"></i><b>4.5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#line-graphs"><i class="fa fa-check"></i><b>4.6</b> Line-graphs</a><ul>
<li class="chapter" data-level="4.6.1" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#summary-4"><i class="fa fa-check"></i><b>4.6.1</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#brief-review-of-the-grammar-of-graphics"><i class="fa fa-check"></i><b>4.7</b> Brief Review of The Grammar of Graphics</a></li>
<li class="chapter" data-level="4.8" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#script-of-r-code"><i class="fa fa-check"></i><b>4.8</b> Script of R code</a></li>
<li class="chapter" data-level="4.9" data-path="4-data-visualization-via-ggplot2.html"><a href="4-data-visualization-via-ggplot2.html#whats-to-come-1"><i class="fa fa-check"></i><b>4.9</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html"><i class="fa fa-check"></i><b>5</b> Data Manipulation via <code id="manip">dplyr</code></a><ul>
<li class="chapter" data-level="5.1" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#five-main-verbs---the-fmv"><i class="fa fa-check"></i><b>5.1</b> Five Main Verbs - The FMV</a><ul>
<li class="chapter" data-level="5.1.1" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#select-variables-using-select"><i class="fa fa-check"></i><b>5.1.1</b> Select variables using <code id="select">select</code></a></li>
<li class="chapter" data-level="5.1.2" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#filter-observations-using-filter"><i class="fa fa-check"></i><b>5.1.2</b> Filter observations using <code id="filter">filter</code></a></li>
<li class="chapter" data-level="5.1.3" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#summarize-variables-using-summarize"><i class="fa fa-check"></i><b>5.1.3</b> Summarize variables using <code>summarize</code></a></li>
<li class="chapter" data-level="5.1.4" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#create-new-variableschange-old-variables-using-mutate"><i class="fa fa-check"></i><b>5.1.4</b> Create new variables/change old variables using <code>mutate</code></a></li>
<li class="chapter" data-level="5.1.5" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#reorder-the-data-frame-using-arrange"><i class="fa fa-check"></i><b>5.1.5</b> Reorder the data frame using <code id="arrange">arrange</code></a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#the-pipe"><i class="fa fa-check"></i><b>5.2</b> The pipe <code>%&gt;%</code></a></li>
<li class="chapter" data-level="5.3" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#joiningmerging-data-frames"><i class="fa fa-check"></i><b>5.3</b> Joining/merging data frames</a></li>
<li class="chapter" data-level="5.4" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#script-of-r-code-1"><i class="fa fa-check"></i><b>5.4</b> Script of R code</a></li>
<li class="chapter" data-level="5.5" data-path="5-data-manipulation-via-dplyr.html"><a href="5-data-manipulation-via-dplyr.html#whats-to-come-2"><i class="fa fa-check"></i><b>5.5</b> What’s to come?</a></li>
</ul></li>
<li class="part"><span><b>II Inference</b></span></li>
<li class="chapter" data-level="6" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html"><i class="fa fa-check"></i><b>6</b> Simulating Randomness via <code id="sim">mosaic</code></a><ul>
<li class="chapter" data-level="6.1" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#needed-packages"><i class="fa fa-check"></i><b>6.1</b> Needed packages</a></li>
<li class="chapter" data-level="6.2" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#random-sampling"><i class="fa fa-check"></i><b>6.2</b> Random sampling</a><ul>
<li class="chapter" data-level="6.2.1" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#tasting-soup"><i class="fa fa-check"></i><b>6.2.1</b> Tasting soup</a></li>
<li class="chapter" data-level="6.2.2" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#common-terms"><i class="fa fa-check"></i><b>6.2.2</b> Common terms</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#visualizing-sampling"><i class="fa fa-check"></i><b>6.3</b> Visualizing sampling</a><ul>
<li class="chapter" data-level="6.3.1" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#sampling-distribution"><i class="fa fa-check"></i><b>6.3.1</b> Sampling distribution</a></li>
<li class="chapter" data-level="6.3.2" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#repeated-sampling-via-do"><i class="fa fa-check"></i><b>6.3.2</b> Repeated sampling via <code>do</code></a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#simulation"><i class="fa fa-check"></i><b>6.4</b> Simulation</a></li>
<li class="chapter" data-level="6.5" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#review-of-mosaic-simulation-functions"><i class="fa fa-check"></i><b>6.5</b> Review of <code>mosaic</code> simulation functions</a></li>
<li class="chapter" data-level="6.6" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#script-of-r-code-2"><i class="fa fa-check"></i><b>6.6</b> Script of R code</a></li>
<li class="chapter" data-level="6.7" data-path="6-simulating-randomness-via-mosaic.html"><a href="6-simulating-randomness-via-mosaic.html#whats-to-come-3"><i class="fa fa-check"></i><b>6.7</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-hypo.html"><a href="7-hypo.html"><i class="fa fa-check"></i><b>7</b> Hypothesis Testing</a><ul>
<li class="chapter" data-level="7.1" data-path="7-hypo.html"><a href="7-hypo.html#needed-packages-1"><i class="fa fa-check"></i><b>7.1</b> Needed packages</a></li>
<li class="chapter" data-level="7.2" data-path="7-hypo.html"><a href="7-hypo.html#when-inference-is-not-needed"><i class="fa fa-check"></i><b>7.2</b> When Inference Is Not Needed</a></li>
<li class="chapter" data-level="7.3" data-path="7-hypo.html"><a href="7-hypo.html#basics-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.3</b> Basics of Hypothesis Testing</a></li>
<li class="chapter" data-level="7.4" data-path="7-hypo.html"><a href="7-hypo.html#trial"><i class="fa fa-check"></i><b>7.4</b> Criminal trial analogy</a><ul>
<li class="chapter" data-level="7.4.1" data-path="7-hypo.html"><a href="7-hypo.html#two-possible-conclusions"><i class="fa fa-check"></i><b>7.4.1</b> Two possible conclusions</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="7-hypo.html"><a href="7-hypo.html#types-of-errors-in-hypothesis-testing"><i class="fa fa-check"></i><b>7.5</b> Types of Errors in Hypothesis Testing</a><ul>
<li class="chapter" data-level="7.5.1" data-path="7-hypo.html"><a href="7-hypo.html#logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.5.1</b> Logic of Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="7-hypo.html"><a href="7-hypo.html#statistical-significance"><i class="fa fa-check"></i><b>7.6</b> Statistical Significance</a></li>
<li class="chapter" data-level="7.7" data-path="7-hypo.html"><a href="7-hypo.html#example-revisiting-the-lady-tasting-tea"><i class="fa fa-check"></i><b>7.7</b> EXAMPLE: Revisiting the Lady Tasting Tea</a><ul>
<li class="chapter" data-level="7.7.1" data-path="7-hypo.html"><a href="7-hypo.html#data"><i class="fa fa-check"></i><b>7.7.1</b> Data</a></li>
<li class="chapter" data-level="7.7.2" data-path="7-hypo.html"><a href="7-hypo.html#test-statistic-delta"><i class="fa fa-check"></i><b>7.7.2</b> Test Statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="7.7.3" data-path="7-hypo.html"><a href="7-hypo.html#observed-effect-delta"><i class="fa fa-check"></i><b>7.7.3</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="7.7.4" data-path="7-hypo.html"><a href="7-hypo.html#model-of-h_0"><i class="fa fa-check"></i><b>7.7.4</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.7.5" data-path="7-hypo.html"><a href="7-hypo.html#simulated-data"><i class="fa fa-check"></i><b>7.7.5</b> Simulated Data</a></li>
<li class="chapter" data-level="7.7.6" data-path="7-hypo.html"><a href="7-hypo.html#distribution-of-delta-under-h_0"><i class="fa fa-check"></i><b>7.7.6</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.7.7" data-path="7-hypo.html"><a href="7-hypo.html#the-p-value"><i class="fa fa-check"></i><b>7.7.7</b> The p-value</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="7-hypo.html"><a href="7-hypo.html#example-comparing-two-means"><i class="fa fa-check"></i><b>7.8</b> EXAMPLE: Comparing two means</a><ul>
<li class="chapter" data-level="7.8.1" data-path="7-hypo.html"><a href="7-hypo.html#randomizationpermutation"><i class="fa fa-check"></i><b>7.8.1</b> Randomization/Permutation</a></li>
<li class="chapter" data-level="7.8.2" data-path="7-hypo.html"><a href="7-hypo.html#comparing-action-and-romance-movies"><i class="fa fa-check"></i><b>7.8.2</b> Comparing Action and Romance Movies</a></li>
<li class="chapter" data-level="7.8.3" data-path="7-hypo.html"><a href="7-hypo.html#sampling-rightarrow-randomization"><i class="fa fa-check"></i><b>7.8.3</b> Sampling <span class="math inline">\(\rightarrow\)</span> Randomization</a></li>
<li class="chapter" data-level="7.8.4" data-path="7-hypo.html"><a href="7-hypo.html#data-1"><i class="fa fa-check"></i><b>7.8.4</b> Data</a></li>
<li class="chapter" data-level="7.8.5" data-path="7-hypo.html"><a href="7-hypo.html#model-of-h_0-1"><i class="fa fa-check"></i><b>7.8.5</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.8.6" data-path="7-hypo.html"><a href="7-hypo.html#test-statistic-delta-1"><i class="fa fa-check"></i><b>7.8.6</b> Test Statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="7.8.7" data-path="7-hypo.html"><a href="7-hypo.html#observed-effect-delta-1"><i class="fa fa-check"></i><b>7.8.7</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="7.8.8" data-path="7-hypo.html"><a href="7-hypo.html#simulated-data-1"><i class="fa fa-check"></i><b>7.8.8</b> Simulated Data</a></li>
<li class="chapter" data-level="7.8.9" data-path="7-hypo.html"><a href="7-hypo.html#distribution-of-delta-under-h_0-1"><i class="fa fa-check"></i><b>7.8.9</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="7.8.10" data-path="7-hypo.html"><a href="7-hypo.html#the-p-value-1"><i class="fa fa-check"></i><b>7.8.10</b> The p-value</a></li>
<li class="chapter" data-level="7.8.11" data-path="7-hypo.html"><a href="7-hypo.html#summary-5"><i class="fa fa-check"></i><b>7.8.11</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="7-hypo.html"><a href="7-hypo.html#theory-hypo"><i class="fa fa-check"></i><b>7.9</b> Building theory-based methods using computation</a><ul>
<li class="chapter" data-level="7.9.1" data-path="7-hypo.html"><a href="7-hypo.html#example-t-test-for-two-independent-samples"><i class="fa fa-check"></i><b>7.9.1</b> EXAMPLE: <span class="math inline">\(t\)</span>-test for two independent samples</a></li>
<li class="chapter" data-level="7.9.2" data-path="7-hypo.html"><a href="7-hypo.html#conditions-for-t-test"><i class="fa fa-check"></i><b>7.9.2</b> Conditions for t-test</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="7-hypo.html"><a href="7-hypo.html#whats-to-come-4"><i class="fa fa-check"></i><b>7.10</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-ci.html"><a href="8-ci.html"><i class="fa fa-check"></i><b>8</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="8.1" data-path="8-ci.html"><a href="8-ci.html#needed-packages-2"><i class="fa fa-check"></i><b>8.1</b> Needed packages</a></li>
<li class="chapter" data-level="8.2" data-path="8-ci.html"><a href="8-ci.html#bootstrapping"><i class="fa fa-check"></i><b>8.2</b> Bootstrapping</a></li>
<li class="chapter" data-level="8.3" data-path="8-ci.html"><a href="8-ci.html#mean_rating"><i class="fa fa-check"></i><b>8.3</b> mean_rating</a><ul>
<li class="chapter" data-level="8.3.1" data-path="8-ci.html"><a href="8-ci.html#review-of-bootstrapping"><i class="fa fa-check"></i><b>8.3.1</b> Review of Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="8-ci.html"><a href="8-ci.html#relation-to-hypothesis-testing"><i class="fa fa-check"></i><b>8.4</b> Relation to hypothesis testing</a></li>
<li class="chapter" data-level="8.5" data-path="8-ci.html"><a href="8-ci.html#effect-size"><i class="fa fa-check"></i><b>8.5</b> Effect size</a></li>
<li class="chapter" data-level="8.6" data-path="8-ci.html"><a href="8-ci.html#script-of-r-code-3"><i class="fa fa-check"></i><b>8.6</b> Script of R code</a></li>
<li class="chapter" data-level="8.7" data-path="8-ci.html"><a href="8-ci.html#whats-to-come-5"><i class="fa fa-check"></i><b>8.7</b> What’s to come?</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html"><i class="fa fa-check"></i><b>9</b> Regression via <code id="regress">broom</code></a><ul>
<li class="chapter" data-level="9.1" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#needed-packages-3"><i class="fa fa-check"></i><b>9.1</b> Needed packages</a></li>
<li class="chapter" data-level="9.2" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#example-alaskan-airlines-delays"><i class="fa fa-check"></i><b>9.2</b> EXAMPLE: Alaskan Airlines delays</a></li>
<li class="chapter" data-level="9.3" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#correlation"><i class="fa fa-check"></i><b>9.3</b> Correlation</a><ul>
<li class="chapter" data-level="9.3.1" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#correlation-does-not-imply-causation"><i class="fa fa-check"></i><b>9.3.1</b> Correlation does not imply causation</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#linear-regression"><i class="fa fa-check"></i><b>9.4</b> Linear regression</a><ul>
<li class="chapter" data-level="9.4.1" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#understanding-linear-regression-basics"><i class="fa fa-check"></i><b>9.4.1</b> Understanding linear regression basics</a></li>
<li class="chapter" data-level="9.4.2" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#the-equation-of-the-line"><i class="fa fa-check"></i><b>9.4.2</b> The equation of the line</a></li>
<li class="chapter" data-level="9.4.3" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#interpretting-the-slope"><i class="fa fa-check"></i><b>9.4.3</b> Interpretting the slope</a></li>
<li class="chapter" data-level="9.4.4" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#predicting-values"><i class="fa fa-check"></i><b>9.4.4</b> Predicting values</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#inference-for-regression"><i class="fa fa-check"></i><b>9.5</b> Inference for regression</a><ul>
<li class="chapter" data-level="9.5.1" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#data-2"><i class="fa fa-check"></i><b>9.5.1</b> Data</a></li>
<li class="chapter" data-level="9.5.2" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#test-statistic-delta-2"><i class="fa fa-check"></i><b>9.5.2</b> Test Statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="9.5.3" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#observed-effect-delta-2"><i class="fa fa-check"></i><b>9.5.3</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="9.5.4" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#model-of-h_0-2"><i class="fa fa-check"></i><b>9.5.4</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="9.5.5" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#simulated-data-2"><i class="fa fa-check"></i><b>9.5.5</b> Simulated Data</a></li>
<li class="chapter" data-level="9.5.6" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#distribution-of-delta-under-h_0-2"><i class="fa fa-check"></i><b>9.5.6</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="9.5.7" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#the-p-value-2"><i class="fa fa-check"></i><b>9.5.7</b> The p-value</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#resid"><i class="fa fa-check"></i><b>9.6</b> Residual analysis</a></li>
<li class="chapter" data-level="9.7" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#conditions-for-regression"><i class="fa fa-check"></i><b>9.7</b> Conditions for regression</a></li>
<li class="chapter" data-level="9.8" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#script-of-r-code-4"><i class="fa fa-check"></i><b>9.8</b> Script of R code</a></li>
<li class="chapter" data-level="9.9" data-path="9-regression-via-broom.html"><a href="9-regression-via-broom.html#whats-to-come-6"><i class="fa fa-check"></i><b>9.9</b> What’s to come?</a></li>
</ul></li>
<li class="part"><span><b>III Conclusion</b></span></li>
<li class="chapter" data-level="10" data-path="10-effective-data-storytelling.html"><a href="10-effective-data-storytelling.html"><i class="fa fa-check"></i><b>10</b> Effective Data Storytelling</a><ul>
<li class="chapter" data-level="10.1" data-path="10-effective-data-storytelling.html"><a href="10-effective-data-storytelling.html#conclusion"><i class="fa fa-check"></i><b>10.1</b> Concluding Remarks</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="A-appendixA.html"><a href="A-appendixA.html"><i class="fa fa-check"></i><b>A</b> Statistical Background</a><ul>
<li class="chapter" data-level="A.1" data-path="A-appendixA.html"><a href="A-appendixA.html#basic-statistical-terms"><i class="fa fa-check"></i><b>A.1</b> Basic statistical terms</a><ul>
<li class="chapter" data-level="A.1.1" data-path="A-appendixA.html"><a href="A-appendixA.html#mean"><i class="fa fa-check"></i><b>A.1.1</b> Mean</a></li>
<li class="chapter" data-level="A.1.2" data-path="A-appendixA.html"><a href="A-appendixA.html#median"><i class="fa fa-check"></i><b>A.1.2</b> Median</a></li>
<li class="chapter" data-level="A.1.3" data-path="A-appendixA.html"><a href="A-appendixA.html#standard-deviation"><i class="fa fa-check"></i><b>A.1.3</b> Standard deviation</a></li>
<li class="chapter" data-level="A.1.4" data-path="A-appendixA.html"><a href="A-appendixA.html#five-number-summary"><i class="fa fa-check"></i><b>A.1.4</b> Five-number summary</a></li>
<li class="chapter" data-level="A.1.5" data-path="A-appendixA.html"><a href="A-appendixA.html#distribution"><i class="fa fa-check"></i><b>A.1.5</b> Distribution</a></li>
<li class="chapter" data-level="A.1.6" data-path="A-appendixA.html"><a href="A-appendixA.html#outliers"><i class="fa fa-check"></i><b>A.1.6</b> Outliers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="B-appendixB.html"><a href="B-appendixB.html"><i class="fa fa-check"></i><b>B</b> Inference Examples</a><ul>
<li class="chapter" data-level="B.1" data-path="B-appendixB.html"><a href="B-appendixB.html#needed-packages-4"><i class="fa fa-check"></i><b>B.1</b> Needed packages</a></li>
<li class="chapter" data-level="B.2" data-path="B-appendixB.html"><a href="B-appendixB.html#one-mean"><i class="fa fa-check"></i><b>B.2</b> One Mean</a><ul>
<li class="chapter" data-level="B.2.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement"><i class="fa fa-check"></i><b>B.2.1</b> Problem Statement</a></li>
<li class="chapter" data-level="B.2.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses"><i class="fa fa-check"></i><b>B.2.2</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.2.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data"><i class="fa fa-check"></i><b>B.2.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.2.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods"><i class="fa fa-check"></i><b>B.2.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.2.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods"><i class="fa fa-check"></i><b>B.2.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.2.6" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results"><i class="fa fa-check"></i><b>B.2.6</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.3" data-path="B-appendixB.html"><a href="B-appendixB.html#one-proportion"><i class="fa fa-check"></i><b>B.3</b> One Proportion</a><ul>
<li class="chapter" data-level="B.3.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement-1"><i class="fa fa-check"></i><b>B.3.1</b> Problem Statement</a></li>
<li class="chapter" data-level="B.3.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-1"><i class="fa fa-check"></i><b>B.3.2</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.3.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-1"><i class="fa fa-check"></i><b>B.3.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.3.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-1"><i class="fa fa-check"></i><b>B.3.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.3.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-1"><i class="fa fa-check"></i><b>B.3.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.3.6" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-1"><i class="fa fa-check"></i><b>B.3.6</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.4" data-path="B-appendixB.html"><a href="B-appendixB.html#two-proportions"><i class="fa fa-check"></i><b>B.4</b> Two Proportions</a><ul>
<li class="chapter" data-level="B.4.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement-2"><i class="fa fa-check"></i><b>B.4.1</b> Problem Statement</a></li>
<li class="chapter" data-level="B.4.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-2"><i class="fa fa-check"></i><b>B.4.2</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="B.4.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-2"><i class="fa fa-check"></i><b>B.4.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.4.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-2"><i class="fa fa-check"></i><b>B.4.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.4.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-2"><i class="fa fa-check"></i><b>B.4.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.4.6" data-path="B-appendixB.html"><a href="B-appendixB.html#check-conditions-2"><i class="fa fa-check"></i><b>B.4.6</b> Check conditions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="C" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html"><i class="fa fa-check"></i><b>C</b> Test statistic</a><ul>
<li class="chapter" data-level="C.0.1" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#state-conclusion-2"><i class="fa fa-check"></i><b>C.0.1</b> State conclusion</a></li>
<li class="chapter" data-level="C.0.2" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#comparing-results-2"><i class="fa fa-check"></i><b>C.0.2</b> Comparing results</a></li>
<li class="chapter" data-level="C.1" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#two-means-independent-samples"><i class="fa fa-check"></i><b>C.1</b> Two Means (Independent Samples)</a><ul>
<li class="chapter" data-level="C.1.1" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#problem-statement-3"><i class="fa fa-check"></i><b>C.1.1</b> Problem Statement</a></li>
<li class="chapter" data-level="C.1.2" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#competing-hypotheses-3"><i class="fa fa-check"></i><b>C.1.2</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="C.1.3" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#exploring-the-sample-data-3"><i class="fa fa-check"></i><b>C.1.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="C.1.4" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#non-traditional-methods-3"><i class="fa fa-check"></i><b>C.1.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="C.1.5" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#traditional-methods-3"><i class="fa fa-check"></i><b>C.1.5</b> Traditional methods</a></li>
<li class="chapter" data-level="C.1.6" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#test-statistic-3"><i class="fa fa-check"></i><b>C.1.6</b> Test statistic</a></li>
<li class="chapter" data-level="C.1.7" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#compute-p-value-2"><i class="fa fa-check"></i><b>C.1.7</b> Compute <span class="math inline">\(p\)</span>-value</a></li>
<li class="chapter" data-level="C.1.8" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#state-conclusion-3"><i class="fa fa-check"></i><b>C.1.8</b> State conclusion</a></li>
<li class="chapter" data-level="C.1.9" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#comparing-results-3"><i class="fa fa-check"></i><b>C.1.9</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="C.2" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#two-means-paired-samples"><i class="fa fa-check"></i><b>C.2</b> Two Means (Paired Samples)</a><ul>
<li class="chapter" data-level="C.2.1" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#competing-hypotheses-4"><i class="fa fa-check"></i><b>C.2.1</b> Competing Hypotheses</a></li>
<li class="chapter" data-level="C.2.2" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#exploring-the-sample-data-4"><i class="fa fa-check"></i><b>C.2.2</b> Exploring the sample data</a></li>
<li class="chapter" data-level="C.2.3" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#non-traditional-methods-4"><i class="fa fa-check"></i><b>C.2.3</b> Non-traditional methods</a></li>
<li class="chapter" data-level="C.2.4" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#traditional-methods-4"><i class="fa fa-check"></i><b>C.2.4</b> Traditional methods</a></li>
<li class="chapter" data-level="C.2.5" data-path="C-test-statistic-2.html"><a href="C-test-statistic-2.html#comparing-results-4"><i class="fa fa-check"></i><b>C.2.5</b> Comparing results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="D" data-path="D-appendixC.html"><a href="D-appendixC.html"><i class="fa fa-check"></i><b>D</b> Reach for the Starts</a><ul>
<li class="chapter" data-level="D.1" data-path="D-appendixC.html"><a href="D-appendixC.html#sorted-barplots"><i class="fa fa-check"></i><b>D.1</b> Sorted barplots</a></li>
<li class="chapter" data-level="D.2" data-path="D-appendixC.html"><a href="D-appendixC.html#interactive-graphics"><i class="fa fa-check"></i><b>D.2</b> Interactive graphics</a><ul>
<li class="chapter" data-level="D.2.1" data-path="D-appendixC.html"><a href="D-appendixC.html#interactive-line-graphs"><i class="fa fa-check"></i><b>D.2.1</b> Interactive line-graphs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ModernDive</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="test-statistic-2" class="section level1">
<h1><span class="header-section-number">C</span> Test statistic</h1>
<p>The test statistic is a random variable based on the sample data. Here, we are interested in seeing if our observed difference in sample proportions corresponding to no opinion on drilling (<span class="math inline">\(\hat{p}_{college, obs} - \hat{p}_{no\_college, obs}\)</span> = 0.0326481) is statistically different than 0. Assuming that conditions are met and the null hypothesis is true, we can use the standard normal distribution to standardize the difference in sample proportions (<span class="math inline">\(\hat{P}_{college} - \hat{P}_{no\_college}\)</span>) using the standard error of <span class="math inline">\(\hat{P}_{college} - \hat{P}_{no\_college}\)</span> and the pooled estimate:</p>
<p><span class="math display">\[ Z =\dfrac{ (\hat{P}_1 - \hat{P}_2) - 0}{\sqrt{\dfrac{\hat{P}(1 - \hat{P})}{n_1} + \dfrac{\hat{P}(1 - \hat{P})}{n_2} }} \sim N(0, 1) \]</span> where <span class="math inline">\(\hat{P} = \dfrac{\text{total number of successes} }{ \text{total number of cases}}.\)</span></p>
<div id="observed-test-statistic-2" class="section level4">
<h4><span class="header-section-number">C.0.0.1</span> Observed test statistic</h4>
<p>While one could compute this observed test statistic by “hand”, the focus here is on the set-up of the problem and in understanding which formula for the test statistic applies. We can use the <code>prop.test</code> function to perform this analysis for us.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stats::<span class="kw">prop.test</span>(<span class="dt">x =</span> <span class="kw">table</span>(offshore$college_grad, offshore$response),
       <span class="dt">n =</span> <span class="kw">nrow</span>(offshore),
       <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,
       <span class="dt">correct =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions without continuity
##  correction
## 
## data:  table(offshore$college_grad, offshore$response)
## X-squared = 9.9907, df = 1, p-value = 0.001573
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  0.03772522 0.16091078
## sample estimates:
##    prop 1    prop 2 
## 0.3367609 0.2374429</code></pre>
<p><code>prop.test</code> does a <span class="math inline">\(\chi^2\)</span> test here but this matches up exactly with what we would expect from the test statistic above since <span class="math inline">\(Z^2 = \chi^2\)</span> so <span class="math inline">\(\sqrt{9.99} = 3.16 = z_{obs}\)</span>: The <span class="math inline">\(p\)</span>-values are the same because we are focusing on a two-tailed test. The observed difference in sample proportions is 3.16 standard deviations larger than 0.</p>
<p>The <span class="math inline">\(p\)</span>-value—the probability of observing a <span class="math inline">\(Z\)</span> value of 3.16 or more extreme in our null distribution—is 0.0016. This can also be calculated in R directly:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> *<span class="st"> </span><span class="kw">pnorm</span>(<span class="fl">3.16</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## [1] 0.001577691</code></pre>
<p>The 95% confidence interval is also stated above in the <code>prop.test</code> results.</p>
</div>
<div id="state-conclusion-2" class="section level3">
<h3><span class="header-section-number">C.0.1</span> State conclusion</h3>
<p>We, therefore, have sufficient evidence to reject the null hypothesis. Our initial guess that a statistically significant difference did not exist in the proportions of no opinion on offshore drilling between college educated and non-college educated Californians was not validated. We do have evidence to suggest that there is a dependency between college graduation and position on offshore drilling for Californians.</p>
<hr />
</div>
<div id="comparing-results-2" class="section level3">
<h3><span class="header-section-number">C.0.2</span> Comparing results</h3>
<p>Observing the bootstrap distribution and the null distribution that were created, it makes quite a bit of sense that the results are so similar for traditional and non-traditional methods in terms of the <span class="math inline">\(p\)</span>-value and the confidence interval since these distributions look very similar to normal distributions. The conditions were not met since the number of pairs was small, but the sample data was not highly skewed. Using any of the methods whether they are traditional (formula-based) or non-traditional (computational-based) lead to similar results.</p>
<hr />
<hr />
</div>
<div id="two-means-independent-samples" class="section level2">
<h2><span class="header-section-number">C.1</span> Two Means (Independent Samples)</h2>
<div id="problem-statement-3" class="section level3">
<h3><span class="header-section-number">C.1.1</span> Problem Statement</h3>
<p>Average income varies from one region of the country to another, and it often reflects both lifestyles and regional living expenses. Suppose a new graduate is considering a job in two locations, Cleveland, OH and Sacramento, CA, and he wants to see whether the average income in one of these cities is higher than the other. He would like to conduct a hypothesis test based on two randomly selected samples from the 2000 Census. <span class="citation">(Tweaked a bit from Diez, Barr, and Çetinkaya-Rundel <a href="#ref-isrs2014">2014</a> [Chapter 5])</span></p>
</div>
<div id="competing-hypotheses-3" class="section level3">
<h3><span class="header-section-number">C.1.2</span> Competing Hypotheses</h3>
<div id="in-words-3" class="section level4">
<h4><span class="header-section-number">C.1.2.1</span> In words</h4>
<ul>
<li><p>Null hypothesis: There is no association between income and location (Cleveland, OH and Sacramento, CA).</p></li>
<li><p>Alternative hypothesis: There is an association between income and location (Cleveland, OH and Sacramento, CA).</p></li>
</ul>
</div>
<div id="another-way-in-words-1" class="section level4">
<h4><span class="header-section-number">C.1.2.2</span> Another way in words</h4>
<ul>
<li><p>Null hypothesis: The mean income is the <strong>same</strong> for both cities.</p></li>
<li><p>Alternative hypothesis: The mean income is different for the two cities.</p></li>
</ul>
</div>
<div id="in-symbols-with-annotations-3" class="section level4">
<h4><span class="header-section-number">C.1.2.3</span> In symbols (with annotations)</h4>
<ul>
<li><span class="math inline">\(H_0: \mu_{sac} = \mu_{cle}\)</span> or <span class="math inline">\(H_0: \mu_{sac} - \mu_{cle} = 0\)</span>, where <span class="math inline">\(\mu\)</span> represents the average income.</li>
<li><span class="math inline">\(H_A: \mu_{sac} - \mu_{cle} \ne 0\)</span></li>
</ul>
</div>
<div id="set-alpha-3" class="section level4">
<h4><span class="header-section-number">C.1.2.4</span> Set <span class="math inline">\(\alpha\)</span></h4>
<p>It’s important to set the significance level before starting the testing using the data. Let’s set the significance level at 5% here.</p>
</div>
</div>
<div id="exploring-the-sample-data-3" class="section level3">
<h3><span class="header-section-number">C.1.3</span> Exploring the sample data</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">inc_summ &lt;-<span class="st"> </span>cleSac %&gt;%<span class="st"> </span><span class="kw">group_by</span>(metro_area) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">sample_size =</span> <span class="kw">n</span>(),
    <span class="dt">mean =</span> <span class="kw">mean</span>(income),
    <span class="dt">sd =</span> <span class="kw">sd</span>(income),
    <span class="dt">minimum =</span> <span class="kw">min</span>(income),
    <span class="dt">lower_quartile =</span> <span class="kw">quantile</span>(income, <span class="fl">0.25</span>),
    <span class="dt">median =</span> <span class="kw">median</span>(income),
    <span class="dt">upper_quartile =</span> <span class="kw">quantile</span>(income, <span class="fl">0.75</span>),
    <span class="dt">max =</span> <span class="kw">max</span>(income))
<span class="kw">kable</span>(inc_summ)</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">metro_area</th>
<th align="right">sample_size</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">minimum</th>
<th align="right">lower_quartile</th>
<th align="right">median</th>
<th align="right">upper_quartile</th>
<th align="right">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Cleveland_ OH</td>
<td align="right">212</td>
<td align="right">27467.07</td>
<td align="right">27680.68</td>
<td align="right">0</td>
<td align="right">8475</td>
<td align="right">21000</td>
<td align="right">35275</td>
<td align="right">152400</td>
</tr>
<tr class="even">
<td align="left">Sacramento_ CA</td>
<td align="right">175</td>
<td align="right">32427.54</td>
<td align="right">35773.63</td>
<td align="right">0</td>
<td align="right">8050</td>
<td align="right">20000</td>
<td align="right">49350</td>
<td align="right">206900</td>
</tr>
</tbody>
</table>
<p>The boxplot below also shows the mean for each group highlighted by the red dots.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cleSac %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> metro_area, <span class="dt">y =</span> income)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>() +
<span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.y =</span> <span class="st">&quot;mean&quot;</span>, <span class="dt">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/boxplot-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="guess-about-statistical-significance-3" class="section level4">
<h4><span class="header-section-number">C.1.3.1</span> Guess about statistical significance</h4>
<p>We are looking to see if a difference exists in the mean income of the two levels of the explanatory variable. Based solely on the boxplot, we have reason to believe that no difference exists. The distributions of income seem similar and the means fall in roughly the same place.</p>
<hr />
</div>
</div>
<div id="non-traditional-methods-3" class="section level3">
<h3><span class="header-section-number">C.1.4</span> Non-traditional methods</h3>
<div id="collecting-summary-info-1" class="section level4">
<h4><span class="header-section-number">C.1.4.1</span> Collecting summary info</h4>
<p>Next we will assign some key values to variable names in R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">xbar_cle &lt;-<span class="st"> </span>inc_summ$mean[<span class="dv">1</span>]
xbar_sac &lt;-<span class="st"> </span>inc_summ$mean[<span class="dv">2</span>]
obs_diff &lt;-<span class="st"> </span>xbar_sac -<span class="st"> </span>xbar_cle
n_cle &lt;-<span class="st"> </span>inc_summ$sample_size[<span class="dv">1</span>]
n_sac &lt;-<span class="st"> </span>inc_summ$sample_size[<span class="dv">2</span>]</code></pre></div>
</div>
<div id="randomization-for-hypothesis-test-1" class="section level4">
<h4><span class="header-section-number">C.1.4.2</span> Randomization for Hypothesis Test</h4>
<p>In order to look to see if the observed sample mean for Sacramento of 27467.0660377 is statistically different than that for Cleveland of 32427.5428571, we need to account for the sample sizes. Note that this is the same as looking to see if <span class="math inline">\(\bar{x}_{sac} - \bar{x}_{cle}\)</span> is statistically different than 0. We also need to determine a process that replicates how the original group sizes of 212 and 175 were selected.</p>
<p>We can use the idea of <em>randomization testing</em> (also known as <em>permutation testing</em>) to simulate the population from which the sample came (with two groups of different sizes) and then generate samples using <em>shuffling</em> from that simulated population to account for sampling variability.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">2016</span>)
many_shuffles &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span>
<span class="st">  </span>(cleSac %&gt;%
<span class="st">     </span><span class="kw">mutate</span>(<span class="dt">income =</span> <span class="kw">shuffle</span>(income)) %&gt;%<span class="st"> </span>
<span class="st">     </span><span class="kw">group_by</span>(metro_area) %&gt;%
<span class="st">     </span><span class="kw">summarize</span>(<span class="dt">mean_inc =</span> <span class="kw">mean</span>(income))
   )
null_distn &lt;-<span class="st"> </span>many_shuffles %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(.index) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">diffmean =</span> <span class="kw">diff</span>(mean_inc))
null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffmean)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/sim4-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>We can next use this distribution to observe our <span class="math inline">\(p\)</span>-value. Recall this is a two-tailed test so we will be looking for values that are greater than or equal to 4960.4768194 or less than or equal to -4960.4768194 for our <span class="math inline">\(p\)</span>-value.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffmean)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">xintercept =</span> obs_diff) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">xintercept =</span> -obs_diff)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-167-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="calculate-p-value-3" class="section level5">
<h5><span class="header-section-number">C.1.4.2.1</span> Calculate <span class="math inline">\(p\)</span>-value</h5>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pvalue &lt;-<span class="st"> </span>null_distn %&gt;%
<span class="st">  </span><span class="kw">filter</span>( (diffmean &gt;=<span class="st"> </span>obs_diff) |<span class="st"> </span>(diffmean &lt;=<span class="st"> </span>-obs_diff) ) %&gt;%
<span class="st">  </span><span class="kw">nrow</span>() /<span class="st"> </span><span class="kw">nrow</span>(null_distn)
pvalue</code></pre></div>
<pre><code>## [1] 0.1225</code></pre>
<p>So our <span class="math inline">\(p\)</span>-value is 0.1225 and we fail to reject the null hypothesis at the 5% level. You can also see this from the histogram above that we are not very far into the tail of the null distribution.</p>
</div>
</div>
<div id="bootstrapping-for-confidence-interval-3" class="section level4">
<h4><span class="header-section-number">C.1.4.3</span> Bootstrapping for Confidence Interval</h4>
<p>We can also create a confidence interval for the unknown population parameter <span class="math inline">\(\mu_{sac} - \mu_{cle}\)</span> using our sample data with <em>bootstrapping</em>. Here we will bootstrap each of the groups with replacement instead of shuffling. This is done using the <code>groups</code> argument in the <code>resample</code> function to fix the size of each group to be the same as the original group sizes of 175 for Sacramento and 212 for Cleveland.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_means &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *
<span class="st">  </span>cleSac %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">resample</span>(<span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">groups =</span> metro_area) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(metro_area) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_inc =</span> <span class="kw">mean</span>(income))</code></pre></div>
<p>Next, we calculate the difference in sample means for each of the 10,000 replications:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn &lt;-<span class="st"> </span>boot_means %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(.index) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">diffmean =</span> <span class="kw">diff</span>(mean_inc))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diffmean)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-170-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(ci_boot &lt;-<span class="st"> </span>boot_distn %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">lower =</span> <span class="kw">quantile</span>(diffmean, <span class="dt">probs =</span> <span class="fl">0.025</span>),
    <span class="dt">upper =</span> <span class="kw">quantile</span>(diffmean, <span class="dt">probs =</span> <span class="fl">0.975</span>)))</code></pre></div>
<pre><code>## # A tibble: 1 × 2
##      lower    upper
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1 -1512.59 11458.85</code></pre>
<p>We see that 0 is contained in this confidence interval as a plausible value of <span class="math inline">\(\mu_{sac} - \mu_{cle}\)</span> (the unknown population parameter). This matches with our hypothesis test results of failing to reject the null hypothesis. Since zero is a plausible value of the population parameter, we do not have evidence that Sacramento incomes are different than Cleveland incomes.</p>
<p><strong>Interpretation</strong>: We are 95% confident the true mean yearly income for those living in Sacramento is between 1512.59 dollars smaller to 11458.85 dollars higher than for Cleveland.</p>
<p><strong>Note</strong>: You could also use the null distribution based on randomization with a shift to have its center at <span class="math inline">\(\bar{x}_{sac} - \bar{x}_{cle} = \$4960.48\)</span> instead of at 0 and calculate its percentiles. The confidence interval produced via this method should be comparable to the one done using bootstrapping above.</p>
<hr />
</div>
</div>
<div id="traditional-methods-3" class="section level3">
<h3><span class="header-section-number">C.1.5</span> Traditional methods</h3>
<div id="check-conditions-3" class="section level5">
<h5><span class="header-section-number">C.1.5.0.1</span> Check conditions</h5>
<p>Remember that in order to use the short-cut (formula-based, theoretical) approach, we need to check that some conditions are met.</p>
<ol style="list-style-type: decimal">
<li><p><em>Independent observations</em>: The observations are independent in both groups.</p>
<p>This <code>metro_area</code> variable is met since the cases are randomly selected from each city.</p></li>
<li><p><em>Approximately normal</em>: The distribution of the response for each group should be normal or the sample sizes should be at least 30.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cleSac %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> income)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">binwidth =</span> <span class="dv">20000</span>) +
<span class="st">  </span><span class="kw">facet_wrap</span>(~<span class="st"> </span>metro_area)</code></pre></div>
<p><img src="ismaykim_files/figure-html/hist-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>We have some reason to doubt the normality assumption here since both the histograms show deviation from a normal model fitting the data well for each group. The sample sizes for each group are greater than 100 though so the assumptions should still apply.</p></li>
<li><p><em>Independent samples</em>: The samples should be collected without any natural pairing.</p>
<p>There is no mention of there being a relationship between those selected in Cleveland and in Sacramento.</p></li>
</ol>
</div>
</div>
<div id="test-statistic-3" class="section level3">
<h3><span class="header-section-number">C.1.6</span> Test statistic</h3>
<p>The test statistic is a random variable based on the sample data. Here, we are interested in seeing if our observed difference in sample means (<span class="math inline">\(\bar{x}_{sac, obs} - \bar{x}_{cle, obs}\)</span> = 4960.4768194) is statistically different than 0. Assuming that conditions are met and the null hypothesis is true, we can use the <span class="math inline">\(t\)</span> distribution to standardize the difference in sample means (<span class="math inline">\(\bar{X}_{sac} - \bar{X}_{cle}\)</span>) using the approximate standard error of <span class="math inline">\(\bar{X}_{sac} - \bar{X}_{cle}\)</span> (invoking <span class="math inline">\(S_{sac}\)</span> and <span class="math inline">\(S_{cle}\)</span> as estimates of unknown <span class="math inline">\(\sigma_{sac}\)</span> and <span class="math inline">\(\sigma_{cle}\)</span>).</p>
<p><span class="math display">\[ T =\dfrac{ (\bar{X}_1 - \bar{X}_2) - 0}{ \sqrt{\dfrac{S_1^2}{n_1} + \dfrac{S_2^2}{n_2}}  } \sim t (df = min(n_1 - 1, n_2 - 1)) \]</span> where 1 = Sacramento and 2 = Cleveland with <span class="math inline">\(S_1^2\)</span> and <span class="math inline">\(S_2^2\)</span> the sample variance of the incomes of both cities, respectively, and <span class="math inline">\(n_1 = 175\)</span> for Sacramento and <span class="math inline">\(n_2 = 212\)</span> for Cleveland.</p>
<div id="observed-test-statistic-3" class="section level4">
<h4><span class="header-section-number">C.1.6.1</span> Observed test statistic</h4>
<p>Note that we could also do (ALMOST) this test directly using the <code>t.test</code> function. The <code>x</code> and <code>y</code> arguments are expected to both be numeric vectors here so we’ll need to appropriately filter our data sets.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cleveland &lt;-<span class="st"> </span>cleSac %&gt;%<span class="st"> </span><span class="kw">filter</span>(metro_area ==<span class="st"> &quot;Cleveland_ OH&quot;</span>)
sacramento &lt;-<span class="st"> </span>cleSac %&gt;%<span class="st"> </span><span class="kw">filter</span>(metro_area !=<span class="st"> &quot;Cleveland_ OH&quot;</span>)
<span class="kw">t.test</span>(<span class="dt">y =</span> cleveland$income, <span class="dt">x =</span> sacramento$income,
       <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  sacramento$income and cleveland$income
## t = 1.5006, df = 323.36, p-value = 0.1344
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1542.758 11463.712
## sample estimates:
## mean of x mean of y 
##  32427.54  27467.07</code></pre>
<p>Note that the degrees of freedom reported above are different than what we used above in specifying the <strong>Test Statistic</strong>. The degrees of freedom used here is also known as the Satterthwaite approximation and involves a quite complicated formula. For most problems, the must simpler smaller of sample sizes minus one will suffice.</p>
<p>While one could compute this observed test statistic by “hand”, the focus here is on the set-up of the problem and in understanding which formula for the test statistic applies.</p>
<!--
We can use the `inference` function in the `oilabs` package to perform this analysis for us.  Note that to obtain the `F value` given here, you divide the observed $MSG$ value of 17.53 by the observed $MSE$ value of 1.75.  (The use of the word `Residuals` will make more sense when we have covered regression.)
-->
<p>We see here that the observed test statistic value is around -1.5 with <span class="math inline">\(df = min(212 - 1, 175 - 1) = 174\)</span>. Recall that for large degrees of freedom, the <span class="math inline">\(t\)</span> distribution is roughly equal to the standard normal curve so our difference in <code>df</code> for the Satterthwaite and “min” variations doesn’t really matter.</p>
</div>
</div>
<div id="compute-p-value-2" class="section level3">
<h3><span class="header-section-number">C.1.7</span> Compute <span class="math inline">\(p\)</span>-value</h3>
<p>The <span class="math inline">\(p\)</span>-value—the probability of observing an <span class="math inline">\(t_{174}\)</span> value of -1.501 or more extreme (in both directions) in our null distribution—is 0.13. This can also be calculated in R directly:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> *<span class="st"> </span><span class="kw">pt</span>(-<span class="fl">1.501</span>, <span class="dt">df =</span> <span class="kw">min</span>(<span class="dv">212</span> -<span class="st"> </span><span class="dv">1</span>, <span class="dv">175</span> -<span class="st"> </span><span class="dv">1</span>), <span class="dt">lower.tail =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 0.135168</code></pre>
<p>We can also approximate by using the standard normal curve:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> *<span class="st"> </span><span class="kw">pnorm</span>(-<span class="fl">1.501</span>)</code></pre></div>
<pre><code>## [1] 0.1333556</code></pre>
<p>Note that the 95 percent confidence interval given above matches well with the one calculated using bootstrapping.</p>
</div>
<div id="state-conclusion-3" class="section level3">
<h3><span class="header-section-number">C.1.8</span> State conclusion</h3>
<p>We, therefore, do not have sufficient evidence to reject the null hypothesis. Our initial guess that a statistically significant difference not existing in the means was backed by this statistical analysis. We do not have evidence to suggest that the true mean income differs between Cleveland, OH and Sacramento, CA based on this data.</p>
<hr />
</div>
<div id="comparing-results-3" class="section level3">
<h3><span class="header-section-number">C.1.9</span> Comparing results</h3>
<p>Observing the bootstrap distribution and the null distribution that were created, it makes quite a bit of sense that the results are so similar for traditional and non-traditional methods in terms of the <span class="math inline">\(p\)</span>-value and the confidence interval since these distributions look very similar to normal distributions. The conditions also being met leads us to better guess that using any of the methods whether they are traditional (formula-based) or non-traditional (computational-based) will lead to similar results.</p>
<hr />
<hr />
</div>
</div>
<div id="two-means-paired-samples" class="section level2">
<h2><span class="header-section-number">C.2</span> Two Means (Paired Samples)</h2>
<div id="problem-statement-4" class="section level4">
<h4><span class="header-section-number">C.2.0.1</span> Problem Statement</h4>
<p>Trace metals in drinking water affect the flavor and an unusually high concentration can pose a health hazard. Ten pairs of data were taken measuring zinc concentration in bottom water and surface water at 10 randomly selected locations on a stretch of river. Do the data suggest that the true average concentration in the surface water is smaller than that of bottom water? (Note that units are not given.) [Tweaked a bit from <a href="https://onlinecourses.science.psu.edu/stat500/node/51" class="uri">https://onlinecourses.science.psu.edu/stat500/node/51</a>]</p>
</div>
<div id="competing-hypotheses-4" class="section level3">
<h3><span class="header-section-number">C.2.1</span> Competing Hypotheses</h3>
<div id="in-words-4" class="section level4">
<h4><span class="header-section-number">C.2.1.1</span> In words</h4>
<ul>
<li><p>Null hypothesis: The mean concentration in the bottom water is the same as that of the surface water at different paired locations.</p></li>
<li><p>Alternative hypothesis: The mean concentration in the surface water is smaller than that of the bottom water at different paired locations.</p></li>
</ul>
</div>
<div id="in-symbols-with-annotations-4" class="section level4">
<h4><span class="header-section-number">C.2.1.2</span> In symbols (with annotations)</h4>
<ul>
<li><span class="math inline">\(H_0: \mu_{diff} = 0\)</span>, where <span class="math inline">\(\mu_{diff}\)</span> represents the mean difference in concentration for surface water minus bottom water.</li>
<li><span class="math inline">\(H_A: \mu_{diff} &lt; 0\)</span></li>
</ul>
</div>
<div id="set-alpha-4" class="section level4">
<h4><span class="header-section-number">C.2.1.3</span> Set <span class="math inline">\(\alpha\)</span></h4>
<p>It’s important to set the significance level before starting the testing using the data. Let’s set the significance level at 5% here.</p>
</div>
</div>
<div id="exploring-the-sample-data-4" class="section level3">
<h3><span class="header-section-number">C.2.2</span> Exploring the sample data</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">download.file</span>(<span class="st">&quot;http://ismayc.github.io/teaching/sample_problems/zinc_tidy.csv&quot;</span>,
              <span class="dt">destfile =</span> <span class="st">&quot;data/zinc_tidy.csv&quot;</span>,
              <span class="dt">method =</span> <span class="st">&quot;curl&quot;</span>)
zinc_tidy &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/zinc_tidy.csv&quot;</span>)</code></pre></div>
<p>We want to look at the differences in <code>surface - bottom</code> for each location:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">zinc_diff &lt;-<span class="st"> </span>zinc_tidy %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(loc_id) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">pair_diff =</span> <span class="kw">diff</span>(concentration))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">zinc_summ &lt;-<span class="st"> </span>zinc_diff %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">sample_size =</span> <span class="kw">n</span>(),
    <span class="dt">mean =</span> <span class="kw">mean</span>(pair_diff),
    <span class="dt">sd =</span> <span class="kw">sd</span>(pair_diff),
    <span class="dt">minimum =</span> <span class="kw">min</span>(pair_diff),
    <span class="dt">lower_quartile =</span> <span class="kw">quantile</span>(pair_diff, <span class="fl">0.25</span>),
    <span class="dt">median =</span> <span class="kw">median</span>(pair_diff),
    <span class="dt">upper_quartile =</span> <span class="kw">quantile</span>(pair_diff, <span class="fl">0.75</span>),
    <span class="dt">max =</span> <span class="kw">max</span>(pair_diff))
<span class="kw">kable</span>(zinc_summ)</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">sample_size</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">minimum</th>
<th align="right">lower_quartile</th>
<th align="right">median</th>
<th align="right">upper_quartile</th>
<th align="right">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">10</td>
<td align="right">-0.0804</td>
<td align="right">0.0522732</td>
<td align="right">-0.177</td>
<td align="right">-0.11</td>
<td align="right">-0.084</td>
<td align="right">-0.0355</td>
<td align="right">-0.015</td>
</tr>
</tbody>
</table>
<p>The histogram below also shows the distribution of <code>pair_diff</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">zinc_diff %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> pair_diff)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="fl">0.04</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/hist1a-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="guess-about-statistical-significance-4" class="section level4">
<h4><span class="header-section-number">C.2.2.1</span> Guess about statistical significance</h4>
<p>We are looking to see if the sample paired mean difference of -0.0804 is statistically less than 0. They seem to be quite close, but we have a small number of pairs here. Let’s guess that we will fail to reject the null hypothesis.</p>
<hr />
</div>
</div>
<div id="non-traditional-methods-4" class="section level3">
<h3><span class="header-section-number">C.2.3</span> Non-traditional methods</h3>
<div id="collecting-summary-info-2" class="section level4">
<h4><span class="header-section-number">C.2.3.1</span> Collecting summary info</h4>
<p>Next we will assign some key values to variable names in R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">obs_diff &lt;-<span class="st"> </span>zinc_summ$mean
n_pairs &lt;-<span class="st"> </span>zinc_summ$sample_size</code></pre></div>
</div>
<div id="randomization-for-hypothesis-test-2" class="section level4">
<h4><span class="header-section-number">C.2.3.2</span> Randomization for Hypothesis Test</h4>
<p>In order to look to see if the observed sample mean difference <span class="math inline">\(\bar{x}_{diff} = -0.0804\)</span> is statistically less than 0, we need to account for the number of pairs. We also need to determine a process that replicates how the paired data was selected in a way similar to how we calculated our original difference in sample means.</p>
<p>We can use the idea of <em>randomization testing</em> (also known as <em>permutation testing</em>) to simulate the population from which the sample came and then generate samples using <em>shuffling</em> from that simulated population to account for sampling variability. In this case, we will shuffle along each paired location. So values that were on the bottom of location 1 may now be switched to be on the surface or vice versa.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(mosaic)
<span class="kw">set.seed</span>(<span class="dv">2016</span>)
many_shuffles &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span>
<span class="st">  </span>(zinc_tidy %&gt;%
<span class="st">     </span><span class="kw">mutate</span>(<span class="dt">concentration =</span> <span class="kw">shuffle</span>(concentration, <span class="dt">groups =</span> loc_id)) %&gt;%<span class="st"> </span>
<span class="st">     </span><span class="kw">group_by</span>(loc_id) %&gt;%<span class="st"> </span>
<span class="st">     </span><span class="kw">summarize</span>(<span class="dt">pair_diff =</span> <span class="kw">diff</span>(concentration))
   )
null_distn &lt;-<span class="st"> </span>many_shuffles %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(.index) %&gt;%
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_diff =</span> <span class="kw">mean</span>(pair_diff))
null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean_diff)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/sim5-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<p>We can next use this distribution to observe our <span class="math inline">\(p\)</span>-value. Recall this is a left-tailed test so we will be looking for values that are less than or equal to -0.0804 for our <span class="math inline">\(p\)</span>-value.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">null_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean_diff)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">xintercept =</span> obs_diff)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-173-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div id="calculate-p-value-4" class="section level5">
<h5><span class="header-section-number">C.2.3.2.1</span> Calculate <span class="math inline">\(p\)</span>-value</h5>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pvalue &lt;-<span class="st"> </span>null_distn %&gt;%
<span class="st">  </span><span class="kw">filter</span>(mean_diff &lt;=<span class="st"> </span>obs_diff) %&gt;%
<span class="st">  </span><span class="kw">nrow</span>() /<span class="st"> </span><span class="kw">nrow</span>(null_distn)
pvalue</code></pre></div>
<pre><code>## [1] 0.0009</code></pre>
<p>So our <span class="math inline">\(p\)</span>-value is essentially 0.0009 and we reject the null hypothesis at the 5% level. You can also see this from the histogram above that we are far into the left tail of the null distribution.</p>
</div>
</div>
<div id="bootstrapping-for-confidence-interval-4" class="section level4">
<h4><span class="header-section-number">C.2.3.3</span> Bootstrapping for Confidence Interval</h4>
<p>We can also create a confidence interval for the unknown population parameter <span class="math inline">\(\mu_{diff}\)</span> using our sample data (the calculated differences) with <em>bootstrapping</em>. This is similar to the bootstrapping done in a one sample mean case, except now our data is differences instead of raw numerical data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn &lt;-<span class="st"> </span><span class="kw">do</span>(<span class="dv">10000</span>) *<span class="st"> </span>
<span class="st">  </span><span class="kw">resample</span>(zinc_diff, <span class="dt">replace =</span> <span class="ot">TRUE</span>) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_diff =</span> <span class="kw">mean</span>(pair_diff))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_distn %&gt;%<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean_diff)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<p><img src="ismaykim_files/figure-html/unnamed-chunk-175-1.png" width="\textwidth" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(ci_boot &lt;-<span class="st"> </span>boot_distn %&gt;%<span class="st"> </span><span class="kw">summarize</span>(<span class="dt">lower =</span> <span class="kw">quantile</span>(mean_diff, <span class="dt">probs =</span> <span class="fl">0.025</span>),
    <span class="dt">upper =</span> <span class="kw">quantile</span>(mean_diff, <span class="dt">probs =</span> <span class="fl">0.975</span>)))</code></pre></div>
<pre><code>##     lower      upper
## 1 -0.1114 -0.0504975</code></pre>
<p>We see that 0 is not contained in this confidence interval as a plausible value of <span class="math inline">\(\mu_{diff}\)</span> (the unknown population parameter). This matches with our hypothesis test results of rejecting the null hypothesis. Since zero is not a plausible value of the population parameter and since the entire confidence interval falls below zero, we have evidence that surface zinc concentration levels are lower, on average, than bottom level zinc concentrations.</p>
<p><strong>Interpretation</strong>: We are 95% confident the true mean zinc concentration on the surface is between 0.11 units smaller to 0.05 units smaller than on the bottom.</p>
<p><strong>Note</strong>: You could also use the null distribution based on randomization with a shift to have its center at <span class="math inline">\(\bar{x}_{diff} = -0.08\)</span> instead of at 0 and calculate its percentiles. The confidence interval produced via this method should be comparable to the one done using bootstrapping above.</p>
<hr />
</div>
</div>
<div id="traditional-methods-4" class="section level3">
<h3><span class="header-section-number">C.2.4</span> Traditional methods</h3>
<div id="check-conditions-4" class="section level4">
<h4><span class="header-section-number">C.2.4.1</span> Check conditions</h4>
<p>Remember that in order to use the shortcut (formula-based, theoretical) approach, we need to check that some conditions are met.</p>
<ol style="list-style-type: decimal">
<li><em>Independent observations</em>: The observations among pairs are independent.</li>
</ol>
<p>The locations are selected independently through random sampling so this condition is met.</p>
<ol start="2" style="list-style-type: decimal">
<li><p><em>Approximately normal</em>: The distribution of population of differences is normal or the number of pairs is at least 30.</p>
<p>The histogram above does show some skew so we have reason to doubt the population being normal based on this sample. We also only have 10 pairs which is fewer than the 30 needed. A theory-based test may not be valid here.</p></li>
</ol>
</div>
<div id="test-statistic-4" class="section level4">
<h4><span class="header-section-number">C.2.4.2</span> Test statistic</h4>
<p>The test statistic is a random variable based on the sample data. Here, we want to look at a way to estimate the population mean difference <span class="math inline">\(\mu_{diff}\)</span>. A good guess is the sample mean difference <span class="math inline">\(\bar{X}_{diff}\)</span>. Recall that this sample mean is actually a random variable that will vary as different samples are (theoretically, would be) collected. We are looking to see how likely is it for us to have observed a sample mean of <span class="math inline">\(\bar{x}_{diff, obs} = 0.0804\)</span> or larger assuming that the population mean difference is 0 (assuming the null hypothesis is true). If the conditions are met and assuming <span class="math inline">\(H_0\)</span> is true, we can “standardize” this original test statistic of <span class="math inline">\(\bar{X}_{diff}\)</span> into a <span class="math inline">\(T\)</span> statistic that follows a <span class="math inline">\(t\)</span> distribution with degrees of freedom equal to <span class="math inline">\(df = n - 1\)</span>:</p>
<p><span class="math display">\[ T =\dfrac{ \bar{X}_{diff} - 0}{ S_{diff} / \sqrt{n} } \sim t (df = n - 1) \]</span></p>
<p>where <span class="math inline">\(S\)</span> represents the standard deviation of the sample differences and <span class="math inline">\(n\)</span> is the number of pairs.</p>
<div id="observed-test-statistic-4" class="section level5">
<h5><span class="header-section-number">C.2.4.2.1</span> Observed test statistic</h5>
<p>While one could compute this observed test statistic by “hand”, the focus here is on the set-up of the problem and in understanding which formula for the test statistic applies. We can use the <code>t.test</code> function on the differences to perform this analysis for us.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stats::<span class="kw">t.test</span>(<span class="dt">x =</span> zinc_diff$pair_diff, 
       <span class="dt">alternative =</span> <span class="st">&quot;less&quot;</span>,
       <span class="dt">mu =</span> <span class="dv">0</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  zinc_diff$pair_diff
## t = -4.8638, df = 9, p-value = 0.0004456
## alternative hypothesis: true mean is less than 0
## 95 percent confidence interval:
##        -Inf -0.0500982
## sample estimates:
## mean of x 
##   -0.0804</code></pre>
<p>We see here that the <span class="math inline">\(t_{obs}\)</span> value is around -5.</p>
</div>
</div>
<div id="compute-p-value-3" class="section level4">
<h4><span class="header-section-number">C.2.4.3</span> Compute <span class="math inline">\(p\)</span>-value</h4>
<p>The <span class="math inline">\(p\)</span>-value—the probability of observing an <span class="math inline">\(t_{obs}\)</span> value of -5 or less in our null distribution of a <span class="math inline">\(t\)</span> with 9 degrees of freedom—is 0.0004. This can also be calculated in R directly:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pt</span>(-<span class="dv">5</span>, <span class="dt">df =</span> <span class="kw">nrow</span>(zinc_diff) -<span class="st"> </span><span class="dv">1</span>, <span class="dt">lower.tail =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 0.000369484</code></pre>
</div>
<div id="state-conclusion-4" class="section level4">
<h4><span class="header-section-number">C.2.4.4</span> State conclusion</h4>
<p>We, therefore, have sufficient evidence to reject the null hypothesis. Our initial guess that our observed sample mean difference was not statistically less than the hypothesized mean of 0 has been invalidated here. Based on this sample, we have evidence that the mean concentration in the bottom water is greater than that of the surface water at different paired locations.</p>
<hr />
</div>
</div>
<div id="comparing-results-4" class="section level3">
<h3><span class="header-section-number">C.2.5</span> Comparing results</h3>
<p>Observing the bootstrap distribution and the null distribution that were created, it makes quite a bit of sense that the results are so similar for traditional and non-traditional methods in terms of the <span class="math inline">\(p\)</span>-value and the confidence interval since these distributions look very similar to normal distributions. The conditions were not met since the number of pairs was small, but the sample data was not highly skewed. Using any of the methods whether they are traditional (formula-based) or non-traditional (computational-based) lead to similar results.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-isrs2014">
<p>Diez, David M, Christopher D Barr, and Mine Çetinkaya-Rundel. 2014. <em>Introductory Statistics with Randomization and Simulation</em>. First Edition. <a href="https://www.openintro.org/stat/textbook.php?stat_book=isrs" class="uri">https://www.openintro.org/stat/textbook.php?stat_book=isrs</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="B-appendixB.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="D-appendixC.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ismayc/moderndiver-source/edit/master/92-appendixB.Rmd",
"text": "Edit"
},
"download": ["ismaykim.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
